### ISSUE TITLE
How to route Messages

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#10]
Hi,

I just want to write a simple messaging app to test MQTTnet. I want to subscribe 2 or more clients. Client_1 should send to Client_2, Client_2 to Client_3 and Client_3 to Client_1. How do I do this?
Also for logging purposes: How do I log (or write to the console) incoming messages in the Server program?

Server Program:

> var options = new MqttServerOptions
            {
                ConnectionValidator = p =>
                {
                    Console.WriteLine("New");
                    Console.WriteLine(p.ClientId);
                    //if (p.ClientId == "SpecialClient")
                    //{
                      //  if (p.Username != "USER" || p.Password != "PASS")
                        //{
                      //      return MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                       // }
                    //}
                    return MqttConnectReturnCode.ConnectionAccepted;
                }
            };
            var mqttServer = new MqttServerFactory().CreateMqttServer(options);
            mqttServer.Start();
            Console.WriteLine("Press any key to exit.");
            Console.ReadLine();
            mqttServer.Stop();

ClientProgram:

> var options = new MqttClientOptions
            {
                Server = "localhost",
                ClientId = "Client_1"
            };
            var client = new MqttClientFactory().CreateMqttClient(options);
            client.ApplicationMessageReceived += (s, e) =>
            {
                Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
                Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
                Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
                Console.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
                Console.WriteLine();
            };
            client.Connected += async (s,e) =>
            {
                Console.WriteLine("### CONNECTED WITH SERVER ###");
                await client.SubscribeAsync(new List<TopicFilter>
    {
        new TopicFilter("bla1", MqttQualityOfServiceLevel.ExactlyOnce)
    });
                Console.WriteLine("### SUBSCRIBED ###");
            };
            client.Disconnected += async (s, e) =>
            {
                Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                await Task.Delay(TimeSpan.FromSeconds(5));
                try
                {
                    await client.ConnectAsync();
                }
                catch
                {
                    Console.WriteLine("### RECONNECTING FAILED ###");
                }
            };
            try
            {
                client.ConnectAsync();
            }
            catch
            {
                Console.WriteLine("### CONNECTING FAILED ###");
            }
            Console.WriteLine("### WAITING FOR APPLICATION MESSAGES ###");
            while (true)
            {
                Console.ReadLine();
                var applicationMessage = new MqttApplicationMessage(
                    "bla2",
                    Encoding.UTF8.GetBytes("Hello World"),
                    MqttQualityOfServiceLevel.AtLeastOnce,
                    false
                );
                Console.WriteLine("Sending");
                client.PublishAsync(applicationMessage);
            }

Thanks for helping me =)
Best regards, 
Zuendelmeister

**Comment by chkr1011** [comment]
Hi,
your code likes fine so far. For your case you need one server and several clients. So you need a parameter to distinguish the clients in your client code (i.e. parameter).

It is not possible to send a message _directly_ to a special client. You can only publish a message to the server. Depending on the topic several clients can subscribe to that topic. You can build your own patterns based on it. So if you need to send a message to _client1_ you can send them to something like _client/1/messages_ and _client1_ is the only one who has subscribed that topic. For example with _client/1/+_.

Please find more information here: http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices

If you have more questions please let me know.

Best regards
Christian

**Comment by Zuendelmeister** [comment]
Hi @chkr1011,
thanks for your fast response and the link. There are a few things I didn't know yet so it was very helpful. If I understand correctly I should do something like this:
Client_2:

> var applicationMessage = new MqttApplicationMessage(
                    "client/1/messages",
                    Encoding.UTF8.GetBytes("Hello World"),
                    MqttQualityOfServiceLevel.ExactlyOnce,
                    false
                );
                Console.WriteLine("Sending");
                client.PublishAsync(applicationMessage);

And Client_1:

> client.Connected += async (s,e) =>
            {
                Console.WriteLine("### CONNECTED WITH SERVER ###");

                await client.SubscribeAsync(new List<TopicFilter>
    {
        new TopicFilter("client/1/+", MqttQualityOfServiceLevel.ExactlyOnce)
    });

Unfortunately nothing happens. Client_1 doesn't get anything. And to my second question: How can I show in the server that it received a message (for logging purposes)? 
I probably should mention that I deleted the "await" in fron of _client.ConnectAsync();_ and _client.PublishAsync(applicationMessage);_ because with it the client program just dies.

Where did I go wrong?
Thansk again =)

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
You can use the MqttTrace class to attach a handler for general trace and debug messages. But there you will not see the content of the messages etc.
Or do you need something different?

**Comment by Zuendelmeister** [comment]
I was hoping to log all incomming and outgoing messages in the broker program. But if thats not possible I have to live without it. Thanks.

**Comment by chkr1011** [comment]
I can add it if you like. It should be not a huge change. You need the _ApplicationMessages_ and the sending _ClientId_ only? I assume you don't need the low level packages or?

**Comment by Zuendelmeister** [comment]
Gread that would be awsome. 
What I need is the ApplicationMessage, the ClientId, the MqttQualityOfServiceLevel and the topic. The retain information could come in handy too but this is not important.
Thank you =)

**Comment by Zuendelmeister** [comment]
Perfect =)

**Comment by chkr1011** [comment]
Hi, I added this feature to _master_. Please test it and tell me if it fits your needs. It is a new event at the MqttServer available.

**Comment by chkr1011** [comment]
I released a new version. If you need something please let me know (open the ticket).
