### ISSUE TITLE
MQTT Client able to specify multiple TCP server connections

### ISSUE THREAD

**Issue by dereklew** [chkr1011/MQTTnet#1001]
### Describe the feature request
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example. I'm am trying to do [...] but [...]

Currently the WithTcpServer would also allow 1 hostname/IP being specify.  It would be good to support multiple of TCP server.  The same is happening in the C and Java version of MQTT Paho implementation.

### Which project is your feature request related to?

- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

Client

### Describe the solution you'd like

WithTcpServer to support multiple TCP Server,

**Comment by SeppPenner** [comment]
Seems to be a similar request to https://github.com/chkr1011/MQTTnet/issues/983 and https://github.com/chkr1011/MQTTnet/issues/821.

**Comment by chkr1011** [comment]
@dereklew The question is what should happen with those multiple addresses. How are these C and Java versions handling this internally. Do they just try to connect to any of them and if one works they are fine? Or is there more?

The question for is is where such a feature can be placed properly. I don't see such a feature at the regular MqttClient and the LowLevelMqttClient as well. Maybe the ManagedMqttClient can deal with it but on the other hand subscriptions are unique per server. Or are the multiple addresses pointing to the same server? Like some "backup DNS" etc?

In my opinion such a feature is too complex to add it directly to this project. Maybe as an extension which has a new MQTT client (which implements the IMqttApplciationMessageSender etc. interface) but will internally use one client with a list of "possible" connections.

**Comment by dereklew** [comment]
@chkr1011 

Have a look at the Paho MQTT Java implementation.  Similar feature has been incorporated into C implementation too.

https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttConnectOptions.html#setServerURIs-java.lang.String:A-

Basically allows to set an array of URLs.  Tried X times with Y interval for each URL, and if fail, move to the next URL in a round robin manner.

**Comment by chkr1011** [comment]
I don't want to add this feature to this library directly. In my opinion this is quite easy to implement in user code around this library. Maybe someone wants to add an exception library which adds this feature by calling _ConnectAsync_ with a custom rule set over and over.
