### ISSUE TITLE
TLS v1.3 support request

### ISSUE THREAD

**Issue by Dvergatal** [chkr1011/MQTTnet#1003]
Hello,
i was using recently MQTTnet library in our company project and while i was inspecting that TLS connection is working properly with termshark i have discovered that the protocol is in 1.2 version. I tried to force mosquitto to run only on 1.3 but than the connection was being rejected to the client, because of unsupported protocol. After some time of digging i have found that MQTTnet library supports up to 1.2. I tried to change this in the code and had also problems because TLS 1.3 is supported from .NETCore 3.1 and NET5_0. Gladly i have managed to turn on the support for it and the library compiled with success.  The connection was also checked with termshark and it is TLS 1.3 now. Now the question is, how can i contribute this changes to the code? Because we would like to use official libraries in our company's project.

**Comment by JanEggers** [comment]
just create a pull request

**Comment by chkr1011** [comment]
@Dvergatal If you plan to create a pull request please let me know. If not I will add this feature in the future.

**Comment by SeppPenner** [comment]
I agree, this would be a great feature @Dvergatal :)

**Comment by Dvergatal** [comment]
Ok i will do a pull request at the end of week, but i need a moment for this and i was really busy during the last week.
