### ISSUE TITLE
Publish a message from raw binary data, instead of using the MQTT-Message class

### ISSUE THREAD

**Issue by michaelrall** [chkr1011/MQTTnet#1005]
Hello,
for a development project I need to consume various messages that are published by another client, not developed by myself. Because the other client is not easily accessible during development their developers gave me some binary files that represent the MQTT-Messages that are published by them as they are transmitted over the TCP-Wire.

Now I would need to read these files and "stuff" them into the MQTT-Server (directly or via publishing), so that the broker forwards/publishes them as if they were received from another client.

Is there any way to convert my binary data to a Message (I guess the client/server need to have this kind of serializer/deserializer already) or could I access some internal buffer/queue of the MQTT-Server where I could place the binary data.

So what I want to do would be 
```
var data = File.ReadAllBytes("myfile.dat");
await mqttClient.PublishAsync(data, CancellationToken.None);
```

instead of

```
var message = new MqttApplicationMessageBuilder()
    .WithTopic("MyTopic")
    .WithPayload("Hello World")
    .WithExactlyOnceQoS()
    .WithRetainFlag()
    .Build();

await mqttClient.PublishAsync(message, CancellationToken.None);
```

This I only for development/testing purposes, not for production !

kind regards

**Comment by JanEggers** [comment]
why do you want to use an mqtt client to transmit raw data? just use a raw dotnet socket connected to a broker

**Comment by michaelrall** [comment]
oh well, yeah, keep it simple, they say :-), of course that will do the trick.

thanks
