### ISSUE TITLE
How to authorize for REST API in MQTTnet.Server?

### ISSUE THREAD

**Issue by githubjanson** [chkr1011/MQTTnet#1009]
How to authorize for REST API of MQTTnet.Server? 

Sorry for my ignorance, but this server could do with some documentation.

Thanks.

**Comment by chkr1011** [comment]
Hi, the MQTTnet.Server supports custom Python scripts.
The sample file also contains the authorization code for the HTTP requests.
Documentation is required but there is no free time at the moment. But you can add some if you like.

Best regards
Christian

**Comment by githubjanson** [comment]
Ok, thanks. But why is the Swagger endpoint supporting Basic auth when it doesn't work? Or am I missing something here?

**Comment by SeppPenner** [comment]
@githubjanson I guess, that's what https://github.com/chkr1011/MQTTnet/issues/1012 is about? We should discuss this there, I would say.

**Comment by githubjanson** [comment]
@SeppPenner I agree.
