### ISSUE TITLE
Swagger UI not adding Authorization header in MQTTnet.Server

### ISSUE THREAD

**Issue by githubjanson** [chkr1011/MQTTnet#1012]
### Describe the bug
Swagger UI is not adding the Authorization key/value pair to header of REST API requests.

### Which project is your bug related to?
- MQTTnet.Server

### To Reproduce
1. Run MQTTnet.Server-Portable-v3.0.12
2. Open Swagger UI endpoint in  browser
3. Click Authorize and enter some username/password
4. Try to execute some request
5. Curl is not adding Authorization to header

### Expected behavior
That curl creates a request with Authorization to the header

**Comment by SeppPenner** [comment]
@JanEggers I guess, this is a question for you.

**Comment by JanEggers** [comment]
nope MQTTnet.Server is preconfigured by @chkr1011 i dont know how he configured auth

**Comment by chkr1011** [comment]
I am not sure why this does not work. I tried some settings and they are also shown in the authorization menu but they still not working... If anyone knows why please let me know 😄

**Comment by githubjanson** [comment]
Changed the definition of `securityScheme `variable, property `Scheme `to lowercase "basic" and added the `Reference `property definition. Code snippet is part of Startup.cs.
 
```
var securityScheme = new OpenApiSecurityScheme
                {
                    Scheme = "basic",
                    Name = HeaderNames.Authorization,
                    Type = SecuritySchemeType.Http,
                    In = ParameterLocation.Header,
                    Reference = new OpenApiReference
                    {
                        Type = ReferenceType.SecurityScheme,
                        Id = "Swagger"
                    }
                };

c.AddSecurityDefinition("Swagger", securityScheme);
```
After that the authorization is included as part of header. Don't know the intended behavior though, authorization succeeds every time.

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/1a9460776b4d889aa78d0ea10978595f492435e3/Source/MQTTnet.Server/Web/Startup.cs#L152

looks broken to me. @chkr1011 what was your intention?

**Comment by chkr1011** [comment]
@JanEggers Yes this is intentional. When testing things locally there is no security "active". So that you must patch the Python file first by return false and checking the credentials based on your own requirements. Maybe it is a good idea to add a default password but if this is documented there is literally no password 😄

**Comment by chkr1011** [comment]
@githubjanson I added the snipped. Works perfectly 😄

**Comment by githubjanson** [comment]
Ok, great!

**Comment by githubjanson** [comment]
So...are you going to make the change?

**Comment by chkr1011** [comment]
Yes I will do.
