### ISSUE TITLE
User/Password Authentication on broker side

### ISSUE THREAD

**Issue by LouisCPro** [chkr1011/MQTTnet#1018]
### Describe the feature request
I'm trying to implement, as it is available on MOSQUITTO, a way to check for client user and password **authentication** on my MQTT Broker in C#. I do not see anything in **MqttServerOptionsBuilder** related to this capability.

### Which project is your feature request related to?
- MQTTnet.Server

### Describe the solution you'd like
Would it be possible to have a method called **.WithUserAuthentication(string userlogin, string userpassword)** verifiying that the clients are providing the right elements when connecting ?

### Describe alternatives you've considered
I tried to access the underlying socket to validate its authentication prior to the connection is made, but with no luck...

**Comment by SeppPenner** [comment]
You can have a look at https://github.com/chkr1011/MQTTnet/wiki/Examples. The first four should have authentication in the project.

**Comment by LouisCPro** [comment]
Amazing !

Thanks for your help !

**Comment by mindcedeka** [comment]
You can use ValidatingConnectionAsync event to check credentials before accept the connection:

-----server-----
public static class Broker
    {
        static MqttFactory mqttFactory = new MqttFactory();
        static MqttServerOptions mqttServerOptions = new MqttServerOptionsBuilder().WithDefaultEndpoint().Build();  
        static MqttServer mqttServer;
        private static bool enabled = false;
        
        public static async Task<string> initBroker()
        {
            try
            {
                if (!enabled)
                {
                    mqttServer = mqttFactory.CreateMqttServer(mqttServerOptions);
                    mqttServer.ValidatingConnectionAsync += (e) => onConnectedClient(e);
                    await mqttServer.StartAsync();
                    enabled = true;
                    return "Enabled";
                }
                else
                {
                    return "Already enabled";
                }
            }
            catch(Exception e)
            {
                Log.Error(e, "MQTT -> Broker -> initBroker()");
                throw;
            }
        }

        private static Task onConnectedClient(ValidatingConnectionEventArgs e)
        {
            if(e.Password != "pass" || e.Username != "user")
            {
                return Task.FromException(new Exception("User not authorized"));
            }
            return Task.CompletedTask;
        }
}

------client------

static MqttClientOptions mqttClientOptions = new MqttClientOptionsBuilder()
                .WithTcpServer("127.0.0.1")
                .WithCredentials("user","pass")
                .Build();

**Comment by LouisCPro** [comment]
OK,

But Task.FromException is not sufficient apparently.

I had to put before the return 👍 

`
if(e.Password != "pass" || e.Username != "user")
        {
            e.ReasonCode = MQTTnet.Protocol.MqttConnectReasonCode.NotAuthorized;
            return Task.FromException(new Exception("User not authorized"));
        }
`

Instead of what the connection is successful....

Dont really see where Exception is catched there ?

**Comment by LouisCPro** [comment]
@henon Thanks for your feedback !
