### ISSUE TITLE
WithoutAutoReconnect doesn't work in MQTTnet3.0.13

### ISSUE THREAD

**Issue by liaoliaoda** [chkr1011/MQTTnet#1024]
### Describe the bug

I setted WithoutAutoReconnect in MQTTnet3.0.13, but it failed when connect to server. Callback function did not work in OnMqttClientConnected OnMqttClientDisconnected and OnMqttClientConnectingFailed.

It blocked and did not has responded when the program started.

The program can connect to the server normally when remove WithoutAutoReconnect.

Thanks a lot for solving this.

Which project is your bug related to?
1. Client
2. ManagedClient

you can refer to the code below:

```csharp
IManagedMqttClient client = null;
IManagedMqttClientOptions options = new ManagedMqttClientOptionsBuilder()
                    .WithoutAutoReconnect()
                    .WithClientOptions(new MqttClientOptionsBuilder()
                        .WithTcpServer(clientConf.ServerUri, clientConf.Port)
                        .WithCommunicationTimeout(TimeSpan.FromSeconds(DEFAULT_CONNECT_TIMEOUT))
                        .WithCredentials(clientConf.DeviceId, secret)
                        .WithClientId(clientID)
                        .WithKeepAlivePeriod(TimeSpan.FromSeconds(DEFAULT_KEEPLIVE))
                        .WithCleanSession(false)
                        .WithProtocolVersion(MqttProtocolVersion.V311)
                        .Build())
                    .Build();

client.ApplicationMessageProcessedHandler = new ApplicationMessageProcessedHandlerDelegate(new Action<ApplicationMessageProcessedEventArgs>(ApplicationMessageProcessedHandlerMethod)); 

client.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(new Action<MqttApplicationMessageReceivedEventArgs>(MqttApplicationMessageReceived)); 

client.ConnectedHandler = new MqttClientConnectedHandlerDelegate(new Action<MqttClientConnectedEventArgs>(OnMqttClientConnected));

client.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(new Action<MqttClientDisconnectedEventArgs>(OnMqttClientDisconnected)); 

client.ConnectingFailedHandler = new ConnectingFailedHandlerDelegate(new Action<ManagedProcessFailedEventArgs>(OnMqttClientConnectingFailed));

Log.Info("try to connect to server " + clientConf.ServerUri);

client.StartAsync(options);
```

**Comment by chkr1011** [comment]
From by point of view this API makes no sense. Without this being set to true the managed client will do nothing. I assume the managed client got new features all the time which renders this property useless.

I will remove this from the next version.

**Comment by liaoliaoda** [comment]
> From by point of view this API makes no sense. Without this being set to true the managed client will do nothing. I assume the managed client got new features all the time which renders this property useless.
> 
> I will remove this from the next version.

**Comment by liaoliaoda** [comment]
Hi @chkr1011 ,

ok, It will be greate that this option is removed next version and we can disable auto reconnect feature manually.

thanks a lot.

**Comment by chkr1011** [comment]
Closing this issue because it is fixed.

**Comment by luowenhao-github** [comment]
how can i set my mqtt client not auto reconnect when my client is disconneted by the mqtt server,can you show me the code
