### ISSUE TITLE
Can we add .NET Framework 4.5 support?

### ISSUE THREAD

**Issue by lindexi** [chkr1011/MQTTnet#1030]
### Describe the feature request

I find the code can support the .NET Framework 4.5 version. And some of my projects use the  .NET Framework 4.5 and they can not update to  .NET Framework 4.5.2

Can I add .NET Framework 4.5 support?

Thank you

**Comment by SeppPenner** [comment]
This would mean to support an outdated version of the framework: https://dotnet.microsoft.com/download/dotnet-framework...

Or adding support for NetStandard 1.1: https://dotnet.microsoft.com/platform/dotnet-standard or 1.0... I'm not sure if this is a good idea.

**Comment by chkr1011** [comment]
I agree that 4.5 is out of support since several years. 4.5.2 on the other hand is still supported.

One thing we can try is to downgrade from netstandard 1.3 to 1.1 but I don't think this is possible because I already tried that.

**Comment by kkwpsv** [comment]
Many APIs are missing in netstandard 1.1. It's may be impossible to downgrade to netstandard 1.1.
Can we replace net452 to net45 directly? They are almost identical.

**Comment by chkr1011** [comment]
Sorry but for me this is no option. Even 4.5.2 bothers me a little but since it is still officially supported I will keep support for that but 4.5 is way too old.

But you can fork this project and start maintaining a custom 4.5 build (including nuget releases).

**Comment by lindexi** [comment]
@chkr1011 Thank you
