### ISSUE TITLE
MQTTnet Client in Xamarin C# Android Service Widget disconnect by disconnect USB (change network state?)

### ISSUE THREAD

**Issue by LionelJeans** [chkr1011/MQTTnet#1031]
Ge:
Hallo, ich habe ein Android Widget mit einem Service für Android in Visual Studio geschrieben. 
Ich übertrage das Widget per Usb an das Android Smartphone aus dem Visual Studio heraus.
Der Service verbindet sich erfolgreich mit dem MQTTnet Client über TCP auf den Server. Die Verbindung funktioniert problemlos.
Sobald ich die Usb Verbindung trenne, trennt sich der MQTTnet Client. Wiederverbindungen enden immer im disconnect.
Ist das Problem bekannt und gibt es eine Lösung?
Vielen Dank!

Annahme: die Verbindung zum Server besteht zwar über z.B. WLan, beim Trennen vom USB entsteht aber ein NetworkStateChange was auch zum Trennen der MQTTnet Client Verbindung zum mosquitto Server führt.

Server: mosquitto auf Rasp
Client: MQTTnet Version 3.0.11 (Problem tritt bei allen Vorgängerversionen auf)

En:
Hello, I wrote an Android widget with a service for Android in Visual Studio.
I deploy the widget to the Android smartphone via usb.
The service successfully connects to the MQTTnet client via TCP on the server. The connection works fine.
As soon as I disconnect the USB connection, the MQTTnet client disconnects. Reconnection always ends in disconnect.
Is the problem known and is there a solution?
Thank you so much!

Assumption: the connection to the server exists via e.g. WLan, when disconnecting from the USB, however, a NetworkStateChange occurs, which also leads to the disconnection of the MQTTnet client connection to the mosquitto server.

Server: mosquitto auf Rasp
Client: MQTTnet Version 3.0.11 (Problem occurs with all previous versions)

**Comment by chkr1011** [comment]
I don't think that the problem is related to this library. We only use regular sockets and if there is some different behavior I assume it is a Xamarin dedicated issue. I also use the library in a Xamarin App (Android) and cannot reproduce the issue in any way. 
Maybe you have to restart the app if USB is disconnected? Or maybe you need to give the app permissions like 'INTERNET' etc?
