### ISSUE TITLE
"The remote certificate validation callback for Web Sockets is only supported for netstandard 2.1+" on .NET 5.0

### ISSUE THREAD

**Issue by nesherhh** [chkr1011/MQTTnet#1034]
### Describe the bug
IMqttClient.ConnectAsync throws NotSupportedException on .NET Core 3.1 and .NET 5.0 if CertificateValidationHandler is set

### Which project is your bug related to?
- Client
- Generic

### To Reproduce
1. Using this version of MQTTnet '3.0.13'.
2. Run this code '....'.
```csharp
            var factory = new MqttFactory();
            var client = factory.CreateMqttClient();

            var options = new MqttClientOptionsBuilder()
                .WithWebSocketServer("wss://localhost:8383/mqtt")
                .WithTls(parameters =>
                {
                    parameters.UseTls = true;
                    parameters.CertificateValidationHandler = _ => true;
                })
                .Build();

            client.UseConnectedHandler(args => Console.WriteLine(args));
            await client.ConnectAsync(options, CancellationToken.None);
```
3. Throws Exception:
```csharp
System.NotSupportedException: The remote certificate validation callback for Web Sockets is only supported for netstandard 2.1+
   at MQTTnet.Implementations.MqttWebSocketChannel.SetupClientWebSocket(ClientWebSocket clientWebSocket)
   at MQTTnet.Implementations.MqttWebSocketChannel.ConnectAsync(CancellationToken cancellationToken)`
```

### Expected behavior
Code runs without exception

**Comment by chkr1011** [comment]
Mhh it seems I have to check for not supported platforms instead of support ones 😄 I will change that soon.

**Comment by chkr1011** [comment]
Please test with latest RC.

**Comment by simymylooran** [comment]
> Please test with latest RC.

Thanks for the update? Where can we get latest RC build .. Build available in https://www.nuget.org/packages/MQTTnet/ is 11 days old ..

**Comment by chkr1011** [comment]
I just uploaded a new verison.

**Comment by simymylooran** [comment]
> I just uploaded a new version to nuget.

Thank you very much, Christian. The new version is working fine for us ..

**Comment by chkr1011** [comment]
Closing this issue because it is fixed.
