### ISSUE TITLE
[Question/Issue] MQTT Messages is sent to client not in real time

### ISSUE THREAD

**Issue by redradist** [chkr1011/MQTTnet#1035]
By some reason MQTTBroker when it receive message not at the same time send it to local network device ...
Mobile Phone receives it after some delay
It happens with QoS=1 and Retain Flag=true ...
Actually I do not know if it is an issue or I missed to add some options on create ManagedClient or at start of MQTTBroker ?

### Which project is your question related to?
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

**Comment by chkr1011** [comment]
Do you have some kind of storage where retained messages are stored? 
Messages are in queued in general. So there is always some delay but this should be quite small. 
How long is the delay on your phone?

**Comment by chkr1011** [comment]
You should also use the regular client if you need max performance because the managed client also queues on its own. If you need the absolute best performance you should use the low level client (but then you have to deal with all kinds of messages on your own).

**Comment by redradist** [comment]
> Do you have some kind of storage where retained messages are stored?
> Messages are in queued in general. So there is always some delay but this should be quite small.
> How long is the delay on your phone?

@chkr1011 I do not have any storage, it takes near 15-30 seconds in local network ...

**Comment by redradist** [comment]
> You should also use the regular client if you need max performance because the managed client also queues on its own. If you need the absolute best performance you should use the low level client (but then you have to deal with all kinds of messages on your own).

@chkr1011 I do not need the biggest performance, I need to receive messages in reasonable amount of time 5-10 seconds from broker and the same time for sending and receiving

**Comment by redradist** [comment]
@chkr1011 Seems like this issue happens only for Xamarin.Android (

I have tested the same ManagedClient for console app and all works perfectly !!

**Comment by redradist** [comment]
@chkr1011 
Also seems like on Android happens issue:
```console
12-06 23:11:20.764 I/HuaweiWifiWatchdogStateMachine( 1345): PTcp RTT:0, rtt pkt=0, tcp_rx=0, tcp_tx=0, tcp_reTran=0, rtRate=0
12-06 23:11:20.766 I/MQoS    ( 1345): rtt=768,tcp_tx_pkts=547746,tcp_rx_pkts=721776
12-06 23:11:20.771 I/MQoS    ( 1345): QOS_level:4(4),wifi-link;use signalLvl:4;RAT:3G-UMTS
12-06 23:11:20.799 E/mono    (29987): [0x7234dfb4f0] The instruction pointer of the currently executing method(MQTTnet.PacketDispatcher.MqttPacketAwaiter`1/<WaitOneAsync>d__4<TPacket_REF>:MoveNext ()) is not on the recorded stack. This is likely due to a runtime bug. The 1 frames are as follow: 
12-06 23:11:20.800 E/mono    (29987): 	 [0x7234dfb4f0] Frame (0 / 1): System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
12-06 23:11:21.027 I/TrafficMonitor( 1345): update:rxPkts:3,txPkts:4,rxBytes:281,txBytes:160
12-06 23:11:21.027 I/TrafficMonitor( 1345): start expired. level:-1
12-06 23:11:21.027 I/TrafficMonitor( 1345): gettimer:interval=2000
12-06 23:11:22.005 E/WifiHAL (  623): enter wifi_get_link_stats
12-06 23:11:22.019 E/WificondControl( 1345): Noise: -91, Snr: 35, Chload: -1
12-06 23:11:22.020 D/HwInnerWifiManagerImpl( 1345): SupplicantState = COMPLETED
12-06 23:11:22.021 D/HwInnerWifiManagerImpl( 1345): isPhoneAP = false
12-06 23:11:22.023 I/TrafficMonitor( 1345): expired arrive. level:-1
12-06 23:11:22.024 I/TrafficMonitor( 1345): during_ms:2003,period_ms:2000
12-06 23:11:22.024 I/TrafficMonitor( 1345): count:564,rx_sum:3,tx_sum:4,rxBytes:281,during_ms:2003,rx_speed:140.2895656515227,tx_speed:79.8801797304044,rto:0.75
12-06 23:11:22.024 D/WifiScoreReport( 1345): Score = 60, wifiConnectivityManagerEnabled = false, lowScoreCount = 0
--------- beginning of crash
12-06 23:11:22.222 E/AndroidRuntime(29987): FATAL EXCEPTION: FinalizerWatchdogDaemon
12-06 23:11:22.222 E/AndroidRuntime(29987): Process: com.companyname.{App}, PID: 29987
12-06 23:11:22.222 E/AndroidRuntime(29987): java.util.concurrent.TimeoutException: crc644bcdcf6d99873ace.SelfDisposingBitmapDrawable.finalize() timed out after 10 seconds
12-06 23:11:22.222 E/AndroidRuntime(29987): 	at crc644bcdcf6d99873ace.SelfDisposingBitmapDrawable.n_finalize(Native Method)
12-06 23:11:22.222 E/AndroidRuntime(29987): 	at crc644bcdcf6d99873ace.SelfDisposingBitmapDrawable.finalize(SelfDisposingBitmapDrawable.java:85)
12-06 23:11:22.222 E/AndroidRuntime(29987): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
12-06 23:11:22.222 E/AndroidRuntime(29987): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
12-06 23:11:22.222 E/AndroidRuntime(29987): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
12-06 23:11:22.222 E/AndroidRuntime(29987): 	at java.lang.Thread.run(Thread.java:784)
12-06 23:11:22.223 W/        (29987): Thread 0x7264f8a4f0 may have been prematurely finalized
12-06 23:11:22.223 F/        (29987): * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/utils/mono-threads.c:650, condition `info' not met, function:mono_thread_info_current, 
12-06 23:11:22.224 E/JankService(30292): child Thread receive to stop
12-06 23:11:22.225 I/QarthDisFileCreator( 1345): pattern not match
12-06 23:11:22.230 E/iMonitor(  745): FaultDetect: DUMPTOOL_PRINTF return.
12-06 23:11:22.232 F/libc    (29987): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 30001 (FinalizerWatchd), pid 29987 (panyname.{App})
```

Seems like due to this packets not received in time ... (

**Comment by redradist** [comment]
> 
> 
> Thanks for your response. I will close this ticket since the root cause seems to be the Android runtime.

@chkr1011 But I am not sure if it is an issue on Android runtime ... and actually it should work on Xamarin.Android

**Comment by chkr1011** [comment]
The problem is that I have to access to android internals. I just make use of a .net socket and that's it. If there is something different/slow on android, I cannot do much about it.

But I will create a xamarin test app to see if I can reproduce the issue.
