### ISSUE TITLE
ManagedMqttClient loses connection

### ISSUE THREAD

**Issue by tgrtb** [chkr1011/MQTTnet#1038]
### Describe the bug

Using Version 3.0.9

The ManagedMQTTClient sporadically loses connection and does no attempt to reconnect. All it does (from our perspective) is calling the registered IConnectingFailedHandler (once) with belows exception.
To fix this we have to restart the client application.
Note: This is a quite rare event and happens maybe once in a month or two.

### Which project is your bug related to?

- Client
- ManagedClient

### To Reproduce

Unfortunately this happens every now and then without a known pattern

### Expected behavior

The client should try to reconnect until the connection is re-established

### Additional context / logging

Exception passed to the IConnetingFailedHandler:
```batch
MQTTnet.Exceptions.MqttCommunicationException: The operation is not allowed on non-connected sockets. ---> System.IO.IOException: The operation is not allowed on non-connected sockets.
   bei System.Net.Sockets.NetworkStream.InitNetworkStream(Socket socket, FileAccess Access)
   bei System.Net.Sockets.NetworkStream..ctor(Socket socket, Boolean ownsSocket)
   bei MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__15.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MQTTnet.Internal.MqttTaskTimeout.<WaitAsync>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__31.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   bei MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__31.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MQTTnet.Client.MqttClient.<ConnectAsync>d__36.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei MQTTnet.Client.MqttClient.<ConnectAsync>d__36.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<ReconnectIfRequiredAsync>d__62.MoveNext()
```

**Comment by chkr1011** [comment]
Do you use Xamarin or similar? Could you please enable tracing (described in wiki) and post it here? Please let it run for several connection attempts so that I can see what's happening inside.

**Comment by tgrtb** [comment]
No, Xamarin is not used, just plain .Net Standard 2.0/Framework 4.7.2

The tracing logs are already enabled on one of our testing systems. But unfortunately (as mentioned), this may take some weeks to occur again. I'll provide the logs and more info when we have it.

I know this can hardly be answered well, but do you think that an update to a newer version may help, or is it unlikely (from your point of view) that this is a sympton of another bug that you already fixed?
Thanks so far.

**Comment by chkr1011** [comment]
Updating to a newer version might help because I changed some things in the way how the network stream and especially when it is created. So I recommend to try it out.

**Comment by chkr1011** [comment]
I close this because I assume it is fixed.
