### ISSUE TITLE
Messages sent and received, there is quite a long time delay

### ISSUE THREAD

**Issue by bobbyliu58** [chkr1011/MQTTnet#1041]
The current online equipment 1200, probably to send and receive a total of 50 messages per second, now found that there are quite a long time delay, delay one minute or more, from v3.0.13 upgrade to Version 3.0.14 - rc2, or have the same situation, is caused by a backlog of message queue, please? What should I do?
thank you

**Comment by MikePineda** [comment]
Hello @bobbyliu58 , I know this issue is already closed but have you managed to solve this? I'm currently in the same situation

**Comment by bobbyliu58** [comment]
> Hello @bobbyliu58 , I know this issue is already closed but have you managed to solve this? I'm currently in the same situation

Receive data before the position of the asynchronous, problem solving for a while, but found the system with time delay again today.
Peak current situation online equipment 3500, issued a message is 30 times per second, article receives the message seems to be limited to 60 per second.
