### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void MQTTnet.Internal.TaskExtensions.Forget(System.Threading.Tasks.Task, MQTTnet.Diagnostics.IMqttNetScopedLogger)'

### ISSUE THREAD

**Issue by JamesYangLim** [chkr1011/MQTTnet#1042]
### Describe the bug
After I upgraded to 3.0.13, MqttManagedClient failed to start due to System.MissingMethodException: Method not found: 'Void MQTTnet.Internal.TaskExtensions.Forget(System.Threading.Tasks.Task, MQTTnet.Diagnostics.IMqttNetScopedLogger)'. This exception wasn't showing in previous version.

The method name "Forget" has been renamed to "RunInBackground"

https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Internal/TaskExtensions.cs

**Comment by chkr1011** [comment]
Please update all nugets at the same time (MQTTnet and Managed Client extension).

**Comment by JamesYangLim** [comment]
@chkr1011 thank you for your reply. I found the issue. I have another test project that is referencing rc-2 version and when I try to upgrade nuget packages, visual studio says everything is up to date which I thought is the latest stable version. So when I build the solution in the pipeline dotnet automatically uses the latest mqttnet which default to the rc-2 version. After I manually update rc-2 to stable version, everything works.

**Comment by alex13p** [comment]
I'm still seeing this issue

"Method not found: void MQTTnet.Internal.TaskExtensions.Forget(System.Threading.Tasks.Task,MQTTnet.Diagnostics.IMqttNetScopedLogger)"

I'm using nuget packages:
MQTTnet 3.0.14-rc2
MQTTnet.Extensions.ManagedClient 3.0.14-rc1

Both were recently installed so they must be latest versions.

Any ideas?
Thanks

**Comment by chkr1011** [comment]
It turns out that RC2 of managed client was not published to nuget. I will upload it soon.

**Comment by alex13p** [comment]
Morning, Do you have an idea of when RC2 of the managed client will be available? It's put the brakes on something I'm working on
