### ISSUE TITLE
The semaphore has been disposed

### ISSUE THREAD

**Issue by satsuki1202** [chkr1011/MQTTnet#1043]
### Describe the bug
During using MQTTnet Client, we encountered an error "The semaphore has been disposed".

### Which project is your bug related to?
- Client

### To Reproduce
1. Using this version of MQTTnet '3.0.11'.
2. Using .Net Framework version 4.7.1
3. using MQTT server is EMQ  version 2.3.11
4. See error.

### Additional context / logging
```
tm: 2020-12-04T00: 57: 32.721 + 0900 lv: FATAL th: 2 lgr: jp.co.carecom.EasterApplication file: AppBase.cs line: 242 msg: AggregateException.InnerExceptions [System.ObjectDisposedException]: セマフォは破棄されています。
   場所 System.Threading.SemaphoreSlim.CheckDispose ()
   場所 System.Threading.SemaphoreSlim.Release (Int32 releaseCount)
   場所 MQTTnet.Adapter.MqttChannelAdapter. <SendPacketAsync> d__33.MoveNext ()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   場所 MQTTnet.Client.MqttClient. <DisconnectAsync> d__36.MoveNext ()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
   場所 MQTTnet.Client.MqttClient. <DisconnectAsync> d__36.MoveNext ()

```
The message appeared in Japanese because we use .Net Japanese version.
the frequency of occurrences varies from day to day.

**Comment by chkr1011** [comment]
I added some fix in the latest version. Please test with the latest RC version.

**Comment by satsuki1202** [comment]
Thank you for your reply.

I don't know the cause and how to reproduce this issue.
Can you tell me the cause and how to reproduce it?

**Comment by chkr1011** [comment]
It is uploaded to nuget (https://www.nuget.org/packages/MQTTnet/3.0.14-rc3).

The issue comes from the AsyncLock which had a race condition which leads to access to a disposed object. Disposal is now wrapped into a lock so that there is no chance that the disposed semaphore is being accessed at any time (@JanEggers  such errors are the reason for the lock statements).

**Comment by satsuki1202** [comment]
What is the cause of this event?
It doesn't seem to occur at the timing of Publish or Subscribe.

Also, from which version does this problem occur?
I don't think it happened in version 2.8.4.0.

I have verified it with the RC version module I received, but so far no problem has occurred.
We will continue to verify.

**Comment by chkr1011** [comment]
I cannot tell which was the first version with that error. I don't think that 2.8 is affected because the events were not async. So with 3.0.x the bug bug occurs. I will close the ticket for now. If you still encounter problems please reopen the ticket.
