### ISSUE TITLE
Unable to instantiate multiple clients

### ISSUE THREAD

**Issue by Hunter-Rogers** [chkr1011/MQTTnet#1044]
### Describe the feature request
Spinning up many clients for testing (or just as a general architectural decision) is not possible as it is.

### Which project is your feature request related to

- Client
- ManagedClient

### Describe the solution you'd like
Binding to port 0 for the client socket

### Describe alternatives you've considered
Exposing ReuseSocket option out through the options builder

### Additional context
I am perfectly willing to perform the changes myself

**Comment by chkr1011** [comment]
What exception do you get? Having multiple clients should be no problem.

**Comment by Hunter-Rogers** [comment]
If I instantiate 2 clients to the same broker I stop receiving messages.  With one client it's fine.

**Comment by Hunter-Rogers** [comment]
Sorry, the problem was in my test.  Withdrawing.
