### ISSUE TITLE
性能

### ISSUE THREAD

**Issue by yjc2010** [chkr1011/MQTTnet#1047]
封装过深，性能非常差，比其他的API差一个数量级
在16核的笔记本上一秒发布1000个消息时，CPU占到百分之14，接收端占到百分之30

**Comment by chkr1011** [comment]
Please share some code so that we can see where the performance bottleneck comes from.

**Comment by bobbyliu58** [comment]
@yjc2010 你在用这个组件？我现在已经用于生产了，我们可以互相交流一下，你可以给我发邮件45488734@qq.com

**Comment by maikebing** [comment]
如果觉得性能差， 可以找出问题并修复它， 而不是在这里莫名其妙的抱怨。

**Comment by maikebing** [comment]
这里没有人有义务为你优化， 你也没有权利要求别人为你优化！更没有人强迫你必须用 MQTTnet !

**Comment by yjc2010** [comment]
> 这里没有人有义务为你优化， 你也没有权利要求别人为你优化！更没有人强迫你必须用 MQTTnet !

楼主有点情绪化了，好像有失风度。我们做技术的，应该是把精力用在技术，而不是用在情绪上。

**Comment by maikebing** [comment]
那你发扬风度， 拿出数据和代码来发问。 而不是说说而已。

**Comment by yjc2010** [comment]
&nbsp;class Program
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; public class tr_mqtt
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public string ReceiveTime { get; set; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public string SendTime { get; set; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public string Topic { get; set; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public string TotalIndex { get; set; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public string TopicIndex { get; set; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public string Context { get; set; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public string Delay { get; set; }
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; private static bool runState = false;
&nbsp; &nbsp; &nbsp; &nbsp; private static bool running = false;
&nbsp; &nbsp; &nbsp; &nbsp; private static MqttClient mqttClient = null;
&nbsp; &nbsp; &nbsp; &nbsp; private static IMqttClientOptions options = null;
&nbsp; &nbsp; &nbsp; &nbsp; public const string WIND = "/Monitor/Disater/WindUn";
&nbsp; &nbsp; &nbsp; &nbsp; static void Main(string[] args)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; try
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; RunAsync();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Console.ReadLine();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; catch (Exception ex)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Console.WriteLine("启动客户端出现问题:" + ex.ToString());
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; public static async Task RunAsync()
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; try
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var factory = new MqttFactory();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var client = factory.CreateMqttClient();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var clientOptions = new MqttClientOptions
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ChannelOptions = new MqttClientTcpOptions
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Server = "127.0.0.1"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; };


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; client.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(e =&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; try
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //json 反序列化，把这句代码注释掉，几乎没影响，即说明性能与这句无关
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; tr_mqtt msg = JsonSerialHelper.StringToMsg<tr_mqtt&gt;(Encoding.UTF8.GetString(e.ApplicationMessage.Payload));
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; catch (Exception ex)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Console.WriteLine(ex);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; });


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; client.ConnectedHandler = new MqttClientConnectedHandlerDelegate(async e =&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; try
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; List<MqttTopicFilter&gt; listTopic = new List<MqttTopicFilter&gt;();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (listTopic.Count() <= 0)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var topicFilterBulder = new MqttTopicFilterBuilder().WithTopic(WIND).Build();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; listTopic.Add(topicFilterBulder);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await client.SubscribeAsync(listTopic.ToArray());
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; catch (Exception ex)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Console.WriteLine(ex);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; });


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; client.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(async e =&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await Task.Delay(TimeSpan.FromSeconds(5));
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; });


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; try
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await client.ConnectAsync(clientOptions);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; catch (Exception exception)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Console.WriteLine("### CONNECTING FAILED ###" + Environment.NewLine + exception);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; catch (Exception exception)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Console.WriteLine(exception);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bobbyliu"<notifications@github.com&gt;; 
发送时间: 2020年12月15日(星期二) 中午1:35
收件人: "chkr1011/MQTTnet"<MQTTnet@noreply.github.com&gt;; 
抄送: "名字不用太长"<517287199@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [chkr1011/MQTTnet] 性能 (#1047)





 
@yjc2010 你在用这个组件？我现在已经用于生产了，我们可以互相交流一下，你可以给我发邮件45488734@qq.com

**Comment by yjc2010** [comment]
> 那你发扬风度， 拿出数据和代码来发问。 而不是说说而已。

 class Program
    {
        public class tr_mqtt
        {
            public string ReceiveTime { get; set; }
            public string SendTime { get; set; }
            public string Topic { get; set; }
            public string TotalIndex { get; set; }
            public string TopicIndex { get; set; }
            public string Context { get; set; }
            public string Delay { get; set; }
        }

        private static bool runState = false;
        private static bool running = false;
        private static MqttClient mqttClient = null;
        private static IMqttClientOptions options = null;
        public const string WIND = "/Monitor/Disater/WindUn";
        static void Main(string[] args)
        {
            try
            {
                RunAsync();
                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine("启动客户端出现问题:" + ex.ToString());
            }
        }

        public static async Task RunAsync()
        {
            try
            {
                var factory = new MqttFactory();
                var client = factory.CreateMqttClient();
                var clientOptions = new MqttClientOptions
                {
                    ChannelOptions = new MqttClientTcpOptions
                    {
                        Server = "127.0.0.1"
                    }
                };

                client.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(e =>
                {
                    try
                    {
                        //json 反序列化，把这句代码注释掉，几乎没影响，即说明性能与这句无关
                        tr_mqtt msg = JsonSerialHelper.StringToMsg<tr_mqtt>(Encoding.UTF8.GetString(e.ApplicationMessage.Payload));
                      
                    }
                    catch (Exception ex)
                    {

                        Console.WriteLine(ex);
                    }
                });

                client.ConnectedHandler = new MqttClientConnectedHandlerDelegate(async e =>
                {
                    try
                    {
                        List<MqttTopicFilter> listTopic = new List<MqttTopicFilter>();
                        if (listTopic.Count() <= 0)
                        {
                            var topicFilterBulder = new MqttTopicFilterBuilder().WithTopic(WIND).Build();
                          
                            listTopic.Add(topicFilterBulder);
                        }
                        await client.SubscribeAsync(listTopic.ToArray());
                  
                    }
                    catch (Exception ex)
                    {

                        Console.WriteLine(ex);
                    }
                });

                client.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(async e =>
                {
                    await Task.Delay(TimeSpan.FromSeconds(5));
                });

                try
                {
                    await client.ConnectAsync(clientOptions);
                }
                catch (Exception exception)
                {
                    Console.WriteLine("### CONNECTING FAILED ###" + Environment.NewLine + exception);
                }
                
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
            }
        }
    }

**Comment by SeppPenner** [comment]
What actually happened here? 😄

**Comment by chkr1011** [comment]
@SeppPenner I tried to translate this with Google translate 😄 Do me @yjc2010 complains about the performance about this library and that it is too slow compared to other libraries. @maikebing Asked for some code examples because complaining only does not solve the problem. 

@yjc2010 Please try without this line _tr_mqtt msg = JsonSerialHelper.StringToMsg<tr_mqtt>(Encoding.UTF8.GetString(e.ApplicationMessage.Payload));_ The thing is that the client will process the messages in serial which leads to delays when "a lot" is happening in the application message handler. If the order of the incoming messages is not relevant for you, it is also recommended to start a new Task (Task.Run) for every message.

**Comment by yjc2010** [comment]
Thank you very much, the author. You can make time to reply in your busy schedule. About your handle tr_ Mqtt monosodium glutamate= JsonSerialHelper.StringToMsg <tr_ mqtt&gt;( Encoding.UTF8 .GetString(e. ApplicationMessage.Payload ））; this line of code comments, this I also tried to comment out, almost no effect. Therefore, the effect of temporarily guessing to open a new task to process the received message should be negligible. I tried to check the source code, the code is very elegant, but initially think that the package should be too deep, resulting in performance degradation.


I tried to use it https://github.com/ctacke/mqtt The client tried, the performance is very high, and check the source code, the source code is very simple and direct, but the function is not perfect







非常感谢，作者你能在百忙中抽时间来回复。关于你提的 把 Tr_mqtt味精=JsonSerialHelper.StringToMsg<tr_mqtt&gt;(Encoding.UTF8.GetString(e.ApplicationMessage.Payload));这行代码注释，这个我也尝试注释掉了，几乎没任何影响。所以暂时猜测开启新的Task来处理接收到的消息，应该效果甚微。我尝试着查看源码，代码写得非常优雅，但初步认为应该是封装太深，导致性能下降。
我试着使用 https://github.com/ctacke/mqtt&nbsp; 客户端试了下，性能非常高，并查看了下源码，该源码非常简单直接，但功能确实也不完善



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chkr1011/MQTTnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月24日(星期四) 凌晨5:07
收件人:&nbsp;"chkr1011/MQTTnet"<MQTTnet@noreply.github.com&gt;;
抄送:&nbsp;"名字不用太长"<517287199@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [chkr1011/MQTTnet] 性能 (#1047)





 
@SeppPenner I tried to translate this with Google translate 😄 Do me @yjc2010 complains about the performance about this library and that it is too slow compared to other libraries. @maikebing Asked for some code examples because complaining only does not solve the problem.
 
@yjc2010 Please try without this line tr_mqtt msg = JsonSerialHelper.StringToMsg<tr_mqtt&gt;(Encoding.UTF8.GetString(e.ApplicationMessage.Payload)); The thing is that the client will process the messages in serial which leads to delays when "a lot" is happening in the application message handler. If the order of the incoming messages is not relevant for you, it is also recommended to start a new Task (Task.Run) for every message.

**Comment by chkr1011** [comment]
Well this is hard to compare because this library also has some features like support for different protocol versions, full async, web socket transport etc. So it will ever be slower (a bit).

If you want to get the max possible performance please use the _LowLevelClient_ from this library. It has no overhead and you are directly working with raw MQTT packets.

**Comment by yjc2010** [comment]
Thank you very much.
I'll try the LowLevelClient
