### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by 1iveowl** [chkr1011/MQTTnet#105]
... just wanted to say thank you for creating MQTTnet, which have enabled me to create this App, that you might find use full. 

- [Android](https://play.google.com/store/apps/details?id=com.liveowl.mqtttester)
- [Windows](https://www.microsoft.com/en-us/store/p/mqtt-tester/9wzdncrd272c)
- [iOS](https://itunes.apple.com/us/app/mqtt-tester/id1278621826?mt=8)

![180x180](https://user-images.githubusercontent.com/12871120/32702527-d91c7bc2-c7e8-11e7-860b-351c7917ce9f.png)

Also, if it is OK with you I'd like to add credit to MQTTnet in the About page?

**Comment by chkr1011** [comment]
Hi,
thank you. The app looks good. Did you use Xamarin?
Yes please add those information. Also please have a look at the license in GitHub (README). There is the text you shall copy to your app 😄 

Best regards
Christian

**Comment by 1iveowl** [comment]
Yes, it's made with Xamarin.

Sure, I'll look at the license and get that part in order.

**Comment by chkr1011** [comment]
Do you also want to add your app to the README at this project under "refrences"?

**Comment by 1iveowl** [comment]
Sure. I would be honored if you do.

**Comment by chkr1011** [comment]
Then please give me one line (following the scheme of the existing entries) and I will add it.

**Comment by 1iveowl** [comment]
Thanks. 

Please see PR #106
