### ISSUE TITLE
Move Method Documentation from Wiki to Code

### ISSUE THREAD

**Issue by juwens** [chkr1011/MQTTnet#1052]
### Describe the feature request
There is this Wiki page [Server and client method documentation](https://github.com/chkr1011/MQTTnet/wiki/Server-and-client-method-documentation)

Please move that documentation to the matching Methods in the source code.
The benefits:

- the developer can see the comments immediately  in Visual Studio intellisense.
- the current way is cumbersome
  - write code in Visual studio
  - lookup method in wiki
- separate Method documentation is prone of diverging (naming or contentual) from the code.

### Which project is your feature request related to?
- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

### Describe the solution you'd like
Move all of the Method documentation in [Server and client method documentation](https://github.com/chkr1011/MQTTnet/wiki/Server-and-client-method-documentation) directly to the methods in the code.

**Comment by chkr1011** [comment]
@SeppPenner Do you want to do this?

**Comment by SeppPenner** [comment]
Which classes should I document? All the public available methods and properties for the client and server side (and the extensions)?

**Comment by chkr1011** [comment]
In my opinion the most important parts are all builders and the factory. They should be used to compose most things.
And another interesting this are the interfaces of the clients and server (including the extension methods). 
All other things like API which are available but not "visible" to the user (like SessionManager in the server).

And one last thing: We should avoid useless comments. So writing "Gets or sets the host" for the "Host" property has no benefit and can be avoided. Such things do not need any comments (in my opinion). Only some interesting side information like the default port at the Port property has benefits.

**Comment by SeppPenner** [comment]
Ok, I start with the client and add some comments and we can discuss if something is not needed or else here. I will let you know when I have the first things done here.
