### ISSUE TITLE
Are There Plans to Consolidate API for MqttClientOptoinsBuilder's Certificates Property?

### ISSUE THREAD

**Issue by jcisme** [chkr1011/MQTTnet#1057]
### Question
Are there plans to consolidate the API for MqttClientOptionsBuilder with a specific interest in the property Certificates (i.e. byte array for UWP and X509Certificate everywhere else)? We have two reasons for asking:

1. In Windows 10, we've never gotten the byte array to work whereas it works out of the box with X509Certificate.
2. We consume MQTTnet in a utility .NET Standard 2.0 library that is in-turn used by a Xamarin application. The .NET Standard 2.0 library uses the .NET standard MQTTnet assembly at design time, but the Xamarin UWP application uses the UAP MQTTnet assembly at run time. The net result is the following exception:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Void MQTTnet.Client.Options.MqttClientOptionsBuilderTlsParameters.set_Certificates(System.Collections.Generic.IEnumerable`1<System.Security.Cryptography.X509Certificates.X509Certificate>)'.`

Short-term, we've worked around this problem by removing the NuGet package and manually adding the .NET Standard assembly to our Xamarin project. Long-term, we'd prefer using the NuGet package to this manual/error-prone method.

### Product
- MQTT Client (using MQTTnet ver 3.0.13)

**Comment by chkr1011** [comment]
This is not planned yet because some oder UWP platforms have no support for SslStream (even if they compile, they crash on startup). Maybe we can add some more targets to the nuspec so that the .netstandard version is used on newer UWP platforms!?

**Comment by chkr1011** [comment]
I close this due to inactivity. In my opinion this behavior is OK because Xamarin choses the platform which should be used. Probably there is a way to force Xamarin to NOT use UWP for UWP builds but I don't think so. In the end you may need to add a compiler pragma and use UWP APIs from MQTTnet on UWP platforms.
