### ISSUE TITLE
ManagedMqttClient.IsConnected does not swithc to true even when connected

### ISSUE THREAD

**Issue by LouisCPro** [chkr1011/MQTTnet#1058]
When Publishing,

I trid to check IsConnected before proceeding but finally I removed the if(client.IsConnected) as it is always false.

When removing this check (or passing over in debug mode), I do my publishAsync and it returns a success ReasonCode.

Can you advice why ?

Thanks,

**Comment by chkr1011** [comment]
Please try with latest RC from nuget. We changed a couple of things in IsConnected detection.

**Comment by LouisCPro** [comment]
@chkr1011 

I'll have some tests asap ans feedback.

Thanks

**Comment by chkr1011** [comment]
I will close this because I assume that this issue is fixed.

**Comment by LouisCPro** [comment]
Oups ! 

Apologize for the late answer. Yes you can ;)
