### ISSUE TITLE
MQTTnet.Server on .Net4

### ISSUE THREAD

**Issue by zz9pa** [chkr1011/MQTTnet#1060]
Hi,
our project is all based (currently) on .net 4.8, but I cant seem to see how I can compile a .net 4.8 version of the MQTTnet.Server ?

I can see
    .NET Framework 4.5.2+ (x86, x64, AnyCPU) 

in the list of supported frameworks

Is this possible, or is the MQTTnet.Server in the solution only for .net 5 or core ?

Thanks in advance.

**Comment by chkr1011** [comment]
The MQTTnet.Server is a standalone version of MQTTnet server. I is not supposed to compile with any other framework than net5.0. It is released as a single exe file.

**Comment by SeppPenner** [comment]
> The MQTTnet.Server is a standalone version of MQTTnet server. I is not supposed to compile with any other framework than net5.0. It is released as a single exe file.

Well, from the code, this is not completely true, I would say. https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet.Server/MQTTnet.Server.csproj contains `<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>`, so it should compile under NetCore 3.1 as well.

@zz9pa Do you want to run the server under .NET Framework 4.5.2? The client side library should be available (with NetStandard compatible Nuget packages).

**Comment by chkr1011** [comment]
@SeppPenner Yes you are right but this is just a leftover from the .net5.0 upgrade. So my plan is to remove it soon.

**Comment by SeppPenner** [comment]
> @SeppPenner Yes you are right but this is just a leftover from the .net5.0 upgrade. So my plan is to remove it soon.

Makes sense.

**Comment by zz9pa** [comment]
> @zz9pa Do you want to run the server under .NET Framework 4.5.2? The client side library should be available (with NetStandard compatible Nuget packages).

That was my original plan - but only because I wanted everything to be at the same version for simplicity.

If it doesn't work on that version - I'm not missing something obvious - I'll just need to run it at a later .net version..


Thanks everyone.

**Comment by SeppPenner** [comment]
@zz9pa Yeah, it currently runs on NetCore 3.1 and Net5.0 only, but will only run on Net5.0 from a certain point on as @chkr1011 told.
