### ISSUE TITLE
ASP.Net Core TCP TLS not working when hosted in IIS

### ISSUE THREAD

**Issue by agvluca** [chkr1011/MQTTnet#1062]
### Describe your question
I am trying to host an MQTT TCP TLS server inside an ASP.Net Core 3.1 webapplication hosted inside IIS.
This application also host some REST API working just fine.
I am able to achieve this configuration running in debug mode inside Visual Studio: I have both REST API and MQTT broker working just fine.
Once I deploy the application on IIS the REST API are still working but the MQTT broker does not and running ` netstat -noa` shows no one is listening on the configured TCP TLS port.

Here you are my relevant configuration
#### startup

```
services.AddSingleton<MqttService>();
services.AddHostedMqttServerWithServices(options =>
{
    var s = options.ServiceProvider.GetRequiredService<MqttService>();
    s.ConfigureMqttServerOptions(options);
})
.AddMqttConnectionHandler()
.AddConnections()
.AddMqttTcpServerAdapter();
```

#### configure

```
app.UseMqttServer(server => app.ApplicationServices.GetRequiredService<MqttService>().ConfigureMqttServer(server));
```

#### MqttServer
```
 public void ConfigureMqttServerOptions(AspNetMqttServerOptionsBuilder options)
{
  var currentPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
  var certificate = new X509Certificate2(Path.Combine(currentPath, "certs", "certificate.pfx"), "redacted", X509KeyStorageFlags.Exportable);
  
  options.WithoutDefaultEndpoint()
    .WithEncryptedEndpoint()
    .WithEncryptedEndpointPort(8883)
    .WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx))
    .WithEncryptionSslProtocol(System.Security.Authentication.SslProtocols.Tls12);
}
```

I tryed to figure it out by myself using the documentation but with no luck.

Thanks to anyone willing to help, and thank you for this very nice library.

### Which project is your question related to?

- Server

**Comment by agvluca** [comment]
I found out why: if you set the apppool identity to be Network Service then the broker starts listening once the application is started and everything works fine.
Hope it can help someone trying to achieve a similar result.

**Comment by vslzl** [comment]
Hello there, what about the linux side, we have same issue on the ubuntu server. Application is .net core v5.0 web api application with mqttnet. Once we deploy application to our server (nginx as reverse proxy) we cant connect to mqtt broker within the application. Thank you for any help on this issue
