### ISSUE TITLE
Asp dotnet Core 5 + MQTT Websocket Server 

### ISSUE THREAD

**Issue by vikramtamboli** [chkr1011/MQTTnet#1065]
### Describe your question
Does this lib host MQTT Websocket Server in ASP dotnet Core 5

### Which project is your question related to?

- Server

below is sample code i am using i am able to connect to tcp 1883 port  but not sure which port websocket uses

            // This adds a hosted mqtt server to the services
            services.AddHostedMqttServer(builder =>
            {
                builder.WithDefaultEndpointPort(1883);
                builder.WithEncryptedEndpointPort(8883);
            });

            // This adds TCP server support based on System.Net.Socket
            services.AddMqttTcpServerAdapter();

            // This adds websocket support
            services.AddMqttWebSocketServerAdapter();

            services.AddMqttConnectionHandler();

could you please share an example code

**Comment by iliDaedalus** [comment]
Yes it works on net5.0
Examples included in the source.
Check https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet.Server/Web/Startup.cs for correct WebSocket implementation.

**Comment by SeppPenner** [comment]
I have added the link to the wiki as well: https://github.com/chkr1011/MQTTnet/wiki/Server#using-websockets-with-net50
