### ISSUE TITLE
Wrong edge case in MqttTopicFilterComparer

### ISSUE THREAD

**Issue by dagophil** [chkr1011/MQTTnet#1067]
Hello and thank you for this great library.

### Describe the bug
I think there is a wrong edge case in the `MqttTopicFilterComparer`. The topic `a/b/` should match the filter `a/b/#`. However, according to the comparer, it does not.

### Which project is your bug related to?
- Server

### To Reproduce
- Using MQTTnet 3.0.13.
- Call `MqttTopicFilterComparer.IsMatch("a/b/", "a/b/#");`.

### Expected behavior
The function should return `true`, however, it returns `false`.

### Additional context
The topics `a/b` and `a/b/c` are correctly matched to the filter `a/b/#`, it is just the corner case with the empty level `a/b/`. I know that it is not good practice to use empty levels, but according to the MQTT specification, they are valid.

**Comment by chkr1011** [comment]
Yes you are right. This is wrong. I will have a look at it.

**Comment by dagophil** [comment]
Thank you for the quick reply. If you have higher prioritized tasks, I can try to open a PR at the weekend.

**Comment by chkr1011** [comment]
OK sure please create a pull request.
