### ISSUE TITLE
Apply Semantic Versioning with releases

### ISSUE THREAD

**Issue by ramonsmits** [chkr1011/MQTTnet#1069]
### Describe your question

MQTTnet its versioning isn't very useful. When looking the version then recently seem to be incrementing the last digit signifying bugfixes if you would follow semver. This would really help to know if you can blindly update to a newer version:

- patch: drop in replacements (overwrite assembly)
- minor: requires recompile because of type changes but not requiring code changes
- major: requires code changes

Read more on semantic versioning at https://semver.org/

### Which project is your question related to?

- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

**Comment by chkr1011** [comment]
I know semantic versioning but honestly I don't have enough free time to check all changes and make a proper version increment. The current changes are usually very small and not a huge impact. The minor version is incremented but only when there a significant changes. This did not happen in the last month but will happen after the next 1 or 2 releases.

**Comment by chkr1011** [comment]
I will close this ticket because applying the versioning is an ongoing task.
