### ISSUE TITLE
Client disconnection occurs on debugging the application  

### ISSUE THREAD

**Issue by akhtarusafzai** [chkr1011/MQTTnet#1072]
I ma new to .net as well as MQTTnet. I am using the following client options for an IMqttClient, it connects to my AWS endpoint but the connection resets when I try to debug the application
`var clientOptions = new MqttClientOptionsBuilder()
                    .WithTcpServer(IoTEndPoint, Port)
                    .WithTls(new MqttClientOptionsBuilderTlsParameters
                    {
                        UseTls = true,
                        Certificates = certs
                    })
                    .Build();`

Any solution to this will be highly appreciated

**Comment by SeppPenner** [comment]
Have you seen https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws and looked at it?

**Comment by akhtarusafzai** [comment]
> Have you seen https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws and looked at it?

Yes I have, But I am not using websockets, I am connecting to the endpoint with certificates. I am able to connect and do basic pub sub in a go, but the client disconnects after some time interval. I noticed it while debugging my application. There is no issue with either the library or the way I am using it. I think there is some time span which is unknown to me which disconnects the client after some time

**Comment by akhtarusafzai** [comment]
although it works well with the subscribe, I am publishing messages which are taken from an API, now when I debug the process on publish event, it says disconnected and then reconnects with the disconnection handler. Is it something by default or I am missing something

**Comment by akhtarusafzai** [comment]
The solution is there, I solved it with giving .WithKeepAlivePeriod(new TimeSpan(0, 0, 0, 0, Timeout.Infinite)) to the client options

**Comment by SeppPenner** [comment]
> 
> 
> The solution is there, I solved it with giving .WithKeepAlivePeriod(new TimeSpan(0, 0, 0, 0, Timeout.Infinite)) to the client options

Sounds a bit strange, but glad that you found it :)
