### ISSUE TITLE
Sparkplug?

### ISSUE THREAD

**Issue by jgmdavies** [chkr1011/MQTTnet#1073]
Hi folks,

I haven't seen many mentions of Sparkplug here - does this project fit well with Sparkplug?  I note that it supports MQTT 3.1.1.

And also, is there an open-source or free C# library that implements Sparkplug?

Many thanks,
Jim

**Comment by SeppPenner** [comment]
This is a question to be answered by @chkr1011, but I guess that Sparkplug is not supported.

**Comment by chkr1011** [comment]
@jgmdavies Never heard of Sparkplug. 
From what I read it is just a protocol or convention on top of MQTT?

**Comment by SeppPenner** [comment]
@chkr1011 Take a look at this article, please: https://www.hivemq.com/blog/mqtt-sparkplug-essentials-part-1-introduction/.

> With Sparkplug, all participants settle on a common data format, how to receive specific data, how to publish their data, and how data can be interpreted.

So, I guess, it's "just" a data format specification on top of MQTT?

> **Requirements for Sparkplug**

> In order to use Sparkplug, you need an MQTT broker that is responsible for distributing the data. It is important that the MQTT broker implements 100% of the MQTT 3.1.1 specification since Sparkplug requires the following:

> * QoS 0 and 1
> * Retained Messages
> * Last Will and Testament
> * A flexible security system

Also, https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf might be interesting.

If you ask me, MQTTnet does fulfill the specifications despite you have to write your own authentication system based on the `WithConnectionValidator` validator (Check https://github.com/chkr1011/MQTTnet/wiki/Server#validating-mqtt-clients).

**Comment by jgmdavies** [comment]
Thanks all - much appreciated.

Hive are extolling Sparkplug's virtues in various ways, e.g. `(https://www.hivemq.com/tags/mqtt-sparkplug-essentials/)`, and I was hoping to find a nice easy C# route!

**Comment by chkr1011** [comment]
@SeppPenner Ah interesting. Thanks for creating the summary 👍

**Comment by SeppPenner** [comment]
@jgmdavies Since you seem to be a bit more experienced with the topic. Is the Eclipse Standard (SparkPlug 2.2) still the latest?

**Comment by jgmdavies** [comment]
@SeppPenner 
Well, no actual experience (yet)!
As far as I can see, yes, the latest is 2.2 - e.g. from [Eclipse Tahu](https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf) .
The [Opto 22 company](http://www.opto22.com) seem quite active, and they have an interesting PDF dated 2020/21 which also refers to 2.2 in [Sparkplug B](https://documents.opto22.com/2357_Industrial_Strength_MQTT_Sparkplug_B.pdf) .
Jim

**Comment by SeppPenner** [comment]
I guess, we can close this. I'm trying to build a Sparkplug implementation here: https://github.com/SeppPenner/SparkplugNet.

@jgmdavies Don't expect too much yet, it isn't done. Would be great if you give me your ideas once it's at least a bit stable :D
