### ISSUE TITLE
What do I need to post on a topic?

### ISSUE THREAD

**Issue by ascazzola** [chkr1011/MQTTnet#108]
I have a server working 

This is the start method

        public void Start()
        {
            _mqttServer = new MqttFactory().CreateMqttServer(options =>
            {
                options.ConnectionValidator = c =>
                {
                    if (c.ClientId.Length != 12)
                    {
                        return MqttConnectReturnCode.ConnectionRefusedIdentifierRejected;
                    }

                    if (c.Username != appConfiguration.MqttConfig.UserName)
                    {
                        return MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                    }

                    if (c.Password != appConfiguration.MqttConfig.Password)
                    {
                        return MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                    }

                    return MqttConnectReturnCode.ConnectionAccepted;
                };

            });
            _mqttServer.StartAsync();

            _mqttServer.ClientDisconnected += MqttServerOnClientDisconnected;
            _mqttServer.ClientConnected += MqttServerOnClientConnected;
            Logger.Info("MqttService started");
        }

and i have a public method 

        public void SendMessage(string text, string clientId)
        {
                var message = new MqttApplicationMessageBuilder()
                    .WithTopic(clientId)
                    .WithPayload(Encoding.ASCII.GetBytes(text))
                    .WithExactlyOnceQoS()
                    .WithRetainFlag()
                    .Build();
                _mqttServer.Publish(new[] {message});
        }

and i configured a client in MQTTlens, i can connect and suscribe to the same topic as the id (for example 123456789012) but if i send a message from the server using the method "Send message" i do not see it in the client.

What is missing?

Thank you very much

**Comment by JanEggers** [comment]
you have to subscribe to the topic you want to receive msgs for. in your case 123456789012

**Comment by ascazzola** [comment]
The device is suscribed to the topic if y send a message from another device (MQTTlens) y see it but if y send messages from the server i don't see anything

**Comment by JanEggers** [comment]
hmm do you subscribe with qos  exacly once? if you subscribe with lower qos the message will not be send.

**Comment by ascazzola** [comment]
I changed it but i do not see any change
![image](https://user-images.githubusercontent.com/22962158/32741178-1aeab212-c884-11e7-8484-13c1099fa239.png)

and other strange issue _mqttServer.GetConnectedClients() returns always 0

**Comment by JanEggers** [comment]
can you please add logstatements to your clientvalidation callback just to verify the clients are accepted?

**Comment by ascazzola** [comment]
The clients accept the connection, i am debugging it. And i found where is the issue. i commented this line of code

_mqttServer.ClientDisconnected += MqttServerOnClientDisconnected

and it's works fine..

I emptied the ClientDisconnected function but it does not work
here is my ClientDisconnected function 

 private void MqttServerOnClientConnected(object sender, MqttClientConnectedEventArgs mqttClientConnectedEventArgs)
        {
        }

**Comment by ascazzola** [comment]
"hmm do you subscribe with qos exacly once? if you subscribe with lower qos the message will not be send." this is the solution. Now in MQTTlens  i deleted the suscription i created again and it's works.

Thank you very much for your help and apologies for the inconveniencie
