### ISSUE TITLE
ManagedClient 3.0.14 file not found

### ISSUE THREAD

**Issue by pigwing** [chkr1011/MQTTnet#1080]
### Which project is your bug related to?

- ManagedClient

### To Reproduce
System.IO.FileNotFoundException: Could not load file or assembly 'MQTTnet.Extensions.ManagedClient, Version=3.0.14.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'. The system cannot find the file specified

```

**Comment by pigwing** [comment]
![Snipaste_2021-02-04_14-47-39](https://user-images.githubusercontent.com/8393545/106855504-f9de9000-66f7-11eb-8965-36a4ec6d9ee3.png)
file version is 1.0.0.0

**Comment by janzenisek** [comment]
I'm currently struggling with the same issue. It seems that only for Net5.0 the version of the generated dll is configured wrong (1.0.0.0 instead of 3.0.14.0). The dlls for other runtimes are fine.

**Comment by pigwing** [comment]
@janzenisek me too

**Comment by chkr1011** [comment]
It turns out that the build script was not properly updated for .net 5.0. I changed this. Please test RC1 of 3.0.15. @JanEggers Please let me know if the settings are fine for the ASP.NET parts.

**Comment by chkr1011** [comment]
This should be done with 3.0.15-rc2.

**Comment by elektromntr** [comment]
Same issue here. With .NET Core 3.1
