### ISSUE TITLE
Message routing best practices

### ISSUE THREAD

**Issue by hmihail** [chkr1011/MQTTnet#1081]
### Describe your question
I have a client which will subscribe to many topics (like 10-15 topics). Each topic handles a different kind of JSON, so it has to be deserialized differently. The message for each topic is handled by a different method, so it has to be sent to its designated method for handling.

What would be the best approach for handling those messages, besides a big switch statement?

### Which project is your question related to?

- Client
- ManagedClient

**Comment by JanEggers** [comment]
I tend to use a dictionary lookup from topic to messagetype and after deserializing I use https://github.com/jbogard/MediatR to handle the messages

**Comment by JanEggers** [comment]
I was also experimenting with signalr like dispatching adapter but mqtt does not really map well to the signalr protocol.

**Comment by chkr1011** [comment]
I will close this ticket because I assume that the question is properly answered.
