### ISSUE TITLE
Failed to connect to mqtt broker (Mosquitto) in version 3.0.14 

### ISSUE THREAD

**Issue by nrudkovskiy** [chkr1011/MQTTnet#1085]
Hi!
When trying to connect to a broker with parameters in version 3.0.14:
  **var mqttClientOptions = new MqttClientOptionsBuilder()
      .WithClientId(clientId)
      .WithTcpServer(brokerUri, (int)brokerPort)
      .WithCredentials(login, password)
      .WithTls(new MqttClientOptionsBuilderTlsParameters
      {
          UseTls = true,
          AllowUntrustedCertificates = true,
      })
      .WithCleanSession()
      .WithWillMessage(lastWillmessageBuilder.Build())
      .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311)
      .Build();**
connection failed!
In version 3.0.13 all OK.

**Comment by chkr1011** [comment]
Please share the exception or MQTTnet trace so that we have a chance to identify the root cause.

**Comment by rbliznets** [comment]
I have the same issue. It's working only if `SslProtocol = System.Security.Authentication.SslProtocols.Tls12` and `tls_version tlsv1.2` in mosquito conf.

**Comment by chkr1011** [comment]
@rbliznets Are you probably using .net 5.0? When I am not wrong they removed support for TLS < 1.2 due to security reasons.

**Comment by rbliznets** [comment]
Yes. .net 5.0

**Comment by chkr1011** [comment]
OK then I assume that this is the reason. If you need older TLS you may need to create a .netstandard project in your project which wraps the MQTTnet lib (simple factory only) so that you get the deprecated stuff back.

**Comment by SeppPenner** [comment]
This can be solved (as already stated) by using the following snippet:

```csharp
var options = new MqttClientOptionsBuilder()
    .WithClientId("ClientId")
    .WithTcpServer("mybroker.com", 8883)
    .WithCredentials("Username", "Password")
    .WithTls(new MqttClientOptionsBuilderTlsParameters()
    {
        UseTls = true,
        SslProtocol = SslProtocols.Tls12
    })
    .WithCleanSession()
    .Build();
var factory = new MqttFactory();
var mqttClient = factory.CreateMqttClient();
await mqttClient.ConnectAsync(options);
```

It's already in the wiki under https://github.com/chkr1011/MQTTnet/wiki/Client#tls-using-a-client-certificate (Even if the topic is slightly different).

As @chkr1011 said, if you need support for TLS1.1, you need to build your own wrapper library for that.
