### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream

### ISSUE THREAD

**Issue by akhtarusafzai** [chkr1011/MQTTnet#1087]
I am using mqttnet to connect with aws mqtt broker with TLS using certificates. It runs quite good on my windows environment but when I try running it on a Linux environment it throws an exception "Authentication failed because the remote party has closed the transport stream". 

**What I have tried**
I found that with adding the security protocol type, resolves this issue

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11;`

I have tried the above in every possible way enabling TLS versions 1.1, 1.2 and 1.3 but it does nothing.

I am using .netcore 3.1

Any help?

**Comment by akhtarusafzai** [comment]
@chkr1011 Can you look into this?

**Comment by akhtarusafzai** [comment]
@SeppPenner ?

**Comment by SeppPenner** [comment]
I'm not an expert, but I can tell that there have been lots of people who had issues with the AWS broker... I can only give you the link to the wiki (https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws) where an example project is linked: https://github.com/aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4

**Comment by akhtarusafzai** [comment]
@SeppPenner I have looked into that already, That used websockets but I am using TLS certificates

**Comment by akhtarusafzai** [comment]
Resolved It. Any one who has this issue can overcome it with the following steps;

I removed the amazon root cert and passed just the client cert in pfx format
```
List<X509Certificate> certs = new List<X509Certificate>
                {
                    new X509Certificate2("ClientCertPath", "ClientCertPass", X509KeyStorageFlags.Exportable)
                };
```

Change the client options as below

```
var clientOptions = new MqttClientOptionsBuilder()
                    .WithTcpServer(endpoint, port)
                    .WithKeepAlivePeriod(new TimeSpan(0, 0, 0, 300))
                    .WithTls(new MqttClientOptionsBuilderTlsParameters
                    {
                        UseTls = true,
#pragma warning disable CS0618 // Type or member is obsolete
                        CertificateValidationCallback = (X509Certificate x, X509Chain y, System.Net.Security.SslPolicyErrors z, IMqttClientOptions o) =>
#pragma warning restore CS0618 // Type or member is obsolete
                        {
                            return true;
                        },
                        AllowUntrustedCertificates = false,
                        IgnoreCertificateChainErrors = false,
                        IgnoreCertificateRevocationErrors = false,
                        Certificates = certs
                    })
                    .WithProtocolVersion(MqttProtocolVersion.V311)
                    .Build();
```

With this I am able to run the program on Linux, but it has limitation as well. This code snippet runs on Linux not Windows.

**Comment by SeppPenner** [comment]
I will just re-open this for me to add this as hint to the wiki.

**Comment by akhtarusafzai** [comment]
An Update on the limitation side, As I said earlier that this piece of code will not run on windows was wrong. I said that in a hurry and without testing the code on Windows, But the same code runs on both Linux and Windows

**Comment by SeppPenner** [comment]
I have added your example code now to the wiki under https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws.
