### ISSUE TITLE
Something wrong with buildscript of nupkg for net5.0?(MQTTnet.dll should not be bundle in other nupkgs for net5.0)

### ISSUE THREAD

**Issue by yyjdelete** [chkr1011/MQTTnet#1090]
### Describe the bug
Not sure if it's related to #1080, but I try to build local and it's not the issue fixed by 18cc45484278f0c470874758fb520ad4fcee9822

1. Download nupkg from https://www.nuget.org/packages/MQTTnet.Extensions.ManagedClient/3.0.14
2. Unpack it as normal zip file, or open it with NuGet Package Explorer.
3. And you can see `MQTTnet.dll` inside `/lib/net5.0`
![image](https://user-images.githubusercontent.com/1819074/107336850-93d97a80-6af4-11eb-98e5-8d627a571289.png)

Seems it also happens for all others `MQTTnet.*.nupkg`, 

### Expected behavior
MQTTnet should be referenced by nuget instead of dll, like all other targetframework does.

**Comment by chkr1011** [comment]
Please test with RC1 of 3.0.15.

**Comment by yyjdelete** [comment]
@chkr1011 
Yes, it works.
And some other changes are included in #1097
