### ISSUE TITLE
Not receiving messages with ManagedMqttClient

### ISSUE THREAD

**Issue by davepruitt** [chkr1011/MQTTnet#1092]
### Which project is your question related to?
- ManagedClient

### Development environment
- Visual Studio 2019 on Windows 10.
- Xamarin Forms project, developing for Android and iOS. Currently doing all my testing on a Nexus 5X running Android 8.1.
- Nuget packages installed: MQTTnet and MQTTnet.Extensions.ManagedClient (version 3.0.14).

### Description of the issue

I have a microcontroller that is sending out messages to an MQTT server, and then an Android device that is subscribed to receive those messages. The microcontroller is sending the messages properly, and the server is receiving them properly. The server, by the way, is PubNub's MQTT server (https://www.pubnub.com/docs/sdks/mqtt-pubnub-bridge/).

I am using MQTTnet to subscribe to the topic and receive the messages. I am using the ManagedMqttClient, and it works....sometimes....?

It will seem like it is working perfectly for a bit, but then sometimes it will just inexplicably stop receiving the messages. At the same time, however, the server is definitely still receiving the messages from the microcontroller, because I am logged on to PubNub and using their debug console I can see the messages arriving on the server.

I have noticed that *sometimes* it will get fixed if I change the "uuid" in my Android code and re-build my solution, but it doesn't always work like that.

Here is my code. It is pretty simple. Setting up the MQTT connection:

```
//Setup and start a managed MQTT client.
mqtt_options = new ManagedMqttClientOptionsBuilder()
    .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
    .WithClientOptions(new MqttClientOptionsBuilder()
        .WithClientId(publish_key + "/" + subscribe_key + "/" + client_id)
        .WithTcpServer(server_address, server_port)
        .Build())
    .Build();

mqtt_client = new MqttFactory().CreateManagedMqttClient();
mqtt_client.UseApplicationMessageReceivedHandler(HandleReceivedMessage);
mqtt_client.UseConnectedHandler(HandleConnectedEvent);
mqtt_client.UseDisconnectedHandler(HandleDisconnectedEvent);
mqtt_client.StartAsync(mqtt_options);
```

My code to subscribe to a topic is also fairly simple:

```
await mqtt_client.SubscribeAsync(new MqttTopicFilterBuilder()
    .WithTopic(topic_name)
    .Build());
```

No exceptions are being thrown, and the "connected" event occurs successfully (the `HandleConnectedEvent` event handler that I defined is getting called). But the messages just simply aren't arriving... any thoughts?

**Comment by KraskoVladimir** [comment]
Can you share what was the solution here?
