### ISSUE TITLE
Message retransmission with QoS 1

### ISSUE THREAD

**Issue by ssambi** [chkr1011/MQTTnet#1096]
### Describe your question
I'm studying MQTT 3.1.1 and testing MQTTnet, and I have a question about the message retransmission with QoS 1.

I've understood that it's possible to resend a pulished message for which the PUBACK is not received, using the DUP flag.
In other docs is mentioned that usually the resend mechanism is handled by the client library:
`DUP flag The flag indicates that the message is a duplicate and was resent because the intended recipient (client or broker) did not acknowledge the original message. This is only relevant for QoS greater than 0. Usually, the resend/duplicate mechanism is handled by the MQTT client library or the broker as an implementation detail. `
https://www.hivemq.com/blog/mqtt-essentials-part-4-mqtt-publish-subscribe-unsubscribe/

Does MQTTnet handle the retransmission? 
It seems also that the DUP flag is not publicly exposed. How is it possible to resend messages with MQTTnet?

### Which project is your question related to?

- Client
- ManagedClient
- Generic

**Comment by chkr1011** [comment]
Unfortunately you cannot set it manually in this library and the client will not retry a transmit on its own. You will only get an exception. But I can expose this property so that users can set it manually.

**Comment by ssambi** [comment]
@chkr1011, thank you for your reply. 
Since the flag is not exposed, I suppose that the DUP flag and message retransmission are not very common in MQTT application, isn't it? I've not found much information in mosquitto docs, too.

**Comment by chkr1011** [comment]
Well it is used by the MQTTnet Server implementation because it has internal queues so that it knows when a message was sent and retries it so setting the dup flag is easy. The clint is a different thing because an exception is thrown when no ACK is sent for QoS 1.

**Comment by chkr1011** [comment]
The Dup flag is exposed in version 3.0.15-rc2.
