### ISSUE TITLE
Problems with .NET Core on raspberry => Could not load file or assembly 'Windows.Foundation.UniversalApiContract

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#11]
Hi it's me again,

I wanted to start my program (.NET Core) on a raspberry pi and got the following error:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Windows.Foundation.UniversalApiContract, Version=3.0.0.0, Cultre=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. The system cannot find the file specified.
   at MQTTnet.Implementations.MqttTcpChannel..ctor()
   at MQTTnet.MqttClientFactory.CreateMqttClient(MqttClientOptions options)
   at MqttClientModule.MqttClientModule.<threadBodyAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

This error occurs in this line:
MqttClient client = new MqttClientFactory().CreateMqttClient(options);

It seems like my program uses the wrong framework. I found three frameworks:
MQTTnet.NetCoreApp
MQTTnet.NetFramework
and MQTTnet.UniversalWindows

Obviously I need the MQTTnet.NetCoreApp framework and it seems like it's using MQTTnet.UniversalWindows.

How do I tell my framework to use the right one?

Thanks again
Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
Hi,
at the moment .NET Core for ARM is not supported. I know there is a Beta or whatever available but I had no time to add support for ARM .NET Core. 
But there is already support for .NET Core at all. Another user has contributed support for it. But I did not created a new release yet (this change is still in the _master_ branch). I don't know if this works with ARM too.

Do you want to test it via creating a package on your machine (from _master_ branch) and test it? If it works I can release a new build.

Best regards
Christian

**Comment by chkr1011** [comment]
It depends on your target OS. For Windows 10 on a Pi only _UniversalApps_ are supported. If you want to run it with Linux and .NET Core you need the .NET Standard library. The _nuget_ package (which you need to create for testing) is prepared and the required library will be added to your project automatically.

**Comment by Zuendelmeister** [comment]
My target OS is an Ubuntu. But I want to develop with VisualStudio on Windows. Is there a way to to tell my project to build the final .dll for Ubuntu? My problem seems to be that it chooses automatically for me and thinks I want to build an UWP app. 
Or in short: How do I set the target OS? With .NET Core commands I could use the -r flag but in my case this does not work because of the SDK I'm using.

Thanks again
Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
nuget will do this automatically. But you can also select the DLL manually in VS for tests. But you need to use the master branch.

**Comment by Zuendelmeister** [comment]
Sooooo, I deinstalled the nuget package, downloaded the repo (master) and builded the MQTTnet.NetCoreApp solution.  After that I added the new MQTTnet.Core.dll to my project. And it works like a charm ^^ Thank you so much. This is exactly what I wanted to know.

**Comment by chkr1011** [comment]
OK perfect. I will release a new version soon. Then this will work with the official nuget too. If not please let me know.
