### ISSUE TITLE
MqttClientOptionsBuilder WithTls(Action<MqttClientOptionsBuilderTlsParameters> optionsBuilder) doesn't work properly

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#1104]
### Describe the bug
When using the code from the wiki, the connection can be established when specifiying some SSL options (https://github.com/chkr1011/MQTTnet/wiki/Client#tls-using-a-client-certificate), but not if the action syntax is used.

This code works as expected:
```csharp
var options = new MqttClientOptionsBuilder()
    .WithClientId("ClientId")
    .WithTcpServer("mybroker.com", 8883)
    .WithCredentials("Username", "Password")
    .WithTls(new MqttClientOptionsBuilderTlsParameters()
    {
        UseTls = true,
        SslProtocol = SslProtocols.Tls12
    })
    .WithCleanSession()
    .Build();
var factory = new MqttFactory();
var mqttClient = factory.CreateMqttClient();
await mqttClient.ConnectAsync(options);
```

This code doesn't work as expected (e.g. SSL protocol is still TLS1.3):
```csharp
var options = new MqttClientOptionsBuilder()
    .WithClientId("ClientId")
    .WithTcpServer("mybroker.com", 8883)
    .WithCredentials("Username", "Password")
    .WithTls(o => o.SslProtocol = SslProtocols.Tls12)
    .WithCleanSession()
    .Build();
var factory = new MqttFactory();
var mqttClient = factory.CreateMqttClient();
await mqttClient.ConnectAsync(options);
```

Maybe I understand this wrong, but just from my point of view, the second one should be ok as well.

### Which project is your bug related to?
- Client

### To Reproduce
1. Test the code snippets above against any MQTT broker with TLS1.2 enabled.

### Expected behavior
Both scenarios should succeed.

### Screenshots
None.

### Additional context / logging
None, the second secnario results in a MQTT timeout message. Running my code on Net5.0 in ASP.net.

### Code example
Already added above as snippets.

**Comment by chkr1011** [comment]
Yes both ways should lead to the same result. I pushed a fix in master. Please let me know if it works. The problem is that _UseTls_ must be also set to true in order to work properly. Calling the _WithTls_ method indicates that the user definitely wants to have TLS enabled to I change this by default now.

**Comment by SeppPenner** [comment]
Ah okay, I guess, I didn't know that. I will check it now :)

**Comment by SeppPenner** [comment]
@chkr1011 Can be closed as it will be fixed in the next version.
