### ISSUE TITLE
Is PublishAsync() thread-safe on the server?

### ISSUE THREAD

**Issue by fogzot** [chkr1011/MQTTnet#1105]
### Describe the bug
This is probably just some missing information in the documentation. The "Publishing messages" section on the Server wiki page says that it is possible to publish messages from server code and the example is in the Client wiki page. I know that the client isn't thread safe (you cannot publish atb the same time from different threads) but I always supposed that this is not true when publishing from the server, i.e., it is possible to call `PublishAsync()` from different threads at the same time on the server.
Is this true? Also, I think this is something that should be documented (I can provide a patch to the docs, if necessary).

### Which project is your bug related to?
- Server

**Comment by SeppPenner** [comment]
@chkr1011 This is something, you should answer. I can update the docs afterwards.

**Comment by fogzot** [comment]
I checked the source code and AFAIK the messages are added to a concurrent queue, so it should be. But I am not familiar with the source code - that's why I opened the bug and I am waiting for an "official" answer.

**Comment by chkr1011** [comment]
@fogzot  Yes it is 😄 Your assumption was correct.
