### ISSUE TITLE
How to use TLS?

### ISSUE THREAD

**Issue by darl1234567890** [chkr1011/MQTTnet#1106]
Hi there,

Apologies for the more general question, but could someone kindly explain how/where I obtain a TLS certificate & how I use it with Mqttnet?

I want to make Mqtt transactions more secure but have no experience with encryption/TLS.

Thank you!

**Comment by chkr1011** [comment]
@SeppPenner Do we have a sample somewhere? I remember that there was something which also includes command line stuff etc. in order to generate the certificate but I was not able to find it quickly.

**Comment by SeppPenner** [comment]
I guess, you were searching for this: https://github.com/chkr1011/MQTTnet/wiki/Server#using-a-certificate.

At least, if we talk about a self-signed certificate.

I have done that with the openssl library somehow like that

```batch
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in cert.pem
```

The first line generates a key and a certificate where the certificate is valid for 365 days.
The second line exports the certificate as *.pfx format.

Another note: This is still a self-signed certificate which is not validated by any certificate authority, so you will most probably need to set some certificate checks to ignore.

```csharp
var options = new MqttClientOptionsBuilder()
    .WithClientId("ClientId")
    .WithTcpServer("mybroker.com", 8883)
    .WithCredentials("Username", "Password")
    .WithTls(new MqttClientOptionsBuilderTlsParameters()
    {
        UseTls = true,
        SslProtocol = SslProtocols.Tls12,
        AllowUntrustedCertificates = true,
        IgnoreCertificateChainErrors = true,
        IgnoreCertificateRevocationErrors = true
    })
    .WithCleanSession()
    .Build();
var factory = new MqttFactory();
var mqttClient = factory.CreateMqttClient();
await mqttClient.ConnectAsync(options);
```

In the example, I'm talking about `AllowUntrustedCertificates`, `IgnoreCertificateChainErrors` and `IgnoreCertificateRevocationErrors`. Probably, it's sufficient to use `AllowUntrustedCertificates = true`.

**Comment by darl1234567890** [comment]
I'll give this a whirl.
Thank you for the info. Very much appreciated.
