### ISSUE TITLE
New Endpoint API in 3.1.x

### ISSUE THREAD

**Issue by chkr1011** [chkr1011/MQTTnet#1107]
I am implementing a new endpoint API for the upcoming version 3.1.0 of the library. The new implementation only affects the server implementation. 

With the new API it is possible to open as many endpoints as required. Even multiple unencrypted TCP endpoints are possible. Each open endpoint has an assignable ID so that the server handlers can check where a certain client belongs to. This allows treating intranet connections differently than external ones etc. Furthermore the API for configuration (options) is aligned and no longer implemented twice etc.

@JanEggers I ported the ASP stuff so far. Please have a look if there are more obsolete classes in the ASP.NET project. My plans for the next version are to get rid of all obsolete stuff.

@JanEggers While checking the ASP.NET code I found a client side implementation for a Span based adapter. Isn't this a part for the regular library which should be used when supported by the target platform (#if etc.)? Are you using this adapter in your projects?

@JanEggers @SeppPenner Please have a look at the API and let me know what you think. I am still working on some bits like exposing the endpoint ID in event handlers etc.

All others are also welcome to have a look and giving feedback before the API is final and released.

The branch is: feature/Server_Endpoint_API

**Comment by JanEggers** [comment]
> My plans for the next version are to get rid of all obsolete stuff.
just make it clear in the docs. 
for me it is confusing now as you allow asp.net core 2.1 but when using 3.1 you removed the methods  that are required for 2.1 but obsolete in 3.1.
I would prefere a clean baseline here. So if you remove methods that are obsolete in 3.1 then remove the support of aspnetcore 2.1.

Im personally on net5 now so I dont mind ditching anything older than that. that would also enable us to cleanup docs as we dont need to document how to use it for each different version as there are slight differences.

> While checking the ASP.NET code I found a client side implementation for a Span based adapter. Isn't this a part for the regular library which should be used when supported by the target platform (#if etc.)? Are you using this adapter in your projects?

yes I use them. but Id rather wait for the official pipeline based network stack from microsoft and use that once its ready.

**Comment by JanEggers** [comment]
also there is some commented out code so im not sure that this was intentional / is still working

**Comment by chkr1011** [comment]
@JanEggers Do you mean the code that I removed is for ASP 2.1 etc.? I removed it because it was declared as obsolete. So is this NOT obsolete and still required? If that is true I will revert the deletions but also remove the obsolete declaration.

The code which is commented out needs to be reviewed and migrated if required. But for now I want to talk about the general idea behind these endpoints.

For the pipeline thing I would like to create a separate library which can be uploaded as a nuget and maintained separately. What do you think about that idea instead of having this "hidden" in the ASP.NET library?

**Comment by JanEggers** [comment]
regardning the obsolete stuff:

it is required for asp.net 2.1 but obsolete in 3,1. so I also marked the method as obsolete because it is calling an obsolete api of aspnet. the issue is that it is dependent on the version of the aspnet stuff. I dont know if that makes sense...

> For the pipeline thing I would like to create a separate library which can be uploaded as a nuget and maintained separately. What do you think about that idea instead of having this "hidden" in the ASP.NET library?

sounds good for me

**Comment by chkr1011** [comment]
I will close this for now because the feature is delayed to version 4.x.
