### ISSUE TITLE
WithConnectionValidator with async does not work

### ISSUE THREAD

**Issue by Octoate** [chkr1011/MQTTnet#1112]
### Describe your question
I am currently using MQTTnet to create a simple MQTT broker that retrieves user credentials from a database in the cloud. This request needs some time and uses async methods for data retrieval and so I am using async / await in the WithConnectionValidator delegate implementation. However, the user always get's access to the MQTT broker and it seems that the connection validation does not wait for the database query to finish.

### Which project is your question related to?
- MQTTnet.Server standalone (v3.0.15)

It seems that a similar issue was mentioned in issue #597, but the implementation did not use async / await. Any ideas what might be wrong here?

Here is the delegate that I use for the WithConnectionValidator:
```csharp
        private async void ValidateConnection(MqttConnectionValidatorContext context)
        {
            var verified = await _backendCommunicationService.VerifyUserAsync(context.Username, context.Password);
            if (!verified)
            {
                context.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
            }
            else
            {
                context.ReasonCode = MqttConnectReasonCode.Success;
            }
        }
```

and this is the user verification:
```csharp
        public async Task<bool> VerifyUserAsync(string loginName, string loginPassword)
        {
            // anonymous login not allowed
            if (string.IsNullOrEmpty(loginName) || string.IsNullOrEmpty(loginPassword))
            {
                return false;
            }

            try
            {
                // get current user
                var backendUser = await GetUserAsync(loginName);

                // user not found?
                if (backendUser == null)
                {
                    return false;
                }

                // user found -> check credentials
                if (backendless.Name == loginName && IsPasswordValid(backendUser, loginPassword))
                {
                    // credentials okay
                    return true;
                }
            }
            catch (BackendException ex)
            {
                _logger.LogError(ex, "An exception occurred while querying the backend database.");
            }
            
            return false;
        }

        private async Task<MqttUser> GetUserAsync(string name)
        {
            MqttUser user = null;

            // create Backend query
            var queryBuilder = DataQueryBuilder.Create();
            queryBuilder.SetWhereClause($"name = '{name}'");
            var userList = await _mqttUserTable.FindAsync(queryBuilder);

            // user not found?
            if (userList.Count == 1)
            {
                // set the user and store it in our local cache
                user = userList[0];
            }
            
            return user;
        }
```

**Comment by chkr1011** [comment]
Please replace _private async void ValidateConnection(MqttConnectionValidatorContext context)_ with _private async Task ValidateCo...._.

**Comment by Octoate** [comment]
Thanks for the fast answer. If I do this, I am unable to add the method via ".WithConnectionValidator(ValidateConnection)" to the options. How do I have to add the Validator then?

**Comment by chkr1011** [comment]
Ah OK there is no overload yet in the builder. You can create the instance of the delegate on your own like ".WithConnectionValidator(new ConnectionValidatorDelegate())".

**Comment by Octoate** [comment]
It works with ".WithConnectionValidator(new MqttServerConnectionValidatorDelegate(ValidateConnection))" now. Awesome, thanks a lot for your help!

**Comment by chkr1011** [comment]
I will also add this overload so that no one else will have this issue.

**Comment by SeppPenner** [comment]
@chkr1011 I'm not sure if this is needed... I have some working code where I use it like this:

```csharp
 .WithConnectionValidator(this)
```

and the class looks somehow like this:

```csharp
public class MqttService : BackgroundService, IMqttServerSubscriptionInterceptor
{
    // Lot of stuff...

    public async Task ValidateConnectionAsync(MqttConnectionValidatorContext context)
    {
        // Do something
    }
}
```

and this works as expected.
