### ISSUE TITLE
Supporting multiple instances

### ISSUE THREAD

**Issue by dereklew** [chkr1011/MQTTnet#1118]
### Describe your question
Does MQTTnet supports multiple instances? E.g. 

IMqttClientOptions_options1 = new MqttClientOptionsBuilder()...
IMqttClientOptions_options2 = new MqttClientOptionsBuilder()...

IMqttClient _client1;
IMqttClient _client2;

Task<MqttClientAuthenticateResult> mqttClientAuthenticateResult1 = _client1.ConnectAsync(_options1);
Task<MqttClientAuthenticateResult> mqttClientAuthenticateResult2 = _client2.ConnectAsync(_options2);

### Which project is your question related to?

- Client

**Comment by JanEggers** [comment]
yep?

**Comment by SeppPenner** [comment]
Yes, it does. Just stay cautious to use unique client identifiers for all clients to avoid disconnection issues.
