### ISSUE TITLE
ManagedClient subscription and wildcard character "#" in the wrong place

### ISSUE THREAD

**Issue by marcelwinh** [chkr1011/MQTTnet#1119]
### Describe the bug
If you want to subscribe to the topic "test/#t" with the managed client the server closes the connection. This is because the "#" is a multi level wildcard which is only allowed at the end of the topic. 

There was a similar issue on the publish side https://github.com/chkr1011/MQTTnet/issues/581 but it is not exactly the same. When you publish no wildcards are allowed.

### Which project is your bug related to?

- ManagedClient

### To Reproduce
1. Using this version of MQTTnet '3.0.15'.
2. Run this code 'ManagedMqttClient.SubscribeAsync("test/#t")'.
3. With these arguments '....'.
4. See error.

### Expected behavior
I would expect that an error is thrown because the topic is invalid

### Example fix
A validation could be in \Source\MQTTnet\Protocol\MqttTopicValidator.cs
```CS
public static void ThrowIfInvalidSubscribe(string topic)
{
    if (string.IsNullOrEmpty(topic))
    {
        throw new MqttProtocolViolationException("Topic should not be empty.");
    }
   
    if(topic.IndexOf("#") != -1 && topic.IndexOf("#") != topic.Length - 1) throw new MqttProtocolViolationException("The character '#' is only allowed as last character");
}
```
And some tests:
```CS
[TestClass]
public class MqttTopicValidatorSubscribe_Tests
{
    [TestMethod]
    public void Valid_Topic()
    {
        MqttTopicValidator.ThrowIfInvalidSubscribe("/a/b/c");
    }

    [TestMethod]
    public void Valid_Topic_Plus_In_Between()
    {
        MqttTopicValidator.ThrowIfInvalidSubscribe("/a/+/c");
    }

    [TestMethod]
    public void Valid_Topic_Plus_Last_Char()
    {
        MqttTopicValidator.ThrowIfInvalidSubscribe("/a/+");
    }

    [TestMethod]
    public void Valid_Topic_Hash_Last_Char()
    {
        MqttTopicValidator.ThrowIfInvalidSubscribe("/a/#");
    }

    [TestMethod]
    public void Valid_Topic_Only_Hash()
    {
        MqttTopicValidator.ThrowIfInvalidSubscribe("#");
    }

    [TestMethod]
    [ExpectedException(typeof(MqttProtocolViolationException))]
    public void Invalid_Topic_Hash_In_Between()
    {
        MqttTopicValidator.ThrowIfInvalidSubscribe("/a/#/c");
    }

    [TestMethod]
    [ExpectedException(typeof(MqttProtocolViolationException))]
    public void Invalid_Topic_Empty()
    {
        MqttTopicValidator.ThrowIfInvalidSubscribe(string.Empty);
    }
}
```

**Comment by marcelwinh** [comment]
sry i can't get the project running on my machine and therefore can't create a PR

**Comment by SeppPenner** [comment]
I will see what I can do here.

> sry i can't get the project running on my machine and therefore can't create a PR

Did you use the *.sln solution with UWP or without? (With UWP will of course not work if UWP is not installed).

**Comment by SeppPenner** [comment]
I have added the pull request, @chkr1011 and @JanEggers should verify the changes soon :)
