### ISSUE TITLE
managed client subscriber not recieving messages in the form xxxx/#

### ISSUE THREAD

**Issue by fbd-ss** [chkr1011/MQTTnet#1120]
When subscribing to the topic xxxx/# the client does not throw the messages out to the subscriber object.

subscription is made just like any other 

```csharp
  var filter = new MqttTopicFilterBuilder()
    .WithTopic( topic )
    .WithQualityOfServiceLevel( (MqttQualityOfServiceLevel)subscription_data.qos_level )
    .Build();

  await _mqtt_client.SubscribeAsync( filter );
```

and messages recieved via "mqtt_client.UseApplicationMessageReceivedHandler"

inside "UseApplicationMessageReceivedHandler" is the following code:

```csharp
foreach ( var subscription in _subscriptions[ topic ] ) {
	subscription?.callback?.Invoke( payload );
}
```

expected behavoiur,
The object that subscribed via "SubscribeAsync" should recieve messages from xxxx/foo and xxxx/bar, but doesnt, because while "args.ApplicationMessage.Topic" never shows in the form "xxxx/#" only for each topic name.  Inside "UseApplicationMessageReceivedHandler" there is no way of telling when to send message to subscriber object apart from going through stored subscriptions and checking each one individually.

**Comment by SeppPenner** [comment]
I'm not sure if I understand the problem. The topics inside the message received handler are of course topics, not topic filters like `xxx\#`.

**Comment by chkr1011** [comment]
I agree that you cannot use wildcards in topics. So you will never get your expected result. This is by design and not supported in MQTT at all.

**Comment by vhe1** [comment]
Hm. Given that comment on the topic property:
![image](https://user-images.githubusercontent.com/12475356/184326649-a1b0faed-55c5-474c-8da9-a9869b917f61.png)

I would have expected to get that back too. It says "uses to filter". Not "result of a match".
