### ISSUE TITLE
Publishing in the MQTT server implementation does not seem to work

### ISSUE THREAD

**Issue by Octoate** [chkr1011/MQTTnet#1122]
### Describe the bug
It seems that the PublishAsync method does not publish the given MqttApplicationMessage to the connected clients.

### Which project is your bug related to?
MQTTnet server 3.0.15

### To Reproduce
1. Use the SimpleServer example from the MQTTnet examples
2. Start the MQTTnet server
3. Connect with another MQTT client to the server and subscribe to all messages
4. Enter some text or generate a random value
5. Click "Publish"
--> The connected client does not receive the published message.

### Expected behavior
The connected client receives the message that was published on the given topic.

### Code example
[SimpleServer Repository](https://github.com/SeppPenner/SimpleMqttServer)

**Comment by SeppPenner** [comment]
I will have a look at it.

**Comment by Octoate** [comment]
Hi,
I have rechecked it on another system and it works fine there. After an update and an restart of my main development machine, it seems to work as expected now. Strange error. Anyway, it works now.
