### ISSUE TITLE
MQTTnet won' work with dot net framework 4.8

### ISSUE THREAD

**Issue by OIJimChen** [chkr1011/MQTTnet#1126]
Hi,
Just installed MQTTnet 3.0.15.0 via Nuget but it wouldn't recognise the referenced dll. Environment VS2019. Project target AnyCPU, dot net framework 4.8. While running the code where it references the component, it stops and shows error in debug:

System.IO.FileNotFoundException: 'Could not load file or assembly 'MQTTnet, Version=3.0.15.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'. The system cannot find the file specified.'

Does it not support framework 4.8? I do notice that v4.6.1 and v5.0 are mentioned.

Many thanks
Jim

**Comment by chkr1011** [comment]
In my opinion VS should select netstandard1.3 in this case!?

https://nugettoolsdev.azurewebsites.net/3.5.0-beta2-1484/get-nearest-framework?project=net48&package=netstandard1.3%0D%0Anetstandard2.0

**Comment by OIJimChen** [comment]
Thanks Christian. I will give a go. My project was created long time ago (about 10 years) and updated to the .net framework 4.8 last year.

**Comment by SeppPenner** [comment]
I assume, that this issue is now solved. If not, just re-open the issue, please.
