### ISSUE TITLE
Concurrent publishes from multiple clients

### ISSUE THREAD

**Issue by colinmc86** [chkr1011/MQTTnet#1129]
Hello,

For my use case, I am using 1 client / connection per use case. For one of my .net core services, this results in about 10 clients / connections. I am seeing lots of disconnects and reconnects, even though the connection is stable. Any suggestions? I'm using the default keepalive, which I believe is 15 seconds (sounds aggressive?)

Thanks,

Colin

**Comment by SeppPenner** [comment]
As a first question: Did you assign unique client ids to your clients / connections? If not, this could be the issue as client ids need to be unique in the whole MQTT broker.

**Comment by colinmc86** [comment]
Hi @SeppPenner 

The each client / connection has a unique clientId (we use app_name + Guid.NewGuid() to gurantee uniqueness)

**Comment by colinmc86** [comment]
The issue was actually from using an incorrect profile in our F5 configuration. Closing issue.

Thanks!
