### ISSUE TITLE
Errors in .NET 5.0 Example 

### ISSUE THREAD

**Issue by k0qed** [chkr1011/MQTTnet#1130]
### Describe the bug
The example (Program and Startup) at https://github.com/chkr1011/MQTTnet/wiki/Server#net-50 won't compile (unknown classes and interfaces).

### Which project is your bug related to?
- Server

### To Reproduce
1. Create a new .net 5 console project
2. Replace contents of Program.cs with code in example Program class
3. Create new Startup class using code in example Startup class
4. Add missing nuget packages

### Expected behavior
No code errors

### Screenshots
![image](https://user-images.githubusercontent.com/6035553/112704803-918f6d80-8e61-11eb-804e-63350da46de0.png)

![image](https://user-images.githubusercontent.com/6035553/112704779-7a508000-8e61-11eb-9cda-a0781b869cf0.png)

**Comment by SeppPenner** [comment]
Maybe the heading was misleading here, I have changed it: https://github.com/chkr1011/MQTTnet/wiki/Server#aspnet-50.

The example only works in a ASP.Net project, not in a console application as you're missing the ASP.Net specific stuff like the host or routing for controllers, etc.
