### ISSUE TITLE
Disable ping logging

### ISSUE THREAD

**Issue by notpaimon** [chkr1011/MQTTnet#1138]
### Describe your question
When a client is connected to server the log is flooded with ping spam:
```
RX (2 bytes) <<< PingReq
TX (2 bytes) >>> PingResp
```

I guess it would make more sense to move such log messages to verbose level.
Is there an option to disable the ping logging? 

### Which project is your question related to?
- Client
- Server

**Comment by ramonsmits** [comment]
@notpaimon These log entries use `MqttNetLogLevel.Verbose` to should already have the correct log level.

Can you share your custom `IMqttNetLogger` implementation?

**Comment by notpaimon** [comment]
@ramonsmits I got it from [here ](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet.Server/Logging/MqttNetLoggerWrapper.cs)
Now I've inspected that code and found this:
```
case MqttNetLogLevel.Verbose: return LogLevel.Debug;
```
I believe there's a typo on [this line](https://github.com/chkr1011/MQTTnet/blob/8f1d4e3c22f3226570eec681bccef3a88c4ebd16/Source/MQTTnet.Server/Logging/MqttNetLoggerWrapper.cs#L58)
Changing to Trace has resolved the question.
Thanks!
