### ISSUE TITLE
BindingFailure on Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by GlebTyazhyolov** [chkr1011/MQTTnet#114]
Hi all!

VS 2017 Community edition
Project target framework: 4.5.2
MqttNet 2.5.1

I write some library, let's name it MyMQTT.dll, which use ManagedMqttClient and provide some higher level MQTT abstractions for my project.

As I say MyMQTT.dll is referenced in my application project. When I start application, I catch exception in MyMQTT.dll
_"Managed Debugging Assistant 'BindingFailure'":
The assembly with display name 'Microsoft.Extensions.DependencyInjection' failed to load in the 'LoadFrom' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)_

Exception is throwing on the line:
`var cli = new MqttFactory().CreateManagedMqttClient();`

The library Microsoft.Extensions.DependencyInjection.dll is in place in both MyMQTT and in application
File version: 1.1.1.30427
Product version: 1.1.1

Tried to add netstandard and net core libraries to my project, migrate to ProjectReferences, do some voodoo magic. No success. Spent few days and pulled out almost all my hairs. Please help! =)

PS Versions 2.3.x works like a charm, but I really like ManagedMqttClient which is provided in newer versions.

**Comment by chkr1011** [comment]
Hi, thanks for reporting this issue. Please test again with version 2.5.2-rc1 (Preview available as nuget). Several reference issues are fixed in that release.

**Comment by GlebTyazhyolov** [comment]
Tried rc version. The error slightly changed in the part of DependencyInjection library version. Was 1.1.1.0 became 1.0.2.0

_Message=Managed Debugging Assistant 'BindingFailure' : 'The assembly with display name 'Microsoft.Extensions.DependencyInjection' failed to load in the 'LoadFrom' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'_

**Comment by chkr1011** [comment]
Did you have copied all binaries to your root project? The .exe or whatever? If your "MyMQTT.dll" used it you must also copy it to the output of your root project output even if you don't reference them there.

**Comment by GlebTyazhyolov** [comment]
Yes, all libraries was in exe program folder. As Microsoft.Extensions.DependencyInjection.dll.
I admit that it can be some bug in my environment, so no problem if you will ignore this issue until someone else report the same.
I tempoprary fallback to other mqtt library, so it's not urgent for me anymore. Maybe will try to switch back later.

**Comment by chkr1011** [comment]
@GlebTyazhyolov I just released a RC version of 2.5.3 ("2.5.3-rc1" nuget) which has no more any 3rd-Party references. This should work for your case as well. Please let me know if it works.

**Comment by GlebTyazhyolov** [comment]
Thanks chkr1011, it's interesting to try, but I too busy next few weeks to make test. If I find some time I will. Thanks again.

**Comment by GlebTyazhyolov** [comment]
Hi chkr1011
Just for information, I tried next version and confirm that my issue was gone away.
