### ISSUE TITLE
Client disconnected directly when trying to connect with AWS IoT

### ISSUE THREAD

**Issue by andi-shehu93** [chkr1011/MQTTnet#1145]
### Describe your question
I'm trying to connect with AWS IoT core using certificates. My code is pretty typical, nothing fancy:

```
                var tlsParameters = new MqttClientOptionsBuilderTlsParameters
                {
                    UseTls = true,
                    Certificates = new[] { RootCertificate, Certificate },
                    IgnoreCertificateRevocationErrors = true, //Prevent online revocation check
                    IgnoreCertificateChainErrors = true,
                    AllowUntrustedCertificates = true,
                    SslProtocol = System.Security.Authentication.SslProtocols.Tls12
                };
                var connectOptions = new MqttClientOptionsBuilder()
                    .WithClientId(ClientID)
                    .WithTcpServer("xxx.amazonaws.com", 8883)
                    .WithTls(tlsParameters)
                    .WithCommunicationTimeout(TimeSpan.FromMilliseconds(30 * 1000))
                    .WithCleanSession()
                    .Build();

                // Connect to the MQTT broker
                var result = await Client.ConnectAsync(connectOptions);

```

The logger is outputting the following:

```
Verbose - Trying to connect with server 'xxx.amazonaws.com:8883' (Timeout=00:00:30).
Verbose - Connection with server established.
Verbose - Start receiving packets.
Verbose - TX (100 bytes) >>> Connect: [ClientId=yyy] [Username=] [Password=] [KeepAlivePeriod=15] [CleanSession=True]
Verbose - Disconnecting [Timeout=00:00:30]
Verbose - Disconnected from adapter.
Info - Disconnected.
Verbose - Stopped receiving packets.
Warning - Timeout while waiting for response packet (MqttConnAckPacket).
Error - Error while connecting with server.
```

It seems, it's connected successfully and automatically disconnected. I get an exception `Error while authenticating. Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.` afterwards, so not sure what I'm doing wrong.

Certificate is activated on AWS and I've attached the "thing" with a policy that allows everything.

Any idea?

### Which project is your question related to?
- Client

**Comment by andi-shehu93** [comment]
By looking at the code, seems the exception is thrown at the following line

`return await packetAwaiter.WaitOneAsync(Options.CommunicationTimeout).ConfigureAwait(false);`

**Comment by chkr1011** [comment]
I personally don't use AWS so I cannot provide help. But there are already some tickets in the repo which are covering this topic a lot. We also have some notes in the Wiki (https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws). Hope this helps.

**Comment by albert-t25** [comment]
Check out https://github.com/chkr1011/MQTTnet/issues/1079

**Comment by SeppPenner** [comment]
I've collected every troubleshooting tips under https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws now. There is a discussion available under https://github.com/chkr1011/MQTTnet/discussions/1225 where I'm trying to collect all issues with AWS now since all the same issues seem to occur very often.
