### ISSUE TITLE
Connect with AWS

### ISSUE THREAD

**Issue by KevinBurton** [chkr1011/MQTTnet#1155]
### Describe the feature request
I would like to know if there is a work around for connecting with AWS. 

### Which project is your feature request related to?
- Client
- ManagedClient

### Describe the solution you'd like
I would like to be able to use MQTTNet to connect to a MQTT server/hub that is hosted in AWS

### Additional context
I read

> Due to a known issue with WebSocket implementation for .NET it is not possible to connect with Amazon AWS with MQTTnet because it relies on the .NET implementation of WebSockets.

**Comment by SeppPenner** [comment]
There are already some issues open with that topic. From my side, I have never used AWS IoT and can't talk about it. Maybe give https://github.com/chkr1011/MQTTnet/issues/1079 a try.

**Comment by jkoplo** [comment]
Here's some snippets that are 'known good'. I don't promise they are perfect. Often people have trouble with AWS permissions and with AWS IoT limitations (`Retain`, `QoS=2`, `Will messages` will all cause abrupt disconnects).

[Framework](https://gist.github.com/jkoplo/16f25875f7aca9503a7520fcda99005f)
[Core](https://gist.github.com/jkoplo/bd60cfe1a02c6e13b0a2d753289ae00f)

**Comment by SeppPenner** [comment]
I've collected every troubleshooting tips under https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws now. There is a discussion available under https://github.com/chkr1011/MQTTnet/discussions/1225 where I'm trying to collect all issues with AWS now since all the same issues seem to occur very often.

**Comment by SeppPenner** [comment]
> 
> 
> Here's some snippets that are 'known good'. I don't promise they are perfect. Often people have trouble with AWS permissions and with AWS IoT limitations (`Retain`, `QoS=2`, `Will messages` will all cause abrupt disconnects).
> 
> [Framework](https://gist.github.com/jkoplo/16f25875f7aca9503a7520fcda99005f)
> [Core](https://gist.github.com/jkoplo/bd60cfe1a02c6e13b0a2d753289ae00f)

I have added your snippets to both resources as well ;)
