### ISSUE TITLE
MapMqtt in aspnetcore

### ISSUE THREAD

**Issue by alberk8** [chkr1011/MQTTnet#1156]
### Describe your question
I would like to know where is this  `endpoints.MapMqtt("/mqtt') ` mapped to.  Is there a controller that will host the topic?
example code:   https://github.com/chkr1011/MQTTnet/issues

### Which project is your question related to?
- Server
aspnet core 5.

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/8f1d4e3c22f3226570eec681bccef3a88c4ebd16/Source/MQTTnet.AspnetCore/Extensions/EndpointRouterExtensions.cs#L11-L17

the MqttConnectionHandler forwards the mqtt packets from a websocket to the mqtt broker implementation

**Comment by SeppPenner** [comment]
@alberk8 If you have your MQTT broker running on localhost:1883, the route to the WebSocket handler would be `ws://localhost:1883/mqtt`. If you use a domain with a TLS certificate, it would be something like `wss://mydomain.com/mqtt` for mydomain.com.
