### ISSUE TITLE
TLS two way from server MQTTnet (client certificate)

### ISSUE THREAD

**Issue by walterrrossi** [chkr1011/MQTTnet#1159]
Is it possibile to build a server with MQTTnet that check the certificate of a client? 
I tried to see if there are present some functions to do that, but I didn't find anything. It seems that it is possibile to do it from a client, so a one way TLS.

### Which project is your question related to?
- Server
- TLS

**Comment by amelkor** [comment]
Do you mean this one:
`WithRemoteCertificateValidationCallback()` in `MqttServerOptionsBuilder` ?

It can validate client certificates on the server, as far as I know:

```
        private bool Value(object sender, X509Certificate? certificate, X509Chain? chain, SslPolicyErrors sslpolicyerrors)
        {
            // validate
            return true;
        }
```

**Comment by SeppPenner** [comment]
@amelkor That's the answer I would have given as well.
