### ISSUE TITLE
Secured websocket client

### ISSUE THREAD

**Issue by StAI** [chkr1011/MQTTnet#116]
Is it possible to add support of secured websocket client? I mean "wss://someserver".
As I see "ws://" hardcodede in MqttWebSocketChannel for now

**Comment by chkr1011** [comment]
Hi you can try using the full URI including the _wss://_ protocol prefix.

**Comment by StAI** [comment]
HI Christian, Uri with wss:// prefix will not work because there is the following in MqttWebSocketChannel:public async Task ConnectAsync()        {            var uri = _options.Uri;            if (!uri.StartsWith("ws://", StringComparison.OrdinalIgnoreCase))            {                uri = "ws://" + uri;            }… If I remove this it will work. Best Regards 21.11.2017, 23:03, "Christian" <notifications@github.com>:Hi you can try using the full URI including the wss:// protocol prefix.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by chkr1011** [comment]
@StAI Thanks for your support. A new version is released as RC ("2.5.3-rc1" nuget) which contains a fix (beside other changes). Please let me know if it works with that version.

**Comment by chkr1011** [comment]
@StAI Version 2.5.3 is now released. If the issue still exists please reopen this ticket or create a new one.
