### ISSUE TITLE
ManagedClient: message receiving hangs without any apparent reason

### ISSUE THREAD

**Issue by maiorfi** [chkr1011/MQTTnet#1162]
### Describe the bug
After a random time (from a few minutes to several hours) message receiving hangs without any apparent reason

### Which project is your bug related to?

- ManagedClient

### To Reproduce
1. Using this version of MQTTnet '3.0.15'.
2. Run provided example code for ManagedClient

### Expected behavior
As long as messages keep on arriving they should be processed. Restarting application causes messages processing restart regularly.

### Additional context / logging
Console .net core 5.0 application

Is there any best practice to check for unexpected conditions?

**Comment by ramonsmits** [comment]
What is the workload? Could it be that your workload somehow results in a hang?

**Comment by maiorfi** [comment]
I enabled logging and just before everything hangs I get following log entries:

Verbose: Stopped sending keep alive packets.
Info: Disconnected.
Verbose: Stopped receiving packets.
Verbose: Stopped receiving packets.

Any idea?

**Comment by ramonsmits** [comment]
By default message processing is sequential. Is `processAlleantiaSubscribedMessage` stuck or running for a long time? 

If these messages are QOS1 you might want to do:

```
static async void processAlleantiaSubscribedMessage(MqttApplicationMessageReceivedEventArgs e)
{
	// async void results in fire and forget, but without any throttling!
}
```

**Comment by maiorfi** [comment]
Hi, I tried with following handler structure, but after a random time (sometimes 2-3 minutes, sometimes several days) message reception stops working, without any evident reason (other client instances, running in different processes, keep on processing same messages after one instance hangs):

```csharp
static async Task processAlleantiaSubscribedMessage(MqttApplicationMessageReceivedEventArgs e)
        {
            try
            {
                var topic = e.ApplicationMessage.Topic;
                var payloadAsString = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);

                var telemetry = TelemetrySet.FromJson(payloadAsString);

                var handlerTask = processTelemetry(telemetry);
                var timeoutTask = Task.Delay(TimeSpan.FromMilliseconds(MQTT_MESSAGE_HANDLING_TIMEOUT_MSECS));

                var completedTask = await Task.WhenAny(handlerTask, timeoutTask);

                if (completedTask == timeoutTask)
                {
                    throw new TimeoutException($"processAlleantiaSubscribedMessage timed out after {MQTT_MESSAGE_HANDLING_TIMEOUT_MSECS} msecs");
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Exception in processAlleantiaSubscribedMessage() : {0} while processing args\n{1}",ex.Message, ObjectDumper.Dump(e));
            }
        }
```

**Comment by ramonsmits** [comment]
@maiorfi What mqtt server are you using? Are you actually still connected? I'm not using the managed client and use mosquito.


By the way, the `await Task.WhenAny(handlerTask, timeoutTask);` is really not a great pattern.

Its better to use a `CancellationTokenSource` and apply cooperative cancellation.

static async Task processAlleantiaSubscribedMessage(MqttApplicationMessageReceivedEventArgs e)
{
    try
    {
        var topic = e.ApplicationMessage.Topic;
        var payloadAsString = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);

        var telemetry = TelemetrySet.FromJson(payloadAsString);

		using var cts = new CancellationTokenSource(MQTT_MESSAGE_HANDLING_TIMEOUT_MSECS);
        await processTelemetry(telemetry, cts.Token);
    }
    catch (Exception ex)
    {
        _logger.LogWarning(ex, "Exception in processAlleantiaSubscribedMessage() : {0} while processing args\n{1}",ex.Message, ObjectDumper.Dump(e));
    }
}

**Comment by maiorfi** [comment]
We're using https://www.emqx.io/ MQTT broker.

**Comment by maiorfi** [comment]
Hi. I think I could have got issue cause.
I realized I was using same clientid on different concurrent clients (very often 2 console apps instances, running on different machines).
Could described issue be related to such cause?
I updated apps in order to use a semi-random clientid and since then apps are running without hiccups (12 hours and running).
Finger-crossed!

**Comment by ramonsmits** [comment]
@maiorfi if that happens you should see log entries indicating the client is disconnected. If you do not see these you should configure your logging to see these log events.

**Comment by maiorfi** [comment]
Indeed, I got many log messages about client being disconnected. At this time, it has been running for several days, so I'm going to close the issue. Anyway, could you explain why two concurrent clients, competing for same ClientId, actually ran as expected even for several hours before stopping? I guess disconnections happen to be in kind of interlaced way, but why did such pattern always come to an end where one of two instances stopped receiving messages, according to you? Thanks!

**Comment by ramonsmits** [comment]
> could you explain why two concurrent clients, competing for same ClientId, actually ran as expected even for several hours before stopping?

I have never seen this myself. The behavior I've observed is that they continuously compete to get an active connection until either process dies.

**Comment by SeppPenner** [comment]
> 
> 
> > could you explain why two concurrent clients, competing for same ClientId, actually ran as expected even for several hours before stopping?
> 
> I have never seen this myself. The behavior I've observed is that they continuously compete to get an active connection until either process dies.

@ramonsmits  That's exactly the behaviour I experienced as well when using non unique client ids...
