### ISSUE TITLE
try_private false

### ISSUE THREAD

**Issue by Zac4Git** [chkr1011/MQTTnet#1166]
Hi there!

We've tried to use MQTTnet as a broker (server) with our old raspberry pi boards (where was installed mosquito as a client), but we couldn't get a proper communication until we didn't change clients settings try_private to false in mosquitto.conf file.
I understand that try_private settings related only to mosquito library, but I'm sure that it will be very great if current library would support that feature also.

[try_private [ true | false ]
If try_private is set to true, the bridge will attempt to indicate to the remote broker that it is a bridge not an ordinary client. If successful, this means that loop detection will be more effective and that retained messages will be propagated correctly. Not all brokers support this feature so it may be necessary to set try_private to false if your bridge does not connect properly.](https://mosquitto.org/man/mosquitto-conf-5.html)

Thanks!

### Which project is your question related to?
- Server

**Comment by AlexShvets83** [comment]
Hi developer!
I'm also waiting for a decision))

**Comment by AlexShvets83** [comment]
Solved!
try_private true - default - add one bit fore protocol version (mast 0000 0011 = 3, but send 1000 0011 = 131)
if try_private false - send protocol version equals 3

**Comment by Zac4Git** [comment]
You are the Rockstar, dude! You saved this garbage code! God bless you!
