### ISSUE TITLE
Client does not connect

### ISSUE THREAD

**Issue by peteryang023** [chkr1011/MQTTnet#1169]
I use mqtt client to publish the images with QoS0 at a high interval(about 10/s) after it can publish the message successfully at the beginning, but after approximately 5s, it throws an exception with the error message "The client does not connect." The broker I am using is **mosquitto**, is someone have any idea about it?
MQTTNet version is 3.0.15.

**Comment by notjulian** [comment]
I've the same problem ...

**Comment by jyc939841799** [comment]
俺也一样，俺也是这个问题。

**Comment by PeterWone** [comment]
1. Out of the box Mosquitto will accept unauthenticated connections on localhost. 
2. Until you define a listener, you can only connect from localhost.
3. Define a listener by editing `mosquitto.conf` around line 200 and set up a listener on the default MQTT port on all interfaces with
   ```
   listener 1883
   ```
4. As soon as you define a listener, Mosquitto stops permitting unauthenticated connections on localhost and you **must** use authentication.
5. To use authentication (there are several ways) you must configure it. Once again you must define this in `mosquitto.conf`
6. There are various ways you can set up configuration. Search for `mosquitto cert authentication` or whatever you feel is appropriate. You must also supply credentials or a cert or whatever when you set up the managed client.
7. Either set up TLS or turn it off.

```
      var options = new ManagedMqttClientOptionsBuilder()
          .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
          .WithClientOptions(new MqttClientOptionsBuilder()
              .WithProtocolVersion(MqttProtocolVersion.V500)
              .WithClientId(ClientId)
              .WithTcpServer("nas.lan")
              .WithCredentials("roger", "password")
              // .WithTls()
              .Build())
          .Build();

      var mqttClient = new MqttFactory().CreateManagedMqttClient();
```

**Comment by SeppPenner** [comment]
@peteryang023 I will close this issue now as I assume that it's solved. @PeterWone's answer seems to give you the hints you should try. If still some issues occurr, you can re-open the issue :)
