### ISSUE TITLE
Troubles with different versions of Microsoft.Extensions.Logging and Options

### ISSUE THREAD

**Issue by ChristianRiedl** [chkr1011/MQTTnet#117]
You are using different versions of the Microsoft Extension 1.x DLLs (1.0.2, 1.1.2) in your Core and Netstandard (UWP) projects and I am struggling with assembly bindings in my components.

I think it would be better to use always the same and latest version before 2.0. This latest version contains some fixes and a bit additional functionality, keeping full compatibility.

**Logging, Options : 1.1.2, DI : 1.1.1**

Options is missing for some targetframeworks, I think it is better to add it explicitely. Why do you use 2.0 for net461 ? It will works with 1.x too without creating troubles for people currently using net461 with 1.x DLLs.  

Proposal for Core : 
```
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.2" />

```

Proposal for Frameworks.NetStandard : 

```
  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="System.Net.Security" Version="4.3.2" />
    <PackageReference Include="System.Net.WebSockets" Version="4.3.0" />
    <PackageReference Include="System.Net.WebSockets.Client" Version="4.3.1" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netstandard1.3'">
    <PackageReference Include="System.Net.Security" Version="4.3.2" />
    <PackageReference Include="System.Net.WebSockets" Version="4.3.0" />
    <PackageReference Include="System.Net.WebSockets.Client" Version="4.3.1" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='uap10.0'">
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="5.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net452'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net461'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.2" />
  </ItemGroup>


```

**Comment by chkr1011** [comment]
After some time I have doubts if this approach with DI etc. was a good decision. It leads to more problems that it solves. @JanEggers I would like to revert to a version without this DI approach (and also the logging and options libraries).

**Comment by JanEggers** [comment]
I agree, there are way more troubles than i anticipated.

**Comment by ChristianRiedl** [comment]
I think it is an overkill to introduce DI and `IOption<T>` interface for the creation of one MqttClient or MqttServer object. Also the `ILogger<T>` are not really neccessary for this size of project. The only thing I use now in every library is non generic `ILogger` from Microsoft.Extensions.Logging.Abstractions. Before every lib had its own ILog interface, LogLevel and I wrote a lot of log converters. For me it is important not to use a static log object because having more than 1 client or server is quite normal. I would add a `ILogger logger = null)` parameter to the MqttClient and MqttServer constructor, If logger is null you can create an internal log object implementing ILogger interface.

**Comment by chkr1011** [comment]
This was already implemented. The static event is only the must easy way of consuming log messages without having classes implemented etc. It was also possible to specify a custom handler which adds some custom code like adding own IDs etc. 

@JanEggers So who will revert it? I can do it. I would leave the Factory as it is. Maybe we can keep some parts of the DI approach to allow injection of classes for testing etc.

**Comment by JTrotta** [comment]
As I told you some days ago, I completely disagree in using DI (IOC) inside a library that should be used into other projects. It should be matter of the "host"  project to select and use the right DI (IOC) library. Of course it's a  matter of choice, and with some "extra" work it can be used, but @ChristianRiedl  sentence is perfect to define this kind of situation: "_it leads to more problems that it solves_. "

We should take it off.

**Comment by 949f45ac** [comment]
Hi, quickly jumping in here, as I’ve been struggling to use this library on Xamarin Android 7 for about a week now, for similar reasons.

Could be due to all kinds of other things also set up for my project, but basically the Microsoft.Extensions.* packages were pulling in System.* packages (netstandard versions) that clashed with the System.dll and System.Core.dll libs included with Xamarin. This manifested in "VTable setup failed" errors when starting the app. But I couldn’t exclude these packages that MS.Ext was pulling in, because some APIs (e.g. System.AppContext and System.Buffers) apparently weren’t available from the Xamarin dlls. Or in any case some component tried to specifically load System.Buffers.dll on app launch, and failed, which made the app stall on launch indefinitely.

Entirely forgoing the Xamarin-provided System dll’s in favour of netstandard ones was also not possible, as some APIs absolutely needed by Xamarin Android are only available from netstandard 2.0, which needs Android 8. This notably concerns System.CodeDom.Compiler, because `GeneratedAttribute` is used in the autogenerated Resource.Designer.cs.

Anyways, after reading in this issue that you initially didn’t use MS.Ext, I reverted to MQTTnet 2.3.1 and now things appear to be working.
Just wanted to post this here in favour of removing the MS.Ext deps again.

ps: I can do a detailed bug report for my issues, if you want, but if you remove the deps, I guess it does not matter.

**Comment by JanEggers** [comment]
just go ahead im quite busy at work currently....

**Comment by JTrotta** [comment]
I can help in testing phase on MONO.

**Comment by chkr1011** [comment]
@JanEggers Yes me too. I will start with it in the evening 😄

**Comment by chkr1011** [comment]
@ChristianRiedl @JTrotta @JanEggers @949f45ac I release a RC version of 2.5.3 (as "2.5.3-rc1" nuget) which has no external references. There are some minor breaking changes in logging but the other stuff should work without changes. I will now test on my systems.

**Comment by ChristianRiedl** [comment]
The solution is ok for me. I tested 2.5.3 client side successfully. Can you publish AspNetCore 2.5.3-rc1 ?

**Comment by JTrotta** [comment]
Please give me two hours from now to test it

**Comment by JTrotta** [comment]
It works : MONO 5.4.1.6. Only two libraries, 
![image](https://user-images.githubusercontent.com/2145654/33176878-e9d6f5a2-d060-11e7-8c0d-550527b5b8af.png)

You got it!

**Comment by chkr1011** [comment]
@ChristianRiedl I published a fixed version of the AspNetCore package. On my machine it works. There is only one breaking change in providing the options. Please let me know if this works.

**Comment by ChristianRiedl** [comment]
@chkr1011 It is working, thank you very much.
