### ISSUE TITLE
Enable WebSocket Support

### ISSUE THREAD

**Issue by highwingers** [chkr1011/MQTTnet#1173]
### Describe your question
I am able to connect to my MQTT Server hosted inside a Console App (using TCP port 1883), how do I enable my Console app to serve WebSockets as well? Basically I want both, TCP & We socket (Http) support.

### Which project is your question related to?

- Server

**Comment by chkr1011** [comment]
You need to create  an ASPnet.Core application first. Then you can use MQTTnet to expose a WebSocket based connection.

**Comment by SeppPenner** [comment]
For the ASPnetCore application follow https://github.com/chkr1011/MQTTnet/wiki/Server#aspnet-core-integration and https://github.com/chkr1011/MQTTnet/wiki/Server#using-websockets-with-net50 for the setup and the WebSocket support. If you have concrete questions afterwards, you can contact us here again :)
