### ISSUE TITLE
Need help with example because I'm stupid

### ISSUE THREAD

**Issue by VizDock** [chkr1011/MQTTnet#1179]
Hi
I'm using .net framework.
Could someone please give me example how to create/instantiate mqttrpcclient and mqttrpcClientOptions based on existing client, to send async request and to receive response from other party.

Also, I have a question, is it possible to use broker as RPCclient to send RPC request to client and to receive response from it? Because I use broker in windows service to publish messages to other devices.. I don't need to create client for that.

Thanks

Edit:
I managed to use RpcClient by creating managedMqttClient and pass it's IMqttClient because I can't find a way to use broker/server for creating RpcClient.
I don't know if that is even possible?

**Comment by VizDock** [comment]
Hi
Thanks, I managed to solve it.
I couldn't use mqttserver to send RPC messages, I had to create additional client to do it.

**Comment by SeppPenner** [comment]
I assume that this is now solved.
