### ISSUE TITLE
When is the next Release Planned for this Project, may be 3.0.16

### ISSUE THREAD

**Issue by phanisrinivas13** [chkr1011/MQTTnet#1181]
### Describe your question
Would like to integrate some of the recent fixes made especially the one #1134(Disallow to call MqttClient.ConnectAsync while Disconnect is pending), would like to know when is next release planned.

### Which project is your question related to?

- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

**Comment by chkr1011** [comment]
Hi I will Release the next Version at the next Weekend.

**Comment by phanisrinivas13** [comment]
Thank you Christian, will wait for the release
