### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by dengchenhua** [chkr1011/MQTTnet#1189]
### Describe your question
When i test  mqttnet performance，1500 topic published every second，the cpu utilization rate up to 40%  even more
My cpu is I7 9th gen
how can i reduce cpu utilization？

### Which project is your question related to?

- ManagedClient
- MQTTnet.Server standalone

**Comment by ikbalkazanc** [comment]
if you executing program on visual studio, as much as i know, visual studio's limits cpu usage. You run on dotnet cli or change dotnet environment like this maybe can be does
`{
  "profiles": {
    "Broker": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Production"
      }
    }
  }
}
`

**Comment by chkr1011** [comment]
Which QoS level to you use? You get the fastest performance with QoS 0. If you problem still exists please reopen the ticket.
