### ISSUE TITLE
Querying connected clients, subscribed events list from server by client

### ISSUE THREAD

**Issue by archerian** [chkr1011/MQTTnet#119]
First of all many thanks for building this library. I'm migrating from an old .ocx pseudo publish/subscribe framework and MQTTnet seems like a great fit for the new framework we need. We have a lot of legacy apps that rely on the .ocx framework functions, some of which are GetAllClients, GetAllEvents, GetClientInfo, GetEventInfo function calls on the client side. Any ideas on how to get these functions to be supported?

**Comment by chkr1011** [comment]
Hi,
thanks for your feedback. So you want to get the connected clients (GetAllClients) using a client? And all events? Is that correct?

Best regards
Christian

**Comment by archerian** [comment]
Christian,

Yes, you are correct. Something along the lines of having a #SYS topic with updates on connected clients and their parameters, subscribed events and their parameters.

Thanks
Arun

**Comment by JanEggers** [comment]
from my point of view this would be an antipattern and security risk. I dont think it should be provided on library level. if you want to use mqtt that way you can still define your own messages and publish  them when you see fit.

**Comment by archerian** [comment]
@JanEggers glad to know your viewpoint, if this were not part of the standard library can you or Christian recommend ideas on where would I ideally implement this in MQTTnet? I have seen a method on StackOverflow that utilizes Retained messages and LastWill but I'm thinkingfor my particular case it might need more server side changes to retain an updated cache of connected clients and subscribed events.

Just to add more context, in my scenario the broker and clients run over a private network and are all in a 'trusted' domain. Regular application clients don't need or use these 'status' data, they operate using what are currently implemented MQTTnet/MQTT standard features. We have 2 applications that are used to monitor and troubleshoot connection issues, they have a UI which when connected to the server shows two tabs - connected events, clients and various operations on these tabs like clicking a client shows its subscribed events and vice versa, last time an event was triggered.

**Comment by chkr1011** [comment]
I also agree that this is nothing for a base library. But your requirements can be implemented in a layer on top of that library. The server is also able to handle all incoming messages. No subscribe but you can check the topic on your own. Then you can build that requirements without changing this library.

You can then publish them with a retain flag etc. to store that data for clients which will connect later.

**Comment by JanEggers** [comment]
> I'm thinkingfor my particular case it might need more server side changes

nope the server already knows everything you need. The Server provides a list of connected clients and events in case a client connects or disconnects. 

https://github.com/chkr1011/MQTTnet/blob/861d3dfa0f4503d9b7cf44612bf5fb5778edba43/MQTTnet.Core/Server/MqttServer.cs#L46-L54

so all you need to do is wire up eventhandlers and publish that information somehow. id rather use the server side events than will messages, as the client has to provide last will and for monitoring there should be  no client code needed. 

and id rather use a seperate api like http to query the list of connected clients. that way this kind of monitoring events dont get published on the same port your regular stuff is implemented. 

maybe you could integrate with https://github.com/dotnet-architecture/HealthChecks or https://azure.microsoft.com/de-de/services/application-insights/ depending on your needs

**Comment by JanEggers** [comment]
maybe we could add an api to get the list of subscribed topics for clientId or provide that information with the connectedclient class

**Comment by chkr1011** [comment]
@JanEggers Good idea. Let's put this on the list for 2.6.0.

**Comment by archerian** [comment]
Thanks @chkr1011  and @JanEggers for all the help.
