### ISSUE TITLE
MqttClient connect to server and subscribe topics but can't receive and publish messages on Android

### ISSUE THREAD

**Issue by KoroshRH** [chkr1011/MQTTnet#1194]
Hello,
We implemented MqttNet in our mobile game for real-time communications in the Unity game engine
(MQTT server implemented a long time ago and works correctly for recent builds with another game engine that MQTT implementation was android native, now we migrate our game to Unity game engine)
MQTT system works properly in editor mode of Unity but when we test it on the android build, the app can't receive and publish messages
the logs tell us that client connects to the server and successfully subscribes to the topics but can't publish any messages due to the timeout.
Also when we send messages to this client, the ApplicationMessageReceivedHandler doesn't call.

**Comment by KoroshRH** [comment]
Hi @moncio,

Our problem is fixed now and our mistake was using some unnecessary filters on received client id in broker code and also a wrong client id format from our client code.

But about your problem i think it can be from your broker address and specifically port number.

I hope it can be useful for you

**Comment by moncio** [comment]
Hi @KoroshRH ,

Great to read your problem is fixed, in my case I need to connect to the server through websocket transport but I dont know why I'm not able to establish the proper connection, this is my current approach:

```
var builder = new MqttClientOptionsBuilder()
                .WithClientId(Guid.NewGuid().ToString())
                .WithWebSocketServer("localhost:443/ws")
                .WithCredentials(username, password)
                .WithTls()
                .WithCleanSession();

        this.mqttOptions = builder.Build();

        this.mqttClient = new MqttFactory().CreateMqttClient();

        this.mqttClient.ConnectedHandler = new MqttClientConnectedHandlerDelegate(OnConnected);
        this.mqttClient.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(OnDisconnected);
        this.mqttClient.UseApplicationMessageReceivedHandler(OnMessageReceived);
```

is this the right way to do that? Thank you!

**Comment by KoroshRH** [comment]
Use this code instead of `.WithTls()`:
```
.WithTls(new MqttClientOptionsBuilderTlsParameters
    {
        UseTls = true,
        CertificateValidationHandler = (MqttClientCertificateValidationCallbackContext x) =>
        {
            return true;
        }
    })
```
If with this code you faced problem either, removing it and try again.

**Comment by moncio** [comment]
I have the next problem:

_Remote certificate validation callback is not supported when using 'net461'._

**Comment by KoroshRH** [comment]
Remove this line. Just use `UseTls = true`.

**Comment by moncio** [comment]
It continues failing, I think it may be a problem related with certificates because I have exposed the websocket to an extern url, use this one comes the problems but trying the connection against the internal url, everything is ok

**Comment by moncio** [comment]
Hi again @KoroshRH , first of all I really appreciate your help, finally the client connects to the broker succesfully, I had to add the host to the headers in the request. Now I have your original problem, I see the client is connected but no messages sent to the broker and problems for subscribing to the topic, how do you solve it?

Thank you and sorry for so many questions.

**Comment by KoroshRH** [comment]
Hi @moncio, it is very good to hear that your problem is fixed now.
It was a pleasure to have a conversation with you.
