### ISSUE TITLE
Design issue with dependency resolution and avoiding the service locator pattern

### ISSUE THREAD

**Issue by BrightSoul** [chkr1011/MQTTnet#1199]
First of all, thanks to everyone who participated in this extendable and reliable project. I really am grateful for it but I also feel there's a stone in my shoe.
In my ASP.NET Core application, I provided my own implementation for a few components such as the connection validator, the subscription interceptor and the retained message manager. The `ConfigureServices` method of my `Startup` class looks like this:
```cshapr
services
  .AddHostedMqttServerWithServices(mqttServerOptions =>
  {
    mqttServerOptions
      .WithConnectionValidator(new CustomMqttConnectionValidator())
      .WithSubscriptionInterceptor(new CustomMqttSubscriptionInterceptor())
      .WithRetainedMessagesManager(new CustomMqttRetainedMessageManager())
      .WithoutDefaultEndpoint();
  });
```

As you can see, MQTTnet forces me to provide my own custom components **instances** but that's not ideal because they, in turn, they depend on other services I've registered with the ASP.NET Core dependency container. So, in order to resolve those dependencies, my components are forced to use the [ugly service locator pattern which I'd like to avoid](https://odetocode.com/blogs/scott/archive/2016/02/18/avoiding-the-service-locator-pattern-in-asp-net-core.aspx). This is not just a code style issue: I'm having a hard time testing my components because the service locator pattern makes it harder to mock their dependencies.

As suggested in [this other issue](https://github.com/chkr1011/MQTTnet/issues/947) by @ovidiaconescu, I think it would be better if we could register our own implementations with the dependency container, an approach used by other projects, such as Microsoft's ASP.NET Core Identity.
```csharp
services.AddSingleton<IMqttServerConnectionValidator, CustomMqttConnectionValidator>();
services.AddSingleton<IMqttServerSubscriptionInterceptor, CustomMqttSubscriptionInterceptor>();
services.AddSingleton<IMqttRetainedMessagesManager, CustomMqttRetainedMessageManager>();
```
I'm suggesting the MqttServer should leverage the `IServiceProvider` for its dependency resolutions.
Thanks.

**Comment by mKenfenheuer** [comment]
@BrightSoul I've got the exact same stone in my shoe too. I'm using a EFCore DBContext to validate clients and subscriptions to topics. Having this on a single DBContext is far from ideal ass there are many clients connecting regularly in my case.

I'll have a look on how this could be achieved. 
However, ideas and hints are always welcome - i haven't worked with this codebase before ;)

**Comment by mKenfenheuer** [comment]
What i have found out by now is that you can use the following to inject the validators to the mqtt server component:


Create your validators as singleton dependencies with a dependency to an `IServiceScopeFactory`.
In the validation tasks you can create a scope and resolve the services required.

```
public class MqttConnectionValidator : IMqttServerConnectionValidator
{
    private readonly IServiceScopeFactory _serviceScopeFactory;

    public MqttConnectionValidator(IServiceScopeFactory serviceScopeFactory)
    {
        _serviceScopeFactory = serviceScopeFactory;
    }

    Task IMqttServerConnectionValidator.ValidateConnectionAsync(MqttConnectionValidatorContext context)
    {
        using (var scope = _serviceScopeFactory.CreateScope())
        {
            var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
            context.ReasonCode = MqttConnectReasonCode.Success;
        }
        return Task.CompletedTask;
    }
}
```

In your Startup.cs register the validator components as singletons as follows:

```
services.AddSingleton<MqttConnectionValidator>();
```


Then add your hosted MQTT service with `services.AddHostedMqttServerWithServices()`. There you can use the `ServiceProvider` from the `AspNetMqttServerOptionsBuilder` to resolve the validators.

```
services.AddHostedMqttServerWithServices(options =>
{
    var scope = options.ServiceProvider.CreateScope();
    options.WithDefaultEndpoint().WithDefaultEndpointPort(1883);
    options.WithConnectionValidator(scope.ServiceProvider.GetRequiredService<MqttConnectionValidator>());
});
```

Let me know if this works out for you!

**Comment by BrightSoul** [comment]
@mKenfenheuer 
> Let me know if this works out for you!

YES! Indeed, thanks a ton for your solution! I implemented it right away in my project. At least I can now provide a mock implementation of `IServiceScopeFactory` to my components' constructor (and this eases unit testing which was my immediate concern).

> Edit: Unfortunately we cannot use anything else than a singleton as the validators are singletons by design.

No problem since, as you said, I could always create a scope. I was already doing it in order to get a reference to ther scoped dependencies such as a `DbContext` and `IHttpContextAccessor`.

Thanks again! I'd like to keep the issue open in case project maintaners wanted to consider/implement proper dependency resolution for a future release.

**Comment by JanEggers** [comment]
@BrightSoul I will close the issue. I integrated microsoft.extensions.dependencyinjection 3 years ago and it was met by backlash and had to be removed again.
