### ISSUE TITLE
Create server with options.

### ISSUE THREAD

**Issue by hunterius-prime** [chkr1011/MQTTnet#120]
I don't know if I am doing something wrong but after update to version 2.5.3 CreateMqttServer doesn't offer possibility to use options as parameters as is stated in Wiki.
Definition of MqttFactory now looks :

    public class MqttFactory : IMqttClientFactory, IMqttServerFactory
    {
        public MqttFactory();

        public IManagedMqttClient CreateManagedMqttClient();
        public IManagedMqttClient CreateManagedMqttClient(IMqttNetLogger logger);
        public IMqttClient CreateMqttClient();
        public IMqttClient CreateMqttClient(IMqttNetLogger logger);
        public IMqttServer CreateMqttServer();
        public IMqttServer CreateMqttServer(IEnumerable<IMqttServerAdapter> adapters, IMqttNetLogger logger);
    }

What I am doing wrong?

**Comment by archerian** [comment]
I noticed that change too.. this works for me with 2.5.3

           // Start a MQTT server.
            IMqttServer mqttServer = new MqttFactory().CreateMqttServer();
            MqttServerOptions options = new MqttServerOptions();
            options.DefaultEndpointOptions.Port = 13571;
          
            mqttServer.StartAsync(options);

**Comment by hunterius-prime** [comment]
Thank you I already figured it out , just only want to point out that changing surface of library is not something you would expect from "patch" version update. It definitely need something as "release notes" or wiki update ... at least for heads-up.

**Comment by chkr1011** [comment]
Hi,
due to 3rd-Party library issues this have changed and caused breaking changes. The Wiki will be updated soon.

Best regards
Christian
