### ISSUE TITLE
unable to create mqtt server for .net core 2.0

### ISSUE THREAD

**Issue by ganeshmahajan1985** [chkr1011/MQTTnet#121]
Hi I am trying to create mqtt server using the code from wiki, but i am getting below error, please help.

My Code
                ```

>  `var optionsBuilder = new MqttServerOptionsBuilder()
>                  .WithConnectionBacklog(100)
>                  .WithDefaultEndpointPort(1884);
> 
>                 var mqttServer = new MqttFactory().CreateMqttServer();
>                 mqttServer.ClientDisconnected += (s, e) =>
>                 {
>                     Console.Write("Client disconnected event fired.");
>                 };
> 
>                 await mqttServer.StartAsync(optionsBuilder.Build());
> 
>                 Console.WriteLine("Press any key to exit.");
>                 Console.ReadLine();
> 
>                 await mqttServer.StopAsync();

```

Getting below Error  --- 

>> [2017-11-27T07:46:23.8408036+00:00] [2] [MqttServer] [Info]: Started.
Press any key to exit.
>> [2017-11-27T07:46:23.8586061+00:00] [2] [MqttServer] [Info]: Stopped.
>> [2017-11-27T07:46:23.8572258+00:00] [10] [MqttServerAdapter] [Error]: Error while accepting connection at default endpoint.
System.Net.Sockets.SocketException (0x80004005): Operation canceled
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttServerAdapter.<AcceptDefaultEndpointConnectionsAsync>d__12.MoveNext()

**Comment by ganeshmahajan1985** [comment]
Also i have tried to handled the server started event and removed the server stop call.
but it is also not getting executed.
```
mqttServer.Started += (s, e) =>
                {
                    Console.Write("Server started now.");
                };
```
there is nothing in console.. ideally if server is started then this line should get printed on console.

**Comment by ganeshmahajan1985** [comment]
My Bad!

I am creating the Azure IoT Edge module inside my containerized application.
Azure IoT edge itself needs a docker to run its runtime. So there was problem of the ports. I need to do port forwarding, then I hope this will work.

**Comment by chkr1011** [comment]
Hi,
thank you for reporting the issue. The exception after the stop is still an issue which will be fixed 😄 
If you need more assistance please let me know.
Best regards
Christian

**Comment by ganeshmahajan1985** [comment]
Hi Christian,
After port forwarding everything working fine.

Thanks
Ganesh
