### ISSUE TITLE
When ClientMessageQueueInterceptor is called?

### ISSUE THREAD

**Issue by elektromntr** [chkr1011/MQTTnet#1210]
### Describe your question
When **ClientMessageQueueInterceptor** is called? Is it when message reception is confirmed by subscriber? 
I mean the option on server _.WithClientMessageQueueInterceptor()_

### Which project is your question related to?
- Server

**Comment by chkr1011** [comment]
The interceptor is called when a message is being queued for a client. So when you publish message A and clients X and Y have subscribed to the topic the interceptor will be called two times before the message is added to the clients queue. It will be sent later.
