### ISSUE TITLE
Cannot connect to secured hivemq cloud

### ISSUE THREAD

**Issue by Freshdouble** [chkr1011/MQTTnet#1211]
### Describe your question
I have a private cloud broker at hivemq with the tls port at 8883 and no unsecured port.

When im trying to connect i get a ssl error that the server and client doesn't have a matching algorithm. I think this is TLS connection error so i tried to disable the certificate validation but without success.

My connection options are:
```
options = new MqttClientOptionsBuilder()
                .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V500)
                .WithTcpServer("*******", 8883)
                .WithCredentials("******", "*******")
               .WithTls(new MqttClientOptionsBuilderTlsParameters()
                {
                    AllowUntrustedCertificates = true,
                    IgnoreCertificateChainErrors = true,
                    IgnoreCertificateRevocationErrors = true
                })
                .WithCleanSession()
                .Build();
```

Ive validated the server credentials with hivemq web client.

Does anybody have used the client to connect to a secured hivemq cluster?
Connecting to the public server without tls is no problem.

### Which project is your question related to?

- Client

**Comment by SeppPenner** [comment]
I guess, the error is the following: `The client and server cannot communicate, because they do not possess a common algorithm.`:

Therefore, you need to manually downgrade the TLS settings of MqttNet to TLS1.2 (instead of TLS1.3) as in the example:

```csharp
options = new MqttClientOptionsBuilder()
    .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V500)
    .WithTcpServer("*******", 8883)
    .WithCredentials("******", "*******")
    .WithTls(new MqttClientOptionsBuilderTlsParameters()
    {
        UseTls = true, // Is set by default to true, I guess...
        SslProtocol = SslProtocols.Tls12, // TLS downgrade
        AllowUntrustedCertificates = true, // Not sure if this is really needed...
        IgnoreCertificateChainErrors = true, // Not sure if this is really needed...
        IgnoreCertificateRevocationErrors = true, // Not sure if this is really needed...
        CertificateValidationHandler = (w) => true // Not sure if this is really needed...
    })
    .WithCleanSession()
    .Build();
```

**Comment by chkr1011** [comment]
If the problem still occurs please reopne the ticket. I assume the above comment solves your issue.
