### ISSUE TITLE
how to block a message in "WithApplicationMessageInterceptor"

### ISSUE THREAD

**Issue by mfjiang** [chkr1011/MQTTnet#1214]
### Describe your question
how to block a message in "WithApplicationMessageInterceptor"?

I want to block a message  when client token has broken.
The token is inside of payload data.
I can't find any way to cancel the message before publish it.

### Which project is your question related to?

- MQTTnet.Server standalone
- Server

**Comment by SeppPenner** [comment]
Please check out the example code under https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-application-messages. What you want to do is something like this:

```csharp
var isTokenValid = ...; // Whatever check you need inside the payload data.

if (!isTokenValid)
{
    context.AcceptPublish = false;
    return;
}
```
