### ISSUE TITLE
Connection gets terminated immediately at StartAsync

### ISSUE THREAD

**Issue by sheepinwild** [chkr1011/MQTTnet#122]
`var caCert = new X509Certificate("../test.crt");
            var cbytes = caCert.Export(X509ContentType.Cert);

            var options = new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                .WithClientOptions(new MqttClientOptionsBuilder()
                                   .WithCredentials("username", "password")
                                    .WithClientId("Client1")
                                   .WithTcpServer("broker.test.com", 443)
                                   .WithTls(false, false, false, cbytes).Build())
                .Build();

            var mqttClient = new MqttFactory().CreateManagedMqttClient();

            mqttClient.StartAsync(options).GetAwaiter().GetResult();
`

The connection gets Finned after a SSL Continuation Data package being sent through.

Am I doing something wrong here?

**Comment by sheepinwild** [comment]
okay I've found out that I need to add this line(is there a way to put this in the builder btw?).

options.ClientOptions.ChannelOptions.TlsOptions.UseTls = true;

However what's happening this time is:
Server to Client: Change Cipher Spec, Encrypted Handshake Message
Client to Server: 59080 -> 443 [ACK] ...
Client to Server: Application Data
Server to Client: Encrypted Alert
Server to Client: 443 -> 59080 [FIN, ACK] ...

**Comment by chkr1011** [comment]
Hi,
the builder already has a _WithTls_ method. It sets the "UseTls" property always to true and the other parameters as they are provided.
Best regards
Christian

**Comment by sheepinwild** [comment]
Thanks.

However I still cannot get the connection established. do you see anything wrong in my code?

**Comment by sheepinwild** [comment]
`			MemoryPersistence persistence = new MemoryPersistence();
			String clientId = "andr_" + UUID.randomUUID().toString().substring(0, 8) + "_"
					+ System.currentTimeMillis() % 10000;

			// CA cert is used to authenticate the server
			FileInputStream in = new FileInputStream(
					System.getProperty("user.dir") + "/Cert/test.crt");
			CertificateFactory cf = CertificateFactory.getInstance("X.509");
			X509Certificate caCert = (X509Certificate) cf.generateCertificate(in);
			KeyStore caKs = KeyStore.getInstance(KeyStore.getDefaultType());
			caKs.load(null, null);
			caKs.setCertificateEntry("ca-certificate", caCert);
			TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
			tmf.init(caKs);

			// create SSL socket factory
			SSLContext context = SSLContext.getInstance("TLSv1.2");
			context.init(null, tmf.getTrustManagers(), null);

			mqttClient = new MqttClient(broker, clientId, persistence);
			MqttConnectOptions connOpts = new MqttConnectOptions();
			connOpts.setUserName(userName);
			connOpts.setPassword(password.toCharArray());
			connOpts.setSocketFactory(context.getSocketFactory());
			connOpts.setCleanSession(true);
			// System.out.println("Connecting to broker: "+broker);
			mqttClient.connect(connOpts);`


This is a Java implementation that is able to connect.

**Comment by hunterius-prime** [comment]
As it may be OT , I wouldn't recommend using port 443 as it is reserved port for http over ssl and cross-using ports could be considered as bad practice. You can run into bunch of unexpected network behaviors or problems.

are you using client certificate in server/client authentication? It failed even if you are explicitly set to ignore all cert errors?

**Comment by sheepinwild** [comment]
Eventually I got it figured it out. Our broker happen to be using an older version of mqtt protocol: 3.1, which is probably not supported by mqttnet even though you can specify it in the code. I used another library m2mqttdotnetcore and it worked in this scenario...

**Comment by chkr1011** [comment]
Version 3.2 is also supported. Please share a trace so I can follow up the package flow. Processing trace messages is described in the Wiki.

Best regards
Christian
