### ISSUE TITLE
MqttNetTrace removed in version 2.5.3

### ISSUE THREAD

**Issue by hunterius-prime** [chkr1011/MQTTnet#123]
As MqttNetTrace has been removed in version 2.5.3 , what is now suggested way to do simple trace ( wiki) ?

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/a72516fdcc20105e5a808242acf63cc747620633/MQTTnet.Core/Diagnostics/MqttNetGlobalLog.cs#L5

is equivalent

**Comment by hunterius-prime** [comment]
I am trying this, with no success ... never hit log :-( ..... am I missing something?

static void Main(string[] args)
        {
            string certPath = @"D:\xxxxxxxxxxxxxxxxxxxx\test.cer";
            X509Certificate certificate = new X509Certificate(certPath, "");

            var logger = new MqttNetLogger();
            logger.LogMessagePublished += Logger_LogMessagePublished;
            var adapters = new List<IMqttServerAdapter> { new MqttServerAdapter(logger) };

            var server = new MqttFactory().CreateMqttServer(adapters, logger);

            var options = new MqttServerOptionsBuilder()
                 .WithEncryptedEndpoint()
                 .WithEncryptionCertificate(certificate.Export(X509ContentType.Cert))
                 .Build();

            server.StartAsync(options);
            Console.WriteLine("MQTT Server is UP and running.");

            Console.ReadLine();
            server.StopAsync();
        }

        private static void Logger_LogMessagePublished(object sender, MqttNetLogMessagePublishedEventArgs e)
        {
            Console.WriteLine("LOG: .....");
        }

**Comment by chkr1011** [comment]
Hi, I updated the Wiki. Please have a look there. 

Your code looks OK to me. I will check if there is an issue in the code.

**Comment by hunterius-prime** [comment]
Thank you very much, tracing is now working.
