### ISSUE TITLE
Client cannot connect when running on .NET Core 3.1 or .NET 5

### ISSUE THREAD

**Issue by janpalas** [chkr1011/MQTTnet#1231]
I have sample code that works perfectly when project (clean console project) runs on .NET Core 2.2:
```csharp
var options = new MqttClientOptionsBuilder()
    .WithClientId("SubscriberId")
    .WithTcpServer("*****", 8888)
    .WithCredentials("****", "****")
    .WithTls()
    .WithProtocolVersion(MqttProtocolVersion.V500)
    .WithCleanSession()
    .Build();

IMqttClient client = factory.CreateMqttClient();
client.UseConnectedHandler(async e =>
{
    Console.WriteLine("Connected.");
});

client.UseDisconnectedHandler(e =>
{
    Console.WriteLine("Disconnected.");
});

await client.ConnectAsync(options);
```
However, when I switch target framework to .NET Core 3.1 or .NET 5, the disconnected handler is executed right after calling `await client.ConnectAsync(options)` with following `MqttClientDisconnectedEventArgs`:

```text
ClientWasConnected: false
Reason: UnspecifiedError
Exception: MqttCommunicationException: "The client and server cannot communicate, because they do not possess a common algorithm."
```

The same situation (and error) occurs when I use `IManagedMqttClient` instead of `IMqttClient`.
NuGet package version is 3.0.16

**Comment by janpalas** [comment]
With further experimenting, I found out that problem could be with handling TLS on .NET 3.1 / .NET 5. When I add following option:

```csharp
.WithTls(new MqttClientOptionsBuilderTlsParameters
{
    UseTls = true,
    SslProtocol = System.Security.Authentication.SslProtocols.Tls12
})
```
The code starts to behave as expected and successfully connects.

**Comment by SeppPenner** [comment]
Yes, this is due to the fact that Microsoft uses TLS1.3 as default in Net5.0+ (and most of the public brokers don't support TLS1.3 yet). Similar to https://github.com/chkr1011/MQTTnet/issues/1211 and https://github.com/chkr1011/MQTTnet/issues/1207.
