### ISSUE TITLE
Subscribe  QoS cannot be set

### ISSUE THREAD

**Issue by adriannowaq** [chkr1011/MQTTnet#1240]
Hi, when I publish message with QoS 1 or 2, it works well, but I can't listen with qos 1 or 2 setting because I cant find the setting, it's always set to 0, is it possible to change qos while listening?

**Comment by pver** [comment]
I think you're looking for this method, which accepts the qos:
https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Client/MqttClientExtensions.cs#L171

(or via the topic filter properties)

**Comment by adriannowaq** [comment]
Thank you so much, works  @pver
