### ISSUE TITLE
What does KeepAliveMonitorInterval do?

### ISSUE THREAD

**Issue by abimr** [chkr1011/MQTTnet#1245]
### Describe your question
I have upgraded an old project to the latest version of MQTTNet. I have implemented the IMQTTServerOptions interface which got a new property KeepAliveMonitorInterval. What does this property do?

### Which project is your question related to?

- MQTTnet.Server
- MQTTnet.AspNetCore

**Comment by chkr1011** [comment]
It allows to configure the interval in which the keep alive is checked for a all clients. Let's say every 1 second the server should check if a keep alive is expired.
