### ISSUE TITLE
Do sever，when Qos=0 Subscribe， Suback Qos=1

### ISSUE THREAD

**Issue by redbeans2017** [chkr1011/MQTTnet#125]
Thank you very much for your project，Create the project using Vs2017,C#, run in win7 64bit,Use Mqttnet 2.5.2 to du server.Connect an MQTT hardware, hardware work in Qos= 0, and if you return Qos= 1, hardware will disconnect actively, how can I set Qos=0 in the code。

**Comment by redbeans2017** [comment]
![default](https://user-images.githubusercontent.com/34080535/33354112-26060a7e-d4ec-11e7-9ccc-aa72cf534155.png)

**Comment by chkr1011** [comment]
Hi,
first please try with version 2.5.3 as this is the latest version containing some bugfixes.
Then I don't understand your question completely. As far as I understand your device (hardware) only uses QoS 0 and from another client you use QoS 1 right? When a device is subscribing it also sends the maximum OoS level which can be used for that device. If the device sends 0 the server will send all messages with QoS 0 to that device even if the other client uses QoS 1 or even QoS 2. 

Can you share the trace from the client? In the Wiki you can find some code how to enable this. Then I can try to reproduce the issue.

Best regards
Christian

**Comment by redbeans2017** [comment]
Hi，
Thank you for your reply，Yesterday，try with V2.5.3 ，The problem remains.
hardware only uses Qos 0 ,if hardware receive Qos=1  is disconnected actively.
question：Only one client ，the client uses Qos 0.The device sends Qos 0， the server to device Qos 1.
Do you understand my question？

**Comment by chkr1011** [comment]
OK now I got it. But I am not sure if this is a problem in the server. I checked the documentation of MQTT and found this:

> The Server might grant a lower maximum QoS than the subscriber requested. The QoS of Payload Messages sent in response to a Subscription MUST be the minimum of the QoS of the originally published message and the maximum QoS granted by the Server.

As far as I understand this the returned QoS CAN be higher (it is also called MaximumQoS). My clients are working with that code without problems (PubSubClient for Arduino).

Can you please tell me which library you use?

**Comment by chkr1011** [comment]
I checked the implementation in other MQTT servers and I can see that they behave differently. They work like you explained. I will fix this issue in the next version.

**Comment by redbeans2017** [comment]
Thank you very much. It's great.

**Comment by chkr1011** [comment]
@redbeans2017 I release a preview of the next version as a nuget package. Please let me know if it fixes the issue for you.

**Comment by chkr1011** [comment]
Version 2.6.0 is now released.
Best regards
Christian
