### ISSUE TITLE
Logging some messages to a database

### ISSUE THREAD

**Issue by GeoffArmstrong** [chkr1011/MQTTnet#1252]
### Describe your question
I'm using MQTTnet Server in a ASP.NET Core 3.1 app, with clients connecting via webstockets.  I need to add a feature where some messages from some clients need to be stored in a database.  The plan is to use WithApplicationMessageInterceptor and cause the messages to be saved - but I'm looking for performance advice.

I don't want to do anything that will substantially degrade the performance of MQTTnet Server. I assume that just writing to a database in the WithApplicationMessageInterceptor callback is a terrible idea - even if they're async calls - but I want to make sure that this is indeed the case before necessarily creating a in-memory queue and a IHostedService to save these messages to a database.

I'm interested in learning about the best practices in this kind of scenario. This is a QoS 0 situation - if messages get lost when the broker is shut down, it's not the end of the world.

### Which project is your question related to?

- Server

**Comment by JanEggers** [comment]
If you dont need the guarantee that the messages are stored then I would put them into an observable. then you can subscribe to that observable on a different thread and batch the events to store them with something like ef bulkextensions

**Comment by GeoffArmstrong** [comment]
> If you dont need the guarantee that the messages are stored then I would put them into an observable. then you can subscribe to that observable on a different thread and batch the events to store them with something like ef bulkextensions

Thank-you for the suggestion.  I appreciate it!
