### ISSUE TITLE
Is it save to publish a message before awaiting the result of the last publish?

### ISSUE THREAD

**Issue by mg90707** [chkr1011/MQTTnet#1253]
### Describe your question
I'd like to know if it is possible with a MqttClient created by new MqttFactory().CreateMqttClient() to have multiple requests "in-flight". That means can I call e.g.

```
List<Task> publishResults =
const msgResult1 = client.publishAsync(..) 
const msgResult2 = client.publishAsync(..) 

await Task.WhenAll(publishResults)
```

or does every publish have to get finished (awaited) before calling the next.

### Which project is your question related to?
- Client

**Comment by chkr1011** [comment]
I recommend to wait before the publish is completed. There is no performance gain in sending parallel. It only adds the risk of corrupting data.
