### ISSUE TITLE
Remaining length is invalid. Unable to subscribe to any topic

### ISSUE THREAD

**Issue by shahroze90** [chkr1011/MQTTnet#126]
I am trying to use MQTTNet as a client. I have tried it on .Net Standard 2.0. My code correctly works when i use "broker.hivemq.com" as broker ip. I am using Mosquitto MQTT as broker. It works correctly when broker is deployed on Windows machine. However, when i try to connect it to broker on **LINUX** machine, i get the following error:
>> [2017-11-29T16:47:59.8800740+05:00] [4] [MqttClient] [Warning]: MQTT communication exception while receiving packets.

MQTTnet.Core.Exceptions.MqttCommunicationException: Remaining length is invalid (Data=238,244,166,3). ---> MQTTnet.Core.Exceptions.MqttProtocolViolationException: Remaining length is invalid (Data=238,244,166,3).
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadBodyLengthFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadHeaderFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Adapter.MqttChannelAdapter.<ReceiveAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Adapter.MqttChannelAdapter.<>c__DisplayClass11_0.<<ReceivePacketAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Core.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Client.MqttClient.<ReceivePacketsAsync>d__40.MoveNext()

Mosquitto MQTT is only configured for credentials. My client is able to connect to it successfully, the error comes when I try to subscribe to any topic. Here is my code snippet:

`var factory = new MqttFactory();
            var mqttClient = factory.CreateMqttClient();
            var options = new MqttClientOptionsBuilder()
                .WithClientId(Guid.NewGuid().ToString())
                .WithTcpServer("172.18.23.172")
                //.WithTls()
                .WithCleanSession()
                .Build();

            mqttClient.ApplicationMessageReceived += (s, e) =>
            {
                Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
                Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
                Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
                Console.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
                Console.WriteLine();
            };

            mqttClient.Connected += async (s, e) =>
            {
                Console.WriteLine("### CONNECTED WITH SERVER ###");

                // Subscribe to a topic
                await Task.Delay(1000);
                //await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("data/#").Build());
                await mqttClient.SubscribeAsync(new TopicFilter("#"));
                Console.WriteLine("### SUBSCRIBED ###");
            };`

**Comment by chkr1011** [comment]
Hi and thanks for sharing this issue.

I wanted to reproduce the issue but I cannot access the mosquitto test server. So I have to guess or setup a mosquitto server for testing too. 

You mentioned that the broker works fine when deployed to windows. Do you use mosquitto for Windows and Linux? So the same product works on Windows but not on Linux?

Best regards
Christian

**Comment by shahroze90** [comment]
I have set up mosquitto for both windows and Linux. my publisher client is running on UWP and .Net Framework 4.6. Publisher is able to connect to Mosquitto broker on both Linux and Windows., and publishes fine.

My subscriber is running on .Net Standard 2.0. When it connect it to windows, it connects and subscribes without giving "remaining length is invalid" error. When i connect it to broker on Linux, it connects but then gives "remaining length is invalid" error. In both the situations, i am not able to receive data at subscriber end.

My mosquitto configuration file is as follows on linux:
allow_anonymous false
password_file /etc/mosquitto/passwd

**Comment by chkr1011** [comment]
I installed a mosquitto server in a Ubuntu VM. I tested the connection from a netcore 2.0 app running on windows and I can connect, subscribe and publish without issues. Is there something which I am missing in my setup?

**Comment by shahroze90** [comment]
I just discovered that when i run the Mosquitto broker from terminal, both my client and publishers work fine. 
`mosquitto` -c /etc/mosquitto/mosquitto.conf
However, when i run it as a service, subscriber does not work.

**Comment by chkr1011** [comment]
I believe this problem is not related to this library because also running as a service the packets should have the same format.
