### ISSUE TITLE
MqttApplicationMessageReceived QoS is always 0 ?Java client demo is normal

### ISSUE THREAD

**Issue by L60008028** [chkr1011/MQTTnet#1262]
![企业微信截图_16342905903852](https://user-images.githubusercontent.com/19485497/137468234-6a034912-6ceb-4858-b6d6-b56ae623155a.png)

MQTT.fx  publish 
![image](https://user-images.githubusercontent.com/19485497/137468405-0465d946-1888-4726-ac50-d9f215cf151b.png)

Java client demo Received
![image](https://user-images.githubusercontent.com/19485497/137468874-ce3fa44a-cf47-4260-8fe8-63f951327b4b.png)

**Comment by chkr1011** [comment]
I assume you are using MQTT v5 right?
Did you subscribe to the topic with QoS 2 as well in the C# code?
