### ISSUE TITLE
why GetClientStatusAsync() function working async?

### ISSUE THREAD

**Issue by ikbalkazanc** [chkr1011/MQTTnet#1280]
the question's briefly as in the title. Why GetClientStatusAsync() function working async? This function is getting status from memory. Isn't it? or from remote client? Logically, have to be first way. So, Why is there a need to use async to retrieve data from memory?

**Comment by chkr1011** [comment]
The reason is to keep a stable API. The source of the data might change in the future or other plugins might perform other async operations in the future. So to avoid changing the API later on all APIs in MQTTnet are async right from the beginning.

**Comment by ikbalkazanc** [comment]
So it's all about data consistency. not as expensive as I thought at the time
