### ISSUE TITLE
Use SemVer guidelines for breaking changes

### ISSUE THREAD

**Issue by ridomin** [chkr1011/MQTTnet#1281]
I was using MqttNet 3.0.16, took the 3.0.17 update and found breaking changes (also described in the changelog).

Will be good to follow SemVer practices and bump the major version when there is a public api breaking change.

Also, having the wiki up-to-date will help to understand the changes.  Is there any doc I missed?

**Comment by SeppPenner** [comment]
> Also, having the wiki up-to-date will help to understand the changes. Is there any doc I missed?

I will try to update this soon.

**Comment by chkr1011** [comment]
The version increase is indeed an issue made by me when releasing the last version. The versioning scheme will be changed with the upcoming version 4.0 and following semantic versioning.

**Comment by ridomin** [comment]
>  the upcoming version 4.0

any ETA/Roadmap available?

**Comment by chkr1011** [comment]
No sorry. I am doing this in my free time. So it may be a few weeks or a lot of weeks. But I will at least release a preview for API discussions etc. soon. @SeppPenner Before finally releasing that version we can together update all docs and create a migration document (which basically points to renamed methods etc.).

**Comment by SeppPenner** [comment]
Good idea if you ask me. I will contact you on Gitter.
