### ISSUE TITLE
Release notes 3.1.0 - where's the difference?

### ISSUE THREAD

**Issue by milbrandt** [chkr1011/MQTTnet#1289]
### Describe your question
Release notes 3.1.0.  Whre is the difference in the naming? Is it a spelling error or was it reverted and not removed from release notes?

[Client] Renamed _MqttClientConnectResult_ to _MqttClientConnectResult_ (BREAKING CHANGE!).

**Comment by SeppPenner** [comment]
Seems to me like a copy-paste error. @chkr1011 Can you explain this?

**Comment by chkr1011** [comment]
Yea sorry this is a stupid typo. The original name of the class was _MqttClientAuthenticateResult_. Now it is _MqttClientConnectResult_.

**Comment by SeppPenner** [comment]
I fixed this in https://github.com/chkr1011/MQTTnet/releases/tag/v3.1.0.
