### ISSUE TITLE
More extensive documentation or reference to more sample code

### ISSUE THREAD

**Issue by bdollerup** [chkr1011/MQTTnet#129]
Hi there,

Love the work you are doing, but I do have a request!

I want to use the server API in a home automation solution, but I'm really struggling with implementing anything but the basic server. I would like more extensive documentation as well as more compete sample code.

Thanks!

**Comment by chkr1011** [comment]
Hi,
If you mean documentation about plain MQTT protocol related stuff then I recommend having a look at <https://www.hivemq.com>. There you will find lots of examples and explanations.

If you need more documentation about the components of this project please let me now in which areas you are missing details in the Wiki.

Best regards
Christian

**Comment by bdollerup** [comment]
Hi Christian,

Thanks for getting back to me.

It's not the protocol related stuff. In fact, I've use the client for of your implementation already using a Mosqutto server.  I need an example of how setup the various configuration option as well as the parameters on the server as well as an example of how you would handle user id and passwords.

Thanks!
Bjarne
