### ISSUE TITLE
Object reference not set while disposing MqttClientConnection

### ISSUE THREAD

**Issue by anwarminarso** [chkr1011/MQTTnet#1292]
### Describe the bug
I use MQTTnet Client for my application and have never had a problem. Until I upgraded to version 3.1.0 something strange happened. classic bug "Object reference not set to an instance of an object"

### Which project is your bug related to?
- ManagedClient
- Client

### To Reproduce
1. Using this version of MQTTnet `3.1.0`
2. Using `WebSocket` and connect via `mqtt.js` library
3. Refresh browser frequently

### Screenshots
![2021-11-10_13-47-42](https://user-images.githubusercontent.com/5240703/141064789-ddfae98d-dc61-48bb-9f05-a9c61854aa44.jpg)

### Workaround
change this
```csharp
public void Dispose()
{
  _cancellationToken.Dispose();
}

```
to
```csharp
public void Dispose()
{
   _cancellationToken?.Dispose();
}

```

**Comment by SeppPenner** [comment]
This is already discussed in https://github.com/chkr1011/MQTTnet/pull/1284 and should be fixed with https://github.com/chkr1011/MQTTnet/pull/1288.

**Comment by anwarminarso** [comment]
okay... thank you
