### ISSUE TITLE
More documentation or reference to more sample code

### ISSUE THREAD

**Issue by bdollerup** [chkr1011/MQTTnet#131]
@chkr1011 ,

I still would like some more documentation and sample code on both client and server in particular around the API in general and the options available and their use. Also a sample for both client and server that follow the recommend pattern would be of great help.

Thanks,
Bjarne

**Comment by 1iveowl** [comment]
I think you are barking up the wrong tree here. The Wiki here provides all you need for using the library. At least all I needed to create this: [MQTTClient for Reactive Extensions](https://github.com/1iveowl/MQTTClient.rx) as well as using MQTTnet to create apps for iOS, Android and Windows 10.

For sample: code look at the Tests in this repo.

P.s. Hej Bjarne. Det er Jasper, din tidligere kollega fra MS ;-)

**Comment by chris-steema** [comment]
I knew nothing about MQTT about four hours ago, but before I could use the examples in the Wiki I had to read these excellent [MQTT Essentials](https://www.hivemq.com/mqtt-essentials/) - having done that and having played around with the client and server (broker) code I eventually came up with something that works. I leave [here](steema.us/files/public/support/MQTTnetTEST.zip)the example I produced as it may be of use to somebody else looking for one.
