### ISSUE TITLE
无法还原NuGet包

### ISSUE THREAD

**Issue by hezlog** [chkr1011/MQTTnet#135]
错误信息：
还原 NuGet 程序包时出错: 由于无法加载项目 MQTTnet.NetStandard 的详细信息，操作失败。
IDE: VS 2017 15.4.5
OS: Win10 10.0.16299

我无法完成编译，请帮助我，谢谢。

**Comment by chkr1011** [comment]
Hi,
google translate tells me that you have issues in compiling the source code directly. Is this correct?

Best regards
Christian

**Comment by hezlog** [comment]
First of all, thank you for your precious time.

Yes，I can not complete the compilation.

Visual Studio Output:

还原 NuGet 程序包时出错: 由于无法加载项目 MQTTnet.NetStandard 的详细信息，操作失败。
1>------ 已启动生成: 项目: MQTTnet.Core, 配置: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\MQTTnet.Core\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
1>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\MQTTnet.Core\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
1>已完成生成项目“MQTTnet.Core.csproj”的操作 - 失败。
2>错误: 未找到导入的项目“C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。  C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets
3>------ 已启动生成: 项目: MQTTnet.AspNetCore, 配置: Debug Any CPU ------
4>------ 已启动生成: 项目: MQTTnet.Core.Tests, 配置: Debug Any CPU ------
5>------ 已启动生成: 项目: MQTTnet.TestApp.NetCore, 配置: Debug Any CPU ------
3>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Frameworks\MQTTnet.AspnetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
3>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Frameworks\MQTTnet.AspnetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
3>已完成生成项目“MQTTnet.AspNetCore.csproj”的操作 - 失败。
4>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.Core.Tests\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
4>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.Core.Tests\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
4>已完成生成项目“MQTTnet.Core.Tests.csproj”的操作 - 失败。
5>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.NetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
5>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.NetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
5>已完成生成项目“MQTTnet.TestApp.NetCore.csproj”的操作 - 失败。
5>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.NetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
5>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.NetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
5>已完成生成项目“MQTTnet.TestApp.NetCore.csproj”的操作 - 失败。
5>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.NetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
5>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.NetCore\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
5>已完成生成项目“MQTTnet.TestApp.NetCore.csproj”的操作 - 失败。
6>------ 已启动生成: 项目: MQTTnet.TestApp.AspNetCore2, 配置: Debug Any CPU ------
6>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.AspNetCore2\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
6>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : 找不到资产文件“D:\Documents\Workspaces\VisualCsharp\GitHub.git\Mqtt\chkr1011.MQTTnet\Tests\MQTTnet.TestApp.AspNetCore2\obj\project.assets.json”。运行 NuGet 程序包还原以生成此文件。
6>已完成生成项目“MQTTnet.TestApp.AspNetCore2.csproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 6 个，最新 0 个，跳过 0 个 ==========

Thank you。

**Comment by hezlog** [comment]
how to sync call?
.Net 4.6.1

public bool Start()
{
                // Use TCP connection.
                var options = new MqttClientOptionsBuilder()
                    .WithTcpServer(this.brokerHost, this.brokerPort) // Port is optional
                    .WithClientId(MQTT_CLIENTID)
                    .WithCleanSession()
                    .Build();
               **var result = _mqtt.ConnectAsync(options).Result;**

                // subscribe to the topic "/iot/pb/+" with QoS 2 
                _mqtt.SubscribeAsync(new TopicFilterBuilder().WithTopic(MQTT_SUB_TOPIC).WithExactlyOnceQoS().Build());

                if (!_mqtt.IsConnected)
                    throw new Exception("Mqtt Broker 连接失败！");

            return this.IsRuning;
}

**_mqtt.ConnectAsync(options).Result;** It‘s NOT Work!

**Comment by chkr1011** [comment]
Hi, 
I am closing this because it is quite old. If you need more assistance please reopen this ticket.
Best regards Christian
