### ISSUE TITLE
Intercept message

### ISSUE THREAD

**Issue by pengxiaobo123** [chkr1011/MQTTnet#137]
@chkr1011  hello.
How can you get the ClientID from the sender when you intercept the information?

**Comment by chkr1011** [comment]
Hi,
this is not available at the moment. But I will add it for version 2.6.

Best regards
Christian

**Comment by pengxiaobo123** [comment]
Thank you. I've changed the source code to this, and I've solved this problem.

      var interceptorContext = new MqttApplicationMessageInterceptorContext(senderClientSession?.ClientId)
                {
                    ApplicationMessage = applicationMessage,
                    
                };


public class MqttApplicationMessageInterceptorContext
    {
        public MqttApplicationMessageInterceptorContext(string clientId)
        {
            ClientId = clientId;
        }
        public MqttApplicationMessage ApplicationMessage { get; set; }
        public string ClientId { get; }
    }
