### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by MelangeF3A** [chkr1011/MQTTnet#140]
Hello.

On a client that is subscribed to the broker, when does the client know it has lost the connection.? Can the timeout be adjusted ..?

We are running the client on a link with high latency, via SatCom. I see many disconnect and Auto Reconnect events, even though there is still a connection to the Internet.

Secondly. How would it be possible to 'stack' the message from the Broker so when the client reconnects it gets a short history of messages not just the last one. I am using Mosquitto as the broker. Does the broker on here have this feaure..?

Great work.

Many Thanks

Richard

**Comment by chkr1011** [comment]
Hi,
with version 2.6.0 the keep alive timeout will be checked and clients are disconnected if they not respond. The client sends this timeout. The overall connection timeout is part of the options called _DefaultCommunicationTimeout_ for the server. The client also has this property but called _CommunicationTimeout_. 

If you want to stack them you can have a look at the _ManagedMqttClient_. The client queues all messages and is also able to store them (you have to implement a interface for this).

Best regards
Christian

**Comment by MelangeF3A** [comment]
Hi Christian.

Updated to 2.6.0 RC2 but unable to connect now.

Back to the stable version. I can see WithKeepAlivePeriod(TimeSpan.FromSeconds(10)) 
WithCommunicationTimeout((TimeSpan.FromSeconds(10)))

which I have set to 10 seconds.. will this work on 2.8.5...?

Will I need to run your Broker to get the Stack working at the Server end or is this a normal feature of most Brokers..?

Would you be able to outline some code to configure this on the Server and Client..?

Many Thanks

Richard

**Comment by chkr1011** [comment]
The keep alive feature is related to MQTT and also other brokers should support it. The overall communication timeout is a different topic but also other brokers should support it.

There is no Version 2.8.5???

Can you share some sample code?

Best regards
Christian

**Comment by kconfesor** [comment]
All clients are being disconnected, even if the keepalive is sent from the client. The managed client also disconnect after a while.

**Comment by mxkacsa** [comment]
in 2.6.0 version DefaultCommunicationTimeout not working?
It always 15 sec

**Comment by chkr1011** [comment]
@mxkacsa What does it mean that it is not working? The default is 10 seconds and not 15... So I am wondering why you mentioned 15 seconds. Do you have some sample code?
Best regards
Christian

**Comment by mxkacsa** [comment]
In `MQTTnet.Server.MqttServerOptions` class the DefaultCommunicationTimeout value is TimeSpan.FromSeconds(15.0), or it's not the keep alive?

**Comment by chkr1011** [comment]
Ah sorry I was referring to the client. Yes your mentioned property is the general communication timeout on socket level. This is not the keep alive internval. This is sent from the clients.

**Comment by mxkacsa** [comment]
I changed on the client, and it's working fine! thank you!
