### ISSUE TITLE
Need configurable host IP address

### ISSUE THREAD

**Issue by zhudanfei** [chkr1011/MQTTnet#142]
Current code always uses sockets binds with IPAddress.Any, but in some cases the specific IP address needs to be bound.
Could you provide IP binding configuration in MqttServerDefaultEndpointOptions?

Thanks.

**Comment by chkr1011** [comment]
Hi,
sure. I will add this for the next version 2.6.0. 

Best regards
Christian

**Comment by chkr1011** [comment]
I added this in the current _develop_ branch. Please let me know if this fits your needs.
Best regards
Christian

**Comment by zhudanfei** [comment]
Yes, that is exactly what I want. Thanks.
Looking forward to version 2.6.0.

**Comment by chkr1011** [comment]
Version 2.6.0 is now released.
Best regards
Christian

**Comment by ivansager** [comment]
@chkr1011, could you add the PR so that I can see how to assign an IP address ? I assume it would be in MqttBrokerSetting() but I do not see it.
