### ISSUE TITLE
Questions about how to do some things after Upgrade to V4

### ISSUE THREAD

**Issue by jogibear9988** [chkr1011/MQTTnet#1422]
Hello, I've now upgraded to V4 but I don't know how I should do some things:

1.) I used the following code: _internalServer.PublishAsync(messages);
But now the server does not have a "Publish" method any more. How do I publish messages?

2.)  _internalServer.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(e =>
                {
                    ApplicationMessageReceived(e.ClientId, e.ApplicationMessage);
                });

This callback does not exist any more. Wich one Should I now use?

**Comment by MD-V** [comment]
Hi @jogibear9988,

1. I think MqttServer.InjectApplicationMessage See: https://github.com/dotnet/MQTTnet/blob/dc9afa6c3a80e28eac8dd123fa0934b260ab58c9/Source/MQTTnet/Server/MqttServer.cs#L202

2. I think MqttServer.InterceptingPublishAsync See: https://github.com/dotnet/MQTTnet/blob/dc9afa6c3a80e28eac8dd123fa0934b260ab58c9/Source/MQTTnet/Server/MqttServer.cs#L94

**Comment by jogibear9988** [comment]
@MD-V will try, thanks for the help

**Comment by jogibear9988** [comment]
> 1. InjectApplicationMessage

saw this, but the compare result has no bool property

**Comment by MD-V** [comment]
The Compare Methode returns a MqttTopicFilterCompareResult which contains IsMatch value.

**Comment by jogibear9988** [comment]
> The Compare method returns a MqttTopicFilterCompareResult which contains IsMatch value.

I'm so dump... It's an enum...

**Comment by jogibear9988** [comment]
I've added the changes I need to the wiki page:

https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide
