### ISSUE TITLE
[Develop Branch]Create WebSocket Server Failed

### ISSUE THREAD

**Issue by FourOnes** [chkr1011/MQTTnet#143]
hi, @chkr1011 
I created an asp.net core 2.0.0 project. this project reference MQTTnet.AspNetCore.csproj, and compile successed.
But can't launch the project and have some errors:

![image](https://user-images.githubusercontent.com/3375961/33977889-17fd910c-e0d8-11e7-854f-06ad18eed3be.png)

Thanks.

**Comment by chkr1011** [comment]
Hi, 
which version are you using? 

Best regards
Christian

**Comment by FourOnes** [comment]
@chkr1011  Latest Develop Branch

**Comment by chkr1011** [comment]
It is now fixed. Thanks for reporting this issue.
Best regards
Christian
