### ISSUE TITLE
Intercept and discard the message

### ISSUE THREAD

**Issue by pengxiaobo123** [chkr1011/MQTTnet#144]
@chkr1011  hello

After the interception of the message, the message is abandoned, that is, do not send to other people.

**Comment by chkr1011** [comment]
Hi,
you can set the message to _null_ in the interceptor callback. Then the message will be truncated and not processed.

Best regards
Christian

**Comment by pengxiaobo123** [comment]
@chkr1011 

          options.ApplicationMessageInterceptor = context =>
            {
                try
                {
                    context = null;
                    return;


I don't understand where you're talking about.

I tried to set up null in the interceptor, but it didn't work.

**Comment by chkr1011** [comment]
I forgot to say that this is only possible with the next 2.6.0 release (which is available as a preview version (nuget)). Please try with that version instead.
