### ISSUE TITLE
Message on re-connect: recive message published when client was offline

### ISSUE THREAD

**Issue by psummo** [chkr1011/MQTTnet#145]
I try from MQTT.js and with public/subscribe QoS = 1 and with cleanSession false,  I have this

**CLIENT A** & **CLIENT B** ONLINE SUBSCRIBED TO THE SAME TOPIC
**CLIENT A** --> SEND MESSAGE 1, MESSAGE 2, MESSAGE 3--> CLIENT A/B REVICE MESSAGE 1/2/3
**CLIENT B** --> DISCONNECT
**CLIENT A**--> SEND MESSAGE 4/ MESSAGE 5--> **CLIENT A** REVICE MESSAGE 4/5
**CLIENT B** --> RE-CONNECT --> **CLIENT B** RECIVE MESSAGE 4/5

Why not working on xamarin with this package?
[Here my client ](https://pastebin.com/BVQ6bGUj)

**Comment by chkr1011** [comment]
Hi,
which version are you using? Please try with the RC version 2.6.0 (nuget).
Best regards
Christian

**Comment by psummo** [comment]
I do some test with RC2 2.6
The problem in RC2 persist. More

1. If client disconnect with DisconnectAsync and connect again without subscribe topic listener of message don't work
2. On android emulator 6.0 Marshmallow on start give me error the IMqttClient. Say that's a problem with assembly MQTTnet
This 2 problem with versione 2.5 doesn't exist, but message when client come online from offline doesn't work.
Thanks a lot

**Comment by psummo** [comment]
@chkr1011  Sorry, I found My mistake.
```
var options = new MqttClientOptionsBuilder()
                    .WithClientId(user)
                    .WithTcpServer("broker.net", 1883)
                    .WithCleanSession(false)
                    .Build();
```
My mistake was WithCleanSession(false). From suggestion of Visual studio appear that if WithCleanSession is not used, Default is FALSE. Suggestion say WithCleanSession(bool value = true) --> that seem's to be Necessary only if you want se a cleanSession to true...

Sorry for bad english 

Thanks. That work fine

**Comment by chkr1011** [comment]
Hi,
OK no problem 😄 
So the problem with Xamarin is also solved?

Best regards
Chrisitan

**Comment by chkr1011** [comment]
Version 2.6.0 is now released 😄

**Comment by psummo** [comment]
on version 2.6
on android version, during compile give me this error
"Could not resolve type with token 01000015 (from typeref, class/assembly MQTTnet.Client.IMqttClient, MQTTnet, Version=2.6.0.0, Culture=neutral, PublicKeyToken=909d71c724771999) assembly:MQTTnet, Version=2.6.0.0, Culture=neutral, PublicKeyToken=909d71c724771999 type:MQTTnet.Client.IMqttClient member:<none>"
But on UWP there's any problem :)

**Comment by chkr1011** [comment]
Sorry but this seems to be Xamarin related to me. I have no issues with 2.6.0 and Xamarin. If this problem still occurs please reopen this ticket.
Best regards
Christian
