### ISSUE TITLE
ACK after publish: how to recive?

### ISSUE THREAD

**Issue by psummo** [chkr1011/MQTTnet#147]
I try to recive a ACK to verify that message was recived from server. It's possible?

I see that .PublishAsync(MessageToSend) have
-Status
-IsCompleted
...
what is the correct way?

**Comment by chkr1011** [comment]
What classes are you referring? There is no "IsCompleted" message? The publish method will throw an exception if the message was not delivered to the server. For the _ManagedClient_ it is currently not possible to get the status of the published packets.

**Comment by psummo** [comment]
In my project I use
 **await emitter.PublishAsync(MessageToSend);**
that not get back anythings.
But If I use IsCompleted, return false. How i can use this IsCompleted?
**var completed = emitter.PublishAsync(MessageToSend).IsCompleted;**
                
The try/catch is the final way so :)

**Comment by chkr1011** [comment]
The _IsCompleted_ is coming from the Task library in .NET. It is not related to this library and shall not be used directly. If you await the call an exception will be thrown if the publish has failed. If no exception is thrown it works.

**Comment by psummo** [comment]
Ok sorry 🙂

**Comment by liaoliaoda** [comment]
hello, I have tested this function, the msg published success when the network connected normal, but there is no exception appear when I disconnect the network and publish the msg.  so I publish the msg cotinue and the exception(connection lost) appear after ten seconds later. so during about ten seconds, our msg is missing and I do not konw the details of the missing message. any solution about this? Thanks very much.
