### ISSUE TITLE
ConnectionValidator returns void in 2.6.0

### ISSUE THREAD

**Issue by schtibb** [chkr1011/MQTTnet#148]
Hi,

The connection validator used to return a MqttConnectReturnCode, it now returns void. I tried to set the MqttConnectReturnCode in the context but I could still connect even when the the ReturnCode was set to MqttConnectReturnCode.ConnectionRefusedIdentifierRejected. How is the ConnectionValidator supposed to work in 2.6.0?

EDIT: Setting the MqttConnectReturnCode  in the context actually worked. This issue can be closed.

Kind regards,
Jonas

**Comment by tobischw** [comment]
Hi,

I am still having the same issue. Using the exact sample code, I receive the following error message:

Anonymous function converted to a void returning delegate cannot return a value

How did you fix this issue? What is meant by the context?

**Comment by chkr1011** [comment]
Hi, sorry but the Wiki was not up to date. I fixed this.
Best regards
Christian

**Comment by malibVB** [comment]
Hi,
 I having the issue, that my app hangs at

>...
>await mqttClient.ConnectAsync(options);
>..

when I'm using the `MqttServerOptions`-Validator and set the return-code like

>...
>options.ConnectionValidator = c =>
>{
>  ...
>  c.ReturnCode = MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
>};
>...

If I set the return-code to 

>  ...
>  c.ReturnCode = MqttConnectReturnCode.ConnectionAccepted;
>...

It's work fine.

Any idea what's missing ?
