### ISSUE TITLE
CommunicationTimeOutException after each PublishAsync

### ISSUE THREAD

**Issue by pjrobin** [chkr1011/MQTTnet#149]
I'm using MQTT V2.6.0 / .NET 4.6.1 / UWP / connection over MqttClient and TcpServer
I get Exceptions every time I run PublishAsync although the data I send are transmitted to my server. I'm sending something like 1 message every 5s

Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' in System.Private.CoreLib.ni.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' in MQTTnet.dll

**Comment by chkr1011** [comment]
Hi,
please share the trace messages (described in Wiki). Then I can follow up the package flow. Are you using MQTTnet server or a different broker?
Best regards
Christian

**Comment by pjrobin** [comment]
I'm sorry, I'm not able to upload the trace as file ("Something went really wrong, and we can't process that file")

So here is the trace:
>> [2017-12-22T09:40:18.1542213+01:00] [3] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T09:40:18.2615070+01:00] [3] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T09:40:18.3236726+01:00] [3] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T09:40:18.3246761+01:00] [3] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T09:40:18.3276833+01:00] [3] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T09:40:18.3286865+01:00] [3] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T09:40:18.5643140+01:00] [3] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T09:40:18.5653165+01:00] [3] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T09:40:18.6475352+01:00] [8] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T09:40:18.6565590+01:00] [11] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T09:40:18.6555569+01:00] [9] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T09:40:18.6555569+01:00] [10] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T09:40:18.6685914+01:00] [11] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T09:40:18.6685914+01:00] [8] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T09:40:18.6685914+01:00] [10] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T09:40:18.6685914+01:00] [9] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T09:40:20.6689197+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=6b7a2e17-0961-4d5b-adb1-d719a71ecbfc] [Username=cl5Ro11rmOLS3gSVe7hP] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T09:40:20.6859667+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=2d2b80d2-e392-4cf0-a97c-df4dee8f15c9] [Username=RASPBERRY_PI_DEMO_TOKEN] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T09:40:20.6879721+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=b910280d-ccd8-4ddc-ac65-2037f2dc0c75] [Username=nPilvvZwD6YtwoxKsLDX] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T09:40:20.6949909+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=e3ddf485-eced-4f1b-aefb-d9146961a709] [Username=ZqQuQBDqFaxaHPAcOkzu] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T09:40:20.7020084+01:00] [9] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7020084+01:00] [10] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7020084+01:00] [11] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7070219+01:00] [8] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7070219+01:00] [15] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7120358+01:00] [15] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T09:40:20.7190533+01:00] [15] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T09:40:20.7200561+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:20.7230643+01:00] [15] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7240672+01:00] [15] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T09:40:20.7250700+01:00] [15] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T09:40:20.7250700+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:20.7270754+01:00] [15] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7270754+01:00] [15] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T09:40:20.7280775+01:00] [15] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T09:40:20.7280775+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:20.7290807+01:00] [15] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T09:40:20.7300846+01:00] [15] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T09:40:20.7310896+01:00] [15] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T09:40:20.7310896+01:00] [15] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:20.7300846+01:00] [9] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:20.7330910+01:00] [15] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:20.7350978+01:00] [8] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:20.7360992+01:00] [15] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:20.7401106+01:00] [10] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:20.7401106+01:00] [15] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:20.7461252+01:00] [11] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:20.7471281+01:00] [15] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:21.0459244+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=253] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T09:40:21.0599618+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=56] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.7948190+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=37] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.7978671+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=183] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.7988682+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=37] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.8008358+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=130] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.8018390+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=37] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.8078539+01:00] [11] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T09:40:23.8088571+01:00] [15] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T09:40:23.8078539+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=128] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.8108618+01:00] [10] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T09:40:23.8118660+01:00] [15] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T09:40:23.8118660+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=184] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=3] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.8138700+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=69] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=4] [Timeout=00:00:10]
>> [2017-12-22T09:40:23.8199248+01:00] [8] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T09:40:23.8199248+01:00] [15] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T09:40:23.8279458+01:00] [9] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T09:40:23.8279458+01:00] [15] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T09:40:28.8152378+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=43] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=3] [Timeout=00:00:10]
>> [2017-12-22T09:40:28.8322245+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=43] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=3] [Timeout=00:00:10]
>> [2017-12-22T09:40:28.8342298+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=41] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=5] [Timeout=00:00:10]
>> [2017-12-22T09:40:28.8352330+01:00] [3] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=69] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=6] [Timeout=00:00:10]
>> [2017-12-22T09:40:28.8482665+01:00] [9] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T09:40:29.8539468+01:00] [20] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T09:40:30.7344472+01:00] [20] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:30.7475833+01:00] [20] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:30.7493305+01:00] [20] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:30.7523387+01:00] [9] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:30.7533426+01:00] [20] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:30.7586153+01:00] [10] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:30.7593597+01:00] [20] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:30.7613640+01:00] [20] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T09:40:30.7653736+01:00] [8] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:30.7673790+01:00] [21] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:30.7766997+01:00] [11] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T09:40:30.7784082+01:00] [20] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T09:40:31.1794762+01:00] [21] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttPubAckPacket'.
>> [2017-12-22T09:40:31.1794762+01:00] [20] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttPubAckPacket'.
Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

**Comment by pjrobin** [comment]
Some more informations: I'm running 4 Mqqt Clients (main, warm, cold and part_3)
Here a new trace with increased delays (1 message / s) and I added the client name in the trace:

>> [2017-12-22T10:57:55.2992198+01:00] [3] [main] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T10:57:55.4034934+01:00] [3] [main] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T10:57:55.4756847+01:00] [3] [cold] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T10:57:55.4756847+01:00] [3] [cold] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T10:57:55.4796954+01:00] [3] [warm] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T10:57:55.4806982+01:00] [3] [warm] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T10:57:55.7193305+01:00] [3] [part_3_] [MqttClient] [Verbose]: Trying to connect with server.
>> [2017-12-22T10:57:55.7203336+01:00] [3] [part_3_] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2017-12-22T10:57:55.8065615+01:00] [7] [main] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T10:57:55.8175909+01:00] [10] [cold] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T10:57:55.8175909+01:00] [8] [warm] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T10:57:55.8175909+01:00] [9] [part_3_] [MqttClient] [Verbose]: Connection with server established.
>> [2017-12-22T10:57:55.8296228+01:00] [8] [warm] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T10:57:55.8296228+01:00] [9] [part_3_] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T10:57:55.8296228+01:00] [10] [cold] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T10:57:55.8296228+01:00] [7] [main] [MqttClient] [Info]: Start receiving packets.
>> [2017-12-22T10:57:57.8359413+01:00] [15] [part_3_] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=d2fd887a-cbb0-499d-8d80-d7e9a879c7b8] [Username=nPilvvZwD6YtwoxKsLDX] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T10:57:57.8620104+01:00] [15] [warm] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=8768fd35-e05b-486d-950e-67d6dbc75a09] [Username=cl5Ro11rmOLS3gSVe7hP] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T10:57:57.8775262+01:00] [15] [main] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=e03d0bf4-11bc-474b-ad52-8ad89f9067cb] [Username=RASPBERRY_PI_DEMO_TOKEN] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T10:57:57.8795315+01:00] [15] [cold] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=5ad93f13-1afd-4fd7-a281-ec8f69dbc770] [Username=ZqQuQBDqFaxaHPAcOkzu] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:10]
>> [2017-12-22T10:57:57.8870513+01:00] [9] [part_3_] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.8875566+01:00] [8] [warm] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.8885626+01:00] [7] [main] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.8970814+01:00] [10] [cold] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.9000892+01:00] [15] [main] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.9061055+01:00] [15] [main] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T10:57:57.9171342+01:00] [15] [main] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T10:57:57.9201434+01:00] [15] [main] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:57:57.9301697+01:00] [15] [warm] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.9311725+01:00] [7] [main] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:57:57.9311725+01:00] [15] [warm] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T10:57:57.9331792+01:00] [15] [warm] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T10:57:57.9422012+01:00] [15] [warm] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:57:57.9442065+01:00] [15] [main] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:57:57.9502225+01:00] [15] [cold] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.9512292+01:00] [15] [cold] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T10:57:57.9532306+01:00] [15] [cold] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T10:57:57.9562391+01:00] [8] [warm] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:57:57.9572409+01:00] [15] [cold] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:57:57.9592462+01:00] [15] [warm] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:57:57.9602494+01:00] [15] [part_3_] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=True]
>> [2017-12-22T10:57:57.9612515+01:00] [15] [part_3_] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2017-12-22T10:57:57.9622540+01:00] [15] [part_3_] [MqttClient] [Info]: Start sending keep alive packets.
>> [2017-12-22T10:57:57.9632569+01:00] [15] [part_3_] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:57:57.9672671+01:00] [10] [cold] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:57:57.9682714+01:00] [15] [cold] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:57:57.9732834+01:00] [9] [part_3_] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:57:57.9742859+01:00] [15] [part_3_] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:57:58.2179316+01:00] [3] [main] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=185] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T10:57:58.2329717+01:00] [7] [main] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T10:57:58.2339756+01:00] [15] [main] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T10:57:59.2165794+01:00] [3] [cold] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=128] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T10:58:00.2326448+01:00] [3] [cold] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=38] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T10:58:00.2446760+01:00] [10] [cold] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T10:58:00.2456788+01:00] [15] [cold] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T10:58:01.2503425+01:00] [3] [warm] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=130] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T10:58:02.2680402+01:00] [3] [warm] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=38] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T10:58:02.2790696+01:00] [8] [warm] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T10:58:02.2800732+01:00] [15] [warm] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T10:58:03.2867457+01:00] [3] [part_3_] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=183] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1] [Timeout=00:00:10]
>> [2017-12-22T10:58:04.3024338+01:00] [3] [part_3_] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=38] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T10:58:04.3145066+01:00] [9] [part_3_] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T10:58:04.3154728+01:00] [15] [part_3_] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T10:58:05.3237247+01:00] [3] [main] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=242] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=2] [Timeout=00:00:10]
>> [2017-12-22T10:58:06.3374495+01:00] [3] [main] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=41] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=3] [Timeout=00:00:10]
>> [2017-12-22T10:58:06.3504468+01:00] [7] [main] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T10:58:06.3514496+01:00] [15] [main] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T10:58:07.3551098+01:00] [3] [cold] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=43] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=3] [Timeout=00:00:10]
>> [2017-12-22T10:58:07.9529933+01:00] [21] [main] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:58:07.9687696+01:00] [21] [warm] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:58:07.9687696+01:00] [15] [cold] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:58:07.9810938+01:00] [21] [part_3_] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:10]
>> [2017-12-22T10:58:08.0341792+01:00] [7] [main] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:58:08.0341792+01:00] [9] [part_3_] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:58:08.0359144+01:00] [15] [part_3_] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:58:08.0341792+01:00] [10] [cold] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:58:08.0349123+01:00] [8] [warm] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2017-12-22T10:58:08.0359144+01:00] [21] [main] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:58:08.0399296+01:00] [21] [warm] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:58:08.0389236+01:00] [15] [cold] [MqttClient] [Info]: Received <<< PingResp
>> [2017-12-22T10:58:09.3112964+01:00] [15] [cold] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttPubAckPacket'.
Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
>> [2017-12-22T10:58:09.3895076+01:00] [3] [warm] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=43] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=3] [Timeout=00:00:10]
>> [2017-12-22T10:58:11.3091723+01:00] [15] [warm] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttPubAckPacket'.
Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
>> [2017-12-22T10:58:13.3444591+01:00] [15] [part_3_] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttPubAckPacket'.
Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
>> [2017-12-22T10:58:13.4597307+01:00] [3] [main] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/telemetry] [Payload.Length=69] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=4] [Timeout=00:00:10]
>> [2017-12-22T10:58:14.4774288+01:00] [3] [main] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=v1/devices/me/attributes] [Payload.Length=41] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=5] [Timeout=00:00:10]
>> [2017-12-22T10:58:14.4894794+01:00] [7] [main] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2017-12-22T10:58:14.4904667+01:00] [15] [main] [MqttClient] [Info]: Received <<< PubAck
>> [2017-12-22T10:58:15.3547561+01:00] [15] [main] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttPubAckPacket'.
Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

**Comment by chkr1011** [comment]
Which broker are you using?

**Comment by pjrobin** [comment]
https://thingsboard.io/docs/reference/mqtt-api/#telemetry-upload-api

**Comment by chkr1011** [comment]
Please try again with the latest beta of version 2.8.0. If the problem still occurs please reopen this ticket.
