### ISSUE TITLE
Mqttlens interface is messed up : large icons

### ISSUE THREAD

**Issue by jjtoard** [chkr1011/MQTTnet#150]
My mqttlens interface doesn't look like on examples.
It looks like the icon size is out of proportion
![mqttlens_screenshot](https://user-images.githubusercontent.com/24300782/34356036-4e8db7d6-ea3a-11e7-85e5-51813d07e916.jpg)

How can I solve this ?

**Comment by chkr1011** [comment]
Hi @jjtoard,
sorry but MQTTlens is not part of this project.

Best regards
Christian

**Comment by aspork42** [comment]
This came up as the top hit in google for this issue - any luck resolving the issue? Happening on three of my computers today.

**Comment by smiley561** [comment]
... same issue here!

Smiley561
