### ISSUE TITLE
Please help me to add InvalidName and Expired.

### ISSUE THREAD

**Issue by poumason** [chkr1011/MQTTnet#152]
https://github.com/chkr1011/MQTTnet/blob/312773d0549c5bd2b01881de8841ba6c6258d599/Frameworks/MQTTnet.NetStandard/Implementations/MqttTcpChannel.Uwp.cs#L126

Please add two `ChainValidationResult.InvalidName` and `ChainValidationResult.Expired`.
Because some MQTT server don't have really Certificates.
It's very important in the debug mode.

Thank you.

**Comment by chkr1011** [comment]
Hi @poumason,
you can add a static callback function to _MqttTcpChannel.CustomIgnorableServerCertificateErrorsResolver_ on UWP. If this one is set it will override the internal code and you can decide what should be filtered etc. 

Best regards
Christian

**Comment by poumason** [comment]
Wow!!!!
I got it. The structure is great. Thank you.
