### ISSUE TITLE
how to Intercepting application messages?

### ISSUE THREAD

**Issue by anxin1225** [chkr1011/MQTTnet#153]
Hi:
    I read the page of "Server" on wiki. about "Intercepting application messages" I have a little problem. that was how to Intercepting a message? I mean let the message stop, do not forward.

Look forward to your answer, thanks

**Comment by anxin1225** [comment]
Let me guess
`           options_builer.WithApplicationMessageInterceptor(context =>
            {
                if (stop_is)
                    context.ApplicationMessage = null;
            });
`
how about this?

**Comment by anxin1225** [comment]
applicationMessage = InterceptApplicationMessage(senderClientSession, applicationMessage);
                if (applicationMessage == null)
                {
                    return;
                }

Source Code was that， but I do not know. what is your hope want me todo.

**Comment by chkr1011** [comment]
Hi @anxin1225,
sorry but the Wiki was not up to date.
Yes you need to set it to _null_. Then it will not be processed anymore.

Best regards
Christian

**Comment by anxin1225** [comment]
oh,  I got it. 
and thank you for your reply.

May you have a good day.
