### ISSUE TITLE
Managed Client 2.60 not connecting

### ISSUE THREAD

**Issue by MelangeF3A** [chkr1011/MQTTnet#154]
When I install 2.60 the Managed Client does not connect. Works OK with 2.53.

Do I need to change any connect options..?

Thansk

Richard

**Comment by Tyrannmisu** [comment]
Did you build your client with TLS without any parameters?
Because i had the same issue and it worked fine when i removed the TLS Option.

Have not been able to test the client with actual certificates, but just WithTLS() does not seem to work anymore.

**Comment by MelangeF3A** [comment]
Hi.

Yes that worked.. Thank You.

**Comment by Katamato** [comment]
Hi,
I've got the same problem. I allready removed the WithTLS() option.
But ManagedClient is NOT connecting if I use the option WithCleanSession(false).
If I set the option to .WithCleanSession(true) the client is connecting.

Any idea?

Thanks...

**Comment by pengxiaobo123** [comment]
@Katamato  Hello, I also have the same problem, you can use v2.53 connection, but the client will not be able to connect if it is upgraded to v.2.60.

**Comment by Katamato** [comment]
@pengxiaobo123 Hi, I made some tests and looked into the source code. The managed client does not support existing sessions. An UnsupportedException is thrown if the option is set. In my test client I had no exception handling... so I missed the exception.

**Comment by chkr1011** [comment]
The exception is new in Version 2.6.0 because (at the moment) existing sessions are not supported when using the ManagedClient.

**Comment by chkr1011** [comment]
Also the Options builder has some bugs with TLS related settings. So it "worked" but the internal options were wrong.

**Comment by elmosan** [comment]
Hi, 

Will it ever be possible to use existing sesssions on the ManagedClient? Or can you explain the reason why it's not supported? We need these in one of our mqtt configurations (sometimes the mqtt broker suddenly gets interrupted/restarted). So otherwise we have to implement the session handling (reconnect and subscribing) our selves, which would be a pity.

Thanks

**Comment by chkr1011** [comment]
Hi,
at the moment this is not planned. The problem is dealing with the subscription management.
Best regards
Christian

**Comment by chkr1011** [comment]
Hi,
at the moment this is not planned. Because the client maintains the subscriptions and subscribes automatically even if the connection was lost. Dealing with existing sessions is a little bit complicated.
Best regards

**Comment by Onasss** [comment]
Hello, so is there by now (v3.0) any way to use non-clean connections with managed client?
Thank you!
