### ISSUE TITLE
ManagedClient Refused Responses

### ISSUE THREAD

**Issue by setamodius** [chkr1011/MQTTnet#156]
Hi,
First I have to say thanks for this library. 
I am using ManagedClient. I want to detect connection refused responses. For example if username or password is wrong. How can i get "bad user name or password" response. I tried 
try
{
    mqttClient.StartAsync(options);
}
catch (Exception)
{

} 
but it is not working.
Is there any example code for get refused responses?
Thanks

**Comment by chkr1011** [comment]
Hi @setamodius,
this is not supported at the moment. But I will extend the _Disconnected_ event in the next verison. Then you get some details why the connection is lost.

Best regards
Christian

**Comment by chkr1011** [comment]
Hi @setamodius,
I just released a preview of 2.7.0 (nuget). Please let me know if this works for you.
Best regards
Christian

**Comment by setamodius** [comment]
Hi @chkr1011 
My problem was solved with 2.7.0. I can get refused response details. Thanks.
