### ISSUE TITLE
TlsOptions cannot be set

### ISSUE THREAD

**Issue by 1iveowl** [chkr1011/MQTTnet#16]
Maybe I'm doing something wrong, however while creating a [Rx Wrapper for MQTTnet](https://github.com/1iveowl/MQTTClient.rx) I notices that I was unable to set TlsOptions. 

Did I miss something or...?

**Comment by chkr1011** [comment]
What exactly do you mean with "unable to set"?

**Comment by 1iveowl** [comment]
Look at your implementation of MqttClientOptions. [There is no sette for TlsOptions](https://github.com/chkr1011/MQTTnet/blob/master/MQTTnet.Core/Client/MqttClientOptions.cs#L11)

But maybe there is something is misunderstand?

**Comment by chkr1011** [comment]
Ah OK. It is because this object is always set. You can access the fields directly. This property is never null.

**Comment by 1iveowl** [comment]
My time to say ahh. I can Work with that.
