### ISSUE TITLE
Build server and signed assemblies

### ISSUE THREAD

**Issue by chkr1011** [chkr1011/MQTTnet#160]
@JanEggers Do you have an idea how to setup the build server and fix the failed builds? The problem is that the certificate for code signing is not importet at the build server. Is it maybe possible to define a configuration for the build process which has no code signing activated?

Best regards
Christian

**Comment by JanEggers** [comment]
Hi Christian, 

i found this:

https://help.appveyor.com/discussions/questions/217-signing-net-assemblies-without-exposing-the-snk-file-publicly
