### ISSUE TITLE
How to remove a subscriber's subscription on the server side

### ISSUE THREAD

**Issue by pengxiaobo123** [chkr1011/MQTTnet#164]
@chkr1011  
Hello, how can you remove a subscriber from a server on the server, but keep his other subscriptions

Specific scene:

A user has left a group of A, so he should not receive the message in the group A. But the news of other groups should continue to be sent to him.

**Comment by chkr1011** [comment]
Hi @pengxiaobo123,
this is not possible at the moment. Only  a client can unsubscribe itself from a topic. 
But I can add this to version 2.7.0 if you tell me which data you have to pass in etc. 

Best regards
Christian

**Comment by pengxiaobo123** [comment]
Hi @chkr1011 
I want to provide you with ClinetID and List<topic>, and then, you remove the topic under this ClinentID

The reason for these needs is because I'm trying to get a server-side management software that is convenient for ordinary users to maintain.

**Comment by chkr1011** [comment]
Hi @pengxiaobo123,
I just released a preview of 2.7.0. It also contains the new feature. Please let me know if this fits your needs.
Best regards
Christian
