### ISSUE TITLE
WSS Configuration

### ISSUE THREAD

**Issue by MattComb** [chkr1011/MQTTnet#165]
Hi Christian,

I am having some difficulty getting the WSS implementation to work with the asp.net core package.

My current objective is to achieve a connection from a third party system such as freeboard.io which uses the paho js client to connect on wss://host:port/mqtt endpoint. I preferred to host this mqtt over websocket endpoint in a windows service but have decided to implement it in asp.net core for now.

Are you able to provide some additional insight on how to configure the setup for that?

In the documentation it states the following for websocket, should that be app.UseWebsockets ? I have tried both but can't get either to work.

Also does the websocket implementation require that the Websocket protocol is installed under IIS ? or is it a standalone implementation ?

```
public void ConfigureServices(IServiceCollection services)
{
     var mqttServerOptions = new MqttServerOptionsBuilder().Build();
     services.AddHostedMqttServer(mqttServerOptions);
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseMqttEndpoint();
    // other stuff
}

```

**Comment by MattComb** [comment]
Please note that I have successfully managed to get TLS connection working client and server in a win forms test app. Its just the asp.net core host configuration and websocket implementation that I'm struggling with.

**Comment by chkr1011** [comment]
Hi @MattComb,
In this repo there is a .NET Core ASP.NET test app. Please compare this project with yours. Maybe some configs, references etc. are missing. The WebSocket part is mostly done by @JanEggers so I cannot assist a lot here. 

Best regards
Christian

**Comment by JanEggers** [comment]
the code is in https://github.com/chkr1011/MQTTnet/blob/master/Frameworks/MQTTnet.AspnetCore/ApplicationBuilderExtensions.cs i didnt put any logging in there so i guess to debug you should copy that code to your solution and than add logging or attach the debugger to figure out why its not working.

i dont know what could possibly go wrong either you hit the biddleware or you dont.

**Comment by MattComb** [comment]
Thanks guys, I'll take a look at the reference code and come back soon

**Comment by MattComb** [comment]
I have this working now, was a misconfiguration. it worked once deployed and i had the SSL certificate applied to the website.
