### ISSUE TITLE
add unsubscription event

### ISSUE THREAD

**Issue by bartbreur** [chkr1011/MQTTnet#171]
Hi @chkr1011 , 
Can you add an event when unsubscription happens (server)? We have a use case where a client subscribes only for a certain amount of time. You library would fit perfecly in our system, if we can monitor the unsubscriptions also.

**Comment by chkr1011** [comment]
Hi @bartbreur,
please consider using the subscription interceptor instead. You can call your own code there without changing the subscription.

Best regards
Christian

**Comment by bartbreur** [comment]
Hi Christian @chkr1011,  thanks for the suggestion. I have tried again and also with version 2.7.0-rc1 But the subscription interceptor seems to be activated only on subscription, not on unsubscription.

**Comment by chkr1011** [comment]
OK, I added events for this. They will be added in version 2.7.0.
Best regards
Christian
