### ISSUE TITLE
PacketIdentifier can't be zero (should be non-zero according to the MQTT spec)

### ISSUE THREAD

**Issue by benpittoors** [chkr1011/MQTTnet#172]
The private method GetNewPacketIdentifier() in MqttClient returns zero for every ushort cycle. According to the MQTT spec, a packet identifier should be non-zero.  Some broker implementations consider a publication package with a packet identifier of zero to be an invalid mqtt message and will not accept it (or even close the connection).

From the spec:
Section 2.3.1
SUBSCRIBE, UNSUBSCRIBE, and PUBLISH (in cases where QoS > 0) Control Packets MUST contain a non-zero 16-bit Packet Identifier [MQTT-2.3.1-1]

This is a small XUnit test that mimics the behavior:

'
   public class MqttNetPacketIdentifierTest
    {
        private int _packetIdentifier;

        [Fact]
        public void TestPackageIdentifierMechanismAsInV26()
        {
            _packetIdentifier = ushort.MaxValue;

            var result =  GetNewPacketIdentifier();

            Assert.Equal(1, result);
        }

        // this is copied from MqttClient.cs
        private ushort GetNewPacketIdentifier()
        {
            return (ushort)Interlocked.Increment(ref _packetIdentifier);
        }
    }
'

What would be an efficient way to fix this?

**Comment by benpittoors** [comment]
I saw the fix in the develop branch.  Will it be part of the 2.7.0 release?  And if so, when can I get it through NuGet (maybe as -rc2, or something?)

I don't like to ask for ETA's ;-) but I the timing will impact some of the decisions we need to make in our setup.

**Comment by chkr1011** [comment]
Hi,
yes it will be part of 2.7.0. I will release a new version now as final.

Best regards
Christian
