### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by FM1973** [chkr1011/MQTTnet#175]
Hello.

I´ve used version 2.5.0 without any problem.
For testing purpose I used MQTT.fx to connect to the broker (hosted in asp.net core).

After upgrading to version 2.7 I do get an "connection refused" error when trying to connect to the broker.
Reverting to 2.5 solves the problem.

Did I miss any breaking change regarding connections?

**Comment by chkr1011** [comment]
Hi,
no there you be now breaking change. Maybe the sub protocol _mqtt_ is missing. Please take some traces (described in Wiki) and share it with me. Probably there is a bug in message handing etc.

Best regards
Christian

**Comment by FM1973** [comment]
Hello Christian.

I can´t use tracing because the connection is refused before a trace can be done.
But I think I found why the connection is being refused.

In 2.7 you register only the Websocket-Adapter.  In ServiceCollectionExtensions you register the MqttHostedServer and the MqttWebsocketServerAdapter. But you are not registering the MqttServerAdapter as you did in 2.5.

When I Add `services.AddTransient<IMqttServerAdapter, MqttServerAdapter>();` to the AddHostedMqttServer Extension Method, I can connect to the MQTT-Broker.

I don´t know If there is missing something else, but maybe you can take a look at it.

All the best, 
Florian

**Comment by chkr1011** [comment]
@JanEggers Is this really missing (thus a bug) or by design?

**Comment by JanEggers** [comment]
it is missing here https://github.com/chkr1011/MQTTnet/blob/b426ae1198cecca192ff853a5d97948ca1836382/Frameworks/MQTTnet.AspnetCore/ServiceCollectionExtensions.cs#L22-L25

I had a look at the history and it seems it never has been there in 2.5 so i dont know why it worked there
