### ISSUE TITLE
Re-authenticate with fresh credentials

### ISSUE THREAD

**Issue by loubonta** [chkr1011/MQTTnet#178]
Currently when using the Managed Client and connections are dropped, a reconnection occurs with a potentially expired password.  When this occurs the BulkCollection queue keeps increasing causing a massive memory leak as the messages are never delivered to the broker.  The fix would be to expose a `Func<IMqttClientCredentials> GetCredentials` to be passed into the IMqttClientOptions class and setup through the MqttClientOptionsBuilder.  The MqttClient.AuthenticateAsync function would then invoke GetCredentials if it has been set in the builder, thereby overriding the Credentials passed in through the builder.

**Comment by loubonta** [comment]
I'm trying to push code on the develop branch so that I can submit a pull request.  I get a 403.  Is that a permission problem on the repository that I need to be granted?

**Comment by chkr1011** [comment]
Hi @loubonta,
At the moment this is not supported. But I will ad a custom credentials provider for the next version. You cannot push to this repo. You must fork it and then you can create a pull request. But I also have started this feature so I think it is not required.

Best regards
Christian

**Comment by loubonta** [comment]
great.  many thanks
