### ISSUE TITLE
Could not load file or assembly 'MQTTnet.Core

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#18]
Hi again,

I finally found the time to test you ApplicationMessageReceived event for the mqtt broker.
This is what I did:

`            MqttServer mqttServer = new MqttServerFactory().CreateMqttServer(options);

            mqttServer.ApplicationMessageReceived += (s, e) =>

            {

                string messageString = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);

                try

                {

                    Dictionary<string, string> messageProperty = new Dictionary<string, string>();

                    Console.WriteLine(e.ClientId + " sent " + e.ApplicationMessage.Payload);

                }

                catch (Exception ex)

                {

                    Console.WriteLine(ex);

                }

            };
`
It looks all like I wanted it. Unfortunately VS somehow cannot "find" the dll, even though I added it in my project:
![image](https://user-images.githubusercontent.com/14317353/28869744-00b35522-777e-11e7-90a4-6518cb7b72d6.png)

Next I tried to use the NugetPackage. With it everything works gread on windows. Unfortunately it does not work on my raspberry pi.
![image](https://user-images.githubusercontent.com/14317353/28870722-a4dea194-7781-11e7-8a82-90095297afe7.png)

What did I do wrong?
Also I cannot find the "MQTTnet.NetCoreApp" folder under "Frameworks":
![image](https://user-images.githubusercontent.com/14317353/28871160-a7143de6-7783-11e7-9cce-b04a48c68fe4.png)
 

Thanks again.

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
Hi,
I just tested it in a LINQPad script and it works.
Can you please tell me which kind of project use use? .NET Framework or .NET Core?

Yes the NetCoreApp project is removed because there is a new NetStandard one which should also work für NetCoreApps.

Best regards
Christian

**Comment by chkr1011** [comment]
Hi,
is this still open or should I close it?
Best regards
Christian

**Comment by chkr1011** [comment]
@Zuendelmeister Please reopen this ticket if the problem still occurs.
Best regards
Christian

**Comment by Zuendelmeister** [comment]
Hi @chkr1011,
sorry for answering so late. I was away for a few days.
I use a NetCoreApp.
![image](https://user-images.githubusercontent.com/14317353/29061311-94398df4-7c1d-11e7-9a2b-cd8721bb18af.png)

I just tried the NetStandard dll's and it realy works. I probably used the wrong ones.
Thank you =)

Best regards,
Zuendelmeister
