### ISSUE TITLE
Need of kicking connected clients when others tries to connect with same Id

### ISSUE THREAD

**Issue by aaarnaaauuu** [chkr1011/MQTTnet#181]
I am having problems beacause a client using another mqtt client library losts i'ts connection and gets stucked, I was wondering if it could be posible to manage the connected clients and kick the stucked client. This way it would be able to reconnect because no fake connection with it's Id would exist in our broker.

I was thinking of kicking a connected client when another one tries to connect with the same Id.

**Comment by chkr1011** [comment]
Hi @aaarnaaauuu,
at the moment the server will disconnect the old client if a new one connects with the same client ID. So it should already work as you described.

Best regards
Christian

**Comment by aaarnaaauuu** [comment]
It's true @chkr1011 , thanks for answering.

Kind regards,
Arnau

**Comment by phamminhkhac** [comment]
anw, how to kick a client with an ID? could not find any method in the library

**Comment by SeppPenner** [comment]
@phamminhkhac You can use the https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-subscriptions for this.

E.g.:

```csharp
var optionsBuilder = new MqttServerOptionsBuilder()
    .WithSubscriptionInterceptor(context =>
    {
        if (context.TopicFilter.Topic.StartsWith("#") && context.ClientId != "Imperator")
        {
            context.AcceptSubscription = false;
            context.CloseConnection = true;
        }
    })
    .Build();
```

where `context.CloseConnection = true;` will kick the client from the broker when it tries to subscribe to `#`.

You can do the same for connection and publishing by the way. If you want another fully working example, check e.g. my example project under https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig/blob/master/NetCoreMQTTExampleJsonConfig/Program.cs.
