### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by PitySOFT** [chkr1011/MQTTnet#183]
It's there a way to use this library with a proxy? Thanks.

**Comment by chkr1011** [comment]
Hi,
what kind of proxy do you mean? TCP?

Best regards
Christian

**Comment by PitySOFT** [comment]
A TCP proxy.

**Comment by chkr1011** [comment]
I don't now. I didn't test it on my own but I assume it should work.

**Comment by jltjohanlindqvist** [comment]
Is there a plan to support proxies when using TCP?
