### ISSUE TITLE
Dependency injection in AspNetCore 2.0

### ISSUE THREAD

**Issue by talfirevic** [chkr1011/MQTTnet#184]
Hello,

Firstly, great library, I'm really happy with it ;)

Here's my conundrum, I'd like to use subscription interceptor and from what I've gathered here https://github.com/chkr1011/MQTTnet/wiki/Server

The preferred way is something like this.

```
var mqttServerOptions = new MqttServerOptions();

options.SubscriptionsInterceptor = context =>
{
    if (context.TopicFilter.Topic.StartsWith("admin/foo/bar") && context.ClientId != "theAdmin")
    {
        context.AcceptSubscription = false;
    }

    if (context.TopicFilter.Topic.StartsWith("the/secret/stuff") && context.ClientId != "Imperator")
    {
        context.AcceptSubscription = false;
        context.CloseConnection = true;
    }
};

 services.AddHostedMqttServer(mqttServerOptions);
```
So basically just add the configured MQTTserver to `IServiceCollection` and let the web app do the dependency injection etc.

Clear and simple, right.

But here's my issue, since my requirement for `SubscriptionInterceptor` is a bit more complex than this. For example, in the action, I need an instance of my `IPermissionService` to check if the client is allowed to subscribe to the topic or not. 

Problem is getting the instance of `IPermissionService ` at this point. The application is being bootstrapped, my IoC container hasn't yet been configured and the configuration depends on before mentioned `IServiceCollection`.

This is basically a dependency loop, so I'm obviously doing something wrong. 

Would you recommend something that can be done with MQTTnet, like configuring that interceptor somewhere else, at a later point when the IoC Container has been fully configured or is this basically an issue with the way  I approach dependency injection?

Thanks,
T.

**Comment by chkr1011** [comment]
Hi,
thanks for your feedback.

I got your point but don't have a recommendation yet. One possible solution is to wrap the handler in another service which has the dependency to your permission service. Also this new service can be setup later but the options of the MQTTnet server already contains this "wrapper" and can be initialized.

Another idea is to add an interface with a handler to the options. So you can set a class directly which must implement a dedicated method. But this cannot be filled from the constructor (including your permissions service).

Or you add MQTTnet as a reference to the permission service and add the handler at the permission service. In general you can set this property also later. There is no need to do this before startup. So you can also get both services from the container like a service locator and "connect" them. Maybe access to the internal options through a new property may help you with this.

Best regards
Christian

**Comment by talfirevic** [comment]
Hi @chkr1011 

Thanks for the info. 

Yeah I was considering adding reference to the subscription interceptor to the `PermissionService` but my brief look through the documentation and code did not give me a straight answer how to go about this approach.

Since the "instance" of the MqttServer is being created at the app startup  `services.AddHostedMqttServer(mqttServerOptions);` 

What would be best way of accessing these internal options of the server that's already running at some later point?

Thank you,
T.

**Comment by chkr1011** [comment]
You can hold the reference of the options on your own. You can then change the properties all the time. They are not copied internally to somewhere else. But I will ad a public property getter for the options.

**Comment by talfirevic** [comment]
@chkr1011 oh ok, I just thought there was already a mechanism for this.
Thank you for all the info.

Once again, great library 👍 

T.
