### ISSUE TITLE
KeepAlive timeout interferes with normal message publish/receive

### ISSUE THREAD

**Issue by pehachem** [chkr1011/MQTTnet#187]
Hi Christian,

I have a small test program that, using the regular MqttClient, rises "_MQTT communication exception while sending/receiving keep alive packets._" while processing a lot of publish/receive on the same connection. And connection is lost, of course.

The exception raised exactly 1 second (= CommunicationTimeout) after the log message "_TX >>> PingReq [Timeout=00:00:01]_"
Between both log messages, there are _a lot of_ other log messages from the client, reporting about the publish/listen traffic... and exactly one timeout period (same 100th of second).

I think I found at least one cause.

If I force the Connection Timout to be large enough, then the exception is not raised and all messages are sent. Note that, on my core i7 under Win10 + VS2017, the test program publishes 1000 messages - Publish() _without awaitinng_ - to a broker, using MQTTS, and listen back to them from the broker at the same time.

As far as I understand your code, the keepalive timeout requires the server response to be _processed_ within one timeout. In this particular case, I think that MqttClient has not enough resources to ensure this delay... while the 'pong' message is in the deepth of the received message queue (in client or still in broker).

Note that, as far as I understand the specification in MQTT, the keepalive handshake is required only if the connection has not been active in the past timeout period :-)

Hope this helps,
Philippe.

**Comment by chkr1011** [comment]
Hi Philippe,
I know this problem but at the moment I am not able to fix this. I can reproduce it when sending a very large batch of messages. Then all of those messages are processed in a row and the client has no chance to _inject_ the keep alive package. If you send then one by one it should work because the client gets a change that the keep alive package is sent but this also depends  on the actual load and the connection quality.

Another issue is that the keep alive package is sent in the keep alive period as well. So every second if the keep alive is also every second. So the server will only wait 1.5 seconds for that packet. If the package requires >= 501 ms for transmit the connection will be closed. Maybe a lower interval (configurable) will help here. I am thinking of 1/10 of the keep alive period. So that the client will try send the keep alive every 100 ms (if there was no other package transmitted). What do you think about this solution?

Best regards
Christian

**Comment by pehachem** [comment]
Hi Christian,

If I understand well your suggestion, sending a ping at 1/10th of the keep alive period will let 14/10th of this period for the server to receive and process it (applying the '1.5x' rule for the server to close the connection). It will probably help - it is better than 5/10th - but it seems to me that you would get exactly the same time window if you directly multiply the keep alive period by 14/5th, without any code modification.

I suggest another way to solve the issue:
1 - Implement keepalive logic using retriggerable timers, were the delay is restarted by an external signal so that timeout would elapse only when there has been no signal activity in the past timeout delay:
1.1 - On client side: timer should be retriggered every time a message has been sent (may safely include the sending of PINGREQ itself). When timeout finally occurs, a PINGREQ must be sent.
1.2 - On server side: timer should be retriggered every time a PINGREQ has been received. When timeout occurs, the connection must be closed (server timeout value being 1.5x the client one).
2 - On client side, there is an additional effort to do, since receiving PINGRESP is a health proof of the 2-ways connection.
It can be implemented like 1.2 is implemented on server side: a retriggerable timer may close the connection if no PINGRESP has been received after a 'reasonable' time the last PINGREQ has been sent. Note that the MQTT specification does not _require_ that the client disconnects in this case. Note also that a rule similar to the '1.5x' on PINGREQ should be applied, to take into account the transmission delays in both ways, and the processing delay on server. So I suggest to apply at least the '1.5x' rule; and why not '2x'?
3 - Regarding the implementation, I suggest to implement this logic in a dedicated thread rather than as Tasks which would potentially wait for their turn to be scheduled in the thread pool. The reason is that these timing are real time constraints, and they are required to be as reliable as possible whatever be the task queue level.
4 - while seeking the web on these issues, I found some interesting methods to implement retriggerable timers, like [this one](http://www.thomaslevesque.com/2015/06/04/async-and-cancellation-support-for-wait-handles/)

What do you think of that?
Hope this helps,
Philippe.

**Comment by chkr1011** [comment]
In version 2.8.0 there is a new mechanism which delays the connection check while receiving large packages. This should fix it.
