### ISSUE TITLE
Namespace MQTTnet is missing from NuGet v2.15

### ISSUE THREAD

**Issue by 1iveowl** [chkr1011/MQTTnet#19]
Not sure if I'm doing something wrong, but the Namespace MQTTnet disappears when I upgrade the NuGet from v2.14 to v2.15?

**Comment by chkr1011** [comment]
Hi,
this should not happen. I just tested it with LINQPad and all namespaces are there.
What type of project are you using?
Maybe it is due to a breaking change. The Factories are now returning an Interface for Client and Server instead of the actual implementation. Maybe this is the reason.

Best regards
Christian

**Comment by 1iveowl** [comment]
It's for the .NET Standard project I created: [MQTTClient.rx](https://github.com/1iveowl/MQTTClient.rx).

Hmm, not sure what is going on. Are you sure that the NuGet includes all the right files?

**Comment by chkr1011** [comment]
I used the build script you created :-)

**Comment by 1iveowl** [comment]
Ha ha. Touché ;-)

Anyhow, here is what I see in Visual Studio. Sure does look like there are some .dll's missing.

![mqtt2 15](https://user-images.githubusercontent.com/12871120/28996985-f87c9168-7a0a-11e7-8721-c53c5ac5d898.png)
![mqtt2 14](https://user-images.githubusercontent.com/12871120/28996986-f87e451c-7a0a-11e7-9a86-60da44f638d0.png)

**Comment by chkr1011** [comment]
I am downloading your project. Then I will test it.
But I can see that the .NET Standard  libraries are only two. Which seems to be OK!?

**Comment by 1iveowl** [comment]
Have you tried to look at the NuGet package that is created using the [Nuget Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) to see if all is there? 

Could just be related to some paths that havde changed.

**Comment by chkr1011** [comment]
I tested it with your repo and it works with 2.1.5 BUT you have to convert several places in your code. Because the factories are returning the interfaces of MqttServer and MqttClient now.

**Comment by chkr1011** [comment]
And the dependency looks like this after updating your solution to 2.1.5...

![image](https://user-images.githubusercontent.com/6939810/28997040-34dea6fe-7a0c-11e7-93c5-0a81eabca094.png)

Seems to be OK!?

**Comment by 1iveowl** [comment]
It sure does. So the issue must be in my end. Not sure what is going on. I will investigate...

**Comment by 1iveowl** [comment]
I found the culpit. I cleared the NuGet cache and now it works.

**Comment by chkr1011** [comment]
ok perfect :)
