### ISSUE TITLE
Authorization of clients by the server

### ISSUE THREAD

**Issue by abnyn** [chkr1011/MQTTnet#190]
Thanks for making this wonderful library!

I would like to know how I can allow only a subset of clients to access project/topic/secret-subtopic as described in the official MQTT specs below.

I'm trying to use the following approach:

1. Authenticate username/password against a database, .
2. Authorize access to a subtopic as described in the MQTT specs:

> An implementation may restrict access to Server resources based on information provided by the Client such as User Name, Client Identifier, the hostname/IP address of the Client, or the outcome of authentication mechanisms.

[_Authorization of Clients by the Server_ from the MQTT specs](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718117)

How can I do that using MQTTnet?

**Comment by chkr1011** [comment]
Hi,
please have a look at the Wiki. There are some examples for your requests. You can extend them and check the credentials against your own DB and also the subscriptions can be validated.

Best regards
Christian

**Comment by abnyn** [comment]
Thanks!
