### ISSUE TITLE
Are there api to check status and monitoring MQTT server?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#192]
Are there api to check status and monitoring MQTT server?

**Comment by chkr1011** [comment]
Hi @biapar,
you can use the _GetConnectedClients_ method from the server to obtain several connection related information about the clients.

Best regards
Christian

**Comment by chkr1011** [comment]
Hi @biapar,
you can use the _GetConnectedClients_ method from the server to obtain several connection related information about the clients.

Best regards
Christian
