### ISSUE TITLE
How to detect disconnection in ManagedClient

### ISSUE THREAD

**Issue by duncanellison** [chkr1011/MQTTnet#194]
I'm just trying to get to grips with this library since converting over from another and to keep things simpler, I'm using a ManagedClient.

However ... I need to know the status of the connection so that I can display that on the UI.  What's the best strategy to do that when using the _managed_ client?

Keep polling the .isConnected?  

I'm not sure if the managed client exposes the disconnected event, can you confirm that as I can't seem to hook into it.  I guess it might be because you have no business setting an event handler for this event when the managed code is doing it for you ????

I also found that i had to add a Thread.sleep after calling StartAsync and checking .IsConnected.  Is that expected ?

Thanks Duncan

**Comment by chkr1011** [comment]
Hi,
for connection monitoring you can use the events _Connected_ and _Disconnected_. Additionally the _IsConnected_ property is available. Polling the property is not a good approach. I recommend using the events.

Yes you have to wait because _Start_ does not mean that the client is connected. It only means that the internal connection management will start and maintain the connection automatically (reconnect etc.). So you have to wait a short period of time.

Best regards
Christian

**Comment by duncanellison** [comment]
Hi Christian,  Thanks for the quick reply.

I'm having problems trying to hook the events and I'd really appreciate your eye on this, I can't just see what I'm doing wrong.  Apologies that this is in VB, but can you see what's wrong here.  mqtt_client doesn't expose .disposed when I do it like this :
```
    ' Now create an MQTT client with global scope
    Public mqtt_client = New MqttFactory().CreateManagedMqttClient

    Public Function StartMQTTConnection() As Integer
        ' This routine spins up the MQTT engine.
        ' It uses library MQTTNet from chkr10011 in 'Managed Client' mode
        ' 
        AddHandler mqtt_client.Disconnected, AddressOf MQTTclient_disconnected
        AddHandler mqtt_client.Connected, AddressOf MQTTclient_connected

        Dim communicationTimeout As New TimeSpan(0, 0, 5)
        Dim keepAlivePeriod As New TimeSpan(0, 0, 30)

        ' Set protocol version
        Dim protocolVersion As String
        If MQTT_Version = "V3.1.1" Then
            protocolVersion = Serializer.MqttProtocolVersion.V311
        ElseIf MQTT_Version = "V3.1" Then
            protocolVersion = Serializer.MqttProtocolVersion.V310
        Else
            protocolVersion = Serializer.MqttProtocolVersion.V310
        End If

        ' Set up the options
        Dim mqtt_options = New ManagedMqttClientOptionsBuilder().WithAutoReconnectDelay(TimeSpan.FromSeconds(5)) _
                .WithClientOptions(New MqttClientOptionsBuilder() _
                    .WithClientId(MQTT_ClientID) _
                    .WithTcpServer(MQTT_Server, MQTT_Port) _
                    .WithCredentials(MQTT_Username, MQTT_Password) _
                    .WithCleanSession() _
                    .WithCommunicationTimeout(communicationTimeout) _
                    .WithKeepAlivePeriod(keepAlivePeriod) _
                    .WithProtocolVersion(protocolVersion) _
                    .WithWebSocketServer(False) _
                .Build()).Build()

        ' Now create the MQTT client
        ' Fire off the client asynchonously, but don't block this thread
        mqtt_client.StartAsync(mqtt_options)
```

**Comment by duncanellison** [comment]
Update :  This (below) does work. 

I was trying to create the client as a Public outside the Function code block so it would also be available to other Subs.

```
Public Module MQTTFunctions

    Public Sub StartMQTTConnection(ByVal returnCode As Integer)

        ' Now create an MQTT client with global scope
        Dim mqtt_client = New MqttFactory().CreateManagedMqttClient

        ' This routine spins up the MQTT engine.
        ' It uses library MQTTNet from chkr10011 in 'Managed Client' mode
        ' 
        AddHandler mqtt_client.Disconnected, AddressOf MQTTclient_disconnected_handler
        AddHandler mqtt_client.Connected, AddressOf MQTTclient_connected_handler
```

**Comment by duncanellison** [comment]
Issue resolved - Scope issue

**Comment by duncanellison** [comment]
Just to confirm that this is firing nicely now :-)

`    Friend Sub MQTTclient_ApplicationMessageProcessed_handler(sender As Object, e As MQTTnet.ManagedClient.ApplicationMessageProcessedEventArgs)
        ' An application mesage was received for a subscribed topic
        ' TODO : Write a received message handler
        Console.WriteLine("MQTT Message published successfully")
    End Sub`
