### ISSUE TITLE
Bridge mqtt broker? 

### ISSUE THREAD

**Issue by DrSensor** [chkr1011/MQTTnet#196]
Hello,
Is it possible to bridge multiple (or at least one) mqtt broker using this library?
Currently I'm looking for solution to forward mqtt data from local broker into broker in the cloud. (and vice versa).

Regards, 
Wildan

**Comment by chkr1011** [comment]
Hi @DrSensor,
yes you can access every incoming message from the server and forward it with a client i.e.

Best regards
Christian

**Comment by DrSensor** [comment]
Thank you. Any clue or hints how to do that?

**Comment by chkr1011** [comment]
You can start a server and attach to the _ApplicationMessageReceived_ event and use another client instance (which is connected to another broker) to publish the message.
