### ISSUE TITLE
Cannot connect to iot.eclipse.org

### ISSUE THREAD

**Issue by zyofeng** [chkr1011/MQTTnet#197]
Hi
I tried two public brokers
ws://iot.eclipse.org:80/ws/mqtt
and 
ws://broker.hivemq.com:8000/mqtt

Hivemq works perfectly but eclipse kept on erroring out, is there a bug in the client?

sample code below
await _mqttClient.StartAsync(new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                .WithClientOptions(new MqttClientOptionsBuilder()
            .WithWebSocketServer(*replace with connection string*)
            .Build())
               .Build()

**Comment by zyofeng** [comment]
Just to clarify I tested both connection string with hivemq websocket client below and confirmed they are online.
http://www.hivemq.com/demos/websocket-client/

**Comment by chkr1011** [comment]
Hi, I tested this with version 2.7.3 and the UWP test app and it works without issues.
![image](https://user-images.githubusercontent.com/6939810/38393477-3592be76-392b-11e8-82d4-68ef69e1b5b0.png)

Please also test again with 2.7.3.
Best regards
Christian
