### ISSUE TITLE
Extend Options once built ?

### ISSUE THREAD

**Issue by duncanellison** [chkr1011/MQTTnet#199]
I'm sure this is possible, but I'm struggling with the 'fluid syntax' here.

Objective : I'm trying to conditionally compile .withTLS into my options using ManagedMqttClientOptionsBuilder.

I already have this working code:

`        Dim mqtt_options = New ManagedMqttClientOptionsBuilder().WithAutoReconnectDelay(TimeSpan.FromSeconds(5)) _
                .WithClientOptions(New MqttClientOptionsBuilder() _
                    .WithClientId(MQTT_ClientID) _
                    .WithTcpServer(MQTT_Server, MQTT_Port) _
                    .WithCredentials(MQTT_Username, MQTT_Password) _
                    .WithCleanSession() _
                    .WithCommunicationTimeout(communicationTimeout) _
                    .WithKeepAlivePeriod(keepAlivePeriod) _
                    .WithProtocolVersion(protocolVersion) _
                    .WithWebSocketServer("False") _
                .Build()).Build()` 

Now I'm trying to add :

`        If MQTT_Secure Then
               <extend mqtt_options with the options builder to add .withTLS(blah, blah)>
        Else
            ' Do nothing
        End If
`

I assumed that was possible, but I can't seem to pick up the right way to do it.  Does the option builder even support that? 

Or is this an equally valid approach - if a little longer:
  ```
    Dim mqtt_options = New ManagedMqttClientOptionsBuilder().WithAutoReconnectDelay(TimeSpan.FromSeconds(5)) _
                .WithClientOptions(New MqttClientOptionsBuilder() _
                    .WithClientId(MQTT_ClientID) _
                    .WithTcpServer(MQTT_Server, MQTT_Port) _
                    .WithCredentials(MQTT_Username, MQTT_Password) _
                    .WithCleanSession() _
                    .WithCommunicationTimeout(communicationTimeout) _
                    .WithKeepAlivePeriod(keepAlivePeriod) _
                    .WithProtocolVersion(protocolVersion) _
                    .WithWebSocketServer("False") _
                .Build()).Build()

         TODO : Add tls certificate handling
        If MQTT_Secure Then
            mqtt_options.ClientOptions.ChannelOptions.TlsOptions.UseTls = True
            mqtt_options.ClientOptions.ChannelOptions.TlsOptions.IgnoreCertificateChainErrors = True
            mqtt_options.ClientOptions.ChannelOptions.TlsOptions.AllowUntrustedCertificates = True
            mqtt_options.ClientOptions.ChannelOptions.TlsOptions.IgnoreCertificateRevocationErrors = True
            mqtt_options.ClientOptions.ChannelOptions.TlsOptions.Certificates(myCert)
        Else
            mqtt_options.ClientOptions.ChannelOptions.TlsOptions.UseTls = False
        End If`

```

Duncan

**Comment by duncanellison** [comment]
Just to add another point to this question.

I read that mostly just setting .useTLS to true is sufficient when using the _**client**_ .  I'm assuming then that the client is drawing on the Windows Certificate store (i.e. external to MQTTNet) to validate the certificate - Do I have that correct ?

**Comment by chkr1011** [comment]
The options builder only provides a fluent API for the options and also does not covers all settings. Only the most used ones. You can aalways assign all values on your own like in your lower example.

Validating the cert depends on .net internals. The lib only uses encrypted streams. But I assume that it is accessing the personal store for validation.

**Comment by duncanellison** [comment]
Thank for confirming that Christian.

I'll close this one.
