### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by Zazzmatazz** [chkr1011/MQTTnet#2]
Good morning,

I've been planning to use this library in one of my projects, but I have noticed an omission:  SSL/TLS support on port 8883.  See [this](http://www.hivemq.com/blog/mqtt-security-fundamentals-tls-ssl) for information.

Is it possible to add this feature to the library?  Cheers!

**Comment by chkr1011** [comment]
Hi,
I assume you require this for MQTTClient only or for MQTTServer as well?

This feature is actually not on the list but I agree that this is very useful.
Do you want to add it and create a pull request?

If not I will put this on my list but I assume it will require some time to complete.

Best regards
Christian

**Comment by Zazzmatazz** [comment]
I personally require it only for the MQTTClient, but it would be prudent to add the feature to the MQTTServer as well.

I can take a look at the code and see whether I can add it, and I'll let you know.

Cheers,
PdM

**Comment by chkr1011** [comment]
OK perfect, then let me know :)

**Comment by Zazzmatazz** [comment]
I've gone ahead and added the SSL support and created a [pull request](https://github.com/chkr1011/MQTTnet/pull/3) for your perusal.

Cheers!
PdM

**Comment by chkr1011** [comment]
Hi, 
I reviewed the changes. Good work!
I will take care of the Universal-Framework changes when it is merged.

Best regards
Christian

**Comment by chkr1011** [comment]
Hi,
I added the UniversalWindows part and refactored some parts. Can you tell me if the state from the develop-branch works for you? If it works I will release version 2.1.3 soon.

Best regards
Christian

**Comment by Zazzmatazz** [comment]
Looks good!  Should work well enough.

I don't see where in [MqttServerAdapter.cs](https://github.com/chkr1011/MQTTnet/blob/develop/Frameworks/MQTTnet.UniversalWindows/Implementations/MqttServerAdapter.cs) where `_sslCertificate` is consumed.  I am not familiar enough with the Universal Windows framework to know exactly what the process is, but from what I can gather for the client side:

```CSharp
var socket = new StreamSocket();
Windows.Security.Cryptography.Certificates.Certificate cert = ...;
socket.Control.ClientCertificate = certificate;
await socket.ConnectAsync(dest, SocketProtectionLevel.Tls12);
```

Perhaps there is a similar method for `StreamSocketListener`?

**Comment by chkr1011** [comment]
Ah yes I forgot to say that I will test if this is supported. At the moment only the Client side is completed for all frameworks.

Where did you read that it is not supported?

**Comment by Zazzmatazz** [comment]
Ah, perfect then.

The not supported part can be found on the [docs](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Sockets.StreamSocket#Windows_Networking_Sockets_StreamSocket_UpgradeToSslAsync_Windows_Networking_Sockets_SocketProtectionLevel_Windows_Networking_HostName_):  The UpgradeToSslAsync method only implements the client parts of the SSL protocol negotiation, not the server parts that would be needed to listen for and accept SSL connections.

**Comment by chkr1011** [comment]
Mhh this is confusing because the StreamSocketListener has a parameter which accepts TLS when binding to a port etc!? But I found no way to set the certificate.

So I assume you area right and I need to throw a "NotSupportedException" there. Stupid UWP! I found some blog articles about that. No HTTP server, no SSL support. And this is an IoT platform!?

**Comment by Zazzmatazz** [comment]
Aye, I don't know.  Microsoft seriously dropped the ball on the serverside here.

The best course of action is to throw a `NotSupportedException` explaining why the feature isn't in UWP, then send a letter to Microsoft requesting proper SSL support.

C'est la vie.

**Comment by chkr1011** [comment]
You are right. I added a NotSupportedException... I will release a new nuget-package soon. Thanks for your support.
