### ISSUE TITLE
Protocol name is not MQTT when testing with MQTTLens

### ISSUE THREAD

**Issue by wind-rider** [chkr1011/MQTTnet#20]
[MQTTLens](https://chrome.google.com/webstore/detail/mqttlens/hemojaaeigabkbcookmlgmdigohjobjm) is a popular testing / debugging tool for mqtt traffic. When I test it with MQTTnet 2.1.5 the exception at https://github.com/chkr1011/MQTTnet/blob/0172606747e7e3aecca999a798f837c02b74356d/MQTTnet.Core/Serializer/DefaultMqttV311PacketSerializer.cs#L263 is triggered.

**Comment by wind-rider** [comment]
The cause is that `Encoding.UTF8.GetString(protocolName, 0, protocolName.Length)` returns `MQIs`

**Comment by chkr1011** [comment]
I can implement this but it seems that this "MQIs" is identifying version 3.1 of the MQTT protocol. And this version is currently not supported. Do you know some details about this? Are these versions compatible (at least in meaning of packet types and format)?

**Comment by wind-rider** [comment]
Yes i also think that it is version 3.1; an alternative for testing would be http://www.hivemq.com/demos/websocket-client/ but that only works with web sockets

**Comment by chkr1011** [comment]
I will add support for MQTT 3.1.0 in the next version (2.2.0). Then MQTTLens will work. Please wait a couple of days.
