### ISSUE TITLE
Published Messages Dropped and Last Message Re-Published

### ISSUE THREAD

**Issue by ksmiller99** [chkr1011/MQTTnet#201]
I may have found a bug, but hopefully, I'm doing something wrong. If messages are published quickly, for example in a for-next loop, the last message is published n times instead of n distinct messages being published. This can be seen in the publisher's trace.  Adding a delay in the for-next loop reduces the dropping. A high enough delay will prevent any messages from being dropped.

I created a git (<a href="https://github.com/ksmiller99/MqttNetTest">here</a>) with screenshots, code, and more detail.

**Comment by chkr1011** [comment]
Hi,
thanks for reporting this issue in a very detailed way. You said that only the latest message is published n times and that messages are dropped (not processed in any way). Are both things happening at the same time?

I will investigate the issue soon.

Best regards
Christian

**Comment by chkr1011** [comment]
Maybe I found an issue in your code. You are reusing the same message in the loop in the publisher. You must instead always create a new message before sending.

On the other hand I will still check why this may causes the error because in theory the messages should be send after each other and thus reusing the same message should work.

**Comment by ksmiller99** [comment]
Hi Christian,
You are exactly correct. When I create a new message inside the loop, it
works as expected. I will update my repo and the issue in your repo later
today. I don't see a GUID in the MqttApplicationMessage class, so I thought
I could save a little time by re-using the message.

Thanks for your help! Your project is a great help to me!

Kevin
