### ISSUE TITLE
Trying to set up Tls with Mosquito Broker 

### ISSUE THREAD

**Issue by rvca1140** [chkr1011/MQTTnet#203]
I am currently trying to use MQTTnet's TLS feature with a Mosquito Broker for encrypted transmission and the client seems to be unable to connect whenever I set the .WithTls() as part of the client options. 
current code for setting up client - 

var factory = new MqttFactory();
                var options = new MqttClientOptionsBuilder()
                .WithClientId(Environment.MachineName + "Reciver")
                .WithTcpServer(address, 8883)
                .WithCredentials(user, pass)
                .WithCleanSession()
                .WithTls()
                .Build();
                var mqttClient = factory.CreateMqttClient();
                await mqttClient.ConnectAsync(options);

and changes made to mosquito broker to allow for TLS -
port 8883
# capath
cafile C:\Program Files (x86)\mosquitto\certs\m2mqtt_ca.crt

# Path to the PEM encoded server certificate.
certfile C:\Program Files (x86)\mosquitto\certs\m2mqtt_srv.crt

# Path to the PEM encoded keyfile.
keyfile C:\Program Files (x86)\mosquitto\certs\m2mqtt_srv.key

# valid values are tlsv1.
tls_version tlsv1

any help would be much appreciated.

**Comment by chkr1011** [comment]
Please provide some traces so the error can be seen. Is the validation chain maybe broken?
