### ISSUE TITLE
ClientId in ApplicationMessageReceived

### ISSUE THREAD

**Issue by Gonzo4** [chkr1011/MQTTnet#204]
Hi,

If I use the ApplicationMessageReceived of the MqttClient, the ClientId of the MqttApplicationMessageReceivedEventArgs is always set to the ClientId of the receiving client and not to the ClientId of the sending client. If I use the ApplicationMessageReceived of the MqttServer the ClientId is set to the ClientId of the sending client as expected. Is this a bug or did I misunderstood the ClientId ;)

Thanks!

**Comment by chkr1011** [comment]
Hi,
the CientId is always the ID of the sender because the client  doesn't know the sender ID. This is not transmitted from the server to the client. But the same object is used within the server because the interface is the same.

Best regards
Christian
