### ISSUE TITLE
Windows 10 example link not working

### ISSUE THREAD

**Issue by dongouyang** [chkr1011/MQTTnet#207]
Windows 10 example link does not work.  Could anyone provide an example?

MQTT Tester (MQTT client test app for Android, iOS, and Windows 10)
https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=ng4zg7K+O0uvzkAt.4

Thanks

**Comment by chkr1011** [comment]
Hi,
please provide the correct link. The error link you posted is a static error page!?
Best regards
Christian

**Comment by chkr1011** [comment]
@1iveowl Please let me know if the app still exists. If not I will cleanup the master page and remove the Windows Edition.
