### ISSUE TITLE
How to exchange data from broken server from/to asp.net web api? 

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#208]
How to exchange data from broken server from/to asp.net web api?

**Comment by rshillington** [comment]
Both of IMqttServer and IMqttClient have SubscribeAsync and PublishAsync methods.

If you want to server to send something to one or more clients your server code needs to call the PublishAsync method on a Topic that your client has subscribed to.  Likewise, if the client is to send something to the server, it can also publish to the server on a Topic that the server is subscribing to.  The only difference is that the server gets the clientId (so it can tell who's talking to it)

**Comment by biapar** [comment]
Ok. Is there an example if the client is a web client or a rest service?

**Comment by JanEggers** [comment]
the main problem is that http is request / response and mqtt is publish / subscribe
i see some options:

1. get call semantic
1.1 with this https://github.com/chkr1011/MQTTnet/blob/master/Extensions/MQTTnet.Extensions.Rpc/MqttRpcClient.cs

1.2 do your own thing to create "call symantic"

2. forget webapi and use mqttjs in the browser to get the data from mqtt

**Comment by biapar** [comment]
But 1 and 1.2 can be done with SignalR.
