### ISSUE TITLE
When using SubscriptionInterceptor the client doesn't learn that the subscription is not accepted

### ISSUE THREAD

**Issue by rshillington** [chkr1011/MQTTnet#209]
I'm using SubscriptionInterceptor to block subscriptions to topics that the client doesn't have permission for.  That part works great.

However it seems that there is no way for the client to know that their subscription has been denied.  Is this by design?

**Comment by chkr1011** [comment]
Hi,
which client do you use? The managed one or a different? The server returns "Failure = 0x80" if a subscribe has been denied. Then the client can decide to no longer subscribe to that topic.
Best regards
Christian
