### ISSUE TITLE
Exception & Crash on disconnect for a lot of client connection/disconnection

### ISSUE THREAD

**Issue by Flo1987** [chkr1011/MQTTnet#210]
It's maybe the same problem describe in issue #198 (Exception & Crash on disconnect).
I use the version 2.7.2 of the library and i always have an error on the disconnect.
My application will have very often a new client connection/disconnection after a message sended. I try to do a stress test in that case (project VS in zip file)
In case whare my method is bad, can you tell me a better method to do what?

![capture](https://user-images.githubusercontent.com/8143811/37959601-ca5cc260-31b3-11e8-935c-7ae90978187f.PNG)
[ConsoleApplication1.zip](https://github.com/chkr1011/MQTTnet/files/1851374/ConsoleApplication1.zip)

**Comment by chkr1011** [comment]
Hi,
I tested your code and was able to reproduce it. Please try it again using version 2.7.3-rc1.
Let me know if this version works.
Best regards
Christian

**Comment by biapar** [comment]
I follow.

**Comment by Flo1987** [comment]
Hi,
thanks for you quick response, i have test with the version 2.7.3-rc1 and i always have an error on the disconnect method. In attachement, the capture of the error.

Best regards.

![capture](https://user-images.githubusercontent.com/8143811/38012789-0c264fe0-3263-11e8-8442-7a365c0fb2f1.PNG)

**Comment by chkr1011** [comment]
I fixed some more issues and now you test app runs several times from 0 to 200. Please test with version 2.7.3-rc3 again and let me know if this works.

**Comment by Flo1987** [comment]
I have tested with the version 2.7.3 RC3 and no problem with a loop of 1500, so i think it's work.
