### ISSUE TITLE
Connecting to AWS IOT with SigV4 - "Unable to connect to the remote server" on Xamarin

### ISSUE THREAD

**Issue by prokis65** [chkr1011/MQTTnet#211]
I have no problems connecting to AWS IOT with SigV4 when using MQTTnet (2.7.1) and WPF (net framework 4.6.1)
but I still have an exception "Unable to connect to the remote server" with excactly the same code but on Xamarin platform.
Any idea?

**Comment by chkr1011** [comment]
Hi,
did you maybe forget the "INTERNET" permission?
Please provide some more information like traces or debug output.
Best regards
Christian

**Comment by chekodev** [comment]
Hello.
Unfortunately, there is an incompatibility when using System.Net.Sockets + AWS IOT SigV4 MQTT + Xamarin. This incompatibility is exception message "Unable to connect to the remote server"
Most of the MQTT Clients for .net using System.Net.Sockets as its layer of ws: or wss: protocol connection. Including MQTTnet.
The only way I found to connect me to AWS IOT SigV4 MQTT was through the following fork [https://github.com/cityzenith/paho.mqtt.m2mqtt](https://github.com/cityzenith/paho.mqtt.m2mqtt)
It is not MQTTnet but just work for me. It includes a way to use sockets WebSocket4Net (apparently are highly recommended and supported by Xamarin) using a class called WebSocketMqttNetworkChannel that is added in the constructor of the client MQTTnet in your code.

**Hopefully, the MQTTnet team @chkr1011 could provide a guide for use the MQTTnet.Channel.IMqttChannel Interface to be able to easily implement WebSocket4Net in MQTTnet.
If you are interested in the solution with M2MQTT, I can share an example.**

**Comment by prokis65** [comment]
Hello,
Thank you very much for your explanation. I spent a lot of time googling how to connect to AWS IOT broker using MQTT over Websocket and Xamarin and almost lost my faith. If its possible share with your working solution, please.

Regards

Piotr

**Comment by chekodev** [comment]
After obtaining the url SigV4, have appropriate permissions on AWS for the user to connect and attach the policy to the user.

1. Clone or download the repo https://github.com/cityzenith/paho.mqtt.m2mqtt. (I recommend that this together with the **Xamarin Solution** for easy location)

2. Delete the file _M2Mqtt/Properties/AssemblyInfo.cs_  (this file has incompatibility with Xamarin and apparently is damaged or obfuscated)

3. Edit the file _M2Mqtt/M2Mqtt.Shared.projitems_ with a text editor and remove the line
```
< compile Include = "$(MSBuildThisFileDirectory) Properties\AssemblyInfo. cs" / >
```
(this will prevent to **Shared Project**, locate the deleted file)

4. In your **Xamarin solution** we add an existing project, look for **Shared Project** and add it to our **Xamarin solution**.

5. Open the _M2Mqtt/Net/MqttNetworkChannel.cs_ file and add the following references
```
using System.Net.Security; 
using System.Security.Authentication;
```

6. Open the _M2Mqtt/MqttClient.cs_ file and add the reference
```
using System.Net.Security;
```

With this we will have in our solution compatible with Xamarin and WebSocket4Net M2Mqtt

7. Add the reference of **Shared Proyect** to **Your Project** in which we want to use MQTT (in my case is the PCL Xamarin Forms) Note: If you already have installed some Nugget of MQTT I recommend uninstalling it to avoid confusion of namespaces.

8. Install the nuget Kerry Jiang WebSocket4Net in **Your project**

9. Create a **new file** c# in **Your Project** called WebSocketMqttNetworkChannel.cs, look for the file of the same name in M2Mqtt repo _M2Mqtt.Net.WebSockets/Net/WebSocketMqttNetworkChannel.cs_ and copy its content to our **new file.**

With this we have the desired compatibility, it is time to prove.
In **The file where we will implement MQTT logic** we code something like this:

```
var channel = new uPLibrary.Networking.M2Mqtt.WebSocketMqttNetworkChannel(signedUrl);//Url SigV4
var mqttClient = new uPLibrary.Networking.M2Mqtt.MqttClient(null, 443, false, uPLibrary.Networking.M2Mqtt.MqttSslProtocols.None, null, null, channel);
 
mqttClient.MqttMsgPublishReceived += MqttClient_MqttMsgPublishReceived; //register the desired events
 
mqttClient.Connect(Guid.NewGuid()).ToString());
 
mqttClient.Subscribe(new string[] {"MyTopic"}, new byte[] {1}); We subscribe to the topic
```
 
To be everything correctly received messages in the event MqttClient_MqttMsgPublishReceived

**Comment by prokis65** [comment]
Thank you very much.
With your instructions it was piece of cake. I managed to compile my
solution, connect to ASW IOT, publish and subscribe.
I knew about some paho mgtt clones but MQTTnet has nice nuget packets ... :)
I'm gona test it more deeply now.

Regards

2018-04-05 18:28 GMT+02:00 chekodev <notifications@github.com>:

**Comment by chkr1011** [comment]
Is someone able to share the trace and Wireshark export when connecting with AWS? I am wondering why this is not working when using WebSockets from .NET framework.

**Comment by prokis65** [comment]
Today I tested version 2.8.0 in my project again but the same problem still exists.

Regards

**Comment by chkr1011** [comment]
I build a test adapter factory supporting _WebSocket4Net_.

```csharp
public class WebSocket4NetMqttClientAdapterFactory : IMqttClientAdapterFactory
{
    public IMqttChannelAdapter CreateClientAdapter(IMqttClientOptions options, IMqttNetChildLogger logger)
    {
        if (options == null) throw new ArgumentNullException(nameof(options));
        if (logger == null) throw new ArgumentNullException(nameof(logger));

        if (!(options.ChannelOptions is MqttClientWebSocketOptions))
        {
            throw new NotSupportedException("Only WebSocket connections are supported.");
        }

        return new MqttChannelAdapter(new WebSocket4NetMqttChannel(options), new MqttPacketSerializer(), logger);
    }

    private class WebSocket4NetMqttChannel : IMqttChannel
    {
        private readonly BlockingCollection<byte> _receiveBuffer = new BlockingCollection<byte>();

        private readonly IMqttClientOptions _clientOptions;
        private WebSocket4Net.WebSocket _webSocket;

        public WebSocket4NetMqttChannel(IMqttClientOptions clientOptions)
        {
            _clientOptions = clientOptions ?? throw new ArgumentNullException(nameof(clientOptions));
        }

        public string Endpoint { get; } = "";

        public Task ConnectAsync(CancellationToken cancellationToken)
        {
            var channelOptions = (MqttClientWebSocketOptions)_clientOptions.ChannelOptions;

            var uri = "ws://" + channelOptions.Uri;
            var sslProtocols = SslProtocols.None;

            if (channelOptions.TlsOptions.UseTls)
            {
                uri = "wss://" + channelOptions.Uri;
                sslProtocols = SslProtocols.Tls12;
            }

            var subProtocol = channelOptions.SubProtocols.FirstOrDefault() ?? string.Empty;

            _webSocket = new WebSocket4Net.WebSocket(uri, subProtocol, sslProtocols: sslProtocols);
            _webSocket.DataReceived += OnDataReceived;
            _webSocket.Open();
            SpinWait.SpinUntil(() => _webSocket.State == WebSocketState.Open, _clientOptions.CommunicationTimeout);
            return Task.FromResult(0);
        }

        public Task DisconnectAsync()
        {
            if (_webSocket != null)
            {
                _webSocket.DataReceived -= OnDataReceived;
                _webSocket.Close();
                SpinWait.SpinUntil(() => _webSocket.State == WebSocketState.Closed, _clientOptions.CommunicationTimeout);
            }

            _webSocket = null;

            return Task.FromResult(0);
        }

        public Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        {
            var readBytes = 0;
            while (count > 0 && !cancellationToken.IsCancellationRequested)
            {
                if (!_receiveBuffer.TryTake(out var @byte))
                {
                    if (readBytes == 0)
                    {
                        // Block until at lease one byte was received.
                        @byte = _receiveBuffer.Take(cancellationToken);
                    }
                    else
                    {
                        return Task.FromResult(readBytes);
                    }
                }

                buffer[offset] = @byte;
                offset++;
                count--;
                readBytes++;
            }

            return Task.FromResult(readBytes);
        }

        public Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        {
            _webSocket.Send(buffer, offset, count);
            return Task.FromResult(0);
        }

        public void Dispose()
        {
            if (_webSocket != null)
            {
                _webSocket.DataReceived -= OnDataReceived;
                _webSocket.Dispose();
            }
        }

        private void OnDataReceived(object sender, WebSocket4Net.DataReceivedEventArgs e)
        {
            foreach (var @byte in e.Data)
            {
                _receiveBuffer.Add(@byte);
            }
        }
    }
}
```

You can use this factory via generating the client like in the following example:

```csharp
var options = new MqttClientOptionsBuilder().WithWebSocketServer("test.mosquitto.org:8081/mqtt").WithTls().Build();
var mqttClient = new MqttFactory().CreateMqttClient(new MqttNetLogger(), new WebSocket4NetMqttClientAdapterFactory());
await mqttClient.ConnectAsync(options);
await mqttClient.SubscribeAsync("Test");
```

**Comment by prokis65** [comment]
Can I use this lib for web socket communication in Xamarin?
Beside AWS IOT with SigV4 I have to connect to a web socket server in local LAN.
Can you give a guidance, please.

Regards
Piotr

**Comment by 12345929** [comment]
Hi @prokis65 ,

could you please share your code of connecting to AWS IOT? I have difficulty to make it work.

thanks

**Comment by chkr1011** [comment]
@12345929 please try with the WebSocket4net snipped I posted above.

**Comment by 12345929** [comment]
@chkr1011 Thanks very much for your reply, could you please advise which library contains MqttPacketSerializer class?

**Comment by chkr1011** [comment]
Oh sorry I forgot that this is not compatible with 3.0.0 (yet). Please try the above code with 2.8.5. If it works I will port that to 3.0.0 and make a proper extension nuget from that.

**Comment by 12345929** [comment]
Hi @chkr1011 after installed 2.8.5, previous issue was gone, however, there is one more complaint for below code line:
`SpinWait.SpinUntil(() => _webSocket.State == WebSocketState.Open, _clientOptions.CommunicationTimeout);`

"Operator cannot be applied to operands of type "WebSocketState" and "WebSocketState"

**Comment by uksreejith** [comment]
> 
> 
> Hi @chkr1011 after installed 2.8.5, previous issue was gone, however, there is one more complaint for below code line:
> `SpinWait.SpinUntil(() => _webSocket.State == WebSocketState.Open, _clientOptions.CommunicationTimeout);`
> 
> "Operator cannot be applied to operands of type "WebSocketState" and "WebSocketState"

You are most probably comparing System.Net.WebSockets.WebSocketState with WebSocket4Net.WebSocetState.

**Comment by asierras** [comment]
Hi! Is this working with Unity? I am trying the snippet websocket4Net but seems it does nothing. The project without webSocket4Net works flawlessly in visual studio as a windows form project but in Unity it always return websocket exception.
