### ISSUE TITLE
How much concurrency can be supported

### ISSUE THREAD

**Issue by systemxgl** [chkr1011/MQTTnet#212]
How much concurrency can be supported

**Comment by chkr1011** [comment]
Hi,
sorry but I don't undertsand your question. Please add some more information.
Best regards
Christian

**Comment by systemxgl** [comment]
How many links are supported in one second

**Comment by chkr1011** [comment]
Sorry but I did not measured this yet. So you have to evaluate this on your own.
Best regards
Christian
