### ISSUE TITLE
Any disconnect reliability issues with MqttClient

### ISSUE THREAD

**Issue by rshillington** [chkr1011/MQTTnet#216]
So far all of the client applications that I've written with MqttClient have been netcoreapp2.0 running as services on IoT like devices.  Works great.

Today I've squandered a solid 8 hours trying to get the same MqttClient code working in a WPF (.net 4.6 or 4.71) app.

Generally the Disconnect event never fires when the network connection is disabled.  No problem getting the Disconnected event when calling DisconnectAsync (or StopAsyc. I've been working with both Client and ManagedClient). The issue is that it's not detecting the network failures.

Also I've noticed that there seems to be a number of ConnectedClient objects in the server which never get cleaned up.  I believe this is also related to a failure to handle the client side network failure.

I have a minimalist WPF app (at the office) that I can put in a repo somewhere if somebody is curious.

I've really loved working with this library, both on the broker side, as well as the client, well except for today's client.

**Comment by rshillington** [comment]
I've added the minimalist WPF app https://github.com/rshillington/MqttNetWPFClientSample.git
This thing just connects to ws://broker.hivemq.com:8000/mqtt and mimics the sample at http://mitsuruog.github.io/what-mqtt/

In this sample app I've added a "WatchDog" timer that watches the IsConnected flag and reports when that flag becomes false.  What's bizarre is the flag turns false right on time, ~15 seconds after I pull the plug, yet the disconnected event doesn't fire.  Also there are a set of Exception Thrown messages in the Debug.Output window, again right on time ~15 seconds after pulling the plug on the network connection.

Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' in MQTTnet.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' in mscorlib.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' in MQTTnet.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' in mscorlib.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' in mscorlib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll
[etc  --- there are quite a few more of these]

**Comment by setamodius** [comment]
Disconnect event works in version 2.7.2 but does not work in version 2.7.3.

**Comment by rshillington** [comment]
Wow --- thanks for that tip.  I'm curious to see in the change sets what happened to break that bit of functionality.

**Comment by chkr1011** [comment]
Thank you for reporting the issue. I found a dead lock in the disconnect method in 2.7.3. I will release 2.7.4 soon.

Regarding the connected clients in the server. This is by design at the moment. There is no ways to manage the sessions. They will live forever at the moment (without blocking a lot of memory. Only meta data is stored). But the plan for a future release is to allow injection of a custom session manager. Then you can remove sessions with your own logic etc.

**Comment by rshillington** [comment]
Looks like the disconnect issue is sorted out.  AWESOME.

The idea if injecting a custom session manager is great, and would certainly streamline things for me.  When that's ready I'll test it right away.

**Comment by chkr1011** [comment]
OK I will let you know 👍
