### ISSUE TITLE
Broker hangs when stopping

### ISSUE THREAD

**Issue by Tatasterix** [chkr1011/MQTTnet#218]
Hi,

I'm having some troubles when trying to stop the MQTT server. The StopAsync() method hangs in the 2 scenario (i'm not sure if they are related to the same problem or not) described below.

**Context:** 1 Broker, 2 Clients

**First scenario:** 
Start the broker
Connect both clients
Wait a little to be sure there is no communication error (Ping messages are visible into logs)
Broker sends a message to clients (no effect in this scenario)
Stop the broker **(it hangs)**
        One of the client is effectively disconnected (after a timeout)
        The second one is still sending/receiving ping (the communication is still alive)

After some tests, I've found that it seems to be due to both clients defining exactly the same will message property during its connection. (Removing the WithWillMessage() fix the problem)

**Second scenario:** 
Start the broker
Connect both clients
Wait a little to be sure there is no communication error (Ping messages are visible into logs)
Broker sends a message to clients
One of the client disconnect properly when receiving the message from the broker
Stop the broker **(it hangs)**
        The second client is effectively disconnected (after a timeout)

In that case, i'm not really sure of what happened but i was hoping that closing one of the client properly will allow to stop the second one successfully, on broker stop, without hanging the broker.

Am I misusing the Will message ?

**Another question**, not related to that problem: Why the client is not immediately notified that the broker has closed its connection ? 
Indeed, as the broker is closing all the communication properly, i would expect all clients to notify its listeners immediately. But currently, I observed that the client is sending the Disconnected event only after detecting that a PingResp has not been received after sending a PingReq. It can leads to a large amount of time before being notified, following the KeepAlivePeriod and CommunicationTimeout time configured.

I'm using MQTTServer and MQTTClient with the last version of **MQTTnet.dll (2.7.4)**

In the attached file, you will find a project which reproduce the problem.
The project contains 2 console applications, one which launch a broker and another which start 2 clients. The solution is configured to start both applications when debugging.
By default the first scenario is executed. In order to execute the second one, just uncomment the only one commented line in the Program.cs file of the ConsoleApplication2 project.
I've also added log4net to print logs into files as i got some troubles when using Console.WriteLine(). Log files are located in {outputDirectory}/Logs/MqttCommunication.log

[MQTT_Test.zip](https://github.com/chkr1011/MQTTnet/files/1903479/MQTT_Test.zip)

**Comment by chkr1011** [comment]
Hi, thanks for reporting this issue and providing the sample app. I started it but I cannot see the trace outputs. Is there something missing for the log4net config?
Best regards
Christian

**Comment by Tatasterix** [comment]
I tested it again and it is logging correctly.
Log files are located in:
**MQTT_Test\ConsoleApplication1\bin\Release\Logs** folder for the broker
**MQTT_Test\ConsoleApplication2\bin\Release\Logs** folder for clients
(because the solution is building in Release by default)

If needed, i can provide you some sample log files.
