### ISSUE TITLE
High water mark and flood prevention

### ISSUE THREAD

**Issue by israellot** [chkr1011/MQTTnet#219]
Testing a flood situation I could see that both client and server will pile up messages indefinitely, until they go out of memory. Is there a way to configure the server to start dropping messages after a high water mark so the server survives a flood ?

**Comment by chkr1011** [comment]
In theory a good idea but I have no idea how to detect this. Memory allocation? Count of pending messages? Count of messages per second?

**Comment by biapar** [comment]
An idea could be a queue manager integrated in the broker. So client send messages to queue-in to the broker and broker send out messages into queue-out.  So we can measure the lenght of the queue.
Is't possible to integrate with small and fast https://redis.io/ used like queue cache / manager.
But How to insert this logic into the broker?

**Comment by chkr1011** [comment]
Limits for this are added in version 2.8.0 which will be released soon.
