### ISSUE TITLE
MQTTnet.Core.Exceptions.MqttProtocolViolationException: 'Packet type (0) not supported.'

### ISSUE THREAD

**Issue by wind-rider** [chkr1011/MQTTnet#22]
It seems that when using MQTTnet with this popular [mqtt](https://www.npmjs.com/package/mqtt) npm package, a packet type "0" is sent.

This causes exceptions in MQTTnet.

**Comment by chkr1011** [comment]
But the question is what packet type "0" does!? In the official MQTT documentation type "0" is reserved and should not be used. Do you know why this library is sending "0"?

**Comment by wind-rider** [comment]
No, i have no idea.. just that by default that library sends 0 (you can try the example from the npm page)

**Comment by chkr1011** [comment]
I tested it with the MQTTnet server and a client in node.js using the _mqtt_ packet. The example code works as expected without problems. 

Please keep in mind that this exception is only a warning in the trace. This situation can happen when the connection is closed while receiving a packet (like ping etc.). 
A possible solution is to filter packets with type _0_.

Can you please retry and tell me if that problem sill exists?

**Comment by chkr1011** [comment]
I assume this issue is fixed. If not please reopen the ticket.
Best regards
Christian
