### ISSUE TITLE
Is it possible to publish a message to client when it subscribes to specific channel?

### ISSUE THREAD

**Issue by ahmadalli** [chkr1011/MQTTnet#221]

**Comment by chkr1011** [comment]
Hi, 
you can use a custom subscription interceptor and publish a message if a certain topic was subscribed.
Best regards
Christian

**Comment by ahmadalli** [comment]
I'm implementing a chat server and I needed to send a message only to one user. I've implemented it by taking and modifying your source:

[b2a1c773667048312b15086427c8e806598a9d42.patch.txt](https://github.com/chkr1011/MQTTnet/files/1925743/b2a1c773667048312b15086427c8e806598a9d42.patch.txt)

since I wasn't sure whether it's a clean solution or not, I didn't send a PR for that.

**Comment by ahmadalli** [comment]
take a look at this commit:
https://github.com/ahmadalli/MQTTnet/commit/637efc89b098fbd4a724006e335dc7c2f0ea541e

**Comment by chkr1011** [comment]
From server side this can be done theoretically. As you have done in your code. But from MQTT perspective this is not "allowed". The clients decide via a subscription what the want to receive. If you add not requested data to the queue I would advise to not use MQTT because it has no benefits and other protocols may work better for your case.

**Comment by ahmadalli** [comment]
you're right. we needed a simple communication platform and MQTT seemed about right. But we have to change the way we use MQTT.
Thanks :)

**Comment by henon** [comment]
@ahmadalli I know, stale thread, but for anyone searching and finding this thread there is a legal way to do private communication between broker and client:

In order for only one client to receive messages, you can authorize only that particular client to subscribe to the topic and reject authorization for all other clients. This way only one client will subscribe to the topic and hence only that client will receive messages published on the topic. In MQTT, this is called Topic Authorization
