### ISSUE TITLE
$SYS

### ISSUE THREAD

**Issue by AngeloBestetti** [chkr1011/MQTTnet#228]
Do you have idea when are you going to implement $SYS ?

**Comment by chkr1011** [comment]
Hi,
this has no prio at the moment and can be also implemented by the user. But I am considering to implement an extension which can be used.
Best regards
Christian

**Comment by biapar** [comment]
@AngeloBestetti you can use a "private" topic to send sys messages.

**Comment by chkr1011** [comment]
I will consider adding a new extension lib for this project but I have no roadmap for this yet.
