### ISSUE TITLE
How to know the IP address from which a client is connecting to the broker

### ISSUE THREAD

**Issue by VLorz** [chkr1011/MQTTnet#229]
Hi, 
Is there any means to know the IP address from which a client is connecting to the broker?
B.R., Victor

**Comment by chkr1011** [comment]
Hi,
at the moment not but I believe this can be added quickly.
Best regards
Christian

**Comment by chkr1011** [comment]
This is added in version 2.8.0 which will be released soon.

**Comment by djarvis** [comment]
How is this done?  When I GetClientSessionsStatusAsync() and look at the endpoints, they are null.  Using version 2.8.2.

**Comment by K1LL3R234** [comment]
How do I get the IP of the client?

**Comment by VLorz** [comment]
Hi K1LL3R234,
> 
> 
> How do I get the IP of the client?

In the handler for `ClientConnectedHandler`, from `IMqttServer`, I use something like this:

```csharp
IList<IMqttClientStatus> Csl = await MyMqttServer.GetClientStatusAsync();
IMqttClientStatus Cs = Csl.First<IMqttClientStatus>( c => c.ClientId == e.ClientId );
```
Definitively not sure if it is the best way of doing this, but `Cs.Endpoint` contains a string representation for the endpoint from where the client has connected, `<ipaddress>:<port>`, that is good enough for my logging purposes.
I'm using NuGet package version 3.0.13.0
BR

**Comment by K1LL3R234** [comment]
> Hi K1LL3R234,
> 
> > How do I get the IP of the client?
> 
> In the handler for `ClientConnectedHandler`, from `IMqttServer`, I use something like this:
> 
> ```cs
> IList<IMqttClientStatus> Csl = await MyMqttServer.GetClientStatusAsync();
> IMqttClientStatus Cs = Csl.First<IMqttClientStatus>( c => c.ClientId == e.ClientId );
> ```
> 
> Definitively not sure if it is the best way of doing this, but `Cs.Endpoint` contains a string representation for the endpoint from where the client has connected, `<ipaddress>:<port>`, that is good enough for my logging purposes.
> I'm using NuGet package version 3.0.13.0
> BR

Hi VLorz

I am using ASP.NET Core 2.0 and can't get that working.

Any idee?

**Comment by VLorz** [comment]
I'm using it in a basic windows desktop application.
`GetClientStatusAsync()` returns an empty list when called within the connection validator. But in `a.EndPoint` you should have the end point's information in plain text. Have you tried that?

**Comment by K1LL3R234** [comment]
> I'm using it in a basic windows desktop application.
> `GetClientStatusAsync()` returns an empty list when called within the connection validator. But in `a.EndPoint` you should have the end point's information in plain text. Have you tried that?

Hi VLorz

I get something like this 

  | Name | Value | Type
-- | -- | -- | --
  | Endpoint | "0HM4TQKQRK8B4" | string

**Comment by VLorz** [comment]
In my desktop application it gives me the IPAddress+Port, but I see now it is a slightly different scenario from yours as the EndPoint is related to the adapter. I don't know the inner details of the adapter used when using MQTTNet with Kestrel. Maybe @chkr1011 can bring some light on this? I haven't fully studied the source code for this part.

**Comment by chkr1011** [comment]
@JanEggers I assume this is a question for you!?

**Comment by JanEggers** [comment]
heres the code that figures out the endpoint:

https://github.com/chkr1011/MQTTnet/blob/86256d1b10cf10e21e4c40682ea33867a184751b/Source/MQTTnet.AspnetCore/MqttConnectionContext.cs#L40-L58

I assume you are in line 55 because you are using ASP.NET Core 2.0 that does not expose the remote endpoint of the connection. if you have a suggestion on how to dig better information from aspnet let me know or create a pr

**Comment by K1LL3R234** [comment]
> heres the code that figures out the endpoint:
> 
> https://github.com/chkr1011/MQTTnet/blob/86256d1b10cf10e21e4c40682ea33867a184751b/Source/MQTTnet.AspnetCore/MqttConnectionContext.cs#L40-L58
> 
> I assume you are in line 55 because you are using ASP.NET Core 2.0 that does not expose the remote endpoint of the connection. if you have a suggestion on how to dig better information from aspnet let me know or create a pr

Hi @JanEggers

Can you please help to dig for better information?

Thanks
