### ISSUE TITLE
Received not supported QoS level.

### ISSUE THREAD

**Issue by Schwenkner** [chkr1011/MQTTnet#23]
When I specify "MqttQualityOfServiceLevel.AtMostOnce)" then the exception is thrown in MqttClientSession. A look in the code shows, in case of AtMostOnce the method doesn't has a return statement and falls through to the exception.

What action has to be executed instead?
Or is this QoS not supported?

**Comment by chkr1011** [comment]
Hi,
this is a bug and fixed in version 2.1.5.1...
Best regards
Christian
