### ISSUE TITLE
deadlock when a new client tries to connect to the broke with an existing clientId and a will message

### ISSUE THREAD

**Issue by william-wps** [chkr1011/MQTTnet#231]
When the MqttClientSessionManager tries to create a session, it calls GetOrCreateClientSessionAsync, if there's already a session with the same clientId and cleanSession equals true, the existing session will be closed. However if the session has a will message, it will be be dispatched via the ApplicationMessageReceivedCallback delegate, which calls DispatchApplicationMessageAsync.
Since both GetOrCreateClientSessionAsync and DispatchApplicationMessageAsync wait on the same SemaphoreSlim, this cause a deadlock.

**Comment by chkr1011** [comment]
Hi,
thanks for reporting this issue and providing the solution 😄 
Please try again with the RC version _2.7.5-rc1_ from nuget. 
Best regards
Christian

**Comment by william-wps** [comment]
Hi,
The problem is still there in 2.7.5,
A quick fix could be change the line# 286 in MqttClientSessionManager to
await clientSession.StopAsync(true).ConfigureAwait(false);
This will stop the will message being published. I think it's acceptable since we are creating a session with the same clientId anyway.
What do you think about it?

**Comment by chkr1011** [comment]
I am wondering why it still occurs. I was able to reproduce it and after the fix from 2.7.5 it was gone.

**Comment by chkr1011** [comment]
This will be fixed in 2.8.0 which will be released soon.
