### ISSUE TITLE
2.1.5.1 Update broke MqttClient/MqttServer constructor?

### ISSUE THREAD

**Issue by Spawnkid** [chkr1011/MQTTnet#24]
I just got an update earlier and now its failing my build. Here are the errors:

Cannot implicitly convert type 'MQTTnet.Core.Client.IMqttClient' to 'MQTTnet.Core.Client.MqttClient'. An explicit conversion exists (are you missing a cast?)

Cannot implicitly convert type 'MQTTnet.Core.Server.IMqttServer' to 'MQTTnet.Core.Server.MqttServer'. An explicit conversion exists (are you missing a cast?)

Probably an updated doc will help?

**Comment by Spawnkid** [comment]
Update: fixed by just properly casting.

 _mqttClient = (MqttClient)new MqttClientFactory().CreateMqttClient(options);
 _broker = (MqttServer)new MqttServerFactory().CreateMqttServer(options);

**Comment by chkr1011** [comment]
Hi,
the factories are returning the interfaces only since version 2.1.5 (IMqttClient, IMqttServer). Please use them instead of casting the classes. Or use _var_ like in the examples.
Best regards
Christian
