### ISSUE TITLE
Need help in setting up the MQTT server

### ISSUE THREAD

**Issue by SunilKrishna1234** [chkr1011/MQTTnet#240]
Hi, 

I'm very new to MQTT concept. I wanted to implement this protocol in my xamarin projects where I need to configure the server on my local machine. I'm not able to find a complete example of setting up the server. Can you please help me by providing any tutorial on setting up the server so that I can communicate through my xamarin mobile application in which the Android and iOS devices acts as clients. 

Thanks,
Sunil

**Comment by chkr1011** [comment]
Hi,
the Wiki contains an example for a simple MQTT broker without special settings.
Best regards
Christian
