### ISSUE TITLE
CodeReview: is there a reason that you didn't use long running tasks for tasks containing a while?

### ISSUE THREAD

**Issue by ahmadalli** [chkr1011/MQTTnet#242]
`Task.Run` is generally for tasks that will have result in future. By using
```csharp
 Task.Factory.StartNew((),
                _cancellationTokenSource.Token,
                TaskCreationOptions.LongRunning,
                TaskScheduler.Current);
```
you can have tasks with their own threads running as long as required.

Take a look at this commit:
https://github.com/ahmadalli/MQTTnet/commit/ac5e2aeb334e66661b68b21fd6a82ee247215a62

**Comment by chkr1011** [comment]
Hi,
in general this is correct BUT for historical reasons this is not correct in this case.

The _LongRunning_ parameter indeed forces the creation of a new thread but since async/await was introduced it makes no sense to use it because the _await_ will _release_ the thread and the code will continue on a thread pool thread in the future. So using _LogRunning_ will only decrease performance because a new and clean thread will be created and used only until the first _await_ is reached.

But I still appreciate the code review 👍 

Best regards
Christian

**Comment by ahmadalli** [comment]
actually, `await/async` by itself doesn't create a new thread (see [here](https://stackoverflow.com/a/37419845/1003464)). e.g. by awaiting I/O operations (if supported by the framework. e.g. HttpClient) you won't create a new thread.

>`Task` is more than just an abstraction of "where to run some code" though - it's really just "the promise of a result in the future". 
[John Skeet](https://stackoverflow.com/a/13429164/1003464)

on the other hand, `Task.Run()` (which has nothing to do with `Task` and `Task<>` types which are awaitable) is a TPL method. and actually, it's just a shortcut for `Task.Factory.StartNew` without additional parameters.

when you call `Task.Run`, you're telling TPL to get a thread from limited amount of threads available in ThreadPool, run your task inside it and return the thread to ThreadPool after the task was done.

so if you have a task that is not expected to finish in foreseeable future, like the tasks having `while(true)`, I think using `TaskCreationOptions.LongRunning` is preferable since the task is not expected to return a result any time soon (in this case, the result doesn't matter. we need something to be done as long as the client is not disconnected)

also, the difference between awaiting a Task and not awaiting it is not that if you don't use `await`, the task will run in the current thread. awaiting it means that you want to wait (without blocking current thread) for the task to finish before you continue executing the next line of code. (I'm not sure what will happen under the hood without a `SynchronizationContext`)
