### ISSUE TITLE
Server performance under heavy load

### ISSUE THREAD

**Issue by ahmadalli** [chkr1011/MQTTnet#243]
I'm having a problem with the server in high load situation. I'm testing server to see if it's production ready for a chat server. In my test, I have a lot of clients (in my high load test I'm simulating 2000) subscribing to few topics (up to 5 topics) sending a lot of messages (10 message per second per each client) [this is my test project](https://github.com/ahmadalli/MQTTServerStressTest) and I'm facing these issues:

1. I run my script, I can't connect any other clients to the server (watcher.js in my tests)
1. After a while, clients start getting disconnected and they try to reconnect but it seems to fail.

I've tried some modifications on your code (like using `Task.Factory.StartNew` explained in #242) but no luck so far

**Comment by JanEggers** [comment]
with this number of connections i assuume its a port exthaustion issue. the tcp ports stay open for some time after they are closed. 

can you provide any logs from the server that indicate why the clients disconnect in the first place?

**Comment by ahmadalli** [comment]
is trace log good enough? I tried to find out the reason from there but it produced a lot of logs and I couldn't find out the issue from them

**Comment by ahmadalli** [comment]
@JanEgger how much time should a client wait before reconnecting?

**Comment by chkr1011** [comment]
Version 3.0.0 has new connection handling and message processing. Please try with that version or latest dev branch and reopen this ticket if it still fails. Also some sample to to reproduce this would be fine.
