### ISSUE TITLE
Start/Stop Mqtt Server Websocket

### ISSUE THREAD

**Issue by DrSensor** [chkr1011/MQTTnet#244]
Hello,
I have some use case to start Mqtt Server via REST API like `curl -X POST -d "{timeout: 5s}" htpp://localhost:5000/api/broker/start` (I'm using ASP.NET Core). Is there any way to register MqttServer instance instead of options? In the wiki I only found

```
services.AddHostedMqttServer(mqttServerOptions)
```

Regards,
Wildan

**Comment by JanEggers** [comment]
there isnt a predefined method but you can add your own methods that adds all services except

https://github.com/chkr1011/MQTTnet/blob/5e79581662f0e7f409974920a5949fb87202860f/Frameworks/MQTTnet.AspnetCore/ServiceCollectionExtensions.cs#L24

then you can request IMqttServer in your controller and start it manually.

**Comment by DrSensor** [comment]
I see. Can I also start mqtt-websocket manually to?

**Comment by JanEggers** [comment]
you can build your own middleware, the build in version can be found here:

https://github.com/chkr1011/MQTTnet/blob/9f4f37bb51c1e41e527ed84c0a9e9439cdacfb4a/Frameworks/MQTTnet.AspnetCore/ApplicationBuilderExtensions.cs#L11-L41

I think it is best you copy that over to your project and reject the request if you dont want it to be handled. I dont think you can "start" a websocket route in aspnet so i guess it has to be registered during startup and then enabled / disabled based on your preferences.
