### ISSUE TITLE
MQTT Version 5.0 Implementation?

### ISSUE THREAD

**Issue by prime167** [chkr1011/MQTTnet#246]
Hi, is there any plan to implement [MQTT 5.0](http://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html) ?

**Comment by skynetv** [comment]
Fair enough, thanks

**Comment by AtosNicoS** [comment]
There are several Mqtt brokers available for testing now:
https://github.com/eclipse/paho.mqtt.testing
https://flespi.com/mqtt-broker#mqtt-checklist
https://vernemq.com/mqttv5.html

**Comment by markusschaber** [comment]
@chkr1011 Maybe re-open this issue, to keep track of the progress of V5 support?

**Comment by chkr1011** [comment]
v3.0.0 will have MQTTv5 support. For individual issues with that I prefer separate issues.
