### ISSUE TITLE
Reconnect does not work

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#25]
Hi again,

I have a problem with the reconnect. I'm sending data and sometimes the connection does not work anymore. My client code trys to reconnect:
> 
> client.Disconnected += async (s, e) =>
>              {
                 Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                 sendMessages = false;
                 while (!sendMessages)
               {
                     await Task.Delay(TimeSpan.FromSeconds(5));
                    Console.WriteLine("### Try to connect ###");
                    try
                    {
                        await client.ConnectAsync();
                        sendMessages = true;
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("### RECONNECTING FAILED ### " + ex);
                    }
                }
            };

The reconnection never works though. This is what I get:
>\#\#\# Try to connect ###
>\#\#\# RECONNECTING FAILED ### MQTTnet.Core.Exceptions.MqttProtocolViolationException: It is not allowed to connect with a server after the connection is established.
   at MQTTnet.Core.Client.MqttClient.<ConnectAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MqttClientModule.MqttClientModule.<>c__DisplayClass12_0.<<threadBodyAsync>b__2>d.MoveNext()
\#\#\# Try to connect ###
\#\#\# RECONNECTING FAILED ### MQTTnet.Core.Exceptions.MqttProtocolViolationException: It is not allowed to connect with a server after the connection is established.
   at MQTTnet.Core.Client.MqttClient.<ConnectAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MqttClientModule.MqttClientModule.<>c__DisplayClass12_0.<<threadBodyAsync>b__2>d.MoveNext()
...

In this case it does not work to restart the client or the broker. I have to kill both and restart them or a reconnection is impossible.
How do I make shure that my reconnect works properly? 
And how can I destroy the client object? There is no dispose.
Thanks =)

Best regards,
Zuendelmeister

**Comment by wuzhenda** [comment]
it seems the resource is not  released totally

**Comment by Zuendelmeister** [comment]
That means? And what can I do to avoid this?

**Comment by wuzhenda** [comment]
add more time span before re-connection after last time disconnection, but  not a good solution

**Comment by Zuendelmeister** [comment]
Ok I'll try it. Thanks for the hint.

**Comment by chkr1011** [comment]
Yes this is only a workaround. I will check this...

**Comment by wuzhenda** [comment]
you use a disposed socket when do re-connect
refs,
https://github.com/chkr1011/MQTTnet/issues/27#issuecomment-322094071

**Comment by chkr1011** [comment]
@Zuendelmeister: I tested it but I cannot reproduce the error. 

I assume the problem is in your code. Because in the event handler of the _Disconnected_ event you start a while loop. The problem is that after the connection is droppped the event handler is called again and again if a _ConnectAsync_ for retries fails. Then you have several while loops running and this leads to unexpected errors like this one.

Best regard
Christian

**Comment by Zuendelmeister** [comment]
Ok that makes sense. But what would be the right way to do a save reconnect with several retries?

**Comment by wuzhenda** [comment]
when do disconnection,the ReceivePacketAsync  task seems not disabled,and it continue to use the disposed socket read?

**Comment by chkr1011** [comment]
Yes you are right. These problems are related BUT starting this loop isn't a good idea. You can monitor the _IsConnected_ property within a loop or only try a reconnect in the event but a loop is defenetely causing problems because it will be executed several times for each failed try to reconnect and you will end up having several loops running at the same time.

**Comment by Zuendelmeister** [comment]
Hi @chkr1011,

yes I understood and deleted the loop and tried it with your example code. 
Same problem though. Does it work for you? My testcases are the following:
1.: A client trys to connect to a broker that is not started yet. After several retries I start the broker and the client SHOULD get a connection.
2.: A client connects to a started broker, I kill the broker, the client looses the connection, trys to reconnect a few times and I start the broker again. Client SHOULD get a connection again.
As I said I used your example code and deleted the loop. What am I doing wrong?

Thanks again.

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
Please wait until the reconnect bug is fixed. Then we can continue here. In general it should work like in the example code. But this is currently broken. I will publish a fixed version soon.

**Comment by wuzhenda** [comment]
maybe try this commit?
https://github.com/wuzhenda/MQTTnet/commit/16f9faed4022392972c3cec5dd309d1f87772df8

**Comment by wuzhenda** [comment]
when timeout happened ,the original task seems still running,not abort?
`        public async Task ConnectAsync(MqttClientOptions options, TimeSpan timeout)
        {
            var task = _channel.ConnectAsync(options);
            if (await Task.WhenAny(Task.Delay(timeout), task) != task)
            {
                throw new MqttCommunicationTimedOutException();
            }
        }`

**Comment by wuzhenda** [comment]
tks!  I hope the evenhandle  Disconnected could tell user the reason for disconnected
`Disconnected?.Invoke(this, EventArgs.Empty); ==> Disconnected?.Invoke(this, EventArgs.Dis-Reason);`

**Comment by Zuendelmeister** [comment]
He you guys,

I just tested the new code. Works perfect for me.
Thanks for implementing!

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
@wuzhenda  If you need this feature please create a new ticket for it. But the question is which information you need. If you call disconnect on your own you should know the reason. If the library disconnects it depends on a dropped connection. Either TCP, MQTT or physically.
