### ISSUE TITLE
Refactoring Transport once more (aspnetcore 2.1)

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#250]
Hi @chkr1011  im planning to adapt the Connection abstraction of aspnetcore 2.1 for mqttnet. these abstractions provide a unified way to handle tcp, tls and websockets.

common:
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Connections.Abstractions/ConnectionContext.cs

tcp:
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Transport.Sockets/Internal/SocketConnection.cs

websocket:
https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Http.Connections/Internal/Transports/WebSocketsTransport.cs

I see two ways of integration. What would you prefere?

Option 1: Implement IMqttServerAdapter, IMqttChannelAdapter for tcp in MQTTnet.AspnetCore (that depends on aspnetcore already just need to increment version to 2.1 once released)

Option 2: remove IMqttChannel, IMqttChannelAdapter, ... and let MQTT.Net depend on Kestrel 

what I expect from the change:

1. perf boost
2. less errors

**Comment by markusschaber** [comment]
A hard dependency on Kestrel might be too much for some use cases (not all of them use Kestrel).

But as long as we can still plug in our own adapters, I won't mind too much... :-)

**Comment by israellot** [comment]
Depending on kestrel for a client-only use case would seem odd. I know @chkr1011 doesn't want to split the library on client / server though.

**Comment by JanEggers** [comment]
lets see what the aspnet comes up with. 

client side story should be supported in 2.2.

also I could instead just depend on https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Connections.Abstractions and copy the code for the implementations so there is no dependency on kestrel. but I dont really like that approach as it negates the advantage of having the code maintened by the aspnet team

**Comment by israellot** [comment]
We could fork and submodule kestrel code

**Comment by JanEggers** [comment]
@chkr1011 can you give me some feedback pls 2.1 is final and I would like to start experimenting over the weekend

**Comment by chkr1011** [comment]
@JanEggers To me option 1 is the best because one of the principles of this library is to be independent from 3rd party libs. I know that we already have dependencies to WebSocket libs but at least they belong to .net. I am also not sure if kestrel is supported for UWP!? Is there a way to support 2.0 as well? I don't know if everyone will directly migrate to 2.1. Probably support for 2.0 is still required.

**Comment by JanEggers** [comment]
Kestrel is netstandard so it should run on uwp but i never tested that myself. the lowest dependency to take is system.io.pipelines that runs on netstandard 1.3 and above. also if we depend on system.io.pipelines we are not tight to kestrel but need to implement the pipeline our own. 

I will first provide some benchmarks to measure the difference between a pipeline and the current channel design.

**Comment by JanEggers** [comment]
my first results look good! for both cases it is 10000 chunks with 5 bytes each, just transport no serializer or adapter stuff just transport

|            Method |     Mean |    Error |   StdDev |     Gen 0 | Allocated |
|------------------ |---------:|---------:|---------:|----------:|----------:|
| existing | 331.6 ms | 6.786 ms | 13.24 ms | 3000.0000 |  12.07 MB |
| pipe | 3.064 ms | 0.0328 ms | 0.0307 ms | 85.9375 | 356.15 KB |

100x faster and 3% of memory usage

**Comment by JanEggers** [comment]
as the pr is merged ill close this

**Comment by JanEggers** [comment]
@chkr1011 thx again for merging this, and your optimization efforts. I am really happy with the results!

I ran the MessageProcessingMqttConnectionContextBenchmark and with that new transport and the other optimizations I can transfer 10000 the messages in 15ms instead of 450ms meaning we are at 600K msg/sec thats amazing!

**Comment by chkr1011** [comment]
Wow 600K is very fast. Hopefully still with some required fixed for the ThreadStatic topic etc.
