### ISSUE TITLE
Task deadlock?

### ISSUE THREAD

**Issue by hezlog** [chkr1011/MQTTnet#251]
![image](https://user-images.githubusercontent.com/13940360/39617336-e9e0e992-4fb1-11e8-9adb-62be257da292.png)

Two client access servers using the same ID are not automatically disconnected.

**Comment by chkr1011** [comment]
Hi, thank you for reporting this. I am already working on a fix.
Best regards
Christian

**Comment by hezlog** [comment]
okay, thank you

**Comment by chkr1011** [comment]
Please try again with 2.8.0-alpha1. It should be fixed now.
