### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by evacomaroski** [chkr1011/MQTTnet#252]
Hello and thanks for all the great work! I am trying to get to grips with creating an encrypted MQTTnet server and there is barely anything in the GitHub wiki documentation on the proper way to do so. Nevertheless, I've scraped the issues section and managed to cobble together the following:

```csharp
_MQTTCertificate =
    new X509Certificate2(path, password, X509KeyStorageFlags.Exportable);

var optionsBuilder = new MqttServerOptionsBuilder()
    .WithEncryptedEndpoint()
    .WithEncryptionCertificate(_MQTTCertificate.Export(X509ContentType.Pfx))
    .WithSubscriptionInterceptor(SubscriptionInterceptor);

    await _MQTTServer.StartAsync(optionsBuilder.Build());
```

which allows the MQTT server to start - so far, so well.

If a connection is then made using `mosquitto_sub` client without specifying any certificate, CA nor key:

```bash
mosquitto_sub -h MQTTNet.tld -p 8883 -t 'sometopic' -v
```

then MQTTnet will gladly accept the unencrypted connection and not even warn that the connection is not encrypted.

This is quite the security hazard given that all data flowing between the subscriber and the broker is very much plaintext and, in some cases, may contain sensitive information that can be sniffed right off the network - both the subscription topic and payload data are exposed.

Am I using MQTTnet correctly? If so, then why is MQTTnet accepting an unencrypted connection when it has been explicitly told not to do so? Is there some way to prevent this behaviour?

I can work around the issue by creating an SSL encrypted stream on top of all communication but shouldn't encryption work with MQTTnet without having to resort to SslStream?

Furthermore, connecting with `mosquitto_sub` and specifying a CA, client certificate and a certificate key simply leads to `mosquitto_sub` bailing out with:

```
Error: A TLS error occurred.
```

I understand that the latter is a `mosquitto_sub` issue but I am unsure how to debug given that the connection is handled by MQTTnet internally. MQTTnet does not throw any elucidating errors when `mosquitto_sub` fails to connect.

Finally, I do not see a way to set the desired protocol version with MQTTnet - does it default to Tls1.2? `mosquitto_sub` is capable of Tls1, Tls1.1 and Tls1.2 - which one is then implied by MQTTnet if there is no way of selecting?

Thanks!

**Comment by evacomaroski** [comment]
To answer part of the questions:

1.) The following code will disable the "DefaultEndPoint" and enable the "TlsEndPoint" thereby forcing encryption - I am not sure this can be done with the options builder instead:
```csharp
            var options = new MqttServerOptions
            {
                SubscriptionInterceptor = SubscriptionInterceptor,
                DefaultEndpointOptions =
                {
                    IsEnabled = false
                },
                TlsEndpointOptions =
                {
                    BoundIPAddress = address,
                    Certificate = _MQTTCertificate.Export(X509ContentType.Pfx),
                    Port = _configuration.Servers.MQTTServer.Port,
                    IsEnabled = true
                }
            };
```

2.) MQTTnet only works with Tls1.2

**Comment by evacomaroski** [comment]
I'll just post the rest here in case other people have the same issue with TLS and MQTTnet - perhaps someone will add the details to the wiki for others. . .

Generate the MQTTnet server certificates using OwnTracks:

```bash
wget https://github.com/owntracks/tools/blob/master/TLS/generate-CA.sh
```

You may need to comment out `subjectAltName` on certain OpenSSL versions:

```diff
--- generate-CA.sh~	2018-05-05 17:44:59.000000000 +0300
+++ generate-CA.sh	2018-05-05 17:46:17.000000000 +0300
@@ -181,7 +181,7 @@
 		%%% nsComment               = "Broker Certificate"
 		%%% subjectKeyIdentifier    = hash
 		%%% authorityKeyIdentifier  = keyid,issuer:always
-		%%% subjectAltName          = $ENV::SUBJALTNAME
+		%%% # subjectAltName          = $ENV::SUBJALTNAME
 		%%% # issuerAltName           = issuer:copy
 		%%% ## nsCaRevocationUrl       = http://mqttitude.org/carev/
 		%%% ## nsRevocationUrl         = http://mqttitude.org/carev/
```

Run:
```bash
chmod +x generate-CA.sh
generate-CA.sh HOSTNAME
```
where `HOSTNAME ` **MUST** be the hostname of the server where the application using MQTTnet runs on.

This will generate `ca.crt`, `ca.key`, `HOSTNAME.crt` and `HOSTNAME.key`. Now convert the certificates to PFX with OpenSSL:
```bash
openssl pkcs12 -export -out server.pfx -inkey HOSTNAME.key -in HOSTNAME.crt
```
It will prompt for a password, so be creative - let's say it's `somepassword`.

Now transfer `server.pfx` to the application using MQTTnet and initialise the MQTTnet server as follows:
```csharp
_MQTTCertificate = new X509Certificate2(
    "server.pfx", 
    "somepassword", 
    X509KeyStorageFlags.Exportable
);

var options = new MqttServerOptions
{
    SubscriptionInterceptor = SubscriptionInterceptor,
    DefaultEndpointOptions =
    {
        IsEnabled = false
    },
    TlsEndpointOptions =
    {
        BoundIPAddress = address,
        Certificate = _MQTTCertificate.Export(X509ContentType.Pfx),
        Port = port,
        IsEnabled = true
    }
};
```

This will force MQTTnet to refuse insecure connections.

Now, for the client, generate client certificates:
```bash
openssl genrsa -out client.key 2048
openssl req -new -out client.csr \
    -key client.key -subj "/CN=HOSTNAME"
openssl x509 -req -in client.csr -CA ca.crt \
    -CAkey ca.key -CAserial ./ca.srl -out client.crt \
    -days 3650 -addtrust clientAuth
```

where, again, `HOSTNAME` **MUST**  be the hostname of the machine where your MQTT client resides.

Finally, you can test with `mosquitto_sub`:
```bash
mosquitto_sub -h HOSTNAME -p PORT -t 'sometopic' -v --cafile ca.crt
```
where `HOSTNAME` is the hostname of the application running MQTTnet, `PORT` is the port you chose to initialise MQTTnet and `ca.crt` was generated in the first steps.

**Comment by SeppPenner** [comment]
Isn't this documented here: https://github.com/chkr1011/MQTTnet/wiki/Server#using-a-certificate?

**Comment by SeppPenner** [comment]
By the way, which version and which environment (Standalone server or Asp.NetCore server?) are you using?

**Comment by SeppPenner** [comment]
I'm closing this now. Feel free to open this if you still see any problems.
