### ISSUE TITLE
.NET Microframework support ???

### ISSUE THREAD

**Issue by valoni** [chkr1011/MQTTnet#253]
is there version of .NET Micro Framework 4.3 or 4.4 support 
or 
we need still to continue with old client  from   https://github.com/eclipse/paho.mqtt.m2mqtt

**Comment by chkr1011** [comment]
Hi,
sorry but this is not planned. 

Best regards
Christian

**Comment by biapar** [comment]
Why Micro Framework? You can use .net core example and .net core runtime is small.

**Comment by valoni** [comment]
@biapar 

because I'm using development boards and not pc 
(such are Nucleo STM32F411 or Fez Spider 2 http://old.ghielectronics.com/catalog/product/432 )

and for a moment is compiled only https://github.com/eclipse/paho.mqtt.m2mqtt 

but  i will like this ones to be able to compile client (at least too in ,NET Micro Framework)
