### ISSUE TITLE
How to configure WSS and WS at the same?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#258]
How to configure WSS server side? Is still possible to have on WS and WSS?

```
var mqttServerOptions = new MqttServerOptionsBuilder()
                .WithConnectionBacklog(100)
                .WithDefaultEndpointPort(1883)
                .WithEncryptedEndpointPort(2883)
                .WithStorage(new RetainedMessageHandler())
                .WithSubscriptionInterceptor(
```
Thx

**Comment by SeppPenner** [comment]
Which version are you referring to?

**Comment by biapar** [comment]
2.8.5

**Comment by chkr1011** [comment]
WS and WSS require ASP.NET and kestrel. There is no direct support in MQTTnet. Please x check the source code of MQTTNET.Server in order to see how to integrate ASP.NET web sockets in MQTTnet
