### ISSUE TITLE
MQTT Client Network disconnect can't receive Disconnected event

### ISSUE THREAD

**Issue by hezlog** [chkr1011/MQTTnet#259]
**MQTTnet:**  
2.8.0-alpha1

.net 4.5.2

Step：
1. Run the broker on computer A 
2. Run the client on computer B and connect the broker 
3. Disconnect the Internet network of client computer B 

Expect: Receive the Disconnected event.
Actual: Nothing happens.

引发的异常:“MQTTnet.Exceptions.MqttCommunicationException”(位于 MQTTnet.dll 中)
引发的异常:“MQTTnet.Exceptions.MqttCommunicationException”(位于 mscorlib.dll 中)
引发的异常:“MQTTnet.Exceptions.MqttCommunicationException”(位于 mscorlib.dll 中)
 [2018-05-18T04:32:42.2825262Z] [23] [MqttClient] [Warning]: MQTT communication exception while receiving packets.
MQTTnet.Exceptions.MqttCommunicationException: 无法从传输连接中读取数据: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试?О堋！?---> System.IO.IOException: 无法从传输连接中读取数据: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。。 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   在 System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 MQTTnet.Serializer.MqttPacketReader.<ReadHeaderAsync>d__0.MoveNext() 位置 \Serializer\MqttPacketReader.cs:行号 26
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__16.MoveNext() 位置 \Adapter\MqttChannelAdapter.cs:行号 132
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ??System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 MQTTnet.Adapter.MqttChannelAdapter.<>c__DisplayClass15_0.<<ReceivePacketAsync>b__0>d.MoveNext() 位置 \Adapter\MqttChannelAdapter.cs:行号 105
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   在 MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__17.MoveNext() 位置 \Adapter\MqttChannelAdapter.cs:行号 176
   --- 内部异常堆栈跟踪的结尾 ---
   在 MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__17.MoveNext() 位置 \Adapter\MqttChannelAdapter.cs:行号 213
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   在 MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__15.MoveNext() 位置 \Adapter\MqttChannelAdapter.cs:行号 94
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 MQTTnet.Client.MqttClient.<ReceivePacketsAsync>d__39.MoveNext() 位置 \Client\MqttClient.cs:行号 390

![image](https://user-images.githubusercontent.com/13940360/40216337-a28764da-5a98-11e8-9bba-4a459a2e91fb.png)

**Comment by JanEggers** [comment]
should be solved see #342

**Comment by dealproc** [comment]
@JanEggers Can you tell me what update has this patch in?  I am running into this exact issue and I want to see if v2.8.4 has a fix for it or not.  In my case, the server does not seem to be firing the `Disconnected` event when the cord is unplugged from the device, and I'd like to know this, whether it is a webSocket connection [in my case], or a tcp socket connection.

**Comment by JanEggers** [comment]
#343 was merged before 2.8.3
