### ISSUE TITLE
Max Message Size

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#26]
Hi again,

is there a maximum message size? If I send a message with 500 character everything works fine. The broker dies if I send a message with 1000 character though.
Any ideas?
Thanks as always =)

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
Hi,
I tested it with a message which has a payload of 6500 bytes and it works without problems. Can you please sent me exceptions or the trace messages (from MqttTrace)?

Best regards
Christian

**Comment by Zuendelmeister** [comment]
I somehow cannot reproduce the problem. I guess it was due to connection problems maybe? Close this for now please. If I can reproduce this, I will let you know.
