### ISSUE TITLE
AspNet Core: Is't possible to run up WS and TCP broker server?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#261]
AspNet Core: Is't possible to run up WS and TCP broker server?
This because some clients don't support MQTT on WS.

**Comment by chkr1011** [comment]
Hi, yes you can use both endpoints. The example in the repo using AspNetCore 2 uses TCP adapter and WS adapter. With the current version there is no change required. Both are opened by default.

**Comment by biapar** [comment]
Strange. I’ve build a customized broker run on Asp.net core 2 build starting from your example and I’m not able to connect from a “normal” MQTT client.
