### ISSUE TITLE
Which is the correct worflow to close a connection on websocket?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#262]
Which is the correct worflow to close a connection on websocket?
Example: if an user close a web page.

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/2e3e58ed73d6bd5602d4a57e2a6b09f1d28efc72/Tests/MQTTnet.TestApp.AspNetCore2/wwwroot/app/app.ts#L8-L10
