### ISSUE TITLE
Asp.NET core 2: How to setup TCP port for websocket and socket MQTT server?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#263]
Asp.NET core 2: How to setup TCP port for websocket and socket MQTT server?
Is this only for TCP socket ( no websocket )?
Thx.

```
                .WithDefaultEndpointPort(1883)
                .WithEncryptedEndpointPort(2883)
```

**Comment by JanEggers** [comment]
have a look at the wiki:

https://github.com/chkr1011/MQTTnet/wiki/Server#websocket-endpoint
