### ISSUE TITLE
Is't supported WSS?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#264]
Is't supported WSS?

**Comment by chkr1011** [comment]
Hi,
do you mean client or server?

**Comment by biapar** [comment]
Server.
I build a simple MQTT javascript client but it’s on a ssl website. So the client required that the server has on WSS

**Comment by chkr1011** [comment]
I assume this is related to the ASP.NET integration only.
@JanEggers  could you please shed some light? I saw the implemention for Websockets but have no idea about WSS etc.

**Comment by JanEggers** [comment]
I guess it just works, never tried it. you need to setup tls for aspnetcore and you are good to go. if it does not work feel free to open the issue again.
