### ISSUE TITLE
Proxy for connections

### ISSUE THREAD

**Issue by archerian** [chkr1011/MQTTnet#265]
Hello,

Is it possible to specify a proxy to connect to the MQTT server? In our work environment all access is via a proxy with username/password credentials. I am trying to connect via the proxy.

Thanks,
Arun

**Comment by biapar** [comment]
I’m able to connect from behind a proxy plus firewall to our demo server build on our external Mqtt asp.net core 2 server.
Have you open the ports on proxy?

**Comment by archerian** [comment]
thanks for the answer, how do you connect via your proxy? I was looking for something like how mosquitto_sub uses --proxy option, or like how HttpWebRequest uses IWebProxy

**Comment by biapar** [comment]
@archerian Is't your client a web client?
