### ISSUE TITLE
when not use ssl ,disconnected will cause exception

### ISSUE THREAD

**Issue by wuzhenda** [chkr1011/MQTTnet#27]
in file MqttTcpChannel.cs

public Task DisconnectAsync()
        {
            try
            {                
                  **//not judge if _sslStream is null
                    _sslStream.Dispose();**

                _socket.Dispose();
                return Task.FromResult(0);
            }
            catch (SocketException exception)
            {
                throw new MqttCommunicationException(exception);
            }
        }

**Comment by wuzhenda** [comment]
when disconnected happened,the socket is disposed,
but when reconnect, you do not create a new socket,

your tesk code:
`                client.Disconnected += async (s, e) =>
                {
                    Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                    await Task.Delay(TimeSpan.FromSeconds(5));

                    try
                    {
                        await client.ConnectAsync();
                    }
                    catch
                    {
                        Console.WriteLine("### RECONNECTING FAILED ###");
                    }
                };`

your connectAsync code in MqttTcpChannel.cs
`        public async Task ConnectAsync(MqttClientOptions options)
        {
            if (options == null) throw new ArgumentNullException(nameof(options));
            try
            {
                await Task.Factory.FromAsync(_socket.BeginConnect, _socket.EndConnect, options.Server, options.GetPort(), null);

                if (options.TlsOptions.UseTls)
                {
                    _sslStream = new SslStream(new NetworkStream(_socket, true));
                    await _sslStream.AuthenticateAsClientAsync(options.Server, LoadCertificates(options), SslProtocols.Tls12, options.TlsOptions.CheckCertificateRevocation);
                }
            }
            catch (SocketException exception)
            {
                throw new MqttCommunicationException(exception);
            }
        }`

**Comment by chkr1011** [comment]
Please test with version 2.2.0...

**Comment by chkr1011** [comment]
If this still occurs with 2.2.0 please reopen the ticket.
Best regards
Christian
