### ISSUE TITLE
Two apps subscribed for the same topic is unable to receive messages when the topic has messages to deliver

### ISSUE THREAD

**Issue by arlingan** [chkr1011/MQTTnet#271]
I have an application that subscribes for messages on a topic with wildcard(say topic/state/+). I open two instances of this application, so I have two subscribers subscribing for messages on the same topic for scalability purposes. I have another application publishing the messages to the same topic. I don't see the messages coming in to both the application instances. I understand only one application subscriber reads one specific message. But I expect both the application instances to get the messages randomly which does not seem to happen.

When the second application instance or the subscriber subscribes to the same topic, all the messages are received by the latest subscriber.

Example:

Two subscribers for the same topic (topic/state/+)
Publisher publishes to the topic(topic/state/123-345)

"Hello World1"
"Hello World2"
"Hello World3"
"Hello World4"
"Hello World5"
"Hello World6"

Subscriber 1 gets nothing

Subscriber 2 gets 

"Hello World1"
"Hello World2"
"Hello World3"
"Hello World4"
"Hello World5"
"Hello World6"

EXPECTED:

Subscriber 1 gets 

"Hello World1"
"Hello World3"
"Hello World5"

Subscriber 2 gets 

"Hello World2"
"Hello World4"
"Hello World6"

I tried the same example with mosquitto_sub and mosquitto_pub and I seem to get the messages as expected  into multiple mosquito subscribers. Is this a limitation or a bug or expected functionality?

**Comment by VladimirAkopyan** [comment]
I've also seen this issue, but your expectation is incorrect. Both clients should get all messages in MQTT, it's not meant for load balancing.

**Comment by arlingan** [comment]
Both the clients get all the messages if the clientID is different. If the clientID is the same for both the clients(meaning running multiple instances of the same application), then only the last subscribed client starts to get the messages. I tried this with persistent session clients. 

So, my confusion is if MQTT is not meant for load balancing messages or this plugin does not support it? As I said, I got the same behavior to work with mosquitto_sub and mosquitto_pub. 

I tried this with Rabbit MQTT adapter and also with mosquitto as the brokers. Same experience.

**Comment by VladimirAkopyan** [comment]
Huh, it looks like I am wrong then. 
I was always under impression that if another client with the same I'd connects, previous one should be disconnected.

**Comment by arlingan** [comment]
So this is where I am equally confused and this is one of the reason why I opened the issue. I would like to get some thoughts from experts on the expectation with MQTT and this client plugin. Are multiple clients with same ID supported and if yes, are there plans to be supported with this plugin?

**Comment by VLorz** [comment]
Running two client instances in the same application, using the same ClientId, gave me the result described by @VladimirAkopyan: a second client instance connecting to the same server instance using the same credentials disconnects the previously connected client. When this disconnected client tries to reconnect again, then the other client is disconnected...and so on.

**Comment by arlingan** [comment]
Right... and I see the same. But, the question is if this is the overall expectation? What if you want to load balance reading of messages from one topic with an app?

**Comment by chkr1011** [comment]
@arlingan Multiple clients with the same ID are not supported. 

From the official MQTT specs:
> The Client Identifier (ClientId) identifies the Client to the Server. Each Client connecting to the Server has a unique ClientId. The ClientId MUST be used by Clients and by Servers to identify state that they hold relating to this MQTT Session between the Client and the Server [MQTT-3.1.3-2].

**Comment by VLorz** [comment]
Thanks for the clarification, @chkr1011. In my current application I circumvented this behaviour using some sort of client id aliasing (client Id + instance Id), the idea is to be able to implement independent applications connecting to the same server sharing the same credencials, this way I simplify a litte bit the configuration process.
Once again, thanks a lot for this great job.

**Comment by bsampica** [comment]
Multiple instances of the client with the same id have never been supported in any platform of MQTT I've ever used...but as far as the server and message delivery is concerned, it's just a single client, so the poster above the say the behavior of the client bumping off the connected one, is correct.

What should happen depends entirely on the QOS specified.

QOS 0 - client (regardless which one) will only receive those messages if it's connected AT THE TIME they flow downstream
QOS 1- client (regardless which one) WILL receive those messages if it's connected (or resumes a session) - but a client resuming a session with the same ID may receive that message again (duplicates)
QOS 2- client (number 1) connects and receives messages 1, 2 3 - then client (number 2) connects (disconnecting the first) - will receive messages 4,5,6 - no duplication will occur.

Ive sent over a million frames through my mqtt.net server /client at QOS 0 and lost 5% - at QOS 1, lost 0% and duplicated 1% (staging random disconnects) and QOS 2, Lost 0%, duplicated 0% (staging random disconnects)

@chkr1011 if you're interested in my benchmarking code I can shoot it to you in a zip, and you could include it in your project.
