### ISSUE TITLE
Cannot add package to Xamarin.Forms project

### ISSUE THREAD

**Issue by russd2357** [chkr1011/MQTTnet#272]
Hi Christian,

First, I want to thank you for posting this project. I have been using it for a few months on an IoT project and it works like a champ! However....

When I try to add the package to a Xamarin.Forms project I'm working on, I get the following error:

Installing MQTTnet-CP 2.7.5.
Completed installation of MQTTnet-CP 2.7.5
For adding package 'MQTTnet-CP.2.7.5' to project 'Masterflex' that targets 'portable45-net45+win8+wpa81'.
Install failed. Rolling back...
Package 'MQTTnet-CP.2.7.5' does not exist in project 'Masterflex'
Package 'MQTTnet-CP.2.7.5' does not exist in folder '/Users/admin/Desktop/XamarinProjects/MasterflexLive-Xamarin/packages'
Executing nuget actions took 727.25 ms
Could not install package 'MQTTnet-CP 2.7.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm not familiar with building PCLs, but I guess I can look into compiling the project for the profile I use. If you have any advice, I'd greatly appreciate it!

**Comment by russd2357** [comment]
Tried building the PCL for this but the System.Net.Security and System.Net.Websockets both have dependencies on that are not supported under the .NET Portable subset. Looks like I'll have to find another library to use for my mobile app.

**Comment by chkr1011** [comment]
Hi,
the package _MQTTnet-CP_ is no official package. It is a fork of this project. PCLs are not supported by this project because netstandard 2.0 is already supported by Xamarin. 

Best regards
Christian

**Comment by russd2357** [comment]
Get the same error trying to use v 2.7.5

Attempting to gather dependency information for package 'MQTTnet.2.7.5' with respect to project 'Masterflex', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
  GET https://api.nuget.org/v3/registration3-gz-semver2/mqttnet/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/mqttnet/index.json 75ms
Total number of results gathered : 61
Gathering dependency information took 81.66 ms
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	80.84 ms
Attempting to resolve dependencies for package 'MQTTnet.2.7.5' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'MQTTnet.2.7.5'
Resolved actions to install package 'MQTTnet.2.7.5'
Retrieving package 'MQTTnet 2.7.5' from 'nuget.org'.
For adding package 'MQTTnet.2.7.5' to project 'Masterflex' that targets 'portable45-net45+win8+wpa81'.
Install failed. Rolling back...
Package 'MQTTnet.2.7.5' does not exist in project 'Masterflex'
Package 'MQTTnet.2.7.5' does not exist in folder '/Users/admin/Desktop/XamarinProjects/MasterflexLive-Xamarin/packages'
Executing nuget actions took 33.92 ms
Could not install package 'MQTTnet 2.7.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Just trying to figure out what I'm doing wrong.

**Comment by russd2357** [comment]
Hi Christian,
My Xamarin.Forms project  targets .NET Portable 4.5 Profile 111, which is compatible with .NET Standard 1.1. Do you know if it is possible to build MQTT for .net standard 1.1 and use that library with a project targeting Profile 111? I'd move everything to .net standard 2 but there are some XF controls I use that aren't there yet.

**Comment by russd2357** [comment]
Never mind. A little more digging produced an answer to my question and it is no. You use .net standard 1.3 because that is the lowest version of the standard that supports websockets. I'll have to try something else for this one.

**Comment by chkr1011** [comment]
Hi sorry but 1.3 is the min version required. But maybe you can introduce a new .netstandard 2.0 lib which references MQTTnet AND the existing portable classes as well?
Best regards
Christian
