### ISSUE TITLE
Duplicate folder names/.csproj file

### ISSUE THREAD

**Issue by TroelsL** [chkr1011/MQTTnet#278]
If you check out the master branch on a case sensitive file system, you'll end up with identical files:

https://github.com/chkr1011/MQTTnet/tree/master/Frameworks

There is both a MQTTnet.Netstandard directory and a MQTT.NetStandard directory. I'm assuming only one of them should stay.

**Comment by chkr1011** [comment]
Hi, I deleted the duplicate. Please try again and let me know if it works now.
Best regards
Christian

**Comment by TroelsL** [comment]
Looks fine now, thanks.
