### ISSUE TITLE
Is compression of the payload supported?

### ISSUE THREAD

**Issue by fleed** [chkr1011/MQTTnet#281]
Is there support for compression of the payload?

[V3](http://stanford-clark.com/MQTT/#payload) of the protocol mentions this possibility

**Comment by biapar** [comment]
you can put everything into payload and compress data. The main part of message is topic

**Comment by fleed** [comment]
@biapar so I can only handle it at application layer, can't I?

**Comment by markusschaber** [comment]
To quote from the V3 link above:

> If you want an application to apply compression to the payload data, you need to define in the application the appropriate payload flag fields to handle the compression details. You cannot define application-specific flags in the fixed or variable headers.

**Comment by fleed** [comment]
thank you for clarification
