### ISSUE TITLE
MqttCommunicationTimedOutException when transferring large files 

### ISSUE THREAD

**Issue by DanielMarcato** [chkr1011/MQTTnet#282]
I am trying to transfer large files >100MB via MQTT. The protocol apparently allows a maximum payload size of up to 256MB, however, in my tests with MQTTnet whenever I try to transfer one such file I get an MqttCommunicationTimedOutException. Is there a setting I forgot?

Here is the trace for a 100MB dummy file:

> [2018-05-23T15:59:55.0665557+02:00] [14] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=/clientname/Image] [Payload.Length=100000000] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=4] [Timeout=00:00:10]

> [2018-05-23T16:00:05.0668149+02:00] [6] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttPubRecPacket'.

>[2018-05-23T16:00:05.0688103+02:00] [6] [ManagedMqttClient] [Warning]: Publishing application message failed.

Edit: i was able to solve my issue by increasing the timeout via the WithCommunicationTimeout option to 60s. However shouldn't the protocol be intelligent enough to know that it is currently in the process of transferring data and thus should not throw the exception?

**Comment by chkr1011** [comment]
Hi,
sorry but increasing the timeouts is the only solution because all packets are sent in serial order. There is no way to send a different packet while another one (the large one) is not completed yet. 

Another solution is maybe splitting the large packets into smaller ones and creating the large file after all small ones are received. But this requires additional client logic.

Best regards
Christian

**Comment by chkr1011** [comment]
But maybe there is a solution...
MQTTnet server restarts the internal timer only after every received packet. Maybe there is a way to disable the timer while data (the payload) is being received. I will check this.

**Comment by chkr1011** [comment]
I just release an Alpha version (alpha3) which contains a fix. Please let me know if this version works for you.
