### ISSUE TITLE
folder issue 

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#283]
this file is in a wrong folder:

https://github.com/chkr1011/MQTTnet/blob/master/Frameworks/MQTTnet.Netstandard/MQTTnet.NetStandard.csproj

but i have no clue how to fix that, the folder has to be MQTTnet.NetStandard instead of MQTTnet.Netstandard

on windows it is the same folder

**Comment by TroelsL** [comment]
This is a duplicate of the issue I created yesterday. The reason you're seeing only one on Windows is that the Windows file system is case insensitive and doesn't allow two folders with the same name, but different casing.

https://github.com/chkr1011/MQTTnet/issues/278

**Comment by JanEggers** [comment]
thx
