### ISSUE TITLE
Managed client, retained message

### ISSUE THREAD

**Issue by JTrotta** [chkr1011/MQTTnet#284]
Hello, I'm checking if the retained message system used by the managed client, can work in any situations. If the serialized file contains only few messages, it definitely works well. But it could happen that the serialized file grows indefinitely, till many Mbytes. In that case I noticed some problems, also due to the OS or write and read file speed. 
I'm wondering if it could be better to create as many files as the messages are and not one file containing the whole messages. In the former case, we need to select the file (unique id, unique file name), to delete when it is sent. But now the retained message list does not expose any of.
What you think?
JJ

**Comment by chkr1011** [comment]
Hi,
the managed client is only a simple implementation for most cases. If there are special conditions I recommend creating a custom one which uses the regular client. I will also move this client to an extension lib like RPC in the near future.

But is is already possible to pass in a different storage implementation via the options. There you can decide how to store the messages. Per file or a single file etc. Probably some more methods in the interface for adding or removing a single file are a suitable way. 

Best regards
Christian

**Comment by JTrotta** [comment]
I do not agree. It's a very useful client full of clever customizable options. It should be maintained: standard client, following Mqtt rules, managed client as a full standard client with customizable options, very powerful and uncommon in the Mqtt clients world.
What I asked for, is the possibility to have a unique identifier in the MqttApplicationMessage class, if it is possible of course.

**Comment by JTrotta** [comment]
It'a good idea but MqttApplicationMessage  is sealed. This means that I cannot use neither the new MqttApplicationMessageBuilder.
Create a new MqttApplicationMessageWithId class and a new builder from zero, does not seem to be  a good idea. Suggestions?

**Comment by chkr1011** [comment]
With 2 very small changes this can be done very easy.
1) MqttApplicationMessage is no longer sealed.
2) The builder gets a constructor which accepts a pre build message. There you pass your _MessageWithId_ and the builder will modify this instance. There is still an empty constructor which creates a new one.

I assume this should work.

**Comment by JTrotta** [comment]
Just published a very early, but working, solution to manage message with id serialized on disk.
Take a look.

**Comment by chkr1011** [comment]
Hi,
I released version 2.8.0-alpha5 which now contains the new type of message. Please let me know if this works for you. Please keep in mind that the managed client is also in a new nuget now. But beside of namespaces it should also work.

**Comment by JTrotta** [comment]
Version 2.8.1 works as expected.
Great work!

**Comment by andnig** [comment]
Hey @JTrotta. I'm wondering if you could share your implementation of IMqttClientStorage which uses the MessageWithId? 
Thanks in advance!
