### ISSUE TITLE
Crash when losing wifi while connected

### ISSUE THREAD

**Issue by acrabb** [chkr1011/MQTTnet#287]
We're getting a crash if we turn off wifi during a connection and are actively publishing messages:
> [ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: Error while sending TLS Alert (Fatal:InternalError): System.IO.IOException: Unable to write data to the transport connection: The socket is not connected. ---> System.Net.Sockets.SocketException: The socket is not connected

our PublishAsync call is wrapped in a try/catch, but the unhandled exception seems to get past it
> try {
		await Client.PublishAsync (message);
	} catch (Exception e) {
		this.Log (LogTag.Error, $"ERROR Publishing MQTT payload: {e.Message}");
	}

**Comment by chkr1011** [comment]
Thank you very much! I was trying hard to find the cause of this exception. Now I can reproduce and fix it 😄

**Comment by chkr1011** [comment]
Which version did you use? Does this also happen with the Alpha 2.8.0 version?

**Comment by acrabb** [comment]
We're using 2.7.3-rc3 in Android.

**Comment by acrabb** [comment]
Weird, seems like it continues to throw repeatedly (every 5 seconds or so) if we silently catch it and do nothing.

**Comment by chkr1011** [comment]
Is it possible to test it again with 2.8.0 alpha 1?

**Comment by acrabb** [comment]
yes, seems fixed! (at least in android)

**Comment by chkr1011** [comment]
I don't know. There will be some more test releases first. So in 1-3 weeks I guess.
