### ISSUE TITLE
How can the server force close a client connection?

### ISSUE THREAD

**Issue by asthomas** [chkr1011/MQTTnet#296]
I have created a MQTTnet server with an administrative front-end.  I want the administrator to be able to select a client connection from a list and force it closed.  I don't see an API in the MqttServer class that would allow this.  Is there a way to do it?  If not, would you contemplate adding it?  Something like IMqttServer.CloseConnectedClient(string clientId).

**Comment by chkr1011** [comment]
Hi, there is a new API for this in version 2.8.x. A alpha version is available as a nuget package.
Best regards
Christian

**Comment by asthomas** [comment]
Thank you.  I guess you are referring to MQTTnet.Server.MqttClientSession.Stop().  I'll take a look.
