### ISSUE TITLE
Having some sort of change tracking log between versions would be of help

### ISSUE THREAD

**Issue by VLorz** [chkr1011/MQTTnet#299]
Hi,

I've just upgraded to version 2.8.0-alpha1 (Nuget) and both of my applications (client, server) stopped working. Rolling back to version 2.7.5 made it work again. 

After trying to compare branches in the repo to see what changed, I simply stopped looking at the 36th modified file.

It would be great having some sort of change tracking mechanism in a more higher level than just looking at the repo.

Thanks a lot in advance,

**Comment by chkr1011** [comment]
Hi,
what exactly do you mean with "stopped working"? Exceptions? 

Also please keep in mind this is a alpha release. There is no guarantee for anything at all.

Best regards
Christian

**Comment by VLorz** [comment]
Hi Christian,

I'll try to create a test project working in similar way as my applications to be able to reproduce it. No exceptions. I tried two times the upgrade/downgrade process and got same results but I didn't have logging on the MQTT side.

Best regards,
Victor

**Comment by chkr1011** [comment]
If your issues are still existing with the release of 2.8.0 please let me know.
