### ISSUE TITLE
2.8.0-alpha3 breaks payload

### ISSUE THREAD

**Issue by GieltjE** [chkr1011/MQTTnet#304]
It appears the payload gets cutoff, we are sending json serialized messages with Statics.UTF8Encoding.GetString/Statics.UTF8Encoding.GetBytes.

Seeing a max of 72bytes, but always 50 or 72.

**Comment by chkr1011** [comment]
Do you have some more details? All unit tests are still working.

**Comment by GieltjE** [comment]
Not at the moment, have to go to sleep now.
Reverting to 2.7.5 for now, the ApplicationMessage.Payload is always the first 50 or 72 bytes of the sent payload (sending on avarage 177bytes).

Will do some more testing hopefully tomorrow evening.

**Comment by GieltjE** [comment]
Example message: ```{"Callback":"d3b2c1fe6af04d0180e7142422305928","MessageID":"a8098be726c64174a4feac136eaf5c3a","Type":3,"Content":{"Action":true,"CompanyID":1384,"LocationID":1,"TerminalID":"929c92ab49","KioskID":0}}```

**Comment by chkr1011** [comment]
I found the problem. The encoding for large messages is wrong which was introduced with alpha3. I will fix it and upload alpha4 for testing.
