### ISSUE TITLE
Client Stuck when I call DisconnectAsync Method

### ISSUE THREAD

**Issue by adeel1996** [chkr1011/MQTTnet#305]
Hello, 
   I am using version 2.7.5. I need to verify broker credentials provided by user. I use following code
After verifying broker connection when I call DisconnectAsync() method it stuck here, does not return from DisconnectAsync() method.

public async Task VerifyCredentials(Credentials userCredential)
{
            try
            {
                var factory = new MqttFactory();
                var client = factory.CreateMqttClient();
                // Ignore untrusted certificate exceptions
                IgnoreCertificateAuthorityException(userCredential.SkipTlsVerification);
                IMqttClientOptions options;
                
                    options = new MqttClientOptionsBuilder()
                       .WithClientId(_deviceId)
                       .WithCredentials(userCredential.Username, userCredential.Password)
                       .WithTcpServer(userCredential.IP, userCredential.Port)
                       .Build();

                await client.ConnectAsync(options);
                if (client.IsConnected)
                {
					//Alert Message for UI
                    UIAlertManager.SendAlert("Credentials Verified", WebSocketIdentifier.Configuration, AlertType.Success);
                }
                await client.DisconnectAsync();
            }
            catch (Exception ex)
            {
				//Alert Message for UI
                UIAlertManager.SendAlert(ex.Message, WebSocketIdentifier.Configuration, AlertType.Error);
            }
}

**Comment by chkr1011** [comment]
Hi, thank you for reporting this issue.
I found the issue and released 2.8.0-alpha5 as a nuget package. Please let me know if this version works for you. Please keep in mind that it contains some breaking changes.
Best regards
Christian

**Comment by adeel1996** [comment]
Hello, thank you for your fast reply.
I have updated to 2.8.0-alpha5 but I am still getting the same error.

**Comment by chkr1011** [comment]
Please try again with 2.8.0-rc1.

**Comment by adeel1996** [comment]
It seems to be working fine, Thankyou soo much.
Can you please tell me when it will be available in stable realease?

**Comment by chkr1011** [comment]
2.8.0 already has several RC versions. So issume it will be released in a couple of days.
