### ISSUE TITLE
CustomCertificateValidationCallback cannot distinguish multiple client connections

### ISSUE THREAD

**Issue by asthomas** [chkr1011/MQTTnet#308]
My application makes 2 client connections via SSL.  Each connection uses a different CA Root certificate for validation.  Each IMqttClient adds a method to MqttTcpChannel.CustomCertificateValidationCallback that validates the server certificate against the CA Root for that IMqttClient.

The problem is that CustomCertificateValidationCallback is not client-specific, so whenever either client connects the CustomCertificateValidationCallback is called twice, once for each client that has added a callback to the callback list.  In all cases, one of these two callbacks will fail since the server certificate of one client will always fail against the CA Root of the other.  A certificate validation will fail if any callback returns false.

In order to correct this, the callback needs to know which client is trying to connect.  The callback has a MqttClientTcpOptions argument, which contains Server and Port members.  Theoretically the callback could compare Server and Port to the original connection parameters.  But that won't work, as the connection was likely made to a DNS name, not an IP address, and the Server member contains the IP address.  This causes a problem when the MQTT server is behind a reverse proxy where the DNS name may be used to route a connection to a different MQTT server running at the same IP address.  I realize this isn't pertinent to TCP connections, but it is for WebSocket connections.

So, I have to write this code in the certificate validator:
```
FieldInfo optionsInfo = Client.GetType().GetField("_options", BindingFlags.NonPublic | BindingFlags.GetField | BindingFlags.Instance);
if (optionsInfo != null)
{
    IMqttClientOptions ioptions = optionsInfo.GetValue(Client) as IMqttClientOptions;
    if (ioptions != null)
    {
        MqttClientTcpOptions options = ioptions.ChannelOptions as MqttClientTcpOptions;
        if (options != null)
        {
            if (tcpOptions.Server != options.Server || tcpOptions.Port != options.Port)
            {
                // This is not our responsibility, so return true.
                return true;
            }
        }
    }
}
```

I would like to suggest that the CustomCertificateValidationCallback take an argument of type IMqttClient that identifies the connecting client so that we don't need to dig around in the private members of MqttClient using reflection to be secure.

**Comment by chkr1011** [comment]
Hi, I will add the client options to the callback and also add a new callback which can be specified at the client options. I will let you know when the new version is released.
Best regards
Christian
