### ISSUE TITLE
Exception handling during the multiple asynchronous method call is not working

### ISSUE THREAD

**Issue by isharehappycode** [chkr1011/MQTTnet#309]
I am calling **RunAsync** method in c#, but it's not returning the exception when connection is down. 

private async static Task SendMessage(string message)
    {
        try
        {
            (MQTT.RunAsync(message.ToString(), topic)).Wait();                
        }
        catch (Exception Ex)    
        {
           // Exceptions are not getting cought here
        }
    }

What is best practice to handle exceptions during async calls?

**Comment by chkr1011** [comment]
Hi,
you have to await the call: _await MQTT.RunAsync(message.ToString(), topic);_

Best regards
Christian

**Comment by isharehappycode** [comment]
(MQTT.RunAsync(message.ToString(), topic)).Wait();  is same as  await MQTT.RunAsync(message.ToString(), topic);
