### ISSUE TITLE
Performance bottlenecks - analysis

### ISSUE THREAD

**Issue by asthomas** [chkr1011/MQTTnet#311]
I created a test client and server sending trivial messages as quickly as the CPU would allow.  I'm running on an 8-core system (well, 4 + hyperthreading).  I am using the "develop" branch dated June 12, 2018.

The client creates 1000 topics and attempts to update them every 20 milliseconds, for a total of 50,000 topic changes per second.  The client also subscribes to all 1000 topics, so the total maximum messages at the client would be 100,000 per second (50,000 in, 50,000 out).

I ran the client and server in RedGate's ANTS Performance Profiler V9 to get an idea of performance  bottlenecks.

The stock code was able to manage about 2000 messages, round trip, for a total of 4000 messages per second.  All 8 cores were exhausted.  The server used about 80% of the machine, with the rest in the client and sundry O/S processes.

According to ANTS, The largest bottleneck is in the use of async/await.  The async/await pattern was never intended for very high performance systems.  The overhead associated with task pool management, thread context switching, thread creation, etc. is very high.  About 80% of the total CPU load was attributable just to async/await overhead.  I created a separate set of synchronous methods to mirror almost all of the Async functions, and re-implemented the client and server using only synchronous calls.  I had to retain the threads for sending and receiving, but that's more or less it.  I had to change the packet awaiters in the synchronous code to use semaphores instead of async awaiters.

Removing async/await increased the throughput to 16,000 messages per second and exposed two other bottlenecks.

The AsyncAutoResetEvent used by MqttClientPendingMessageQueue was now using about 40% of the CPU, just in the one line in TrySendNextQueuedPacketAsync.  Well, actually in the synchronous equivalent: TrySendNextQueuedPacket:
```
// original:
await _queueAutoResetEvent.WaitOneAsync(cancellationToken).ConfigureAwait(false);

// synchronous:
_queueAutoResetEvent.WaitOneAsync(cancellationToken).Wait();
```
I  replaced the AsyncAutoResetEvent with a Semaphore.  CPU usage in TrySendNextQueuedPacket dropped essentially to zero.  This simple change increased messages per second to around 30,000 per second.

Now the bottleneck is in MqttClientSubscriptionManager.CheckSubscriptions.  This method uses a linear search through all of the client's subscriptions, for every change in any topic.  That means that for a client with 1000 subscriptions, every change must call MqttTopicFilterComparer.IsMatch 1000 times.  That results in millions and millions of IsMatch calls in my test case for a relatively low number of actual value changes, and for zero actual IsMatch hits.  As the number of subscriptions rises, the overhead of MqttClientSubscriptionsManager.CheckSubscriptions swamps all other processing.

I changed CheckSubscriptions to use a Dictionary<string,Hash<string>> where the key is the topic and the Hash is the set of subscription regular expressions that are matched by the topic.  Adding a topic to the server adds that topic to the dictionary and traverses all subscriptions to add any matching subscriptions to the topic's hash.  Subscribing and unsubscribing edit the hash to add or remove the subscriptions from the topic.  This makes CheckSubscriptions a constant-time call, and IsMatch is called only when a topic is added or a subscription is added.

After this change I am seeing 63,000 messages per second.  The total CPU usage on the machine is about 12% for each of the client and server (effectively 1 core each).  So the net result is that the total message rate increased by a factor of 16 and the CPU load decreased by a factor of 4.  That's a 64-fold performance improvement.

The code I wrote to perform these tests is utter garbage.  It doesn't handle disconnections and timeouts at all, and all of the synchronous methods are just copies of the async methods with no thought to proper factoring.  I can send you a zip if you would like.  I guarantee it will make you weep.

Anyway, this demonstrates there is a lot of room for performance improvement just by focusing on these three changes.  The hardest by far is removing all of the async/await code.  From the profiler it looks like you won't get much out of the other changes until the code can handle the data rates that are unreachable with async/await.

**Comment by chkr1011** [comment]
Hi,
thank you for your report. That is very interesting. But providing async functionality is one of the key goals of this library. But I will check where this can be removed.

I noticed that the performance of the _netcoreapp_ version is much faster than the others (60.000 vs. 2.000) message rate. Which version did you use for your tests?

Yes please upload the ZIP.

Best regards
Christian

**Comment by asthomas** [comment]
Following up on this, I reinstated the async/await code and added a command-line argument so I can switch between async and sync modes of operation in my client and server.

With all other things being equal, the sync code is 1/3 the throughput and 3x the CPU usage, so about 1/9th the resource efficiency.  That means that the other two efficiency changes are a lot more important than I originally reported.

I then added an out-of-order packet detector to the test.  The sync server never receives an out-of-order packet from the MQTT library.  The sync client receives a small number of out-of-order packets.  I haven't figured out where they come from - whether they are transmitted out of order or received from the socket thread out of order.

The async code delivers about 0.5% of packets out of order from in the server, and about 3.5% out of order packets in the client.  This seems to vary with CPU availability.  The culprit appears to be the server code.  In addition a similar number of packets appear to get lost entirely in both client and server.

For some applications out of order packets do not matter much.  For others they are catastrophic.  I think that the out of order problem is at least as big a deal as the efficiency issue.  I'll post here if I can identify the source.

**Comment by asthomas** [comment]
In response to your response:
- I am using .Net Framework 4.6.1 for my tests.  That's my production target.

- I agree that asynchronous operation is helpful, but it does not have to be provided using the async/await mechanism.  Queuing messages between threads using semaphores is both substantially faster and not prone to message re-ordering.  In my experiments I have both async and sync functionality living side-by-side.  That lets the user choose between performance and async operation.

I have attached my test code.  The MQTTnet solution is in the MQTTnet subdirectory.  MQTTnetTest.sln is the solution for the test client and server.  If you run either client or server with a "-a" argument it will run the async code.  By default they run the sync code.
[MQTTnetTest1.zip](https://github.com/chkr1011/MQTTnet/files/2103905/MQTTnetTest1.zip)

**Comment by chkr1011** [comment]
I remember this ticket #269. There was an issue with the semaphore approach. I am wondering if this will also happen here.

**Comment by asthomas** [comment]
Christian, as a baseline, can you post the speeds that you get when running my client and server in sync mode?  That will help me to understand your performance numbers.  I'm sure they vary a lot depending on the computer hardware.

**Comment by dWwwang** [comment]
no

**Comment by JanEggers** [comment]
@chkr1011 my main intend of batch send was to improve network buffer usage, if its causing issues im fine with removing it.

**Comment by asthomas** [comment]
I have a little more info.  I changed the missing message detection to be more accurate, keeping a 4000-value message history and periodically looking back over the history for missing values.  That eliminates the false positives that my earlier test apps were reporting.  I also added duplicate message detection at the same time.  I also found a couple of thread races in my sync code that was causing some wacky behaviour.

This lets me run the tests with different quality of service choices.  The net result is that the code produces:

Async
ExactlyOnce:  0.013 % out of order, 0.19% missing, 0 duplicate, 2400 /sec, CPU = 65%
AtLeastOnce:  0.015 % out of order, 0.19 % missing, 0 duplicate, 3800 /sec, CPU = 65%
AtMostOnce:  0.4 % out of order, 0 missing, 0 duplicate, 7900 /sec, CPU = 50%

Sync
ExactlyOnce:   0 out of order messages, 0 missing, 0 duplicate, 5900 /sec, CPU = 40%
AtLeastOnce:   0 out of order, 0 missing, 0 duplicate, 10400 /sec, CPU = 40%
AtMostOnce:  0 out of order, 0.16 % missing, 0 duplicate, 32000 /sec,  CPU = 30%

**Comment by chkr1011** [comment]
I published some changes in DEV. Now my performance increased to ~6.000 messages for net461.  I also made the following changes:

1. All application messages are now added to a big queue and a separate thread at the server will distribute them to the sessions. This should fix the issue with out of order packets.
2. I removed some useless _async/await_ calls. Especially where the data should be already present. Reading calls where the data may arrive in a long time still use _async/await_.
3. I removed the timeout from the sending code. I am wondering if it makes sense here because the _NetworkStream_ has an established connection and an exception will be thrown if the connection is lost etc. For me the timeout only makes sense for connecting or reading purpose because it cannot be determined when exactly data will arrive or if data will arrive at all. @JanEggers What do you think about this? Would you agree?

@asthomas I will perform a test with your code soon. What exactly to you require?

As long as I have to memory profiler I can only guess where I can optimize. I tries the VS analyzer but I don't understand the results 😄

**Comment by JanEggers** [comment]
yup I agree timeout handling was a thing to be optimized as well. may I suggest using the new System.Threading.Channels for buffering messages, they are speficly designed for async buffering.

**Comment by asthomas** [comment]
I merged your latest commit with my code.  It had a significant impact on performance.  I'm now seeing 63000 round-trips (126000 packets) per second with the synchronous code and QoS 0.

The out-of-order packets still occur in all qualities of service with the async code, never in the sync code.

I had to do some modifications to the sync code to incorporate the latest changes, so you will need a new build.  I have put my mods here [https://github.com/asthomas/MQTTnet/tree/SyncIO](https://github.com/asthomas/MQTTnet/tree/SyncIO).

You will also need new test clients and servers:  [https://github.com/asthomas/MQTTnetTest](https://github.com/asthomas/MQTTnetTest).  You will need to change the references to MQTTnet.dll for this to build.

**Comment by chkr1011** [comment]
I just released 2.8.0-rc2. I believe this is a good trade off between async and sync code. Let me know what you think.

Also the order should be preserved now. If not I have absolutely no idea why 😄

**Comment by asthomas** [comment]
I updated my experimental code and test client/server with your new changes.  They did not make a substantial difference to performance.

Here are my test numbers.  I ran three different scenarios:
1) The devel branch code from the original repository
2) The devel branch code with modifications to AsyncAutoResetEvent and CheckSubscriptions
3) Synchronous communication modifications to modified code (number 2 above)

The CheckSubscriptions modification is an attempt to answer [https://github.com/chkr1011/MQTTnet/issues/323](https://github.com/chkr1011/MQTTnet/issues/323)

I did not run this with multiple clients.  The async code cannot be benchmarked with multiple clients due to [https://github.com/chkr1011/MQTTnet/issues/331](https://github.com/chkr1011/MQTTnet/issues/331)

Measurements are the number of packets received and processed by the server.
CPU load is the combined CPU load of both client and server as % of 1 core (on this machine, could be up to 800%).

None of the tests produced out of order or duplicate messages.  Only scenario 3 produced dropped messages, and only in QoS AtMostOnce, which is acceptable and due to intentional queue limits in the library.

The test consists of 2000 subscribed topics being written by the same client as quickly as a Windows timer will allow (about 60Hz).

**Scenario 1: (V 2.8.0-rc2)**
AtMostOnce: 2,500 msg/s, 300% CPU
AtLeastOnce: 1,900 msg/s, 475% CPU
ExactlyOnce:  1,750 msg/s, 525% CPU

**Scenario 2: (V 2.8.0-rc2 with CheckSubscriptions modifications)**
AtMostOnce: 11,500 msg/s, 360% CPU
AtLeastOnce:   5,300 msg/s, 420% CPU
ExactlyOnce:    2,800 msg/s, 600% CPU

**Scenario 3: (V 2.8.0-rc2 with CheckSubscriptions and synchronous modifications)**
AtMostOnce:  84,000 msg/s, 400% CPU
AtLeastOnce:  13,400 msg/s, 250% CPU
ExactlyOnce:     7,300 msg/s, 210% CPU

**Relative performance:**  Call scenario 1 the baseline.  Compare the others on the basis of msg/s per CPU %:
AtMostOnce:  S1 = 1, S2 = 3.80, S3 = 25.2
AtLeastOnce:  S1 = 1, S2 = 3.15, S3 = 13.4
ExactlyOnce:   S1 = 1, S2 = 1.40, S3 = 10.4

That is, improving the CheckSubscriptions code can improve performance by 3.8x in the AtMostOnce case, and 1.4x in the ExactlyOnce case.

Improving CheckSubscriptions and changing the code to synchronous can improve performance by 25.2x for AtMostOnce, and by 10.4x for ExactlyOnce.

**Comment by chkr1011** [comment]
I am still reading your results (thank you for this) but I just want to mention that the _CheckSubscriptions_ method **is** already sync.

**Comment by JanEggers** [comment]
for me this is a bit theoretical can you (@asthomas) provide a PR with benchmarks and your changes, that would make it easier to discuss if the changes are valid and perf gain is in good relation to code complexity.

**Comment by asthomas** [comment]
This is not an issue of CheckSubscriptions being synchronous.  In my original post I identified three distinct performance issues:
1) CheckSubscriptions has a linear search, which is very inefficient with large data sets
2) AsyncAutoResetEvent consumes a huge amount of CPU and can be replaced with a semaphore
3) async/await code spends a lot of time in thread management.  Removing async/await improves performance hugely.

CheckSubscriptions can be improved without regard to the other two issues.

**Comment by asthomas** [comment]
I forked the repo and uploaded my changes as the SyncIO branch in my fork.  I created some test server and client applications in a separate repo.  You can see the links 6 comments above this one in this thread.

My sync code is terrible.  I didn't try to make it fit with the library nicely.  I'm not really sure how to re-factor code to provide both sync and async versions of functions without making complete copies of the functions.  The point was to test whether sync is faster than async in this code base.  

The CheckSubscriptions improvements use dictionaries and hashes to perform comparisons only once, but to do that the server must always store the value for each topic, which violates the MQTT spec and uses more memory.  That's a trade-off that in my case I'm happy to make.

My test applications let you run async and sync code separately for client and server so you can compare.  If you compile without the HAVE_SYNC compilation definition then they will work with the current version of MQTTnet.  If you use HAVE_SYNC then you must compile with my version.

My goal here was to identify performance bottlenecks.  I don't know how to make my hacks fit prettily into the existing code base.

**Comment by JanEggers** [comment]
@asthomas I had a look at your branch and I think you should create a new branch that just contains the subscription management changes. then create a PR and we can review it. 

the changes look good overall but there are still some double access to the collections that can be optimized away.

next we can have a look at the other changes, im currently also working on optimizations with more queues and less locking and less task so there may be overlapping effort

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.

**Comment by XingJordan** [comment]
Hey,
Currently I‘m working with the managed client latest version and have a test to send 100 messages in one topic, another client subscribes this topic and tries to receive the packets. Depending on QoS and Intervall between two messages sent the receiving client gets between 60-95% of the messages. Are there known issues with message loss in the managed client?!

**Comment by SeppPenner** [comment]
Hi @XingJordan: If I was you, I would put this in a seperate issue. As far as I know by now, there is no such problem known by now... Can you share a code sample, please?
