### ISSUE TITLE
ManagedClient removed from Beta5?

### ISSUE THREAD

**Issue by bsampica** [chkr1011/MQTTnet#313]
It appears I can no longer find the IManagedClient or ManagedClientOptions or related classes in the 2.8.0-alpha5  version of the Nuget package.

Is the managed client being removed?

**Comment by chkr1011** [comment]
Hi,
yes that is correct. Please have a look at the release notes. The ManagedClient is now a separate nuget package.

Best regards
Christian

**Comment by bsampica** [comment]
Can you link me to the release notes?  I’ve been all over your GitHub and can’t aeem to locate anything about it being moved.

**Comment by chkr1011** [comment]
Here is the link: https://www.nuget.org/packages/MQTTnet/2.8.0-alpha5
