### ISSUE TITLE
MQTT Server:Generally,how many clients can server bear max?

### ISSUE THREAD

**Issue by JhouXerox** [chkr1011/MQTTnet#314]
through the simple test,l have some questions.

I haven't tested the server's limit.So is there anyone tested the server's limit?

how much MQTTClients can a single server handle?
Is it depend on the server computer's hardware or tcp protocol‘s limit’?

if there are any clients large more than the limit? how can l  connect two or more server to deal with and it will work like a single server?

**Comment by chkr1011** [comment]
Hi,
I did not  measured this yet. If you do it I would appreciate it. Putting servers together is not supported. But you can send messages from one broker to another using the interceptors of the server and the server side publish method. But you will have to take care that you don't send that new message back to avoid a infinite loop.

Other brokers like CloudMQTT are using a topic prefix filter for this.

Best regards
Christian
