### ISSUE TITLE
Packet identifier collision between client and server

### ISSUE THREAD

**Issue by asthomas** [chkr1011/MQTTnet#316]
I have a client that sends 1000 Subscribe messages when it starts.  My server sends back a Publish message for every topic that has a stored message.

It turns out that the packet identifiers used by the client and server both start from 1, and monotonically increase.  Depending on scheduling and data behaviour in the server, it is possible that the client sends a Subscribe with packet identifier 90 (for example) at the the same time that the server sends out a Publish message with packet identifier 90.

The result is that the client receives a Publish packet with identifier 90 when it was expecting a SubAck with identifier 90.  The code matches the waiting subscriber thread with the Publish packet and then throws an error because it cannot coerce a MqttPublishPacket to a MqttSubAckPacket.

I know this sounds like a rare case.  You would be surprised how many times I encountered this before I figured out what is going on.

Can you suggest a good fix for this?  I was thinking that I could change MqttPacketIdentifierProvider to set _value to a random number to start, which would reduce the chance of this happening, but how can I eliminate this case entirely?

**Comment by JanEggers** [comment]
that is an mqtt issue in general the identifier is a uint, a complete fix would be to specify a new protcol version with 128 bit idents aka guids, but that is out of the scope of this implementation

**Comment by asthomas** [comment]
Thank.  That's what I thought I was seeing in the spec.  Thinking about this, I'm going to hack the awaiter code to compare the packet by both type and identifier.  I cannot think of a case where both the identifier and the packet type could match while actually being the wrong message.

**Comment by chkr1011** [comment]
I am wondering because the original Dispatcher was comparing Type and ID as well. The Tuple contains both. To me only this makes sense.

**Comment by chkr1011** [comment]
I assume this is no longer relevant because the mentioned way is already implemented. Feel free to open it again if required.

**Comment by asthomas** [comment]
Thanks for looking at this.  It was entirely my mistake.  I modified the code for synchronous operation and did not properly take into account the expected return packet type.  After fixing my problem it works as you describe.
