### ISSUE TITLE
SSL connection from client fails, when target framework is netcoreapp2.1

### ISSUE THREAD

**Issue by Jay424** [chkr1011/MQTTnet#319]
OS: Ubuntu 16.04
dotnet version: 2.1.300

When I try to connect to a Server with a client certificate I receive the following error:

`Unhandled Exception: MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+Crypto+OpenSslCryptographicException: error:2006D002:BIO routines:BIO_new_file:system lib
`

As soon as i change the target framework to netcoreapp2.0 it works.

Steps to reproduce:
- Setup server
- Start server
- Build client with TargetFramework netcoreapp2.1
- execute
- leads to exception

The same steps wit netcoreapp2.0 works

**Certificates:**
[certs.zip](https://github.com/chkr1011/MQTTnet/files/2122776/certs.zip)

**Client code:**
```
    using System;
    using System.Security.Cryptography.X509Certificates;
    using MQTTnet;
    using MQTTnet.Client;
    using MQTTnet.ManagedClient;
    using MQTTnet.Serializer;
    using MQTTnet.Diagnostics;
    
    public class Client
    {
       public async void Connect()
        {
            var caCert = new X509Certificate(@"certs/ca.crt");
            var clientCert = new X509Certificate2(@"certs/client.pfx", string.Empty);

            Console.WriteLine(clientCert.HasPrivateKey);
            var mqttClienOptions = new MqttClientOptionsBuilder()
                .WithClientId("test123456789")
                .WithTcpServer("127.0.0.1", 8883)
                .WithKeepAlivePeriod(TimeSpan.FromSeconds(40))
                .WithTls(true, false, false, clientCert.Export(X509ContentType.Pfx), caCert.Export(X509ContentType.Cert))
                .WithProtocolVersion(MqttProtocolVersion.V311)
                .WithCleanSession(true)
                .Build();
            
            var managedMqttClienOptions = new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(1))
                .WithClientOptions(mqttClienOptions)
                .Build();

            MqttNetGlobalLogger.LogMessagePublished += (s, e) =>
            {
                var trace = $">> [{e.TraceMessage.Timestamp:O}] [{e.TraceMessage.ThreadId}] [{e.TraceMessage.Source}] [{e.TraceMessage.Level}]: {e.TraceMessage.Message}";
                if (e.TraceMessage.Exception != null)
                {
                    trace += Environment.NewLine + e.TraceMessage.Exception.ToString();
                }

                Console.WriteLine(trace);
            };
            
            var mqttClient = new MqttFactory().CreateMqttClient();
            mqttClient.Connected += OnConnected;
            mqttClient.ApplicationMessageReceived += OnApplicationMessageReceived;
            await mqttClient.ConnectAsync(mqttClienOptions);
            await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("/#").Build());
        }

        private void OnApplicationMessageReceived(object sender, MqttApplicationMessageReceivedEventArgs eventArgs)
        {
            Console.WriteLine($"Received msg from topic: {eventArgs.ApplicationMessage.Topic}");
        }

        private void OnConnected(object sender, MqttClientConnectedEventArgs mqttClientConnectedEventArgs)
        {
            Console.WriteLine("Connected to broker");
        }
    }
```
Copy ca.crt and client.pfx to clientExecutionFolder/certs

**Setup server**
Change this value in the server config to enable client verification
by certificate:
emq.conf:
```
listener.ssl.external.keyfile = etc/certs/server.key
listener.ssl.external.certfile = etc/certs/server.crt
listener.ssl.external.cacertfile = etc/certs/ca.crt
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
```

Clear ./emqttServerFolder/etc/certs
Copy ca.crt, server.crt and server.key to  ./emqttServerFolder/etc/certs

**Comment by chkr1011** [comment]
That is a interesting issue. But I believe this is a .net core related issue because the code for nestandard2.0 and 2.1 is the same. 

@JanEggers Do you maybe have an idea?

**Comment by JanEggers** [comment]
I am certain that this is an aspnetcore / dotnet core issue as the stacktrace indicates it is not mqttnet code that generates the error.

**Comment by Jay424** [comment]
Know I found a solution. It seems that in .net 2.1 was a change which throws an error when certificates are not accessible.
My solution was to change access rights for the failing certificates. 

[dotnet/corefx#29942](https://github.com/dotnet/corefx/issues/29942)

I have used [this](https://github.com/dotnet/corefx/issues/29942#issuecomment-397207557) code to identify the failing certificates.

**Comment by TechAspirant** [comment]
I am facing same issue with .net core 3.0 Can you tell me how you resolved this ?
@Jay424  My solution was to change access rights for the failing certificates means exactly what you did ?
