### ISSUE TITLE
Add OnDisconnect() Event

### ISSUE THREAD

**Issue by AtosNicoS** [chkr1011/MQTTnet#320]
Currently there is only a Disconnected event available, which is raised, when the client disconnected. It would be nice to also have an OnDisconnect() event that is triggered before the disconnect gets invoked.

The reason behind this is to send some status updates before disconnecting, for example to set the status to "offline" before disconnecting. The same could be useful for OnConnect(). What do you think?

**Comment by GieltjE** [comment]
Isn't this where the willmessage has it's intended use? Also it wouldn't be possible to send these messages if the message got disconnected by the server/router e.t.c. (the willmessage is sent by the server on your disconnect).

**Comment by AtosNicoS** [comment]
I am talking about the client library. I want to realize 3 possible status stages:
* online
* offline (graceful disconnect) -> my request
* disconnected (ungraceful disconnect) -> will message

My code will do the following:
1. Set will options
2. Connect with options
3. Publish online status
4. Do stuff
5. User initiated disconnect
6. Disconnect
7. OnDisconnect() -> not used

If 5-6 wont get exectued the last will is sent. However if they are used, I flag a graceful shutdown to my subscribers. What I want to do is to put 5. into a pre-hook before the disconnect.

Currently I am wrapping 5&6 in a single function. I might be wrong, this might be not that useful. So now that my usecase is hopefully clearer, what do you think?

**Comment by chkr1011** [comment]
I get your point but at the moment this is not possible. I added a new property to the ManagedClient which provides the count of pending messages. You can use it to wait before calling the Disconnect method (using SpinWait etc.).

**Comment by AtosNicoS** [comment]
Why not possible? I think the event must be raised here:
https://github.com/chkr1011/MQTTnet/blob/8f96acaec4350de49d0141cb4faac74683070d50/Frameworks/MQTTnet.NetStandard/Client/MqttClient.cs#L97

**Comment by chkr1011** [comment]
Yes this event can be added but I assume your intention is different. If this event is raised in a different thread it will not block and the client will disconnect immediately. From your use case it seems you want to ensure that all pending messages are sent before the connection is closed. Also please keep in mind that we cannot inform you about a disconnect. If the server is down or network the _OnDisconnect_ event will have the same functionalety as the _Disconnected_ event. There is no chance for you to send anything. 

If you use a regular client you can just send a message before disconnecting. The managed client works asynchronous but also contains an event which is called for every processed (send) application message. You can just wait until your "offline" message was sent and then stop the client.

**Comment by AtosNicoS** [comment]
You are right, I will close this for now.
