### ISSUE TITLE
Large scale performance test

### ISSUE THREAD

**Issue by ChristianRiedl** [chkr1011/MQTTnet#323]
I tested MQTTnet in a large scale environment. 10000 datapoints with 1000 changes per second are distributed to 50 visualisation clients.

Unfortunately in my typical environment the topic hierarchy is quite flat. Every client has to subscribe approx 200 topics to optimize network traffic.

I measured that the performance bottleneck in this case is not the network but the topic matching logic on the server. 

Your topic matching implementation uses linear search per client. So every datapoint change requires 50 * 200 topic matchings. 

I was able to modify MQTTnet using topic dictionaries to improve topic matching dramatically.

And I took a look to other MQTT broker implementations like MOSQUITTO. They implemented some optimized topic matching using search trees.

I can imagine that most of the MQTTnet applications do not have such requirements. 

But when your intention is to implement a scaleable high perf mqtt broker you should also consider to optimize the topic matching algorithm, I think.

It would be great to support injection of other alternative matching algorithms.

What do you think ?

**Comment by chkr1011** [comment]
Which version did you use for this? Version 2.8.0 has lots of improvements. One is the rewrite of the topic matching code.

**Comment by ChristianRiedl** [comment]
Yes I used latest version.  Optimization of **TopicFilterComparer** cannot help in this case. Problem is the linear search per client and per subscribed topic.

**Comment by SeppPenner** [comment]
@chkr1011 Is this something that is still relevant?

**Comment by ChristianRiedl** [comment]
I have found an alternative solution

**Comment by iliDaedalus** [comment]
> I have found an alternative solution

Can you share with us?
Thank you in advance
