### ISSUE TITLE
build issues with 2.8.0 rc2

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#325]
new MqttFactory().CreateMqttClient(new MqttNetLogger(), new MqttClientConnectionContextFactory());

generates

error CS0012: The type 'IMqttClientAdapterFactory' is defined in an assembly that is not referenced. You must add a reference to assembly 'MQTTnet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by JanEggers** [comment]
nuget version seem correct but dlls are version 0.0.0.0 didnt figure ut why yet

**Comment by JanEggers** [comment]
there is still an issue....

![image](https://user-images.githubusercontent.com/6747376/41835398-b8baa7e4-7857-11e8-8511-25c02272589a.png)

**Comment by JanEggers** [comment]
// Assembly: MQTTnet.AspNetCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Assembly location: C:\Users\egja\.nuget\packages\mqttnet.aspnetcore\2.8.0-rc4\lib\netstandard2.0\MQTTnet.AspNetCore.dll

**Comment by JanEggers** [comment]
@chkr1011 can you please provide a new rc so i can verify its fixed?

**Comment by chkr1011** [comment]
@JanEggers Done. I will close this ticket hoping it is solved now 😄
