### ISSUE TITLE
Is it best practice to send messages in batch? Does this feature available?

### ISSUE THREAD

**Issue by isharehappycode** [chkr1011/MQTTnet#329]
I am sending 100's of messages and almost 3% messages fails due to connectivity issues. So do we have any option to send messages in batches?

**Comment by chkr1011** [comment]
Hi there is no "batch" sending at all. Messages in MQTT are transmitted in serial. Message after Message. But you can define a "batch" on your own, trying to send it and repeat it if one of the messages was not transmitted.
Best regards
Christian

**Comment by isharehappycode** [comment]
Thank you
