### ISSUE TITLE
WSS - Suppress certificate validation?

### ISSUE THREAD

**Issue by radekstepan85** [chkr1011/MQTTnet#332]
Is there a way to suppress the "The remote certificate is invalid according to the validation procedure. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel." exception?

My code snippet:

var brokerHostWithPort = "wss://host:port"

var options = new MqttClientOptionsBuilder()
.WithWebSocketServer(brokerHostWithPort)
 .WithTls(true, true, true, null)
.WithCredentials(userName, password)
.Build();

 await mqttClient.ConnectAsync(options);

Thank you,
Radek

**Comment by radekstepan85** [comment]
I used following to disable the validation...
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

**Comment by nesherhh** [comment]
This solution does not work in .NET Core.
