### ISSUE TITLE
'IManagedMqttClient' does not contain a definition for 'ConnectAsync' and no extension method 'ConnectAsync' accepting a first argument of type 'IManagedMqttClient' could be found

### ISSUE THREAD

**Issue by deepakkumpala** [chkr1011/MQTTnet#336]
I am trying to check the connection before sending message, But I get below error

'IManagedMqttClient' does not contain a definition for 'ConnectAsync' and no extension method 'ConnectAsync' accepting a first argument of type 'IManagedMqttClient' could be found (are you missing a using directive or an assembly reference?)	

Code

               using (var mqttClient = mqttFactory.CreateManagedMqttClient())
               {
                 try
                 {

                    var options = BuildMqttClientOptions(connectivityInfo);
                    var connectResult = await mqttClient.ConnectAsync(options);
                 }
               }

**Comment by isharehappycode** [comment]
But IsConnected will be true only after connecting right?

**Comment by chkr1011** [comment]
Yes it is only true if the connection is established. 
No the factory creates only a new instance which does nothing. After the start method has been called the client will connect internally.

**Comment by isharehappycode** [comment]
Actually my client app want to check periodically the connection stability. So as per your comment , the only way is to check the connectivity is to send/ping TEST messages?

**Comment by chkr1011** [comment]
The property will be updated as soon as the client detects a closed or broken connection. A clean close or disconnect from the client machine will be detected very fast.

But for other crashes at the server etc. messages must be sent. Please have a look at the "KeepAlive" settings for MQTT clients. Then messages like the one you mentioned are sent automatically.
