### ISSUE TITLE
How can I verify messages are secured while sending to Azure cloud?

### ISSUE THREAD

**Issue by isharehappycode** [chkr1011/MQTTnet#337]
Team,

I am using MQTTNet for sending sensor data to the azure cloud. I would like to do penetration test/security testing. What are the options I have got? What protocols I have to trace? Is it possible by Fiddler or do I need WireShark?

**Comment by chkr1011** [comment]
You can verify the MQTTnet trace and use Wireshark for message inspection.

**Comment by isharehappycode** [comment]
Thank you chkr011
