### ISSUE TITLE
Implement ServiceCollectionExtensions.AddHostedMqttServer<TService>(this IServiceCollection services) to make the IMqttServerOptions injectable

### ISSUE THREAD

**Issue by liuhongbo** [chkr1011/MQTTnet#338]
curently, when use the asp.net core library, normally do following:

```
public void ConfigureServices(IServiceCollection services)
{
     var mqttServerOptions = new MqttServerOptionsBuilder().Build();
     services.AddHostedMqttServer(mqttServerOptions);
}
```

the mqttServerOptions will passed in as an instance and registered with DI container. Then resolved with MqttHostedServer as IMqttServerOptions.

If I want to make the IMqttServerOptions itself injectable, for example, IMqttServerOptions might depends on some settings and neededs to resolve the IOptions<> which might not be availabe at the ConfigureServices. Even though can find some work around. I thhink it would be better to add an extra extention method like this:

```
public static IServiceCollection AddHostedMqttServer<TService>(this IServiceCollection services) where TService: class, IMqttServerOptions
{          
    services.AddSingleton<IMqttServerOptions,TService>();
    services.AddSingleton<IMqttNetLogger>(new MqttNetLogger());
    services.AddSingleton<MqttHostedServer>();
    services.AddSingleton<IHostedService>(s => s.GetService<MqttHostedServer>());
    services.AddSingleton<IMqttServer>(s => s.GetService<MqttHostedServer>());
    services.AddSingleton<MqttWebSocketServerAdapter>();
    services.AddSingleton<MqttTcpServerAdapter>();
    services.AddSingleton<IMqttServerAdapter>(s => s.GetService<MqttWebSocketServerAdapter>());
    services.AddSingleton<IMqttServerAdapter>(s => s.GetService<MqttTcpServerAdapter>());
    return services;
}
```

Then I can have a class implement IMqttServerOptions:

 ```
public class MyMqttServerOptions : IMqttServerOptions
    {
	public MyMqttServerOptions(IOptions<MyMqttServerSettings> options)
	{
		....
	}
...
}

```

In the ConfigureServices

```
public void ConfigureServices(IServiceCollection services)
{
     ...
     services.AddHostedMqttServer<MyMqttServerOptions>();
}

```

**Comment by JanEggers** [comment]
yup I agree I will create a pr and improve factoring of the extensions. there where some issues regarding how to enable tcp or websockets so i think ill make that more obvious aswell.

**Comment by JanEggers** [comment]
the changes you requested are merged into dev, so ill close this.
