### ISSUE TITLE
PublishAsync does not fail when server is not running!

### ISSUE THREAD

**Issue by isharehappycode** [chkr1011/MQTTnet#345]
I have below code to publish messages to MQTT server. I am using managed MQTT Client.

            var messagePayload = new MqttApplicationMessageBuilder()
                                              .WithTopic("Topic1")
                                              .WithPayload(message)
                                              .WithExactlyOnceQoS()
                                              .WithRetainFlag()
                                              .Build();

            try
            {
                  await mqttClient.PublishAsync(messagePayload);                  
            }
            catch (Exception ex)
            {
                 //Why I am not getting exception? 
            }

Note: I get exception when I use un-managed client.

By the way, How do I add labels to these type of questions?

**Comment by chkr1011** [comment]
You can add the label "help wanted" (right sidebar).

The managed client will not fail because it has an internal queue. All messages are only added to the queue and stored (if storage implemented in options). If you have to react to the failed messages you can use the _ApplicationMessageProcessed_ event.

**Comment by isharehappycode** [comment]
What is the size of this internal queue? This internal queue is only available in manged client or normal client too ?

**Comment by isharehappycode** [comment]
ApplicationMessageProcessed is not triggering. I have subscribed to same topic where message is published.

**Comment by isharehappycode** [comment]
ApplicationMessageProcessed  is not firing. I have updated the question
