### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by L3viAckerman** [chkr1011/MQTTnet#352]
I read your wiki and try to create MqttServer on my app ASP.NET Core 2.1 but I have some problems. I use your source code in wiki for configure my app and I have an exception when I build my project. This is my screenshot
https://drive.google.com/file/d/1-uh3C1KO3jng0eirfQQT8sfXi0BS3kkp/view?usp=sharing. Can you help me resolve this issue. And after add MqttServer on my project, I dont know using EventHandle. Please help me. 
Sorry for my bad English and thank you very much!

**Comment by L3viAckerman** [comment]
Thank you for your help.
I have added MQTTserver in my app using asp.net core 2.1. I can run it in localhost but when I deploy on IIS, my mqttClient cant connect my app. I dont know how to config in IIS.
Thank you!

**Comment by JanEggers** [comment]
what errors are you getting? I didnt set this up myself. did you install / enable websockets in iis?
 https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support

**Comment by L3viAckerman** [comment]
Thank you for your help. I try to config lIS like you suggest but my client cant connect to my server. I think I open port 443 in IIS but MQTTServer is configed port 1883. So should I config my mqttServer run on port 443 or try open port 1883 in IIS? Can you give me some advise? 
Thank you!
