### ISSUE TITLE
MqttClientKeepAliveMonitor using to much CPU time

### ISSUE THREAD

**Issue by GarageGadget** [chkr1011/MQTTnet#356]
Hi,

I have been conducting a quick load test with 2000 Clients sessions to the Broker. 
I profiled the code using the VS2017 Profiler (CPU Mode) and found that the report revealed MqttClientKeepAliveMonitor is using 53% of the CPU time.

A closer look at the code reveals that the task is being scheduled every 15ms resulting in many tasks being scheduled. I changed the code to decrease the frequency of the task. 

Re-running the test and profiling the code proved that the change removed the MqttClientKeepAliveMonitor event as a Top consumer of CPU. 

BR,

**Comment by chkr1011** [comment]
Hi,
thank you for reporting this issue. You are right. I found the problem. The delay requries milliseconds but the keel alive interval for MQTT is specified in seconds so a keep alive of 15 seconds will let the thread sleep 15 milliseconds. 

I will fix this with 2.8.1.

Best regards
Christian

**Comment by GarageGadget** [comment]
Hi Christian,

Thanks for the feedback and fix.

You may consider dedicating (1 or more) thread(s) or long running task(s) to perform the Keep Alive Monitoring of the sessions. This will reducing the number of tasks being scheduled.

BR,
Brent

**Comment by chkr1011** [comment]
Yes I agree. This is maybe a better solution but I will not implement this for 2.8.x. I will add this to the list for 2.9.x.
