### ISSUE TITLE
Performance Observations

### ISSUE THREAD

**Issue by GarageGadget** [chkr1011/MQTTnet#357]
Hi,
I have been conducting performance and resilience testing to determine how the Broker performs under various real world scenarios.

**Observations:**

_Scenario 1 - Flash Crowd - Large number of incoming connections (2000)._ 
The AcceptClientConnectionsAsync() is a hot spot as incoming connections must be accepted at a high rate. 
The performance can be improved by removing the __logger_.

_Scenario 2 - Crowd Disconnection - Large number of disconnections (1000)_
The Disconnect operation is expensive causing the CPU to hit 100% for a long period.

_Scenario 3 - This is a combination of Scenario 1 & 2 followed by Scenario 1 with half number (1000) the new connections._

The Disconnection operation from Scenario 2 appears to prevent incoming connections to be readily accepted.

**Comment by JanEggers** [comment]
can you also try the aspnetcore 2.1 adapter? it relies on kestrel network stack so it should be more robust

**Comment by chkr1011** [comment]
Hi,
thank you for providing the measurement results.

Scenario 1: I changed the generation of the log message to string.Format instead of string interpolation. With a disabled logger the performance should be better now (in dev branch).

Do you have some more details for Scenatio 2?

Best regards
Christian

**Comment by JanEggers** [comment]
@chkr1011 regarding scenario 2 currently there is use of exceptions to cancel a session and the associated tasks, if there are a bunch of connections that generates the cpu load. Im just not shure how to handle that instead...

**Comment by JanEggers** [comment]
I think it would be best to create a benchmark for the case described by op and then optimize, maybe there are other issues we did not think of yet

**Comment by GarageGadget** [comment]
Hi,

Thanks for your feedback. I have some suggestions that should improve performance.

At the moment the Broker is relying on the OS and .NET to manage performance and reliability.

In order to manage the performance and reliability it would be important to divide the Broker up into areas of responsibility and to provide settings to control the behaviour of the areas.

The Broker can be divided up into different areas of responsibilities:-

Listener - Accepting new connections
Transmitter - Sending of messages to clients
Receiver - Handling incoming messages from the client
Disconnections - Handling of client disconnecting or aborting.

Log Writer - Publishing of logs
Health - Monitors the other sections and manages each sections.

Each area can be run as dedicated named thread controlled by settings e.g. Listener is a dedicated task, the Log writer another etc.

To achieve a balance between performance and reliability it is important to assign priorities to each responsibility.

For example maintaining existing sessions has a higher priority than accepting new connections and disconnecting sessions has the lowest priority of the afore mentioned.

The Logger can have a dedicated thread responsible for processing a Log Writer queue which is fed by the Logger.

The Health Monitor thread can be used manage the other threads like throttling back accepting new connections when under heavy load.

By taking control the threading and having settings to configure the Broker the CPU cores can be managed and not overloaded when subjected to the scenarios I reported. 
Remember to reserve +-30% CPU for the OS and .NET GC i.e. use only 7 of 8 Cpu cores at any time.

**Comment by SeppPenner** [comment]
Is this still relevant?

**Comment by JanEggers** [comment]
no, in case @GarageGadget want to provide a pr with changes im happy to review but for now ill close the issue
