### ISSUE TITLE
Update Nuget packages error

### ISSUE THREAD

**Issue by colongj** [chkr1011/MQTTnet#360]
Hi,
     When I try to build the whole project, i need to update and restore Nuget packages first. When i update Nuget packages, out came the following error:
     Package Microsoft.NETCore.UniversalWindowsPlatform 6.1.5 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.NETCore.UniversalWindowsPlatform 6.1.5 supports:
  - netcore50 (.NETCore,Version=v5.0)
  - uap10.0.15138 (UAP,Version=v10.0.15138)

    Does it mean that i should install .NETCore 5.0 first?

**Comment by JanEggers** [comment]
just restore nugets and dont update em an you will be fine
