### ISSUE TITLE
Behavior of MqttApplicationMessageInterceptorContext.AcceptPublish = false

### ISSUE THREAD

**Issue by alamsor** [chkr1011/MQTTnet#371]
Hi Christian,
I have a requirement in the mqtt server to oversee all messages being published and reject certain messages so they don't get forwarded to subscribers.
To implement this feature, I am using the **ApplicationMessageInterceptor** callback in MqttServerOptions with the MqttApplicationMessageInterceptorContext.**AcceptPublish** property.

To reject the message, I set context.AcceptPublish=false inside ApplicationMessageInterceptor callback.
However, after my app executes this line, I noticed the ApplicationMessageInterceptor callback no longer gets triggered while my clients are still publishing messages.

I traced the code to MqttClientSessionsManager.**ProcessQueuedApplicationMessages** and discovered the following condition:
```
if (interceptorContext.ApplicationMessage == null || !interceptorContext.AcceptPublish)
{
    return;
}
```
Apparently, if AcceptPublish=false, the server will exit the loop that processes the messages being published by the clients.  As a result, all subsequent messages are stuck in the queue and don't get forwarded to subscribers.

Is this the intended behavior or am I using this property incorrectly?
I would like all subsequent messages to continue being sent even after one is rejected.
 
Thanks in advance!

**Comment by chkr1011** [comment]
Hi @alamsor,
Thank you for reporting this issue. You are right. This is wrong and must be changed. I will fix this and release a new version soon.

Best regards
Christian

**Comment by chkr1011** [comment]
This is fixed. It it still happens please let me know.
