### ISSUE TITLE
Wrong order of ClientConnected and ClientDisconnected when same clients reconnect after crash/lost connection

### ISSUE THREAD

**Issue by jenscski** [chkr1011/MQTTnet#373]
When testing with a NodeMCU board as a Mqtt-client, i noticed that the order of the ClientConnected and ClientDisconnected was wrong when the NodeMCU board was reset while connected to the server, and the NodeMCU reconnected before the keepalivemonitor was triggered to close the session. Then the ClientConnected was triggered before ClientDisconnected.

```
[TestMethod]
public async Task MqttServer_SameClientIdConnectDisconnectEventOrder()
{
    var serverAdapter = new MqttTcpServerAdapter(new MqttNetLogger().CreateChildLogger());
    var s = new MqttFactory().CreateMqttServer(new[] { serverAdapter }, new MqttNetLogger());

    var connectedClient = false;
    var connecteCalledBeforeConnectedClients = false;

    s.ClientConnected += (_, __) =>
    {
        connecteCalledBeforeConnectedClients |= connectedClient;
        connectedClient = true;
    };

    s.ClientDisconnected += (_, __) =>
    {
        connectedClient = false;
    };

    var clientOptions = new MqttClientOptionsBuilder()
        .WithTcpServer("localhost")
        .WithClientId(Guid.NewGuid().ToString())
        .Build();

    await s.StartAsync(new MqttServerOptions());

    var c1 = new MqttFactory().CreateMqttClient();
    var c2 = new MqttFactory().CreateMqttClient();

    await c1.ConnectAsync(clientOptions);

    await Task.Delay(100);

    await c2.ConnectAsync(clientOptions);

    await Task.Delay(100);

    await c1.DisconnectAsync();
    await c2.DisconnectAsync();

    await s.StopAsync();

    await Task.Delay(100);

    Assert.IsFalse(connecteCalledBeforeConnectedClients, "ClientConnected was called before ClientDisconnect was called");
}

**Comment by chkr1011** [comment]
I am not sure if this order is "wrong". In your unit test you are replacing the existing session (adapter) and this means that the new session has to connect first and THEN the old one is being disconnected.

From my perspective I would say that it is OK. Do you have a use case where the order of the events must be different?

**Comment by jenscski** [comment]
I don't have a use case yet, but what if the code is relying on ClientConnected and ClientDisconnected, if the events are delivered in the current order, isn't it impossible to know if a session was connected or not? You would get a Disconnect of the old session after the new one was connected. It's not possible to tell which client which was diconnected.

**Comment by chkr1011** [comment]
I was able to change the order without much effort. I will write some futher Unit Tests for event processing.
