### ISSUE TITLE
Server does not accept clients connections outside the same code (i.e. not coded in its app)

### ISSUE THREAD

**Issue by juspolo** [chkr1011/MQTTnet#375]
I am definitely missing something! I hope that someone could point me in the right direction.

I am using MQTTnet* [v2.8.1](https://www.nuget.org/packages/MQTTnet/) and I am experiencing these scenarios:
- MQTTnet server does not accept connections from clients outside its source;
- connections and messages from clients of the same source code work without any issue;
- connections and messages from clients to an external broker work without any issue (i.e. clients based on MQTTnet and not);

For example:
- using [MQTTnet.TestApp.UniversalWindows](https://github.com/chkr1011/MQTTnet/tree/master/Tests/MQTTnet.TestApp.UniversalWindows) example to start a server (i.e. based on MQTTnet) and connect from a client of the same project, works like a charm;
- use MQTTnet.TestApp.UniversalWindows example to start a server and connect from a MQTT.fx client, MQTT.fx client timeouts;
- use MQTTnet.TestApp.UniversalWindows example to start a server and connect from a client of another solution still based on MQTTnet (i.e. my own code), client timeouts;
- use/start an external server (i.e. HiveMQ, my own code based on GnatMQ, etc.) and connect from clients based on MQTTnet and not, works like a charm.

The code of my own is based on MQTTnet.TestApp.UniversalWindows example and from wiki; specifically, server implementation is based on StartServer method from [MainPage.xaml.cs](https://github.com/chkr1011/MQTTnet/blob/master/Tests/MQTTnet.TestApp.UniversalWindows/MainPage.xaml.cs).

Can someone point me in the right direction, please?

All the best.

**Comment by jenscski** [comment]
UWP apps is running with network isolation, so it's no possible to run a local server on UWP.

For testing purspose, you can open up the network isolation. Read https://msdn.microsoft.com/en-us/library/windows/apps/hh780593#enable_loopback_for_network_access

**Comment by juspolo** [comment]
Lovely, thank you! I did not know that.

I am struggling to exempt the example from network isolation... so far, I did not success.
I tried both editing the manifest and adding exempt rules.

**Comment by chkr1011** [comment]
I had the same issues. I was not able to solve it. I followed lots of tutorials and added custom rules etc. but it never worked. Some day I realized that I had to stop the Windows Firewall service on the local machine. But when disabled a deployment is not possible anymore. So I had to turn it on and off a lot of times. But I don't know if this hack still works.

This was one reason for me to use .net core and linux.

**Comment by juspolo** [comment]
Ouch! Thank you for sharing your experience with me.

I was hoping to find that I was missing something, but now it seems to me that there are some headaches with UWP.

I found that the apps result as exempted from network isolation, but I did not success; I also tried to disable Windows Firewall service as you suggested, but still no success.

Did you have any experience with UWP and Win IoT?
