### ISSUE TITLE
Windows 7 / net fw 4.6 asyncconnect throws: Could not load file or assembly 'System.Net.Sockets

### ISSUE THREAD

**Issue by pierreSLA** [chkr1011/MQTTnet#378]
Hi.
We built an app with multiple "plugins" which communicate with each other through a windows service.
All projects target framework 4.62. Now if i run it on a windows 7 i get 
"""
Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
"""
although all libraries from the plugin output directory are deployed into same directory.
what can i do else?
please help.

**Comment by miladghasemi** [comment]
hello, 

I exactly had the same problem. By doing the following items, it works fine

1. install .NetFarmework 4.7.1

1.  clean Project

1. build Project

**Comment by rapmue** [comment]
@pierreSLA I noticed the exact same thing, but with targeting 4.6.1...
@miladghasemi I don't think that your fix should be applied. The system requirements states: 

> Minimum required .NET Framework 4.5.2+ (x86, x64, AnyCPU)

Therefor we should search the wrong reference in this project.
