### ISSUE TITLE
Many Dll in bin folder

### ISSUE THREAD

**Issue by DoneByGj** [chkr1011/MQTTnet#380]
Since V2.8.0, there are 94 System dlls that are added to the bin/debug folder of all projects.
Is it really necessary?

**Comment by chkr1011** [comment]
Which bin folder do you mean? I have 3- 9 files in all bin directories.

**Comment by JTrotta** [comment]
@DoneByGj sometimes it happens to me with other projects, but not this one. 
IMHO it depends on any single PC .NET configuration, but I never find out a solution.

**Comment by DoneByGj** [comment]
If I create a new WPF project (framework 4.6.1) with only mqttnet nuget package version 2.8.1, I get all these files in the output folder : 
They weren't there with the previous version. 

C:\...\TestMqtt\TestMqtt\bin\Debug
MQTTnet.dll                                     System.Net.WebHeaderCollection.dll
Microsoft.Win32.Primitives.dll                  System.Net.WebSockets.Client.dll
System.AppContext.dll                           System.Net.WebSockets.dll
System.Collections.Concurrent.dll               System.ObjectModel.dll
System.Collections.NonGeneric.dll               System.Reflection.Extensions.dll
System.Collections.Specialized.dll              System.Reflection.Primitives.dll
System.Collections.dll                          System.Reflection.dll
System.ComponentModel.EventBasedAsync.dll       System.Resources.Reader.dll
System.ComponentModel.Primitives.dll            System.Resources.ResourceManager.dll
System.ComponentModel.TypeConverter.dll         System.Resources.Writer.dll
System.ComponentModel.dll                       System.Runtime.CompilerServices.VisualC.dll
System.Console.dll                              System.Runtime.Extensions.dll
System.Data.Common.dll                          System.Runtime.Handles.dll
System.Diagnostics.Contracts.dll                System.Runtime.InteropServices.RuntimeInformation.dll
System.Diagnostics.Debug.dll                    System.Runtime.InteropServices.dll
System.Diagnostics.FileVersionInfo.dll          System.Runtime.Numerics.dll
System.Diagnostics.Process.dll                  System.Runtime.Serialization.Formatters.dll
System.Diagnostics.StackTrace.dll               System.Runtime.Serialization.Json.dll
System.Diagnostics.TextWriterTraceListener.dll  System.Runtime.Serialization.Primitives.dll
System.Diagnostics.Tools.dll                    System.Runtime.Serialization.Xml.dll
System.Diagnostics.TraceSource.dll              System.Runtime.dll
System.Diagnostics.Tracing.dll                  System.Security.Claims.dll
System.Drawing.Primitives.dll                   System.Security.Cryptography.Algorithms.dll
System.Dynamic.Runtime.dll                      System.Security.Cryptography.Csp.dll
System.Globalization.Calendars.dll              System.Security.Cryptography.Encoding.dll
System.Globalization.Extensions.dll             System.Security.Cryptography.Primitives.dll
System.Globalization.dll                        System.Security.Cryptography.X509Certificates.dll
System.IO.Compression.ZipFile.dll               System.Security.Principal.dll
System.IO.Compression.dll                       System.Security.SecureString.dll
System.IO.FileSystem.DriveInfo.dll              System.Text.Encoding.Extensions.dll
System.IO.FileSystem.Primitives.dll             System.Text.Encoding.dll
System.IO.FileSystem.Watcher.dll                System.Text.RegularExpressions.dll
System.IO.FileSystem.dll                        System.Threading.Overlapped.dll
System.IO.IsolatedStorage.dll                   System.Threading.Tasks.Parallel.dll
System.IO.MemoryMappedFiles.dll                 System.Threading.Tasks.dll
System.IO.Pipes.dll                             System.Threading.Thread.dll
System.IO.UnmanagedMemoryStream.dll             System.Threading.ThreadPool.dll
System.IO.dll                                   System.Threading.Timer.dll
System.Linq.Expressions.dll                     System.Threading.dll
System.Linq.Parallel.dll                        System.ValueTuple.dll
System.Linq.Queryable.dll                       System.Xml.ReaderWriter.dll
System.Linq.dll                                 System.Xml.XDocument.dll
System.Net.Http.dll                             System.Xml.XPath.XDocument.dll
System.Net.NameResolution.dll                   System.Xml.XPath.dll
System.Net.NetworkInformation.dll               System.Xml.XmlDocument.dll
System.Net.Ping.dll                             System.Xml.XmlSerializer.dll
System.Net.Primitives.dll                       TestMqtt.exe
System.Net.Requests.dll                         TestMqtt.exe.config
System.Net.Security.dll                         TestMqtt.pdb
System.Net.Sockets.dll                          netstandard.dll

**Comment by JanEggers** [comment]
that is a dotnet issue

https://github.com/dotnet/standard/issues/415#issuecomment-314288712

**Comment by JanEggers** [comment]
I knew I did some poking with this. here is the original issue I posted as we discovered this issue:

https://github.com/dotnet/standard/issues/580
