### ISSUE TITLE
Keep alive issue

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#381]
Hi there using 2.8.1 im having weird keepalive issues. 

the keepalive monitor ends the session 3 seconds after it was established but the keepalive is 15 sec.  and im getting 5000 msgs in that 3 seconds anyway so it should not be detected as idle anyway....

edit: im not shure if this is related to the server shutdown not terminating the connection in a clean way so a preview build would be really helpful.

**Comment by chkr1011** [comment]
There is a fix in 2.8.2. The pause and resume logic was wrong.

**Comment by JanEggers** [comment]
thx
