### ISSUE TITLE
Managed client doesn't reconnect when WiFi connection is re-established

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#383]
I only started using MQTTnet yesterday, so I may be misunderstanding how the managed client is meant to deal with connection loss.  I've set up separate publisher and subscriber clients, both talking to test.mosquitto.org.  The publisher publishes a message with an ascending ID on a timer every five seconds.  In order to test that the automatic reconnect and offline message retention features work, I disconnect my WiFi adapter from my home network for a few seconds, and then reconnect it.

**What I expect to see**:  When I disconnect my WiFi, I expect the Disconnected event to fire and messages to stop transmitting to the broker.  When I reconnect my WiFi, I expect the Connected event to fire, all messages published while offline to be read from disk (using the IManagedMqttClientStorage implementation found in ManagedClientTest.cs) and transmitted to the broker, and for all subsequent published messages on the aforementioned timer to transmit to the broker.

**What actually happens**:  Neither the Disconnected event nor the Connected event fires when WiFi is disconnected/reconnected, and no published messages (from either disk or the timer event) are transmitted to the broker once WiFi is reconnected.  The only way I can get it working again is to close the publisher application entirely and restart it.

I've attached a trace file showing that when WiFi reconnects, I get hundreds of MqttCommunicationExceptions in rapid succession.
[Log.txt](https://github.com/chkr1011/MQTTnet/files/2250818/Log.txt)

**Comment by laarlinn** [comment]
Haha, I meant 2.8.2-rc1*  :)

**Comment by PaulFake** [comment]
Oh, cool.  I'll give it a shot.  Thanks.

**Comment by PaulFake** [comment]
That worked!  It behaves exactly as I'd expect now.  Thank you.
