### ISSUE TITLE
Unhandled exception while processing queued application message

### ISSUE THREAD

**Issue by Gonzo4** [chkr1011/MQTTnet#385]
Hi,

I get sometimes the exception _Unhandled exception while processing queued application message_ after calling  StopAsync. I'm using the Net4.6.1 Build...
I've tried to attach your source to my project, but I had no success to build it, hopefully the following information will help you:

**Message:**
Der Wert darf nicht NULL sein.

**StackTracke:**
   bei System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   bei System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   bei MQTTnet.Server.MqttClientSessionsManager.ProcessQueuedApplicationMessages(CancellationToken cancellationToken)

**Comment by chkr1011** [comment]
Please reopen this ticket if the error still occurs in version 3.0.0.
