### ISSUE TITLE
The IMqttClientFactory does not have all the overloading methods for CreateMqttClient

### ISSUE THREAD

**Issue by sheepinwild** [chkr1011/MQTTnet#394]
I'm trying to do unit testing and this interface is missing

public IMqttClient CreateMqttClient(IMqttNetLogger logger, IMqttClientAdapterFactory adapterFactory)

kind of stuck for this...

**Comment by chkr1011** [comment]
Hi, 
yes you are right. They are missing. I add all missing methods to the interfaces (also server).
Best regards
Christian

**Comment by sheepinwild** [comment]
Thanks... I created a wrapper in the meantime to get around it. but would be good to have them in that interface.
