### ISSUE TITLE
Managed client new will message on reconnect?

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#395]
I need to implement the MQTT Sparkplug spec, which requires that each connect message includes an incrementing sequence number.  I'd like to use the managed client for this, but it seems like I can only specify a will message (which will include the sequence number) on the initial connect, and each automatic reconnect will send the same will message.  Before I go implementing my own managed client (sigh), is there a way to do this with the existing managed client that I'm not seeing?

**Comment by chkr1011** [comment]
Hi,
I am wondering why you want to access the sequence number!? The sequence number is set on MQTT level by the library automatically and respected when waiting for responses etc.

Best regards
Christian Kratky

**Comment by PaulFake** [comment]
It's possible I'm misunderstanding something, but what I think I understand is that the Sparkplug specification requires that a "bdSeq" (birth-death sequence) metric is included as part of the payload of a will upon connecting.  After connecting, Sparkplug requires that an "NBIRTH" message is sent, which should include the same bdSeq number used when connecting, so that the backend can correlate node births and deaths.  So, each time the connection is lost and re-established, I would need to increment the bdSeq number and send a new will, then send a new NBIRTH message with the same bdSeq.

That's different from the sequence number you're talking about, right?  I'm pretty sure bdSeq is unique to the Sparkplug spec.

**Comment by PaulFake** [comment]
There's a more detailed explanation of the NBIRTH message payload on page 58.  It says:

"A bdSeq number as a metric should be included in the payload [of the NBIRTH message]. This should match the bdSeq number provided in the MQTT CONNECT packet’s LW&T payload. This allows backend applications to correlate NBIRTHs to NDEATHs. The bdSeq number should start at zero and increment by one on every new MQTT CONNECT."

So I believe that I need to supply a new bdSeq number in the will (LW&T) payload every time a reconnect occurs, and then send that same bdSeq number with in the payload of the NBIRTH message.  My understanding of the ManagedMqttClient is that the will payload is set only on StartAsync and can't be changed on reconnect.

**Comment by PaulFake** [comment]
Well, I came up with a way to do it without implementing my own managed client, and it *seems* to work.  I'll have to give it some more thought in terms of thread safety, but the general idea is:

1) Application keeps a bdSeq variable
2) Application sets the will message in the client options with the initialized bdSeq (zero)
3) Application handles the managed client's OnConnected event
4) When OnConnected is triggered, publish NBIRTH with bdSeq, increment bdSeq, and then set a new will message in the client options with the new bdSeq

Simpler than I thought it would be at first, assuming it's safe.  The trick was setting the bdSeq and will message for the next time it reconnects rather than trying to intercept the reconnect when it happens.  Anyways, cool library!  The managed client really saves our enterprise a lot of development time.
