### ISSUE TITLE
Why do I receive messages from my server?

### ISSUE THREAD

**Issue by bbhxwl** [chkr1011/MQTTnet#397]
My server executes mqttServer. PublishAsync (new MqttApplicationMessageBuilder (). WithTopic (txtTopic. Text. Trim ()). WithPayload (txtMsg. Text. Trim ()). Build ()).

Why do we enter the MqttServer_ApplicationMessageReceived incident?

**Comment by chkr1011** [comment]
Hi, 
because it is fired for _all_ published messages. No matter if they are coming from clients or server.
If you need to distinguish you can check the ClientId property which is not set for server side published messages.

Best regards
Christian
