### ISSUE TITLE
XmlDoc would be very beneficial

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#398]
For someone new to using MQTTNet, it would be grand to be able to have XmlDoc on the API to better guide how to use the api/library.

**Comment by chkr1011** [comment]
Hi,
this is possible indeed but has lowest priority at the moment. Most parts of the SDK are self describing and the Wiki provides additional information. I aggree that there are some places and methods which need some docs but I don't want to add meaningless comments (like the ones generated with ghost doc).
Best regards
Christian

**Comment by dealproc** [comment]
"Meaningless" comments, I'll agree on.. but for anyone that is trying to adopt your framework, at least the API facades would be beneficial, even if they are meaningless to you, they may not be for others (such as myself).  I'm finding that I'm needing to read through the code to understand its intent, where I would rather have a simple blip to understand the focus/intent of the method/procedure/etc.
