### ISSUE TITLE
why MqttClient can not  FireApplicationMessageReceivedEvent when MqttQualityOfServiceLevel.AtLeastOnce?

### ISSUE THREAD

**Issue by zhaobaolong** [chkr1011/MQTTnet#4]
When MqttApplicationMessage.MqttQualityOfServiceLevel =  MqttQualityOfServiceLevel.AtLeastOnce that client  can not  FireApplicationMessageReceivedEvent,but MqttApplicationMessage.MqttQualityOfServiceLevel =  MqttQualityOfServiceLevel.AtMostOnce can FireApplicationMessageReceivedEvent ,why?

**Comment by chkr1011** [comment]
Hi,
to me this sounds like a bug. Can you give some more details about the server you use? And a little code snippet?

Best regards
Christian

**Comment by zhaobaolong** [comment]
I have a windows form ,have three buttons "StartServer" 、“StartClient” and “SendMessage”。
`   private MqttServer mqttServer = null;
     private MqttClient mqttClient = null;

   private void button_startServer_Click(object sender, EventArgs e)
        {
            MqttTrace.TraceMessagePublished += MqttTrace_TraceMessagePublished;
          if (this.mqttServer == null)
            {
                try
                {
                    var options = new MqttServerOptions
                    {
                        ConnectionValidator = p =>
                        {
                            if (p.ClientId == "SpecialClient")
                            {
                                if (p.Username != "USER" || p.Password != "PASS")
                                {
                                    return MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                                }
                            }

                            return MqttConnectReturnCode.ConnectionAccepted;
                        }
                    };

                    mqttServer = new MqttServerFactory().CreateMqttServer(options);

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                    return;

                }
            }
            mqttServer.Start();

            this.txt_服务器.AppendText( $">> 启动成功..." + Environment.NewLine);
        }

//StartClient
 private async void button_startClient_Click(object sender, EventArgs e)
        {
            if (this.mqttClient == null)
            {
                var options = new MqttClientOptions
                {
                    Server = "192.168.2.54",  --My Local Server
                    ClientId = "zbl",
                    CleanSession = true
                };
                this.mqttClient = new MqttClientFactory().CreateMqttClient(options);
                this.mqttClient.ApplicationMessageReceived += MqttClient_ApplicationMessageReceived;
                this.mqttClient.Connected += MqttClient_Connected;
                this.mqttClient.Disconnected += MqttClient_Disconnected;
            }
            try
            {
                await this.mqttClient.ConnectAsync();
            }
            catch(Exception ex)
            {
                this.txt_客户端.AppendText( $"### CONNECTING FAILED ###" + Environment.NewLine);
            }
        }

   private async void button_发送_Click(object sender, EventArgs e)
        {

            **//  this.mqttClient.ApplicationMessageReceived  can not fired**
            //var applicationMessage = new MqttApplicationMessage(this.txt_topic.Text,
            //  Encoding.UTF8.GetBytes(this.txt_message.Text), MqttQualityOfServiceLevel.AtLeastOnce, false);
            //await this.mqttClient.PublishAsync(applicationMessage); 

            **// this.mqttClient.ApplicationMessageReceived  can fired**
            var applicationMessage = new MqttApplicationMessage(this.txt_topic.Text,
                Encoding.UTF8.GetBytes(this.txt_message.Text), MqttQualityOfServiceLevel.AtMostOnce, false);
            await this.mqttClient.PublishAsync(applicationMessage);
        }
`
sorry, I upload source code got error:Something went really wrong, and we can’t process that file.

**Comment by ericwu** [comment]
private Task HandleIncomingPacketAsync(MqttBasePacket packet)
        {
......
            MqttTrace.Warning(nameof(MqttClientSession), $"Client '{_identifier}': Received not supported packet ({packet}). Closing connection.");
........

>> [25] [MqttClientSession] [Verbose]: Client '[::ffff:127.0.0.1]:61740: Enqueued pending publish packet.
>> [30] [MqttChannelCommunicationAdapter] [Information]: RX <<< MQTTnet.Core.Packets.MqttPubRecPacket
>> [30] [MqttClientSession] [Warning]: Client '[::ffff:127.0.0.1]:61740': Received not supported packet

**Comment by chkr1011** [comment]
This warning is coming if the packet type is invalid. This can happen if the data stream is aborted etc. Then the value is invalid. But this is only a warning.

I will test the the event and add it to the test app.

**Comment by chkr1011** [comment]
@zhaobaolong I tested it but cannot find any problems. The code you posted has several formatting errors.
