### ISSUE TITLE
always offline in .NET Framework 4.5.2+  when using websocket

### ISSUE THREAD

**Issue by mazhongbin** [chkr1011/MQTTnet#401]
Run about 90 second, it will be offline in .net framework 4.5.2 project. (using websocket)

**Comment by SeppPenner** [comment]
Which version is concerned, do you have some snippets for us and does this still happen in the latest version?

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.
