### ISSUE TITLE
mqttClient  - TargetInvocationException thrown when server not available

### ISSUE THREAD

**Issue by gismofx** [chkr1011/MQTTnet#405]
I'm writing a simple windows form client. When the server is available I have no issues so far, but when testing a connection when the server is not available, I've implemented the "Disconnected" event in mqttClient and I show a message box that connection to server has failed. After than, I receive a "Target Invocation Exception" and the debugger is as this line:

> ************** Exception Text **************
> System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it [::ffff:127.0.0.1]:1883
>    at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MQTTnet.Internal.TaskExtensions.<TimeoutAfterAsync>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__20.MoveNext()
> 

```
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1()); //DEBUGGER HERE
        }
    }
```

**Comment by chkr1011** [comment]
Hi, please post the full code. Probably there is an issue with async/await usage.
Best regards
Christian

**Comment by gismofx** [comment]
Hi Christian,

I've create a simplified project which exhibits the issue. Run the project with debugger and press the connect button. Ensure no server is running. You should get the debugger error.

[MQTT Client.zip](https://github.com/chkr1011/MQTTnet/files/2349653/MQTT.Client.zip)
