### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by JTrotta** [chkr1011/MQTTnet#406]
I'm using MQTT Managed client. Sometimes the connection, even if established is lost, and the system does not reconnect automatically anymore, using managed client auto reconnect feature. Find below the mqtt trace log.
Any hints?

2018/08/31 12:14:45.073|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:45.0728710Z] [26] [MqttClient] [Verbose]: Trying to connect with server (192.168.0.20:8883).
2018/08/31 12:14:46.476|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:46.4764600Z] [26] [MqttClient.MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:20]
2018/08/31 12:14:48.108|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:48.1081180Z] [24] [MqttClient] [Verbose]: Connection with server established.
2018/08/31 12:14:49.811|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:49.8111160Z] [24] [MqttClient] [Verbose]: Start receiving packets.
2018/08/31 12:14:49.811|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:49.8117610Z] [26] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=865234030021165] [Username=lobu] [Password=674627090578563365] [KeepAlivePeriod=31] [CleanSession=True]
2018/08/31 12:14:50.427|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.4275860Z] [24] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=False]
2018/08/31 12:14:50.454|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.4544640Z] [28] [MqttClient] [Verbose]: MQTT connection with server established.
2018/08/31 12:14:50.489|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.4896670Z] [27] [MqttClient] [Verbose]: Start sending keep alive packets.
2018/08/31 12:14:50.547|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.5468890Z] [28] [MqttClient] [Info]: Connected.
2018/08/31 12:14:50.569|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.5688380Z] [28] [ManagedMqttClient] [Info]: ManagedMqttClient
2018/08/31 12:14:50.618|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.6184320Z] [26] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Subscribe: [PacketIdentifier=1] [TopicFilters=message@ExactlyOnce,message/865234030021165@ExactlyOnce,message/@ExactlyOnce]
2018/08/31 12:14:50.822|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.8222110Z] [29] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< SubAck: [PacketIdentifier=1] [SubscribeReturnCodes=SuccessMaximumQoS2,SuccessMaximumQoS2,SuccessMaximumQoS2]
2018/08/31 12:14:50.877|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:50.8775490Z] [25] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=ennio/main] [Payload.Length=397] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=2]
2018/08/31 12:14:51.227|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:51.2272000Z] [28] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubRec
2018/08/31 12:14:51.245|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:51.2452090Z] [27] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> PubRel
2018/08/31 12:14:51.450|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:51.4494640Z] [27] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubComp
2018/08/31 12:14:51.493|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:51.4936010Z] [29] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=ennio/main] [Payload.Length=418] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=3]
2018/08/31 12:14:51.766|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:51.7666220Z] [26] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubRec
2018/08/31 12:14:51.794|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:51.7941600Z] [24] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> PubRel
2018/08/31 12:14:51.987|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:51.9872740Z] [26] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubComp
2018/08/31 12:14:52.019|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.0193480Z] [28] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=ennio/main] [Payload.Length=424] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=4]
2018/08/31 12:14:52.337|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.3373820Z] [24] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubRec
2018/08/31 12:14:52.354|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.3540550Z] [26] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> PubRel
2018/08/31 12:14:52.148|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.1486960Z] [29] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubComp
2018/08/31 12:14:52.167|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.1672120Z] [27] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=ennio/main] [Payload.Length=424] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=5]
2018/08/31 12:14:52.388|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.3882530Z] [24] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubRec
2018/08/31 12:14:52.402|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.4027640Z] [26] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> PubRel
2018/08/31 12:14:52.588|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.5880170Z] [29] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubComp
2018/08/31 12:14:52.690|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.6917720Z] [25] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=ennio/main] [Payload.Length=377] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=6]
2018/08/31 12:14:52.887|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.8872350Z] [29] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubRec
2018/08/31 12:14:52.902|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:52.9023520Z] [25] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> PubRel
2018/08/31 12:14:53.093|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:14:53.0934410Z] [28] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubComp
2018/08/31 12:15:16.156|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:16.1562230Z] [29] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> PingReq
2018/08/31 12:15:16.602|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:16.6023040Z] [27] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PingResp
2018/08/31 12:15:21.986|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:21.9875980Z] [27] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=ennio/main] [Payload.Length=377] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=7]
2018/08/31 12:15:22.988|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:22.9878390Z] [25] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubRec
2018/08/31 12:15:23.018|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:23.0178080Z] [29] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> PubRel
2018/08/31 12:15:23.408|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:23.4082700Z] [21] [MqttClient.MqttChannelAdapter] [Verbose]: RX <<< PubComp
2018/08/31 12:15:23.926|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:23.9344390Z] [22] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=ennio/main] [Payload.Length=398] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=8]
2018/08/31 12:15:24.478|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:24.4786360Z] [22] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Disconnect
2018/08/31 12:15:24.487|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:24.4875690Z] [22] [MqttClient] [Verbose]: Stopped sending keep alive packets.
2018/08/31 12:15:30.364|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:30.3620260Z] [30] [ManagedMqttClient] [Error]: Unhandled exception while publishing application message (b9986dd5-c7d2-4858-9233-8a269b2f8d4d).
System.Threading.ThreadAbortException: Thread was being aborted.
  at (wrapper managed-to-native) System.Threading.Monitor.Monitor_wait(object,int)
  at System.Threading.Monitor.ObjWait (System.Boolean exitContext, System.Int32 millisecondsTimeout, System.Object obj) [0x0002f] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.Monitor.Wait (System.Object obj, System.Int32 millisecondsTimeout, System.Boolean exitContext) [0x0000e] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.Monitor.Wait (System.Object obj, System.Int32 millisecondsTimeout) [0x00000] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ManualResetEventSlim.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00141] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.Tasks.Task.SpinThenBlockingWait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x0002d] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.Tasks.Task.InternalWait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00069] in <2943701620b54f86b436d3ffad010412>:0 
  at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.TryPublishQueuedMessage (MQTTnet.Extensions.ManagedClient.ManagedMqttApplicationMessage message) [0x00019] in <91e13803ae4446bdbae6f6f03ef926de>:0 
2018/08/31 12:15:30.370|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:30.3693670Z] [30] [ManagedMqttClient] [Error]: Unhandled exception while publishing queued application messages.
System.Threading.ThreadAbortException: Thread was being aborted.
  at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.TryPublishQueuedMessage (MQTTnet.Extensions.ManagedClient.ManagedMqttApplicationMessage message) [0x000b2] in <91e13803ae4446bdbae6f6f03ef926de>:0 
  at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessages (System.Threading.CancellationToken cancellationToken) [0x00019] in <91e13803ae4446bdbae6f6f03ef926de>:0 
2018/08/31 12:15:30.370|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:15:30.3732480Z] [30] [ManagedMqttClient] [Verbose]: Stopped publishing messages.
2018/08/31 12:16:03.365|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:16:03.3422540Z] [1] [ManagedMqttClient] [Info]: Started
2018/08/31 12:16:03.387|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:16:03.3873740Z] [14] [MqttClient] [Verbose]: Trying to connect with server (192.168.0.20:8883).
2018/08/31 12:16:03.408|Debug|LOBU.Core.Services.MQTT.MQTTNetService+<>c.<.ctor>b__8_3|>> [2018-08-31T12:16:03.4081460Z] [14] [MqttClient.MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:20]

**Comment by JanEggers** [comment]
I guess that is the reason:

08-31T12:15:30.3693670Z] [30] [ManagedMqttClient] [Error]: Unhandled exception while publishing queued application messages.
System.Threading.ThreadAbortException: Thread was being aborted.

you have to find out why the thread is aborted.

I just use Threadpool whenever possible so I dont have to deal with thread lifetime at all...

**Comment by JTrotta** [comment]
Ok. So you are telling me that a thread (one inside ManagedMqttClient.cs I suppose ) aborted for some reason. May you tell me which thread aborted, so I can better investigate? I cannot figure it out.

**Comment by chkr1011** [comment]
This looks very strange to me. Is there maybe a reference lost and the GC is cleaning something?

The thread is probably the connection monitor in the ManagedClient. It is a thread which runs forever and maintaines the connection.

**Comment by MrPec** [comment]
I think we actually have to same problem with MQTTnet 2.7.5.0. Even with AutoReconnect, 3 clients were disconnected the same time from the same broker and did not reconnect, We also tried to restart the Broker but to no avail. We restartet the application and all was good again. Any idea where I can look or what I can check?

**Comment by quintonv** [comment]
Are you receiving this issue on Android 8? I experience it on 8 and think it's that background activity mode that's causing it.

I don't think it reconnects once the app opens after the OS has shut it down

**Comment by JTrotta** [comment]
@quintonv I'm using Linux 4.14.67 and MONO 5.14.0.177

**Comment by quintonv** [comment]
@JTrotta ah ok, so not on an android device like my scenario
