### ISSUE TITLE
.net core 2.1 using MQTTnet  :errors observed starting the kestral in linux (Ubuntu 18.04) 

### ISSUE THREAD

**Issue by RaghavKumar** [chkr1011/MQTTnet#407]
The server is built using the  .net core 2.1 and MQTT2.8.2.

The server works good in windows and fails with in linux  .
The errors observed in linux during the start , and with kestral configurations .
	this.host = new WebHostBuilder()
				.UseKestrel( x =>
				{
					x.ListenAnyIP(tcp port);
					x.ListenAnyIP(http port);
				})

The error observed is as below :

**An error occurred starting the application.**

System.AggregateException: One ore more errors occured(Address in use) --> System.Net .Sockets.SocketException. : Address in use at 

at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error,string callerName)

at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot,SocketAddress socketAddress)

**Comment by chkr1011** [comment]
Hi, it seems that the port is already in use. There is a setting in the server options to disable either ipv4 or ipv6. Maybe you need to disable v6.

Best regards
Christian
