### ISSUE TITLE
Final Message/Will usage

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#408]
Is there any good documentation on how this 'will' message is utilized?  Can this be used to properly shut-down a connection server-side if a MQTT client disconnects (e.g. during a reboot)?  I'm running into a weird issue that when the client abruptly ends, the server does not realize the disconnect.  It could be due to using nginx and proxying the connection, but am unsure yet.

**Comment by chkr1011** [comment]
For more information about usage of MQTT please visit "https://www.hivemq.com/blog/how-to-get-started-with-mqtt". This library only implements the standard and provides no documentation of the basics.
