### ISSUE TITLE
How to get IP addresses of connected clients?

### ISSUE THREAD

**Issue by djarvis** [chkr1011/MQTTnet#410]
I would have thought that GetClientSessionsStatusAsync()'s returned element's Endpoint member would give me the IP address but it doesn't.  It is null.

Am I missing something?  Running version 2.8.2.

**Comment by djarvis** [comment]
Nevermind.  Something happened and they are not null now.

**Comment by biapar** [comment]
How Did you done this?

**Comment by djarvis** [comment]
There used to be something called MqttServer.GetClientSessionStatusAsync() where you could query by client Id and get the endpoint.  Not sure if this is there in later versions.

**Comment by biapar** [comment]
I use the last version of branch 2. I'm able to use GetClientSessionStatusAsync. A question: Why I don't see if client is off? Do it depend by timeout?
