### ISSUE TITLE
ThrowIfNotConnected

### ISSUE THREAD

**Issue by panyi-dotnet** [chkr1011/MQTTnet#411]
Using Managedmqttclient,
[Program.txt](https://github.com/chkr1011/MQTTnet/files/2373951/Program.txt)

 After the server connection is lost( stop mqtt server), the connection cannot be automatically reconnected without triggering any events. 

ThrowIfNotConnected() throw new MqttCommunicationException("The client is not connected.");

ConnectionState didn't change from stillconnected to notconnected.

MQTTNet : 2.8.2 
server mosquito 1.4.15

**Comment by chkr1011** [comment]
Hi,
sorry but I cannot reporoduce the issue. My test setup with managed client and mosquitto works as expected. Do you have some more information about your setup?
Best regards
Christian

**Comment by panyi-dotnet** [comment]
@chkr1011 
sorry, I reference the package from nuget.org,
it works fine.
It could be a problem with my compilation.

btw, when target to net461,  Framework dll files are copied to the target directory. eg netstandard.dll .


![15368261083546](https://user-images.githubusercontent.com/6744243/45475586-68110980-b76f-11e8-9dba-2681197b2189.png)
![15368260724568](https://user-images.githubusercontent.com/6744243/45475592-6a736380-b76f-11e8-8b4c-4c0759ba8115.png)

**Comment by chkr1011** [comment]
Please try again with 3.0.0 and reopen this ticket if it still fails.
