### ISSUE TITLE
Password heap security

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#412]
This is more of a feature request.  Can you consider using SecureString for user-supplied passwords, and/or clear them out after use so they don't linger on the heap longer than they need to?  I'm being picky, I know, but I figure if it's possible to reduce the window of vulnerability, why not do it.

**Comment by chkr1011** [comment]
Hi,
this is a good idea. I will add a new property to avoid breaking changes. The secured one will be preferred if both are set. Then you can choose which one to use. The builder can also use the secured one internally without causing breaking changes.
Best regards
Christian

**Comment by chkr1011** [comment]
Update: This is not possible :-( SecureString is not available for UWP and netstandard 1.3. So I would recommend that you implement your own _IMqttClientCredentials_ and use the SecureString internally.

**Comment by chkr1011** [comment]
I updated the Wiki with a hint for this. Thank you for your feedback 👍

**Comment by mvadu** [comment]
Are you still supporting netstandard 1.3? Given UWP is pretty much dead and netstandard 2.0 [supports SecureString](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netstandard-2.0) could you re-consider this?

**Comment by chkr1011** [comment]
What makes me wonder is this quote: "We don't recommend that you use the SecureString class for new development. For more information, see SecureString shouldn't be used on GitHub."

**Comment by SeppPenner** [comment]
I agree with @chkr1011. SecureString shouldn't be used as the string array is only encrypted on NetFramework (Which is almost already legacy as well right now) and isn't supported on NetCore at all as stated in the Github docs under https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md.
