### ISSUE TITLE
Unable to connect to client

### ISSUE THREAD

**Issue by MatteoBaldini** [chkr1011/MQTTnet#413]
Hello

I'm trying to send a simple message to a broker using this library. This is the code I've been trying to use and it's not working. Any ideas as to why? All help is highly appreciated.

Thanks to everyone

            var factory = new MqttFactory();
            var client = factory.CreateMqttClient();

            var options = new MqttClientOptionsBuilder()
            .WithTcpServer("00.000.00.00") <--server IP goes there
            .Build();

            await client.ConnectAsync(options);

            var message = new MqttApplicationMessageBuilder()
            .WithTopic("test")
            .WithPayload("Hello World")
            .WithExactlyOnceQoS()
            .Build();

            client.PublishAsync(message);

**Comment by chkr1011** [comment]
Hi,
what exactly is the problem you having? Is the client not connecting or is the message not published?

So far I cannot see any issues in the code (beside from the missing _async_ before _PublishAsync()_).

Best regards
Christian

**Comment by lore4** [comment]
> Hi @chkr1011 . So the error is: unable to send the message as the client isn't connected. If I run the code it throws an exception on the last line with that message. Therefore I'm assuming I made some mistake in the code to actually connect to the client.
> This is weird to me though because I literally copied and pasted the example from the wiki and I wrote heaps of other clients (in other languages) that use that same server and everything works fine with them. This refuses to work though.

Did you try to test your broker with another tool? For example, you may use mqtt.fx to connect to your target broker and publish some messages.

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.
