### ISSUE TITLE
Cannot use TLS

### ISSUE THREAD

**Issue by erwan200026** [chkr1011/MQTTnet#414]
I read the issue #60 but my code doesn't work. Someone can help me ? because there is not a lot of documentation in the wiki about tls.

### Client (publisher):
`namespace MqttPublisher
{
    class Program
    {
        static void Main(string[] args)
        {
			MqttFactory factory = new MqttFactory();
            var client = factory.CreateMqttClient();

			MqttClientOptionsBuilderTlsParameters tls = new MqttClientOptionsBuilderTlsParameters();
			tls.AllowUntrustedCertificates = true;
			tls.UseTls = true;
			tls.IgnoreCertificateChainErrors = true;

			IMqttClientOptions options = new MqttClientOptionsBuilder()
               .WithTcpServer("192.168.153.101",8883)
               .WithCleanSession(false)
               .WithClientId("publisher1")
               .WithCredentials("publisher1", "1234")
               .WithKeepAlivePeriod(TimeSpan.FromSeconds(30))
               .WithKeepAliveSendInterval(TimeSpan.FromSeconds(10))
			   .WithTls(tls)
               .Build();
			
            client.ConnectAsync(options);

            client.Connected += async (s, e) =>
            {
                Console.WriteLine("### CONNECTED WITH SERVER ###");

                try
                {
                    MqttApplicationMessage message;

                    Temp temperature = new Temp(18, "capteur1");
                    String json = JsonConvert.SerializeObject(temperature, Formatting.Indented);
                   
                    Console.WriteLine(json);

                    message = new MqttApplicationMessageBuilder()
                                           .WithTopic("cave/temperature")
                                           .WithPayload(json)
                                           .WithExactlyOnceQoS()
                                           .WithRetainFlag(false)
                                           .Build();
                    
                    await client.PublishAsync(message);

                    Console.WriteLine("### publications ok ###");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message.ToString());
                }
            };

            client.Disconnected += async (s, e) =>
            {
                Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                await Task.Delay(TimeSpan.FromSeconds(5));

                try
                {
                    await client.ConnectAsync(options);
                    Console.WriteLine("### RECONNECTED ###");
                }
                catch
                {
                    Console.WriteLine("### RECONNECTING FAILED ###");
                }
            };

            Console.ReadKey();

        }
    }
     
    [Serializable()]
    internal class Temp :  ISerializable
    {
        public Temp(int temp, String capteur)
        {
            this.temp = temp;
            this.capteur = capteur;
        }

        private int temp
        {
            get;
            set;
        }

        private String capteur
        {
            get;
            set;
        }

        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("temp", temp);
            info.AddValue("capteur", capteur);
        }

        override public String ToString()
        {
            return capteur + " : " + temp;
		}
    }
}`

### Broker:
`namespace MqttBroker
{
    class Program
    {
        static void Main(string[] args)
        {
            MqttFactory factory = new MqttFactory();
            IMqttServer broker = factory.CreateMqttServer();

            MqttServerOptions validator = new MqttServerOptions();
            validator.ConnectionValidator = c =>
            {

                c.ReturnCode = MqttConnectReturnCode.ConnectionAccepted;
                Console.WriteLine("Connexion OK");
            };

            MqttServerOptions subValidator = new MqttServerOptions();
            subValidator.SubscriptionInterceptor = context =>
            {
                context.AcceptSubscription = true;
                Console.WriteLine("Subscribe OK");

            };

            var storage = new RetainedMessageHandler();

            var certificate = new X509Certificate(@"C:\Users\StreamX\Desktop\TestCa.crt", "");
            MqttServerOptions certifOption = new MqttServerOptions();
            certifOption.TlsEndpointOptions.Certificate = certificate.Export(X509ContentType.Cert);
            certifOption.TlsEndpointOptions.IsEnabled = true;

            MqttServerOptionsBuilder options = new MqttServerOptionsBuilder()
                .WithConnectionValidator(validator.ConnectionValidator)
                .WithConnectionBacklog(100)
                .WithDefaultEndpointPort(1883)
                .WithSubscriptionInterceptor(subValidator.SubscriptionInterceptor)
                .WithStorage(storage)
                .WithPersistentSessions()
                .WithEncryptionCertificate(certifOption.TlsEndpointOptions.Certificate)
                .WithEncryptedEndpoint();
           

            broker.StartAsync(options.Build());
            
            broker.ApplicationMessageReceived += (s, e) =>
            {
                Console.WriteLine("### message reçu ###");
                Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
                Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
                Console.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
                Console.WriteLine();
            };

            Console.WriteLine("Press any key to exit.");
            Console.ReadLine();
            broker.StopAsync();
        }
    }

    public class RetainedMessageHandler : IMqttServerStorage
    {
        private const string Filename = "C:\\Users\\erwanp\\Desktop\\messageConservé.json";

        public Task SaveRetainedMessagesAsync(IList<MqttApplicationMessage> messages)
        {
            File.WriteAllText(Filename, JsonConvert.SerializeObject(messages));
            return Task.FromResult(0);
        }

        public Task<IList<MqttApplicationMessage>> LoadRetainedMessagesAsync()
        {
            IList<MqttApplicationMessage> retainedMessages;
            if (File.Exists(Filename))
            {
                var json = File.ReadAllText(Filename);
                retainedMessages = JsonConvert.DeserializeObject<List<MqttApplicationMessage>>(json);
            }
            else
            {
                retainedMessages = new List<MqttApplicationMessage>();
            }

            return Task.FromResult(retainedMessages);
        }
    }
}
`

**Comment by chkr1011** [comment]
Hi maybe this post #124 has some useful information.
Best regards
Christian

**Comment by erwan200026** [comment]
I'm sorry I am not an expert with certificates. A ".crt" certificate doesn't work ?

**Comment by SeppPenner** [comment]
> A ".crt" certificate doesn't work ?

You can convert your `.crt` certificate to a pfx easily using openssl: https://www.ssl.com/how-to/create-a-pfx-p12-certificate-file-using-openssl/

> Because I do the test with the _HasPrivateKey_ property and I don't have private key. So what can I do to have a private key ?

If you do not have the private key, this doesn't work...

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.
