### ISSUE TITLE
Redundant X509ChainStatusFlags check

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#418]
In MqttTcpChannel.cs:

`            if (chain.ChainStatus.Any(c => c.Status == X509ChainStatusFlags.RevocationStatusUnknown || c.Status == X509ChainStatusFlags.Revoked || c.Status == X509ChainStatusFlags.RevocationStatusUnknown))
            {
                if (!_options.TlsOptions.IgnoreCertificateRevocationErrors)
                {
                    return false;
                }
            }
`

Of course, this works ok but it made me wonder if the second RevocationStatusUnknown was meant to be a different enum.

**Comment by chkr1011** [comment]
Hi,
thank you for reporting this. I will fix it for the next version. I assume the flag "OfflineRevocation" was missing. 

Best regards
Christian
