### ISSUE TITLE
Client certificate credentials not recognized

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#419]
I'm hoping another user can help me out with this one.  This may not be the correct place to be asking the question, because I'm not sure if I'm doing something wrong with my certificates or if I'm doing something wrong with MQTTnet, but here it is anyways.  I'm trying to connect to [test.mosquitto.org](http://test.mosquitto.org)'s 8884 port that requires a client certificate.  I've done the following things:

1) Generated a private key:

> openssl genrsa -out client.key

2) Generated the .csr:

> openssl req -out client.csr -key client.key -new

3) Used [test.mosquitto.org/ssl/](http://test.mosquitto.org/ssl) to generate the certificate using the .csr

4) Merged the key and certificate into a .pfx:

> openssl pkcs12 -export -in client.crt -inkey client.key -out client.pfx

5) Set the certificates in the TLS options of MQTTnet:

```
List<byte[]> certificates = new List<byte[]>();

X509Certificate trustedCertificate = new X509Certificate(settings.TrustedCertificatePath);
certificates.Add(trustedCertificate.Export(X509ContentType.SerializedCert));

X509Certificate2 pfxCertificate = new X509Certificate2(settings.PfxCertificatePath, GetSecurePfxPassword(settings, encryptionService));
certificates.Add(pfxCertificate.Export(X509ContentType.SerializedCert));

MqttClientOptionsBuilderTlsParameters tlsOptions = new MqttClientOptionsBuilderTlsParameters();
tlsOptions.Certificates = certificates;
tlsOptions.SslProtocol = ConvertSecurityProtocolString(settings.Protocol);
tlsOptions.UseTls = true;
tlsOptions.AllowUntrustedCertificates = true;
tlsOptions.CertificateValidationCallback += CertificateValidationCallback;

options.WithTls(tlsOptions);
```

But when I run this, I get the following error:

> The credentials supplied to the package were not recognized

I am using a password in the .pfx, but I have verified that the password is correct and that I get a different error if the password is incorrect.  As a shot in the dark I tried installing both certificates to my local computer as well as my user account, but this didn't work.  Has anyone else seen this before, and if so what am I doing wrong?

**Comment by PaulFake** [comment]
If I grab the certificate from the store rather than the file system, it hangs rather than errors out.  But, now it at least gets far enough to where it's calling my certificate validation callback so it's progress.  Although I don't see why it wouldn't work to point to the .pfx in the file system rather than the store.

```
X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);
X509Certificate2Collection certs = store.Certificates;
store.Close();
X509Certificate2 pfxCertificate = certs[2];
```

**Comment by PaulFake** [comment]
If it helps someone in the future, the trick that got it working for me was to use

`X509KeyStorageFlags.PersistKeySet`

when loading a client certificate from the file system.

**Comment by mcdigisaar** [comment]
Awesome. Thank you man! Helped me a lot!
