### ISSUE TITLE
Asp Net Core: CPU spike

### ISSUE THREAD

**Issue by SherifRefaat** [chkr1011/MQTTnet#421]
I have noticed when running the Asp Net core example that the cpu usage spikes when doing the following:
- A client connects and stay connected for a while
- I close the network connection on the client by removing the network cable
- The server (Asp Net Core) app's cpu usage spikes;
- When the server consider the client disconnected (client disconnected event is fired) the app's cpu usage is back to minimal.

What do you think about the above? Is this a bug or a by design?

Thanks.

**Comment by JanEggers** [comment]
thx for reporting the issue I just created a fix

**Comment by SherifRefaat** [comment]
@JanEggers When do you think this is going to Nuget?

**Comment by JanEggers** [comment]
I dunno @chkr1011 is in charge of that! Do we have the nightly builds on myget yet?
