### ISSUE TITLE
Support for client TLS certificate authentication in Broker?

### ISSUE THREAD

**Issue by fyrdude** [chkr1011/MQTTnet#426]
Hello.
Im wondering if there is any plan to support client authentication via TLS certificate in the broker? I have looked and not found any way to do it.

**Comment by SeppPenner** [comment]
@chkr1011 I don't think this is available yet. Am I right?

**Comment by SeppPenner** [comment]
Oh, this is a duplicate of https://github.com/chkr1011/MQTTnet/issues/312.
