### ISSUE TITLE
App hangs, if MqttServerOptions.ConnectionValidator returns != MqttConnectReturnCode.ConnectionAccepted

### ISSUE THREAD

**Issue by malibVB** [chkr1011/MQTTnet#427]
Hi,
 I having the issue, that my app hangs at

>...
>await mqttClient.ConnectAsync(options);
>..

when I'm using the `MqttServerOptions`-Validator and set the return-code like

>...
>options.ConnectionValidator = c =>
>{
>  ...
>  c.ReturnCode = MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
>};
>...

If I set the return-code to 

>  ...
>  c.ReturnCode = MqttConnectReturnCode.ConnectionAccepted;
>...

It's work fine.

Any idea what's missing ?

**Comment by chkr1011** [comment]
Hi, thank you for reporting the issue. I was able to reproduce it and written a UnitTest and a fix.
I will release 2.8.4-rc1 soon for testing. Please let me know if it works for you.

Best regards
Christian

**Comment by malibVB** [comment]
Hi,
thanks for the quick fix.
I tested it now and it doesn't hang anymore.

Best regards
Ali
