### ISSUE TITLE
Which is the timeout between unsubscribe and subscribe topic ?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#433]
Which is the timeout between unsubscribe and subscribe topic ?

**Comment by SeppPenner** [comment]
What do you mean by timeout? The time between a client unsubscribes and subscribes to a topic?

**Comment by biapar** [comment]
yes

**Comment by SeppPenner** [comment]
I don't think that it's possible to answer this question in a generic way. I would say that this depends heavily on the internet connection between the broker and the client, the hardware capabilities of the client machine as well as the hardware of the broker... I would say that the time between is somewhere in the milliseconds, but I will test this in a simple setup.

**Comment by chkr1011** [comment]
I think this question makes no sense at all. There is no implicit timeout for that. The delay is a different story. But the timeout is the same as the generic TCP timeout which is set in the options. But you can build your own timeout via the cancellation token which can be passed as a parameter.

**Comment by SeppPenner** [comment]
> I think this question makes no sense at all. There is no implicit timeout for that. The delay is a different story. But the timeout is the same as the generic TCP timeout which is set in the options. But you can build your own timeout via the cancellation token which can be passed as a parameter.

Sorry, I didn't state it that clear. I meant the delay in my first answer.

**Comment by biapar** [comment]
Thanks.
