### ISSUE TITLE
Building under net462 brings all netstandard references into build directory

### ISSUE THREAD

**Issue by Avalan4er** [chkr1011/MQTTnet#434]
After building my .Net 4.6.2 project, I've found lots of .dll files in the build directory. It seems like all netstandard dependencies of MQTTnet are copying in the build directory event if project is under net462.
I tried deleting these files, but got an error without them during execution of method IMqttClient.ConnectAsync().

**Comment by chkr1011** [comment]
Hi,
I assume this is due to a missing config for 4.6.2 so it uses netstandard for that platform. We only have specified 4.6.1.

@JanEggers Do you maybe know more?

Best regards
Christian

**Comment by JanEggers** [comment]
https://github.com/dotnet/standard/issues/580
