### ISSUE TITLE
AddMqttTcpServerAdapter() & AddMqttWebSocketServerAdapter()?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#436]
I see this new calls into last version MQTTNet asp.net core.

```
//this adds tcp server support based on System.Net.Socket
services.AddMqttTcpServerAdapter();

//this adds websocket support
services.AddMqttWebSocketServerAdapter();
```

What done different from before and Why Do you introduce them?

**Comment by SeppPenner** [comment]
@biapar Which version are you referreing to? I will try to provide a upgrade log if you give me some more hints here.

**Comment by biapar** [comment]
2.8.5

**Comment by SeppPenner** [comment]
Do you mean changes from 2.8.4 or so to 2.8.5 or the changes from 2.8.5 to 3.0.x?

**Comment by SeppPenner** [comment]
I will close this due to inactivity now. The upgrading guide is in the wiki: https://github.com/chkr1011/MQTTnet/wiki/Upgrading-guide. If you have further remarks on that, do not hesitate to tell them.
