### ISSUE TITLE
IManagedMqttClientStorage Expectation

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#439]
Can someone tell me what the expectations are for the load/retrieve methods?  For example, during the load, do we purge the underlying store, or is there a guarantee when the messages are sent to the server, etc.?

**Comment by chkr1011** [comment]
Hi,
messages are only deleted from the managed client when they are successfully sent. So QoS 0 only means sent but not received from server. QoS 1 means sent and received.

So when the method of the interface is called you can assume that the messag was sent.

Best regards
Christian

**Comment by dealproc** [comment]
Apologies for the delay in responding.  I almost understand your response, but the interface has Load() and Save(), but there are no instructions on the expectations the load method and/or Save method should be doing.  Did i miss something within code?

**Comment by SeppPenner** [comment]
To be honest, I do not understand the question...

**Comment by SeppPenner** [comment]
I'm closing this now. Please feel free to re-open it or add another issue if you have further questions.
