### ISSUE TITLE
Which is the reference for UseMqtt?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#440]
Which is the reference for UseMqtt?

I'm not able to write 
`o.ListenAnyIP(1883, l => l.UseMqtt())`

To open a MQTT TCP Endpoint, I have to use the older method that is I follow this example 
 for AspNetCore 2 and my project is 2.1
https://github.com/chkr1011/MQTTnet/tree/master/Tests/MQTTnet.TestApp.AspNetCore2

**Comment by biapar** [comment]
🤔

**Comment by SeppPenner** [comment]
I will check this and update the documentation.

**Comment by biapar** [comment]
Thanks.

**Comment by SeppPenner** [comment]
Might take some time though.

**Comment by SeppPenner** [comment]
This issue might go in the same direction: https://github.com/chkr1011/MQTTnet/issues/605

**Comment by SeppPenner** [comment]
I can't reproduce the issue: https://github.com/mqttnettest/Issue440Test. Do you have some full code example for me? The only thing I found is the message from https://github.com/chkr1011/MQTTnet/issues/605.

**Comment by SeppPenner** [comment]
I will close this now. The only issue I had was the one mentioned in https://github.com/chkr1011/MQTTnet/issues/605.
