### ISSUE TITLE
Xamarin.Froms App Crash from frequent ApplicationMessageReceived

### ISSUE THREAD

**Issue by 0w8States** [chkr1011/MQTTnet#441]
Hi All,

So far I've been loving the MQTTnet code, I've got it running on a few different project with C# WPF and .Net Core. This week I experienced something odd, and it might just have to do with my knowledge of how Xamarin handles things. 

I have a cloud based MQTT publisher device that is sending out position data at 10ms interval; this is a higher speed than most MQTT projects, but the other applications with MQTTnet seem to power through without issues. When I port my usual code to Xamarin however, it will run on the app for about 3 seconds and then crash; this is being ported to a Galaxy Watch. On a side note, if i bump the interval to 200ms or higher, the app seems pretty stable.

Is there a better way to be handling the ApplicationMessageReceived event?

In my main app body:
```csharp
        public App()
        {
           Task.Run(RunAsync)
        }
```

In my MQTT Client side code:
``` csharp
       public static async Task RunAsync()
        {

            var factory = new MqttFactory();
            var client = factory.CreateMqttClient();

            var clientOptions = new MqttClientOptions
            {
                ChannelOptions = new MqttClientTcpOptions
                {
                    Server = MQTTBroker
                }
            };


            client.ApplicationMessageReceived += (s, e) =>
            {
                PayloadLabel.Text = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);
            };


            client.Connected += async (s, e) =>
            {
               await client.SubscribeAsync(new TopicFilterBuilder().WithTopic(MQTTSubTopic).Build());

            };

            // Attempt a connection to the broker
            try
            {
                await client.ConnectAsync(clientOptions);
            }
            catch (Exception exception)
            {
                PayloadLabel.Text = "Failed to connect..."
            }
        }
    }
```

Cheers!
+JH

**Comment by chkr1011** [comment]
Hi,
to me it sounds like a memory leak or related bug. Do you have some more details like memory consumption or exceptions?
Best regards
Christian

**Comment by 0w8States** [comment]
I think you are spot on, it's most likely a memory leak, I'm just not sure where!! I re-tested the same setup with the M2MQTT library; while it could get down to 150ms, it would have the same results.

The frustrating part is that the Samsung Galaxy Watch Emulator for Xamarin development will run a solid 30 seconds before a crash, while the actual watch takes about 2 seconds to crash; downside is it takes much longer to push the app to the watch for testing, and neither the emulator or watch seem to accept running in debug mode.

I've pushed my project to BitBucket if anyone wants to take a look, it's a very simple project. There is data being pushed at 50ms update for testing to the topic 'tizeniotdemo/robot/position' for the broker.hivemq.com

https://bitbucket.org/0w8States/galaxy-watch-tizen4-projects/src/19140058cd344167f9a106e63bfcea879e8f61b2/TizenWearable_IIoTPendant/?at=master

**Comment by chkr1011** [comment]
For me the code looks fine.
Could you please test with line "PositionData.Text = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);" removed. I want to make sure that the other code is not affecting the execution of the library.

**Comment by chkr1011** [comment]
Mhh that is still very strange. But is it now running stable across a long time also?

**Comment by 0w8States** [comment]
Yeah, it seems stable from here on, but can be hard to tell from the Samsung Tizen Emulator... I'll keep playing with the code and update if I happen to find a fix.

I appreciate all the help!

**Comment by SherifRefaat** [comment]
@0w8States I think you should keep the line and try using `RunOnUiThread()`
https://developer.xamarin.com/api/member/Android.App.Activity.RunOnUiThread/p/System.Action/

Because, I think that the problem is that you manipulate a GUI on a background thread. It could be that it is not alwayes the UI/Main thread is available to execute your test setting code.

Also, take a look on the following

1. https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.begininvokeonmainthread?view=xamarin-forms
2. https://docs.microsoft.com/en-us/xamarin/ios/user-interface/ios-ui/ui-thread

**Comment by 0w8States** [comment]
Awesome! That got me to a great point, here is what I did.

`
Device.BeginInvokeOnMainThread(() => {PositionData.Text = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);});
`

I can now update the UI with my robot publishing at 2ms. The robot wont necessarily publish at 2ms, but it will be between 2-10ms and the UI is very stable. Thank you!! 😄

**Comment by SherifRefaat** [comment]
@0w8States If this is done here, please close the case. Cheers.
