### ISSUE TITLE
Load config from config file

### ISSUE THREAD

**Issue by archerian** [chkr1011/MQTTnet#442]
Is there a way to load MQTT parameters like host, port, username etc. from a appsettings.json or similar config file? Something like WebHost.CreateDefaultBuilder calls serverOptions.Configure(context.Configuration.GetSection("Kestrel")) by default to load Kestrel configuration instead of having to manually get key value pairs and pass as arguments to the function calls?

**Comment by chkr1011** [comment]
Hi,
sorry but such a feature is currently not available.

Best regards
Christian
