### ISSUE TITLE
Packet of type 'MqttPubRecPacket' not handled or dispatched.

### ISSUE THREAD

**Issue by udarakasun** [chkr1011/MQTTnet#445]
I am trying to develop MQTTNET server using ASP.NET Core 2.1. Server is started ok. But when i trying to connect Client throws above Error message. 

My client and server are woking perfectly in ASP.NET Standard. But In .NET core it doesn't working.

I want to build server with TCP and WebSocket 

Any one can give me a help to solve this matter?

**Comment by SeppPenner** [comment]
What do you mean by `ASP.NET Standard.`? It's quite easy to build the standalone server in .NetCore. Checkout the https://github.com/chkr1011/MQTTnet/wiki/Server and maybe also my example https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig (It runs on .NetCore, you just will have to remove the JSON configuration and that stuff if you do not need this.

**Comment by SeppPenner** [comment]
I will close this issue now. If you have further questions, please re-open this issue or comment. Thank you.
