### ISSUE TITLE
Meta discoverability

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#448]
Im thinking about building an extension that would provide discoverability via asyncapispec (https://github.com/asyncapi/asyncapi/issues/96)

what do you guys/gals think?

**Comment by chkr1011** [comment]
Hi, looks interesting to me. I would like to test it then in my Smart Home project or MQTTnet.Server for example. If you still want to do it 😄

**Comment by chkr1011** [comment]
I close this because I assume that the extension will no longer be built.
