### ISSUE TITLE
MqttClientOptionsBuilderTlsParameters doesn't have a setting for client certificate

### ISSUE THREAD

**Issue by btrepp** [chkr1011/MQTTnet#449]
It looks like the WithTls options have been changed to require this object,
but it doesn't support the same features? I don't see a property to set the clientCertificate.

**Comment by ovshestakov** [comment]
@btrepp , I think that `Certificates` property in `MqttClientOptionsBuilderTlsParameters` is what are you looking for. Please, check it.

**Comment by cpipero** [comment]
I tried and can't understand the error (also see screenshot):

> CS0103 The name 'Certificates' does not exist in the current context


![image](https://user-images.githubusercontent.com/1840311/50344227-1effec80-04f8-11e9-80ac-c0f0d14a6378.png)

**Comment by ovshestakov** [comment]
> I tried and can't understand the error:
> 
> > CS0103 The name 'Certificates' does not exist in the current context
@cpipero , you are using the wrong syntax, please, remove the dot right after the "Certificates"

**Comment by cpipero** [comment]
@ovshestakov  thank you for your reply. I actually figured out the way after a while and forgot to post. Your observation is of course correct. 
Here's the code I ended up with
```         
            MqttFactory factory = new MqttFactory();
            mqttClient = factory.CreateMqttClient();`

            var options = new MqttClientOptionsBuilder()
                    .WithTcpServer("someaddress.com", 1883)
                    .WithCredentials("user", "password")
                    .WithTls(false, false, false,
                    new X509Certificate(@"filename.pem", "").Export(X509ContentType.Cert))
                    .Build();

```

This syntax is obsolete but does the trick. You can change it to use the `MqttClientOptionBuilderTlsParamaters` instead, and add the cert by creating the `X509Certificate` the way shown.
Thanks again.

**Comment by skakavyponik** [comment]
Hi,
for me .WithTls cannot take 4 argument [**false, false, false, new X509Certificate(@"filename.pem", "").Export(X509ContentType.Cert)**]
Thanks
