### ISSUE TITLE
Question about MqttCommunicationClosedGracefullyException

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#450]
I'm trying to diagnose an issue with an AWS broker immediately closing the connection after establishing it.  MQTTnet throws a MqttCommunicationClosedGracefullyException, and a stack trace points to this line of MqttPacketReader.cs:

`ExceptionHelper.ThrowIfGracefulSocketClose(bytesRead);`

This line throws if bytesRead is <= 0.  My question is, why would that packet be empty?  I ran a Wireshark trace and didn't see any empty packets - rather, I saw an encrypted alert from the server, followed by a FIN/ACK message, neither of which was an empty packet.  Am I misinterpreting what I'm seeing here?

**Comment by SeppPenner** [comment]
@PaulFake Do you still see this issue in the latest version?

**Comment by SeppPenner** [comment]
I will close this due to inactivity now. Please feel free to re-open this issue if it still applies. Maybe also https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws can help you.
