### ISSUE TITLE
About Cluster

### ISSUE THREAD

**Issue by woshile163** [chkr1011/MQTTnet#451]
Hi，MQTTnet support cluster？

**Comment by dealproc** [comment]
MQTTnet itself does not support "clustering" for the server componets (which I think is what you are asking here).
To do this, I borrowed an implementation of a signalr backplane for Orleans and built out a way to address the MQTT object through streams and such.  I'll be testing how well this works in the next few weeks as we begin deployment.

here's the project: https://github.com/dealproc/MQTTnet.Orleans

Yes, a readme, as well as inline docs are warranted.
