### ISSUE TITLE
ManagedClient Qos Upgrade question

### ISSUE THREAD

**Issue by archerian** [chkr1011/MQTTnet#455]
I read on the wiki 

> Also included ManagedMqttClient which maintains the connection and subscriptions automatically. Also application messages are queued and **re-scheduled for higher QoS levels automatically**.

does this mean based on some criteria the messages added to the queue to be sent are actually sent at a higher QoS than originally requested?

**Comment by chkr1011** [comment]
Hi, not it will only enqueue QoS > 0 internally. The managed client always tries sending only when connected. So QoS 0 is not lost immediately. But only 1 and 2 are enqueued again on failure.
Best regards
Christian
