### ISSUE TITLE
Proxy for connections without WebSocket

### ISSUE THREAD

**Issue by wanirahul** [chkr1011/MQTTnet#457]
Hello,

Is it possible to specify a proxy to connect to the MQTT server? In our work environment, all access is via a proxy with username/password credentials. I am trying to connect via the proxy.

I do not want to use WebSocket option as it increases frame size. 

Thanks,
Rahul

**Comment by sumitkrsaxena** [comment]
I am facing same issue where I don't want to use WebSocket to by-pass corporate proxy filter.
Is there any way to establish tunnel to communicate with mqtt?
