### ISSUE TITLE
How fast should the lib user return from ApplicationMessageReceived while consuming messages

### ISSUE THREAD

**Issue by kiranpradeep** [chkr1011/MQTTnet#458]
I am using MQTTnet _ManagedClient_ to receive messages from MQTT broker. In order to avoid any message being dropped, in _ApplicationMessageReceived_, I am currently adding messages to a _BlockingQueue_ for later processing. Is this mandatory? Will use of aync method result in message loss? The query is since Eclipse Paho documentation ([1](http://www.eclipse.org/paho/files/cppdoc/classmqtt_1_1iaction__listener.html)) specifically mentions like "_It is important that the listener returns control quickly otherwise the operation of the MQTT client will be stalled._" Is there a similar guideline to be followed for MQTTnet ManagedClient subscriber? Also ManagedClient had a internal queue ([2](https://github.com/chkr1011/MQTTnet/blob/d273148bc56571e04878e3b2aa5a459ecd5fe511/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L16)) for publisher but not for receiver.

Are both of below equivalent usages for this library? My usecase is that: An external MQTT publisher (Eclipse Paho based) is publishing at a total rate of 20000 msgs/sec to Mosquitto broker. These message are published even across 500 topics (around 40 messages per topic) at QOS of 2. 

```
mqttClient.ApplicationMessageReceived += async (s, e) =>
{
    //slow ?
   await PredominantlyIOoperationWhichCouldTakeUpTo50milliSeconds(e.ApplicationMessage.Topic, e.ApplicationMessage.Payload);
};

mqttClient.ApplicationMessageReceived += (s, e) =>
{
    // fast ?
    AddToBlockingQueueForLaterProcessing(e.ApplicationMessage.Topic, e.ApplicationMessage.Payload);
};
```

**Comment by chkr1011** [comment]
Hi,
the packets are processed one by one. So when your message processing is (sometimes) slow it will delay all other subsequent messages. So I prefer moving them to an additional queue. This allows the client to quickly send the ACK for a message etc.

Best regards
Christian
