### ISSUE TITLE
MQTTServer in UWP

### ISSUE THREAD

**Issue by haeberle** [chkr1011/MQTTnet#46]
Dear’s

First of all, thank a lot for the great solution.

I did some test by using the MQTTserver in a UWP app and identified an issue. I used the example code from the Readme and set the Port to 1883 in the DefaultEndpointOptions.
The Server runs into a Nullpointer Exception, because the ReceiveStream in the MqttTcpChannel is not initialized. I see that the initialization is done in the ConnectAsync method, but it looks the method is used in MQQTClient context but not if the Channel is used in Server context. 

My fix in MqttTcpChannel (MQTTnet.UniversalWindows), please validate ;-)
…..

```
public MqttTcpChannel(StreamSocket socket)
{
	_socket = socket ?? throw new ArgumentNullException(nameof(socket));
	CreateStreams(socket);
}
```
```
private void CreateStreams(StreamSocket socket)
{
	SendStream = socket.OutputStream.AsStreamForWrite();
	ReceiveStream = socket.InputStream.AsStreamForRead();
	RawReceiveStream = ReceiveStream;
}
```
```
public async Task ConnectAsync(MqttClientOptions options)
{
	if (options == null) throw new ArgumentNullException(nameof(options));
	if (_socket == null)
	{
		_socket = new StreamSocket();
	}
	if (!options.TlsOptions.UseTls)
	{
		await _socket.ConnectAsync(new HostName(options.Server), options.GetPort().ToString());
	}
	else
	{
		_socket.Control.ClientCertificate = LoadCertificate(options);

		if (!options.TlsOptions.CheckCertificateRevocation)
		{
			_socket.Control.IgnorableServerCertificateErrors.Add(ChainValidationResult.IncompleteChain);
			_socket.Control.IgnorableServerCertificateErrors.Add(ChainValidationResult.RevocationInformationMissing);
		}

		await _socket.ConnectAsync(new HostName(options.Server), options.GetPort().ToString(), SocketProtectionLevel.Tls12);
	}

	CreateStreams(_socket);
}
```

Cheers

**Comment by chkr1011** [comment]
Hi,
thank you for your bug report. You are right this is a bug and I fixed it in the way you proposed. 
A new version will be released soon.

Best regards
Christian
