### ISSUE TITLE
Gracefully disconnected on Connect

### ISSUE THREAD

**Issue by MattComb** [chkr1011/MQTTnet#460]
Hi, I have an issue when connecting at present.

I'm trying to connect a new client (v 2.8.4) against an older server (v2.6) and am getting gracefully disconnected.

Is this to be expected ? I was hoping not to have to upgrade the server component this release.

**Comment by chkr1011** [comment]
Hi, 
no this should not happen because the protocol did not change. But I am sorry to say that it is probably a bug in 2.6 (instead of 2.8.4).

Do you have some logs for me?

Best regards
Christian

**Comment by MattComb** [comment]
Hi Christian, no problem. In the end I setup a prototype using 2.8.4 to 2.8.4 and the bug went away, so I applied 2.8.4 server side in my server software and it also worked.

So all good now with the current version

**Comment by SeppPenner** [comment]
I will just close this issue then. Seems to be resolved + the latest version is already 3.0.3 by now.
