### ISSUE TITLE
IMqttServerOptions.ClientMessageQueueInterceptor set?

### ISSUE THREAD

**Issue by fogzot** [chkr1011/MQTTnet#463]
All the members of `IMqttServerOptions` have just getters except for `ClientMessageQueueInterceptor` that also has a setter. This makes pretty annoying to implement the options as an immutable type. Given that the setter is never used, is it possible to remove it?

**Comment by chkr1011** [comment]
Hi, 
you are right. This is wrong. It was added by accident. I will remove it in the next version.

Best regards
Christian

**Comment by chkr1011** [comment]
I released 2.8.5-rc1. Please let me know if version works for you.
Best regards
Christian
