### ISSUE TITLE
Feature Request: Serializable ManagedMqttApplicationMessage

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#466]
I'd like to be able to serialize ManagedMqttApplicationMessage so I can store it on disk as binary rather than JSON (in my IManagedMqttClientStorage implementaton).  Can this class be given the [serializable] attribute?

**Comment by chkr1011** [comment]
Hi, sorry but I don't think this is possible. This attribute is not available in .net standard. I can only add it for older frameworks.

**Comment by PaulFake** [comment]
Ok.  I didn't know it wasn't available in .NET Standard.  Darn!
