### ISSUE TITLE
Cannot access server over websocket

### ISSUE THREAD

**Issue by VetonAbdiu** [chkr1011/MQTTnet#467]
Love ur work, but how i can access server over ws ?
Tried server_ip:1883.
The connection keeps refusing

**Comment by VetonAbdiu** [comment]
Added this on startup -> config services
`
            //this adds a hosted mqtt server to the services
            services.AddHostedMqttServer(builder => builder.WithDefaultEndpointPort(1883));

            //this adds tcp server support based on System.Net.Socket
            services.AddMqttTcpServerAdapter();

            //this adds websocket support
            services.AddMqttWebSocketServerAdapter();`

this at startup -> configure
`app.UseMqttEndpoint();`

this at Program 
`        private static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseKestrel(o =>
                {
                    o.ListenAnyIP(1883, l => l.UseMqtt()); // mqtt pipeline
                    o.ListenAnyIP(5000); // default http pipeline
                })
                .UseStartup<Startup>()
                .Build();`

This works :
`
        [Route("/A/{m}")]
        public async Task Test(string m)
        {
            var factory = new MqttFactory();
            var mqttClient = factory.CreateMqttClient();

            var options = new MqttClientOptionsBuilder()
                .WithTcpServer("192.168.1.23") // Port is optional
                .Build();

            await mqttClient.ConnectAsync(options);

            var message = new MqttApplicationMessageBuilder()
                .WithTopic("Test")
                .WithPayload(m)
                .WithExactlyOnceQoS()
                .WithRetainFlag()
                .Build();

            await mqttClient.PublishAsync(message);

        }
`

this not 
`        public async Task Test1(string m)
        {
            var factory = new MqttFactory();
            var client = factory.CreateMqttClient();

            // Use WebSocket connection.
            var options = new MqttClientOptionsBuilder()
                .WithWebSocketServer("192.168.1.23:1883/mqtt")
                .Build();

            await client.ConnectAsync(options);

            var message = new MqttApplicationMessageBuilder()
                .WithTopic("Test")
                .WithPayload(m)
                .WithExactlyOnceQoS()
                .WithRetainFlag()
                .Build();

            await client.PublishAsync(message);
        }`

the Error:

 `An unhandled exception occurred while processing the request.
TaskCanceledException: The operation was canceled.
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

HttpRequestException: The operation was canceled.
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

WebSocketException: Unable to connect to the remote server
System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)

MqttCommunicationException: Unable to connect to the remote server
MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)`

**Comment by JanEggers** [comment]
1883 is the tcp port if you want to use websocket it will be on the http port

**Comment by dealproc** [comment]
I had the same issue.. I had to add the websocket support itself...

Within the Client's Startup.cs class, in `ConfigureServices(IServicesCollection services)`, I had to make a call to `services.AddMqttWebSocketServerAdapter();`, then under `Configure(IApplicationBuilder app)`, I had to call `app.UseMqttEndpoint("/myendpoint")`  From there, it seems to be working as expected.

HTH

**Comment by VetonAbdiu** [comment]
and how do make the connection ? 
Like this ? 
`         // Use WebSocket connection.
                var options = new MqttClientOptionsBuilder()
                    .WithWebSocketServer("192.168.1.27:1883/myendpoint")
                    .Build();`

**Comment by VetonAbdiu** [comment]
You made my day, week, month and year ! Thanks a lot :P

**Comment by dealproc** [comment]
.... i just heard the Friend's theme song reading your response here... 😆

**Comment by rushisharma** [comment]
> 1883 is the tcp port if you want to use websocket it will be on the http port

What this mean?
There is no WebSocket port listening ?

**Comment by rushisharma** [comment]
@JanEggers How can I subscribe in JavaScript? please advise.

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/master/Tests/MQTTnet.TestApp.AspNetCore2/wwwroot/app/app.ts

**Comment by rushisharma** [comment]
@JanEggers Thank you, Its work like charm.
Appreciate you response.

**Comment by andarg** [comment]
> https://github.com/chkr1011/MQTTnet/blob/master/Tests/MQTTnet.TestApp.AspNetCore2/wwwroot/app/app.ts

Hi! Does it work under Ubuntu, thanks a lot for a help!

**Comment by andarg** [comment]
![image](https://user-images.githubusercontent.com/5294728/76090955-a5093580-5fcd-11ea-8920-a6c26a9ffce4.png)
i got smth like this when i run it, sorry if i ask a stupid question

**Comment by SeppPenner** [comment]
@andarg I cannot see any issue there. Just some warnings...
