### ISSUE TITLE
A couple of questions, if I may?

### ISSUE THREAD

**Issue by darrenlogan01** [chkr1011/MQTTnet#470]
Hi,
This isn't an issue, but two questions regarding Mqtt if you don't mind?
(Seems like a good place to ask since you guys are obviously professionals on the subject)

I'm quite new to Mqtt & do not fully appreciate its capability yet, however I've had Mqttnet publishing via a simple .net app. over a LAN + Mosquitto broker, and a cloud demo. using cloudmqtt - both with standard tcp connections, so I have "some" experience.

My questions are:

1/ Websockets
When or why would you choose to use websockets over standard tcp?
Am I right in thinking that Windows 7 and below does not support websockets and that only Windows 8 onward does?
I don't understand what a websocket is or how it is used in Mqtt, so I'd very much appreciate some enlightenment here.

2/ Secure connection
I've seen standard, non-secure Mqtt working over port 1883 with Mosquitto, but I'd like to know what steps I need to take to get a secure connection working?
What type of certificate do I need to purchase (a link would be useful) and how do I use it in this context?

Thanks in advance to anyone who cares to answer.
Regards,
Darren

**Comment by dealproc** [comment]
I'm not completely there for #2 yet.... but #1 I'm definitely doing both webSockets and TCP sockets because I am concerned about clients who adopt our technology being behind firewalls that block many IP Ports... it gives me a fallback to still create the connection with an alternative means before I need to work with potential client's IT staff.

**Comment by chkr1011** [comment]
WebSockets are also supported in Browsers out of the box. So you can easily send and receive data in HTML based apps.
