### ISSUE TITLE
I found a strange problem in the latest edition.

### ISSUE THREAD

**Issue by bbhxwl** [chkr1011/MQTTnet#473]
Client B subscribes to a/cmd. I want Client A to send a message to the server. The server pushes the message from Client A to a/cmd, forwards it, and sends it directly to MqttServer_Application MessageReceived as if it would not receive the message. But I push the message through the button to subscribe to a/cmd, and I can send it successfully.

The following code cannot be forwarded to other clients.

 private   void MqttServer_ApplicationMessageReceived(object sender, MqttApplicationMessageReceivedEventArgs e)
        {
            if (e.ClientId == null || e.ClientId == "")
            {
                return;
            }

            mqttServer.PublishAsync(new MqttApplicationMessageBuilder().WithTopic(e.ApplicationMessage.Topic).WithPayload(e.ApplicationMessage.Payload).Build());
            
        }

The following code is OK. I think the two should be exactly the same. I don't know why.

  private async void button1_Click(object sender, EventArgs e)
        {
          await  mqttServer.PublishAsync(new MqttApplicationMessageBuilder().WithTopic(textBox1.Text).WithPayload(textBox2.Text).Build());

        }

**Comment by chkr1011** [comment]
Hi,
they are not the same. Missing the async keyword leads to strange behavior. Please use the first way using _...GetAwaiter().GetResult()_ if you want to avoid async/await.

Best regards
Christian

**Comment by SeppPenner** [comment]
I will close this issue by now. As @chkr1011 already told you, @bbhxwl: These are definitely not the same.
