### ISSUE TITLE
Server refusing connection 

### ISSUE THREAD

**Issue by Giulio-Ladu** [chkr1011/MQTTnet#474]
Hi I am trying to connect a wpf application to a MQTTNet server. I have the server running on local host
and using the following code in a wpf application:

```
public MainViewModel()
        {
            mqttClient = new MqttFactory().CreateManagedMqttClient();

            mqttClient.Connected += MqttClient_Connected;
            mqttClient.Disconnected += MqttClient_Disconnected;
            mqttClient.ApplicationMessageReceived += MqttClient_ApplicationMessageReceived;

            Task.Run(async () => { await Connect(); });
        }

        private async Task Connect()
        {
            options = new ManagedMqttClientOptionsBuilder()
                   .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                   .WithClientOptions(new MqttClientOptionsBuilder()
                       .WithCommunicationTimeout(TimeSpan.FromSeconds(5))     // Default value
                       .WithKeepAlivePeriod(TimeSpan.FromSeconds(7.5))          // Default Value
                       .WithTcpServer(serverUrl)
                       .Build())
                       .Build();

            await mqttClient.StartAsync(options);
        }

        private async void MqttClient_Connected(object sender, MqttClientConnectedEventArgs e)
        {
            if (mqttClient.IsConnected) {
                Debug.WriteLine("### CONNECTED WITH SERVER ###");
                await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic($"automation/{topic}").Build());
                Debug.WriteLine("### SUBSCRIBED ###");
            }
        }

        private void MqttClient_ApplicationMessageReceived(object sender, MqttApplicationMessageReceivedEventArgs e)
        {
            //Debug.WriteLine("GETTING HERE");
        }

        private void MqttClient_Disconnected(object sender, MqttClientDisconnectedEventArgs e)
        {
            //Debug.WriteLine("GETTING HERE");
        }
```

I get the connected and subscribed event firing, however straight after, I get the disconnected event firing, with an inner exception "No connection could be made because the target machine actively refused it [::ffff:127.0.0.1]:1883" 
The server is really basic for now 

`var mqttServer = new MqttFactory().CreateMqttServer();

            var options = new MqttServerOptions();
`

I have tried using a basic client too and getting the same problem. Am I missing something or is there 
a problem when using with WPF?

**Comment by chkr1011** [comment]
Hi,
please provide a complete snipped. From what I can see it looks fine. But is the server started via calling "Start" and is there a short delay before trying to access it? Or is it running in a different process?

Is it full WPF or just UWP?

Best regards
Christian

**Comment by Giulio-Ladu** [comment]
Hi, thanks for getting back to me, I have tried a whole range of settings etc and i think there seems to be something up with the client receiving messages. I have moved the broker over to a RabbitMq  Server (using the mqtt plugin) , and it seems that publishing messages is ok, I am totally not able to get the notification that a message has been received?

I am using the managed client in a WPF application.

**Comment by chkr1011** [comment]
Could you please test it with the regular client? And probably post the trace output? You can find an example in the Wiki.

**Comment by Giulio-Ladu** [comment]
Did not notice the trace before! Thanks so much this pointed me to the problem!!
thanks so much

**Comment by chkr1011** [comment]
So is your problem now solved?

**Comment by SeppPenner** [comment]
I assume that this is solved now. @Giulio-Ladu: Please feel free to re-open this issue if not.
