### ISSUE TITLE
Will the MQTTnet support websocket without asp.net core hosts?

### ISSUE THREAD

**Issue by wyy272176594** [chkr1011/MQTTnet#478]
Hi,
I hosts the mqtt server in the console app. Now I forward the message to web with the lib websocket-manager. So does the mqttnet possible support websocket server without asp.net core hosts?
Thank you.

**Comment by chkr1011** [comment]
Hi,
this is not planned yet but you can implement an adapter if you want.
Best regards
Christian

**Comment by wyy272176594** [comment]
Thank you !
