### ISSUE TITLE
Loop in Exception 

### ISSUE THREAD

**Issue by haeberle** [chkr1011/MQTTnet#48]
I found a small issue in the Server implementation. I tested the server in a “rough environment”, means sometimes the MQTT clients go down without an unsubscription by the server and are off for minutes and reconnect again.

My understanding of the code is, the SendPendingPublishPacketsAsync Methods sends the pakages to the client. In case the remote host is not available, the SendPacketsAsync runs into an exception and the packages are restored back to the send queue until a cancelation is triggered from outside. The result is, a loop and the code never returns and give up to send packages to a not connectable client. 

I fixed that by using a trails counter and exit after 10 trails with an exception. On a first view, that works fine, but after some time the server crashes and disconnects other clients. I’m investigating on that.. a bit hard because some documentation is missing ;-)

```
private async Task SendPendingPublishPacketsAsync(CancellationToken cancellationToken, IMqttCommunicationAdapter adapter)
        {
            var consumable = _pendingPublishPackets.GetConsumingEnumerable();
            int trials = 0;
            while (!cancellationToken.IsCancellationRequested)
            {
                if (_pendingPublishPackets.Count == 0)
                {
                    await Task.Delay(TimeSpan.FromMilliseconds(5), cancellationToken).ConfigureAwait(false);
                    continue;
                }

                var packets = consumable.Take(_pendingPublishPackets.Count).ToList();
                try
                {
                    await adapter.SendPacketsAsync(_options.DefaultCommunicationTimeout, cancellationToken, packets).ConfigureAwait(false);
                    trials = 0;
                }
                catch (MqttCommunicationTimedOutException exception)
                {
                    // remote host is not reachable
                    MqttTrace.Warning(nameof(MqttClientMessageQueue), exception, "Sending publish packet failed.");
                    foreach (var publishPacket in packets)
                    {
                        publishPacket.Dup = true;
                        _pendingPublishPackets.Add(publishPacket, cancellationToken);
                        trials++;
                    }
                    await Task.Delay(TimeSpan.FromMilliseconds(20), cancellationToken).ConfigureAwait(false);
                }
                catch (MqttCommunicationException exception)
                {
                    MqttTrace.Warning(nameof(MqttClientMessageQueue), exception, "Sending publish packet failed.");
                    foreach (var publishPacket in packets)
                    {
                        publishPacket.Dup = true;
                        _pendingPublishPackets.Add(publishPacket, cancellationToken);
                        trials++;
                    }
                }                
                catch (Exception exception)
                {
                    MqttTrace.Error(nameof(MqttClientMessageQueue), exception, "Sending publish packet failed.");
                    foreach (var publishPacket in packets)
                    {
                        publishPacket.Dup = true;
                        _pendingPublishPackets.Add(publishPacket, cancellationToken);
                        trials++;
                    }
                }

                if (trials > 10)
                {
                    // give up
                    MqttTrace.Warning(nameof(MqttClientMessageQueue), "Sending publish packet failed. Give up");
                    throw new MqttCommunicationException($"Give up to try to send packages, receiver is lost. Trials {trials}");
                }
            }
        }
```

Regards
Hans

**Comment by chkr1011** [comment]
@JanEggers I saw that you added the _GetConsumingEnumerable_. Can you tell me the purpose of it because I never that this method before and I have no idea what it is used for!?

**Comment by haeberle** [comment]
Another topic in the Exception loop is the 

```
publishPacket.Dup = true;
```
Based on my understanding of the Protocol 3.1.1 is, only resend pakages in QoS > 0. For that,  I propose to change the code:
```
if (publishPacket.QualityOfServiceLevel != Protocol.MqttQualityOfServiceLevel.AtMostOnce)
                        {
                            publishPacket.Dup = true;
                            _pendingPublishPackets.Add(publishPacket, cancellationToken);
                            trials++;
                        }
```

**Comment by JanEggers** [comment]
>I saw that you added the GetConsumingEnumerable. Can you tell me the purpose of it because I never that this method before and I have no idea what it is used for!?

each item that is read with this enumerable is removed form the collection, so the BlockingCollection is basicly a queue. my first implementation was 

`
foreach( var packet in  _pendingPublishPackets.GetConsumingEnumerable()) {
       await adapter.SendPacketsAsync(_options.DefaultCommunicationTimeout, cancellationToken, packet).ConfigureAwait(false);
}
`

that way, with each loop iteration a packet is send and if _pendingPublishPackets is empty the movenext call of the enumerator blocks.

i optimized it the way it is now so multiple items are dequeued with take instead of one at a time with a foreach.

@haeberle the trial counter you added is basicly a session timeout based on failed send.  can u provide any details on how this affects other sessions / connections?

**Comment by haeberle** [comment]
My understanding is, the MqttClientMessageQueue is unique per connected Client, it should not impact any other session. To use a trial counter helps to manage longer response times for the client. But the wait time or number of trails could alsp be higher to wait a longer time in case the client is really busy before retun with the timeout. Was not able to find anything about response time in the MQQT spec.

**Comment by chkr1011** [comment]
@haeberle Please have a look at the develop branch. There is added support for _retained_ messages and also saving of them. In order to implement this I changed the connection handling for client sessions.

I hope this also fixes your problems. I still integrated your changes regarding the _Dup_ flag. But the retries are no longer needed because the connection is dropped directly. 

Best regards
Christian

**Comment by haeberle** [comment]
Thanks a lot Christian!

I run some tests and so fare, the implementation is really stable and works. One thing we should think about, the exception if the remote host / Client is offline because an offline scenario could happen as regular issue and if possible, the application should managed that with state not as an exception. 

Kind regards
Hans

**Comment by chkr1011** [comment]
OK perfect so far  :smile:

But I don't know what you mean with the scenario of disconnected clients. Also in _develop_ there is a new event for a disconnected client and this can happen all the time. So the connections are managed correctly in my opinion. Or do you don't want that internally an exception is thrown? At the moment this is properly handled but exposed as a warning in the trace. Is that what you mean?

**Comment by haeberle** [comment]
Hello Christian

Looks great with the disconnect, can you please add the handler also in the IMqttServer interface ? 

Second is, I struggled with the exceptions because of the static trace, I have the Server and Client in the same UW. I cannot differentiated between the server and client instance in a trace.  I have to change it and will come back with feedback, because for some reasons, if the client and server run at the same time, several TaskCanceledException occur.

Thanks
Hans

**Comment by chkr1011** [comment]
Oh yes sure I will add it.

Isn't it enough to filter via _Source_ in the trace messages? If you need other data etc. please let me know.

Can you please paste some trace with that task cancelled exceptions?

**Comment by haeberle** [comment]
Hi Christian

here the output:
```
ID:"MqttBroker" Message:"Src=MqttClientPendingMessagesQueue Msg=Sending publish packet failed. Lvl=Error ThrId=16 Ex=System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Core.Internal.TaskExtensions.<TimeoutAfter>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<SendPacketsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Core.Server.MqttClientPendingMessagesQueue.<SendPendingPublishPacketAsync>d__7.MoveNext()"
```

The challenge is now, to find the source of the issue, I'm using the Broker and the Client in the same app and using the MqqtTrace.TraceMessagePublished to trace issues. Currently I cannot differenciate between an issue in the Broker or Client code. The Source doesn't help much, because it is related to class names and I have to go to the code for the first analysis. Could be more helpful to have a own trace instance per instance (Broker or Client) so the TraceMessagePublished handler can be assigned to different methods in the App implementation. (i.e Dependency injection)

Regards
Hans

**Comment by chkr1011** [comment]
OK this exception is not properly handled. I fixed it. Please retest with the develop branch BUT I also changed the options handling so you have to rewrite your code because it is a breaking change. In the test apps you can see how it works now.

Why are you using server and client in same application? What is the use case for that (beside of testing)?

**Comment by haeberle** [comment]
Thanks a lot!

The reason to have both in the same UWP app is, it is not possible to communicate between UWP apps on the same host without any configuration on the host system. The final app is a IoT Solution, to distribute different services on multiple devices (Win 10 IoT). And at least, one has to act as MqttBroker and potentially as Client too.

**Comment by chkr1011** [comment]
I had the same issues and it was the reason to start this library 😄 

The server also has a _Publish_ method. You can use this without a separate loopback client. It is also faster because no packet transformation etc. is required.

**Comment by haeberle** [comment]
ah, ;-) ... sounds perfect.. I will test and come back..

**Comment by chkr1011** [comment]
I released a new version. Please reopen this ticket if required.
Best regards
Christian
