### ISSUE TITLE
Receiving retained message from server doesn't set retain flag to true

### ISSUE THREAD

**Issue by trev0115** [chkr1011/MQTTnet#482]
How can a subscriber tell if a received message sent by the server is a retained message? The retain flag is set to false when receiving the retained message after subscribing. 
"When sending a PUBLISH Packet to a Client the Server MUST set the RETAIN flag to 1 if a message is
767 sent as a result of a new subscription being made by a Client [MQTT-3.3.1-8]." from line 766 of the MQTT specification (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf)

**Comment by chkr1011** [comment]
Hi,
thank you for reporting this issue. I will fix it ASAP and upload a new RC.

Best regards
Christian

**Comment by chkr1011** [comment]
I released 2.8.5-rc5. Please let me know if the issue is fixed.

Best regards
Christian

**Comment by trev0115** [comment]
Thank you, it works as intended now.
