### ISSUE TITLE
Sending JSON string as payload leads to loss of data

### ISSUE THREAD

**Issue by zornwal** [chkr1011/MQTTnet#483]
Hello!

I'm experiencing some weird behaviour when sending a string in the JSON format in an RPC call.
I have an RPC client on my broker that instructs my subscriber to execute a rest request, which is does fine.
 But when the subscriber goes to return the result of the rest request as the payload, the broker/rpcclient does not receive the entire json string, only one of the properties, in this case a string array.

Example code is supplied below, and there should be no code omitted which could interfere with the order of the methods shown below, apart from the log statements that have been removed.

I have this object on both the broker and the subscriber (using RestSharp for HttpStatusCode).

```cs
public class CustomRestResponse
{
        public string Content { get; set; }
        public HttpStatusCode StatusCode { get; set; }
        public bool IsSuccessful { get; set; }
}
```

On the subscriber I execute the following code when returning the result from the rest request

```cs
public async void PublishMessage()
{
	/* Code Abbreviated */
	
	/* This would be passed as parameter to PublishMessage by the method executing the rest request*/
/*logging value before serialisation here*/
	var objectToSerialize = new CustomRestResponse()
	{
		Content = "[ \"item1\" , \"item2\", \"item3\" ]",
		HttpStatusCode = HttpStatusCode.OK,
		IsSuccessful = true
	};
	
	var payload = JsonConvert.SerializeObject(objectToSerialize);
	/*logging value after serialisation here*/

	/*
		This is where the fun begins.
		The payload string looks just as we would expect.
		However, when our RPCClient receives the response, the byte array only holds the value of the Content Property.
	*/
	
	var msg = new MqttApplicationMessageBuilder()
				.WithTopic(topic)
				.WithPayload(payload)
				.Build();

	await _client.PublishAsync(msg);

}
```

When the broker/rpcclient receives the response from the RPC it goes through the following code

```cs
/* also abbreviated*/
var piId = 1117;
var cmdString = $"{piId}";
var jsonString = JsonConvert.SerializeObject(commandObject);
var byteLoad = Encoding.UTF8.GetBytes(jsonString);
var byteRes = await _rpcClient.ExecuteAsync(
	TimeSpan.FromSeconds(60),
	cmdString,
	byteLoad,
	MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce
);
var retStr = Encoding.UTF8.GetString(byteRes);
/*logging value of payload after getting from bytes*/

var jsonResponse = JsonConvert.DeserializeObject<CustomRestResponse>(retStr); //Throws exception because retStr is not a CustomRestResponse now.

/*retStr only contains the Content string property. */
```

What happens here is that the retStr variable only contains the content json array defined in the CustomRestResponse and nothing else, even though it gets correctly serialized on the remote client.

Images: 
Broker/rpcclient only receives content string:
![corelog](https://user-images.githubusercontent.com/22613687/49243162-ef842580-f40c-11e8-96ab-c6cd77c74c0a.PNG)
Object is properly serialized on the remote client before sending:
![pilog](https://user-images.githubusercontent.com/22613687/49243163-ef842580-f40c-11e8-9e50-529554d8769a.PNG)

**Comment by dealproc** [comment]
Do we need to base64 encode the string or similar to avoid weird characters?

**Comment by JanEggers** [comment]
message payload is byte array we dont care what you send in there. message seperation is done by size in the header so we dont look at the payload at all.

**Comment by chkr1011** [comment]
Is this a full example or is the actual size of the payload maybe larger?

**Comment by JanEggers** [comment]
please either include the complete mqtt related source code and a wireshark screenshot that shows the incorrect messages.

currently im not able to tell what is wrong

**Comment by chkr1011** [comment]
I wondering how the content works in general. It is written as a string but assumed to be plain JSON.
