### ISSUE TITLE
ClientId property not available on class MqttClient

### ISSUE THREAD

**Issue by StannieV** [chkr1011/MQTTnet#485]
Is there a way to retrieve the clientId of a MqttClient object or could you add it to the MqttClient and IMqttClient?

**Comment by chkr1011** [comment]
Hi,
this is available at the options only. It is generated with a default value. So you can read id from the options before you call _ConnectAsync_.

Does this fix your issue?

Best regards
Christian

**Comment by StannieV** [comment]
Hi Christian,

Currently, I'm using the library Plt.M2Mqtt in an existing solution. My intentions are to switch to MQTTnet because it is used several other solutions within our product and the MQTTnet library is more frequently updated. In the existing solution, there is a list of Mqttclients that are connected to an MQTT broker. When a message is received or a disconnect event is triggered, the client id is used to retrieve several referenced objects from a repository.
I noticed that the options object it a private property in the MqttClient class. Exposing this would help me a lot integrating the MQTTnet library.

**Comment by chkr1011** [comment]
I got your point. I will add the currently used options to the interface for read access.

**Comment by StannieV** [comment]
Thank you!
