### ISSUE TITLE
When Payload StartWith 【DA|xxxx】, Client PublishAsync Success,But   SubscribeAsync Fail

### ISSUE THREAD

**Issue by mahuidong** [chkr1011/MQTTnet#488]
Send

            var factory = new MqttFactory();
            client = factory.CreateMqttClient();
            client.Connected += Client_Connected;
            client.ApplicationMessageReceived += Client_ApplicationMessageReceived;
            
            
            var exceptionIsCorrect = false;
            client.Disconnected += (s, e) =>
            {
                exceptionIsCorrect = e.Exception is MqttCommunicationException c && c.InnerException is SocketException;
            };

            try
            {
                client.ConnectAsync(new MqttClientOptionsBuilder().WithTcpServer(serverIp).WithCredentials(username,password).WithClientId(clientId).Build());
            }
            catch
            {
            }

        private static void Client_Connected(object sender, MqttClientConnectedEventArgs e)
        {
            Console.WriteLine($"Client_Connected>>{e.IsSessionPresent}");
            client.SubscribeAsync("RCU/P1/H0001/R0003");

            var msg = new MqttApplicationMessageBuilder()
                  .WithPayload("DA|18RS00SC00XI0000RV00R100R200R300R400L100L200L300L400Y100Y200AC0102031800BELK0000BM0000|")
                  .WithTopic("RCU/P1/H0001/R0003");
            client.PublishAsync(msg.Build());

        }

**Comment by chkr1011** [comment]
Hi,
please provide some more information from the logs (described in Wiki). 

Best regards
Christian

**Comment by mahuidong** [comment]
But, When Payload Not Contain 【DA|xxxx】, everything is ok,
Server's Server_ApplicationMessageReceived  and  Server_ClientSubscribedTopic  is ok,

When Payload StartWith 【DA|xxxx】, Client PublishAsync Success,But SubscribeAsync Fail,
use mqtt-spy in the same way。

**Comment by mahuidong** [comment]
![image](https://user-images.githubusercontent.com/4902995/49584743-35099b00-f997-11e8-99e3-5816a1b81014.png)
![image](https://user-images.githubusercontent.com/4902995/49584752-3e930300-f997-11e8-90f8-43878898f528.png)

**Comment by chkr1011** [comment]
That looks quite strange to me. 

I added a unit test with the code you provided but it works as expected (with the latest RC). 

Do you maybe have a message interceptor at the server?

**Comment by mahuidong** [comment]
Thank you very much. The reason is ：
when Payload startwith 【DA|】, Server_ApplicationMessageReceived  throw exception 。。。。
