### ISSUE TITLE
Suggestion: Mono support

### ISSUE THREAD

**Issue by JTrotta** [chkr1011/MQTTnet#49]
I tested the library on MONO (last version), and it works very well.
I will do much more intensive test this month. But you can assume:
Supported frameworks:
NET Standard 1.3+
.NET Core 1.1+
.NET Core App 1.1+
.NET Framework 4.5.2+ (x86, x64, AnyCPU)
Universal Windows (UWP) 10.0.10240+ (x86, x64, ARM, AnyCPU)
MONO

**Comment by chkr1011** [comment]
Hi,
thank you for your feedback! Do you know which version of Mono? Then I can add those details to the _Readme_.

Best regards
Christian

**Comment by JTrotta** [comment]
Of course!
Mono JIT compiler version 5.2.0.224 (tarball Mon Sep 18 18:57:13 UTC 2017)

Regards
Gerardo

**Comment by chkr1011** [comment]
OK thank you.
