### ISSUE TITLE
Proxy connection with WebSocket not work

### ISSUE THREAD

**Issue by ynyang** [chkr1011/MQTTnet#499]
Hi,
i use MQTTnet 2.8.5 both on broker and publisher/subscriber. The broker was deploy in Azure VM and open the 443 port. The subsrciber was under my company proxy network and use 443 port. i had set the app.config with `<defaultProxy useDefaultCredentials="true">`. But this subscriber always cannot connect to the broker only if use another network that without proxy. (On the other hand, when i use no-proxy network on subscriber side, it works properly)

Wireshark packets:
![image](https://user-images.githubusercontent.com/2045342/50090706-58103680-0244-11e9-96fb-0e13926d6076.png)
1. Subscriber(10.68.121.82) ask DNS server(10.68.90.26) where is Broker that deploy in Azure VM.
2. DNS server reply the IP address is "104.X.X.X" as the first packet of above image.
3. Subscriber ask the connection to "104.X.X.X". But it's wrong. it must to connection to proxy server.

Does it support proxy connection? Many thanks..

**Comment by chkr1011** [comment]
Hi,
I believe I cannot help here a lot since MQTTnet only uses .NET Core WebSocket class which also has support for proxies. Maybe you can try to do some research for .NET instead.

Best regards
Christian

**Comment by JanEggers** [comment]
yup as christian said we use kestrel for WebSockets so you should enable .net core logging and see why the  websocket request is rejected by kestrel.

**Comment by ynyang** [comment]
Thank you sirs reply.

I notice that i use TCP connection, not WebSocket connection as mqtt client in the past. Sorry about that.
If i change to use WebSocket connection, i can connect via proxy server.

But it still cannot establish the connection to server.
Here is my client settings:
`var options = new MqttClientOptionsBuilder()
                .WithClientId("myId")
                .WithWebSocketServer("XXX.cloudapp.azure.com:443")
                .WithCredentials("name", "password")
                .WithCleanSession()
                .Build();`

server settings:
`var optionBuilder = new MqttServerOptionsBuilder()
                    .WithConnectionBacklog(2000)
                    .WithDefaultEndpoint()
                    .WithDefaultEndpointPort(443);`

Do I must to change to WebSocket on server side?
if yes, is there any sample code for server with websocket? (must to use MQTTnet.AspNetCore?)

Thanks a lot.

**Comment by dealproc** [comment]
If you're rocking on asp.net core, you need to still setup kestrel listener for listening to websockets...

```CSharp
            services.AddMqttServer((builder) =>
                {
                    builder
                        .WithDefaultEndpoint()
                        .WithDefaultCommunicationTimeout(TimeSpan.FromSeconds(5))
                        .WithConnectionValidator(async (ctx) =>
                        {
                        });
                })
                .AddMqttWebSocketServerAdapter()
                .AddMqttConnectionHandler();
```

Notice that I add the websockets server adapter to the stack.

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.
