### ISSUE TITLE
Contribution interest: Message routing?

### ISSUE THREAD

**Issue by GeorgeHahn** [chkr1011/MQTTnet#5]
Hi! Would you be interested in a contribution to enable more fluent MQTT message handling?

Eg:

```
client.On["{room}/sensors/{sensor}"] = x =>
{
	Log("Data received from {0} (in {1}): {2}", x.sensor, x.room, x.Message);
};
```

I built something like this years ago in a library I named [Charlotte](https://github.com/GeorgeHahn/Charlotte), but neither it nor the MQTT library it depends on supports .Net Core. The API is inspired by [Nancy](http://nancyfx.org/). I'd be happy to contribute and maintain such an API for this library.

**Comment by chkr1011** [comment]
Hi,
to me this sounds like a good idea. Contributions are welcome!

But there is one thing I must rely on: The mentioned extension should be a extension only. So that the original MQTT client still works in the same way and standalone. And on top of it your extension. Maybe a new client class or static extension methods!? This is up to you :-)

If you agree please let me know :-)

Best regards
Christian

**Comment by GeorgeHahn** [comment]
Sounds good to me! I think I can make this work as an extension method, I'll give it a try!

**Comment by GeorgeHahn** [comment]
Hi,

Your API is actually very similar to the M2Mqtt API, so porting [Charlotte](https://github.com/georgehahn/charlotte) was really easy. I'm running into some connection reliability issues though, so I'm going to move to the M2Mqtt .Net Core fork. If I have some time in the future, I'll add an option for Charlotte to use this library or that one.

I'm sorry I have to walk away from this work; I've been pretty tight on personal-project time lately. I just noticed I don't have a license on Charlotte, but I'm happy to make it MIT so you can reuse any of the code. The interesting bits are the topic matcher and the dynamic message object. Happy to help, but I don't think I can drive this forward anytime soon.

Cheers,
George

**Comment by chkr1011** [comment]
Hi,
don't worry. For me it is OK.

Best regards
Christian
