### ISSUE TITLE
ClientConnected does not use ClientId and does not match connectedclientlist

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#50]
hi two issue around client connected event: 

1. if a client connected event is triggered Server.GetConnectedClients() does not contain the new client.
id expect that the client is in the list of connected cliensts if an event signals this. 

2. the identifier in the event is the remote endpoint of that socket or something else for websockets.
id expect the client id of the connect packet in the event.

id like to submit a pr either change the existing behavior or add another event like session created.

@chkr1011  thoughts?

**Comment by chkr1011** [comment]
Hi,
yes I agree this is a issue. The event is fired directly after the physical connection is made via TCP etc. not after the session is set up and running.

If you want to change this keep going :-)

I would prefer to stay with the existing events (in _develop_ branch) with a changed behavior of the _ClientConnected_ event including the real _ClientId_ and some other information like username etc. in the EventArgs (but not the ConnectPacket directly). Also a flag indicating if the session is new or reused would be useful in my opinion. Maybe the class _ConnectedClient_ can be reused and extended and then added to the event args? Then the data is the same if you read the connected clients later.

What do you think? Do you agree?

Best regards
Christian

**Comment by JanEggers** [comment]
yup sounds good

**Comment by chkr1011** [comment]
Ah yes and please add the _ConnectedClient_ to the _ClientDisconnected_ event. In my opinion it is useful there too 😄
