### ISSUE TITLE
Total number of PublishAsync & Respond from ApplicationMessageProcessed does not tally

### ISSUE THREAD

**Issue by hs84** [chkr1011/MQTTnet#500]
Hi,

I'm using ManagedClient 2.8.5 and I found something weird. 

FYI, I need to monitor every PublishAsync call to make sure all messages are delivered to the server. So I use the HasSucceeded or HasFailed property of ApplicationMessageProcessedEventArgs in the ApplicationMessageProcessed event to determine the status.

However, I found the total number of respond received (HasSuceeded and HasFailed) from ApplicationMessagedProcessed event will always more than the total number of PublishAsync call. Is it due to the logic behind of PublishAsync call will auto publish again when connection is disconnected or publish is failed? If the answer is yes, then I should able to get the total of HasSuceeded count same with the total of PublishAsync count. But when I monitor the HasSuceeded flag only, my system could not proceed due to web socket or client is disconnected while waiting for the HasSuceeded respond. May I know how do i ensure the connection can persist until last HasSuceeded respond to return?

**Comment by chkr1011** [comment]
Hi,
yes this is due to several retries. The client will stop trying after disconnect was detected but it can still happen that the event is raised a couple of times for a single message.

Your idea sounds good but requires some architecture changes in the managed client.

Best regards
Christian

**Comment by hs84** [comment]
Hi chkr1011,

Thanks for your reply. 

Seems like this is a big change to managed client. Is there any plan for this change in the next release?

**Comment by chkr1011** [comment]
Maybe not next release but I can add it on the list.

**Comment by hs84** [comment]
Hi chkr1011,

No problem. Really hope to see this feature in the near future...

Thanks.

**Comment by SeppPenner** [comment]
Is this already possible, @chkr1011?

**Comment by liaoliaoda** [comment]
Hi @SeppPenner 

have you solve your problem? I tested the ApplicationMessageProcessedHandlerMethod, the HasSucceededis's value is also be true when msg published fail.

Thanks.

**Comment by SeppPenner** [comment]
I'm not sure if this is already fixed in the latest version of the library or not @liaoliaoda

**Comment by liaoliaoda** [comment]
Hi @SeppPenner ,

It is working when the CleanSession value is false.

**Comment by chkr1011** [comment]
Please try with the latest version and reopen this ticket if the problem still occurs.
