### ISSUE TITLE
Dequeue Message Fails on Windows 2016 Server VM

### ISSUE THREAD

**Issue by YingGSZA** [chkr1011/MQTTnet#501]
Hi 
I am using this great library to create a MQTT Server running in a Windows service , all works well on my development machine (Windows 10 ) on my local Windows 2016 Server. Running the MQTTnet Server on a foreground application on an Azure Windows 2016 Server VM  all works we but when I run it on aa a Windows Service the following error occurs when I try to publish and subscribe to a topic >> [2018-12-20T04:33:29.6951745Z] [13] [MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter] [Verbose]: RX <<< Subscribe: [PacketIdentifier=25191] [TopicFilters=fred/test@ExactlyOnce]
>> [2018-12-20T04:33:29.7107447Z] [9] [MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter] [Verbose]: TX >>> SubAck: [PacketIdentifier=25191] [SubscribeReturnCodes=SuccessMaximumQoS2]
>> [2018-12-20T04:33:33.6569180Z] [13] [MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter] [Verbose]: RX <<< Publish: [Topic=fred/test] [Payload.Length=5] [QoSLevel=ExactlyOnce] [Dup=False] [Retain=False] [PacketIdentifier=25192]
>> [2018-12-20T04:33:33.6569180Z] [9] [MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter] [Verbose]: TX >>> PubRec
>> [2018-12-20T04:33:33.6733093Z] [8] [MqttServer.MqttClientSessionsManager] [Error]: Unhandled exception while processing next queued application message.
System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at MQTTnet.Server.MqttClientPendingPacketsQueue.Enqueue(MqttBasePacket packet)
   at MQTTnet.Server.MqttClientSession.EnqueueApplicationMessage(MqttClientSession senderClientSession, MqttPublishPacket publishPacket)
   at MQTTnet.Server.MqttClientSessionsManager.TryProcessNextQueuedApplicationMessage(CancellationToken cancellationToken)
>> [2018-12-20T04:33:33.9153035Z] [13] [MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter] [Verbose]: RX <<< PubRel
>> [2018-12-20T04:33:33.9153035Z] [9] [MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter] [Verbose]: TX >>> PubComp

Any suggestions on why the Queue Collection is failing?

Thanks

**Comment by JanEggers** [comment]
can you please verify that MaxPendingMessagesPerClient is > 0.

@chkr1011 maybe we should verify > 0 here:

https://github.com/chkr1011/MQTTnet/blob/fca9876111779ed6b229fb127ac98b622f6a9d42/Source/MQTTnet/Server/MqttServerOptionsBuilder.cs#L20

**Comment by JanEggers** [comment]
ie verify that you get the correct folder for your settings if you use Environment.CurrentDirectory for that you will get the windowsfolder instead of the application folder. use Path.GetDirectoryName( assembly.getentryassembly().Location) instead

**Comment by YingGSZA** [comment]
Thank you for the update , for some reason I did not set the value in the settings file., changed the value and it works. Thank you for your help
