### ISSUE TITLE
ManagedMqttClient ceases to attempt reconnection

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#502]
Stack:
 - Android 5.1.1
 - Xamarin Tools
 - MQTTnet/MQTTnet.ManagedClient v2.8.5

Once a client is connected, if the connection is severed [turned off wifi radio], it seems as if the framework is not reliably attempting to reconnect to the MQTT server.  The disconnect throws an exception which seems to be given to the ConnectingFailed event off of the managed client.  The system does not subsequently seem to try to continue a reconnection attempt.

I have a feeling I need to create a simple client for this, but would value some feedback.

**Comment by dealproc** [comment]
@JanEggers If you happen to have any ideas on what to take a look at... I feel like I am forgetting something with the LWT stuff, but I can't, for the life of me, think that the LWT signal is what we need to get a `Disconnected` event on the server... ideas?

**Comment by JanEggers** [comment]
@dealproc what do the client logs say? maybe forward the logs to a debug form im not familiar with xamarin / android development.

Im also not familiar with the managed client. had a look at the source and by the looks of it it should resubscribe after reconnecting.

there also seems to be an eventhandler that is fired if resubsrcibing fails for some reason.

https://github.com/chkr1011/MQTTnet/blob/fca9876111779ed6b229fb127ac98b622f6a9d42/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L339-L380

**Comment by dealproc** [comment]
I'm at the point of realizing it is not MQTT as much as it is the setup i did with Orleans streaming... I'm looking at refactoring to Azure Service Bus to support the streams, and hopefully that relieves the final issue.
