### ISSUE TITLE
!!! HAPPY HOLIDAYS !!!

### ISSUE THREAD

**Issue by chkr1011** [chkr1011/MQTTnet#503]
Dear contributors and users,

this year is about to end in a couple of days. Looking back it was a great year for _MQTTnet_. The project was started by extracting some code out of my Smart Home System _HA4IoT_ two years ago. Today it is about to hit 100.000 total downloads at _nuget_ within the next couple of weeks 🤞 . Another statistics I can see in _GitHub_ (as the repository owner) are ~60 clones and ~7.000 views per week. 

It is also interesting to read more and more people are using this library in real fabrics or hosting servers in _Microsoft Azure_ or _Amazon AWS_. I also get private e-mails from time to time with some project references in the area of _Microsoft HoloLens_ or _Unity_ games. What are you using _MQTTnet_ for? If you want to share it just add it to this ticket or write me an e-mail.

So keeping the above described situation in mind I want to thank all contributors of 2018 achieving this (listed in alphabetically order):

* @alamsor
* @acrabb
* @cstichlberger
* @fogzot
* @GarageGadget
* @israellot
* @JanEggers
* @jenscski
* @JTrotta
* @kpreisser
* @lerppana
* @malibVB
* @PaulFake
* @PitySOFT
* @trev0115
* @VladimirAkopyan
* @william-wps

But my thanks also go to all users of _MQTTnet_ as well which downloaded this library already 89.200 times 😮 .

I wish you all happy holidays, merry Christmas (is applicable) and all the best for the upcoming year 2019 🎆 .

Additionally I have a small Christmas gift for you 🎁 . I released version _3.0.0-alpha1_ which adds initial support for MQTT Version 5.

Best regards
Christian

**Comment by dealproc** [comment]
Building an exchange for IoT devices (both the device and the cloud).  I have a library [which needs updating] to connect this to Orleans.  If there is enough value, would it be best to have an org for this, and we can add contribution projects into that org?
