### ISSUE TITLE
Question - ConnectionRefusedBadUsernameOrPassword flag not being recognised.  Cannot locate unit test to prove the same.

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#505]
When using the MQTT server, if I set the context's ReturnCode to be `MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword`, my devices are still being allowed to connect to the broker.

Is there a unit test that I cannot locate which proves that this particular response code is indeed respected within the code base to deny the connection?

**Comment by chkr1011** [comment]
Mhh it seems that there is no session created but the client is also not actively disconnected. Are you able to send messages or subscribe them?

**Comment by dealproc** [comment]
According to the logs on my server, yes. I'm allowed to actively subscribe to them yet.

![image](https://user-images.githubusercontent.com/1635244/50387882-01d44500-06d5-11e9-81af-6600b005970d.png)

So, I downloaded the project, and wrote the unit test to ensure the failure exception was indeed happening... but I believe I would expect the server code to sever the connection at this point, as we're rejecting the connection.  This would create a security hole IMO if the server were to allow a client to continue subscribing to topics, etc.

**Comment by dealproc** [comment]
Looking at logs more, and I want to review the client code... but it seems when this case happens, the client is not properly informed that the server is denying the connection due to a bad username/password.  Not sure if this is according to specification or not, but will review the client code in the meantime.

**Comment by dealproc** [comment]
Reading over the client code, specifically here: https://github.com/chkr1011/MQTTnet/blob/4fed80c2d0c9e08e4364700eaf358bb37ed28d6f/Source/MQTTnet/Client/MqttClient.cs#L55-L99 it seems that the client is not checking the result from the server to determine if a connection was successful or not.  I was thinking that the connectresult object that was being returned from this function was being checked elsewhere, but there is no properties that state whether the authentication had succeeded or not.  I am wondering if this is the ultimate culprit, and if maybe an exception should be thrown in the event that the authentication has failed maybe?  IT would then allow the disconnect logic within the same method to take hold, i believe.

**Comment by chkr1011** [comment]
Here is no exception because it is a valid result. The caller should decide to either throw a proper exception or doing something else. I assume there is _DisconnectAsync_ missing here:

https://github.com/chkr1011/MQTTnet/blob/4fed80c2d0c9e08e4364700eaf358bb37ed28d6f/Source/MQTTnet/Server/MqttClientSessionsManager.cs#L240-L250

**Comment by dealproc** [comment]
Right... but the code I am presenting back to you _is_ the client code.  From what I am reading, it's getting the response back of "Bad Username or Password", and sending through that all is rosey, go ahead and link up with the server.  The client is not checking to see if it made a valid connection and/or has a valid authentication response.  So it seems like server and client can both use some additional checks through the connection and authentication process.

Eventually, I'll have to learn the APIs and code so I can contribute back.  At this point, I know enough to be dangerous, but not enough to provide PRs to this project yet.

**Comment by dealproc** [comment]
From what I can determine, this is part of https://github.com/chkr1011/MQTTnet/issues/506, as the implementation I've done for authenticating devices was of the following signature:

```CSharp
var options = new MqttServerOptions()
{
   ConnectionValidator = async (p) =>
   {
     ....
   }
}
```

Which the server did not know to "await" for the async Action to complete.  I'm implemented a signature change to resolve this issue temporarily, but need to see how the options can be re-implemented in a way whereas we can mark `ConnectionValidator` as `[Obsolete]` and use `ConnectionValidatorAsync` as the preferred method.

**Comment by dealproc** [comment]
I'm going to call this closed, as I found the issue and it was me.  The solution is to either 1) use a sync pipeline for the ConnectionValidator, or 2) pending the changes I am working on will work as expected, have a full async pipeline so async calls to databases, etc. are able to be used.
