### ISSUE TITLE
WithConnectionValidator Cannot receive connection request

### ISSUE THREAD

**Issue by mahuidong** [chkr1011/MQTTnet#508]
Hi,

At the first connection, everything was all right.
but after mqtt broker restart,
WithConnectionValidator Cannot receive connection request

tcp：

![image](https://user-images.githubusercontent.com/4902995/50461976-4144af00-09bd-11e9-95e9-a28f8ba4b90c.png)

code：
![image](https://user-images.githubusercontent.com/4902995/50462034-98e31a80-09bd-11e9-95a1-ebf4b8817b79.png)

**Comment by mahuidong** [comment]
![image](https://user-images.githubusercontent.com/4902995/50462120-21fa5180-09be-11e9-87ed-2ce210f22b56.png)

**Comment by mahuidong** [comment]
When the client is unchanged, the reconnection request of the client can be received by using Mosca 

![image](https://user-images.githubusercontent.com/4902995/50467234-e458f100-09dc-11e9-83a8-549ab9cc92dd.png)

**Comment by mahuidong** [comment]
Problem solved，thank you
![image](https://user-images.githubusercontent.com/4902995/50486353-98399b00-0a34-11e9-90b2-bfdeaeebf29d.png)

**Comment by chkr1011** [comment]
Hi, thank you for sharing this issue. 
Do you have some more details? I must say I don't understand the issue.

Is the connection still open after the exception (which you commented out)?

Best regards
Christian

**Comment by mahuidong** [comment]
1. Is the connection still open after the exception (which you commented out)?
  yes.

2. Most of the client communication is OK (including mqtt-spy), only my client can not really disconnect after 【throw new MqttProtocolViolationExcepiton】. My client is a RCU host.

3. In my case,
【throw new MqttProtocolViolationExcepiton】cannot close client connections，
【clientAdapter.DisconnectAsync】It can notify the client to stop requesting。

**Comment by mahuidong** [comment]
Hi, thank you for sharing this repository.

In my case,   After restarting broker, rcu's request log is as follows:
![image](https://user-images.githubusercontent.com/4902995/50502232-973a5500-0a98-11e9-9609-600d00c69a26.png)

RCU cannot recognize broker reboot, so it can only be forced to disconnect when RCU tries to connect

Best regards
Christian

**Comment by SeppPenner** [comment]
@mahuidong Please try with the latest version and tell us if this issues still occurs.
