### ISSUE TITLE
Hang on connecting client (Win 7 Embedded)

### ISSUE THREAD

**Issue by jerome155** [chkr1011/MQTTnet#510]
I'm using MQTTnet v2.8.5. I develop in a Win10 VM. The developed software using MQTTnet is using .NET framework 4.6.1, a Win Forms Application. I implemented "Plugins" for this software that are bound  during runtime, where MQTTnet is used as one reference in one Plugin. On the development machine, MQTTnet works like a charm. As soon as I install my software on the machine it is supposed to run on (Win 7 Embedded, 32bit), when trying to connect with any client, the client starts hanging and does never throw any exception. The server does not register that the client tries to connect, it does not throw any exception as well. The server however does occupy the port it is assigned.

I had Visual Studio installed on that development machine. All of a sudden, MQTTNet worked. When I uninstalled VS, it continued working until I reinstalled my software, where it stopped working.

When running the server implementation on its own on that system (without it being late-bound), everything works fine.

Are there any issues known related to this, and what is a possible solution?

Edit:
Firewall is turned off completely, the connection is made over localhost.

**Comment by chkr1011** [comment]
Hi,
sorry but I have no ideas for this special case. Maybe VS comes with a newer version of .NET Framework which includes a bugfix and then it works?

Best regards
Christian

**Comment by jerome155** [comment]
Hi Christian.
Thank you for your response. I was able to resolve the issue by building MQTTnet on the computer it is supposed to run on. I'm now using that .dll in my code and not the nuget version (which does not work for me). This is most likely due to some incompatibility of different .NET versions but I sadly do not have time to look deeper into the issue... If someone has the time:
Installed versions on my dev computer:
.NET 4.5
.NET 4.5.1
.NET 4.6
.NET 4.6.1
Installed versions on my Win7 Embedded machine:
.NET 4.6.1
Best
Jérôme

**Comment by SeppPenner** [comment]
I would not consider this as very important thing. If it works now, it's done. I'm closing this issue now. If anyone wants to investigate this, feel free to do so.
