### ISSUE TITLE
Question: LWT Firing after quick reconnect

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#513]
This may be documented, and I need to do further research, but I would like to know if the expected behavior for a network disconnection/reconnection within 5 seconds where the LWT firing timeout is 15 seconds... if the server should still fire off the LWT message or not.  IMO, this should not be the case, and if I am correct, I think there is a bug within the framework, as the LWT is being fired in these scenarios.

My current use:
 - 3.0.0-alpha (server)
 - 2.8.5 Managed Client (on Android)

Steps to reproduce
 - Android Application
 - Connect to broker
 - Use the onscreen enable/disable capability of android to turn off/on the network.  Turn off the network, count to 1, then turn on the network.

With this scenario, the server does not seem to be able to send further messages to clients either.  Not sure exactly why this is, and if there is a setting I can change or not to resolve the issue.  Will keep reading.

**Comment by chkr1011** [comment]
Could you please test with 3.0.3 RC? If the problem still occurs please reopen this ticket.
