### ISSUE TITLE
Windows Desktop Server Application cant send message to Client

### ISSUE THREAD

**Issue by jacksparrow47** [chkr1011/MQTTnet#515]
Hi ,
I am using MQTTnet 2.8.5.0 version and I want to send message from Server to specific client . Firstly I try "SubscribeAsync" method to send message and when I try this on Unit Test application everything work well , But when I try exactly same things on Windows Form application , Client just dont accept messages
Here is my Server and Client code

Server Code

`

        public static async void CreateServer(Action<MqttConnectionValidatorContext> validation)
        {
            mqttServer = new MqttFactory().CreateMqttServer();

            var optionsBuilder = new MqttServerOptionsBuilder()
            .WithConnectionBacklog(100)
            .WithDefaultEndpointPort(1884);

            if (validation != null)
                optionsBuilder = optionsBuilder.WithConnectionValidator(validation);
            var options = optionsBuilder.Build();
            await mqttServer.StartAsync(options);

        }
        public static void SendMessageToClient(string clientId, string message)
        {
            if (mqttServer == null)
                return;
            mqttServer.SubscribeAsync(clientId, new List<TopicFilter>()
                {
                     new TopicFilter(message,MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce)
                     {

                     }
                });
        }

`

Client Code

`

        IMqttClient client;
        public Form1()
        {
            InitializeComponent();
        }
        private void btnConnect_Click(object sender, EventArgs e)
        {
            try
            {
                client = new MqttFactory().CreateMqttClient();

                var clientOptions = new MqttClientOptionsBuilder().WithTcpServer(txtServer.Text.Trim(), 1884).WithClientId(txtClientId.Text.Trim()).Build();

                client.ConnectAsync(clientOptions).GetAwaiter().GetResult();
                client.ApplicationMessageReceived += Client_ApplicationMessageReceived;
                MessageBox.Show("Connected");
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
             
        }
        private void Client_ApplicationMessageReceived(object sender, MqttApplicationMessageReceivedEventArgs e)
        {
            MessageBox.Show("Message= " + e.ApplicationMessage.Topic);
        }

`

Is there any missing?

**Comment by jacksparrow47** [comment]
Hi,
I added await but result is same. 
Here is my message send code



        private void btnSend_Click(object sender, EventArgs e)
        {
              MqttServerConfiguration.SendMessageToClient(txtClientId.Text.Trim(), txtMessage.Text.Trim());
         }

message send code is in the server app. 
if you want I can publish code to github

Best regards Jack

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions. Please make sure to re-check this issue with the latest version if you re-open this issue again.
