### ISSUE TITLE
can the server forbid certain client publish message ?

### ISSUE THREAD

**Issue by jandykwan** [chkr1011/MQTTnet#517]
can the server forbid certain client publish message ?
in case the hacker  hack a client, and publish the message.

**Comment by SeppPenner** [comment]
This was a question I wanted to ask, too. I will provide an example for this in the Wiki.

**Comment by chkr1011** [comment]
Hi, yes you can implement a application message interceptor at the server. There you can check for every message if it is "safe". There you can check if "ClientX" is allowed to publish the specified topic etc. If not you can set the message to null or set "AcceptPublish" to false and the server will discard that message.

**Comment by SeppPenner** [comment]
@jandykwan: In the latest version, this is possible with e.g.:

```csharp
.WithSubscriptionInterceptor(
    c =>
        {
            if(c.ClientId == "Hans")
            {
                c.AcceptSubscription = false;
                return;
            }
            
            c.AcceptSubscription = true;
         })
```

My project https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig makes use of this.

I will provide this example in the wiki, too.

**Comment by SeppPenner** [comment]
This is now documented under https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-application-messages.
