### ISSUE TITLE
MQTTnet works in a dev machine but not in a QA machine

### ISSUE THREAD

**Issue by scotthome** [chkr1011/MQTTnet#518]
Hi all,

I am using VS 2017 to incorporate MQTTnet in a project.  It works perfectly in my dev machine.  However, when I deploy the code to a Windows Server 2012 machine.  ConnectAsync throws an exception and cannot connect.  The source of the exception is mscorlib.  The message says one or more errrors occurred...  It is definitely not a firewall issue because I can use M2MQTT library to connect to the same IP and port.

My project targets .NET framework 4.6.1 and the QA machine has that.  It also has .NETCore 2.2.  What else am I missing?  UniversalWindowsPlatform runtime?

Thanks,

Scott

**Comment by scotthome** [comment]
This is the error.

12:52:43.160 Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by SeppPenner** [comment]
@scotthome Does this still occur with the latets version?

**Comment by chkr1011** [comment]
I assume this is fixed.
