### ISSUE TITLE
IIS as reverse proxy?

### ISSUE THREAD

**Issue by keradamka** [chkr1011/MQTTnet#519]
Hi,
I want to use this great library as MQTT broker in ASP.NET Core project. The same app host a http site, and the MQTT broker.

`.UseKestrel(o =>
{
    o.ListenAnyIP(1883, l => l.UseMqtt()); 
    o.ListenAnyIP(80);
}).UseIISIntegration()`

I wondering is it possible to use in this situation the IIS as a reverse proxy?
Microsoft recommends to use in production Kestrel behind IIS.
Now I access the site on port 80, but I can't access the broker.

Thanks
Adam

**Comment by VetonAbdiu** [comment]
i dont use `.UseKestrel(o => { o.ListenAnyIP(1883, l => l.UseMqtt()); o.ListenAnyIP(80); }).UseIISIntegration()`
use this :
first delete the UseKestrel
than under Startup.cs -> public void ConfigureServices(IServiceCollection services)
add this :
`            var mqttServerOptions = new MqttServerOptionsBuilder()
                .WithDefaultEndpointPort(1883)
                .Build();
            services
                .AddHostedMqttServer(mqttServerOptions)
                .AddMqttConnectionHandler()
                .AddConnections()
                .AddMqttTcpServerAdapter();`

**Comment by SeppPenner** [comment]
Please feel free to re-open this if needed.
