### ISSUE TITLE
ApplicationMessageReceived isn't Async

### ISSUE THREAD

**Issue by ramonsmits** [chkr1011/MQTTnet#524]
ApplicationMessageReceived isn't Async which breaks the async flow and requires the event implementation to do `.GetAwaiter().GetResult();`.

Consider adding the ability to register a `Func<Task>` to flow the async context and also the cancellation token.

```c#
var mqttOptions = new MqttClientOptionsBuilder()
    //...
    .WithApplicationMessageReceiver(MyReceiver)  //   WithApplicationMessageReceiver(Func<MqttApplicationMessage, CancellationToken, Task>)
    //...
    .Build();
```

```c#
Task MyReceiver(MqttApplicationMessage message, CancellationToken cancellationToken)
{
     // Do async stuff
}
```

**Comment by chkr1011** [comment]
Hi,
you can make the event handler async by making the method _async void_. But version 3 of this library will have support for a real async handler.

Best regards
Christian

**Comment by ramonsmits** [comment]
While technically you can do `async void` that will result in data loss as the invoking of the event will then immediately return and [send the PubAck as mentioned in the other issue](https://github.com/chkr1011/MQTTnet/issues/523).

This basically results in `AtMostOnce` behavior is unreliable and as said results in data loss when errors occur.

**Comment by GieltjE** [comment]
Isn't the connection between the client and server synchronous? If that is the case how much sense does it make to have an aysnc messagereceived event?

**Comment by ramonsmits** [comment]
@GieltjE c# async await doesn't have a direct correlation with a process being synchronous but more with blocking IO which often happens.

**Comment by dpsenner** [comment]
@ramonsmits the event handler posted in your previous comment is a worst case scenario for async code because of `GetAwaiter().GetResult()` which should instead return a `Task` to `await` on. This would not only fix deadlocks but also fix any re-entrant issues of event handlers that do async publish. As far as I can tell, the proper way to fix this is probably by adding an async api that goes through all the layers. This unfortunately also means that c# events and event handlers need a replacement because they are unsuited for async code since they usually return void or only await the first attached event handler. See [this](https://stackoverflow.com/questions/12451609/how-to-await-raising-an-eventhandler-event) for further information.

**Comment by dpsenner** [comment]
I checked the implementation and the issue appears to stem from `ApplicationMessageDispatcher` having

* `public void Dispatch(Exception exception)`
* `public void Dispatch(MqttBasePacket packet)`

whereas it should probably read as:

* `public Task Dispatch(Exception exception)`
* `public Task Dispatch(MqttBasePacket packet)`

This forces the `ApplicationMessageDispatcher` implementation to spawn threaded tasks.

@chkr1011 What do you think? Do you think that the interaction there should be async, too? Changing this would allow an application that uses mqttnet to completely work async.

PS: I ignored any backward compatibility issues on purpose.

**Comment by dpsenner** [comment]
@ramonsmits The latest develop branch does now include an async api and the events are going to be deprecated. See [here](https://github.com/chkr1011/MQTTnet/commit/087c622122bc2d154faca5ef8ed2bbe6a2c9dff2).

**Comment by ramonsmits** [comment]
@dpsenner Maybe I'm missing it, but it seems the call stack still isn't fully async? I only looked at the diff of the commit you linked, not the full source.

**Comment by dpsenner** [comment]
On the develop branch the `ApplicationMessageReceived` event is deprecated and there is an alternative and MQTTnet does now call the `ReceivedApplicationMessageHandler` and awaits that handler. That makes the api async, but the internals of MQTTnet are not async yet. This issue overlaps with the discussion we had in the PR #550. I now created #556 to discuss and track those changes.

**Comment by ramonsmits** [comment]
Are there any develop builds on a build server? It is too bad that the broken async stuff isn't added as a feature on the current major.

**Comment by dpsenner** [comment]
Hey @ramonsmiths, I had the intention to make this happen. The intention and motivation is still here but I cannot estimate when I am going to be able to work on this. Something unexpected hit me hard and what I can tell you now is that I can't get back to work in front of a computer within the next 4 weeks. I look forward coming back to this as soon as possible.

**Comment by behroozbc** [comment]
hi
@chkr1011 I think is feature is implemented and should close this issue
