### ISSUE TITLE
Managed Client should dispose inner mqtt client

### ISSUE THREAD

**Issue by andreabalducci** [chkr1011/MQTTnet#527]
Last will message is delivered only when my application closes and not on disconnection of my managed client. 

Found the issue in ManagedClient not disposing wrapped client. 

As workaround I created the managed client without the factory, holding my reference to inner client and manually disposing after managed client.

**Comment by SeppPenner** [comment]
@andreabalducci @chkr1011 Is this fixed already? I would say yes when looking at the merged pull request.

**Comment by SeppPenner** [comment]
I will close this now. Feel free to open it again or contact me if this is still relevant.
