### ISSUE TITLE
Can I develop client using .net framework 2.0

### ISSUE THREAD

**Issue by kudlatiger** [chkr1011/MQTTnet#529]
Can I develop client using .net framework 2.0 which send messages to MQTT broker?

**Comment by JanEggers** [comment]
nope sry

https://github.com/chkr1011/MQTTnet#supported-frameworks

**Comment by kudlatiger** [comment]
So does it mean I can develop client only using supported framework. MQTT is a protocol right? Why can't I just send messages using node.js or Java?  May be I am wrong, please enlight me.

**Comment by JanEggers** [comment]
shure you can send a mqtt message with any app / language you want but this library only works on  
https://github.com/chkr1011/MQTTnet#supported-frameworks

**Comment by kudlatiger** [comment]
so you mean i can write like this?

       // Create a new MQTT client.
        var factory = new MqttFactory();  -> Any language client 
        var mqttClient = factory.CreateMqttClient();

do you have any sample?

**Comment by JanEggers** [comment]
sry im confused. 

the snippit above looks like you want to use this library. but this library requires .net 4.5.2 so it wont work on .net 2.0 

for node there is 
https://www.npmjs.com/package/mqtt

for java there is 
https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttClient.html

so your options are:

- update .net to at least 4.5.2 or .net core and use this library like in  https://github.com/chkr1011/MQTTnet/wiki/Client

- use another language client like the ones I referened above or google up some on your own

- fork this repo and port it to .net 2.0

I would try to use dotnet core selfcontained deployment that way you are not depending on a preinstalled framework and can run your client on the most operating systems

**Comment by kudlatiger** [comment]
The code which is responsible for sending the messages currently on .net framework and device team is not ready to upgrade .net framework.   The server which we developed using mqttnet is acting as gateway between device and cloud. Now, only option i feel is to expose some API's from gateway code so that client (.net framework) can send messages to gateway (.net core)

**Comment by dpsenner** [comment]
You can target your gateway application against .net standard. This gives you the opportunity to host the resulting application either on linux, on windows or even dockerize it.

**Comment by kudlatiger** [comment]
My gateway application is developed using .NET Core 2.1!  It's running on windows 7. Question is,  Can  non MQTTNet client can send messages to the gateway?
