### ISSUE TITLE
Web Socket support in MQTTNet Server

### ISSUE THREAD

**Issue by sehd** [chkr1011/MQTTnet#53]
The documentation is unclear and I couldn't find anything in the source code about Web Socket support in this library.
If it does support WS connections please tell me how to use it because I can't connect to the server with web sockets but I can using pure TCP connections.

Thanks.

**Comment by chkr1011** [comment]
Hi,
I updated the Wiki with an example: https://github.com/chkr1011/MQTTnet/wiki/MqttClient
If you need more information please let me know

Best regards
Christian

**Comment by sehd** [comment]
As the title suggests I'm talking about Server.

**Comment by chkr1011** [comment]
Ah sorry 😄 

This is currently not supported because it highly depends on the HTTP server you use. I started a HTTP server library which will have support for it but at the moment it is not ready.

If you use a certain HTTP server you can write a adapter for the server.

Best regards
Christian

**Comment by gfbaggio** [comment]
Hi Christian ... any updates on server websockets ... or do you have any optional solutions. I am stuck on my project.
dotnet c#

thanks

**Comment by stefannilsson** [comment]
@gfbaggio As per the Wiki this is supported via the ASP.NET Core-package which can be retrieved via NuGet: https://github.com/chkr1011/MQTTnet/wiki/Server#websocket-endpoint
