### ISSUE TITLE
Remote ip address

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#534]
Is’t possible to know the client ip address?

**Comment by JanEggers** [comment]
not baked into the protocol. with mqtt v5 you could fill a mqtt user property with the ip address or put it in the message body.

why would you want to know it anyway? its the idea of topics that you dont need to know ips as they may change....

**Comment by biapar** [comment]
Because to know if I’m in the same lan of device. If yes we use RestApi else Broker.
Maybe this a bad idea.
But :
Can be a broker a client and server?
Is there a proprierty that said “I gived topic ( command ) to client 100x100!”?

**Comment by JanEggers** [comment]
> Can be a broker a client and server?

a broker is a server like thing that can send and receive messages

> Is there a proprierty that said “I gived topic ( command ) to client 100x100!”?

I dont understand. 

You could generate a device id on each device and have it subscribe to /{deviceId}/{CommandName}.
But the broker should have some verification that only special authentificated clients or the broker itself can send this messages.

> Is’t possible to config qos different for some topics?

you can configure qos for each message you publish and for each subscription you make

**Comment by biapar** [comment]
I wish to said. Is there a propierty that said to the sender that the message is 100% released to the target?

**Comment by chkr1011** [comment]
There is no guarantee for a 100% send. Even when using QoS 2 you can also verify that the cleint has uploaded the event properly. There is nothing which lets the client know that ANOTHER client has received that message. If you need such an acknowledge you might add your own messages which will handle this.
