### ISSUE TITLE
How to use TlsOptions certificates list?

### ISSUE THREAD

**Issue by JTrotta** [chkr1011/MQTTnet#54]
May you add a wiki example?
I cannot get it working.

Thank you
JJ

**Comment by chkr1011** [comment]
Sure I will. Can you please share the code you are using and which exception is thrown first?

**Comment by JTrotta** [comment]
Sorry. No errors at all. The certificate used was wrong.
Only one doubt: what is the best method to export certificate into byte array from X509Certificate2?

**Comment by chkr1011** [comment]
Sorry but I don't know which the best method is. I often work with certificates from the personal store only.
