### ISSUE TITLE
IMqttNetLogger called with plaintext password

### ISSUE THREAD

**Issue by haraldreif** [chkr1011/MQTTnet#543]
Upon connecting to the MQTT broker, the Verbose method of the implementation of the IMqttNetLogger interface is called with a MqttConnectPacket object in the parameters array. This object includes the password in plaintext.

**Comment by chkr1011** [comment]
Hi,
thank you for your suggestion. I will think about it and modify the logger. I assume I will add a setting for this which defaults to removal of the password. Because in some cases this value might be interesting while debugging etc.

Best regards
Christian

**Comment by chkr1011** [comment]
This will be added in the next version 3.0.0.
