### ISSUE TITLE
No persistent session?

### ISSUE THREAD

**Issue by PontusHolmberg** [chkr1011/MQTTnet#546]
Can't get persistent sessions to work.

Subscribing with a QoS of 1 or 2 works and can receive messaged that are published while the
client is connected.

Any message published to that same topic while a client is disconnected will not be
received when the client re-connects.

Am I missing something or does this broker not support it?

**Comment by chkr1011** [comment]
Hi,
the broker supports it but you have to enable it first in the options.

Best regards
Christian

**Comment by PontusHolmberg** [comment]
What option would that be?

**Comment by chkr1011** [comment]
You should use _WithPersistentSessions_ when using the options builder.

**Comment by PontusHolmberg** [comment]
Is there any other requirements?
I've added WithPersistentSessions and is connecting clients with clean session = false, I'm also sub to topics with QoS 1 and sending messages with QoS 1.

But when publishing to topic, any disconnected clients won't receive it when they re-connect.
