### ISSUE TITLE
Windows 7 websockets support

### ISSUE THREAD

**Issue by Isreh** [chkr1011/MQTTnet#548]
Hi folks,

i'm developing an application who sends data from my android application to a desktop PC. First it worked on local network at home with no port restrictions. (without mqtt)

Now i need this application for my workstation at work. This is a Windows 7 PC behind a McAfee (uargh) firewall (i guess there is only port 80 open).

I decided to use mqtt to transmit the needed data over my raspberry pi. On the pi there is already a nginx webserver, so port 80 is in use and cannot take it for mosquitto broker. So i need to use websockets for this situation, BUT Windows 7 cannot use System.Net.Websockets.Client. I think this issue is already known.

Is it possible to use System.Net.Websockets.Client.Managed in MQTTnet? I already testet it, and it seems to work fine.

What do you think about it? Or did i miss something that MQTTnet already supports Windows 7 clients?

Thanks in advance!
Regards...

**Comment by chkr1011** [comment]
Hi,
your approach is absolutely fine. I also added a transport for WebSockets4Net in the past. 

But I am wondering why the original WebSocket libraries are not working in Windows 7. Do you have some links?

Best regards
Christian

**Comment by Isreh** [comment]
Hi Christian,

well with .NET Core 2.1 microsoft enabled managed implementation of websockets.
Here the link for the explanation why the original WebSocket are not working on Windows 7 previous .NET Core 2.1:
https://stackoverflow.com/a/48013336

Regards...

**Comment by JohBa** [comment]
Hi,

I'm currently doing the same and wanted to open a PR for this. @Isreh how did you manage the fact that `System.Net.Websockets.Client.Managed` is not strong named? Did you sign the package yourself or did you just not sign the `MQTTnet` package?

**Comment by Isreh** [comment]
Hi Johannes,

i just tried the nuget package if this really works. Right now i dont need to create a signed application and can use it for some tests. Later this could be a problem i guess.

Best Regards...

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.

**Comment by SeppPenner** [comment]
I'm not sure if we still need this @chkr1011? @matthid wanted to provide something under https://github.com/chkr1011/MQTTnet/pull/734, but I have no idea what the status is there...

**Comment by matthid** [comment]
I think this can be closed now.

**Comment by SeppPenner** [comment]
Okay.
