### ISSUE TITLE
Enhancement: modify psw during reconnect

### ISSUE THREAD

**Issue by JTrotta** [chkr1011/MQTTnet#55]
I suggest to implement a new feature. Now the password seems to be static and must be given during the client creation. It is very useful to modify the psw during connection (dynamic psw) and not during client creation.
For example it's possible to use a TOTP psw during reconnection.

I will propose a PR.
JJ

**Comment by chkr1011** [comment]
Hi, thank you for your request.
There is no PR required because I am already working on such a feature 😄 

Best regards
Christian
