### ISSUE TITLE
SSL Certificate 

### ISSUE THREAD

**Issue by gregjesl** [chkr1011/MQTTnet#552]
## Problem
I followed along #60 in an attempt to enable TLS on the broker but when starting the broker I encountered the exception `System.InvalidOperationException: The certificate for TLS encryption must contain the private key` despite the certificate having the key. 

## Solution
To fix the issue, I first had to mark the certificate as `Exportable`:
``` C#
var certificate = new X509Certificate2(filePathToCertificate, password, X509KeyStorageFlags.Exportable);
```
Then, when setting the options for the broker, the certifciate needs to be exported as a `Pfx` certificate (which contains the private key):
``` C#
options.TlsEndpointOptions.Certificate = certificate.Export(X509ContentType.Pfx);
options.TlsEndpointOptions.IsEnabled = true;
```

## Recommendation
Update the Wiki with this information.

**Comment by gregjesl** [comment]
Duplicate of #124.  Recommendation stands.

**Comment by chkr1011** [comment]
Thank you for the detailed explanation. I will update the Wiki soon. But you can do it as well if you like.

**Comment by gregjesl** [comment]
I just made the update.  Thanks!

**Comment by inforaudio** [comment]
Can you connect using TLS?

**Comment by gregjesl** [comment]
@inforaudio I am able to.  Our application uses two different clients:  the [MQTT node.js package](https://www.npmjs.com/package/mqtt) and the [ESP32 MQTT Client](https://github.com/espressif/esp-mqtt).  Both are able to connect using TLS to a broker built using MQTTNet running on a Windows VM we are hosting via Microsoft Azure.

**Comment by inforaudio** [comment]
But this library is no possible use in Xamarin.
What platform do you use for made the APP? and use this library?

**Comment by gregjesl** [comment]
> But this library is no possible use in Xamarin.

I have not tried using it in Xamarin. 

> What platform do you use for made the APP? and use this library?

I created a console application using Visual Studio that uses this library.

**Comment by inforaudio** [comment]
thanks for answer.
and do you know a simple library for use MQTT with SSL over Xamarin

**Comment by gregjesl** [comment]
Have you tried Xamarin's broker/client? https://github.com/xamarin/mqtt

**Comment by inforaudio** [comment]
I think that this library dont run in SSL /TLS mode, 
There are some question ask about it, wiht problem with this theme/topic
And there are nothing information about TLS /SSL in the library

**Comment by chkr1011** [comment]
Why do you think it is not able to run TLS in Xamarin?
I can connect with the test broker from hivemq without problems in Xamarin. 
The only thing I need to do is to use _WithTls_ in the client options builder.

**Comment by inforaudio** [comment]
Hello:
I have some days try with it, and i cant made it.

if only add:
.WithTls()

Show the exception.

MQTTnet.Exceptions.MqttCommunicationException: A call to SSPI failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED



I add 
  MqttClientOptionsBuilderTlsParameters tls = new MqttClientOptionsBuilderTlsParameters();
                    tls.AllowUntrustedCertificates = true;
                    tls.UseTls = true;
                    tls.IgnoreCertificateChainErrors = true;
and
.WithTls(tls)

And show the exception
MQTTnet.Exceptions.MqttCommunicationException: A call to SSPI failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.Mon


the code is like your example..

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using MQTTnet.Client;
using MQTTnet.Protocol;
using MQTTnet.Client.Options;
using System.Security.Cryptography.X509Certificates;
using System.IO;

namespace App24
{
    public partial class MainPage : ContentPage
    {
        

        public MainPage()
        {
            InitializeComponent();

            RunAsync();

           

            async Task RunAsync()
            {
                try
                {
                   
                    var factory = new MQTTnet.MqttFactory();
                    var client = factory.CreateMqttClient();
                    var clientOptions = new MqttClientOptionsBuilder()
                     .WithClientId("foo")
                     .WithTcpServer("192.168.0.167", 8883)
                     .WithCredentials("", "")
                     .WithTls()                     
                    //.WithTls(true, false, false, serverCertificate.Export(X509ContentType.Cert))
                    //.WithTls(true, false, false, serverCertificate.Export(X509ContentType.Cert))
                    .WithCleanSession()
                     .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311)
                     .WithKeepAlivePeriod(TimeSpan.FromSeconds(60))
                     .WithCommunicationTimeout(TimeSpan.FromSeconds(30))
                     .Build();
                  

                  

                    client.Connected += async (s, e) =>
                    {
                        Console.WriteLine("### CONNECTED WITH SERVER ###");

                        await client.SubscribeAsync(new MQTTnet.TopicFilterBuilder().WithTopic("#").Build());

                        Console.WriteLine("### SUBSCRIBED ###");
                    };

                    client.Disconnected += async (s, e) =>
                    {
                        Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                        await Task.Delay(TimeSpan.FromSeconds(5));

                        try
                        {
                            //await client.ConnectAsync(clientOptions);
                            await client.ConnectAsync(clientOptions);
                        }
                        catch
                        {
                            Console.WriteLine("### RECONNECTING FAILED ###");
                        }
                    };

                    try
                    {
                        await client.ConnectAsync(clientOptions);
                        Console.WriteLine(" Conectando : ......................");
                    }
                    catch (Exception exception)
                    {
                        Console.WriteLine("### CONNECTING FAILED ###" + Environment.NewLine + exception);
                    }

                    Console.WriteLine("### WAITING FOR APPLICATION MESSAGES ###");

                    while (true)
                    {
                        Console.ReadLine();

                        //client.SubscribeAsync(new TopicFilter("test", MqttQualityOfServiceLevel.AtMostOnce));

                        var applicationMessage = new MQTTnet.MqttApplicationMessageBuilder()
                            .WithTopic("A/B/C")
                            .WithPayload("Hello World2")
                            .WithAtLeastOnceQoS()
                            .Build();

                        await client.PublishAsync(applicationMessage);
                    }
                }
                catch (Exception exception)
                {
                    Console.WriteLine(exception);
                }
            }

            
        }
    }
}

**Comment by chkr1011** [comment]
OK this seems to be a platform specific issue. Are you able to connect to hivemq test broker (broker.hivemq.com) with TLS? If yes the problem may be caused by your environment.

Additionally you can attach an event handler to the static validation callback at the TLS options object.  Maybe the properties you set are not covering your problem while validating.

**Comment by inforaudio** [comment]
Thanks so much by your answer.
I try to connect to: broker.hivemq.com

and the answer is  nothing.

MQTTnet.Exceptions.MqttCommunicationException: The client is not connected.
  at MQTTnet.Client.MqttClient.ThrowIfNotConnected () [0x00021] in <6fb0ae0760d243c8a0c3422110b350c4>:0 
  at MQTTnet.Client.MqttClient.PublishAsync (MQTTnet.MqttApplicationMessage applicationMessage, System.Threading.CancellationToken cancellationToken) [0x0000e] in <6fb0ae0760d243c8a0c3422110b350c4>:0 
  at MQTTnet.Client.MqttClientExtensions.PublishAsync (MQTTnet.Client.IMqttClient client, MQTTnet.MqttApplicationMessage applicationMessage) [0x00023] in <6fb0ae0760d243c8a0c3422110b350c4>:0 
  at App24.MainPage+<<-ctor>g__RunAsync|0_0>d.MoveNext () [0x0023b] in C:\Users\Pablo\source\repos\App24\App24\App24\MainPage.xaml.cs:170 




So, here https://github.com/mqtt/mqtt.github.io/wiki/public_brokers
you can see that dont work in SSL only 
address | broker.hivemq.com
port | 1883, 8000 (WebSockets)

**Comment by inforaudio** [comment]
In broker broker.hivemq.com, we try to connect with desktop client like MQTTBOX and MQTTFX and cant connect by SSL.
And in my Broker, we can connect whit this clients.
always with CA signed server certificate

**Comment by inforaudio** [comment]
Hello:
We ty to connect to other public broker and we can connect to mqtt.fluux.io properly..
WONDERFULL.

But try to connect to other server MQTT and cant connect, show this message.
One have seft signed certificate and other have lets encrypt certificate

MQTTnet.Exceptions.MqttCommunicationException: A call to SSPI failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED03-15 13:27:56.230 I/mono-stdout(27658): MQTTnet.Exceptions

Really what can looking for in the broker?? What need the broker? How can solved it?
At this broker connect other clients by SSL without problem MQQTBOX MQTT.FX etc..
