### ISSUE TITLE
Elvis operator will result in null reference exceptions with await

### ISSUE THREAD

**Issue by BennyM** [chkr1011/MQTTnet#554]
Hi

While trying out the dev branch I ran into this:

` await ConnectedHandler?.HandleConnectedAsync(new MqttClientConnectedEventArgs(authenticateResult));`

using **?** together with await will result in a _NullReferenceException_.

Reference: https://stackoverflow.com/questions/40436213/why-elvis-operator-doesnt-work-with-async-await

**Comment by dpsenner** [comment]
I thought about making these async handlers a set of handlers instead. This would solve this and also allow the usecase of registering multiple async handlers.

**Comment by chkr1011** [comment]
This is fixed in Alpha 3. @dpsenner I agree that a list makes sense but then we need to provide rules etc. If just one of the handler has failed. With a single handler the user can and must implement this.
