### ISSUE TITLE
ReceivedApplicationMessageHandler example ??

### ISSUE THREAD

**Issue by javirs85** [chkr1011/MQTTnet#557]
I used ApplicationMessageReceived event to listen to incoming messages but it warns me that it is deprecated and I should be using ReceivedApplicationMessageHandler instead. But this one it not an event and I have no idea how to "listen to it".

Any example ??

**Comment by chkr1011** [comment]
Hi sorry but examples are finished just before the release.
I recommend you use the extension methods (merges just a few seconds ago). 
You need to have a class that implements the proper interface. Either you create one or use the ...Delegate class which Accepts an action or Func.

**Comment by SeppPenner** [comment]
This is already documented here: https://github.com/chkr1011/MQTTnet/wiki/Upgrading-guide
