### ISSUE TITLE
MQTTnet server with MQTT.js client

### ISSUE THREAD

**Issue by masterchen** [chkr1011/MQTTnet#558]
I want to use MQTTnet as Server side , and paho client with Mqtt.js  as client, but  i got the wrong message at server side:
Please await mqttServer.StartAsync()
MQTTnet.Server.MqttServer
>> [2019-02-25T11:21:15.2672214+08:00] [4] [MqttServer] [Info]: Started.
>> [2019-02-25T11:21:19.4946060+08:00] [3] [MqttChannelAdapter] [Verbose]: RX <<< PubAck
>> [2019-02-25T11:21:19.5195311+08:00] [3] [MqttClientSessionsManager] [Error]: The first packet from a client must be a 'CONNECT' packet [MQTT-3.1.0-1].
MQTTnet.Exceptions.MqttProtocolViolationException: The first packet from a client must be a 'CONNECT' packet [MQTT-3.1.0-1].
   在 MQTTnet.Server.MqttClientSessionsManager.<RunSessionAsync>d__26.MoveNext()
>> [2019-02-25T11:21:19.5344898+08:00] [3] [MqttChannelAdapter] [Verbose]: Disconnecting [Timeout=00:00:15]
>> [2019-02-25T11:21:19.5404818+08:00] [3] [MqttServer] [Info]: Client '': Disconnected (clean=False).

=============
And  at client i got:
WebSocket connection to 'ws://127.0.0.1:8222/mqtt' failed: Connection closed before receiving a handshake response
k._doConnect @ mqttws31.min.js:36
k.connect @ mqttws31.min.js:31
I.connect @ mqttws31.min.js:65
(anonymous) @ index.html:32
mqttws31.min.js:36 WebSocket connection to 'ws://127.0.0.1:8222/mqtt' failed: Connection closed before receiving a handshake response

can you give some suggestion ?

**Comment by JanEggers** [comment]
you should enable aspnet core logging to see whats wrong with ws. and have a look in the networktab in the prowser to see what packages are send.

**Comment by masterchen** [comment]
well, can you tell me where to  enable the detials log， i can't use MQTTNet source code to debug, just use the reference lib, in the console window of the vs studio(Server project),i can see 
引发的异常:“MQTTnet.Exceptions.MqttProtocolViolationException”(位于 MQTTnet.dll 中)
引发的异常:“MQTTnet.Exceptions.MqttProtocolViolationException”(位于 MQTTnet.dll 中)

i just want to know the thnking i'm testing(using MQTTNet as server and MQTTjs as client) is right , from the Server side info "The first packet from a client must be a 'CONNECT' packet [MQTT-3.1.0-1]." , i doublt my be the protocol is not match with each other. @JanEggers @chkr1011

**Comment by masterchen** [comment]
In my startup file. i Add :             services.AddMqttWebSocketServerAdapter();
even ,    app.UseCors("any");
After tried many methodes , still can't make the MQTTjs connected,  I'm using the MQTTNet sample code as server(which is under this github ,named aspnetcore2 as broker), and here is the MQTTjs test client project,link:
https://pan.baidu.com/s/1TPvpFLFLhI15UWK1SL2w-A 
download code ：6xhf 
can you help me to fined out what's the problem?, 

@JanEggers

**Comment by biapar** [comment]
I've the same problem.
