### ISSUE TITLE
how to confirm the topic is exist

### ISSUE THREAD

**Issue by kingloser** [chkr1011/MQTTnet#559]
First of all,thanks to the author's awsome projiect.
I wonder how to confirm the topic is exit,when I need to publish a message to the serve ,but when the topic is not exit ,the progrom can't give the API to konw the topic is not exit . i have read wiki but is nothing to give me .
Hope your replay ,thank you .

**Comment by JanEggers** [comment]
a topic does never exist on the broker. 

you can always publish packages to any topic and subscribe to any topic.

**Comment by kingloser** [comment]
yeah ,if the open mqtt service always you can publish the topic you like ,but like aiyun iot platform ,they foces some topic is useful,if i use  the topic which it  is  not allowed , how i to confirm the topic  is exit ?

**Comment by chkr1011** [comment]
You can use the SubscriptionInterceptor to check a subscribe request and deny it if it does not fit your rules.

**Comment by kingloser** [comment]
ok tank you very much
