### ISSUE TITLE
.NET Standard 2.0 client not getting disconnected event

### ISSUE THREAD

**Issue by anshulee** [chkr1011/MQTTnet#562]
Have a .NET Standard 2.0 client for MQTT which is talking to a HiveMQ broker.  The client is getting a disconnected event when the network goes down or if the server specifically disconnects but  there are other times when the server disconnects the client ( not clear why)but the client doesn't get the event. The client gets the disconnected event when it then goes to publish something.

Somewhat similar to https://github.com/chkr1011/MQTTnet/issues/358 but i am already using 2.8.5 so assuming that issue is resolved?

**Comment by 18251968697** [comment]
> Have a .NET Standard 2.0 client for MQTT which is talking to a HiveMQ broker. The client is getting a disconnected event when the network goes down or if the server specifically disconnects but there are other times when the server disconnects the client ( not clear why)but the client doesn't get the event. The client gets the disconnected event when it then goes to publish something.
> 
> Somewhat similar to #358 but i am already using 2.8.5 so assuming that issue is resolved?

Hi,bro.I meet this problem recently.Have you found a solution?

**Comment by anshulee** [comment]
No not really. We moved our code to use the https://www.hivemq.com/blog/mqtt-client-library-encyclopedia-m2mqtt/ library and its been working effortlessly since.

**Comment by 18251968697** [comment]
Thank you for your help.But I need to use mqttnet to complete the project.I found that this problem could be solved under MQTTNet 3.02.I need to follow up on this issue.
