### ISSUE TITLE
Timestamp for internal log messages

### ISSUE THREAD

**Issue by abrasat** [chkr1011/MQTTnet#563]
Is it possible to get also a timestamp for the internally generated log messages, for both MQTTnet client and server components? ? For instance when a topic is subscribed, when a topic value is published, when a client connects or sends a ping request and so on.

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/4fed80c2d0c9e08e4364700eaf358bb37ed28d6f/Source/MQTTnet/Diagnostics/MqttNetLogMessage.cs#L20

**Comment by abrasat** [comment]
Thank you for link.
Unfortunately the Publish() method form the IMqttNetLogger interface definition does not contain the MqttNetLogMessage element:
...
void Publish(MqttNetLogLevel logLevel, string source, string message, object[] parameters, Exception exception)
...

**Comment by chkr1011** [comment]
The actual timestamp is generated inside this method. There is no need for every caller to generate the timestamp on its own.

**Comment by abrasat** [comment]
I see. That means that if I use my own IMqttNetLogger implementation that is injected into CreateMqttServer() or CreateMqttClient() methods from the MqttFactory, I have to generate the timestamps by myself inside the Publish() method.

**Comment by chkr1011** [comment]
Yes that is correct.

**Comment by abrasat** [comment]
Ok, thx.
What would be the usage of the LogMessagePublished event from the IMqttNetLogger interface definition?

**Comment by chkr1011** [comment]
You can use it to attach any of your components to the log and write it so a file for example.
