### ISSUE TITLE
Monitoring of client connections in MQTT server

### ISSUE THREAD

**Issue by abrasat** [chkr1011/MQTTnet#564]
Does the MQTT server monitor the connected MQTT clients ? For instance if a MQTT client does not send any data (not even ping requests) for some time, would the server force the disconnection of the client, after a server side configured keep-alive delay expires ?

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/4fed80c2d0c9e08e4364700eaf358bb37ed28d6f/Source/MQTTnet/Server/IMqttServerOptions.cs#L12

**Comment by abrasat** [comment]
Thx for the links.
I set the TimeSpan for the WithDefaultCommunicationTimeout option of MqttServer to 10 seconds, and I connected a MQTT Client (mosquitto_sub) which has the KeepAlive set to 30 seconds to it. The MQTT ping requests are in this case sent to the MQTT server every 30 seconds, but the MQTT Server does not close the client connection after 10 (15 seconds), actually it does not close it at all.

What would be the interpretation of the normative statement [MQTT-3.1.2-24]  ?

> If the Keep Alive value is non-zero and the Server does not receive a Control Packet from the Client 538 within one and a half times the Keep Alive time period, it MUST disconnect the Network Connection to the 539 Client as if the network had failed

[MQTT 3.1.1 Specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/cos01/mqtt-v3.1.1-cos01.pdf)

**Comment by chkr1011** [comment]
@abrasat The _DefaultCommunicationTimeout _ is a general timeout on socket level. It is used in a lower layer (TCP) than the keep alive which is MQTT specific. Generally you do not need to alter the values of _DefaultCommunicationTimeout_. It is only exposed for special edge cases.

**Comment by abrasat** [comment]
@chkr1011 :  I still do not understand which timeout does the MQTT server then use to monitor the client connections, as requested in the MQTT specification?
