### ISSUE TITLE
MQTT broker does not listen on defined port and works only on default port

### ISSUE THREAD

**Issue by TaherianuBeac** [chkr1011/MQTTnet#566]
I am trying to run 2 MQTT broker on one server. The first one on listen port 1883 and WithDefaultEndpointPort(1884) ans the second one on listen port 1885 and WithDefaultEndpointPort(1886) I did it on .net core 2.2 base on your example but only one of them work, the only one that is on 1883.

```    
// code in startup
{
            services.AddSingleton<MyMqttServer>();
            services.AddMvc();

            var mqttServerOptions = new MqttServerOptionsBuilder()
                .WithDefaultEndpointPort(1886)
                .Build();
            services
                .AddHostedMqttServer(mqttServerOptions)
                .AddMqttConnectionHandler()
                .AddConnections()
                .AddMqttTcpServerAdapter();
        }

        public void Configure(IApplicationBuilder app, MyMqttServer myMqttServer)
        {
            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseMqttServer(server =>
            {
                server.Started += async (sender, args) => await myMqttServer.RunAsync();
            });
         }

// Program.cs
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseKestrel(o =>
            {
                o.ListenAnyIP(1885, l => l.UseMqtt()); // mqtt pipeline
                o.ListenAnyIP(5000); // default http pipeline
            })
                .UseStartup<Startup>()
                .Build();

**Comment by masterchen** [comment]
Hi beac ,im also use aspnetcore 2.0.x ,why i can not find the method service.Addconections ,which pakage i need import? or i missed somthing

**Comment by TaherianuBeac** [comment]
Hi, I am using MQTTnet.AspNetCore and MQTTnet

**Comment by masterchen** [comment]
mmh, the above two packages already in my project but vs2017 still says cannt find the method , can u help

**Comment by TaherianuBeac** [comment]
Can share with me your startup code?

**Comment by masterchen** [comment]
Here is the code in startup file, the MQTTnet Section like this and from the sample code:
  public void ConfigureServices(IServiceCollection services)
        {
	....
            #region MQTT

            string hostIp = Configuration["MqttOption:HostIp"];
            int hostPort = int.Parse(Configuration["MqttOption:HostPort"]);
            int timeout = int.Parse(Configuration["MqttOption:Timeout"]);
            string username = Configuration["MqttOption:UserName"];
            string password = Configuration["MqttOption:Password"];

            var optionBuilder = new MqttServerOptionsBuilder()
                .WithDefaultEndpointBoundIPAddress(System.Net.IPAddress.Parse(hostIp))
                .WithDefaultEndpointPort(hostPort)
                .WithDefaultCommunicationTimeout(TimeSpan.FromMilliseconds(timeout))
                .WithConnectionValidator(t =>
                {
                    if (t.Username != username || t.Password != password)
                    {
                        t.ReturnCode = MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                    }
                    t.ReturnCode = MqttConnectReturnCode.ConnectionAccepted;
                });
            var option = optionBuilder.Build();
            services
                .AddHostedMqttServer(option)
                .AddMqttConnectionHandler();
  	// CAN NOT FIND THIS METHOD
                //.AddConnections();         
                
            #endregion
	    }
        public void Configure(IApplicationBuilder app,IHostingEnvironment env, IOptions<SenparcSetting> senparcSetting, IOptions<SenparcWeixinSetting> senparcWeixinSetting)
        {
            #region MQTT
            
             // CAN NOT FIND THIS METHOD
            //app.UseConnections(c => c.MapConnectionHandler<MqttConnectionHandler>("/data", options =>
            //{
            //    options.WebSockets.SubProtocolSelector = MQTTnet.AspNetCore.ApplicationBuilderExtensions.SelectSubProtocol;
            //}));
            
  
            app.UseMqttEndpoint("/data");

            app.UseMqttServer(server =>
            {
                server.Started += async (sender, args) =>
                {
                    var msg = new MqttApplicationMessageBuilder().WithPayload("welcome to mqtt").WithTopic("start");
                    while (true)
                    {
                        try
                        {
                            await server.PublishAsync(msg.Build());
                            msg.WithPayload("you are welcome to mqtt");
                        }
                        catch (Exception e)
                        {
                            Console.WriteLine(e);
                        }
                        finally
                        {
                            await Task.Delay(TimeSpan.FromSeconds(5));
                        }
                    }
                };

            });
             
            #endregion
            //easyNetQ
	    }
	    }

**Comment by TaherianuBeac** [comment]
@chkr1011 Hello again. As I didn't get any response from you, does it work only on 1883, my code is not correct or it is an issue?
Thank you

**Comment by chkr1011** [comment]
Your code looks fine so far. I do not see as mistake. @janeggers do you have any idea?

**Comment by JanEggers** [comment]
the only thing I see is that you set up 2 mqtt servers.
the socket server on 1886
and the asp.net core connection based server on 1885
and I dont know what MyMqttServer is / does.

@masterchen you need at least asp.net core 2.1.x so for connection apis appear

**Comment by TaherianuBeac** [comment]
@JanEggers Thank you for reply, I used those 2 ports based on your sample (you used 1883 in program.ca and 1884 in startup. I also tried WithoutDefaultEndpoint in startup), and this is MyMqttServer class which is just a wrapper
```
 public class MyMqttServer : MqttServer
    {
        public HookMqttServer(IEnumerable<IMqttServerAdapter> adapters, IMqttNetChildLogger logger) : base(adapters, logger)
        {
        }
        public async Task RunAsync()
        {
            string[] ips = new string[2];
            try
            {
                var options = new MqttServerOptions
                {
                    ConnectionValidator = p =>
                    {
                        ips = p.myVal.Split(":");
                    },
                    ApplicationMessageInterceptor = context =>
                    {
                    },
                    SubscriptionInterceptor = context =>
                    {
                        context.AcceptSubscription = false;
                    }
                };
                
                var mqttServer = new MqttFactory().CreateMqttServer();
                var payload = "";
                var topic = "";

                mqttServer.ApplicationMessageReceived += (s, e) =>
                {
                    payload = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);
                    topic = e.ApplicationMessage.Topic;
                    var validTopic = topic.Split("/")[0];

                    if (!string.IsNullOrEmpty(validTopic))
                    {
                        var data = Helper.GetData(e, options);                        
                        if (data != null)
                        {
                            OnDataReceived(validTopic, data).Wait();
                        }
                    }
                };
                
                mqttServer.ClientConnected += (s, e) => { };

                mqttServer.ClientDisconnected += (s, e) => { };

                mqttServer.ClientSubscribedTopic += (s, e) => { };

                mqttServer.ClientUnsubscribedTopic += (s, e) => { };

                mqttServer.Started += (s, e) => { };

                mqttServer.Stopped += (s, e) => { };

                await mqttServer.StartAsync(options);
            }
            catch (Exception)
            {
            }
        }
    }
```

**Comment by TaherianuBeac** [comment]
> Your code looks fine so far. I do not see as mistake. @JanEggers do you have any idea?

Thank you for checking that

**Comment by JanEggers** [comment]
hmm that is a third mqtt server you are starting.... and it is the one that is listening on the default port.

**Comment by TaherianuBeac** [comment]
> hmm that is a third mqtt server you are starting.... and it is the one that is listening on the default port.

How can I define here to listen to specific port? should I remove `server.Started` from startup?

**Comment by JanEggers** [comment]
if MyServer is the class you want to use to setup mqtt you dont need to derive it from mqtt server.

and you can also remove all the aspnet config stuff in you startup.

and finally the port where the server will listen is passed into the  MqttServerOptions either set directly or with the builder pattern you use in startup.

**Comment by TaherianuBeac** [comment]
@JanEggers Thank you very much. It works.

**Comment by TaherianuBeac** [comment]
And how does `WithDefaultEndpoint()` work? It does not get any argument.

**Comment by JanEggers** [comment]
i am sorry I did never run multiple brokers on the same machine so i dont know what / how that could work.

**Comment by JanEggers** [comment]
> And how does WithDefaultEndpoint() work? It does not get any argument.

https://github.com/chkr1011/MQTTnet/blob/195357835b258c8c043ed32fa10ad30e12d6a45f/Source/MQTTnet/Server/MqttServerOptionsBuilder.cs#L30-L52

**Comment by TaherianuBeac** [comment]
@JanEggers Thank you for your help.
