### ISSUE TITLE
Generic Host Asp.NETcore

### ISSUE THREAD

**Issue by FrancescoLusetti** [chkr1011/MQTTnet#567]
Could we use the generic host builder from ASP.NET 2.1 to build the server because the docs from Microsoft are telling that the generic host is better in this workload than the usual web host and this can let a better difference between client and server

**Comment by JanEggers** [comment]
nope not yet that will have to wait until 3.0 is released. at least I dont think the generic host is supported by kestrel yet. If you know how to pull that off please send a pr or details
