### ISSUE TITLE
Number of certificates for UWP

### ISSUE THREAD

**Issue by raymondarvidsson** [chkr1011/MQTTnet#57]
Hi,

I´m working in a Univeral Windows project. When I check you code it seems like I only can have one certificate. The server I´m accessing needs One certificate, one private key and a ca certificate. Create an PFX-certificate and I´m done?

/Raymond

**Comment by JTrotta** [comment]
Hi,
the library accept a list of certificates, not just one. Look at MqttClientTlsOptions. The Certificates property is a list of bytes.
The server you're talking about really needs a CA certificate and PKey? Strange. You should just sends your client certificate.

JJ

**Comment by chkr1011** [comment]
Hi,
I am not an expert of certificate handling in .net but internally the certificate is passed into the following property of the framework: _StreamSocket.Control.ClientCertificate_

More info: https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocketcontrol

I also found some more info about a similar problem (but c++) here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/4264f6db-4c17-484f-befc-5eb8b49b98df/uwpc-streamsocket-client-certificate?forum=wpdevelop

Maybe this helps...

Best regards
Christian

**Comment by chkr1011** [comment]
@raymondarvidsson I assume you don't need more assistance. If I am wrong please reopen this ticket.
