### ISSUE TITLE
Does MqttServer support QoS=2?

### ISSUE THREAD

**Issue by Tschaul** [chkr1011/MQTTnet#574]
Does the server respond to publishing messages with qos=2 by sending PUBREC and PUBCOMP messages? For me it seams like it doesn't, but i can't find a note about that in the wiki.

**Comment by temparus** [comment]
There is indeed an issue about QoS=2 (See #535).

This issue should be fixed in the upcoming version 3.0.0 which is still under development.

**Comment by Tschaul** [comment]
Thanks for the info!
