### ISSUE TITLE
Is possible a simple example running in Xamarin SSL?

### ISSUE THREAD

**Issue by inforaudio** [chkr1011/MQTTnet#575]
Hello:
We are starting with Xamarin a we need this library.
But we cant runing a example that run properly in xamarin.
Have a complete and simple example of this library runing in xamarin?

**Comment by chkr1011** [comment]
Hi,
sorry but there is no example yet but in the end it is not much different in comparison to the existing ones.

You should check:
1. Do not run event handlers on UI thread
2. Grant Internet permission
3. Use _WithTsl_ in options builder

Best regards
Christian

**Comment by inforaudio** [comment]
now we connect perfectly by 1883
But cant conect by 8883 TLS.
Can you explain more how conect?? 
Do i need the cert?  how can add it?
Have you got a code that really conect by TLS without problem?
So much thanks in advance

**Comment by chkr1011** [comment]
Please have a look at the file "PublicBrokerTest.cs" in the repo. There you have some examples including TLS ones. Also please try using the latest version 3.0.2.

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.

**Comment by biapar** [comment]
What Do you mean with "Do not run event handlers on UI thread"?

**Comment by biapar** [comment]
> now we connect perfectly by 1883
> But cant conect by 8883 TLS.
> Can you explain more how conect??
> Do i need the cert? how can add it?
> Have you got a code that really conect by TLS without problem?
> So much thanks in advance

Please, Could you share how to connect on XAM?

**Comment by SeppPenner** [comment]
> Do not run event handlers on UI thread

This means that the "regular" code is run on one thread, e.g. button events, inputs,, e.g.. Handling complex or long running tasks shouldn't be done on the this "UI thread" (it's even prohibited from Android and I suppose from iOS as well).

Use this link for more information: https://docs.microsoft.com/en-US/xamarin/ios/user-interface/ios-ui/ui-thread
