### ISSUE TITLE
LogId is always empty

### ISSUE THREAD

**Issue by adamopoi** [chkr1011/MQTTnet#576]
I am trying to retrieve the LogId from the trace messages, but it is always empty. I create the logger using `MqttNetLogger MqttNetGlobalLogger = new MqttNetLogger();` and I can retrieve the rest of the trace message fields but the LogId is always empty. However, based on #85 it is my understanding that the value of LogId should be the clientId.

**Comment by adamopoi** [comment]
I may have misunderstood the way LogId is used. In my current setup I use external MQTT clients to communicate with the MQTTnet broker. I wanted to get the client ids in the LogId field of the trace messages in order to group them. Would that only be possible if I used MQTTnet clients?

**Comment by chkr1011** [comment]
The log ID is a custom string. It is not related to client ID or whatever. But you can inject the client ID if you want. Some people need it to separate logs across multiple clients in the same application.
