### ISSUE TITLE
Incorrect 'Sec-WebSocket-Accept' header value

### ISSUE THREAD

**Issue by masterchen** [chkr1011/MQTTnet#577]
With example  code (ASP.NET Core 2.0 ),it runs well when lauch the project in vs2017 , but  i just tried to publish and deployed in IIS, when i open the home page, there is an error in the browser console:

WebSocket connection to 'ws://localhost:8181/mqtt' failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value

i changed the ws to wss , but the error still there.

I guess this may not related with MQTTNet, but i'm not familiar with this，can you give some hint how to solve this

**Comment by masterchen** [comment]
well , finally i found websocket service was not enabled in IIS, after enabled it, i can connect

**Comment by Trinitron** [comment]
Have the same error "**System.Net.WebSockets.WebSocketException: 'The 'Sec-WebSocket-Accept' header value 'C0/ZiyQOwL8AswnL0y7dRLBSBHs=' is invalid.'**"  Im using core 2.1 and this is simple console client app with using System.Net.WebSockets;

**Comment by SeppPenner** [comment]
@Trinitron Which version of the library do you use?

**Comment by Trinitron** [comment]
@SeppPenner this one System.Net.Sockets (4.3.0)
