### ISSUE TITLE
An unknown error occurred while processing the certificate

### ISSUE THREAD

**Issue by raymondarvidsson** [chkr1011/MQTTnet#58]
Cannot use a pfx-certificate. Get "An unknown error occurred while processing the certificate". 

Should I use code:
   tlsOptions.Certificates = new List<byte[]>();
   byte[] byteArray = cert.GetRawCertData();
   tlsOptions.Certificates.Add(byteArray);

**Comment by JTrotta** [comment]
Try: 
`X509Certificate2 ca = new X509Certificate2(Path.Combine(Environment.CurrentDirectory, "cert.xxx")); 
byte[] tosend = ca.Export(X509ContentType.XXX);   `
Check at X509ContentType enumerator

**Comment by chkr1011** [comment]
Please read comment of #57. Maybe it is related.

**Comment by mandarj123** [comment]
I have the same error while using MQTTdotnet, were you able to find solution of sending Ca,clientcert and key ?

**Comment by chkr1011** [comment]
@mandarj123 Please try with sample from https://github.com/dotnet/MQTTnet/issues/877 and let me know if it works.
