### ISSUE TITLE
ManagedClient and invalid characters for MQTT topics

### ISSUE THREAD

**Issue by kiranpradeep** [chkr1011/MQTTnet#581]
I use the ManagedClient to publish to Mosquitto broker. If I happen to create a topic containing an invalid character ( e.g. _home+_ ) and publish a message to it, the broker disconnects the client. Since this is ManagedClient, the invalid publish will be reattempted again and again resulting in connection drop and reconnections in an infinite loop.  

1. This could be considered a bug in the application, but still, can some kind of validation be added in ManagedClient to ignore invalid publish attempts to avoid connect/reconnect infinite loop? 
2. When using ManagedClient the lib user is not aware if each individual message is correctly published - Should some of kind of exception/callback be invoked to let the lib user know of a publish success/failure?

**Comment by chkr1011** [comment]
HI,
that is indeed a good idea. I will add this to all methods which are publishing messages.

Best regards
Christian

**Comment by chkr1011** [comment]
This is added in Alpha 3.
