### ISSUE TITLE
V3.0.0 Alpha3 example?

### ISSUE THREAD

**Issue by frankygoop** [chkr1011/MQTTnet#582]
Any where to find the new event handler alpha3 examples?
thanks

**Comment by chkr1011** [comment]
Sorry but the Wiki is not yet updated. But in the UnitTests you can find some ways how to use that handlers like here: https://github.com/chkr1011/MQTTnet/blob/a7204234f61a84decdcc3999d24b78e588be8cbf/Tests/MQTTnet.Core.Tests/MqttClientTests.cs#L123-L128

**Comment by djarvis** [comment]
Can I UN-USE a message received handler?  Often throughout my pre-v3 code I add a message handler temporarily to handle something, then remove it.
