### ISSUE TITLE
Received packet 'PubRec: [PacketIdentifier=23973] [ReasonCode=]' at an unexpected time.

### ISSUE THREAD

**Issue by GieltjE** [chkr1011/MQTTnet#583]
During high load situations (the kind where the mouse starts lagging or on slower VM's), the following occurs:

``` MqttProtocolViolationException: Received packet 'PubRec: [PacketIdentifier=23973] [ReasonCode=]' at an unexpected time.```

This triggers a crash:
```System.AggregateException: 'A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.'```

Is this a bug in the library or is there a way to properly handle this exception

**Comment by chkr1011** [comment]
Do you have some code to reproduce that issue? Could you also please try it with latest ALPHA of 3.0.0?

**Comment by GieltjE** [comment]
Sorry I forgot to mention all the important bits, this is using the 3.0.0-alpha3 version.
Running for 8+ hours usualy, using a singular connection to an mqtt server over which roughly every second a message is received and one is sent (sometimes more sometimes less).

When we run it on a virtual machine (KVM), it starts breaking fast, on my development machine in debug mode it takes a long time.

**Comment by chkr1011** [comment]
I added some test cases in the test app (not unit tests). Also for QoS 2. Is it possible to run that code in your VM? Please let me know if the error still occurs. On my machine I cannot reproduce it. Maybe I need to run it longer?

**Comment by GieltjE** [comment]
I'm about to go on a holliday, after I'm back the first thing I'll try is the new code.
It does need to run for long times with high loads (usualy 8+ hours orso).

**Comment by GieltjE** [comment]
Have these test cases been added to 3.0.0-beta1 or should I still run against the source?

**Comment by chkr1011** [comment]
Please try the latest dev branch.

**Comment by SeppPenner** [comment]
@GieltjE Does this still occur in the latest version?

**Comment by GieltjE** [comment]
Have been to busy to properly debug it, but haven't noticed it lately.

**Comment by SeppPenner** [comment]
@GieltjE Ok, thanks. Just re-open this issue or add another one if this still occurs.
