### ISSUE TITLE
MQTTnet.Exceptions.MqttCommunicationTimedOutException (3.0.0-alpha3) with MqttQualityOfServiceLevel.AtLeastOnce

### ISSUE THREAD

**Issue by ramonsmits** [chkr1011/MQTTnet#587]
While testing 3.0.0-alpha4 I get the following exception:
```
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.WaitOneAsync(TimeSpan timeout)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.PublishAtLeastOnceAsync(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
```

Getting this after I transitioned to the async methods although I'm not certain that v3 is the cause.

Easily reproducable by just PublishAsync a bunch of messages with `MqttQualityOfServiceLevel.AtLeastOnce` set. There are blocking and eventually result in the timeouts.

This is with RabbitMQ as the broker.

**Comment by chkr1011** [comment]
Please share some code example. I let the client run for like 1 h and constantly sending QoS1 messages but it works perfectly.

**Comment by ramonsmits** [comment]
@chkr1011 I'll try and create a minimalistic repro, I have the same with beta1

**Comment by chkr1011** [comment]
Do you mean develop branch? Because there is no Alpha4!?

**Comment by ramonsmits** [comment]
@chkr1011 Sorry, seems it was alpha3 when I look at the nuget packages

**Comment by SeppPenner** [comment]
@ramonsmits Did you find something or is this issue fixed?

**Comment by ramonsmits** [comment]
@SeppPenner yeah, solution is mentioned in https://github.com/chkr1011/MQTTnet/issues/648 which is to not publish using the same client that does the receive as that seems to not be supported. Not sure if that is a limitation by mqttnet or by the mqtt protocol itself.

**Comment by SeppPenner** [comment]
> @SeppPenner yeah, solution is mentioned in #648 which is to not publish using the same client that does the receive as that seems to not be supported. Not sure if that is a limitation by mqttnet or by the mqtt protocol itself.

This should be possible: https://stackoverflow.com/questions/49484629/mqtt-publish-subscribe-in-the-same-client. Seems to be a bug than.

**Comment by ramonsmits** [comment]
@SeppPenner Not sure what that link would mean.

I think a mqttnet client represents one channel. So far it seems that you can publish and receive with at-least-once but not at the same time. That SO post doesnt make that clear.

**Comment by SeppPenner** [comment]
> That SO post doesnt make that clear.

That's what I meant. I was searching for some reference and didn't read properly on the first view.
