### ISSUE TITLE
TLS Support reconnect

### ISSUE THREAD

**Issue by donhauro** [chkr1011/MQTTnet#590]
Hi,

thank you for sharing your library!

I encountered a problem using Tls. 
My Broker only allows Tls connections.

If I try to connect my Client without Tls, I don't see an error message. 
It seems that the client hangs on ConnectAsync.

I want to cancel the first connection and start a second attempt with tls settings.

If I use ManagedClient the Client stays in starting Mode. If I try to start another Connection with Tls results in an exceptino Client is already started.

Thanks in advance

**Comment by chkr1011** [comment]
Hi,
please try with latest beta version. A TLS fix was applied recently.
Best regards
Christian

**Comment by donhauro** [comment]
Thank you very much!

Best Regards

Roland

Christian <notifications@github.com> schrieb am Mi., 10. Apr. 2019, 23:26:

**Comment by donhauro** [comment]
The Problem seems to be solved.

Thanks

Christian <notifications@github.com> schrieb am Mi., 10. Apr. 2019, 23:26:
