### ISSUE TITLE
`mqttServer.GetClientSessionsStatus( ).Count` is not equal to the real clientconnection count

### ISSUE THREAD

**Issue by pilgrimzh** [chkr1011/MQTTnet#595]
I print  `mqttServer.GetClientSessionsStatus( ).Count`  when client disconnected by Power off  or new cliented connected .   i set server connnection  timeout 300s, but after that the count always not euqal real client connections count.

**Comment by chkr1011** [comment]
Hi, this might happen because sessions and connections are different things. A session remains after disconnect and can be resumed later. A connect is there or not. 
Which version do you use? Since v3.0.0 there are different APIs added for sessions and connections.

**Comment by pilgrimzh** [comment]
version 2.8.5 .  you means that    fix it since 3.0.0 ? thank you

**Comment by chkr1011** [comment]
Yes that should be fixed (changed) in 3.0.0.
