### ISSUE TITLE
WithConnectionValidator gives too little time to validate the client

### ISSUE THREAD

**Issue by Grafu** [chkr1011/MQTTnet#597]
When using WithConnectionValidator to validate the client, the server has to quickly answer to the client, otherwise client gets validated without any checking. I find this very frustrating because it is not enough time to access the DB and get the row with the password for the client.

**Comment by chkr1011** [comment]
Please try with latest 3.0.0. in this version the calls are supporting async and will wait all the time you need to pull the data from somewhere else.

**Comment by Grafu** [comment]
I updated to 3.0.0 and it still fails to correctly validate the connection. And yes, it can be related to async because I am using an async method for validating the connection.

**Comment by chkr1011** [comment]
Please share a small example to reproduce it.

**Comment by Grafu** [comment]
https://pastebin.com/37JVsyE6
https://pastebin.com/gBM85QHK

**Comment by chkr1011** [comment]
Your pasted code is still 2.8.5 and not 3.0.0 as proposed. Please migrate it to 3.0.0-rc1 and please share another snipped. I checked the code and it should work perfectly.
