### ISSUE TITLE
Cancel "ApplicationMessageReceived" event

### ISSUE THREAD

**Issue by LucasSossai** [chkr1011/MQTTnet#599]
I didn't find any method to cancel the "ApplicationMessageReceived" event, 
for example:
If I start with:

`mqttClient.ApplicationMessageReceived += (s, e) =>
            {
                Debug.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
                Debug.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                Debug.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
            };`

And want to change to 

`mqttClient.ApplicationMessageReceived += (s, e) =>
            {
                Debug.WriteLine("### CHANGED THE WAY I HANDLE THE MESSAGE ###");
                Debug.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                Debug.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
            };`

can I do it?

**Comment by chkr1011** [comment]
Hi, you can detach your old event handler via -=. But you need to create a method for it. An anonymous function cannot be detached.
Best regards
Christian
