### ISSUE TITLE
(Bug) MqttCommunicationException on ConnectAsync

### ISSUE THREAD

**Issue by Zazzmatazz** [chkr1011/MQTTnet#6]
Version 2.1.3 has a connection bug it seems.

A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer)
   at MQTTnet.Core.Serializer.MqttPacketWriter.WriteToAsync(IMqttCommunicationChannel destination)
   at MQTTnet.Core.Serializer.DefaultMqttV311PacketSerializer.SerializeAsync(MqttConnectPacket packet, IMqttCommunicationChannel destination)
   at MQTTnet.Core.Serializer.DefaultMqttV311PacketSerializer.SerializeAsync(MqttBasePacket packet, IMqttCommunicationChannel destination)
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<SendPacketAsync>d__5.MoveNext()

This occurs with and without TLS enabled.  The only thing I can gather so far is that the connection fails (via [MqttClient.cs line 61](https://github.com/chkr1011/MQTTnet/blob/master/MQTTnet.Core/Client/MqttClient.cs#L61)) before the packet is sent (at [MqttClient.cs line 74](https://github.com/chkr1011/MQTTnet/blob/master/MQTTnet.Core/Client/MqttClient.cs#L74)).

Can anyone else confirm this issue?

For the record, my `MqttClientOptions` are:

```CSharp
MqttClientOptions opts = new MqttClientOptions
{
    ClientId = Guid.NewGuid().ToString(),

    UserName = "flight|eedovmDCY48yEZtlXPdJwfeayNK5",
    Password = "...",

    Server = "ssl://mqtt-prod.airmap.io",
    Port = 8883,

    CleanSession = true,
    KeepAlivePeriod = TimeSpan.FromSeconds(15),
    DefaultCommunicationTimeout = TimeSpan.FromSeconds(2)
};
```

**Comment by chkr1011** [comment]
Hi, please try without the "ssl://" prefix. Such a prefix is not supported in the library because the new "UseTsl" flag is used for this.

**Comment by Zazzmatazz** [comment]
Yep, that'd do it.  Perhaps a case to allow ssl:// prefixes (if it's detected, automatically set the `UseTLS` flag).

**Comment by chkr1011** [comment]
If you would like to use it you can still create a pull request and add this. But you need to check the options because ssl:// and "UseTsl=false" does not make sense.
