### ISSUE TITLE
Certificate example

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#60]
Hi,

can you please write an example of how to use the certificate for TLS encryption?
I couldn't find the way how to do it.
Thanks =)

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
Hi,
I really want to but I am not an expert with certificates. I personally don't use that feature. I just exposed the API from the .NET Framework. It is possible to share some error details. If we fix your issues I can maybe use it for an example.

Best regards
Christian

**Comment by Zuendelmeister** [comment]
Hi again,

maybe we can solve this together. This is what I did:
Broker:

> var options = new MqttServerOptions
            {
                ConnectionValidator = p =>
                {
                    Console.WriteLine("New");
                    Console.WriteLine(p.ClientId);
                    return MqttConnectReturnCode.ConnectionAccepted;
                }
            };
            options.TlsEndpointOptions.IsEnabled = true;       //message will be encrypted
            options.TlsEndpointOptions.Certificate = File.ReadAllBytes(@"C:\Certs\cert.pem");
            var mqttServer = new MqttServerFactory().CreateMqttServer(options);
            mqttServer.ApplicationMessageReceived += (s, e) =>
            {
                string messageString = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);
                try
                {
                    Dictionary<string, string> messageProperty = new Dictionary<string, string>();
                    Console.WriteLine(e.ClientId + " sent " + messageString);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            };
            Console.WriteLine("Starting MqttBroker");
            await mqttServer.StartAsync();
            Console.WriteLine("MqttBroker started");
            Console.ReadLine();

Client:

> var mqttClient = new MqttClientFactory().CreateMqttClient();
            var secureTcpOptions = new MqttClientTcpOptions
            {
                Server = "127.0.0.1",
                ClientId = "TestClient",
                TlsOptions = new MqttClientTlsOptions
                {
                    UseTls = true,
                    IgnoreCertificateChainErrors = true,
                    IgnoreCertificateRevocationErrors = true,
                    AllowUntrustedCertificates = true
                }
            };
            await mqttClient.ConnectAsync(secureTcpOptions);
            mqttClient.Disconnected += async (s, e) =>
            {
                Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                await Task.Delay(TimeSpan.FromSeconds(5));
                try
                {
                    await mqttClient.ConnectAsync(secureTcpOptions);
                }
                catch
                {
                    Console.WriteLine("### RECONNECTING FAILED ###");
                }
            };

Without TLS it works fine but if I enable it like in the example above the Broker doesn't even realize that the client wants to connect.
Maybe I did something obvious wrong? I don't see my fault though yet since I told the client to allow all certificates.
Thanks again.

Best regards,
Zuendelmeister

**Comment by RainerMueller82** [comment]
Hi!

I'm facing the same problem here.

Without TLS all is fine, when I try to enable it, the client cannot connect and runs into a timeout.

When I try to use TLS, I just add the following lines of code:

Broker:
			options.TlsEndpointOptions.Certificate = File.ReadAllBytes("server.crt");
			options.TlsEndpointOptions.IsEnabled = true;

Client:
			var tlsOptions = new MqttClientTlsOptions
			{			    
			        UseTls = true,
			        IgnoreCertificateChainErrors = true,
			        IgnoreCertificateRevocationErrors = true,
			        AllowUntrustedCertificates = true			        	
			};
			tlsOptions.Certificates= new List<byte[]> {File.ReadAllBytes("ca.crt")};
			
			var tcpOptions = new MqttClientTcpOptions 
			{
			    Server = "localhost",
			    ClientId = "TestClient"		   
					    
			    TlsOptions = tlsOptions
			};

BR,
Rainer.

**Comment by JTrotta** [comment]
Activate the custom validation, and check what's happen there:
` MqttTcpChannel.CustomCertificateValidationCallback`

**Comment by RainerMueller82** [comment]
Hi!

Can you explain this a bit more detailed? Where should I set this callback?

**Comment by RainerMueller82** [comment]
I just managed to get the MQTTnet client working with a gnatMQ broker using TLS 1.2.

Perhaps we should focus on the broker ...

**Comment by JTrotta** [comment]
Ok, but it works with other broker too.
You should use the CustomCertificateValidationCallback on client, to check if the server reply to you with the certificates chain.
Let us know.
JJ

**Comment by RainerMueller82** [comment]
Hi!
I've put the validation callback in the client code, but it is not hit. Not with the MQTTnet broker and not with the gnatMQ broker.

:-(

**Comment by JTrotta** [comment]
Strange,
that's my options:
`            _mqttOptions = new MqttClientTcpOptions();
            _mqttOptions.CleanSession = true;
            _mqttOptions.ClientId ="TEST";
            _mqttOptions.DefaultCommunicationTimeout = TimeSpan.FromSeconds(20);
            _mqttOptions.KeepAlivePeriod = TimeSpan.FromSeconds(31);

            _mqttOptions.Port = 1883;
            _mqttOptions.Server = MQTTBrokerEndPointIP;
            _mqttOptions.UserName = MQTTUserName;

            if (MQTTUseCertificates)
            {
                _mqttOptions.Port = 8883;
                _mqttOptions.TlsOptions = new MqttClientTlsOptions
                {
                    UseTls = true,
                    AllowUntrustedCertificates = true,
                    IgnoreCertificateChainErrors = true,
                    IgnoreCertificateRevocationErrors = true
                };
                MqttTcpChannel.CustomCertificateValidationCallback = remoteValidation;
            }`

It works
JJ

**Comment by RainerMueller82** [comment]
Ok, now the Validation-Callback is hit when I'm using the gnatMQ broker, but not with the MQTTnet one.

I really think the problem is on the server-side.

How do you pass your certificate?

This is my configuration:

options.TlsEndpointOptions.Certificate = new X509Certificate2(File.ReadAllBytes("server.pfx"), "password").RawData;
			options.TlsEndpointOptions.IsEnabled = true;			

			MqttTcpChannel.CustomCertificateValidationCallback = remoteValidation;

			mqttServer = new MqttServerFactory().CreateMqttServer(options);

**Comment by Zuendelmeister** [comment]
Thanks everyone for looking into this. I changed my Code to set the certificate like RainerMueller82 did.
Unfortunately "MqttTcpChannel.CustomCertificateValidationCallback = remoteValidation;" shows an error. What is this remoteValidation?
And even with the certificate set right nothing happens. The broker doesn't get  a connection from the client.
Ideas?

**Comment by JTrotta** [comment]
You're right, I forgot it
remote validation:
`        private bool remoteValidation(X509Certificate certificate,
            X509Chain chain,
            System.Net.Security.SslPolicyErrors sslPolicyErrors,
            MqttClientTcpOptions options)
        {
            //check certificate and return true or false
            return true;
        }`

**Comment by Zuendelmeister** [comment]
I think I tried everything that is mentioned but I still get a timeout.
Ok so this is my Code right now:
Client:
> class Program
    {
        private static bool remoteValidation(X509Certificate certificate, X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors, MqttClientTcpOptions options)
        { return true; }
          //{ //check certificate and return true or false return true; }
            static void Main(string[] args)
        {
            testi();
            Console.ReadLine();
        }
        private static async void testi()
        {
            var mqttClient = new MqttClientFactory().CreateMqttClient();
            var _mqttOptions = new MqttClientTcpOptions();
            _mqttOptions.CleanSession = true;
            _mqttOptions.ClientId = "TEST";
            _mqttOptions.DefaultCommunicationTimeout = TimeSpan.FromSeconds(20);
            _mqttOptions.KeepAlivePeriod = TimeSpan.FromSeconds(31);
            _mqttOptions.Server = "127.0.0.1";
            _mqttOptions.UserName = "MQTTUserName";
            _mqttOptions.Port = 8883;
            _mqttOptions.TlsOptions = new MqttClientTlsOptions
            {
                UseTls = true,
                AllowUntrustedCertificates = true,
                IgnoreCertificateChainErrors = true,
                IgnoreCertificateRevocationErrors = true
            };
            MqttTcpChannel.CustomCertificateValidationCallback = remoteValidation;
            await mqttClient.ConnectAsync(_mqttOptions);
            mqttClient.Disconnected += async (s, e) =>
            {
                Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                await Task.Delay(TimeSpan.FromSeconds(5));
                try
                {
                    await mqttClient.ConnectAsync(_mqttOptions);
                }
                catch
                {
                    Console.WriteLine("### RECONNECTING FAILED ###");
                }
            };
        }
    }

And this is my Broker:

> public static async void broker()
        {
            Console.WriteLine("Starting");
            var options = new MqttServerOptions
            {
                ConnectionValidator = p =>
                {
                    Console.WriteLine("New");
                    Console.WriteLine(p.ClientId);
                    return MqttConnectReturnCode.ConnectionAccepted;
                }
            };
            options.TlsEndpointOptions.IsEnabled = true;       //message will be encrypted
            options.TlsEndpointOptions.Certificate = new X509Certificate2(File.ReadAllBytes(@"C:\Certs\cert.pem")).RawData;
            var mqttServer = new MqttServerFactory().CreateMqttServer(options);
            mqttServer.ApplicationMessageReceived += (s, e) =>
            {
                string messageString = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);
                try
                {
                    Dictionary<string, string> messageProperty = new Dictionary<string, string>();
                    Console.WriteLine(e.ClientId + " sent " + messageString);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            };
            Console.WriteLine("Starting MqttBroker");
            await mqttServer.StartAsync();
            Console.WriteLine("MqttBroker started");
            Console.ReadLine();
        }

Am I doing something wrong?
Thanks guys =) Great to see that there are helping hands.

Best regards, 
Zuendelmeister

**Comment by chkr1011** [comment]
Thanks you sharing code! I am also testing on my own. Maybe some hints:
1) The implementation is different per Platform (UWP etc.). Wich are you using @Zuendelmeister 
2) Good to read that maybe the broker is the root cause.
2 a) @Zuendelmeister Can you provide a trace using the _MqttNetTrace_? I want to see if a connection is made at TCP level (at least). Or if we see an exception.
3 b) Assuming you are using .NET Framework the code where the certificate is used is this:

```csharp
var sslStream = new SslStream(new NetworkStream(clientSocket));
await sslStream.AuthenticateAsServerAsync(_tlsCertificate, false, SslProtocols.Tls12, false).ConfigureAwait(false);
```

Maybe some research for a working example even without MQTT would be a good starting point.
The certificate is loaded using:

```csharp
_tlsCertificate = new X509Certificate2(options.TlsEndpointOptions.Certificate);
```
I have no idea if the _RawData_ propety is sufficient or if you should load the bytes from the file directly. I don't know if a _.cert_ file or a _.pfx_ or whatever file is required here.

**Comment by Zuendelmeister** [comment]
Hi @chkr1011,
1.: I'm using this library for net core (so NetStandard).
2. I would certainly provide a trace, but never uset MqttNetTrace before. How do I do it? How do I define the clientSocket? Can you please provide an example for NetStandard?

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment]
The class _MqttNetTrace_ has a static event. You can attach to it and write a line with all information from the event args to the Console (I will add an example for it at the weekend or so).

I will search for it. But I assume I can support you here not before the weekend.

**Comment by chkr1011** [comment]
@Zuendelmeister Do you have some trace for us?

**Comment by Zuendelmeister** [comment]
@chkr1011 no not yet, I thought you want to provide some example code on how to use MqttNetTrace?

**Comment by chkr1011** [comment]
Oh yes sorry I updated the Wiki already.

**Comment by Zuendelmeister** [comment]
Ah thanks, I didn't see that. Here is what I got:
>> [1] [MqttClient] [Verbose]: Trying to connect with server.
>> [5] [MqttClient] [Information]: Disconnected from adapter.

Doesn't seem too helpfull though.

**Comment by chkr1011** [comment]
And the server is running in the same process?

**Comment by Zuendelmeister** [comment]
Aah sry that was wrong by me.
>> [7] [MqttServerAdapter] [Error]: Error while accepting connection at TLS endpoint.
System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttServerAdapter.<AcceptTlsEndpointConnectionsAsync>d__12.MoveNext()

**Comment by chkr1011** [comment]
There you have it. You need the private key in the certificate. I will consider adding an exception in the _StartAsync_ method which will check this to avoid confusion.

**Comment by Zuendelmeister** [comment]
I see. So somehow I have to create a certificate with a private key. I take a deeper look and get back to you.

**Comment by JTrotta** [comment]
Look here:
`X509Certificate2 ca = new X509Certificate2(Path.Combine(Environment.CurrentDirectory, "certificate.pem"));     
byte[] certifacetWithKey = ca.Export(X509ContentType.Pfx);`

One X509ContentType enumerator will export the private key.
JJ

**Comment by RainerMueller82** [comment]
Hi!

I'm using the Pfx file. Is this file not already a certificate/key
combination?

BR, Rainer.

2017-10-16 13:00 GMT+02:00 Gerardo <notifications@github.com>:

**Comment by Zuendelmeister** [comment]
@JTrotta, thank you so much =) I try this out when I can. I found another way to create a certificate with a private key and that works quit fine.
For the Wiki I try to to summarize:
I created a key and certificate like described here: https://errorin10.wordpress.com/2017/08/25/install-apache2-with-sllhttps-on-ubuntu/ under "create certificate" with openssl.
Next I created a certificate  with the private key with "makecert" (in the Windows Software Development Kit)
`makecert.exe -sky exchange -r -n "CN=selfsigned.crt" -pe -a sha1 -len 2048 -ss My "test.cer"`
(where test.cer is the final certificate and selfsigned.crt is the certificate I created earlier).

Now I loaded the certificate like so:
`var certificate = new X509Certificate(@"C:\certs\test\test.cer", "");
            options.TlsEndpointOptions.Certificate = certificate.Export(X509ContentType.Cert);`
Which worked fine:
> [1] [MqttServer] [Information]: Started.
MqttBroker started
>> [3] [MqttChannelCommunicationAdapter] [Information]: RX <<< MqttConnectPacket: [ClientId=TEST] [Username=MQTTUserName] [Password=] [KeepAlivePeriod=31] [CleanSession=True]
New
TEST
>> [3] [MqttClientSessionsManager] [Verbose]: Created a new session for client 'TEST'.
>> [3] [MqttChannelCommunicationAdapter] [Information]: TX >>> MqttConnAckPacket: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=False] [Timeout=00:00:15]
>> [7] [MqttServer] [Information]: Client 'TEST': Connected.
> 

>

**Comment by chkr1011** [comment]
Thank you for your support. I will write a Wiki entry basing on this.

**Comment by inforaudio** [comment]
> 
> 
> I just managed to get the MQTTnet client working with a gnatMQ broker using TLS 1.2.
> 
> Perhaps we should focus on the broker ...
> netstat says the server port is open (8883) and listening ...

Can you share the code for connect By TLS using gnat library?
