### ISSUE TITLE
How to add validation client  account after Mqtt service  has been started

### ISSUE THREAD

**Issue by masterchen** [chkr1011/MQTTnet#601]
valid user account can be added like this before server starting:
  var optionsBuilder = new MqttServerOptionsBuilder()
                    .WithConnectionBacklog(100)
                    .WithDefaultEndpointPort(8222)
                    .WithConnectionValidator(ValidatingMqttClients());

If i want to add more user after server started how to do , many thanks

**Comment by chkr1011** [comment]
Hi,
this is up to your code. The _WithConnectionValidator_ is passed only one time before start but inside that method you can do whatever you want. So access a dynamic storage like a DB or a file which is read whenever a connection needs to be validated. Then you can extend that file at runtime etc.

Changing the validator at runtime is not supported.

Best regards
Christian
