### ISSUE TITLE
Webapi connection mqtt is always disconnected and cannot connect successfully

### ISSUE THREAD

**Issue by 0zhouquan0** [chkr1011/MQTTnet#604]
Webapi connection mqtt is always disconnected and cannot connect successfully

**Comment by chkr1011** [comment]
Hi,
what exactly do you mean with "Webapi"? Please provide example code so I can try to reproduce it locally.
Best regards
Christian

**Comment by 0zhouquan0** [comment]
Thanks, I have solved this problem, webconfig, missing
       <dependentAssembly>
         <assemblyIdentity name="System.Net.Sockets" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
         <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0"/>
       </dependentAssembly>
So it will always fail to connect.
