### ISSUE TITLE
Local Build on vs2017

### ISSUE THREAD

**Issue by angadsule** [chkr1011/MQTTnet#608]
i m not able to build on local server.

**Comment by chkr1011** [comment]
Please give me some more information.

**Comment by angadsule** [comment]
![image](https://user-images.githubusercontent.com/21181620/56847076-4165a480-68f4-11e9-86c9-384656c0003d.png)

**Comment by chkr1011** [comment]
You need to install the UWP SDK or use the NoUWP solution file instead.

**Comment by angadsule** [comment]
I tried using the NoUWP solution file but same problem, can u please guide me / provide me link for UWP SDK coz i think i have installed that also...but to make sure please provide me the SDK link.

**Comment by chkr1011** [comment]
You need to select the UWP workload in VS Setup.

**Comment by angadsule** [comment]
Can you please Guide me with Same, pretty much new to IOT

**Comment by chkr1011** [comment]
You will find all information here: https://docs.microsoft.com/en-us/windows/uwp/get-started/

But I recommend to use the _MQTTnet.noUWP.sln_ instead. If this still fails please post the error.
