### ISSUE TITLE
MQTT ExactlyOnce and AtLeastOnce

### ISSUE THREAD

**Issue by JTrotta** [chkr1011/MQTTnet#61]
Hello,
The MQTT protocol has 3 publish type. The last two (whose name are in the object), can inform the client that the message has been received with 100% of reliability.
Would be nice to have this information published, i.e. when using ::
`public static Task PublishAsync(this IMqttClient client, params MqttApplicationMessage[] applicationMessages);`

You should return some object result with SENT or not SENT information

JJ

**Comment by chkr1011** [comment]
Hi,
this is already available. An exception is thrown if the publish process has failed for any reason. This means that every QoS has worked if no exception was thrown.

Best regards
Christian

**Comment by JTrotta** [comment]
I will test, and let you know.
JJ

**Comment by JTrotta** [comment]
You mean that this code raise into catch if PublishAsync was not successful?
`                    
try{
var applicationMessage = messageFactory.CreateApplicationMessage(topic, Encoding.UTF8.GetBytes(strMsg), MqttQualityOfServiceLevel.ExactlyOnce,false);
 await _client.PublishAsync(applicationMessage);
}
catch (Exception e)
{

}
`
Regards
JJ

**Comment by JTrotta** [comment]
I did some tests. It seems that after DefaultCommunicationTimeout is thrown an exception, but the client does not not which message has not been received by the server. Isn't it ?
A client that sends a QOS 3 message wants to be sure the server received it. It can be done using the MQTTNET internal queue, and re sending it after the re-connection, or informing the client that messages 1,2...n, have not been received.

JJ

**Comment by chkr1011** [comment]
Yes you are right. If you send multiple ones you don't know which where send and which not. At the moment the only way for you is to add a layer on top like _QueuedMqttClient_ i.e. Also there is no internal queue in the client. If QoS 3 fails directly it is not retried. But I will consider creating a _QueuedMqttClient_ in a future version which sits on top of the _MqttClient_ and has a queue and property result. 

For now you can send every message as a single one with a try-catch statement. If the QoS is 0 you can drop the message or retry it later using your own rules.

**Comment by JTrotta** [comment]
Ok,
I will wrote a PR with a concurrentqueue to manage sent/unsent message.
JJ

**Comment by chkr1011** [comment]
@JanEggers OK please implement it as an extension. So a new Client wich uses the original client. Then users can decide to use the existing one or the new one with predefined rules. The actual _MqttClient_ should as simple as possible.

**Comment by JTrotta** [comment]
@chkr1011 , Mqttnet.Core is .net stantard 1.1 target framework. Would it be possible to update it to 2.0?
Because 1.1 does not have file system API, I need it for persistence.
JJ

**Comment by chkr1011** [comment]
@JTrotta Upgrading to .netstandard 2,0 is on the list but at the moment not possible. For UWP support for 2.0 will come with the official "Fall Creators Update". And I want to limit this library to only "cutting edge" frameworks. The goal is to support at least .NET 4.5.2. This also still supported by Microsoft.

But 1.1 is compatible with 2.0. You can reference it from a 2.0 project and use it.

**Comment by chkr1011** [comment]
@JTrotta Based on your work I refactored the "managed" client. I also added connection maintenance. I added test code to the app core test app. Please test if also the storage works for you. The client will re en-queue all failed messages higher than QoS 0. The storage always receives all queued messages. You can also add messages and start the client later.

Also the subscriptions are managed. After a reconnect the subscriptions are automatically sent again. At the moment persistent server sessions are not supported.

**Comment by JTrotta** [comment]
Thank you Christian, looks good. I see it was not possible to use the previous MqttClient version without some changes.
I will test it on Mono mobile application next Thursday, and let you know.
Thank you again.
JJ

**Comment by chkr1011** [comment]
Yes some very minor changes are required 😄 . I will close this ticket. If you experience some issues after your tests please reopen it or create a new one.

**Comment by neodevit** [comment]
Hi 
i have solve a problem but my client queued many nessage
now i debug the application and after connect client to mqtt receive 1 message
and stop, when I redebug a code receive another message, is possible clean the queued message I uso Mosquitto server
