### ISSUE TITLE
@chkr1011

### ISSUE THREAD

**Issue by panyi-dotnet** [chkr1011/MQTTnet#610]
when target to net461,  Framework dll files are copied to the target directory. eg netstandard.dll .

![15368261083546](https://user-images.githubusercontent.com/6744243/45475586-68110980-b76f-11e8-9dba-2681197b2189.png)
![15368260724568](https://user-images.githubusercontent.com/6744243/45475592-6a736380-b76f-11e8-8b4c-4c0759ba8115.png)

_Originally posted by @panyi-dotnet in https://github.com/chkr1011/MQTTnet/issues/411#issuecomment-420921694_

**Comment by panyi-dotnet** [comment]
v 3.0

**Comment by chkr1011** [comment]
Hi,
this is correct because in nuspec we use netstandard library because .net 4.6.1+ support them properly.

Best regards
Christian

**Comment by chkr1011** [comment]
Please try with 3.0.1.
