### ISSUE TITLE
Cannot connect to MQTT over Websocket with Xamarin

### ISSUE THREAD

**Issue by VircomSheep** [chkr1011/MQTTnet#612]
Hi, 

I tried to connect to the AWS iot core over Websockets in my Xamarin App and it fails. 

This is how I connect:

```
            var optionsBuilder = new MqttClientOptionsBuilder();
            WebsocketUrlSigner signer = new WebsocketUrlSigner();
            var credentials = CognitoSession.Current.CurrentCredentials.GetCredentials();            
            Credentials c = new Credentials()
            {
                AccessKeyId = credentials.AccessKey,
                SecretKey = credentials.SecretKey,
                SessionToken = credentials.Token
            };
            var url = signer.GetWebsocketUrl(c);

            optionsBuilder.WithWebSocketServer(url);
            optionsBuilder.WithClientId(clientId);  
            optionsBuilder.WithProtocolVersion(MqttProtocolVersion.V311);
            

            MqttClientOptionsBuilderTlsParameters tlsParams = new MqttClientOptionsBuilderTlsParameters()
            {
                UseTls = true,
                SslProtocol = System.Security.Authentication.SslProtocols.Tls12
            };
            optionsBuilder.WithTls(tlsParams);

            options = optionsBuilder.Build();
```
The url is a signed url with SigV4 with the cognito AccessKey, SecretKey and Token.

When I call client.ConnectAsync(options) I get the following Exception:

{MQTTnet.Exceptions.MqttCommunicationException}:
Message: "Unable to connect to the remote server" 
Source: mscorlib
StackTrace:
  at MQTTnet.Adapter.MqttChannelAdapter.WrapException (System.Exception exception) [0x0005a] in <0cba824eb1f047f28db40a990343853f>:0 
  at MQTTnet.Adapter.MqttChannelAdapter+<ConnectAsync>d__20.MoveNext () [0x000bf] in <0cba824eb1f047f28db40a990343853f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at MQTTnet.Client.MqttClient+<ConnectAsync>d__30.MoveNext () [0x00152] in <0cba824eb1f047f28db40a990343853f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at MQTTnet.Client.MqttClient+<ConnectAsync>d__30.MoveNext () [0x00356] in <0cba824eb1f047f28db40a990343853f>:0 
--- End of stack trace from previous location where exception was thrown ---

In the inner exception there is a WebSocketErrorCode and it says "System.Net.WebSockets.WebSocketError.Success" 

In a little Windows Forms test application with the same parameters it works. 

Do I miss something in the parameters for Xamarin? 

Any help appreciated.

**Comment by prokis65** [comment]
Hi,
Cristian built a test adapter factory supporting WebSocket4Net. See
https://mail.google.com/mail/u/0/?tab=rm#search/aws/FMfcgxmZTvKnrmSKSpwjSDsqMtfSwmJL

I didn't test it a lot but it worked.
I'm realy interested in AWS IOT and it is a pity that there is still an issue with it.

**Comment by dealproc** [comment]
I know I had been working with this library and webSockets using the server pieces of the library on the other end.  give me some time, and i'll look up how I wrote the connection.  I was using username/password authentication, which may make a difference.

**Comment by chkr1011** [comment]
I released a new extension nuget which allows using WebSocket4Net. All you need to do is download the new nuget and call _UseWebSocket4Net()_ on the _MqttFactory_ instance before creating the client. Please let me know if this works with AWS/Xamarin.

**Comment by prokis65** [comment]
I updated MQTTnet to 3.0.2.
Which extention nuget should I install to call UseWebSocket4Net() ?

**Comment by chkr1011** [comment]
https://www.nuget.org/packages/MQTTnet.Extensions.WebSocket4Net/3.0.3-rc1
