### ISSUE TITLE
Session Present in version 3.0.0

### ISSUE THREAD

**Issue by avengerstark** [chkr1011/MQTTnet#613]
Hi there!
When client connect to server with CleanSession, the server must set Session Present to 0 in the CONNACK packet(MQTT Documentation, section 3.2.2.2 ), but in version 3 set 1. In version 2.8.5 this works correctly.

**Comment by chkr1011** [comment]
Hi, 
thank you for reporting this issue. I fixed it and will release a new version soon. 
Best regards
Christian
