### ISSUE TITLE
mqttv5 client cannot receive ResponseTopic,CorrelationData

### ISSUE THREAD

**Issue by pcbing** [chkr1011/MQTTnet#616]
MqttV500DataConverter.cs
public MqttApplicationMessage CreateApplicationMessage(MqttPublishPacket publishPacket)
        {
            return new MqttApplicationMessage
            {
                Topic = publishPacket.Topic,
                Payload = publishPacket.Payload,
                QualityOfServiceLevel = publishPacket.QualityOfServiceLevel,
                Retain = publishPacket.Retain,
                UserProperties = publishPacket.Properties?.UserProperties ?? new List<MqttUserProperty>()
            };
        }

**Comment by chkr1011** [comment]
Hi,
thank you for reporting this issue. I added these to the message class and will release a new version soon.
Best regards
Christian
