### ISSUE TITLE
cleanup project / reduce duplicated code

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#62]
i would like to submit a pr that deletes .net framework projects and adds net45 or net46 as targetframework to the .net.sdk based projects.

net45 would mean same compatibility but 3 ifdefs
net46 requires higher dependency but no ifdef required

@chkr1011 thoughts?

**Comment by chkr1011** [comment]
Sorry but I don't get it 😄 Maybe because it is to late (here) 😄 

You want to delete the .net framework platform project right. This is OK if .NET 4.5 is still supported in another way. But what do you mean with ".net.sdk"? Do you mean netstandard?

In general some #ifdef are not a problem for me. I was also thinking about it because at the moment it is a lot copy & paste. Too much in my opinion.

**Comment by JanEggers** [comment]
i created a pr and added a comment on the sdk thing i was referring to.

**Comment by JanEggers** [comment]
maybe this change is also an option for uwp but i didnt port that because uwp does things different and the testapp is much different too

**Comment by chkr1011** [comment]
I can see that the BufferedStream is no longer used!? Was it used in the regular .NET Framework project? If it is not used I assume we can remove the "Raw" Stream?

**Comment by JanEggers** [comment]
thx for pointing that out. i submitted another pr that brings back buffering for .net and added some comments when the ifdefs might be removed again. 

btw can you change your default branch to develop so github uses it when creating a pr i always get it wrong....

**Comment by chkr1011** [comment]
I tried it but then the develop branch is also shown at the GitHub page per default. Do you also know how set the master for "startpage" but develop as default for pull requests? But I can change it. It is not a problem for me 😄

**Comment by JanEggers** [comment]
gues i have to pay attention when creating a pr after all ^^

**Comment by chkr1011** [comment]
OK 😄
