### ISSUE TITLE
Cannot implement a "ApplicationMessageInterceptor"

### ISSUE THREAD

**Issue by LuciferSam86** [chkr1011/MQTTnet#621]
Hello,
I'm trying to understand how to implement a "ApplicationMessageInterceptor".
The example in the wiki gives me the error: `Cannot convert lambda expression to type 'IMqttServerApplicationMessageInterceptor' because it is not a delegate type`

Here the example code:
```
var options = new MqttServerOptions();
            options.ApplicationMessageInterceptor = context =>
            {
                if (MqttTopicFilterComparer.IsMatch(context.ApplicationMessage.Topic, "/myTopic/WithTimestamp/#"))
                {
                    // Replace the payload with the timestamp. But also extending a JSON 
                    // based payload with the timestamp is a suitable use case.
                    context.ApplicationMessage.Payload = Encoding.UTF8.GetBytes(DateTime.Now.ToString("O"));
                }
            };
```

What am I missing?
I'm using .NET Framework 4.8 with VisualStudio 2019

**Comment by chkr1011** [comment]
Hi, 
sorry but the Wiki was not updated completely for 3.0.0. I updated the example code.
Let me know if it works now.

Best regards
Christian
