### ISSUE TITLE
MQTTnet.Server-Portable v3.0.2 has missing dependencies

### ISSUE THREAD

**Issue by fgretief** [chkr1011/MQTTnet#622]
We downloaded and unpacked the MQTTnet.Server-Portable-v3.0.2.zip file from the release pages. We opened a CMD box and executed the run.bat script. The output is as follows:
>
> D:\Programs\MqttNet.Server\v3.0.2>run.bat
>
>D:\Programs\MqttNet.Server\v3.0.2>∩╗┐@echo off
>'∩╗┐@echo' is not recognized as an internal or external command,
>operable program or batch file.
>
>D:\Programs\MqttNet.Server\v3.0.2>START "MQTTnet Server" dotnet .\MQTTnet.Server.dll
>
>D:\Programs\MqttNet.Server\v3.0.2>dotnet .\MQTTnet.Server.dll
>Error:
>  An assembly specified in the application dependencies manifest (MQTTnet.Server.deps.json) was not found:
>    package: 'DynamicLanguageRuntime', version: '1.2.2'
>    path: 'lib/netcoreapp2.1/Microsoft.Dynamic.dll'
>
>D:\Programs\MqttNet.Server\v3.0.2>
>
It looks like there is missing dependencies in the zip file created for the release.

**Comment by chkr1011** [comment]
Hi,
I saw that the package contains only release build and no 3rd Party libs. Please let me know if the following ZIP works.

https://filebin.ca/4gykYpa0rRP6/MQTTnet.Server-Portable-v3.0.3.zip

Best regards
Christian

**Comment by fgretief** [comment]
Hello,

Yes. Now it works as expected.

Thanks,
  Francois

**Comment by chkr1011** [comment]
Hi,
thank you for your feedback. I will release 3.0.3 soon with a proper ZIP.

Best regards
Christian

**Comment by BI7PRK** [comment]
Hi~ friend.
i use (run.bat from) MQTTnet.Server-Portable-v3.0.3.zip
```LOG
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\BI7PRK\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
warn: MQTTnet.Server.MqttServer[0]
      Debug logging is enabled. Performance of MQTTnet Server is decreased!
info: MQTTnet.Server.Scripting.PythonScriptHostService[0]
      Added Python lib path: D:\MQTTnet\Lib
```
running to here. The window closes immediately. i cannt get more error information. how to save the log file?

>Python 3.7 has been installed

**Comment by chkr1011** [comment]
Please start a CMD first, then navigate to the MQTTnet.Server dir and execute the bat file. Then you should see some more output. Also please share the output here so that I can see what is happening.

Best regards
Christian

**Comment by BI7PRK** [comment]
thanks @chkr1011
I have already followed the setps.
when run.bat in CDM, it open a new console for running. but the window closes immediately.
