### ISSUE TITLE
Delete retained message

### ISSUE THREAD

**Issue by biovoid** [chkr1011/MQTTnet#623]
Hi,

It seems that I can't delete retained message with this broker server. I send different combination of empty message with retain flag, but it does not work and my retained message still there.

**Comment by chkr1011** [comment]
Hi,
do you mean the standalone server MQTTnet.Server? I tested retained messages and it works perfectly on my machine. Please post the trace while sending the retained messages.
Best regards
Christian

**Comment by biovoid** [comment]
Oh, sorry, it was a problem in InterceptApplicationMessagePublishAsync, because I forget that null message is going through this method.
