### ISSUE TITLE
Expose the CONNACK properties

### ISSUE THREAD

**Issue by paolofulgoni** [chkr1011/MQTTnet#627]
I'd like to access the [Response Information](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901095) property of the `CONNACK` message, which I need in my Request/Response implementation.

Unfortunately I see that `MqttClientConnectedEventArgs` doesn't expose any of the properties returned by the server. Is this on purpose or they could be added?

**Comment by chkr1011** [comment]
Hi,
sorry this is a mistake (not yet done). I added these already for 3.0.3 which is coming soon.
Best regards
Christian

**Comment by paolofulgoni** [comment]
Ok, great, thanks a lot!!
