### ISSUE TITLE
Multiple Subscription Identifiers in PUBLISH message

### ISSUE THREAD

**Issue by paolofulgoni** [chkr1011/MQTTnet#630]
The section about [Subscription Identifier in PUBLISH message](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901117) of the the MQTT v5 specification says:

> Multiple Subscription Identifiers will be included if the publication is the result of a match to more than one subscription, in this case their order is not significant.

I see that only 1 identifier is read in `MqttV500PacketDecoder`:

```cs
private static MqttBasePacket DecodePublishPacket(byte header, IMqttPacketBodyReader body)
{
  //...
  packet.Properties.SubscriptionIdentifiers.Add(propertiesReader.ReadSubscriptionIdentifier());
}
```

Is this an issue or I'm misundertanding the specs?

**Comment by chkr1011** [comment]
Hi, in my opinion this is correct. The subscription ID is sometimes added multiple times. So that the while loop above ensures that the IDs are all added to the same list.

**Comment by paolofulgoni** [comment]
Thanks for the quick reply!
I understand, sorry, I haven't read the code carefully enough.

My doubt originated from this use case:

* subscribe the same topic twice, with different Subscription Id
* publish on the same topic
* the message received contains only one Subscription Id, not both

I'll further investigate, it may be a broker issue...
I'm using Mosquitto 1.6.0 btw

**Comment by paolofulgoni** [comment]
I made some tests and I can confirm that the MQTTnet client processes the Subscription Id correctly, so I'm closing the issue. Sorry for the waste of time.

Moreover, I found on the MQTT spec why the behaviour described in my previous comment is correct:

> If a Server receives a SUBSCRIBE packet containing a Topic Filter that is identical to a Non‑shared Subscription’s Topic Filter for the current Session, then it MUST replace that existing Subscription with a new Subscription
