### ISSUE TITLE
Best approach for multiple mqtt clients?

### ISSUE THREAD

**Issue by LucasSossai** [chkr1011/MQTTnet#633]
Hi, I'm developing an application in Xamarin.Forms using MQTTnet library

My implementation will be easy if I could handle multiple mqtt connections at the same time, is it feaseable with this lib? Any suggestion on how to make it?

**Comment by SeppPenner** [comment]
Well, you could use multiple clients at once?

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions.
