### ISSUE TITLE
Subscribe to several topic in one package don't work correctly in version 3.0.2

### ISSUE THREAD

**Issue by avengerstark** [chkr1011/MQTTnet#635]
Hi there!
Client subscribe to several topic in one package(MQTT Documentation, section 3.8.3) and receive from broker confirmation. But when server publish messages for all topics, client receive messages on only one topic. 
In version 2.8.5 this works correctly.

**Comment by chkr1011** [comment]
Hi,
I added UnitTest "Subscribe_Multiple_In_Single_Request". It seems to work perfectly. Is the UnitTest maybe wrong?

Please let me know if the UnitTest is wrong (or update it accordingly).

Best regards
Christian

**Comment by avengerstark** [comment]
Hi

**Comment by avengerstark** [comment]
Hi,
I tested with real device.
When I use version 3, device received only one topic, but broker publish many topics.

**Comment by avengerstark** [comment]
Hi,
I tested with real device.
When I use version 3.0.2, device received only one topic, but broker publish many topics.
If I update to 2.8.5, device received all topics.

**Comment by SeppPenner** [comment]
@avengerstark Can you provide some example code for this, please?

**Comment by avengerstark** [comment]
@SeppPenner I can't, because I haven't access to the device code.

**Comment by SeppPenner** [comment]
> @SeppPenner I can't, because I haven't access to the device code.

What about the server code? Or is this a client side problem?

**Comment by chkr1011** [comment]
Do you have a more detailed example? We already have a UnitTest for that but it works perfectly. Also my own devices (ESP8266, ESP32) are working perfectly.

So please provide a sample list of the topic filters. Then I can try to add a new UnitTest for that.

**Comment by avengerstark** [comment]
The server code is simple. The Device work correctly with mosquitto server and version 2.8.5, but don't with new version. I haven't have opportunity testing with device now. When I can, I'll show details.

**Comment by chkr1011** [comment]
@avengerstark Could you please try with latest beta? I want to make sure that the issue still exists. And which MQTT version are you using? 3.1.1 or 5.0.0?

**Comment by avengerstark** [comment]
When I can try testing, I'll write here details.

**Comment by SeppPenner** [comment]
I assume that this is fixed as its already covered by a unit test @avengerstark? Just tell us if not.
