### ISSUE TITLE
asp.net core client example documentation

### ISSUE THREAD

**Issue by bryanmullinbwp** [chkr1011/MQTTnet#637]
There doesn't seem to be any examples or documentation on how to use a MQTTnet client in asp.net core 2. I would be willing to write the documentation if someone could point me in the right direction of an example usage!

**Comment by chkr1011** [comment]
Hi I would be amazing if you write a documentation for that.
There is already some example code in the Wiki. But to get a full example please have a lock at the project MQTTnet.Server in the repository. There you can see how to use MQTTnet with an TCP endpoint and a WebSocket endpoint as well.

Best regards
Christian

**Comment by wiuwiu** [comment]
Hi @chkr1011. Thanks for your awesome work.
I will be truly grateful for documentation about how to use mqtt client in ASP .NET Core 2. I tried to run mqtt client in my asp .net core 2 app based on mqttnet.Server project but without luck.

**Comment by SeppPenner** [comment]
Using a client in Asp.NetCore works the same as in the regular .NetCore or .Net framework as documented under https://github.com/chkr1011/MQTTnet/wiki/Client#client-options. Another example can be found under https://github.com/mqttnettest/Issue637Test.

However, I have updated the wiki here: https://github.com/chkr1011/MQTTnet/wiki/Client#using-the-client-in-aspnet-core.

Or am I missing something here?

**Comment by bryanmullinbwp** [comment]
@SeppPenner I think the issue people are having is how to properly integrate this into the stock asp.netcore dependency injected environment. They want to integrate MQTTnet into their asp backend, then send the data to their front-end with something like SignalR.

Does that make sense?

**Comment by SeppPenner** [comment]
> They want to integrate MQTTnet into their asp backend

The client or the server?

The server is documented here: https://github.com/chkr1011/MQTTnet/wiki/Server#aspnet-core-integration (However, ASP.NET Core 2.1+ does not work as described, check https://github.com/chkr1011/MQTTnet/issues/605, too).

Integrating the client into the ASP backend with dependency injection does not make sense for me as it can be used easily in controllers or services added into the ASP context...

**Comment by bryanmullinbwp** [comment]
> be used easily in controllers or services added into the ASP context...

I think that the documentation should be how to best do that then?

**Comment by SeppPenner** [comment]
Okay, I can add this but it may take some time. I'm on vacation soon 😄

**Comment by SeppPenner** [comment]
Hi @bryanmullinbwp. I have added this to the wiki: https://github.com/chkr1011/MQTTnet/wiki/Client#using-the-client-in-aspnet-core

Do you think that this hint is sufficient? I don't know what information I should provide there additionally.

**Comment by bryanmullinbwp** [comment]
@SeppPenner Looks good to me! Let's close it out.

**Comment by msmiha** [comment]
HI,

is it possible someone would share an example on how to use a client application with asp.net. I see there is stated that it's used in the same way but how?

Regards. Miha

**Comment by SeppPenner** [comment]
Hi, there is a linked example under https://github.com/chkr1011/MQTTnet/wiki/Client#using-the-client-in-aspnet-core. Does this help you? --> https://github.com/rafiulgits/mqtt-client-dotnet-core

**Comment by msmiha** [comment]
Hi SeppPenner,

I had seen this but it's not an acctual example. I'm still lost. I mean I head implemented the example in my project. The project shows no errors, but I have no qlue on how to use the implemented code.

Thank you for your help

**Comment by SeppPenner** [comment]
@msmiha Once you have added the service with

```csharp
services.AddMqttClientHostedService();
services.AddSingleton<ExtarnalService>();
```

in Startup.cs, you can use the MQTT client service per dependency injection in any class via the constructor:

```csharp
public class ExtarnalService
{
    private readonly IMqttClientService mqttClientService;
    public ExtarnalService(MqttClientServiceProvider provider)
    {
        mqttClientService = provider.MqttClientService;
    }
}
```

Afterwards, you can use all methods that are defined in the `mqttClientService`.

**Comment by msmiha** [comment]
> @SeppPenner 
> Afterwards, you can use all methods that are defined in the `mqttClientService`.

I know I'm asking stupid questions but this is because of lack of knowledge about ASP.NET Core.

Can you actually show an example how can I use mqttClientService to publish message to a broker from a let say code below (methode OnGet()):

```
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Mqtt.WebGUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            
        }
    }
}
```

**Comment by SeppPenner** [comment]
Hi @msmiha: There is an example https://github.com/mqttnettest/Issue637Test-2. I hope this helps you.

**Comment by msmiha** [comment]
@SeppPenner:

Thank you for this. It really helps

**Comment by msmiha** [comment]
Hi,
@SeppPenner,

Could you also provide a sample on how to Subscribe to a Topic?

thank you.

**Comment by SeppPenner** [comment]
@msmiha It works similar to publishing and is described here: https://github.com/chkr1011/MQTTnet/wiki/Client#subscribing-to-a-topic and here: https://github.com/chkr1011/MQTTnet/wiki/Client#consuming-messages.

Example:

```csharp
public async Task OnGetAsync()
{
    try
    {
        await this.mqttClient.ConnectAsync(this.mqttClientOptions);

        this.mqttClient.UseApplicationMessageReceivedHandler(e =>
        {
            Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
            Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
            Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
            Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
            Console.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
            Console.WriteLine();
        });

        var topic = new MqttTopicFilterBuilder().WithTopic("my/topic").Build();
        await mqttClient.SubscribeAsync(topic);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```

**Comment by msmiha** [comment]
@SeppPenner,

thank you again for your comment.  I thought `public async Task OnGetAsync()` gets fired only on loading the page. But I see that regardless of that `this.mqttClient.UseApplicationMessageReceivedHandler` still listen and receive the messages.

In the meantime, I had also "figure out" how [your code](https://github.com/rafiulgits/mqtt-client-dotnet-core) works at less some parts. What I understand is that `public Task HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs)` gets fired every time the message is received and the data of the message is inside eventArgs. My question now would be how to extract those data from eventArgs to use them in `public async Task OnGetAsync()`? Is there a way to return those arguments out of the Task or is my thinking completely wrong?

Thank you again, for answering my questions.

**Comment by SeppPenner** [comment]
`OnGetAsync()` is only fired once, but the message handler is running until you close the website (Or after a timeout, I'm not sure).

Regarding the rest, I'm not really sure what you want to achieve with this, but you could store the data in a List / Queue or whatever and load the data out of there.

```csharp
using System.Collections;

public class Something
{
    private Queue<MqttApplicationMessageReceivedEventArgs> myData = new Queue<MqttApplicationMessageReceivedEventArgs>();

    public async Task OnGetAsync()
    {
        try
        {
            await this.mqttClient.ConnectAsync(this.mqttClientOptions);

            this.mqttClient.UseApplicationMessageReceivedHandler(e =>
            {
                // Stores the data in the queue
                this.myData.Enqueue(e);
            });

            var topic = new MqttTopicFilterBuilder().WithTopic("my/topic").Build();
            await mqttClient.SubscribeAsync(topic);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

    public async Task SomethingElse()
    {
        while(this.myData.TryDequeue(out var data))
        {
            // Do something with the data
        }
    }
}
```

But, as I said, without knowing what you want to achieve, it's quite difficult.

**Comment by msmiha** [comment]
Hi,

thank you for all your help. This was really helpful, but I still don't know how to do it. In the end, application what I would like to achieve is to display the latest received data on the page in form of text and also be able to send the data when I click the button. The application would look kind of the same as it could be found here:

http://www.hivemq.com/demos/websocket-client/

Could someone make an example for me?

**Comment by SeppPenner** [comment]
@msmiha I would recommend to read the introduction of [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor).

I have created an example (That should work although it doesn't look good to be honest.): https://github.com/mqttnettest/Issue637Test-2/tree/master/BlazorApp1

Of course, you could add the connect setup and buttons as in the MQTT Test Client from HiveMQ as well, but that's extra work. I hope this helps you a bit.

**Comment by msmiha** [comment]
@SeppPenner thank you very much for all your advice, the last one was really helpful.

Actually what I was looking for was an event. This pretty much solves my current trouble. What I need it was to pass the data to another object when they are received, so my current code looks like this:

```
public class MqttClientService : IMqttClientService
{
        private IMqttClient mqttClient;
        private IMqttClientOptions options;
        
        public event EventHandler<MqttApplicationMessageReceivedEventArgs> MqttReceivedData;
        
        public MqttClientService(IMqttClientOptions options)
        {
            this.options = options;
            mqttClient = new MqttFactory().CreateMqttClient();
            ConfigureMqttClient();
        }

        private void ConfigureMqttClient()
        {
            mqttClient.ConnectedHandler = this;
            mqttClient.DisconnectedHandler = this;
            mqttClient.ApplicationMessageReceivedHandler = this;            
        }

        public Task HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs)
        {
            MqttReceivedData?.Invoke(this, eventArgs);
            throw new System.NotImplementedException();
        }
}
```
For subscribing to an event I use:

  ```
  public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly MqttClientService _mqttClientService;
                
        public string MQTTResponse;

        public IndexModel(MqttClientService mqttClientService, ILogger<IndexModel> logger)
        {
            _logger = logger;
            _mqttClientService = mqttClientService;

            _mqttClientService.MqttReceivedData += _mqttClientService_MqttReceivedData;
        }

        private void _mqttClientService_MqttReceivedData(object sender, MqttApplicationMessageReceivedEventArgs e)
        {
            MQTTResponse = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);
            Console.WriteLine(Encoding.UTF8.GetString(e.ApplicationMessage.Payload));
        }

        public async Task OnGetAsync()
        {
            
            await _mqttClientService.PublishAsync("hello/world","welcome!");            
        }
    }
```

But it is true that the value does not get updated in realtime on the webpage. For this, I think I would need Balzor or JavaScript.

I have seen also your other application [IOT hub](https://rafiulgits.github.io/IotHub/). And I like how you handle the MQTT messages there. You basically pass them with SignalIR.

I think this would be an ideal solution for my end application which would basically CRUD the data of the database, which would be read or written to by the RFID reader that talks MQTT protocol.
