### ISSUE TITLE
How can I get in broker, the host name that user sets in client to send data

### ISSUE THREAD

**Issue by TaherianuBeac** [chkr1011/MQTTnet#639]
Is there any way to get in broker the URL that client use to send data to broker? If it is possible, is that possible to have it in server start?

**Comment by chkr1011** [comment]
Hi, 

Do you mean the topic or IP. Please share some code pointing out where exactly you need this information.

Best regards
Christian

**Comment by TaherianuBeac** [comment]
Hi Christian,
Thank you for your reply. In client we set the option like this
```
var options = new MqttClientOptionsBuilder()
    .WithTcpServer("broker.hivemq.com", 1883) // Port is optional
    .Build();
```
How can access that URL in my Broker? I want to know which url client called. I tried to get it from `validationContext` in `MqttServerOptionsBuilder` but there is not such property. How can I get that in broker?

Thank you

**Comment by chkr1011** [comment]
Mhh sorry but that is currently not supported in the broker. I planned to add endpoints with custom IDs but this is not yet started.

**Comment by TaherianuBeac** [comment]
OK. Thank you.

**Comment by wangyiwu** [comment]
@TaherianuBeac is that support now??

**Comment by wangyiwu** [comment]
@chkr1011  hello, iss this support now?

**Comment by chkr1011** [comment]
No
