### ISSUE TITLE
Prevent mqtt broker (server) from receiving messages sent from itself.

### ISSUE THREAD

**Issue by jetompki** [chkr1011/MQTTnet#642]
When a broker publishes a message, I'm noticing that it is receiving the same message that it published.

Is it possible to prevent this from occurring?

**Comment by chkr1011** [comment]
Hi,
this is by design. The broker does not distinguish. Every message is treated the same. But you can skip processing them by checking the _ClientId_. If this is set to _null_ the message was sent by the server directly.
Best regards
Christian

**Comment by ramonsmits** [comment]
Updated https://github.com/chkr1011/MQTTnet/wiki/Tips-and-Tricks , I think this can be closed.
