### ISSUE TITLE
GetClientStatusAsync() get time is errored

### ISSUE THREAD

**Issue by lovezyb** [chkr1011/MQTTnet#643]
var status = await _server.GetClientStatusAsync();

 foreach (var s in status)
 {
      //The output time differ with the current time of 8 hours
      s.LastPacketReceivedTimestamp
      s.LastNonKeepAlivePacketReceivedTimestamp
 }

**Comment by lovezyb** [comment]
The used DateTime.UtcNow

**Comment by chkr1011** [comment]
Due to performance reasons the DateTime is in UTC format. You can check that by using property _Kind_.
