### ISSUE TITLE
Run Multiple MQTT servers on same windows machine with different TCP/IP Ports

### ISSUE THREAD

**Issue by Mani8181** [chkr1011/MQTTnet#645]
Hi,
     I have a requirement to connect more than 300 clients and each client will publish 10 messages on every minute.i am using MQTTNet in my application (MQTT Server ). Will single TCP port handle the concurrent hits from those 300 clients or need to run more than one MQTT Server with different TCP ports.please give me a suggestion.

Thanks,
ManikandanRajendran

**Comment by JanEggers** [comment]
one port can handle 64K connections, your broker will be limited by network bandwith, cpu, or memory but never by the number of connections per port. and in any case running a second server on the same machine will not increase the number of concurrent messages this machine can handle
