### ISSUE TITLE
Message delivery result from broker to client with QoS=2 always Success

### ISSUE THREAD

**Issue by iKuzmich** [chkr1011/MQTTnet#646]
I have a client subscribed to specific topic with ExactlyOnece QoS level.
I disconnected the client and sent the message with corresponding topic from the server with the same ExactlyOnece QoS

var json = pushNotification.ToPayload();
            var messageBuilder = new MqttApplicationMessageBuilder()
                .WithTopic(route)
                .WithPayload(json)
				.WithExactlyOnceQoS()
                .WithRetainFlag(false);
				
var result = await Server.PublishAsync(messageBuilder.Build());

result.ReasonCode is Success anyway

I've tried both disable and enable user sessions but the result is the same.

If it's not right approach to get notifications about failed messages with only one subscriber pease let me know is there any other way for this?

Other question - is it possible to access the messages stored on user serrsion to get a chance of save/load them from file or database in case if server is stopping?

**Comment by chkr1011** [comment]
Hi, the QoS onjly covers communication between client and server. Client to Client is not covered.
I usually have a "response" topic which will be used by the receiving client. 

You can also have a look at the RPC extension to see how to wait for a client response.

Best regards
Christian

**Comment by iKuzmich** [comment]
Thanks for the explanation.
