### ISSUE TITLE
How to Use With WebSocket Server

### ISSUE THREAD

**Issue by qcjxberin** [chkr1011/MQTTnet#65]
How to Use With WebSocket Server,Could you Write a Demo With this?

**Comment by chkr1011** [comment]
Hi this is not fully implemented yet. I started a new library called _HTTPnet_ which will be used for this in the future. Implementing this is quire complex because the used HTTP library can change. There are several available for .NET. If you already use one you can have a look at the _https://github.com/chkr1011/MQTTnet/blob/master/Frameworks/MQTTnet.NetStandard/Implementations/MqttServerAdapter.cs_. There you can see how to implement the required interfaces. Then you can write a _binding_ for the HTTP library. Otherwise you have to wait until the _HTTPnet_ library is including and having a _binding_.

Best regards
Christian

**Comment by ChristianRiedl** [comment]
I tried to integrate MQTTNet into a AspNetCore 2.0 web server. It was possible with some small additional classes and I changed _WebSocketStream_ class to wrap _WebSocket_ instead of _ClientWebSocket_ . I still get some exceptions when client disconnects but it works.

@chkr1011 : I think ASpNetCore 2.0 is netstandard 2.0 so it should run on latest Windows 10 Iot Core. I know it is heavy compared to  HTTPnet. Maybe you have some ideas how to improve my solution.    

Here is the code (Startup class)

```
public class Startup
{
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public async void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(LogLevel.Debug);

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            var adapter = new MqttWebSocketServerAdapter();
            var options = new MqttServerOptions
            {
                ConnectionValidator = p =>
                {
                    if (p.ClientId == "SpecialClient")
                    {
                        if (p.Username != "USER" || p.Password != "PASS")
                        {
                            return MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                        }
                    }
                    return MqttConnectReturnCode.ConnectionAccepted;
                }
            };
            var mqttServer = new MqttServer(options, new List<IMqttServerAdapter> { adapter });
            mqttServer.ClientDisconnected += (s, e) =>
            {
                Debug.WriteLine($">> Disconnected {e.Client.ClientId}");
            };

            await mqttServer.StartAsync();
            MqttNetTrace.TraceMessagePublished += (s, e) =>
            {
                Debug.WriteLine($">> [{e.ThreadId}] [{e.Source}] [{e.Level}]: {e.Message}");
                if (e.Exception != null)
                {
                    Debug.WriteLine(e.Exception.Message);
                }
            };
            app.UseWebSockets();
            app.Use(async (context, next) =>
            {
                if (context.WebSockets.IsWebSocketRequest)
                {
                    using (var webSocket = await context.WebSockets.AcceptWebSocketAsync())
                    {
                        adapter.UseWebSocket(webSocket);
                        while (webSocket.State != WebSocketState.Closed)
                        {
                            await Task.Delay(200);
                        }
                    }
                }
                else
                {
                    await next();
                }
            });
            app.UseStaticFiles();
        }

        private void LogFrame(ILogger logger, WebSocketReceiveResult frame, byte[] buffer)
        {
            var close = frame.CloseStatus != null;
            string message;
            if (close)
            {
                message = $"Close: {frame.CloseStatus.Value} {frame.CloseStatusDescription}";
            }
            else
            {
                string content = "<<binary>>";
                if (frame.MessageType == WebSocketMessageType.Text)
                {
                    content = Encoding.UTF8.GetString(buffer, 0, frame.Count);
                }
                message = $"{frame.MessageType}: Len={frame.Count}, Fin={frame.EndOfMessage}: {content}";
            }
            logger.LogDebug("Received Frame " + message);
        }
}

```
And here the 2 helper classes 

```
public class MqttWebSocketServerAdapter : IMqttServerAdapter, IDisposable
{
        bool                    _isRunning;
        public event Action<IMqttCommunicationAdapter> ClientAccepted;
        public Task StartAsync(MqttServerOptions options)
        {
            if (_isRunning) throw new InvalidOperationException("Server is already started.");
            _isRunning = true;
            return Task.CompletedTask;
        }
        public void UseWebSocket (WebSocket webSocket)
        {
            var wsChannel = new MqttWebSocketServerChannel(webSocket);
            var clientAdapter = new MqttChannelCommunicationAdapter(wsChannel, new MqttPacketSerializer());
            ClientAccepted?.Invoke(clientAdapter);
        }
        public Task StopAsync()
        {
            _isRunning = false;
            return Task.FromResult(0);
        }
        public void Dispose()
        {
            StopAsync();
        }
 }
public class MqttWebSocketServerChannel : IMqttCommunicationChannel, IDisposable
{
        WebSocket _webSocket;
        public MqttWebSocketServerChannel (WebSocket webSocket)
        {
            _webSocket = webSocket;
            RawReceiveStream = new WebSocketStream(_webSocket);
        }
        public Stream SendStream => RawReceiveStream;
        public Stream ReceiveStream => RawReceiveStream;
        public Stream RawReceiveStream { get; set; }

        public Task ConnectAsync()
        {
            throw new NotImplementedException();
        }

        public async Task DisconnectAsync()
        {
            RawReceiveStream = null;
            if (_webSocket == null) return;
            await _webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, string.Empty, CancellationToken.None).ConfigureAwait(false);
        }
        public void Dispose()
        {
            _webSocket?.Dispose();
        }
}


```

**Comment by chkr1011** [comment]
@ChristianRiedl I added your code to the _develop_ branch and also fixed some issues. For me it seems to work now. Please test it and let me know if it works or if it still has issues.

Best regards
Christian

**Comment by chkr1011** [comment]
@qcjxberin Support for WebSockets is coming via ASP.NET Core 2.0. Please have a look at the _develop_ branch.

**Comment by ChristianRiedl** [comment]
Christian, 
thank you for your improvements and demo code, it works fine.

I am working on similar .NET projects just for fun and learning by doing. Smart home and media integration arround AspNet Core servers and Xamarin based clients.  

Smart home with integration of HomeMatic, Osram Spotify, Fritzbox, Tinkerforge, ...
Media  with remotes for Samsung TV, Undok, Musiccast, Roon 
DLNA server based on AspNet Core 

If you have a need for such things tell me.

**Comment by chkr1011** [comment]
@ChristianRiedl I need all 😄 

Sound very interesting to me. I also planning a Xamarin App for my Smart Home system. 
The system is documented here:

https://www.hackster.io/cyborg-titanium-14/home-automation-system-using-raspberry-pi-784235

and here:

https://github.com/chkr1011/Wirehome

Let me know if you are interested in the project. I would like to add you to the Wirehome community if you are interested. Let me know...

Best regards
Christian

**Comment by ChristianRiedl** [comment]
Yes, you can add me to the Wirehome community. 
Currently I am still busy with my companies software product  (SCADA, running in 12 nuclear power plants), but I plan to reduce this boring things, which I do now since 40 years.  
I enjoy creating private projects where I do not have to spend 50 % in test code. 
   
I took a look to the Wirehome project. Alexa integration is also part of my toys. 
But in general I had bad experience with stability of Raspberry PI as server, I prefer a Windows server and also have good experience running AspNet Core on QNAP NAS.  
  
For the SmartHome skill it was quite usefull that all my servers support OpenID authentication.   

I tried to use OAuth Bearer authentication to establish WebSocket connection. But I have no idea how it is possible. I have seen only samples with Basic Authentication. ClientWebSocket.Options supports a Cookie container, but I was not able to deliver a Authentication header to the web server.

**Comment by JanEggers** [comment]
@chkr1011 i had alook at your latest changess and i think it would be great to create a real package based on mqtt.netstandard not just a test app. aka mqttnet.aspnetcore. that package could contain all the code needed to adapt mqttnet into aspnet core. 

that library could:

create a wrapper for your tracing to forward it to ms.extensions.logging
create a wrapper of the options for ms.extensions.options and ms.extensions.configuration
create a wrapper for the MqttServer to be a hosted service (automatic start and stop with app livecycle)
finally do that glue code so a package consumer can just app.UseMqttServer(options => { options.configureStuff()  }); 

that is what i do in my project and i guess it would be great for anyone else that wants to add mqtt to an existing aspnetcore app.

**Comment by chkr1011** [comment]
@JanEggers I agree that is a good idea. But with package you mean a separate nuget package? Since we are not moving to netstandard 2.0 at the moment it must be a separate one.

I already had a look regarding the logging stuff but this requires also netstandard 2.0. So probably a new nuget package would be the best solution or what do you think?

Do you may have some additions for the _managed_ client?

**Comment by ChristianRiedl** [comment]
I propose to introduce ms.extensions.logging.abstraction 1.1.2 in the 1.x standard libraries.
It is netstandard 1.1 and upward compatible with ms.extension.logging 2.0. In the libaries you need only the **ILogger** interface and an extension class. 

MqttWebSocketServerAdapter and MqttWebSocketServerChannel can be added to the framework netstandards libs as they are netstandard 1.3.

App livecycle integration, ms.extensions.options and config would be fine to implement in the meanwhile in the aspnet core 2.0 demo.

**Comment by JanEggers** [comment]
> But with package you mean a separate nuget package?

yup. 

i agree with @ChristianRiedl  we can use 1.x abstractions for logging. only the   IHostedService needs 2.0.

So i can provide a PR with logging and di for the existing package and a seperate package/project for HostedService and AppHostBuilder.

is that ok?

ManagedClient looks good, less stuff to handle manually.

**Comment by chkr1011** [comment]
@JanEggers OK

**Comment by ChristianRiedl** [comment]
I would ask you for one more additional feature. As I am using Bearer authentication I would need a possibility to set header values during websocket connect. I know that not so many people will need this feature, but it will not impair somebody. 

```
    public class MqttClientWebSocketOptions : BaseMqttClientOptions
    {
        public string Uri { get; set; }
        public IEnumerable<KeyValuePair<string, string>> HeaderValues { get; set; }
    }
...

        public async Task ConnectAsync()
        {
            var uri = _options.Uri;
            if (!uri.StartsWith("ws://", StringComparison.OrdinalIgnoreCase))
            {
                uri = "ws://" + uri;
            }

            _webSocket = new ClientWebSocket();
            _webSocket.Options.KeepAliveInterval = _options.KeepAlivePeriod;
            if (_options.HeaderValues != null)
            {
                foreach (var headerValues in _options.HeaderValues)
                {
                    _webSocket.Options.SetRequestHeader(headerValues.Key, headerValues.Value);
                }
            }
            await _webSocket.ConnectAsync(new Uri(uri), CancellationToken.None);
            RawReceiveStream = new WebSocketStream(_webSocket);
        }

```

**Comment by chkr1011** [comment]
Looks OK for me. I will add this feature to the supported frameworks. Even if not everyone needs this it makes sense to me. But I will use a dictionary etc.

**Comment by ChristianRiedl** [comment]
Thanks a lot

**Comment by chkr1011** [comment]
A new project is added to the repository. Please have a look at this. If you still need some information or  assistance please let me know.

**Comment by evangeloper** [comment]
@chkr1011, we can't find information regarding auth with a bearer token.
Instead of using Basic auth, we would like to pass a a JWT to authorize the connection.
Is this possible using this library?

**Comment by JanEggers** [comment]
this project does neither support basic auth or bearer tokens. the mqtt protocol specifies a connect packet that you have to validate in the broker. how you do that is up to you

**Comment by evangeloper** [comment]
@JanEggers thanks!
We are already solving it that way.
