### ISSUE TITLE
Reading persisted messages from broker

### ISSUE THREAD

**Issue by ViktorStepanukCN** [chkr1011/MQTTnet#651]
Hi,

I am using Mosquitto with persisted messages (set in broker configuration with publishing messages with clean session = false and QoS = 1) and I am trying to figure out, how to read all stored messages in case my subscriber went offline for a while. I can see the messages are stored in db file on broker, however these are ignored using code from Wiki samples. It handles only new messages. Could you please point me in the right direction?

```var factory = new MqttFactory();
client = factory.CreateMqttClient();
var options = new MqttClientOptionsBuilder()
  .WithWebSocketServer("localhost:9001")
  .WithCleanSession(false)
  .Build();
await client.ConnectAsync(options);
await Subscribe(client);

private async Task Subscribe(IMqttClient client)
{
    var result = await client
        .SubscribeAsync(
            new TopicFilterBuilder()
                .WithTopic(topicName)
                .WithQualityOfServiceLevel(MqttQualityOfServiceLevel.AtLeastOnce)
                .Build());
    client.UseApplicationMessageReceivedHandler(HandleReceived);
}

**Comment by chkr1011** [comment]
Hi,
please attach the handler at the last line BEFORE subscribing. Otherwise you may loose some messages.

Best regards
Christian

**Comment by ViktorStepanukCN** [comment]
Thank you!
