### ISSUE TITLE
How to use some backend API into a asp.net controller to manage the broker?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#653]
How to use some backend API into a asp.net controller to manage the broker?
Do Have I use a "programmed" MQTT client and to create some management topic that broker know and so it run tasks?

**Comment by chkr1011** [comment]
I don't understand exactly what you mean but to me the way how the MQTTnet.Server works is maybe interesting for you. This service uses a MQTTser server internally which is managed via ASP.NET API.

**Comment by biapar** [comment]
I use 2.8.4 version. I wish to made some API to control the broker server.

**Comment by chkr1011** [comment]
Such a thing doesn't exist.

**Comment by SeppPenner** [comment]
> How to use some backend API into a asp.net controller to manage the broker?

What exactly do you want to do? Create topics? Manage user credentials?

**Comment by biapar** [comment]
I upgrade to 2.8.5
The only method that I found it's to create a special topic filtered by the broker and when a request on that topic arrive, the broker reply on another specific topic, but I like to use a WebApi and not this workaround.

**Comment by chkr1011** [comment]
Please have a look at the MQTTnet.Server source code. It has some controllers for that. Otherwise there is only the hack you already described.

**Comment by SeppPenner** [comment]
> The only method that I found it's to create a special topic filtered by the broker and when a request on that topic arrive, the broker reply on another specific topic, but I like to use a WebApi and not this workaround.

Now I even understand what you're trying to do. If I have time, I will try to check this again.

**Comment by SeppPenner** [comment]
I have created a project that might work as a basis here: https://github.com/SeppPenner/NetCoreMQTTExampleIdentityConfig. Link is also in the wiki: https://github.com/chkr1011/MQTTnet/wiki/Examples.
