### ISSUE TITLE
Keep the client suscribed

### ISSUE THREAD

**Issue by det-iot** [chkr1011/MQTTnet#663]
I have the following app:

**Main class**

>     public class Program
>     {
>         static MQTT cliente = new MQTT();
>         static async Task Main()
>         {
>             await cliente.ManageMQTTClient();
>         }
>     }

**Client class**

>     public class MQTT
>     {
>         public async Task  ManageMQTTClient()
>         {
>             try
>             {
>                 var options = new ManagedMqttClientOptionsBuilder()
>                     .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
>                     .WithClientOptions(new MqttClientOptionsBuilder()
>                         .WithClientId(Guid.NewGuid().ToString())
>                         .WithTcpServer("...")
>                         .WithCredentials("...")
>                         .WithKeepAlivePeriod(TimeSpan.FromSeconds(60))
>                         .Build())
>                     .Build();
> 
>                 var mqttClient = new MqttFactory().CreateManagedMqttClient();
>                 await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("...").Build());
>                 await mqttClient.StartAsync(options);
>                 while (mqttClient.IsStarted == true)
>                 {
>                     mqttClient.UseApplicationMessageReceivedHandler(e =>
>                     {
>                         Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
>                         Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
>                         Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
>                         Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
>                         Console.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
>                         Console.WriteLine();
>                     });
>                 }
>             }
>             catch (Exception e)
>             {
>                 Console.WriteLine("Error: " + e);
>             }            
>         }
>     }

If I want to keep the client subscribed to a broker and not finish it when the program start and call the client using await, I need to add any kind of loop like:

> while (mqttClient.IsStarted == true)
>  {
>  <...>
>   }

¿Is there any other way of doing this?

**Comment by chkr1011** [comment]
You have to add a Thread.Sleep(-1) for example at the end of the Main method. Then the new thread will not stop and the app remains open. Please do not use the loop to set the application message handler all the time.

Best regards
Christian
