### ISSUE TITLE
Add an extension to load user credentials from a configuration file

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#664]
@chkr1011 I would like to add an extension to load user credentials e.g. from a json config file and want to add it to this project. Is there a standard procedure on how to add extensions? Meaning: Should I add the code here or in an extra project that just extends your project?

**Comment by JanEggers** [comment]
I would not consider putting credentials in a json file. you should at least use some encrypted format.

and finally why implement that on your own and not use identity?
https://docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/introduction-to-aspnet-identity

that way you have roles and claims and all the good stuff to fine tune access

**Comment by SeppPenner** [comment]
> I would not consider putting credentials in a json file.

The benefits of using a json file are clear:
* It's fast
* It's easy to configure (If you do not want to recompile your service all the time when changing e.g. some users for testing purposes)
* It's secure as long as the server the service runs on is secure (E.g. does not allow some directory listing in the webserver or has some remote desktop or SSH vulnerability or uses weak passwords, etc.)

> you should at least use some encrypted format.

I can provide that, too. However, I totally disagree on the security aspect here. When someone has access to your server, it does not matter whether the json file is encrypted or not. If you encrypt it using some password (That is stored in code), the attacker can decompile the dll easily. Same for using some *.pfx certificate with a password. Same for using Windows credentials (Despite that the code does not run on Linux afterwards). Using `PBKDF2` or similar stuff doesn't help either because the password to the data still wpuld need to be stored somewhere... Check https://security.stackexchange.com/questions/15040/standards-for-encrypting-passwords-in-configuration-files for this, please (Especially answer 3 and 4).

To sum it up: If someone has access to your server, encrpytion of files does not matter at all. It's just some dummy protection for script kiddies...

> and finally why implement that on your own and not use identity?
https://docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/introduction-to-aspnet-identity

As far as I know, it's only available on `Asp.Net` (meaning `.Net Core 2.0+`, not on:
* .NET Standard 1.3+
* .NET Core 1.1+
* .NET Core App 1.1+
* .NET Framework 4.5.2+ (x86, x64, AnyCPU)
* Mono 5.2+
* Universal Windows Platform (UWP) 10.0.10240+ (x86, x64, ARM, AnyCPU, Windows 10 IoT Core)
* Xamarin.Android 7.5+
* Xamarin.iOS 10.14+

(The official supported frameworks from https://github.com/chkr1011/MQTTnet).

> that way you have roles and claims and all the good stuff to fine tune access

Ist it even possible in MQTTnet to assign certain topic restrictions to specific users? Nevertheless, you can do that in json, too...

**Comment by JanEggers** [comment]
@SeppPenner I didnt want to offend you, I just wanted to point out that I would do it differently.

**Comment by SeppPenner** [comment]
> @SeppPenner I didnt want to offend you, I just wanted to point out that I would do it differently.

I didn't take that as an attack, I just wanted to state my position and the benefits (and problems, of course) of both solutions. I would even consider both solutions as valid ones and good feature requests. (I could as well need support for a database behind the MQTT server).

**Comment by SeppPenner** [comment]
By the way, do you know whether this is possible with the library:
> that way you have roles and claims and all the good stuff to fine tune access
?

**Comment by JanEggers** [comment]
you could implement https://github.com/chkr1011/MQTTnet/blob/efef23e3f55bf600e3322fcd52c5e1b8665403bf/Source/MQTTnet/Server/IMqttServerSubscriptionInterceptor.cs

the https://github.com/chkr1011/MQTTnet/blob/7a642802ed7c217f53a865b4dc16e2f14b9634f1/Source/MQTTnet/Server/MqttSubscriptionInterceptorContext.cs

lacks the user information so you have to look that up yourself with the clientid

and then you can decide wether you accept the subscription or not

**Comment by SeppPenner** [comment]
Thanks, I will try this and check what's neccessary.

**Comment by SeppPenner** [comment]
I have tried to put this into the library itself. This is way to complicated... I have now provided a an example on how to do this here: https://github.com/chkr1011/MQTTnet/wiki/Further-Server-examples (or https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig).

**Comment by SeppPenner** [comment]
@JanEggers By the way: I added the option for encryption with a static password, too.

**Comment by chkr1011** [comment]
In my opinion such an extension might be interesting. Having a hashed password might be a good compromise between security and usability. There is a class for that in ASP.Net (called PasswordHasher). I already used it in another project and it works fine. 

What do you guys think?

**Comment by SeppPenner** [comment]
> What do you guys think?

I agree with you. Currently, my example project runs on .NetCore, not Asp.NetCore. If there is an option to include the password hasher, I can do it.

**Comment by SeppPenner** [comment]
@chkr1011 How do you want to do this? The current problem is that the Hash (Of course) is different with Pbkdf2 every time you call the function. I do not see how I should encrypt the file with that hash...

**Comment by SeppPenner** [comment]
I do not know how to do this.

**Comment by chkr1011** [comment]
That _PasswordHasher_ can also check if a password hash matches the specified password. So my idea was that the file is NOT encrypted like you mentioned. So the file should contain the password hash in plain text and upon connect the clear text password from the CONNECT packet is verified with the hash from the config file (via using the PasswordHasher).

**Comment by SeppPenner** [comment]
Ah, now I understand what you mean. That's possible easily, yes.

**Comment by chkr1011** [comment]
We also should cover some use cases like:
1. With one set of user and pass ANY client ID can be used.
2. Connect is only allowed if User+Password+ClientID match a dedicated entry in the file.
3. Does that file maybe contain a white OR black list (with both supported) which contains 1+ regex which filter the allowed topics to subscribe for?
4. Same as 3 but for topics to publish?
5. Any other ideas?

I would need 1-4 for one of my other projects.

**Comment by SeppPenner** [comment]
1. The problem is that you currently do not get the username from the interceptor
2. This is already possible.
3. Currently a white list only (But with regex. I already contacted someone from Mosquitto and he showed me which code they use for topic validation --> I just need to port it from C to C#)
4. Not yet done, but on my list.
5. 1 to 4, but with a database and Identity (As @JanEggers proposed)

**Comment by SeppPenner** [comment]
Update:
1. Same problem, this is something you, @chkr1011 need to provide somehow.
2. Works already.
3. Whitelists and blacklists are supported, but in my opinion there is a bug in the MQTT topic matching code from mosquitto: https://github.com/eclipse/mosquitto/issues/1317#issuecomment-506461043
4. https://github.com/chkr1011/MQTTnet/issues/517: I would need to implement `WithApplicationMessageInterceptor()`, correct?
5. See https://github.com/chkr1011/MQTTnet/issues/668.


Check: https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig

**Comment by SeppPenner** [comment]
I would close this issue now, the example with hashed user passwords is here: https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfigHashedPasswords and https://github.com/chkr1011/MQTTnet/wiki/Examples. The only things that do not work yet is 1. (Which depends on https://github.com/chkr1011/MQTTnet/issues/682) and 3 (I need to add some correct method to check the wildcards).

Both issues are known and added to the projects already.

**Comment by SeppPenner** [comment]
@chkr1011: Another short update:

1: With one set of user and pass ANY client ID can be used. --> I'm right now using a **prefix** to indicate which username / password combination can be used for a bunch of client ids, meaning that e.g. all client ids starting with `roomsensors_` can be used with one username and password combination.
2: Connect is only allowed if User+Password+ClientID match a dedicated entry in the file. --> Works.
3 and 4: Black and whitelisting of topics for subscription and publishing --> Works.

If you have any more questions, take a look at the readme https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig or contact me ;)
