### ISSUE TITLE
Managed Client removes failed messages from message queue but not from storage manager

### ISSUE THREAD

**Issue by vbBerni** [chkr1011/MQTTnet#665]
When the managed client fails to transmit a message with QoS 0 it removes the message from the message queue but doesn't removes it from the storage manager.
After restarting the server all the QoS 0 messages are loaded again in the message queue and resent.
Our expectation would be to drop QoS 0 messages from the storage manager like in the message queue

**Comment by SeppPenner** [comment]
@chkr1011 You can close this. It's already merged, isn't it?
