### ISSUE TITLE
disconnected-event

### ISSUE THREAD

**Issue by RainerMueller82** [chkr1011/MQTTnet#67]
Hi!
It looks like the disconnected event of the client is called when a ConnectAsync fails.
Wouldn't it be better to call the event only if the client was really connected before?

BR, Rainer.

**Comment by chkr1011** [comment]
Hi,
the idea behind this behavior is that you call _ConnectAsync_ only one time and put retry logic into the _Disconnected_ event. It does not matter why the connection drops. The event is always called and thus the reconnect will work always.

Do you have some troubles with that approach? Do you may need several properties in the event which inform about the previous connection state (Connected / Disconnected)?

Best regards
Christian

**Comment by RainerMueller82** [comment]
Ah ok! Thats exactly what I did, I have a retry loop. This logic is
triggered at startup and when the disconnect event is called. But with this
approach, the connection process is triggered everytime the connection
fails. Perhaps i should redesign my code with your hints in mind.

Thx!

Am 18.10.2017 19:50 schrieb "Christian" <notifications@github.com>:

**Comment by chkr1011** [comment]
OK I will also extend the _Disconnected_ event. Then you can check if the client was connected before or not.
