### ISSUE TITLE
is winform support  MqttWebSocketServer?

### ISSUE THREAD

**Issue by dongdy** [chkr1011/MQTTnet#670]
hi

i want to write a  winform mqttServer  app with MQTTnet .
how can the mqttServer support the MqttWebSocketServer?

thanks!

**Comment by chkr1011** [comment]
Hi,
sorry but this is not supported. You may want to wait for .net core 3.0 and combine WinForms with Kestrel or something like that. 

Or you find a suitable WebSocket server for .net which runs also in .net 4.7 or whatever and build a transport adapter for MQTTnetl

Best regards
Christian
