### ISSUE TITLE
Cannot connect to the local server

### ISSUE THREAD

**Issue by Treycos** [chkr1011/MQTTnet#674]
I'm trying to set up a MQTT server and multiple clients on my machine for a school project. Both the server and one of my clients are UWP Apps.

The server will start running without any trouble. However, when trying to connect the client to it, I get the following error when calling `ConnectAsync`

![image](https://user-images.githubusercontent.com/19551067/60041123-de597980-96ba-11e9-805d-9cfcd5b5b0ba.png)

> MQTTnet.Exceptions.MqttCommunicationException: 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Here is the client code :

```
        private IMqttClient Client = new MqttFactory().CreateMqttClient();

        public async void InitiateClient()
        {
            var options = new MqttClientOptionsBuilder()
                .WithClientId(Guid.NewGuid().ToString())
                .WithTcpServer("127.0.0.1")
                .Build();

            await Client.ConnectAsync(options);
        }
```

And here is the server one :

```
        public IMqttServer MqttServer { get; set; } = new MqttFactory().CreateMqttServer();

        public async void InitiateServer()
        {
            var optionsBuilder = new MqttServerOptionsBuilder()
                .WithConnectionValidator(
                    new MqttServerConnectionValidatorDelegate(
                        c => {
                            c.ReturnCode = ValidateConnection(c);
                        }
                    )
                );

            await MqttServer.StartAsync(optionsBuilder.Build());
        }
```

I opened the ports in the firewall with he following parameters, both inbound and outbound :

![image](https://user-images.githubusercontent.com/19551067/60041329-63dd2980-96bb-11e9-85b8-86090c156cce.png)

Any idea on what could be causing this issue ?
Thank you

**Comment by SeppPenner** [comment]
It looks good for me. One thing: Don't you use credentials?

**Comment by Treycos** [comment]
I did not add any options other about it in the builders. Should I ?
Or is there another way to use credentials ?

The break point i put in the `MqttServerConnectionValidatorDelegate` is never reached

**Comment by SeppPenner** [comment]
Your methods `InitiateClient()` and `InitiateServer()` are async methods. How to you call them? Do you call them in a not async context and do not wait for the result?

**Comment by Treycos** [comment]
The server is started right after the component initialization of the main page

```
    public sealed partial class MainPage : Page
    {
        private GatewayServer Server { get; set; } = new GatewayServer();

        public MainPage()
        {
            InitializeComponent();

            ServerStatus.Text = "Starting server...";

            Server.ServerStarted += () => ServerStatus.Text = "Running...";

            Server.MqttServer.ClientConnectedHandler = new MqttServerClientConnectedHandlerDelegate(client => { ClientList.Items.Add(client.ClientId); });

            Server.InitiateServer();
        }
    }
```

The client connection is bound to a button click

```
    public sealed partial class MainPage : Page
    {
        private MQTTClient Client = new MQTTClient();

        public MainPage()
        {
            InitializeComponent();

            DeviceList.ItemClick += DeviceList_ItemClick;
            ConnectGateway.Click += (object sender, RoutedEventArgs e) => Client.InitiateClient();
        }
```

None of both `InitiateClient` and `InitiateServer` are awaited (they're not returning anything anyway), is it important ?

Now that you say it I realize my `async` / `await` operators are completely useless

**Comment by SeppPenner** [comment]
> Now that you say it I realize my async / await operators are completely useless

That's what I was trying to say. My idea was that the code somehow runs away in the background because you're not waiting for it to complete. But I'm not sure anyway.

@chkr1011 Maybe you can have a look on this?

**Comment by Treycos** [comment]
Is there any way for me to get more details about what is causing the error ?

Using the `MqttNetGlobalLogger` did not give more details than the exception message.

Is there a way I can check that the server is truly online ?

**Comment by Treycos** [comment]
The port seems to be opened in the resource monitor
![image](https://user-images.githubusercontent.com/19551067/60164922-b96e1f00-97fe-11e9-82a3-30c52dffd9c9.png)


However an external port checked does not see it
![image](https://user-images.githubusercontent.com/19551067/60165002-dacf0b00-97fe-11e9-8a46-20c33f0068a1.png)

**Comment by SeppPenner** [comment]
> Is there a way I can check that the server is truly online?

You can try to connect with a tool like MQTTspy or MQTT.fx.

**Comment by chkr1011** [comment]
The UWP app also has proper permissions (Internet (Client)  AND Internet (Server))?

**Comment by Treycos** [comment]
You're right, I did not configure the router and shouldn't.

Here's the client app permissions:

![image](https://user-images.githubusercontent.com/19551067/60166566-b7598f80-9801-11e9-8363-f14ee238c0a0.png)

And the server one:

![image](https://user-images.githubusercontent.com/19551067/60166617-c8a29c00-9801-11e9-8299-8888f4ac2296.png)

**Comment by SeppPenner** [comment]
Can we get the whole project for testing purposes?

**Comment by chkr1011** [comment]
Oh wait. I see you use 127.0.0.1.. that does not work. In UWP all apps are isolated and not allowed to communicate with localhost. There is a setting for it to disable this for debugging purposes. But for me that setting never worked.

I ended up using the server only. You can use a message interceptor to deal with ALL incoming messages and you can also publish messages.

**Comment by Treycos** [comment]
It seems that it could be the origin of my problem, thanks !
In my project's properties, the 'Allow local network loopback' is checked though
![image](https://user-images.githubusercontent.com/19551067/60170535-e4f60700-9808-11e9-978a-4f9a2f50c537.png)

As [the doc states it](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/deploying-and-debugging-uwp-apps#debugging-options), it should prevent this problem.

I also tried the `c:\>checknetisolation loopbackexempt -a -n=<package family name>` command but it didnt solve the problem either.

**Comment by SeppPenner** [comment]
I guess that's why I never liked UWP much... I worked with it once only and the emulator always did some strange, unexpected things.

**Comment by chkr1011** [comment]
Yes that is the setting. For me it never worked 😐

**Comment by Treycos** [comment]
Umm.. would creating a standard library to make the connection and then importing it in the App do the trick ?

**Comment by Treycos** [comment]
Alright, the connection works perfectly fine with another PC on the same switch.
I'll probably create a VM later.

Thank you for your help

**Comment by SeppPenner** [comment]
I have added this to the wiki under https://github.com/chkr1011/MQTTnet/wiki/Server#windows-iot-core-and-uwp-localhost-loopback-addresses and https://github.com/chkr1011/MQTTnet/wiki/Tips-and-Tricks#windows-iot-core-and-uwp-localhost-loopback-addresses.
