### ISSUE TITLE
Compile error when using MQTTnet.AspNetCore v3.0.3 (and 3.0.7).

### ISSUE THREAD

**Issue by fgretief** [chkr1011/MQTTnet#677]
I get the following compile error when trying to build a sample project with MQTTnet.AspNetCore v3.0.3 from NuGet.  I have tried adding MQTTnet v3.0.3 to the project, but with no effect.

The code compile and executes when v3.0.2 is used, but v3.0.3 does not.

```
1>------ Build started: Project: MqttServerApp, Configuration: Debug Any CPU ------
1>Program.cs(22,13,22,38): error CS0012: The type 'IMqttServer' is defined in an assembly that is not referenced. You must add a reference to assembly 'MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'.
1>Program.cs(27,13,27,41): error CS0012: The type 'IMqttServerOptions' is defined in an assembly that is not referenced. You must add a reference to assembly 'MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'.
1>Program.cs(27,13,27,41): error CS0012: The type 'MqttServerOptionsBuilder' is defined in an assembly that is not referenced. You must add a reference to assembly 'MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'.
1>Done building project "MqttServerApp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

MqttServerApp.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MqttNet.AspNetCore" Version="3.0.3" />
  </ItemGroup>

</Project>
```
Program.cs
```csharp
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using MQTTnet.AspNetCore;

namespace MqttServerApp
{
    class Program
    {
        static void Main(string[] args)
        {
            WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().Build().Run();
        }
    }

    public class Startup
    {
        public void Configure(IApplicationBuilder application)
        {
            application.UseStaticFiles();
            application.UseMqttServer(c => { });
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHostedMqttServer(c => { });
        }
    }
}
```

**Comment by fgretief** [comment]
Duplicate of #390

**Comment by chkr1011** [comment]
OK but what happens if you just add _MQTTnet_ 3.0.3 to the project?

**Comment by chkr1011** [comment]
I created a completely new ASP.NET project, added MQTTnet ASP.NET extension ONLY and it works perfectly. The interface _IMqttServer_ is found properly. Please try to clean/rebuild/nuget restore your project.

**Comment by SeppPenner** [comment]
I can reproduce the issue. Reference: https://github.com/mqttnettest/Issue677Test.

> OK but what happens if you just add MQTTnet 3.0.3 to the project?

The same error... Check the https://github.com/mqttnettest/Issue677Test/tree/master/Issue677Test2 project.

**Comment by SeppPenner** [comment]
![image](https://user-images.githubusercontent.com/9639361/60244801-80e04b00-98bb-11e9-8cd1-8ebc0f68d345.png)

**Comment by SeppPenner** [comment]
This seems to be caused by the `services.AddHostedMqttServer(mqttOptions);` call.

**Comment by chkr1011** [comment]
OK I had the wrong Interface. For me it also does not work. But again the IMqttServer interface is working which is also coming from the MQTTnet lib instead of the extension library.

Adding the MQTTnet lib directly is possible but does not solve the problem. Very strange!

Is maybe the referenced ASP.NET lib not compatible? Because it requires that service collection.

**Comment by SeppPenner** [comment]
> Is maybe the referenced ASP.NET lib not compatible? Because it requires that service collection.

That might be a reason...

**Comment by fgretief** [comment]
The error is looking for an assembly with a PublicKeyToken. 
> error CS0012: The type 'IMqttServerOptions' is defined in an assembly that is not referenced. You must add a reference to assembly 'MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'.

Using dotPeek, I looked at the meta data of the MQTTnet.dll files in the NuGet package:

>// Assembly MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=null
>// MVID: CF2294BC-22C9-4DF9-A752-ADAC32691622
>// Assembly references:
>// netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
>...
>[assembly: TargetFramework(".NETStandard,Version=v2.0", FrameworkDisplayName = "")]

>// Assembly MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7
>// MVID: C013CD92-8DA2-4A28-B895-B7C337F60DB1
>// Assembly MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7
>// MVID: C013CD92-8DA2-4A28-B895-B7C337F60DB1
>// Assembly references:
>// System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>...
>[assembly: TargetFramework(".NETStandard,Version=v1.3", FrameworkDisplayName = "")]

>// Assembly MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7
>// MVID: 0B3389AA-CD20-499B-8112-1A82398596D4
>// Assembly references:
>// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
>...
>[assembly: TargetFramework(".NETFramework,Version=v4.6.1", FrameworkDisplayName = ".NET Framework 4.6.1")]

>// Assembly MQTTnet, Version=3.0.3.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7
>// MVID: A9D2BD0B-2588-4F82-88A7-46E9D042E82E
>// Assembly references:
>// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
>...
>[assembly: TargetFramework(".NETFramework,Version=v4.5.2", FrameworkDisplayName = ".NET Framework 4.5.2")]

Looks like there is a problem with the PublicKeyToken of the .NET Standard 2.0 assembly. Which might explain why it can't find the assembly.

**Comment by chkr1011** [comment]
I also found that one diff with 3.0.2 is that the assembly version is no longer 1.0.0. It is now 3.0.3 (same as nuget version). I assume it is coming from the MQTTnet.Server builds because these will rebuild all assemblies and this will override the original ones which are intended for nuget release. This may also explain the issue you mentioned because the first build creates the properly but the build for MQTTnet.Server overrides that bins. I moved nuget generation BEFORE the generation of MQTTnet.Server. Hopefully this will fix it.

**Comment by chkr1011** [comment]
I released 3.0.4 which works again.

**Comment by SeppPenner** [comment]
Hi @chkr1011. I'm afraid but this occurs in version 3.0.7 again...

![image](https://user-images.githubusercontent.com/9639361/63254723-854e3200-c274-11e9-9870-5a50bbb38fd7.png).

Exactly the same issue with the same method: `AddHostedMqttServer`.

Adding the `MQTTnet` package additionally doesn't have an effect.

**Comment by chkr1011** [comment]
O sh... I am afraid that adding the test execution to the build script overrides the binaries again like in the previous issue. I will release 3.0.8 now. It has no change apart from a reordered build script.

Please let me know if the new version works again.

**Comment by SeppPenner** [comment]
3.0.8 fixes this for me :)
