### ISSUE TITLE
v3.0.2 SubscriptionInterceptor callback not firing

### ISSUE THREAD

**Issue by wheel1992** [chkr1011/MQTTnet#678]
Hi @chkr1011 , I've tried to intercept the subscription to filter some clients. However, the `WithSubscriptionInterceptor` callback is not fired at all. `WithConnectionValidator` is working as expected.

- Version
  - 3.0.2

- Environment
  - .Net Core 2.1

```c#
// Startup.cs

public void ConfigureServices(IServiceCollection services) {
...
var mqttOptions = new MqttServerOptionsBuilder()
            .WithSubscriptionInterceptor(c => {
                // This callback area is not fired regardless tested using breakpoint and Console.WriteLine
                Console.WriteLine($"WithSubscriptionInterceptor: client id = {c.ClientId}");
                c.AcceptSubscription = false;
                c.CloseConnection = true;
            })
            ...
            // Other validation + interceptor
           .Build();

           services.AddHostedMqttServer(mqttOptions);
           services.AddMqttTcpServerAdapter();
           services.AddMqttWebSocketServerAdapter();
           ...
}
```

**Comment by SeppPenner** [comment]
I will try this and verify it. Check https://github.com/mqttnettest/Issue678Test soon.

**Comment by SeppPenner** [comment]
Ah, this is Asp.NetCore 2.1.

**Comment by SeppPenner** [comment]
@wheel1992 What kind of Asp.NetCore project did you set up. I do not even get it to run properly like this. Check https://github.com/mqttnettest/Issue678Test/blob/master/log.txt...

**Comment by wheel1992** [comment]
Hi @SeppPenner , yup, I'm using `MQTTnet.AspNetCore`. 
Not sure if my understanding for `WithSubscriptionInterceptor`. I have a gateway which has an editable field called `Publish Topic`. Does this topic checked in `WithSubscriptionInterceptor`?

**Comment by chkr1011** [comment]
The UnitTest for that works perfectly. 

The subscription interceptor is called whenever a client sends a SUBSCRIBE packet in order to subscribe to a topic.

**Comment by wheel1992** [comment]
Sorry about my mistake! Appreciate @chkr1011  and @SeppPenner !
