### ISSUE TITLE
MqttNetTrace

### ISSUE THREAD

**Issue by haeberle** [chkr1011/MQTTnet#68]
In my app I have to instantiate more than one client. Issue is, as long the MqttNetTrace is a static class, I’m not able to differentiate messages between the different client or server instances in my app. I defined an interface based on the MqttNetTrace and added the interface as property in the MqttServerOptions / MqttClientOptions and reimplement the MqttNetTrace based in the Interface but not static. 
I’m not sure how I can share the changes, but from my view that helps to go away from a predefined static trace model. 

Regards
Hans

**Comment by chkr1011** [comment]
Hi,
I will add the event of the trace class to the options. The write methods are only for internal purposes.

I am also interested in the use case for having multiple clients. Can you give me some details?

Best regards
Christian

**Comment by JTrotta** [comment]
@haeberle , yes please. Which are the case when more clients on the same machine are needed?
I'm curious.

**Comment by haeberle** [comment]
Thanks Christian

sure, the app has to translate data between two or more brokers and also other protocols, like KNX, Siemens Logo, S7, etc. And also to act as a broker if needed.

**Comment by haeberle** [comment]
I can share the code if needed, I did the trace changes already and the test is running...

**Comment by chkr1011** [comment]
@haeberle Thank you but sharing is not required. I already changed a lot due to new features. Writing it on my own seems to be faster 😄 

Sounds like a smart home project. Tell me more. I also have a smart home project called "Wirehome" which is also here on GitHub. So I am very interested 😄 

Best regards
Christian

**Comment by chkr1011** [comment]
@haeberle I refactored the tracing. You can find an example in the Wiki and the code in the _develop_ branch. Please let me know if this fits your needs.

**Comment by haeberle** [comment]
Perfect Christian, I will test it. Thanks a lot. I will share more infos about the project if I have stable Mqtt Service.
I did a tour on your IoT project, looks really great, I like the agent !

**Comment by chkr1011** [comment]
@haeberle Thanks 😄 I will close this ticket. If you need something please reopen it. @JanEggers is refactoring the tracing at the moment. So the API will change (a lot) but it is still possible to distinguish between the clients and also the server components.
