### ISSUE TITLE
How to see what client sent message

### ISSUE THREAD

**Issue by FrancescoLusetti** [chkr1011/MQTTnet#685]
I want to see what client sent a message by reading the ClientId from the packet that arrived to the other client
Is there a possibility to do that?

**Comment by SeppPenner** [comment]
Well, you could implement `WithApplicationMessageInterceptor` like  described under https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-application-messages and re-send the message including the original client id to the client that should receive the message finally.

As far as I know there is no other option to do this but correct me if I'm wrong @chkr1011.

**Comment by chkr1011** [comment]
@SeppPenner Yes that is correct. This information is hidden to other clients. The only chance is that clients send this on their own (in payload etc.) or (as @SeppPenner described) by patching the payload at the server using the application message interceptor.
