### ISSUE TITLE
ManagedClient WithCleanSession

### ISSUE THREAD

**Issue by det-iot** [chkr1011/MQTTnet#687]
I'm trying to use the clean session with the managed client

```
var options = new ManagedMqttClientOptionsBuilder()
    .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
    .WithClientOptions(new MqttClientOptionsBuilder()
        .WithClientId(Guid.NewGuid().ToString())
        .WithTcpServer(configuracion.Servidor)
        .WithCredentials(configuracion.Username, configuracion.Password)
        .WithKeepAlivePeriod(TimeSpan.FromSeconds(60))
        .WithCleanSession(false) //sesion persistente
        .Build())
    .Build();
var mqttClient = new MqttFactory().CreateManagedMqttClient();

await mqttClient.SubscribeAsync(new TopicFilterBuilder()
    .WithTopic(configuracion.Topic)
    .WithExactlyOnceQoS()
    .Build());

await mqttClient.StartAsync(options);
```
 I have tried to connect to 2 different HiveMQ brokers with the following error:

```
Error: System.NotSupportedException: The managed client does not support existing sessions.
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.StartAsync(IManagedMqttClientOptions options)
   at MQTT_client.MQTT.ManageMQTTClient()
```

If I use other client, I can connect successfully using cleansesion to that HiveMQ broker.

So, is it not supported to use cleansession with managed client? or it could be done in a different way using the managed client?

I'm using the 3.0.2 MQTTnet version

**Comment by SeppPenner** [comment]
As far as I can see, you're right: It doesn't yet support this, does it? @chkr1011

**Comment by chkr1011** [comment]
No that is not supported yet but already on the feature list.

**Comment by det-iot** [comment]
Thank you for the information. I will wait for the feature. I think it would be very useful.

**Comment by det-iot** [comment]
@chkr1011 do you have an ETA of supporting this feature? I will need to choose in a short time a MQTT client which support clean session.

**Comment by chkr1011** [comment]
No not yet. Also will this feature come with some drawbacks because it cannot cover all use cases. But you can always use the regular _MqttClient_. The _ManagedMqttClient_ is just a small extension which reconnects automatically etc. With that base client you can do everything (including reuse of existing sessions).

**Comment by det-iot** [comment]
Hello,

I have tried with the base client. The problem here is even the exception now is not thrown when using `.With CleanSession(false)` the functioning I was looking for it does not work.

This are the steps:

1. The client (using MQTTNet) subscribe to the broker
2. The broker receives several messages and the client get them all
3. I stop the client running in visual studio
4. The broker keep receiving messages
5. I run again the client and the messages the broker received when the client was stopped are not get it by the client

If I follow that step 5 using Paho (in python) in the step 5 the client received all the messages that he can not receives when was disconnected

How could I do that using MQTTNet with the basic client?

Thank you

--------------------------------------------------

The code:
 
        public async Task ManageMQTTClient(MQTTConfiguration MQTTconfig, string topic, KinesisConfiguration Kinesisconfig)
        {

            try
            {
                var options = new MqttClientOptionsBuilder()
                            .WithTcpServer(MQTTconfig.Servidor)
                            .WithClientId(Guid.NewGuid().ToString())
                            .WithCredentials(MQTTconfig.Username, MQTTconfig.Password)
                            .WithCommunicationTimeout(System.TimeSpan.FromSeconds(600))
                            .WithCleanSession(false)
                            .WithKeepAlivePeriod(System.TimeSpan.FromSeconds(60))
                            .
                            .Build();

                var mqttClient = new MqttFactory().CreateMqttClient();
                mqttClient.UseDisconnectedHandler(async e =>
                {
                    Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                    await Task.Delay(TimeSpan.FromSeconds(5));
                    try
                    {
                        await mqttClient.ConnectAsync(options);
                    }
                    catch
                    {
                        Console.WriteLine("### RECONNECTING FAILED ###");
                    }
                });

                mqttClient.UseApplicationMessageReceivedHandler(e =>
                {
                    Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                    Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
                    Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
                    Console.WriteLine();
                    var fechaActual = DateTime.UtcNow;
                });

                await mqttClient.ConnectAsync(options);
                if (mqttClient.IsConnected)
                {
                    try
                    {
                        await mqttClient.SubscribeAsync(new TopicFilterBuilder()
                            .WithTopic(topic)
                            .WithExactlyOnceQoS()
                            //.WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce)
                            .Build());
                    }
                    catch (Exception e)
                    {
                        Debug.WriteLine("Error al conectarse al broker MQTT: "+e);
                    }
                }
                
            }
            catch (Exception e)
            {
                Console.WriteLine("Error cliente MQTT: " + e);
            }
        }
