### ISSUE TITLE
[question] WithStorage && ConnectionValidator

### ISSUE THREAD

**Issue by BI7PRK** [chkr1011/MQTTnet#688]
## MQTTnet.AspNetCore 3.0.5

I am trying to use MQTT Net in NetCore 2.2,  and I am having some problems while I am learning.
### WithStorage:
```C#
public Task SaveRetainedMessagesAsync(IList<MqttApplicationMessage> messages)
        {
            //var last = messages.LastOrDefault();
            //Logger.Info($"Last: {last.Topic } >> { Encoding.Default.GetString(last.Payload) }");
            foreach (var item in messages)
            {
                Logger.Info($"{item.Topic } >> { Encoding.Default.GetString(item.Payload) }");
            }
            return Task.CompletedTask;
        }
```

When publish the retained message from client. It will get all the messages, including the history of the message. How can I get the latest news from the current client?

### ConnectionValidator:
How to know client disconnection?

**Comment by SeppPenner** [comment]
I assume that this is cleared by the wiki? https://github.com/chkr1011/MQTTnet/wiki
