### ISSUE TITLE
Please change WebSocketStream to use WebSocket instead of ClientWebSocket

### ISSUE THREAD

**Issue by ChristianRiedl** [chkr1011/MQTTnet#69]
I integrated **MQTTnet** in an AspNetCore web app. `WebSocketStream `can be used for all websocket **client** **and** server implementations when you change the parameter to class _WebSocket_.

**Comment by chkr1011** [comment]
I will have a look and see how to change this. Do you agree that I add your code to the Wiki as a reference and also to the repository?

Let's continue with this topic at #65 because this is a duplicate.
