### ISSUE TITLE
Please help me, Destination is too short

### ISSUE THREAD

**Issue by fengbozs** [chkr1011/MQTTnet#692]
The server occasionally throws an exception when it publishes a message. Please help me.
>> [2019-07-09T12:05:03.7273535Z] [47] [MqttHostedServer.MqttServer.MqttClientSessionsManager.MqttClientConnection] [Error]: Sending publish packet failed (ClientId: client_9be48584-1650-4d60-91f6-95563a574a93).
System.ArgumentException: Destination is too short.
   at System.Span`1.CopyTo(Span`1 destination)
   at MQTTnet.AspNetCore.MqttConnectionContext.SendPacketAsync(MqttBasePacket packet, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Server.MqttClientConnection.SendAsync(MqttBasePacket packet)
   at MQTTnet.Server.MqttClientConnection.SendPendingPacketsAsync(CancellationToken cancellationToken)
>> [2019-07-09T12:05:03.7745408Z] [47] [MqttHostedServer.MqttServer.MqttClientSessionsManager.MqttClientConnection.MqttClientKeepAliveMonitor] [Verbose]: Client 'client_9be48584-1650-4d60-91f6-95563a574a93': Stopped checking keep alive timeout.
>> [2019-07-09T12:05:03.7763497Z] [6] [MqttHostedServer.MqttServer.MqttClientSessionsManager.MqttClientConnection] [Info]: Client 'client_9be48584-1650-4d60-91f6-95563a574a93': Session stopped.
>> [2019-07-09T12:05:03.7788522Z] [6] [MqttHostedServer.MqttServer.MqttClientSessionsManager] [Verbose]: Session for client 'client_9be48584-1650-4d60-91f6-95563a574a93' deleted.

**Comment by JanEggers** [comment]
see #691 a fi is on the way
