### ISSUE TITLE
publish symbol information for improved debug experiance

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#694]
it would be nice if mqttnet could provide its symbol information for improved debugging!

for maintainers this would make bug reports more valuable because stacktraces would include line numbers. 

I read there is now this:
https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

In our company we use this nuget package for libraries: 
SourceLink.Embed.AllSourceFiles

And this package for executables to make shure the pdbs are copied to the bin folder:
SourceLink.Copy.PdbFiles

thoughts?

**Comment by SeppPenner** [comment]
This would be a cool thing.

**Comment by chkr1011** [comment]
@JanEggers  Yes I agree. We already have symbols as nugets. But they are not uploaded because there are some pieces missing. I will check the article and try to fix it. If you already know that the problem is please help me out.

**Comment by chkr1011** [comment]
OK it seems that there was really just a very small piece missing in the scripts. To me it seems to work now. v3.0.6-beta1 is pushed and contains symbols.
