### ISSUE TITLE
Strange page in the wiki

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#700]
@BI7PRK: What is this page: https://github.com/chkr1011/MQTTnet/wiki/%E5%9C%A8AspNetCore-2.2%E4%B8%AD%E4%BD%BF%E7%94%A8MQTTnet intended to do?

Plus, if you want to provide something, I would say it makes more sense to add this in English, so that everyone can read it...

@chkr1011 What do you think?

**Comment by chkr1011** [comment]
I think this is a mistake and should be removed.

**Comment by SeppPenner** [comment]
@BI7PRK: I have deleted the page. Just for reference, a backup of the page can be found here: https://gist.github.com/SeppPenner/e257da2d8cf34df2948e122ba28f99c8.
