### ISSUE TITLE
Multiple subscription

### ISSUE THREAD

**Issue by det-iot** [chkr1011/MQTTnet#701]
Hello,

I would need to subscribe to different topic in the same program.

What I would need to know is how I should do it.

Should I created multiple client in the same program?

```
 static async Task Main()
        {
            await cliente.ManageMQTTClient(MQTTconfig,MQTTconfig.Topic1).ConfigureAwait(false);
            await cliente.ManageMQTTClient(MQTTconfig,MQTTconfig.Topic2).ConfigureAwait(false);
            Thread.Sleep(-1);
        }
```

Could I suscribed to multiple topics?

```
  public async Task ManageMQTTClient(<...>)
        {
            try
            {
                IMqttClientOptions options = new MqttClientOptionsBuilder()
                            .WithTcpServer(MQTTconfig.Servidor)
                            .WithClientId(MQTTconfig.Cliente)
                            .WithCredentials(MQTTconfig.Username, MQTTconfig.Password)
                            .WithCommunicationTimeout(System.TimeSpan.FromSeconds(600))
                            .WithCleanSession(false)
                            .WithKeepAlivePeriod(System.TimeSpan.FromSeconds(60))
                            .Build();

                IMqttClient mqttClient = new MqttFactory().CreateMqttClient();
                mqttClient.UseDisconnectedHandler(async e =>
                {
                    await Task.Delay(TimeSpan.FromSeconds(60));
                    try
                    {
                        await mqttClient.ConnectAsync(options);
                        if (mqttClient.IsConnected)
                            Console.WriteLine("Reconexion establecida con éxito");
                    }
                });
                mqttClient.UseApplicationMessageReceivedHandler(async e =>
                {
                    <...>
                });

                await mqttClient.ConnectAsync(options);
                if (mqttClient.IsConnected)
                {
                    try
                    {
                        await mqttClient.SubscribeAsync(new TopicFilterBuilder()
                            .WithTopic(topic1)
			                 .WithTopic(topic2)
                            .WithExactlyOnceQoS()
                            .Build());
                    }
                }                
            }
        }
```

Currently I'm testing it with the first approach I mentioned, but all the time I got the message used in UseDisconnectedHandler

**Comment by SeppPenner** [comment]
What do you mean by that: `Currently I'm testing it with the first approach I mentioned, but all the time I got the message used in UseDisconnectedHandler`?

**Comment by det-iot** [comment]
Currently I'm using this:

 static async Task Main()
        {
            await cliente.ManageMQTTClient(MQTTconfig,MQTTconfig.Topic1).ConfigureAwait(false);
            await cliente.ManageMQTTClient(MQTTconfig,MQTTconfig.Topic2).ConfigureAwait(false);
            Thread.Sleep(-1);
        }

But all the time it looks like the client reconnect all the time, because I have the following message (trace):

`"Reconexion establecida con éxito"`

So I'm not sure if this could be due I have 2 client connected to two different topics in the same program

**Comment by SeppPenner** [comment]
> So I'm not sure if this could be due I have 2 client connected to two different topics in the same program

I guess that's the problem exactly. As far as I know, your code should work properly if you use different client id paramaters, meaning: Add a string called `clientId` as parameter to the function `ManageMQTTClient` like this `ManageMQTTClient(MQTTconfig config, string topic, string clientId)` and fill it differently in both calls:

```csharp
static async Task Main()
{
    await cliente.ManageMQTTClient(MQTTconfig,MQTTconfig.Topic1, "Id1").ConfigureAwait(false);
    await cliente.ManageMQTTClient(MQTTconfig,MQTTconfig.Topic2, "Id2").ConfigureAwait(false);
    Thread.Sleep(-1);
}
```

However, it should be possible to subscribe to multiple topics with one client (I didn't test this yet, however).

**Comment by det-iot** [comment]
That was the problem.

If both of them have the same clientId one of them disconnect when the other connect. So using different names solved the problem

**Comment by pramodsingh** [comment]
> However, it should be possible to subscribe to multiple topics with one client (I didn't test this yet).

Just for people who might be looking to subscribe on multiple topic from a single client
`List<TopicFilter> topicFilters = new List<TopicFilter>();
            TopicFilter topicFilter = new TopicFilter();
            topicFilter.Topic = "hello/world/receive1";
            topicFilters.Add(topicFilter);
            topicFilter = new TopicFilter();
            topicFilter.Topic = "hello/world/receive2";
            topicFilters.Add(topicFilter);
            topicFilter = new TopicFilter();
            topicFilter.Topic = "hello/world/receive3";
            topicFilters.Add(topicFilter);
            await mqttClient.SubscribeAsync( `topicFilters.ToArray());`
