### ISSUE TITLE
Performance issues and halting while receiving high volume of messages under CPU load

### ISSUE THREAD

**Issue by ngdk** [chkr1011/MQTTnet#713]
### Describe the bug:

I conducted some performance testing to find a MQTT C# client for a project.  I compared MQTTnet 3.0.2 to paho.mqtt.m2mqtt 4.3.0.0, with mosquitto v1.5.8 as broker.

In stress testing - 100 packets/second round trip from client to broker to client, while under heavy CPU load - I noticed significant delays using the MQTTnet client.  Most messages were handled in <1 ms, but if CPU load was high, message handling time could increase dramatically, until the client became unresponsive.

This may be related to #243 on performance, and possibly #556 on async.

### Which project is your bug related to?

- [x] Client

### To Reproduce

Using 
 + MQTTnet 3.0.2 to receive messages on a given topic,
 + paho.m2.m2mqtt 4.3.0.0 to send messages on that topic,
 + mosquitto 1.5.8 as a broker on localhost,
 + internal C# System.Diagnostics.StopWatch timers

Run this code:
 + Every 1 second
    - Send 100 messages, spaced randomly by a few milliseconds
    - Tag each message with a unique ID and start a stopwatch for that message
    - Record the time each message arrives at client using its stopwatch

 + Run while under heavy system load
    - I used prime95 to induce 50% cpu usage, and realbench to induce 100% cpu usage.

This may or may not be reproducible using a MQTTnet client to send messages as well, that wasn't something I tested.

### Expected behavior

Using paho.mqtt.m2mqtt as a baseline:  m2mqtt as a client would receive all messages, even under 100% cpu usage with realbench running in the background.  Delays for receiving incoming messages would increase up to 200ms, getting 90% of packets through in 50ms or less.  Increasing throughput to 600msg/sec didn't seem to affect this at all.

Using MQTTnet as a client to receive messages, with 100% cpu usage from realbench in the background, would delay message handling increasingly as the stress test went on.  In less than a minute, 10 second delays were common, before the client stopped receiving any further messages and became unresponsive.

Increasing messages/second to 600 didn't seem to halt the MQTTnet client any sooner, oddly enough.  It would still halt within a minute.

### Code example

This is how I set up the MQTTnet client to receive messages.  The referred handling client_MqttMsgPublishReceived() is common with the m2mqtt client I tested.

```csharp

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using MQTTnet; //chkr1011/MQTTnet  version 3.0.2.0
using MQTTnet.Client;
using MQTTnet.Extensions;
using MQTTnet.Client.Options;

namespace mqttTest
{
                //An MQTTnet client for receiving messages, for stress testing
    class mqttTestReceiveMQTTnet : mqttTestReceive
    {
        IMqttClient mqttClient;

        public mqttTestReceiveMQTTnet(string mqttBrokerAddress, string topic = "mqtttest", int numMessagesPerBurst = 20, int numBursts = 10) : base(numMessagesPerBurst, numBursts)
        {
            var factory = new MqttFactory();
            mqttClient = factory.CreateMqttClient();

            var options = new MqttClientOptionsBuilder().WithTcpServer("localhost").Build();

            //Connect client - Wrapper for executing async method in synchronous class
            Task<MQTTnet.Client.Connecting.MqttClientAuthenticateResult> task = Task.Run<MQTTnet.Client.Connecting.MqttClientAuthenticateResult>(async () => 
                        await mqttClient.ConnectAsync(options));

            //Set up message received handler with MQTTnet:
            mqttClient.UseApplicationMessageReceivedHandler(e =>
            {
                //This is the same message handler used for both m2mqtt and MQTTnet
                base.client_MqttMsgPublishReceived(e.ApplicationMessage.Topic, e.ApplicationMessage.Payload, 
                             (byte)e.ApplicationMessage.QualityOfServiceLevel, e.ApplicationMessage.Retain);
            });

            Console.WriteLine($"setting up subscription to topic: {topic}.");
            mqttClient.UseConnectedHandler(e =>
           {
                // Subscribe to a topic with QoS 2
                mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic(topic).WithExactlyOnceQoS().Build());
            });
        }

    }
}


```

**Comment by chkr1011** [comment]
Comparing both libraries is not possible at all in my opinion. One reason is that this library does support async/await. Also that might be the reason for your behavior because you cannot give the receiving code any higher priority as other code which uses asnync/await. 

One thing you can try is to change to receive code to use _GetAwaiter().GetResult()_ (in receive loop) instead of using _await_. Using this approach will keep the receiver thread up and running forever.  It also might be possible to the the priority to _high_ then.

**Comment by ngdk** [comment]
Yeah, I was thinking it may have to do with async/await or thread priority.  I may come back to MQTTnet in the near future and try _GetAwaiter().GetResult()_.  If I do I will let you know what I find.

Thank you for the quick and helpful feedback.

**Comment by kingsley91-cpu** [comment]
@chkr1011 Still I am able to reproduce this issue with more packets per second and with a 100 percent CPU load in the MQTTnet even after I tried with GetAwaiter().GetResult(). any other way we could able to resolve this issue?
            var subscribeAsyncTask = _mqttClient.SubscribeAsync(options).GetAwaiter().GetResult();
and this way I'm handling asynchronous tasks as you suggest

**Comment by kingsley91-cpu** [comment]
@chkr1011  we are facing this issue only in Android and not in iOS we created a sample app also and it behaves the same, any idea why Android is slow of receiving messages

**Comment by kingsley91-cpu** [comment]
@chkr1011  forgot to mention, even without a CPU load issue is there, In sample app has the load of 10 to 13 percentage

**Comment by chkr1011** [comment]
@kingsley91-cpu Which version do you use? If only Android is affected I recommend to create a ticket in the Xamarin repo etc.

**Comment by kingsley91-cpu** [comment]
And this issue is with the latest MQTT net  4.3.2.930 version.

**Comment by kingsley91-cpu** [comment]
<img width="497" alt="Screenshot 2023-12-11 at 09 54 02" src="https://github.com/dotnet/MQTTnet/assets/152244941/fe787ee0-5358-4630-b7a6-126320ec5c7e">
We could able to fix this issue by increasing TCP buffer size to 1 MB
