### ISSUE TITLE
Session race on device reconnect

### ISSUE THREAD

**Issue by ikalkov** [chkr1011/MQTTnet#719]
### Describe the bug
Client doesn't receive any updates from server. This is difficult to reproduce and happens sometimes after a reconnect (but not always). I suspect a race condition during session re-creation (see log below).

### Which project is your bug related to?
- [ ] Client
- [ ] ManagedClient
- [ ] MQTTnet.Server standalone
- [x] Server
- [ ] Generic

### To Reproduce
Difficult to tell. We are working with MQTTnet v2.8.5 and preparing the switch to the newest version, but it will take a while to confirm.

### Additional context / logging

```batch
 1) MqttTcpServerAdapter.MqttTcpServerListener[6] (Verbose)
    Client '123.123.123.123:51234' accepted by TCP listener '0.0.0.0:1883, ipv4'.

 2) MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter[15] (Verbose)
    RX <<< Connect: [ClientId=abc123] [Username=myusername] [Password=mypassword] [KeepAlivePeriod=10] [CleanSession=True]

 3) MqttHandler
    Allowing connection for device abc123: ConnectionAccepted

 4) MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter[15] (Verbose)
    Disconnecting [Timeout=00:00:30]

 5) MqttServer.MqttClientSessionsManager.MqttClientSession.MqttClientKeepAliveMonitor[15] (Verbose)
    Client 'abc123': Stopped checking keep alive timeout.

 6) MqttServer.MqttClientSessionsManager.MqttClientSession[15] (Info)
    Client 'abc123': Disconnected (clean=True).

 7) MqttHandler
    Device abc123 is now offline

 8) MqttServer.MqttClientSessionsManager[15] (Verbose)
    Stopped existing session of client 'abc123'.

 9) MqttServer.MqttClientSessionsManager[15] (Verbose)
    Created a new session for client 'abc123'.

10) MqttServer.MqttClientSessionsManager[6] (Verbose)
    Session for client 'abc123' deleted.

11) MqttTcpServerAdapter.MqttTcpServerListener.MqttChannelAdapter[15] (Verbose)
    TX >>> ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=False]

12) MqttServer.MqttClientSessionsManager[15] (Info)
    Client 'abc123': Connected.

13) MqttHandler
    Device abc123 is now online
```

### Expected behavior
I would expect the line (10) not to happen after line (9). Since those calls are performed by different threads, it is probably a race condition. After connection completes, the device has no session, so it doesn't receive any topic updates.

**Comment by SeppPenner** [comment]
@chkr1011 I guess, this should not appear in the 3.0.5 version anymore...

**Comment by ikalkov** [comment]
Thanks for the super fast answer. I checked the git history of the MqttClientSessionsManager between 2.8.5 but didn't notice any related fixes. I will setup a test with latest NuGet package, but it is quite difficult to reproduce :(
