### ISSUE TITLE
Not able to Connect aws with Certificate

### ISSUE THREAD

**Issue by imran2say** [chkr1011/MQTTnet#721]
Log:

```log
 [{e.TraceMessage.Timestamp:O}] [{e.TraceMessage.ThreadId}] [{e.TraceMessage.Source}] [{e.TraceMessage.Level}]: {e.TraceMessage.Message}
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' in MQTTnet.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' in mscorlib.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' in mscorlib.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' in MQTTnet.dll
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' in mscorlib.dll
>[{e.TraceMessage.Timestamp:O}] [{e.TraceMessage.ThreadId}] [{e.TraceMessage.Source}] [{e.TraceMessage.Level}]: {e.TraceMessage.Message}
MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' was thrown.
   at MQTTnet.Internal.ExceptionHelper.ThrowIfGracefulSocketClose(Int32 readBytesCount) in F:\14-1-2019\trunk\MQTTnet\Source\MQTTnet\Internal\ExceptionHelper.cs:line 16
   at MQTTnet.Serializer.MqttPacketReader.<ReadFixedHeaderAsync>d__0.MoveNext() in F:\14-1-2019\trunk\MQTTnet\Source\MQTTnet\Serializer\MqttPacketReader.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__24.MoveNext() in F:\14-1-2019\trunk\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__23.MoveNext() in F:\14-1-2019\trunk\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<ReceivePacketsAsync>d__44.MoveNext() in F:\14-1-2019\trunk\MQTTnet\Source\MQTTnet\Client\MqttClient.cs:line 384
```

Code:

```csharp
 string BrokerAddress = "URL_ID-ats.iot.ca-central-1.amazonaws.com";
List<byte[]> certificates = new List<byte[]>();
X509Certificate CaCert = X509Certificate.CreateFromCertFile(@"C:\Iotdevices\AmazonRootCA1.crt");
certificates.Add(CaCert.Export(X509ContentType.SerializedCert));
X509Certificate2 ClientCert = new X509Certificate2(@"C:\Iotdevices\name-certificate.pfx", "Password");
certificates.Add(ClientCert.Export(X509ContentType.SerializedCert));
var options = new ManagedMqttClientOptionsBuilder()
   .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
   .WithClientOptions(new MqttClientOptionsBuilder()
	   .WithClientId(clientId)                   
	   .WithTcpServer(BrokerAddress)
	   .WithKeepAlivePeriod(TimeSpan.FromSeconds(20))
			 .WithTls(new MqttClientOptionsBuilderTlsParameters
			 {
				 UseTls = true,
				 SslProtocol = System.Security.Authentication.SslProtocols.Tls12,
				 AllowUntrustedCertificates = false,
				 Certificates = certificates,
				CertificateValidationCallback = (X509Certificate x, X509Chain y, SslPolicyErrors z, IMqttClientOptions o) =>
				 {
					 // TODO: Check conditions of certificate by using above parameters.
					 return true;
				 }
			 })
	   .Build())
.Build();

var mqttClient = new MqttFactory().CreateManagedMqttClient();
mqttClient.Connected +=
		(s, e) => Console.WriteLine(DateTime.Now.ToShortTimeString() + "connected.");
mqttClient.Disconnected +=
	(s, e) => Console.WriteLine(DateTime.Now.ToShortTimeString() + "disconnected");
mqttClient.ApplicationMessageReceived +=
	(s, e) => Console.WriteLine(DateTime.Now.ToShortTimeString() + "received: "/* + e.ApplicationMessage.ConvertPayloadToString()*/);
// await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("my/topic").Build());
await mqttClient.StartAsync(options);
await mqttClient.PublishAsync("telemetry","Test");
```

**Comment by SeppPenner** [comment]
Have you looked at https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws already?

Plus: Do you really need the managed mqtt client?

**Comment by imran2say** [comment]
@SeppPenner I am able to connect with AWS but not able to publish anything though MqttNet.
Temporary I decided to use m2mqtt: https://github.com/aws-samples/iot-dotnet-publisher-consumer 
but I need the managed client so I want to use MQTT net.

**Comment by SeppPenner** [comment]
@imran2say Okay... The problem is that I can't test this because I have no AWS instance available...

**Comment by jkoplo** [comment]
I have working code for connecting to AWS using MQTTnet and the PEM files and CA certs directly from AWS. It's a little different in Framework vs Core vs Net5 because Microsoft has changed certs a bit between all of those.

@chkr1011 - What's the best way for me to share this? I can add to the wiki documentation, make an example github repo, or add an extension/example to the MQTTnet repo.

**Comment by SeppPenner** [comment]
Sorry for the late reply. I would say, you can add it as a whole example as a Github repo and link it to the wiki.

**Comment by cjkarande** [comment]
@jkoplo even i am facing the same issue with AWS IoT over Mqtt using certificate. While you are trying to figure out the mode of sharing the code via the Repo, can you please share the code snippet here for a quick reference?

Hoping for an early...
Thanks.

**Comment by jkoplo** [comment]
@cjkarande - I wasn't sure if you are in Framework or in Core, but I have working examples for both:

[MQTTNet to AWS IoT - Core](https://gist.github.com/jkoplo/bd60cfe1a02c6e13b0a2d753289ae00f)
[MQTTNet to AWS IoT - Framework](https://gist.github.com/jkoplo/16f25875f7aca9503a7520fcda99005f)

It's worth noting that these gists also work for M2MQTT. The trick to it all is loading the certs into X509 objects and using a callback for verification (there's a callback for the M2MQTT signature in the helper class).

**Comment by cjkarande** [comment]
@jkoplo Thanks a ton. I appreciate your prompt response. Will try out your code snippet and let you know.

However, regarding the verification callback, in my code version (below) i had tried returning true in all cases. Should it not have the same effect?. This code did not work for me. Am i missing something?

            var options = new MqttClientOptionsBuilder()
                .WithClientId(Guid.NewGuid().ToString())
                .WithTcpServer("XXXX.amazonaws.com", 8883)
                .WithTls(new MqttClientOptionsBuilderTlsParameters() {
                    UseTls = true,
                    AllowUntrustedCertificates = true,
                    SslProtocol = System.Security.Authentication.SslProtocols.Tls12,
                    Certificates = new List<X509Certificate>() { caCert, clientCert },
                    CertificateValidationHandler = context => true
                })
                .WithProtocolVersion(MqttProtocolVersion.V311)
                .WithCommunicationTimeout(new TimeSpan(0, 0, 30))
                .WithKeepAlivePeriod(new TimeSpan(0, 0, 10))
                .Build();

**Comment by jkoplo** [comment]
From what you posted that looks correct. Always returning `true` isn't exactly secure, but probably fine for testing.

Usually when I've seen immediate disconnection it's due to your client attempting to do something that's not allowed by AWS. This could be:
1. Attempting to use a feature that isn't supported -> Retained messages, Will messages, Unsupported QoS (QoS 2).
2. Your `Thing` permissions/policy don't allow an action you're doing -> Susbscribing/publishing to a topic that's not allowed, etc.

I'd start by going through those pretty thoroughly and making sure they're set up properly.

**Comment by SeppPenner** [comment]
I've collected every troubleshooting tips under https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws now. There is a discussion available under https://github.com/chkr1011/MQTTnet/discussions/1225 where I'm trying to collect all issues with AWS now since all the same issues seem to occur very often.
