### ISSUE TITLE
[Server] Port 1883 is used even if only the encrypted port should be used.

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#726]
### Describe the bug
It seems like the default non HTTPS port `1883` is used even if only `.WithEncryptedEndpoint().WithEncryptedEndpointPort(8883)` is called.

### Which project is your bug related to?
- [x] MQTTnet.Server standalone
- [x] Server

### To Reproduce
1. Using this version of MQTTnet '3.0.0.5'.
2. Run the code from the example below.

### Expected behavior
Only port 8883 should be used to allow MQTT/S traffic only.

#### Before the start of the service
![image](https://user-images.githubusercontent.com/9639361/62106996-eeaad880-b2a6-11e9-9c1b-a7f722e9e4d1.png)

#### After the start of the service
![image](https://user-images.githubusercontent.com/9639361/62107141-46494400-b2a7-11e9-91bd-be987d1c179f.png)

#### Testing locally with the simplified example
![image](https://user-images.githubusercontent.com/9639361/62107962-18fd9580-b2a9-11e9-8013-7aab74f874c6.png)

![image](https://user-images.githubusercontent.com/9639361/62108061-519d6f00-b2a9-11e9-9d21-6f0f2bdec7dc.png)

### Additional context / logging
The service is run using [Topshelf](http://topshelf-project.com/) on a Windows server. However, this behaviour can be seen on a local instance as well (Running in debug mode, etc.).
The whole stuff of connection validation doesn't have an impact at all and can be removed from the example code, but I left it in for completeness and reference. The issue occurs in the simplified example as well. The process is the one of MQTTnet as it can be seen in the screenshots above.

Am I missing something @chkr1011?

### Code example
```csharp
namespace Test
{
	using System;
	using System.Collections.Generic;
	using System.IO;
	using System.Linq;
	using System.Security.Authentication;
	using System.Security.Cryptography.X509Certificates;
	using System.Text;
	using MQTTnet;
	using MQTTnet.Protocol;
	using MQTTnet.Server;
	using System.Reflection;

	public class User
	{
		public string UserName
		{
			get;
			set;
		}

		public string Password
		{
			get;
			set;
		}
	}

	public class Test
	{
		public static void Main()
		{
			IMqttServer mqttServer;
			var currentPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
			var users = new List<User>{new User{UserName = "Hans", Password = "Test1234"}};
			var certificate = new X509Certificate2(Path.Combine(currentPath, "certificate.pfx"), "asdf", X509KeyStorageFlags.Exportable);
			var optionsBuilder = new MqttServerOptionsBuilder().WithEncryptedEndpoint().WithEncryptedEndpointPort(8883).WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx)).WithEncryptionSslProtocol(SslProtocols.Tls12).WithConnectionValidator(c =>
			{
				var currentUser = users.FirstOrDefault(u => u.UserName == c.Username);
				if (currentUser == null)
				{
					c.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
					return;
				}

				if (c.Username != currentUser.UserName)
				{
					c.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
					return;
				}

				if (c.Password != currentUser.Password)
				{
					c.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
					return;
				}

				c.ReasonCode = MqttConnectReasonCode.Success;
			}

			).WithApplicationMessageInterceptor(message =>
			{
				Console.WriteLine($"Message: \nClientId = {message.ClientId}, Topic = {message.ApplicationMessage.Topic}," + $" Payload = {Encoding.UTF8.GetString(message.ApplicationMessage.Payload)}, QoS = {message.ApplicationMessage.QualityOfServiceLevel}," + $" Retain-Flag = {message.ApplicationMessage.Retain}");
			}

			);
			mqttServer = new MqttFactory().CreateMqttServer();
			mqttServer.StartAsync(optionsBuilder.Build());
		}
	}
}
```

### Simplified code example
```csharp
namespace Test2
{
	using System.IO;
	using System.Security.Authentication;
	using System.Security.Cryptography.X509Certificates;
	using MQTTnet;
	using MQTTnet.Server;
	using System.Reflection;

	public class Test
	{
		public static void Main()
		{
			IMqttServer mqttServer;
			var currentPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
			var certificate = new X509Certificate2(Path.Combine(currentPath, "certificate.pfx"), "asdf", X509KeyStorageFlags.Exportable);
			var optionsBuilder = new MqttServerOptionsBuilder().WithEncryptedEndpoint().WithEncryptedEndpointPort(8883).WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx)).WithEncryptionSslProtocol(SslProtocols.Tls12);
			mqttServer = new MqttFactory().CreateMqttServer();
			mqttServer.StartAsync(optionsBuilder.Build());
		}
	}
}
```

**Comment by SeppPenner** [comment]
A test project is here, too: https://github.com/mqttnettest/Issue726Test.

**Comment by mow20** [comment]
Did you try to use .WithoutDefaultEndpoint() in the options builder?

**Comment by SeppPenner** [comment]
> @SeppPenner Did you try to use .WithoutDefaultEndpoint() in the options builder?

Why would I want to do that? I don't want to use the default endpoint...

**Comment by mow20** [comment]
I think that .WithoutDefaultEndpoint() just removes the default 1883 listening port, something like this:
var optionsBuilder = new MqttServerOptionsBuilder().WithoutDefaultEndpoint().WithEncryptedEndpoint().WithEncryptedEndpointPort(8883).WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx)).WithEncryptionSslProtocol(SslProtocols.Tls12);

**Comment by SeppPenner** [comment]
> I think that .WithoutDefaultEndpoint() just removes the default 1883 listening port, something like this may work for you based on your example:
> `var optionsBuilder = new MqttServerOptionsBuilder().WithoutDefaultEndpoint().WithEncryptedEndpoint().WithEncryptedEndpointPort(8883).WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx)).WithEncryptionSslProtocol(SslProtocols.Tls12);`

I guess, you're right... I missed the **Without** in `WithoutDefaultEndpoint()`...

In my opinion, this should be documented...

**Comment by SeppPenner** [comment]
Is now documented under https://github.com/chkr1011/MQTTnet/wiki/Server#using-a-certificate.
