### ISSUE TITLE
DubFlag missing, or?

### ISSUE THREAD

**Issue by 1iveowl** [chkr1011/MQTTnet#73]
Is there a reason that you did not implement the [DubFlag](https://github.com/chkr1011/MQTTnet/blob/master/MQTTnet.Core/MqttApplicationMessage.cs) as part of Publish?

Or, maybe I'm just overlooking something? 

[On DubFlag](https://www.hivemq.com/blog/mqtt-essentials-part-4-mqtt-publish-subscribe-unsubscribe).

**Comment by chkr1011** [comment]
If it is missing it is a bug. I also remember adding support for it. Probably I forgot a place. Can you give me some details why you mentioned this?

**Comment by 1iveowl** [comment]
Sure. I'm in the process for creating a cross platform Xamarin MQTT Tester app and was implementing Publish and noticed that the Dub Flag was missing.

**Comment by chkr1011** [comment]
Cool, let me know if this library works with Xamarin. I also have a app on my wishlist but you are faster. 

But what exactly do you mean with the "missing" Dub-Flag? In the _MqttApplicationMessage_? From my understanding a user cannot set it actively. Only the client can use it internally and let the server know that the message was already sent. Or at least tried.

**Comment by 1iveowl** [comment]
Sure, but in a test scenario that is what you might want to do.

And yes, the library world fine with Xamarin.

**Comment by chkr1011** [comment]
OK so only for testing purposes but not a real live scenario. I have doubts exposing it. Let me read some documents about MQTT. I will decide then 😄 

Awesome. I tried it with Xamarin.Android but it didn't work. The code always stops after ConnectAsync. It simply hangs and I didn't found a solution. The debug output shows zillions of error because lots of .net libraries were not found. Can you tell me what you have done? Anything special beside adding proper app permissions like Internet?

**Comment by chkr1011** [comment]
I just found that line in the official docs: 
> It is important to note that the DUP flag refers to the Control Packet itself and not to the Application Message that it contains. 

As far as I understand this it means that the Dup flag shall not be exposed to a application message. Only the client uses it internally for its communication retries etc. I also didn't find something else. If I expose it the value must be validated. Sending 0 and it was already tried is a protocol violation. Also sending 1 and it was never sent before is also a violation. So in my opinion this will only produce more problems. What do you think?

**Comment by 1iveowl** [comment]
Sound right. I didn't study the spec that close. 

Regarding Xamarin. It just worked. I don't recall any issues.

I'm using it with the latest version of Xamarin. Maybe it's because I've set it up with .Net Standard.

**Comment by 1iveowl** [comment]
Just found [this](https://www.hivemq.com/blog/mqtt-essentials-part-4-mqtt-publish-subscribe-unsubscribe): 

> DUP flag
The duplicate flag indicates, that this message is a duplicate and is resent because the other end didn’t acknowledge the original message. This is only relevant for QoS greater than 0 and more details are in part 6, which is about QoS levels. This resend/duplicate mechanism is typically handled by the MQTT client library or the broker as an implementation detail.

Also, see [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html) in section 3.3.1.1 Dup in the OASIS 3.1.1. Spec
