### ISSUE TITLE
Deadlock when sending message inside ApplicationMessageReceivedHandler

### ISSUE THREAD

**Issue by paolofulgoni** [chkr1011/MQTTnet#731]
### Describe the bug

If I try to publish a message with AtLeastOnce QoS from the ApplicationMessageReceivedHandler, the message is correctly sent, but the execution of the handler is stuck. It looks like a deadlock.

Everything is working fine with AtMostOnce QoS

### Which project is your bug related to?

Client

### To Reproduce

I changed a test so that it fails, showing the issue: https://github.com/paolofulgoni/MQTTnet/commit/d351a721aa4299d47a3e784bbad2870a75ba8982

### Expected behavior

I expect the handler to continue the execution.

**Comment by paolofulgoni** [comment]
I guess that the `Task.Run` that I removed from the test was there because of this issue, right?

**Comment by SeppPenner** [comment]
Which issue? This one https://github.com/chkr1011/MQTTnet/issues/158?

**Comment by paolofulgoni** [comment]
No, I wasn't referring to that issue. I meant that when @chkr1011 wrote that test, he probably added the `Task.Run` as a workaround because otherwise the test would fail.

https://github.com/chkr1011/MQTTnet/blob/7aa4d5159c6c8a03b0cce3320beb3c83c5e5fc31/Tests/MQTTnet.Core.Tests/MqttClient_Tests.cs#L40

**Comment by SeppPenner** [comment]
Ah, okay. Yeah, it might be like that.

**Comment by paolofulgoni** [comment]
it may be a duplicate of #648

**Comment by SeppPenner** [comment]
This seems to be very similar, yes.

**Comment by paolofulgoni** [comment]
OK, so I'm closing the issue. Thanks

**Comment by SeppPenner** [comment]
Just for reference again: Check out @chkr1011's comments under https://github.com/chkr1011/MQTTnet/issues/648#issuecomment-499596351 and https://github.com/chkr1011/MQTTnet/issues/648#issuecomment-499997450 to find workarounds.
