### ISSUE TITLE
MQTTv5 - The AssignedClientId is ignored in ClientConnected, ClientDisconnected, and is never sent when connection is successful

### ISSUE THREAD

**Issue by bcrosnier** [chkr1011/MQTTnet#745]
### Describe the bug
I've been trying to use server-assigned ClientIds, as designed in MQTT v5.0 3.1.3.1 Client Identifier (ClientID).

I'd like your advice on normative statement MQTT-3.1.3-7, stating:
> It MUST then process the CONNECT packet as if the Client had provided that unique ClientID, and MUST return the Assigned Client Identifier in the CONNACK packet [MQTT-3.1.3-7].

At time of writing, while it is possible to set `AssignedClientIdentifier` in `MqttConnectionValidatorContext`, which then [replaces `connectPacket.ClientId`](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientSessionsManager.cs#L308), `HandleClientAsync()` will still use [the original `clientId`](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientSessionsManager.cs#L243) (which is always empty, which is we we're using `AssignedClientIdentifier`).

This empty `clientId` is then used when calling `HandleClientConnectedAsync()` and `HandleClientDisconnectedAsync()`.

This makes it awkward to properly identify clients from a `ClientConnectedHandler` or a ClientDisconnectedHandler`.

Furthermore, in the event of a successful connection, the client is never informed of its `AssignedClientIdentifier`: the `CONNACK` packet [does not, in fact, have any of the v5 Properties](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientConnection.cs#L144).

Interestingly enough, on a non-successful response, the v5 Properties are properly sent: [`DataConverter.CreateConnAckPacket()` is used](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientSessionsManager.cs#L251) instead of `new MqttConnAckPacket()`.

To sum up:
- When using `AssignedClientIdentifier`, the `ClientId` available in `ClientConnectedHandler` and `ClientDisconnectedHandler` is always empty, even if `AssignedClientIdentifier` is set. Is this normal?
- The `CONNACK` packet from a successful authentication does not have any of the v5 Properties, whereas the one from a non-successful authentication does. Is this normal?

FYI: My use-case is about self-enrolling devices, which try to obtain their own authentication information using MQTT from start to finish, without relying on other protocols to get the job done. It's still possible without auto-assigned IDs - it's just that the clients needs to generate a random clientId and the server needs to map it.

### Which project is your bug related to?
- Server

### To Reproduce
Using MQTTnet.AspNetCore 3.0.6:

- Create a Client with a `null` ClientId
- Create a Server with:
  - a custom `IMqttServerConnectionValidator` that sets `AssignedClientId` and returns otherwise successfully
  - a custom `IMqttServerClientConnectedHandler`
  - a custom `IMqttServerClientDisonnectedHandler`
- Connect the Client to the Server
- Try to obtain `AssignedClientId` in either the Client, `IMqttServerClientConnectedHandler`, or `IMqttServerClientDisonnectedHandler`

### Expected behavior
`AssignedClientIdentifier` is available in `ClientConnectedHandler`, `ClientDisconnectedHandler`, and in the `CONNACK` packet

**Comment by chkr1011** [comment]
To sum up: The server does not support MQTTv5 features yet. It accepts connections from v5 clients and can deal with all packages but special logic is not fully supported yet.

But starting with version 3.1.x of this library more and more MQTTv5 features will be implemented.
But I will have a look if a quick fix is possible because in general the server already sets a custom client ID if no client ID was sent by the client.

**Comment by bcrosnier** [comment]
I have a PR and a unit test that fixes all three of these, but pass on the `MqttConnectionValidatorContext` to `MqttConnection.RunAsync()` so that it can call `DataConverter.CreateConnAckPacket(connectionValidatorContext)`. I'm not sure I like it - I'll submit it anyway.

Alternatively, The `MqttConnAckPacket` can be given (or forged) above.
