### ISSUE TITLE
Can MQTTnet client connect to other mqttserver via websockets?

### ISSUE THREAD

**Issue by BenDerPan** [chkr1011/MQTTnet#748]
### Describe your question
Can MQTTnet client connect to other mqttserver via websockets? such as [emitter](https://github.com/emitter-io/emitter)

### Which project is your question related to?

- Client
- ManagedClient

**Comment by SeppPenner** [comment]
I would say yes. Have you tried https://github.com/chkr1011/MQTTnet/wiki/Client#websocket-connection?

**Comment by BenDerPan** [comment]
yes, I follow the wiki documents, my situation is : I use [Uno](https://github.com/unoplatform/uno) WebAssembly to build a web with C# backend(which instead of javascript to do the emitter pub/sub), and I get MQTTnet.NETStandard from nuget, then I build a test 
```C#
//Connected handler
 public class ConnectedHandler : IMqttClientConnectedHandler
        {
            public Task HandleConnectedAsync(MqttClientConnectedEventArgs eventArgs)
            {
                return Task.Run(() =>
                {
                    
                    Console.WriteLine($"Connected Success:{eventArgs.AuthenticateResult.ToString()}");
                });
            }
        }
//Main func test connect to the emitter server
var factory = new MqttFactory();
            var mqttClient = factory.CreateMqttClient();
            var options = new MqttClientOptionsBuilder()
                .WithWebSocketServer("localhost:8080")
                .Build();
            mqttClient.ConnectedHandler=new ConnectedHandler();
           var r= mqttClient.ConnectAsync(options, CancellationToken.None).Result; // Since 3.0.5 with CancellationToken
           

```
When I run it in web, there is an exception: `protocol option not supported`. then I build another project with .netcore command line app  as the same code with different nuget packages (MQTTnet+MQTTnet.Extensions.WebSocket4Net), it can work.

now I want to make it work with the webassembly (with uno), but I don't know how to fix the exception, in fact, the browser supports websocket(not raw tcp), so the connection should work.

**Comment by SeppPenner** [comment]
I remember that there was a similar issue somewhere...

**Comment by BenDerPan** [comment]
@SeppPenner  Uno have a websocket example [Uno Websocket](https://github.com/unoplatform/Uno.Wasm.WebSockets), Maybe you are right, then maybe I can use Uno websocket to replace the MQTTnet socket channel?  is that possible?

**Comment by SeppPenner** [comment]
I have no idea honestly. Maybe @JanEggers can help you here...

**Comment by BenDerPan** [comment]
thank you! :) @SeppPenner

**Comment by JanEggers** [comment]
https://github.com/chkr1011/MQTTnet/blob/9302e80d7361a2f675abab4f89445655b79bdc1d/Source/MQTTnet/Implementations/MqttWebSocketChannel.cs#L12

this is the mqttnet websocket adapter you can copy it to your project and wrap it around uno websocket instead of the .net websocket

**Comment by BenDerPan** [comment]
@JanEggers  great

**Comment by SeppPenner** [comment]
@BenDerPan I'm closing this issue now. If you have further questions or seing some issues with the integration into your project, feel free to contact us here again :)

**Comment by BenDerPan** [comment]
@SeppPenner  It works now ! thank you!
