### ISSUE TITLE
How to install the MQTTnet package on a project of offonline computers  throug nuget?

### ISSUE THREAD

**Issue by kevinlee0625** [chkr1011/MQTTnet#751]
It's ok to intall Packages on a project of offonline computers  throug nuget, but the MQTTnet has many Dependencies, I am failed to install it like that. Can somebody help me? thank you.

**Comment by kevinlee0625** [comment]
I have try to download .nupkg file and successfully install to my project of offonline computers throug nuget.

**Comment by SeppPenner** [comment]
Well, you would need to have the exact versions of the dependencies available offline, I guess...

**Comment by paolofulgoni** [comment]
This isn't an issue of this library but a general question about NuGet.

This question on stackoverflow may help you: https://stackoverflow.com/questions/8120289/is-there-a-way-to-download-packages-from-nuget-org-then-do-an-offline-installati

**Comment by SeppPenner** [comment]
@paolofulgoni Exactly...

**Comment by paolofulgoni** [comment]
@SeppPenner I don't know which is the workflow of the issues, but I think that this one should be closed

**Comment by SeppPenner** [comment]
@paolofulgoni You're right. I will close this issue now because it's not really related to the library itself and we already provided some hints.
