### ISSUE TITLE
MQTT With Max Payload Length

### ISSUE THREAD

**Issue by focusnt** [chkr1011/MQTTnet#755]
MQTT With Max Payload Length

**Comment by SeppPenner** [comment]
Can you explain this a bit more, please?

**Comment by focusnt** [comment]
I tried to transfer 2M binary pictures. MqttServer-side return error
How to configure server side MaximumPacketSize

**Comment by SeppPenner** [comment]
@chkr1011 A question for you.

**Comment by chkr1011** [comment]
Hi, there is a UnitTest called _Send_Long_Body_ which sends about 30 MB. This test works fine. So I assume there is something wrong in your setup. Please share some sample code or create a UnitTest which fails.

**Comment by focusnt** [comment]
Thinks, I'll take a test demo and try again.
Where is the unit test demo?

**Comment by SeppPenner** [comment]
> Where is the unit test demo?

https://github.com/chkr1011/MQTTnet/blob/9302e80d7361a2f675abab4f89445655b79bdc1d/Tests/MQTTnet.Core.Tests/Server_Tests.cs#L845

**Comment by JanEggers** [comment]
if you use websocket you have too look at kestrel settings

https://github.com/aspnet/Announcements/issues/267

**Comment by SeppPenner** [comment]
@focusnt Did you get this to work properly?

**Comment by kavea** [comment]
I hava met the same question. I  try to send about 300kb picture, but server return "resfuze conneted"(int out net),
but it worked well in local area network.
Have you try it in out net? not in local net?
thank you very much.

**Comment by SeppPenner** [comment]
I'm closing this now due to inactivity. As @chkr1011 said, there is a unit test for that reason. And @JanEggers gave and idea on how this should work for WebSockets.

@kavea:
> but it worked well in local area network.

There might be some firewall / router blocking something or your setup is wrong, I don't know. It's impossible to tell with more details...
