### ISSUE TITLE
aspnet core 3 migration

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#758]
I updated the codebase to aspnetcore 3.0 on a local branch.

https://github.com/JanEggers/MQTTnet/tree/aspnetcore3

Given that for netstandard 2.1 there will be no support for netfx im not sure if it is time yet to upgrade.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by SeppPenner** [comment]
I agree with that: 

> Library authors who need to support .NET Framework customers should stay on .NET Standard 2.0. In fact, most libraries should be able to stay on .NET Standard 2.0, as the API additions are largely for advanced scenarios.

From https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/ --> .NET platform support

**Comment by JanEggers** [comment]
this https://github.com/aspnet/AspNetCore/issues/14585 affects UseMqttServer the callback is not called because when we register it the hosted service is already started

**Comment by SeppPenner** [comment]
This should be possible now, I guess?

**Comment by JanEggers** [comment]
@chkr1011  what is your stance on this? we can only support core 3.0 if we add yet another TFM to the build. @SeppPenner  I would not document anything just yet. Id rather make the "out of the box" as smooth as possible.

**Comment by SeppPenner** [comment]
This seems to be a good idea, yes.
