### ISSUE TITLE
MQTT v5 ? How ?!

### ISSUE THREAD

**Issue by ncg81** [chkr1011/MQTTnet#759]
Hi,

This post pertains to MQTTnet **client**.

MQTT v5 is listed on the project's homepage as supported, however MQTT v5 introduces support for the **request/reply** pattern for which the MQTTnet **client** has no method signature.

I was expecting to see something along the lines of:

`Task PublishAsync(ManagedMqttApplicationMessage message, string requestTopic, string replyTopic);`

I am confused. Help!

**Comment by chkr1011** [comment]
Please checkout chapter 4.10 of the official MQTTv5 spec. There you can see how to use RPC feature. This is all supported in MQTTnet client already.
