### ISSUE TITLE
Example for subscribing to topics?

### ISSUE THREAD

**Issue by chall3ng3r** [chkr1011/MQTTnet#77]
I've been trying to find simple way to subscribe to few topics, but there's no example shared on wiki. 

I've setup `ApplicationMessageReceived` but it's not getting any messages. I guess I need to subscribe to a topic, but there I'm stuck :/

Any pointers how to do it?

**Comment by chall3ng3r** [comment]
Never mind, found one in Unit Tests

https://github.com/chkr1011/MQTTnet/blob/master/Tests/MQTTnet.TestApp.NetFramework/PerformanceTest.cs

**Comment by chkr1011** [comment]
Hi @chall3ng3r,
thank you for your support. If you need more information please let me know.
Best regards
Christian

**Comment by chall3ng3r** [comment]
Glad to contribute back, and thank you for awesome lib :)
