### ISSUE TITLE
Retained messages

### ISSUE THREAD

**Issue by fadeaway** [chkr1011/MQTTnet#770]
### Describe your question
When you publish a retained message via the server does it automatically send out the retained messages when a client subscribes? I'm am publishing a set of retained messages on start of the mqtt server but when a client connects and subscribes to the topic they don't receive any messages. I do see all of the messages I publish in my UseApplicationMessageReceivedHandler. Any direction here would be appreciated.

### Which project is your question related to?

- Server

**Comment by SeppPenner** [comment]
> When you publish a retained message via the server does it automatically send out the retained messages when a client subscribes?

It should, yes.

Do you have an example project or some code? It's quite difficult to check this without.
* Which version of the library are you using?
* Which project type does your project have? UWP, NetCore, ASPNetCore?
* Do you use the server and client project from MQTTnet or another server / client?

**Comment by ncg81** [comment]
@fadeaway maybe the following [article](http://www.steves-internet-guide.com/mqtt-clean-sessions-example/) can be of use.

**Comment by SeppPenner** [comment]
@ncg81 Fuuuuck :D I again forgor this clean session stuff... You're right, this might be causing the issue for @fadeaway

**Comment by SeppPenner** [comment]
Any updates on this @fadeaway? If not, I would like to close this issue.

**Comment by AblEdge** [comment]
Use MqttClient instead of ManagedClient in producer.
