### ISSUE TITLE
Question regarding MQTTnet Server

### ISSUE THREAD

**Issue by ncg81** [chkr1011/MQTTnet#771]
The **MQTTnet Server** entry on the repository home page, mentions that the server 

- **Runs und Windows, Linux, macOS, Raspberry Pi**

... and then a bit lower under **Supported frameworks**, the following two entries are listed:

**- Xamarin.Android 7.5+**
**- Xamarin.iOS 10.14+**

Can someone please clarify if it's safe to deploy the server in iOS & Android apps ?

Regards.

**Comment by SeppPenner** [comment]
Good question. I would assume that the Xamarin information is for the client part of the library only. Another question: Which use case would be reasonable to deploy a MQTT server in an Android app. I mean, you can use it as in app message exchange, but there are better solutions available, I guess :D

**Comment by ncg81** [comment]
> Another question: Which use case would be reasonable to deploy a MQTT server in an Android app. I mean, you can use it as in app message exchange, but there are better solutions available, I guess :D

A possible use case would be enabling p2p communication between apps with MQTTnet, without having to code your own socket based solution nor adding other dependencies.

**Comment by SeppPenner** [comment]
Ehm, you want to use P2P communication between apps on the same Android device? Okay. Is this not possible with a native component already? (I'm not an expert in Xamarin, but would have assumed that this is already possible somehow else :D).

**Comment by ncg81** [comment]
> Ehm, you want to use P2P communication between apps on the same Android device? 

Not between apps on the same device, but apps on different devices. Think LAN p2p.

**Comment by SeppPenner** [comment]
> Not between apps on the same device, but apps on different devices. Think LAN p2p.

Now it makes sense.

**Comment by ncg81** [comment]
@SeppPenner I found this [wiki page](https://github.com/chkr1011/MQTTnet/wiki/Server). The entry "Special notice for using the server project in Android" suggests that Android is a supported platform. And presumably iOS is supported too.

**Comment by SeppPenner** [comment]
Now I remember that. There was an issue with the loopback address under Android. Yes, the server should be available in Android and IOS as well.

**Comment by biapar** [comment]
> Good question. I would assume that the Xamarin information is for the client part of the library only. Another question: Which use case would be reasonable to deploy a MQTT server in an Android app. I mean, you can use it as in app message exchange, but there are better solutions available, I guess :D

Is there a Xamarin MQTT Client example?

**Comment by ncg81** [comment]
@biapar  :

[Wiki](https://github.com/chkr1011/MQTTnet/wiki)
[Wiki - Client](https://github.com/chkr1011/MQTTnet/wiki/Client)
[Wiki - Managed Client](https://github.com/chkr1011/MQTTnet/wiki/ManagedClient)
