### ISSUE TITLE
Portable Version: How to request authorization from a remote server via API?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#779]
Hi,

I customize the server to request authorization from a OAuth server. Is't possible to do the same with portable version?
Thanks.

**Comment by chkr1011** [comment]
Hi, in general I would say yes because you can make use of a HTTP client in python and thus send such requests replies. But I don't know if there are OAuth libraries available in Python which will forward such a request etc.
Best regards
Christian

**Comment by SeppPenner** [comment]
I only found this link: https://oauth.net/code/python/. Maybe this helps you.
