### ISSUE TITLE
Get on Client side the control for the PUBACK

### ISSUE THREAD

**Issue by baddev1** [chkr1011/MQTTnet#780]
Is it possible to controle the PUBACK?

That means after receiving a message, process the message in the client and only if the processing was successfully send the PUBACK. We like to ensure the retry of the message from serverside if something happens in the client (crash).

We see 2 scenarios. 
1. auto PUBACK
2. PUBACK send after processing the message in the client

**Comment by SeppPenner** [comment]
Might be similar to https://github.com/chkr1011/MQTTnet/issues/624. The OP there wants to check this in the server, however.

**Comment by chkr1011** [comment]
I am already planning a new feature which will split the MqttClient into a "MqttClient" and a "RawMqttClient". The new one will be dealing on packet level only. So you need to compose and deal with the incoming packets. This new client will give you all the freedom you need but you need to implement more things on the other hand. Hope that helps.

**Comment by liaoliaoda** [comment]
hello, could you pls show more msg about how to use the RawMqttClient?

**Comment by SeppPenner** [comment]
@liaoliaoda I'm not sure if the raw client is already that far to use it externally...

**Comment by chkr1011** [comment]
@SeppPenner From my side the RAW client is public. Maybe there are still some edge cases which have problems but I merged it after I tested various cases. The idea behind this client is to give the maximum of flexibility to the users. This means that you must send every packet on your own. This also includes receiving of messages. This is a lot of things to do but users can access ALL packages including all user properties etc.

@liaoliaoda If I need to explain the raw client to you then you should not use it 😄 It is basically only the transport layer and you have to send all packets according to the MQTT spec. This gives you a maximum of flexibility but you have to deal with all errors and MQTT features on your own. So with the raw client you first connect and then send a CONNECT packet. After that you must wait for the CONNACK packet (receive method) and so on...

**Comment by liaoliaoda** [comment]
Hi @SeppPenner , @chkr1011 ,

ok, got it. I have soled my problem, thanks very much.

**Comment by behroozbc** [comment]
> @SeppPenner From my side the RAW client is public. Maybe there are still some edge cases which have problems but I merged it after I tested various cases. The idea behind this client is to give the maximum of flexibility to the users. This means that you must send every packet on your own. This also includes receiving of messages. This is a lot of things to do but users can access ALL packages including all user properties etc.
> 
> @liaoliaoda If I need to explain the raw client to you then you should not use it 😄 It is basically only the transport layer and you have to send all packets according to the MQTT spec. This gives you a maximum of flexibility but you have to deal with all errors and MQTT features on your own. So with the raw client you first connect and then send a CONNECT packet. After that you must wait for the CONNACK packet (receive method) and so on...

hi 
I want to know is this merged? How I can use it?

**Comment by chkr1011** [comment]
@behroozbc It is merged and can be used. Please checkout the MQTT spec for more information about packet sequences etc.
