### ISSUE TITLE
Upgrade guidance from 2.7.5 to 3.0.8

### ISSUE THREAD

**Issue by kudlatiger** [chkr1011/MQTTnet#781]
### Describe your question
We are currently using version - [https://www.nuget.org/packages/MQTTnet/2.7.5](url)
And, we are planning to upgrade to [https://www.nuget.org/packages/MQTTnet/3.0.8](url)

So, the question is about backward compatibility. Our clients might still use the old client library, does it impact? where I can find upgrade documents?

**Comment by SeppPenner** [comment]
The upgrading guide is here: https://github.com/chkr1011/MQTTnet/wiki/Upgrading-guide.

However, I don't know the exact changes from 2.7.5 to 2.8.5...

@chkr1011 This is something you need to answer, please.

**Comment by chkr1011** [comment]
3.0.0 is almost a new implementation. Lots of namespaces have changed and a lot of new classes are added (mostly to support protocol version 5.0.0). You can for sure use different versions on client and servers because the underlying MQTT protocol is not changed. Only version 5.0.0 is added (to 3.1.0 and 3.1.1). But at the moment the server is not able to implement all of the new MQTTv5 features. Only packages are accepted and processed. Some features like assigned client IDs are supported already. Other things will follow within the next months.

**Comment by kudlatiger** [comment]
Thanks, Could u help me how to change below method?

**Existing method**

            mqttServer.ClientConnected += (s, e) =>
            {                
                     Console.WriteLine("Connected", e.Client.ClientId.ToString());
             };

I see it has been changed to `ClientConnectedHandler`

**Comment by SeppPenner** [comment]
@kudlatiger: I have tried your method in https://dotnetfiddle.net/ (A really great online compiler if you want to check something fast).

The method itself is fine. At the moment, you're running a method asynchronously, but don't perform any asynchronous operations in it.

E.g.

```csharp
mqttServer.ClientConnectedHandler = new MqttServerClientConnectedHandlerDelegate(ClientConnected);

private async void ClientConnected(MqttServerClientConnectedEventArgs e)
{
    await Task.Run(() => Console.WriteLine("Connected", e.ClientId.ToString()));
}
```

would solve this warning.

However, I'm not sure if you should use `Task.Run` in there. (I somehow remember that this caused issues).

**Comment by kudlatiger** [comment]
Great working!

What about ApplicationMessageReceived?  Which method replaced in upgraded version?

**Comment by SeppPenner** [comment]
As far as I know, `BoundInterNetworkAddress` for IPv4 communication and `BoundInterNetworkV6Address` if you want to use IPv6 communication. I guess, you still would use `BoundIPAddress` in most of the cases. This just depends on the IP address type you want to use.

**Comment by SeppPenner** [comment]
I have added a short hint to the updating guide. In other cases where something is unclear, just open another issue.

https://github.com/chkr1011/MQTTnet/wiki/Upgrading-guide#from-275-to-3xx
