### ISSUE TITLE
Interceptor for unsubscription

### ISSUE THREAD

**Issue by fgather** [chkr1011/MQTTnet#791]
### Describe the feature request
Currently there is the possibility to intercept subscription calls from the client to the server. However, there is no such mechanism to do the same for unsubscription

### Which project is your feature request related to?
- MQTTnet.Server standalone
- Server

### Describe the solution you'd like
An interceptor extension point which could enable us to intercept unsubscribe calls and for example change the topic list. Similar to the subscribtion

**Comment by chkr1011** [comment]
Hi,
I added this in develop branch. Please let me know if this works and fits your needs.

Best regards
Christian

**Comment by fgather** [comment]
Hi,

thank you very much for the fast implementation! Yes, that will work for our purpose!

Best Regards,
Florian

**Comment by fgather** [comment]
Hi @chkr1011 ,

do you plan to release the interceptor soon? As I said, it works for us, and is exactly what we were looking for. Thanks a lot!

Best regards,
Florian

**Comment by SeppPenner** [comment]
@chkr1011 This is already done, isn't it? It will be available in the next version.

@fgather I have no idea when this will be.
