### ISSUE TITLE
Add a MQTTException as a Base Class for all MQTTnet Exceptions

### ISSUE THREAD

**Issue by BigBadPhysicist** [chkr1011/MQTTnet#792]
### Describe the feature request
I would like to have the ability to catch all MQTTnet exceptions in only one try catch statement.

### Which project is your feature request related to?
- Client
- ManagedClient

### Describe the solution you'd like
Create 
 public class MqttException : Exception
{
}
 public class MQTTnetException : MqttException
{
}

### Additional context
I have a feature running which fetches data, computes something and sends the data via mqtt, a solution like above would help to create an easier solution to differentiate between mqtt errros and compute errors.

**Comment by chkr1011** [comment]
Hi,
in my opinion this is already done. There is the exception "MqttCommunicationException". The timeout exception already derives from that exception. Is there an exception which is not covered here? 

Best regards
Christian

**Comment by BigBadPhysicist** [comment]
My bad, I looked into all the classes and saw that  MqttProtocolViolationException and MqttCommunicationException derive from exception and didnt saw the connectiontion in TimeOut and UnexpectedDisconnect.

Sorry my bad.
