### ISSUE TITLE
Uncaught SocketException after upgrading VisualStudio

### ISSUE THREAD

**Issue by ZaubererHaft** [chkr1011/MQTTnet#793]
### Describe the bug
After upgrading to visual studio 16.3.x I am facing an uncaught SocketException when trying to do a connect without wifi/LTE connection or to an illegal endpoint.
The code is executed in a xamarin mobile application.

### Which project is your bug related to?
- Client

### To Reproduce
1. Make sure to have visual studio 16.3.x (it seems that the error does not occur in 16.2.x)
2. Create a xamarin forms blank app with an android project
3. Paste the code below in the App.xaml.cs
4. Run the android app -> Unhandled exception is thrown

### Screenshot
![excep](https://user-images.githubusercontent.com/14924145/68580438-adfe5600-0476-11ea-988a-2797924d49b2.PNG)

### Code example
 
```csharp
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
            MainPage = new MainPage();
        }

        protected override async void OnStart()
        {
            try
            {
                await DoConnect();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        private static async Task DoConnect()
        {

            var factory = new MqttFactory();
            var mqttClient = factory.CreateMqttClient();

            // Create TCP based options using the builder.
            var options = new MqttClientOptionsBuilder()
                .WithClientId("minimum")
                .WithTcpServer("doesnotexist")
                .WithCommunicationTimeout(TimeSpan.FromSeconds(5))
                .WithCleanSession(false)
                .Build();


            await mqttClient.ConnectAsync(options, CancellationToken.None);
        }

    }
```

**Comment by JanEggers** [comment]
are you sure your exception settings are correct? looks like vs defaulted to halt when an exception is thrown

**Comment by jimmy04500** [comment]
@ZaubererHaft Were you able to fix this issue? I'm having the same problem where if I try to connect to the client without wifi connection this exception occurs, and the ConnectAsync call never returns. I'm on 3.0.5

**Comment by ZaubererHaft** [comment]
We couldn't fix it so far. I'll give it a try with the new mqttnet version within the next days

**Comment by SeppPenner** [comment]
@ZaubererHaft Do you have an option to provide a stack trace so we can see where the issue comes from?

**Comment by ZaubererHaft** [comment]
@SeppPenner The code example works now as expected (the exception is caught properly and the app does not enter break state).

I will test this with the productive code tomorrow. We had some trouble finding a workaround for this issue as the returned tasks never got activated. Maybe the latest mqttNet/xamarin/whatever version fixed it.

**Comment by SeppPenner** [comment]
Ok, just give me new information when you tested this. Maybe, it's fixed and we can close the issue :)

**Comment by ZaubererHaft** [comment]
The porductive code runs flawlessly
Seems not to be a problem anymore :)
