### ISSUE TITLE
MVC broker example

### ISSUE THREAD

**Issue by TiedtTech** [chkr1011/MQTTnet#794]
### Describe your question
Would anyone have a basic example of broker implementation in MVC?

### Which project is your question related to?
- Server

**Comment by SeppPenner** [comment]
Hi, do you mean something like this: https://github.com/chkr1011/MQTTnet/wiki/Server#accessing-the-mqtt-server-in-an-aspnet-mvc-controller?

**Comment by SeppPenner** [comment]
Hi @TiedtTech. Did the wiki link help you with your problem? If not, could you please elaborate a bit what you already did / what you're trying to do?
