### ISSUE TITLE
windows 10 not connection error

### ISSUE THREAD

**Issue by panda-big** [chkr1011/MQTTnet#795]
### Describe the bug
windows 10 not connection error
https://github.com/aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4

### Which project is your bug related to?

- Client 
2.8.5
- ManagedClient
- MQTTnet.Server standalone
- Server 
AWS MQTT sigv4
- Generic

### To Reproduce
1. Using this version of MQTTnet '...'.  
2.8.5
2. Run this code '....'.
https://github.com/aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4
3. With these arguments '....'.
4. See error.
Unable to connect to remote server

### Additional context / logging
Include debugging or logging information here:

```batch
\\ Put your logging output here.
```
### Code example
 Please provide full code examples below where possible to make it easier for the developers to check your issues.
 
```csharp
\\ Put your code here.
```
https://github.com/aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4

**Comment by chkr1011** [comment]
Please try with latest version and reopen this ticket if this issue still exists.
