### ISSUE TITLE
MQTTnet source and nuget package no longer appear to support .Net Framework

### ISSUE THREAD

**Issue by cshepley** [chkr1011/MQTTnet#80]
While .Net Standard, UWP and .Net Core seem to work just fine, there is currently no assembly in the nuget package supporting the .Net Framework, and building from source causes output to contain numerous indirect references, making it unusable without many modifications to referencing projects.

**Comment by chkr1011** [comment]
@JanEggers Can you have a look here? You introduced the new project which supports both frameworks in one file. I have no idea what's wrong with that project.

**Comment by JanEggers** [comment]
im currently using version 2.4 with net461 the changes i did to the project structure are just in develop branch so i think there should not be a package. @cshepley what is theversion of the package u use without netfx support?

**Comment by chkr1011** [comment]
@JanEggers Yes you are right. I am focused on next version 😄

**Comment by chkr1011** [comment]
@cshepley Does this problem still exist? If yes can you provide some error messages etc. so we can check? If I don't get a reply I assume it is fixed and thus I will close this ticket. If this is wrong please reopen it if required.

**Comment by schtibb** [comment]
Greetings,

I just tried installing MQTTnet.2.4.0 on my .net framework 4.6.1 project and it require me to also install NetStandardLibrary.1.6.1, Microsoft.NETCore.Platforms.1.1.0 and a bunch of other packages as dependencies. Is it supposed to require all that?

![image](https://user-images.githubusercontent.com/3526608/32366000-8d9bc220-c07c-11e7-952e-7d2f5a3ec7a7.png)

**Comment by schtibb** [comment]
When I changed my project to .net framework 4.5 (from 4.6.1) it seems to not require all the packages listed in the previous posts.

![image](https://user-images.githubusercontent.com/3526608/32366146-285bea56-c07d-11e7-90d5-912a6721f136.png)

**Comment by JanEggers** [comment]
that is because Visual Studio chooses netstandard dll as net461 is closer to standard1.6 then to net45.

but the many packages are the way netstandard works, in dotnet core 2.0 ms introduced some "tree shaking" to remove unneeded packages / packages that are already on the machine when installing .net core runtime.

but until we upgrade to netstandard 2.0 that is the way its supposed to be i guess.
