### ISSUE TITLE
ASP.NET Core 3.0: Host MqttNet Server

### ISSUE THREAD

**Issue by bhopkinson** [chkr1011/MQTTnet#801]
### Describe your question
I would like to be able to host an instance of MqttNet Server in my ASP.NET Core 3.0 application using WebSockets. I am however struggling to piece together the information I need to get it to work. I have tried following the AspNetCore documentation available for 2.1 (https://github.com/chkr1011/MQTTnet/wiki/Server#aspnet-core-21), but this does not seem to work for 3.0. I believe I need to map a "/mqtt" endpoint - but I'm not really sure what I'm doing there.

Any help would be appreciated. Thank you.

### Which project is your question related to?
- Server

**Comment by bhopkinson** [comment]
I have been able to get this working using code from here: https://github.com/JanEggers/MQTTnet/commit/e4ec0ab65b9aa457a9a03d3052199d144f210c3f#diff-e7e572bfaeb001e30649a5cc21fa72b8

Adding just endpoints.MapConnectionHandler to StartUp has worked, however adding app.UseMqttServer caused the rest of the ASP.NET Core 3 app to stop working for some reason. I believe what I have at the moment is OK though so I will close this question.

**Comment by SeppPenner** [comment]
How did I not see this... This needs to be documented :)
