### ISSUE TITLE
Best way to deploy a broker

### ISSUE THREAD

**Issue by avengerstark** [chkr1011/MQTTnet#804]
### Describe your question
Hi there!
My way: I just run console kestrel server. I think it isn't stable.
I want to know how you deploy a broker.

### Which project is your question related to?
- MQTTnet.Server standalone
- Server

**Comment by SeppPenner** [comment]
>  I think it isn't stable.

Why do you believe it isn't stable?

Well, I run the MQTT server in NetCore (Not Asp.NetCore yet) using [Topshelf](http://topshelf-project.com/). However, this can only be used to run the project on a Windows server (as service).

**Comment by avengerstark** [comment]
> Why do you believe it isn't stable?
For example, if the server is restarted, then broker won't start automatically.

Thanks for advice!
