### ISSUE TITLE
The "ResponseTopic" property of MqttApplicationMessage is not transferred

### ISSUE THREAD

**Issue by Tum4ik** [chkr1011/MQTTnet#808]
### Description
When I publish MqttApplicationMessage with ResponseTopic set, the client gets null in the ResponseTopic property instead of published value.

### Which project is your bug related to?
- Client
- Server

### To Reproduce
1. Using this version of MQTTnet "MQTTnet.NETStandard/3.0.8".
2. The Server publishes message via this code:
```csharp
var message = new MqttApplicationMessageBuilder()
    .WithTopic("my/topic")
    .WithPayload(payload ?? string.Empty)
    .WithExactlyOnceQoS()
    .WithResponseTopic("my/response/topic")
    .Build();
await _mqttServer.PublishAsync(message);
```
3. The Client receive the message via this code:
```csharp
_mqttClient.UseApplicationMessageReceivedHandler(ApplicationMessageReceivedHandler);

//

private async Task ApplicationMessageReceivedHandler(MqttApplicationMessageReceivedEventArgs arg)
{
    var payload = Encoding.UTF8.GetString(arg.ApplicationMessage.Payload);
    if (_messageHandler != null)
    {
        await _messageHandler.Invoke(payload, arg.ApplicationMessage.ResponseTopic);
    }
}
```
4. `arg.ApplicationMessage.ResponseTopic == null` here.

### Expected behavior
`arg.ApplicationMessage.ResponseTopic == "my/response/topic"`

**Comment by stoff99** [comment]
Same problem here!

**Comment by casas333** [comment]
We experience the same issue

**Comment by chkr1011** [comment]
I found this unit test "Publish_And_Receive_New_Properties" so I assume it should work. Is the client using MQTT500 as protocol version? Is there maybe something else I am not aware of!?

**Comment by Tum4ik** [comment]
@chkr1011 
I don't  do something special for the MQTT version, so I use `3.1.1` version (the default one).
Here are the Server options:
```csharp
private IMqttServerOptions GetOptions()
{
    var options = new MqttServerOptionsBuilder()
        .WithDefaultEndpointBoundIPAddress(IPAddress.Broadcast)
        .WithDefaultEndpointPort(AppConfig.DefaultMqttPort)
        .WithMaxPendingMessagesPerClient(0)
        .WithConnectionValidator(ConnectionValidator)
        .Build();
    return options;
}

public async Task StartAsync()
{
    await _mqttServer.StartAsync(GetOptions());
}
```

And here are the Client options:
```csharp
_mqttClientOptions = new MqttClientOptionsBuilder()
    .WithClientId(clientId)
    .WithTcpServer(serverIp, AppConfig.DefaultMqttPort)
    .WithCredentials(username, (string)null)
    .WithCleanSession(false)
    .WithKeepAlivePeriod(TimeSpan.FromHours(1))
    .Build();

await _mqttClient.ConnectAsync(_mqttClientOptions);
```

**Comment by Tum4ik** [comment]
Ah! So "response topic" is only available in the MQTT v5, right?

**Comment by SeppPenner** [comment]
> Ah! So "response topic" is only available in the MQTT v5, right?

Yep.

**Comment by Tum4ik** [comment]
Thanks!
