### ISSUE TITLE
ApplicationMessageReceived handler triggering with duplicate messages

### ISSUE THREAD

**Issue by BmsVisionJo** [chkr1011/MQTTnet#815]
### Describe the bug
If you subscribe to a topic with Qos of AtMostOnce and then subscribe to another topic.
The callback for the first topic is triggered twice.
This multiplies with the number of subscribes done.
It just adds it to the already existing subscribes and sends it once more to the broker.

### Which project is your bug related to?
- ManagedClient (V3.0.8)

### To Reproduce
1. Subscribe to topic A
2. The message for topic A is received
3. Subscribe to topic B
4. The message for topic B is received and the message for topic A is received a second time

### Expected behavior
Do not trigger the received handler again if there if there is a subscribe to a different topic.
It seems like there is a new message received for that first topic but they are the same.
(Tested with retained messages)

### Additional context / logging
First subscribe to BMS/MyMES/Events & BMS/MyMES/Events/+ :
 [MqttClient.MqttChannelAdapter] [Verbose]: TX (44 bytes) >>> Subscribe: [PacketIdentifier=1] [TopicFilters=BMS/MyMES/Events@AtMostOnce,BMS/MyMES/Events/+@AtMostOnce]

Second subscribe to BMS/MyMES/Get/Groups/MachineType :
[6] [MqttClient.MqttChannelAdapter] [Verbose]: TX (79 bytes) >>> Subscribe: [PacketIdentifier=2] [TopicFilters=BMS/MyMES/Events@AtMostOnce,BMS/MyMES/Events/+@AtMostOnce,BMS/MyMES/Get/Groups/MachineType@AtMostOnce]

**Comment by BmsVisionJo** [comment]
I see that there has been some work done and that this might be a duplicate report but we are in desperate need of this fix. Any eta on a release date?

**Comment by cosmanovich** [comment]
This issue is a duplate of #569 
Pull request #776 fixes this issue.
When will this be released?

**Comment by SeppPenner** [comment]
@cosmanovich True, I will close this one.

**Comment by SeppPenner** [comment]
@BmsVisionJo You could use the develop branch and build the project on your own for the moment if it's urgent.
