### ISSUE TITLE
Security bug in WithSubscriptionInterceptor?

### ISSUE THREAD

**Issue by eantunes1980** [chkr1011/MQTTnet#816]
### Describe the bug
I think that it is a bug..
When I prevent to Subscribe a Topic in .WithSubscriptionInterceptor in MqttServerOptionsBuilder and a client wants to subscribe the topic. It works, but if the client subscribes with a #, the Client will receive the "blocked" topic as well.

### Which project is your bug related to?
- MQTTnet.Server standalone

**Comment by SeppPenner** [comment]
This heavily depends on your implementation... If you just check for e.g. `example/1`, `example/#` will be ignored by your check.

I don't think that this is a security critical bug. It's even intended.

If you want to block topics with `#` as well, you can check my project under https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfigHashedPasswords (Especially https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfigHashedPasswords/blob/master/NetCoreMQTTExampleJsonConfigHashedPasswords/TopicChecker.cs and the tests under https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfigHashedPasswords/tree/master/TopicCheckerTest). I didn't find a scenario yet where the mechanism didn't match correctly.

**Comment by SeppPenner** [comment]
@chkr1011 What's your opinion on this?

**Comment by chkr1011** [comment]
I also think that this is by design. If you need to block that as well you must block "#" at all or you use the "TopicFilterComparer" from the lib and check the given topic with all possible "dangerous" ones before accepting the subscription.
