### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by eng-ali** [chkr1011/MQTTnet#817]
### API Key username or password
What is the default api key or username and password to make api work and check its get and post requests ? because it shows me unauthorized

- Server

**Comment by chkr1011** [comment]
Do you mean the standalone version of MQTTnet? If so please check the default python scripts and app.config. There you can see which values are used.

**Comment by SeppPenner** [comment]
This can be set in the file `authorization_handler.py` in the folder `MQTTnet.Server\bin\Release\netcoreapp2.2\Web` if checked out from Git or in the binaries folder under `\Web`. Or if you want to adjust the code on C# side on your own: `AuthenticationHandler` class in the `BasicAuthenticationHandler.cs` file under `MQTTnet.Server.Web`.

![Testqw](https://user-images.githubusercontent.com/9639361/76866017-d1da0a00-6863-11ea-8c9f-694f5a7321e9.png)
