### ISSUE TITLE
TopicGenerationStrategy should check MethodName for invalid characters, not MqttRpcClient

### ISSUE THREAD

**Issue by bitmasked** [chkr1011/MQTTnet#818]
Since the strategy can be changed in which these could be valid in the MethodName

**Comment by SeppPenner** [comment]
Can you explain this a bit more, please?

**Comment by bitmasked** [comment]
The MqttRpcClient class throws ArgumentException if methodName contains '/' in ExecuteAsync.   I don't think this enforcement is necessary by the MqttRpcClient, since the topic used can be specified by utilizing a custom TopicGenerationStrategy class.  The TopicGenerationStrategy should provide any specific argument checking based on its implementation..

**Comment by chkr1011** [comment]
Sorry for the long delay. This will be added in 3.0.14...
