### ISSUE TITLE
Server Disconnect Event

### ISSUE THREAD

**Issue by MattComb** [chkr1011/MQTTnet#820]
Is there a way I can hook into the Disconnect event on the server. I need a connection id so that I can maintain references to an MQTT channel token.

Unfortunately the event handlers don't appear to be firing with my configuration.

**Comment by MattComb** [comment]
I am doing this:

            var mqtt = services.BuildServiceProvider().GetService<IMqttServer>();

            mqtt.ClientConnected += ClientConnected;
            mqtt.ClientDisconnected += ClientDisconnected;
            mqtt.ClientSubscribedTopic += SubscribedTopic;
            mqtt.ClientUnsubscribedTopic += UnsubscribedTopic;

But these events are not firing...

I'm sure I'm doing something very basic wrong...

**Comment by MattComb** [comment]
I have upgraded to latest version and eventhandlers also are not working, here is my full code:

```
           var mqttServerOptions = new MqttServerOptionsBuilder()

                .WithConnectionValidator(c =>
                    {
                        /* some stuff here... */
                            c.ReturnCode = MqttConnectReturnCode.ConnectionAccepted;
                    }
                )
                .WithSubscriptionInterceptor(context =>
                    {
                 }
                )
                .WithApplicationMessageInterceptor(context =>
                    {
                        
                    }
                )
                .WithEncryptedEndpoint()
                .WithEncryptedEndpointPort(8883)
                .WithEncryptionCertificate(x509.Export(X509ContentType.Cert))
                .Build();

            var certificate = new X509Certificate(certPath, certPass);
            mqttServerOptions.TlsEndpointOptions.Certificate = certificate.Export(X509ContentType.SerializedCert);

            services.AddHostedMqttServer(mqttServerOptions);

            //supposed to add tcp support but actually next line does ?!?
            services.AddMqttConnectionHandler();

            //does this add tcp
            services.AddMqttTcpServerAdapter();

            services.AddMqttWebSocketServerAdapter();

            var mqtt = services.BuildServiceProvider().GetService<IMqttServer>();
            mqtt.ClientConnectedHandler = new MqttServerClientConnectedHandlerDelegate(e =>
            {
                /* this line does not get hit */
                TraceManager.Instance.Info("log", "text");
            });
```

**Comment by SeppPenner** [comment]
I haven't tried the connected handler, but with unsubscribe or disconnect, I have a working version like below:

```csharp

this.mqttServer.ClientUnsubscribedTopicHandler = new MqttServerClientUnsubscribedTopicHandlerDelegate(LogMessage);

private static void LogMessage(MqttServerClientUnsubscribedTopicEventArgs eventArgs)
{
    Log.Information($"Unsubscription: ClientId = {eventArgs.ClientId}, TopicFilter = {eventArgs.TopicFilter}");
}
```

This should be the same as your approach...

**Comment by MattComb** [comment]
Hi, 

I also can get that to work when self creating the mqtt server, just not when adding via the services collection. Not sure why that would make a difference.

**Comment by SeppPenner** [comment]
> I also can get that to work when self creating the mqtt server, just not when adding via the services collection. Not sure why that would make a difference.

Ah, I see. I haven't tried that yet to be honest...

**Comment by MattComb** [comment]
Just bumping this one to see if anyone had any new thoughts
