### ISSUE TITLE
Certificate .pem problem

### ISSUE THREAD

**Issue by skakavyponik** [chkr1011/MQTTnet#823]
Hi I've got problem with .pem certificate a tried everything in issuses but nothing helps 

`
var options = new MqttClientOptionsBuilder()
                .WithClientId("user")
                .WithTcpServer("local", 8883)
                .WithCredentials("user", "123")
                .WithTls()
                .Build();`

Lets say that path to certificate is e:\mqtt\cacert.pem
how it should be written in the code 
Thanks a lot

**Comment by SeppPenner** [comment]
I would say this is the same issue as https://github.com/chkr1011/MQTTnet/issues/757.

**Comment by skakavyponik** [comment]
Thanks this was solution for me 
`.WithTls(o =>
                {
                    o.UseTls = true;
                    o.Certificates = new List<byte[]>
                        {
                             new X509Certificate(@"C:/certs/cacert.pem", "").Export(X509ContentType.Cert),
                        };
                    o.CertificateValidationCallback = (x509Certificate, chain, sslPolicyErrors, mqttClientTcpOptions) => true;
                })`
