### ISSUE TITLE
Read messaging one by one

### ISSUE THREAD

**Issue by bilalmalik777** [chkr1011/MQTTnet#824]
### Issue
Currently, we are using Microsoft IoT hub for telemetries, for processing the messaging we are using Microsoft.Azure.EventHubs. it is doing quite well. After reading and processing each message, this library updates the IoT hub regarding the status of the message.
Now I am looking for the same functionality in the mosquito. Is it possible to tell the mosquito that the following message has been processed to remove this one from the queue and send the next one? Actually mosquito is sending all the traffic in one go that is doing the problem in the DB connection pool. For example, if there are 50 machines that are sending data after each minute separately, I mean each machine sending data separately after one minute. it means 50 messages are generated in each minute and published against the specific topic. I just want to read one by one each message.
I hope you get my point

**Comment by JanEggers** [comment]
to my understanding MQTT does not have a sequence token or similar so you can not resume consuming / get the next.

I would advice to pump all msgs from mqtt through kafka as kafka has sequence tokens and so on.

**Comment by chkr1011** [comment]
I close this because I assume that the question is properly answered.
