### ISSUE TITLE
Client xxxx has exceeded timeout, disconnecting

### ISSUE THREAD

**Issue by snice1981** [chkr1011/MQTTnet#825]
I'm using ManagedClient with Mosquitto, it works well but after a certain time, the client get disconnected due to missing ping request. I have different apps (Xamarin Forms app) that connects to mosquitto. One seems to work well (Screenxxx) but not the other one (CashDesk)

As you can see in the following log, there is no pingreq from cashdesk

Here is a sample of mosquitto log file:

Mon Dec 16 08:08:43 2019: New connection from 192.168.1.60 on port 1883.
Mon Dec 16 08:08:43 2019: New client connected from 192.168.1.60 as CashDesk1166313646 (p2, c1, k15).
Mon Dec 16 08:08:43 2019: No will message specified.
Mon Dec 16 08:08:43 2019: Sending CONNACK to CashDesk1166313646 (0, 0)
Mon Dec 16 08:08:51 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:08:51 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:09:02 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:09:02 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:09:05 2019: **Client CashDesk1166313646 has exceeded timeout, disconnecting.**
Mon Dec 16 08:09:13 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:09:13 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:09:25 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:09:25 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:09:34 2019: New connection from 192.168.1.60 on port 1883.
Mon Dec 16 08:09:34 2019: New client connected from 192.168.1.60 as CashDesk1166313646 (p2, c1, k15).
Mon Dec 16 08:09:34 2019: No will message specified.
Mon Dec 16 08:09:34 2019: Sending CONNACK to CashDesk1166313646 (0, 0)
Mon Dec 16 08:09:36 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:09:36 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:09:47 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:09:47 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:09:57 2019: **Client CashDesk1166313646 has exceeded timeout, disconnecting.**
Mon Dec 16 08:09:59 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:09:59 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:10:10 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:10:10 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:10:21 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:10:21 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:10:33 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:10:33 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:10:44 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:10:44 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:10:55 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:10:55 2019: Sending PINGRESP to Screen336176334
Mon Dec 16 08:10:58 2019: New connection from 192.168.1.60 on port 1883.
Mon Dec 16 08:10:58 2019: New client connected from 192.168.1.60 as CashDesk1166313646 (p2, c1, k15).
Mon Dec 16 08:10:58 2019: No will message specified.
Mon Dec 16 08:10:58 2019: Sending CONNACK to CashDesk1166313646 (0, 0)
Mon Dec 16 08:11:06 2019: Received PINGREQ from Screen336176334
Mon Dec 16 08:11:06 2019: Sending PINGRESP to Screen336176334

It disconnect at least 100 times a day. And it's only when the app is not used (no publish to mosquitto)

**Comment by SeppPenner** [comment]
The managed client doesn't have the `WithKeepAlivePeriod(TimeSpan value)` method like the **normal client**, I guess?

About hundred times a day means every 15 minutes or so? Personally, I would just reconnect the client if it's inactive for a longer time...

**Comment by snice1981** [comment]
Hi @SeppPenner 

It deconnect more often when the app is not used (between 20h and 8h AM). As you can see in the sample log, it deconnected 52 seconds after reconnection.

I think there is a keepalive as per what I see in the log file: New client connected from 192.168.1.60 as CashDesk1166313646 (p2, c1, **k15**) K15, means Keep alive 15s if'm not wrong.

**Comment by SeppPenner** [comment]
> It deconnect more often when the app is not used (between 20h and 8h AM). As you can see in the sample log, it deconnected 52 seconds after reconnection.

Sure, I understand that, but do you really think this is an issue?

> I think there is a keepalive as per what I see in the log file: New client connected from 192.168.1.60 as CashDesk1166313646 (p2, c1, k15) K15, means Keep alive 15s if'm not wrong.

I guess, you're right. I don't know if it's possible to set this interval to a higher number @chkr1011?

**Comment by chriswue** [comment]
We just ran into the same issue and we're not using the `ManagedClient` just the plain `MqttClient` which should take care of it (the `ManagedClient` ctor requires an instance of `IMqttClient` anyway).
Seems like a bug in `MqttClient` but having a brief look at the code it seems like it should work.

`MqttClient` has options to set the `KeepAlivePeriod` which is 15sec by default and if `KeepAliveSendInterval` it is not specified it defaults to 75% of that.

**Comment by chriswue** [comment]
Actually I think I found the bug. The main keepalive loop is:


    while (!cancellationToken.IsCancellationRequested)
    {
        // Values described here: [MQTT-3.1.2-24].
        var keepAliveSendInterval = TimeSpan.FromSeconds(Options.KeepAlivePeriod.TotalSeconds * 0.75);
        if (Options.KeepAliveSendInterval.HasValue)
        {
            keepAliveSendInterval = Options.KeepAliveSendInterval.Value;
        }

        var waitTimeSend = keepAliveSendInterval - _sendTracker.Elapsed;
        var waitTimeReceive = keepAliveSendInterval - _receiveTracker.Elapsed;
        if (waitTimeSend <= TimeSpan.Zero || waitTimeReceive <= TimeSpan.Zero)
        {
            await SendAndReceiveAsync<MqttPingRespPacket>(new MqttPingReqPacket(), cancellationToken).ConfigureAwait(false);
        }

        await Task.Delay(keepAliveSendInterval, cancellationToken).ConfigureAwait(false);
    }

Let's say period is 15sec and send interval is 11.25sec (default values).
If the task happens to check 10sec since the last send/receive then it will see that `waitTimeSend`/`waitTimeReceive` is greater than `TimeSpan.Zero` and it will not send out a ping and sleep for an entire interval which is another 11.25sec.
This means if no other send/receive activity happens within 5sec then the keepalive window on the server will expire and the client gets disconnected.

The fix would be to sleep `Math.Min(waitTimeSend, waitTimeReceive)` in the case where no ping has been sent - probably a little bit less than that to account for task scheduling overheads.

**Comment by bretternst** [comment]
We are seeing the same issue, frequent missed pings and disconnects on a simple client that only subscribes. Can confirm that the patch above from chriswue fixes the problem.

**Comment by snice1981** [comment]
Hi

any news about that problem? Not yet fixed in the latest version (even RC).

**Comment by bogus105** [comment]
Hi guys,
any news regarding reconnections? It drives me crazy. My esp8266 disconnected more than 1200 times over one day. Tried to set keep alive from 10 to 60 seconds. ClientId is unique. Esps are publishing quite frequently: some of them 1 sec, 3 sec, 10sec. I even changed my router to 801.g instead of 801b/g/n (i found somwhere it helped, not here). Esp has thier MAC addresses whitelisted in the router, connecting with wifi with no problems. I'm tired... Fighting this for two weeks already.

**Comment by chkr1011** [comment]
@bogus105 I also use several ESP8266 and also ESP32 and I cannot reproduce this issues. Please try a keep alive of 0 which will disable that feature.

@bogus105 @snice1981 Please try with 3.0.15-rc1. @bretternst has already confirmed that the problem is fixed.

**Comment by bogus105** [comment]
Thank you for suggestion. What is "3.0.15-rc1"? I'm not so fluent in this area:) 
Somewhere else i've read disabling IPv6 in router will help? I've seen on my logs my mosquitto is using IPv6 and IPv4. Tomorrow i'l check if and how to disable it in my router (is is a router option or some kind of system setting - i'm using RB Pi4 + docker for my IOTstack).

**Comment by chkr1011** [comment]
@bogus105 It meas you should download the nuget version 3.0.15-rc1 and try with that version. You have to check "Include Prerelease" in VS.

**Comment by SeppPenner** [comment]
@bogus You need to check "Include pre-releases"  in the nuget package manager window in Visual Studio.

**Comment by SeppPenner** [comment]
> @bogus105 It meas you should download the nuget version 3.0.15-rc1 and try with that version. You have to check "Include Prerelease" in VS.

Yeah. I didn't read that :D

**Comment by bogus105** [comment]
nuget? i'm not using Visual Studio. I'm using Arduino IDE for my ESPs.

**Comment by chkr1011** [comment]
@bogus105 But you are using MQTTnet as the MQTT broker right? Or are you using the standalone version of MQTTnet.Server?

**Comment by bogus105** [comment]
heh, my setup on RB Pi: docker, mosquitto mqtt, node-red... on esp8266 side PubSubClient library is used.
Yes, different broker but looks like very similar problem - unstable connection with mqtt. Maybe clients side problem?

**Comment by SeppPenner** [comment]
@bogus105 I don't want to be unfriendly, but if your issue is neither related to the MQTTnet broker nor to the MQTTnet client, why do you ask your issue here? The MQTT protocol is a standard, but still implementations might differ.

It would be better to post this issue on Stackoverflow, on the mosquitto MQTT forum or the PubSubClient support (Probably on Github)...

**Comment by bogus105** [comment]
Relax, there's no room for insults here:) I just see some similarities between two libraries - somehow we can see connection issues using MQTTnet and PubSubNet - i raised question is it the library, is it esp8266 or is it RB Pi4 installed MQTT or maybe the router? Maybe there is some common problem?

**Comment by SeppPenner** [comment]
One idea might be two conflicting client ids. Can you ensure that all your MQTT client ids are unique? Otherwise two clients might kick each other from time to time. That's my only idea for now...

**Comment by bogus105** [comment]
Thank you for suggestion. I've checked that already. What's more, i'm using only one device connected to the broker now.
