### ISSUE TITLE
When I use other tools to test server authentication, I get an error

### ISSUE THREAD

**Issue by qcjxberin** [chkr1011/MQTTnet#830]
![image](https://user-images.githubusercontent.com/5792218/71177147-440f7280-22a6-11ea-9342-eff44bde2a42.png)
I want to use the username and password in the above screenshot to verify, but I ca n’t get it when testing with tools developed in other languages. Only clients developed with mqttnet can get it normally. How can I handle this situation?

**Comment by SeppPenner** [comment]
> I want to use the username and password in the above screenshot to verify, but I ca n’t get it when testing with tools developed in other languages.

Ok, I honestly don't understand this. Do you want to connect to the MQTT server with another programming language? Do you want to verify the credentials in another language? Can you explain the use case a bit more, please?

**Comment by qcjxberin** [comment]
I use the mqtt test tool downloaded from the Internet. I can connect normally without verifying the user name and password. If I verify, I cannot connect, and an error is reported, and the user name and password obtained when printing the log are empty.

**Comment by SeppPenner** [comment]
Well, which test tool? There are multiple: https://www.hivemq.com/blog/seven-best-mqtt-client-tools/.

What I can say is, that I have a MQTT server running and MQTT.fx can connect with the credential check running without problems.

For example, you can have a look at my programm under https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig/blob/master/NetCoreMQTTExampleJsonConfig/Program.cs. This code works properly for me.

> If I verify, I cannot connect, and an error is reported

Do you know which error occurs? Maybe an issue with SSL settings? Are you using MQTT 3.1.1 (Default) or 5.0? Just some ideas what might be wrong :)

**Comment by qcjxberin** [comment]
I downloaded the tool you used to test and see. The tool I used is the default 3.1.0. The specific error is unclear, but it is said to be blocked.

**Comment by qcjxberin** [comment]
Thank you, my problem has been solved.

**Comment by SeppPenner** [comment]
> Thank you, my problem has been solved.

What was the issue exactly? :)

**Comment by qcjxberin** [comment]
可能是我找的测试工具的问题，另外有个问题请教下，怎么样接收离线之后的信息的。我目前试过连接之后只能接收新的消息

**Comment by SeppPenner** [comment]
Haha, sorry? :D Google Translate helped me :)

> It may be a problem with the test tool I am looking for. Another question is how to receive information after offline. I currently only receive new messages after trying to connect

**Comment by qcjxberin** [comment]
It may be a problem with the test tool I am looking for. Another question is how to receive the information after offline. I currently only receive new messages after trying to connect

**Comment by qcjxberin** [comment]
Sorry, I also use the google translation, but just make mistakes while translating.
