### ISSUE TITLE
What is the use of Server.Subscribe?

### ISSUE THREAD

**Issue by ManniAT** [chkr1011/MQTTnet#831]
I use MQTTNEt.AspNetCore in a server side blazor project.

I found that I can call "Server.SubscribeAsync" which requires a valid (connected) ClientID and some kind of topic filters.
The documentation tells: Subscribes the server to topics.
But I found no more information on this method.

I understand the use of subscribe with the client - but what is the use at the server?

I get all messages in ApplicationMessageReceivedHandler - no matter if I subscribe or not.
Looking for a kind of "...SubscribedMessageReceivedHandler" would make sense in this case - but I found nothing like this.
Also why does it need a client id? I simply guess that I can only subscribe to messages from specific clients - but how to use it?

**Comment by SeppPenner** [comment]
@chkr1011 @JanEggers This is a question for you two.

**Comment by JanEggers** [comment]
if I understand the api correctly its is used to force msgs to a client with a specifc id that did not subscribe on its own. what do you want to do maybe I can point you in the right direction.

**Comment by ManniAT** [comment]
I just try to understand the API and while most things seem logical this just confused me.

**Comment by chkr1011** [comment]
@ManniAT As @JanEggers already mentioned the idea is that the server can subscribe behalf of the client. This feature was requested some time ago. It is not MQTT spec compliant but also has no downside. If you don't need it just ignore it. The preferred solution is to avoid this API to be compliant to the MQTT spec.
