### ISSUE TITLE
How to get offline information

### ISSUE THREAD

**Issue by qcjxberin** [chkr1011/MQTTnet#832]
How to get offline information, I tested and found that Qos1 is also offline after reconnecting for a period of time, but no offline data is obtained.

**Comment by SeppPenner** [comment]
What do you mean by "no offline data is obtained"?

**Comment by SeppPenner** [comment]
I still don't understand what is the point here. I will close this issue now. If you can specify the question a bit more, I will try to answer your question and open this issue again. Maybe also https://github.com/chkr1011/MQTTnet/issues/846 goes in this direction?
