### ISSUE TITLE
Client  Topic List？

### ISSUE THREAD

**Issue by znyet** [chkr1011/MQTTnet#842]
MQTTnet Server, When Client Disconnected
```chsarp
Server.UseClientDisconnectedHandler(a =>
{
       //how to get the client Subscribe Topic List
});
```

**Comment by SeppPenner** [comment]
What you could do is (I don't know yet if this is possible in another way):

1. Use https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-subscriptions to save the client's subscriptions to a dictionary.
2. When disconnecting, read the subscription data from the dictionary again.

**Comment by znyet** [comment]
Thank you very much！
I will use akka.net and mqttnet write an cluster mqtt system.
so need to know when client disconnecting ,then i can get client topic,
and then tell other server borker unscription  topic.

**Comment by SeppPenner** [comment]
You could take https://github.com/SeppPenner/NetCoreMQTTExampleCluster as an example. There I have built a cluster system using [Microsoft Orleans](https://dotnet.github.io/orleans/). In the project, I do pretty much the same as you want to do, check https://github.com/SeppPenner/NetCoreMQTTExampleCluster/blob/master/src/NetCoreMQTTExampleCluster.Grains/MqttClientGrain.cs and https://github.com/SeppPenner/NetCoreMQTTExampleCluster/blob/master/src/NetCoreMQTTExampleCluster.Grains/MqttRepositoryGrain.cs classes.

**Comment by znyet** [comment]
Thank you very much!
