### ISSUE TITLE
Client - ability to pass UserProperties on connection level in MQTT 5

### ISSUE THREAD

**Issue by ZbynekZ** [chkr1011/MQTTnet#843]
Feature request:

For my application, I need to pass UserProperties in the CONNECT request. There appears to be some support for it in MQTTnet on the protocol level, but I do not see any way to pass in List<MqttUserProperty> in IMQttClientOptions.

Many thanks

**Comment by chkr1011** [comment]
Yes that makes sense. I will add this as soon as possible.

**Comment by kcluusb** [comment]
I would like to second this request. We need MQTT 5.0 User Property on PUBLISH support as well.This was a major new feature of MQTT that we are planning to use heavily.

**Comment by ZbynekZ** [comment]
Re @kcluusb: This issue is specifically about UserProperties in CONNECT.

You have mentioned USER Property on PUBLISH: That is already supported. It had its own problem (#843) which is now supposedly fixed (I haven't gotten to test it yet).

**Comment by chkr1011** [comment]
@kcluusb I added this feature in master branch. Please let me know if this works for you. If it does it will be part of release 3.0.10.

**Comment by SeppPenner** [comment]
I assume that this is fixed now. If not, please tell us and I will re-open this issue :)
