### ISSUE TITLE
Missing v3.0.8 tag

### ISSUE THREAD

**Issue by paolofulgoni** [chkr1011/MQTTnet#844]
Version 3.0.8 was released a few months ago and  [available on NuGet](https://www.nuget.org/packages/MQTTnet/3.0.8) but there is no `v3.0.8` tag in the repository

**Comment by paolofulgoni** [comment]
Sorry, I misused the `bug` template and now I can't remove the `bug` label 😬

**Comment by chkr1011** [comment]
Hi, I created a new release here. The problem is that I don't want to install .net core SDKs for 2.1 or 2.2 in order to build the binaries. I will skip this for the current release and continue with these for 3.0.9.
