### ISSUE TITLE
Inability to get reason code when the connection failed by server

### ISSUE THREAD

**Issue by ZbynekZ** [chkr1011/MQTTnet#847]
### Describe the bug
The reason code is not available in "disconnected handler"

### Which project is your bug related to?
- ManagedClient

### To Reproduce
1. Call UseDisconnectedHandler on IManagedMqttClient and give it your handler
2. In the handler, display the arguments it gets
3. Try some failed connection. In my case, I am trying to connect with protocol version = 5 to an MQTT server that does not support it, and I can see that in Wireshark it responds with "Connect Ack" where Reason Code is 132 (Unsupported Protocol Version). But the behavior is probably with error "reason codes" that idnicate a failure.
4. The "disconnected" handler will be called, but the exception only refers to socket disconnection problem, and the MqttClientDisconnectedEventArgs.AuthenticateResult is null.
"connected handler" isn't call either.
No usable information about the reason code goes to the logger.

I guess that what happens is that MqttNet "kind of" thinks it was a successful connection, and the socket is then closed by the server which triggers the exception that gets reported. But the fact that it is closed by the server should be expected at this point - in fact, the client should close it itself.

### Expected behavior
I would like to be able to retrieve the reason code in the "disconnected handler", so that e.g. the user (or the code) can act accordingly to the specific reason. Or at least it should go to the logger. Or anywhere, where it can be retrieved.

**Comment by SeppPenner** [comment]
That might be due to the fact that MQTTv5 is not yet fully supported. Just for reference, here are the reason codes that should be returned: http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs01/mqtt-v5.0-cs01.html#_Toc502667250

**Comment by ZbynekZ** [comment]
@SeppPenner yes, but to make it clear, the issue is not about the fact that some connection fails. That is fine. The issue is about the inability of the library to provide the reason code to the caller.

**Comment by SeppPenner** [comment]
@ZbynekZ That's what I assumed already 👍

**Comment by SeppPenner** [comment]
For now, I have added the missing reason codes to the enum. I have no idea what else is needed to get this working. The main developers will take a look at this and answer my question.

**Comment by ZbynekZ** [comment]
Thank you @SeppPenner, any progress towards the goal is welcome.

**Comment by chkr1011** [comment]
@SeppPenner I assume your fix will only work when the disconnect packet is sent from the client to the server (I will merge it because this is also a missing feature). But the reason for a disconnect must be added to the "MqttClientDisconnectedEventArgs" which is not yet done.

**Comment by SeppPenner** [comment]
I will do that as well.

**Comment by SeppPenner** [comment]
Check my pull request again, please. I hope, what I did was in the correct classes :)
