### ISSUE TITLE
In MQTTnet.Server, filling in UserProperties for publish improperly causes exception when MQTT V3 is used

### ISSUE THREAD

**Issue by ZbynekZ** [chkr1011/MQTTnet#848]
### Describe the bug
If UserProperties are filled in when publishing a message to MQTTnet.Server, and a client subscribes using MQTT V3, an MqttProtocolViolationException is thrown with "User properties are not supported in MQTT version 3." when the message is about to be sent to the client, and the server closes the connection.

### Which project is your bug related to?
- MQTTnet.Server standalone

### Expected behavior
The UserProperties should be simply ignored when a message is to be sent to a client that has connected using MQTT V3.

Here is why:

When publishing to the server, it is not known upfront which version of the protocol the clients will use when subscribing. I want to be able to publish a message with UserProperties, and have a combination of MQTT V3 and MQTT V5 client subscribing to the server. This is currently impossible. If I fill in UserProperties, clients using MQTT V3 will not work. This forces me to have a switch in the publisher to either publish with UserProperties or not. Then, with UserProperties, only clients using MQTT V5 will be able to connect.  Or, without UserProperties, both MQTT V3 and MQTT V5 clients will be able to connect - but then, any benefit of UserProperties is lost.

Conceptually, the version of the protocol used between the client and the server should be irrelevant to the maximum extent possible, so that the broker can do its work - ship the messages between the publishers and subscribers - and adjust to different protocol versions silently if possible.

**Comment by SeppPenner** [comment]
> The UserProperties should be simply ignored when a message is to be sent to a client that has connected using MQTT V3.

This seems valid to me. I can follow your arguments there. Let's see what the main developers think about this. (https://github.com/chkr1011/MQTTnet/pull/885 is the pull request here).
