### ISSUE TITLE
Git log missing changes that exist in the release notes for v3.0.8

### ISSUE THREAD

**Issue by jltjohanlindqvist** [chkr1011/MQTTnet#850]
### Describe your question
Comparing the diff from v3.0.7 to v3.0.8 I can't really see all the changes that were mentioned in the release notes. I do see them on the develop branch though, did you create the release from the develop branch so that all the changes are included?

### Which project is your question related to?
- Generic

**Comment by SeppPenner** [comment]
@chkr1011 This might be also related: https://github.com/chkr1011/MQTTnet/issues/859 (The binaries for the server were available for 3.0.7 and prior, but not for 3.0.8).

**Comment by chkr1011** [comment]
Yes there was a mistake in that version. So I decided to remove the develop branch at all to make sure that this will not happen again. All these changes should be included. I will release 3.0.9 soon so that you can make sure that you have the latest changes.

**Comment by SeppPenner** [comment]
Ok, nice 👍 I guess we can close this because 3.0.9 will be available soon and the issue was explained.
