### ISSUE TITLE
No Namespace in documentation !

### ISSUE THREAD

**Issue by rafiulgits** [chkr1011/MQTTnet#853]
There is no namespace in each documentation, This is very ambiguous when to implement! Please provide `namespace` for every API.

**Comment by SeppPenner** [comment]
@rafiulgits Why did you close this? In my opinion, it's a valid one...

**Comment by rafiulgits** [comment]
I think in Visual Studio, its automatically find out the namespace, but the problem have to face when using an editor.

**Comment by SeppPenner** [comment]
Yes, that's true. VS does this automatically (most of the time). I will leave this open for now.

**Comment by chkr1011** [comment]
@SeppPenner  Do you want to update the docs with the namesapces? For me it is OK if we avoid them because they are added by VS automatically when needed (Alt + ,). Same applies for VS Code. And I don't think we should provide samples which are Notepad compatible 😄

**Comment by rafiulgits** [comment]
That's OK but documentation should be more rich for this project, also need samples because those are effective to understands by the users.

**Comment by SeppPenner** [comment]
> @SeppPenner Do you want to update the docs with the namesapces? For me it is OK if we avoid them because they are added by VS automatically when needed (Alt + ,). Same applies for VS Code. And I don't think we should provide samples which are Notepad compatible 😄

I guess that's ok. I wanted to introduce them first, but I believe it's too much effort in case anything changes there...
