### ISSUE TITLE
WebSocket doesn't support

### ISSUE THREAD

**Issue by rafiulgits** [chkr1011/MQTTnet#857]
I am using **.NET Core 3.1**  and  **MQTTnet 3.0.8** and **MQTTnet.AspCore 3.0.8**  for my broker service. It's works fine when a client connect with `mqtt` protocol from [MQTT.fx](https://mqttfx.jensd.de/index.php/download) or .NET client; but whenever a request come from browser using `ws` protocol its seems like this 
![](https://i.ibb.co/MCDCKKp/issue.jpg)

***
My .NET broker configuration

`startup.cs`
![](https://i.ibb.co/LpbLpQT/service.jpg)

***

`program.cs`
![](https://i.ibb.co/n1yQfTm/program.jpg)

***

### I saw this [Issue 390](https://github.com/chkr1011/MQTTnet/issues/390)  conversation but nothing found useful for me.

**Comment by JanEggers** [comment]
// this maps the websocket to an mqtt endpoint
    app.UseMqttEndpoint();

**Comment by rafiulgits** [comment]
@JanEggers  I used this, but result is same.

`.NET Server Side`
```c#
 // websocket mapping
 app.UseMqttEndpoint();
```

as by default `.NET` websocket mapping path is `/mqtt`

`JS Client Side`
```js
var client = MQTT.connect('mqtt://localhost:1883/mqtt');
```

**Comment by JanEggers** [comment]
yeah the client should be 

var client = MQTT.connect('ws://localhost:5000/mqtt');

as the webservice runns in the http pipeline not on the mqtt port

**Comment by rafiulgits** [comment]
MQTT.js automatically convert this protocol from `mqtt` to `ws`. Even I used `ws://localhost:1883/mqtt` but still no change

![](https://i.ibb.co/S30n99R/2.jpg)

**Comment by JanEggers** [comment]
**USE PORT 5000**

**Comment by rafiulgits** [comment]
It works. Thanks man

**Comment by snrtbnc** [comment]
Actually I didnt understand one thing, we put 1883 port like

---  o.ListenAnyIP(1883, l => l.UseMqtt()); // mqtt pipeline

--- and we put builder.WithDefaultEndpointPort(1883)

but we are listening default http pipeline  port 5000 why?

**Comment by shaojun** [comment]
@rafiulgits any instructions for running single instance of MQTTnet both on tcp and websocket in .NET CORE Console application?

**Comment by rafiulgits** [comment]
@shaojun follow the [Doc](https://github.com/chkr1011/MQTTnet/wiki/Server), you'll find how to use both TCP and Websocket. Remember if you use browser as a client the your browser use websocket connection. And to connect your MQTT broker by websocket you have to use HTTP port instead of MQTT default port.

**Comment by chkr1011** [comment]
@shaojun Just setup a ASP.NET Core application including kestrel and follow the steps from the Wiki regard the ASP.NET integration.

**Comment by shaojun** [comment]
@rafiulgits I'm using the ASP.NET CORE MVC 3.1, i've followed the doc but this line isn't compiled 

> `endpoints.MapMqtt("/mqtt");`

and I have turn to reference the section of **ASP.NET Core 2.1+**, this finally worked for me:
`services.AddMqttWebSocketServerAdapter();`
