### ISSUE TITLE
about mqtt.js end method throw  Invalid frame

### ISSUE THREAD

**Issue by pigwing** [chkr1011/MQTTnet#861]
### Describe the bug
hello when is use mqtt.js [https://github.com/mqttjs/MQTT.js](https://github.com/mqttjs/MQTT.js) when i client.end() the server will throw about this excption 

> stream.js:64 WebSocket connection to 'ws://xxxx/mqtt' failed: Invalid frame 

### Which project is your bug related to?

- Server
- Asp.net Core 3.1

### To Reproduce
MQTTnet version: 3.0.9-rc1

**Comment by JanEggers** [comment]
I just verified with the testapp. mqttjs works just fine

**Comment by SeppPenner** [comment]
@pigwing Can you provide some more details regarding your setup?

**Comment by pigwing** [comment]
i found the problem in mqtt.js

**Comment by SeppPenner** [comment]
@pigwing Can you maybe describe us what the error was? Just in case someone else experiences the same thing?
