### ISSUE TITLE
Have access to SessionItems using mqttBroker.GetClientStatusAsync

### ISSUE THREAD

**Issue by brunoalreis** [chkr1011/MQTTnet#867]
### Describe the feature request
I have an user interface where is possible to change users credentials (username / password). When credentials changes, i want to disconnect clients. To do that, i must have access to SessionItems, to know what is the client to disconnect.

Using _mqttBroker.GetClientStatusAsync(), for each client, i don't have access to SessionItems.

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
IMqttClientStatus should have a property called SessionItems, just like MqttSubscriptionInterceptorContext has.

### Describe alternatives you've considered
As a workaround, i am using reflection. Something like this:

```
FieldInfo field =typeof(MQTTnet.Server.Status.MqttClientStatus).GetField("_connection", BindingFlags.NonPublic | BindingFlags.Instance);

MqttClientConnection connection = field.GetValue(client) as MqttClientConnection;
```

With that I can access to connection.Session.Items.

**Comment by chkr1011** [comment]
That is a good idea! I added this feature for 3.0.9-rc2. Please test and let me know if it fits your needs.

**Comment by brunoalreis** [comment]
@chkr1011  Works perfect!
Great work. Thank you.
