### ISSUE TITLE
Intercept MQTT

### ISSUE THREAD

**Issue by pashmak73** [chkr1011/MQTTnet#871]
Hi,
Thanks for this amazing library.
I was wondering to know, how can we intercept mqtt packets? Using wireshark is hard. Can we another way or app to do it?
I know some apps in my phones is using mqtt servers like facebook, instagram, i want to intercept their packets and create a client for them.

Thanks in advance.

**Comment by SeppPenner** [comment]
As far as I know, Wireshark and related tools is the only option available...

**Comment by SeppPenner** [comment]
Maybe this can help you to analyze your traffic using Wireshark: https://iotbytes.wordpress.com/capturing-and-analysing-mqtt-packets/.
