### ISSUE TITLE
LWT: for each new publish topic and Timestamp

### ISSUE THREAD

**Issue by joepkemel** [chkr1011/MQTTnet#876]
### Describe your question
So I am trying to make a dynamic application that can publish to new topics at run time.
For each new topic I want to be able to also set a Last will message. Instead of only 1 topic when the client sets up the connection. I know you normally would use a different topic for LWT and the data topic. This is mainly so that I can set a different lastwill for each publish topic and not on the same wildcard level.
One solution I could think of is creating the last will topic with a wildcard, like (data/#). But you still can't define a different message for each topic.

Second: Is it possible to add a timestamp to a Last Will message(broker would need to set this?)?
This is mainly for data acquisition.

### Which project is your question related to?
- Client

**Comment by chkr1011** [comment]
You only have one last will message per client. So having a different per topic is not possible in my opinion. Wildcards are only supported when subscribing. You cannot use them in topics when sending.

I don't think you can add a timestamp because the last will message must be sent with the CONNECT packet. After connecting you cannot change it. But you can implement such thing with custom code in your broker. Then your clients can update the last will every couple of seconds or whatever. Then the server detects the disconnect and sends the message. But you have to build that on your own. With plain MQTT this is not possible.

**Comment by SeppPenner** [comment]
> You only have one last will message per client. So having a different per topic is not possible in my opinion. Wildcards are only supported when subscribing. You cannot use them in topics when sending.

That's all correct.

Honestly, I didn't find anything in the standard: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

Relevant section is 3.1.2.5 to 3.1.2.7.

**Comment by chkr1011** [comment]
I don't think there is anything because the fact that the will message is part of the CONNECT packet sorts all other strategies out. Or do I don't get the idea?

**Comment by SeppPenner** [comment]
> I don't think there is anything because the fact that the will message is part of the CONNECT packet sorts all other strategies out. Or do I don't get the idea?

That's how I understood it as well, yes.

**Comment by chkr1011** [comment]
So we can close this? I am lost 😄

**Comment by SeppPenner** [comment]
@joepkemel What you could do:

1. Serialize multiple topics and multiple will messages into the connect method:

```csharp
using Newtonsoft.Json;
using Mqttnet;
using System.Collections.Generic;

public static void Connect()
{
	var topics = new List<string> { "Topic1", "Topic 2" };
	var serializedTopics = JsonConvert.SerialieObject(topics);
	
	var payloads = new List<string> { "Payload 1", "Payload 2" };
	var serializedPayloads = JsonConvert.SerialieObject(payloads);
	var encodedPayloads = Encoding.UTF8.GetBytes(serializedPayloads);
	
    var factory = new MqttFactory();
    var mqttClient = factory.CreateMqttClient();
    var options = new MqttClientOptionsBuilder()
    .WithClientId("Client1")
    .WithTcpServer("broker.hivemq.com")
    .WithCredentials("bud", "%spencer%")
    .WithTls()
    .WithCleanSession()
    .WithWillMessage(new MqttApplicationMessage
	{
		Topic = serializedTopics,
		Payload = encodedPayloads
	})
    .Build();
}
```

2. Deserialize this on the server side:

```csharp
using Newtonsoft.Json;
using Mqttnet;
using Mqttnet.Server;
using System.Collections.Generic;
using System.Linq;

private MqttServer server;

public void Start()
{
	var optionsBuilder = new MqttServerOptionsBuilder()
		.WithDefaultEndpointPort(1884)
		.WithLastWillInterceptor(c =>
		{
			var topics = JsonConvert.DeserializeObject(c.Topic);
			var payloads = JsonConvert.DeserializeObject(Encoding.UTF8.GetString(c.Payload));
			
			// Todo: Do whatever with this:
			var counter = 0;
			
			foreach(var topic in topics)
			{
				var currentPayload = payloads.ElementAt(counter);
				
				var message = new MqttApplicationMessageBuilder()
					.WithTopic(topic)
					.WithPayload(currentPayload)
					.WithExactlyOnceQoS()
					.WithRetainFlag()
					.Build();

				await server.PublishAsync(message, CancellationToken.None);
				
				counter++;
			}
		});

	this.server = new MqttFactory().CreateMqttServer();
	await this.server.StartAsync(optionsBuilder.Build());
}
```

However, the interceptor `WithLastWillInterceptor` doesn't exist yet. But in general, this is a solution I would probably use (Or similar because it's not tested).

**Comment by joepkemel** [comment]
This could indeed work. But for the system I am making you want to be able to add a last will at run-time. Than what could be added it disconnect the client, then add the LWT to the 'topics' and 'payloads' and setup a new connection.

For now I made my own solution by adding an extra field to my objects that contains the topic string.
So when a LWT message is received a loop goes through the list of objects and checks if the topic is the same.
Thank you for thinking with me and finding alternatives!

This can be closed now.
