### ISSUE TITLE
MqttServer causes CPU 799%

### ISSUE THREAD

**Issue by xljiulang** [chkr1011/MQTTnet#879]
### Describe the bug
I hosted mqttserver in asp.netcore, and half a month later found that MQTT used all 8 CPU cores. Remove mqttserver and you won't have this problem. Of course, I can't catch any logs, and in fact, my mqttserver does nothing but use its built-in default behavior feature.

### Which project is your bug related to? 
- MQTTnet.Server v3.0.8

**Comment by chkr1011** [comment]
Please share some sample code so that we can try to reproduce the issue.

**Comment by xljiulang** [comment]
I'm waiting for recurrence, and then use dotnet dump and dotnet trace to collect more information. At the same time, I'm trying to find out whether it's the problem of mqttserver layer, mqttserver kestrel  tcp connection layer or mqttserver websocket layer. Wait for my good news.

**Comment by chkr1011** [comment]
OK thanks. I will close this ticket for now. Please open it again if you found some issues.
