### ISSUE TITLE
Client Certs not working in xamarin.android, but does work with .NET Core 3.1

### ISSUE THREAD

**Issue by johnjore** [chkr1011/MQTTnet#883]
### Describe the bug
Cross-posted: https://github.com/xamarin/xamarin-android/issues/4481

Connecting to mosquitto when mosquitto configured to use certificates fails when compiled as xamarin.android, but does work if compiled as a console application using .NET Core 3.1.

### Which project is your bug related to?
- Client

### To Reproduce
1. Using this version of MQTTnet 3.0.9-rc1 (same issue when using 3.0.8)

3. See error:
> Exception: MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.Security.Cryptography.CryptographicException: Caught unhandled exception in MonoBtlsSslCtx.ProcessHandshake. ---> System.NullReferenceException: Object reference not set to an instance of an object.
> at Mono.Btls.MonoBtlsSsl.SetPrivateKey (Mono.Btls.MonoBtlsKey key) [0x00006] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsSsl.cs:214
> at Mono.Btls.MonoBtlsContext.SetPrivateCertificate (Mono.Btls.X509CertificateImplBtls privateCert) [0x00011] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:166
> at Mono.Btls.MonoBtlsContext.SelectCallback (System.String[] acceptableIssuers) [0x0003a] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:122
> at Mono.Btls.MonoBtlsSslCtx.NativeSelectCallback (System.IntPtr instance, System.Int32 count, System.IntPtr sizes, System.IntPtr data) [0x00025] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsSslCtx.cs:174
> --- End of inner exception stack trace ---
> at Mono.Btls.MonoBtlsObject.CheckLastError (System.String callerName) [0x00064] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsObject.cs:120
> at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00032] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:219
> at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:715
> at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
> at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:289
> at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:223
> --- End of inner exception stack trace ---
> at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x0025c] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:310
> at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync (System.Threading.CancellationToken cancellationToken) [0x00296] in :0
> at MQTTnet.Internal.MqttTaskTimeout.WaitAsync (System.Func`2[T,TResult] action, System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) [0x000c2] in :0
> at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync (System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) [0x00117] in :0
> --- End of inner exception stack trace ---
> at MQTTnet.Adapter.MqttChannelAdapter.WrapException (System.Exception exception) [0x00067] in :0
> at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync (System

Mosquitto:
> 1585478267: OpenSSL Error[0]: error:140350E5:SSL routines:ACCEPT_SR_CERT:ssl handshake failure

### Expected behavior
Connect without errors

### Code snippet:
```csharp
const SslProtocols sslProtocolVersion = SslProtocols.Tls12;

string currentPath = Path.Combine(Android.OS.Environment.ExternalStorageDirectory.AbsolutePath, Android.OS.Environment.DirectoryDownloads);
X509Certificate rootCert = X509Certificate.CreateFromSignedFile(Path.Combine(currentPath, rootCertName));
X509Certificate2 certificate = new X509Certificate2(Path.Combine(currentPath, userCertName), CertPrivKey);
UpdateStatusNonUI("Root Cert: '" + rootCert.Subject.ToString() + "'");
UpdateStatusNonUI("User Cert: '" + certificate.Subject.ToString() + "'");
UpdateStatusNonUI(userCertName + " has Private Key: '" + certificate.HasPrivateKey.ToString() + "'");

var TLSParameters = new MqttClientOptionsBuilderTlsParameters {
  UseTls = true,
  IgnoreCertificateChainErrors = false,
  IgnoreCertificateRevocationErrors = false,
  AllowUntrustedCertificates = false,
  SslProtocol = sslProtocolVersion,
  CertificateValidationCallback = (X509Certificate x, X509Chain y, SslPolicyErrors z, IMqttClientOptions o) => {
  return true;
  },
  Certificates = new List<X509Certificate> {
    rootCert,
    certificate
  },
};
UpdateStatusNonUI("TLS Parameters Set");

var options = new MqttClientOptionsBuilder()
  .WithClientId(clientId)
  .WithTcpServer(strMQTTServer, intMQTTPort)
  .WithCredentials(strMQTTUser, strMQTTPassword)
  .WithCleanSession()
  .WithTls(TLSParameters)
  .WithProtocolVersion(mqttProtocolVersion)
  .Build();
  UpdateStatusNonUI("Options Set");

  var mqttClient = new MqttFactory().CreateMqttClient();
  var MqttClientAuthenticateResult = await mqttClient.ConnectAsync(options);
```

Problem with MQTTnet or mono?

**Comment by SeppPenner** [comment]
Since this is not supported in Xamarin yet, I guess, there's nothing we can do.

**Comment by chkr1011** [comment]
@johnjore  I agree with @SeppPenner . The exception is thrown inside the Mono implementation (while setting the private key).
If you have any updates or there is something we can do please let us know.

**Comment by KevPantelakis** [comment]
Hi, I know this bug is marked as closed, but I have randomly stumbled workaround by complete chance. 

I've come across the same error while trying out MQTTNet with Xamarin Forms.
In the process of testing solutions, I've found this workaround:

When creating the Certificates list like it's shown in the [Wiki](https://github.com/dotnet/MQTTnet/wiki/Client#tls-using-a-client-certificate) I had the error:
```
[...]
Certificates = new List<X509Certificate>()
{
    caCert,
    clientCert,
}

System.Security.Cryptography.CryptographicException: Caught unhandled exception in MonoBtlsSslCtx.ProcessHandshake. ---> System.NullReferenceException: Object reference not set to an instance of an object.
```
BUT, I have no clue why, giving the clientCert first in the list gave me a successful connection in Xamarin:
 ```
[...]
Certificates = new List<X509Certificate>()
{
    clientCert,
    caCert,
}
```

**Comment by SeppPenner** [comment]
@KevPantelakis I remember that someone else already had a similar finding with the certs in another context. I don't understand why this fixes the issue but the wiki is updated now.
