### ISSUE TITLE
Retain flag reset by the server?

### ISSUE THREAD

**Issue by mstanisavljevicns** [chkr1011/MQTTnet#892]
Hi,

I would like to know if a message is published with retained flag set inside the IMqttApplicationMessageReceivedHandler.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs arg) handler.
I think the same issue was already open (and should be fixed), but my experience with latest nuget MQTTNet package is that all the messages have retained flag not set.
The already existing issue is "Receiving retained message from server doesn't set retain flag to true #482"
Can you please clarify, what is the expected behaviour regarding resetting retained flag by the server?
Ultimately, is there a way for a client to cache all received messages, if the messages were published with retain flag set?

Thanks

**Comment by chkr1011** [comment]
Which version do you use? Latest stable or newer? In 3.0.9-rc2 is some code which sets the flag to true for all retained messages which are sent to a client.

**Comment by mstanisavljevicns** [comment]
Thanks for the reply.
I've updated to the latest (3.0.9) and I can confirm that retained messages are handled according to specification:
_"When sending a PUBLISH Packet to a Client the Server MUST set the RETAIN flag to 1 if a message is
sent as a result of a new subscription being made by a Client [MQTT-3.3.1-8]. It MUST set the RETAIN
flag to 0 when a PUBLISH Packet is sent to a Client because it matches an established subscription
regardless of how the flag was set in the message it received [MQTT-3.3.1-9]."_

I'm closing the issue.
Thanks again and keep up :)
