### ISSUE TITLE
sometimes cpu 100%

### ISSUE THREAD

**Issue by pigwing** [chkr1011/MQTTnet#896]
### Describe the bug
sometime mqttnet will let the cpu 100%, i am use dotnet-trace generated trace
[trace link](https://github.com/AirleaderChina/trace/blob/master/trace.nettrace?raw=true)

### Which project is your bug related to?

- Server

### Environment
1. mqttnet version 3.0.9
2. asp.net core 3.1
3. Linux os(ubuntu 18.04)

![trace picture] (https://raw.githubusercontent.com/AirleaderChina/trace/master/bug-photo.png)

**Comment by JanEggers** [comment]
Hi Pigwing, there must be an issue with your code. 

The callstack you provided starts with pipelines.sockets.unofficial. mqtt.net does not use this package.

**Comment by pigwing** [comment]
oh thx
