### ISSUE TITLE
Not finding MqttUserProperty set at Subscription time

### ISSUE THREAD

**Issue by sebagomez** [chkr1011/MQTTnet#902]
I'm setting a `MqttUserProperty` at Subscription time but I can't get it anywhere else. 

Here's my code
```cs
MqttClientSubscribeOptions options = new MqttClientSubscribeOptions
{
    TopicFilters = new List<MqttTopicFilter> { new MqttTopicFilter() { Topic = topic, QualityOfServiceLevel = (MQTTnet.Protocol.MqttQualityOfServiceLevel)Enum.ToObject(typeof(MQTTnet.Protocol.MqttQualityOfServiceLevel), qos) } },
    UserProperties = new List<MqttUserProperty> { new MqttUserProperty("gxrocedure", $"{{\"gxrocedure\":\"{gxproc}\"}}") }
};

MqttClientSubscribeResult result = mqtt.m_mqttClient.SubscribeAsync(options).GetAwaiter().GetResult();
```

When I disconnect and connect again using the previous session, I can't find that property (gxprocedure). 

I'm not sure if it's a bug or I'm not using it right.

### Which project is your question related to?
- Client

**Comment by chkr1011** [comment]
I quickly checked the spec but I did not find anything which indicates that the user properties should be stored anywhere. They are just custom parameters which can be read by the server to perform some custom tasks (like MQTTnet.Server does with custom Python scripts and interception).

**Comment by sebagomez** [comment]
Oh ok, I thought they could be used as metadata for every subscriber. 
Thanks for your prompt response.
