### ISSUE TITLE
IEndpointRouteBuilder' does not contain a definition for 'MapMqtt'

### ISSUE THREAD

**Issue by BiggerWu** [chkr1011/MQTTnet#903]
### Describe the bug
I configured mqttnet in. Net core, and the following error occurred when configuring startup: 'iendpointrutebuilder' does not contain a definition for 'mapmqtt' and the best extension method overload 'connectionroutebuilder extensions. Mapmqtt (connectionsroutebuilder, pathstring)' requires a receiver of type 'connectionsroutebuilder'
My. Net core version is 3.1, mqttnet version is 3.0.9

![image](https://user-images.githubusercontent.com/51442483/79856038-61904c80-83fe-11ea-9251-4b0d90efbddf.png)

### Code example

 
```csharp
  public void Configure(IApplicationBuilder app,  ILoggerFactory loggerFactory)
        {
            app.UseAbp(options => { options.UseAbpRequestLocalization = false; }); // Initializes ABP framework.

            app.UseCors(_defaultCorsPolicyName); // Enable CORS!

            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();

            app.UseAbpRequestLocalization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapMqtt("/mqtt");
            });
              
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<AbpCommonHub>("/signalr");
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute("defaultWithArea", "{area}/{controller=Home}/{action=Index}/{id?}");
            });
          
            // Enable middleware to serve generated Swagger as a JSON endpoint
            app.UseSwagger();
            // Enable middleware to serve swagger-ui assets (HTML, JS, CSS etc.)
            app.UseSwaggerUI(options =>
            {
                options.SwaggerEndpoint(_appConfiguration["App:ServerRootAddress"].EnsureEndsWith('/') + "swagger/v1/swagger.json", "demo_dzt API V1");
                options.IndexStream = () => Assembly.GetExecutingAssembly()
                    .GetManifestResourceStream("demo_dzt.Web.Host.wwwroot.swagger.ui.index.html");
            }); // URL: /swagger
        }
```
![image](https://user-images.githubusercontent.com/51442483/79855951-4291ba80-83fe-11ea-9bf8-7cca07484d5e.png)

**Comment by JanEggers** [comment]
there seems to be issue with packaging. the nuget only contains netstandard builds. no specific build for netcore31. util that is fixed you can add this repo as a submodule i will have a look at fixing it.

**Comment by djarvis** [comment]
I am seeing the same issue.

What do I do to resolve it?

**Comment by chkr1011** [comment]
Try 3.0.10-rc1.

Dan Jarvis <notifications@github.com> schrieb am Di., 5. Mai 2020, 17:27:

**Comment by fincha** [comment]
same issue with 3.0.11
