### ISSUE TITLE
. net core3.1 changing the server port has no effect

### ISSUE THREAD

**Issue by BiggerWu** [chkr1011/MQTTnet#905]
### Describe your question
I want to use mqttnet as the server to receive messages from the front end of the web program. Because I'm afraid that the port of mqttnet using HTTP will block the port, I want to set a port for mqttnet alone, but I find that when I set other ports, the front-end cannot connect to the server, and only when I set the port of HTTP (Port: 5000) can I connect. I would like to ask where I did not configure the above problems, or the web side can only use the HTTP port.
I use the API in the. .net core web program on the back end, and I use the Vue on the front end.
**server Code :**
 
![image](https://user-images.githubusercontent.com/51442483/79955328-3dda0e80-84b1-11ea-8321-0e7412ee2a4f.png)

### Which project is your question related to?

- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

**Comment by JanEggers** [comment]
> or the web side can only use the HTTP port.

yes

**Comment by mimimiaomiao1** [comment]
> ### Describe your question
> I want to use mqttnet as the server to receive messages from the front end of the web program. Because I'm afraid that the port of mqttnet using HTTP will block the port, I want to set a port for mqttnet alone, but I find that when I set other ports, the front-end cannot connect to the server, and only when I set the port of HTTP (Port: 5000) can I connect. I would like to ask where I did not configure the above problems, or the web side can only use the HTTP port. I use the API in the. .net core web program on the back end, and I use the Vue on the front end. **server Code :**
> 
> ![image](https://user-images.githubusercontent.com/51442483/79955328-3dda0e80-84b1-11ea-8321-0e7412ee2a4f.png)
> 
> ### Which project is your question related to?
> * Client
> * ManagedClient
> * MQTTnet.Server standalone
> * Server
> * Generic

请问前端是这么写的吗？ 
 const client3=mqtt.connect("ws://xxx.xxx.xxx.xxx : 端口", {
        log: console.log.bind(console),
        keepalive: 30,
        clientId: "meterAlarmRecord",
        username: "admin",
        password: "123456",
        path: "/mqtt",
    });

我给后端也设置为端口5000了，但是vue还是连不上。。求助大佬。

**Comment by SeppPenner** [comment]
@mimimiaomiao1 Try to use:

```csharp
mqttServer.WithDefaultEndpoint()
    .WithEndPointPort(20000);
```

**Comment by mimimiaomiao1** [comment]
> @mimimiaomiao1 Try to use:
> 
> ```cs
> mqttServer.WithDefaultEndpoint()
>     .WithEndPointPort(20000);
> ```

  mqttServerOptionsBuilder.WithDefaultEndpoint();
  mqttServerOptionsBuilder.WithDefaultEndpointPort(port);

Not effective

**Comment by mimimiaomiao1** [comment]
> @mimimiaomiao1 Try to use:
> 
> ```cs
> mqttServer.WithDefaultEndpoint()
>     .WithEndPointPort(20000);
> ```

   mqttServerOptionsBuilder.WithDefaultEndpoint().WithDefaultEndpointPort(port);
It's not possible either
