### ISSUE TITLE
MQTTnet and Classic ASP.Net Connection

### ISSUE THREAD

**Issue by martinx4** [chkr1011/MQTTnet#906]
Hi, i try to connect with a Classic ASP.NET Webapplication to my Mosquitto Broker (it runs in the MS Azure Cloud)

Within a normal Windows Application i can connect with my Settings but not over an ASP.NET Webapplication. 
I got always not connected. What could be wrong?
----

            Dim _options As IMqttClientOptions = New MqttClientOptionsBuilder().WithClientId("xyz-Asp.NET").WithTcpServer(IOBrokerIP, port).WithCredentials("x1", "x2").WithTls(New MqttClientOptionsBuilderTlsParameters() With {
        .SslProtocol = System.Security.Authentication.SslProtocols.Tls12,
        .AllowUntrustedCertificates = True,
        .UseTls = True,
       .Certificates = New List(Of X509Certificate) From {
            caCert, clientCert}, .CertificateValidationCallback = Function() True,
        .IgnoreCertificateChainErrors = False,
        .IgnoreCertificateRevocationErrors = False
    }).WithCleanSession().WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311).WithKeepAlivePeriod(TimeSpan.FromSeconds(60)).WithCommunicationTimeout(TimeSpan.FromSeconds(30)).Build()

            objmqttClient.ConnectAsync(_options, CancellationToken.None)

----

**Comment by JanEggers** [comment]
include some details pls

**Comment by martinx4** [comment]
Hi Jan, it seems to work now. I have had a try catch arroud the function, but it seems that was in asp.net wrong. Only added if no Connection, reconnect. that was it
