### ISSUE TITLE
Client gets connected even when Server returns MqttConnectReasonCode.NotAuthorized

### ISSUE THREAD

**Issue by nibirc** [chkr1011/MQTTnet#911]
### Describe the bug
Client gets connected to the server even when the Server returns NotAuthorised as reason code in connection validator

### Which project is your bug related to?

- Server

### To Reproduce
1. Using this version of MQTTnet '...'.
2. Run this code '....'.
3. With these arguments '....'.
4. See error.

### Expected behavior
Client should not be able to connect to the server.

### Code example
 Please provide full code examples below where possible to make it easier for the developers to check your issues.
 
```csharp
if (await IsDeviceRegistered(ClientID))
                        c.ReasonCode = MqttConnectReasonCode.Success;
                    else
                        c.ReasonCode = MqttConnectReasonCode.NotAuthorized;
```

**Comment by SeppPenner** [comment]
I don't know where's the difference, but I use `MqttConnectReasonCode.BadUserNameOrPassword` and it works...

@chkr1011 This is a question for you.

**Comment by pigwing** [comment]
ConnectionValidator can not use async

**Comment by nibirc** [comment]
OK. I will change and see

**Comment by SeppPenner** [comment]
I guess, there will be an option to use the connection validator async in the future. For now, I would consider this issue as closed as I have a lot of projects on my own where this works properly.
