### ISSUE TITLE
WithConnectionBacklog

### ISSUE THREAD

**Issue by danielstock** [chkr1011/MQTTnet#912]
### Describe your question
WithConnectionBacklog 
this function sets the max number of con-current connections?
if i use mqttnet.server as an iot server, could it support 10k devices online together?

any information would be appreciated, thanks a lot!

### Which project is your question related to?
- Server

**Comment by chkr1011** [comment]
The ConnectionBacklog refers to the connection backlog at socket level. Usually you do not have to change this. https://stackoverflow.com/questions/36594400/what-is-backlog-in-tcp-connections

The count of clients is only limited by the available resources (CPU and RAM). So you have to try and increase machine power is required etc.

**Comment by danielstock** [comment]
thanks.
