### ISSUE TITLE
[QUESTION] How to use MQTTnet with Unity3D ?

### ISSUE THREAD

**Issue by Thomas-6freedom** [chkr1011/MQTTnet#914]
### Describe your question
Hello. I use MQTTnet on a console C# app. Which is my broker. I want a MQTT client made with Unity3D to be able to discuss with that broker.

I tried to use Nuget For Unity and get the Nuget Package but there is too much depencies, and theses dependencies are conflicted with Unity internal Engine.

![image](https://user-images.githubusercontent.com/49686866/81189883-697fed00-8fb7-11ea-85e0-89ae01f5fba9.png)

What should I do to use MQTTnet in Unity3d ?

Thank you.

### Which project is your question related to?
- Client

**Comment by chkr1011** [comment]
I am no Unity expert so I can only guess...

What I read sometimes is that you need to download the nuget file, extract it and reference the lib directly (also adding some microsoft ones). Then it might work.

Apart from that I have no idea. The project is netstandard and just requires some libraries for web socket communication etc.

**Comment by GitRaboBormann** [comment]
You can just build the MQTTNet project yourself and use the Standard2.0 dll.
