### ISSUE TITLE
Cluster support for MQTT broker

### ISSUE THREAD

**Issue by Nikhil13x** [chkr1011/MQTTnet#915]
To run the mqtt broker in a distributed environment, it may require some kind of clustering.

**Comment by SeppPenner** [comment]
I have already built such a thing as an example here: https://github.com/SeppPenner/NetCoreMQTTExampleCluster. I know, it's nothing official and still has some bugs (E.g. only supports JSON payloads at the moment), but you might give it a try.

**Comment by Nikhil13x** [comment]
> I have already built such a thing as an example here: https://github.com/SeppPenner/NetCoreMQTTExampleCluster. I know, it's nothing official and still has some bugs (E.g. only supports JSON payloads at the moment), but you might give it a try.

@SeppPenner Thanks for the input.. 
Have you done any performance testing for the solution? Will the silohost not be a bottleneck? What if SiloHost fails? 
I will try to run your solution and post the results.. Thank you.

**Comment by SeppPenner** [comment]
> Have you done any performance testing for the solution?

Not yet, I'm still in the phase where I try to work with Microsoft Orleans for the first time.

> Will the silohost not be a bottleneck?

I would say no. You can run multiple silos on different machines with the Silo host. In my implementation, I would say that the database is the bottleneck (But it can be clustered as well).

> What if SiloHost fails?

Well, good question. There should be the possibility that one of the clusters in the Silo host takes over if another fails. Honestly, I'm not really an Orleans expert yet, but there should be solutions for this scenario.

**Comment by SeppPenner** [comment]
My solution should now work properly. Give it a try :)
