### ISSUE TITLE
Enum all retained topics held by the server?

### ISSUE THREAD

**Issue by KarloX2** [chkr1011/MQTTnet#92]
Hi!
I'm new to MQTT and to this lib.
I want to build a demo solution that facilitates a special script which shall be able to access all values currently known inside the MqttServer. I understand that there's a retained flag that instructs the Server to buffer those Messages and I guess there's an internal list for that somewhere.

Having the Server started and I have a IMqttServer reference. I found there's a method GetConnectedClients() that provides a list of Clients, but I found no method to Access the Tokens (without a loopback connection).

Is there a way to do that?

Thanks
Karlo

**Comment by chkr1011** [comment]
Hi,
what exactly do you mean with tokens? I assume you mean the mentioned retained messages. Those messages are stored in the server (and saved to storage if the required interface is implemented). If you subscribe to a topic which is stored at the server the client will receive that message even if client is offline. This is often used for scenarios where the sensor is most of the time offline like a battery powered temperature sensor which only gets activated every couple of minutes and posts the latest measured value. If those messages are retained a client will receive the latest one. The topic is the key and there can be only one message per topic retained. An empty payload will clear the retained message.

So if you want to access all values in the server you may need a client which subscribes to the topic "#" (which is a wildcard for everything) or make use of the application message received event at the server. This event is fired for every received message and also contains the ID of the client which has sent the message.

What is the demo about you are working on? Can you share some details?

Best regards
Christian

**Comment by KarloX2** [comment]
Hi Christan,

thanks for you comments and explanations about the concepts.
I meant so say topics (not tokens), or maybe messages is the better word.

My demo will be a .net process that has two main modules. One is wrapped around a MQTT server that collects messages from a number of sensors. As far as I can see, there will be no actors. There may or may not be other MQTT clients accessing the server/broker, but that's optional and not important for the start. The second module inside the same process will periodically execute a .csx script and the script shall have access to all the messages collected by the MQTT server, by means of callbacks into the server. Those callbacks shall deliver the queried values quickly (without a client/server roundtrip to MQTT broker).

The interval between two script runs could be something between 10 seconds and 2 minutes. The script code shall be able to access

- A list of all the new messages with changed or unchanged topics/values since the last script run
- All retaining values or last-will values with a timestamp of when received

Based on those values, the script will do calculations and take decisions, resulting in data rows being stored somewhere, but with no effect to the MQTT sphere.
 
As far as I can see, my MQTT value collector module could either utilize a loopback client, or intercept the traffic using the ApplicationMessageReceived event and maintain own lists of messages for making them available to the script on the next script execution, right?

As for the retaining values (where I also need to add the timestamp), it could work in the same way. But a nicer solution would be a separate IMqttServer event allowing me to intercept additions or removals from the MqttServer's internal storage or retaining / last will messages. Is that a good idea? If so and if you guide me the the right direction (which classes I shall look at), I could try to work on the additions for this.

Is my general understanding right up to here?

I have two other questions about how MQTT works in general:
- How do MQTT devices "learn" the IP address of the MQTT server?
- Do the MQTT devices automatically send all their values to the server, or must the server initiate some kind of subscription to tell the device which topics it shall send to the server?

Thanks for your help!
Karlo

**Comment by JanEggers** [comment]
from version 2.5 you can get the retained messages via https://github.com/chkr1011/MQTTnet/blob/develop/MQTTnet.Core/Server/IMqttClientRetainedMessageManager.cs so you dont need to store the messages on your end. 

if you need a timestamp you should add it to the payload of the message.

the payload should be utf8 encoded json but in theory you/or the devices can send whatever they want and even mix that depending on the topic. 

service discovery can either be hardcoded in the devices or if your broker is in the same local network you could add upnp/ssdp server to your broker and let the devices figure it out themselves. 
i will likely integrate this library in my broker https://github.com/Yortw/RSSDP 

as far as i know there isnt a standard that says a temperature sensor must support x topics with y payload to be compliant with MQTTstandard xxxx... but im using this lib just for devices our company builds so i can define how all our messages should look like.

**Comment by KarloX2** [comment]
Hi JanEggers!

Thanks, the IMqttClientRetainedMessageManager looks like something I could use. But it doesn't seem to be in the released version that I installed. Do I need to wait for the next update? When?

In the current version, there's already the MqttClientRetainedMessagesManager class. The reference to such an instance is public in MqttClientSessionsManager, however the reference to MqttClientSessionsManager is private in MqttServer.

Having a MqttServer reference in my hand, how (without reflection) could I get a reference to the IMqttClientRetainedMessageManager interface or the MqttClientRetainedMessagesManager  object?

Thanks,
Karlo

**Comment by chkr1011** [comment]
@KarloX2 This is only available in Version 2.5 which was released yesterday.

**Comment by KarloX2** [comment]
Ah, ok, very good.

I installed version 2.5 and I see the new interface. However without reflection I can't retrieve a reference to that interface from my MqttServer object, right?

Little confused by the naming of the IMqttClientRetainedMessageManager.GetSubscribedMessagesAsync method. Will it really return messages that someone subscribed for? Or is that rather a presumed intention of the caller, in which case it should rather be named GetMessagesAsync.

Thanks
Karlo

**Comment by KarloX2** [comment]
@JanEggers  suggested to add the timestamp to the Payload data.

I can't because I have no full control over the Payload data structures coming from the devices. So I need to apply the timestamp in the server. Ideally, there would be a DateTime field in the appropriate class (MqttApplicationMessage ?) becoming auto-assigned a UTC (!) timestamp on receiving such a message from a client. Also, I need to make the timestamps persistent and reload them in case of retaining messages. Would that be possible for the next version of the lib? Or is there a better way?

Thanks
Karlo

**Comment by chkr1011** [comment]
_GetSubscribedMessages_ means that all messages are returned which are matching the topic filter criteria. The is only a internal class and I recommend not using it directly because its implementation can change in every next version. You can also have a look at the _ApplicationMessageReceived_ event and store the data on your own.

Changing the _MqttApplicationMessage_ and adding properties is not an option because it is not allowed by the protocol. Please have a look at the server Wiki. There is an example how to add the timestamp to a message. Beside from the payload there is no other chance.

**Comment by KarloX2** [comment]
@chkr1011 & @JanEggers !! Thanks for your very valuable comments !!

**Comment by chkr1011** [comment]
You`re welcome.
