### ISSUE TITLE
Tests/MQTTnet.TestApp.AspNetCore2

### ISSUE THREAD

**Issue by danielstock** [chkr1011/MQTTnet#925]
### Describe your question
which version of mqttnet.aspnetcore should i use in the project

![image](https://user-images.githubusercontent.com/35954809/81796225-b9266180-953f-11ea-9e6f-a48b8b10ecce.png)

failed to compile line:
app.UseConnections(c => c.MapMqtt("/mqtt"));

**Comment by danielstock** [comment]
i'm using 
ms.aspnetcore.app 2.2
ms.aspnetcore.razor.design 2.2
mqttnet.aspnetcore 3.0.2

**Comment by SeppPenner** [comment]
MapMqtt will not work, I guess. Follow the approach that is used in https://github.com/chkr1011/MQTTnet/blob/master/Tests/MQTTnet.TestApp.AspNetCore2/Program.cs.
