### ISSUE TITLE
MQTTnet 3.0.10  websocket incomplete data

### ISSUE THREAD

**Issue by pigwing** [chkr1011/MQTTnet#926]
### Describe the bug
when i upgrade server to 3.0.10. i am use mqtt.js for websocket mqtt client.but it unable to receive complete data

### bug related to

- MQTTnet Server
- MQTTnet.AspNetCore

1. upgrade 3.0.10 this version of MQTTnet server.
2. websocket crash it unable to receive complete data.
3. 3.0.9 version is ok

### Screenshots
![1](https://raw.githubusercontent.com/AirleaderChina/trace/master/QQ%E6%88%AA%E5%9B%BE20200515164605.png)

![2](https://raw.githubusercontent.com/AirleaderChina/trace/master/QQ%E6%88%AA%E5%9B%BE20200515164816.png)

![3](https://raw.githubusercontent.com/AirleaderChina/trace/master/QQ%E6%88%AA%E5%9B%BE20200515175200.png)

![4](https://raw.githubusercontent.com/AirleaderChina/trace/master/QQ%E6%88%AA%E5%9B%BE20200515175209.png)

**Comment by OomJan** [comment]
Have the same problem using WebSockets (Remote host closed the connection) but with the client. In v3.0.9 this works fine, in 3.0.10 it does not.

**Comment by pigwing** [comment]
@OomJan same to you, i have WebSockets (Remote host closed the connection)  and more

**Comment by chkr1011** [comment]
@JanEggers Could you please have a look? Maybe I broke something accidentally...

**Comment by chkr1011** [comment]
@pigwing @OomJan Do you have some more information about the environment? I tried the client and connected with _broker.mqttdashboard.com:8000/mqtt_ without issues when using web socket connection. I also tried to connect with a local running standalone _MQTTnet.Server_ which also works fine with web socket transport layer.

**Comment by chkr1011** [comment]
@pigwing Or do you use the standalone _MQTTnet.Server_?

**Comment by pigwing** [comment]
@chkr1011 i am use MQTTnet.AspNetCore

**Comment by pigwing** [comment]
@chkr1011 problems still exist in MQTTnet.AspNetCore

**Comment by pigwing** [comment]
@chkr1011 in MQTTnet.AspNetCore the method UseMqttEndpoint is obsolete, and you fix MQTTnet.Server like it

**Comment by pigwing** [comment]
@chkr1011 hi, i have found the problem, it is in subscribe behavior, when i have many subscribe topic, the problem in 

`for(var i=0;i<1000;i++){mqtt_client.subscribe(i.toString(), { qos: 0 });}`

but i change to array param  

`var array = []; for(var i=0;i<1000;i++){array.push(i.toString());mqtt_client.subscribe(array, { qos: 0 });};`

it is ok

**Comment by pigwing** [comment]
when i have many subscribe topic, it will easy to trigger this problem

**Comment by OomJan** [comment]
MQTTnet 3.0.11 solves the problem for me.

**Comment by SeppPenner** [comment]
@pigwing Is this solved for you as well (in 3.0.11)?

**Comment by pigwing** [comment]
@SeppPenner no,in 3.0.12-rc1 solved

**Comment by SeppPenner** [comment]
Ok, that's good :) So we can close this issue? I don't know when the next release will come, to be honest.
