### ISSUE TITLE
TestParallelWrites failing

### ISSUE THREAD

**Issue by chkr1011** [chkr1011/MQTTnet#932]
@JanEggers I saw that the Unit Test "TestParallelWrites" fails from time to time when being executed 20 times in a row (sometimes more sometimes less). I don't think that it is related to my latest change (replacing the semaphore with async lock). 

The errors usually indicate that the buffer length management  is broken.

```
 TestParallelWrites
   Source: MqttConnectionContextTest.cs line 40
   Duration: 87 ms

  Message: 
    Test method MQTTnet.AspNetCore.Tests.MqttConnectionContextTest.TestParallelWrites threw exception: 
    System.ArgumentOutOfRangeException: Number was less than the array's lower bound in the first dimension. (Parameter 'destinationIndex')
  Stack Trace: 
    Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
    Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
    MqttPacketWriter.Write(Byte[] buffer, Int32 offset, Int32 count) line 140
    MqttPacketWriter.Write(ArraySegment`1 buffer) line 196
    MqttPacketWriter.WriteVariableLengthInteger(UInt32 value) line 82
    MqttV310PacketFormatter.Encode(MqttBasePacket packet) line 47
    MqttPacketFormatterAdapter.Encode(MqttBasePacket packet) line 51
    MqttConnectionContext.SendPacketAsync(MqttBasePacket packet, TimeSpan timeout, CancellationToken cancellationToken) line 166
    <<TestParallelWrites>b__1>d.MoveNext() line 52
    --- End of stack trace from previous location where exception was thrown ---
    MqttConnectionContextTest.TestParallelWrites() line 56
    ThreadOperations.ExecuteWithAbortSafety(Action action)
```

Do you have any idea what is wrong?

**Comment by JanEggers** [comment]
I will have a look

**Comment by JanEggers** [comment]
i had alook on your latest changes why did you add back the pipelines dependency to mqttnet.aspnetcore? also why did you upgrade to connections 1.1 I specificly downgraded all dependencies as much as possible. if the chage was inteded pleas also update the nupkg accordingly otherwise we will have a mess in packaging again. I wonder if there is really any need for the nuspec at all or if all informations can be derived from csproj. (thats what i would prefere to avoid conflicts)

**Comment by chkr1011** [comment]
I had to add the pipelines because net core 3.1 does not have a ref to it (known issue in latest SDK) so adding it manually will solve building issues.

I will revert it as soon as a new .net core 3.1 SDK is available. 

Regarding the other things: I usually update all nugets from time to time. Unfortunately I forgot to update the nuspec. I will update this accordingly. Is there a way to "block" nuget updates? Otherwise it is hard to distinguish which update is "relevant" and which is not.

**Comment by JanEggers** [comment]
>  so adding it manually will solve building issues.

that is strange I was able to build when I removed it 2.1 to 3.1

> I will revert it as soon as a new .net core 3.1 SDK is available.

it is available since last december
https://dotnet.microsoft.com/download/dotnet-core/3.1

> Is there a way to "block" nuget updates?
I would say as long as it builds just dont update. Or change the "policy" to only support latest packages

**Comment by chkr1011** [comment]
I removed the reference and again I get the following errors:

![image](https://user-images.githubusercontent.com/6939810/82839973-5f278380-9ed1-11ea-8043-6a8c6a2e5eee.png)

I found some more information here: 
https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-312-sdk-31102-sdk

So I will add the reference again as long as this is not fixed by MS. If there is another way please let me know. Maybe you will get the same issue when upgrading the SDK?

I don't want to enforce latest packages only. I just update from time to time but I agree that we can stick to older versions as long everything works fine. I will revert the updates. But I will keep updating the nugets for the stand alone applications like MQTTnet.Server and the UWP test app.
