### ISSUE TITLE
Question regarding the session items in MqttApplicationMessageInterceptorContext

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#936]
### Describe your question
How can I set the session items in the MqttApplicationMessageInterceptorContext when publishing a new message / Is this even possible?

### Which project is your question related to?
- Server

### Example
![grafik](https://user-images.githubusercontent.com/9639361/83440419-36f5d280-a445-11ea-8629-51bc91ed548e.png)

I have the following issue: I built a cluster MQTT server system that synchronizes messages between multiple MQTT brokers. Works good so far. The only problem is that my brokers play "ping pong" whenever I publish a message from one broker to another.

E.g. **client 1** publishes a message with topic `a` and payload `b`. **broker 1** validates the message and publishes it (`AcceptPublish = true`). Afterwards, **broker 1** publishes the message to **broker 2**. **broker 2** receives the message and validates it again and publishes the message.

So far, everything is ok.

Afterwards, **broker 2** publishes the message back to **broker 1**. Why? Because both share the same code base (Grain system with Microsoft Orleans). So, the brokers play `ping pong`.

Solutions I have tried:
* Parsing the message to JSON object adding another field that indicates the publishing by the broker. Works, but broker 1 gets message `a`, broker 2 gets message `{ "Message: "a", "SentByBroker": true }`. I don't really like this... Plus, the application message cannnot be changed in the `MqttApplicationMessageInterceptorContext` callback, so this is not really helpful...
* Setting a value to `MqttApplicationMessageInterceptorContext.SessionItems` in the `MqttApplicationMessageInterceptorContext` callback. Doesn't work, the session items are not transfered within the publishing to **broker 2**.
* Setting another property I don't currently use, e.g. `MqttApplicationMessage.ContentType` or `MqttApplicationMessage.ResponseTopic` or something. Problem: Might have an impact on the server + Other users who want to use these properties cannot.
* Using the user properties: Only supported in MQTTv5 and I don't yet want to migrate...

Do you have any ideas on this @chkr1011 / @JanEggers?

My code is under https://github.com/SeppPenner/NetCoreMQTTExampleCluster/blob/master/src/NetCoreMQTTExampleCluster.Grains/MqttRepositoryGrain.cs, e.g. method `ProceedPublish`.

**Comment by JanEggers** [comment]
I would wrap each incoming message + topic in a new message and send that to an internal topic. /SYS/Broadcast/{BrokerId}. Each Cluster member can then Subscribe to /SYS/Broadcast/* and discard their own messages if the BrokerId matches.

broker1 and 2 have to know each other by some well defined cluster discovery like zookeeper or else

each broker subscribes to /SYS/Broadcast/*

client1 connects to broker1
client2 connects to broker2
client1 subscribes to "/World"
client2 publishes "hello" on "/World"
broker2 publishes {p: "hello", t: "/World" } on /SYS/Broadcast/broker2
broker2 ignores msg by matching 3rd topicsegment
broker1 publishes "hello" on /World 
client1 receives "hello" on /World 

problem solved?!

did you have a look on other broker implementations how they solve clustering?

**Comment by SeppPenner** [comment]
@JanEggers That could indeed work. I will try and let you know.

> did you have a look on other broker implementations how they solve clustering?

Not really, no. I want to solve the problem on my own first and fell over this issue, but your suggestion seems to be a good solution.

**Comment by SeppPenner** [comment]
@JanEggers I have thought about you suggestion.

This will cause the same issue: Everytime a broker publishes, the `ValidatePublish` method is called and will republish the message again.

E.g.

client1 connects to broker1
client2 connects to broker2
broker1 subscribes to `/$SYS/Broadcast/+`
broker2 subscribes to `/$SYS/Broadcast/+`
client1 publishes `a` to broker1 on `World`
broker1 publishes `a` to itself on `World` and `{p: "a", t: "/World" }` on `/$SYS/Broadcast/broker2`
broker2 gets subscription message, validates it and publishes a new message `a` to itself on `World`

Here, the problem occurs. broker2 still has the handler for `ValidatePublish` which will immediately publish / sync the sent message back to broker1 like this: `{p: "a", t: "/World" }` on `/$SYS/Broadcast/broker1`. It's called when broker2 publishes the message to itself...

Why? Because the broker doesn't know which message to publish and which not... (And both brokers share the same code base as they're run in virtual actors / grains). And that's what I meant with the `ping pong` example above 😄 

However, I now found a solution for this:
When broker1 publishes a synchronized message to broker2, it uses a specific user, called `mqtt-sync-user`. This user has a property set to true (e.g. IsSyncUser). All other users don't have this property set. With this information, each broker can distinguish whether the message is a sync message or not and whether the message should be synchronized or not.

Only drawbacks with this scenario:
* Another user is needed (I don't think that's a problem).
* Another column in the database is needed (I don't think that's a problem).
* The original publisher client id is lost on all synchronized brokers (Might be a problem, however, there's still the original one in the database as well. So not a big deal I would say).

I will update my code under https://github.com/SeppPenner/NetCoreMQTTExampleCluster soon.

**Comment by SeppPenner** [comment]
By the way, thank you for your idea 👍
