### ISSUE TITLE
Who can tell me the trigger method in the source code· client.UseApplicationMessageReceivedHandler ()

### ISSUE THREAD

**Issue by narojay** [chkr1011/MQTTnet#943]
I am a new user of mqttnet. I am looking at the source code of mqttnet. Who can tell me what method can trigger in the source code` client.UseApplicationMessageReceivedHandler ()`

**Comment by SeppPenner** [comment]
Basically, this should be the section in the wiki that covers the topic: https://github.com/chkr1011/MQTTnet/wiki/Client#consuming-messages.

So, as an example:

```csharp
var factory = new MqttFactory();
var mqttClient = factory.CreateMqttClient();
var options = new MqttClientOptionsBuilder()
    .WithTcpServer("broker.hivemq.com")
    .WithTls()
    .Build();

mqttClient.UseApplicationMessageReceivedHandler(e =>
{
    Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
    Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
    Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
    Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
    Console.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
    Console.WriteLine();
    Task.Run(() => mqttClient.PublishAsync("hello/world"));
});

await mqttClient.ConnectAsync(options, CancellationToken.None);
await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("my/topic").Build());
```

This code starts a MQTT client, connects to `broker.hivemq.com:1883`, subscribes to topic `my/topic` and has the handler method for incoming messages.

**Comment by SeppPenner** [comment]
So, as additional explanation.

1. Connect.
2. Subsribe to a topic.
3. Wait for someone else on the MQTT broker to publish a message to the subscribed topic.
4. Handle the data in the `UseApplicationMessageReceivedHandler` method.
