### ISSUE TITLE
Plug in custom implementation of IMqttServerApplicationMessageInterceptor

### ISSUE THREAD

**Issue by ovidiaconescu** [chkr1011/MQTTnet#947]
Hello, is it possible to plug in a custom implementation of `IMqttServerApplicationMessageInterceptor` via Dependency Injection?
The only example with this seems to be https://github.com/rafiulgits/IotHub

Ideally, something like this would work best
`services.AddScoped<IMqttServerApplicationMessageInterceptor, MessageInterceptor>();`

instead of

```
services
                .AddHostedMqttServer(
                        t => t.WithDefaultEndpointPort(1883)
                        .WithApplicationMessageInterceptor(new MessageInterceptor()))
                .AddMqttConnectionHandler()
                .AddConnections();
```

Scoped seems to be the most used lifecycle as it would work with Entity Framework Core DbCodex which is also Scoped by default. This way the Interceptor would be able to access the database to validate clients and store messages.

**Comment by scabana** [comment]
Hi, until this gets implemented, if you are in an asp.net core app: 

Change ```IMqttServerConnectionValidator``` for ```IMqttServerApplicationMessageInterceptor```

```c#
public class InitializableMqttServerConnectionValidator : IMqttServerConnectionValidator
{
    private IServiceProvider _serviceProvider;

    public void Init(IServiceProvider serviceProvider)
    {
        if (_serviceProvider != null)
        {
            throw new InvalidOperationException("Can't init a second time!");
        }

        _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
    }

    public async Task ValidateConnectionAsync(MqttConnectionValidatorContext context)
    {
        if (_serviceProvider == null)
        {
            throw new Exception("Can't validate if Init not called");
        }

        using IServiceScope scope = _serviceProvider.CreateScope();

        await scope.ServiceProvider.GetRequiredService<IMqttServerConnectionValidator>().ValidateConnectionAsync(context);
    }
}
```
And in ```ConfigureServices```: 
```c#
services.AddHostedMqttServer(t => t.WithDefaultEndpointPort(1883).WithConnectionValidator(new InitializableMqttServerConnectionValidator())
```
And in ```Configure```
```c#
app.UseMqttServer(server =>
{
    ((InitializableMqttServerConnectionValidator)server.Options.ConnectionValidator).Init(app.ApplicationServices);
});
```

But this is not how it should be implemented here. Ideally, the different services

**Comment by BrightSoul** [comment]
Yes please, I also need dependency injection for my custom application message interceptor. Right now I'm using this hack which is pretty ugly and produces a warning at compilation.

```
services.AddSingleton<IMqttServerApplicationMessageInterceptor, MyCustomApplicationMessageInterceptor>();
var serviceProvider = services.BuildServiceProvider();
var interceptorInstance = serviceProvider.GetService<IMqttServerApplicationMessageInterceptor>();
services
  .AddHostedMqttServer(mqttServer => {
    mqttServer.WithApplicationMessageInterceptor(interceptorInstance).WithoutDefaultEndpoint();
});
```
I second @ovidiaconescu's solution and this would also be ok, assuming it uses the dependency resolver to construct the application message interceptor.
```
services
  .AddHostedMqttServer(mqttServer => {
    mqttServer.WithApplicationMessageInterceptor<MyCustomApplicationMessageInterceptor>().WithoutDefaultEndpoint();
});
```

**Comment by avishnyak** [comment]
If you are using MQTTnet with AspNetCore, this library handles a similar use case https://github.com/Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting. It works with the built-in dependency injection in AspNetCore and allows you to treat your MessageInterceptors as controller actions.

Just wanted to makes sure you are aware of the option.

**Comment by BrightSoul** [comment]
> Just wanted to makes sure you are aware of the option.

@avishnyak I wasn't aware, thank you. It looks interesting so I'll definitely give it a look.
