### ISSUE TITLE
Can a MQTT client check whether another client is connected/alive?

### ISSUE THREAD

**Issue by KarloX2** [chkr1011/MQTTnet#95]
Hello Experts!

For a MQTT broker's client A, is it possible to verify whether another client B (a sensor device) is currently connected. Or - if not possible - can client A subscribe for a topic from client B and can A then distinguish whether the topic message from B (if delivered) is a last-will message or a regular "alive" message?

Thanks
Karlo

**Comment by chkr1011** [comment]
Hi,
you can build your own keep alive message system. Client A can publish something like "client-a/alive" every couple of seconds and another client can subscribe to it. But then client B requires some logic to determine whether client A is offline or online.

Another option is, as you already mentioned, the "will" message. You can specify the will message as something like "client-a/status" with payload "offline" and set the retain flag to true. Then every client will get that offline state after subscribing even if client-a is offline. After connecting client-a must set the retained message with topic "client-a" status to "online".

Best regards
Christian

**Comment by KarloX2** [comment]
Ok, I understand. Thanks!
