### ISSUE TITLE
Can the server know whether a message has been consumed by the client?

### ISSUE THREAD

**Issue by pengxiaobo123** [chkr1011/MQTTnet#950]
### Describe your question
Can the server know whether a message has been consumed by the client?

### Which project is your question related to?

- Client

- Server

For example, client a sends a message to client B. If the B client receives the message. Can the server know. If you know, what was it. I want to be able to make sure that client B receives the message

**Comment by SeppPenner** [comment]
If you use Quality of service level 2, than yes. https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/:

> QoS 2 is the highest level of service in MQTT. This level guarantees that each message is received only once by the intended recipients. QoS 2 is the safest and slowest quality of service level. The guarantee is provided by at least two request/response flows (a four-part handshake) between the sender and the receiver. The sender and receiver use the packet identifier of the original PUBLISH message to coordinate delivery of the message.

If you want to know from the view of client A whether client B has received the message, than you would need to implement a response from client B after a message from client A is received.

**Comment by chkr1011** [comment]
@SeppPenner Correct 😄
