### ISSUE TITLE
Question:can server  send the message is encoded by 'gb2312' ?

### ISSUE THREAD

**Issue by liugan123** [chkr1011/MQTTnet#956]
- Server
For example,client A subscribes to the topic X , then, sends a message is encoded by 'gb2312' to the server with topic X.The server can use 'gb2312' to encode the payload.But the message  client A received is unintelligible text.How to change the server's defaule code formats?

PS:i'm so sorry because my English is terible.
![QQ截图20200715093713](https://user-images.githubusercontent.com/54768754/87493199-d8945480-c67e-11ea-96ea-201521073845.png)
![QQ截图20200715093731](https://user-images.githubusercontent.com/54768754/87493206-ddf19f00-c67e-11ea-8a6e-a7c11c013326.png)

**Comment by meanshe** [comment]
@liugan123  
UTF-8 is used for string payload. It looks like your MQTTClient tool is not supported utf-8.
If the client is wroted by MQTTnet or wanna sending payload encoded by 'gb2312', you should send byte[] data and decode it by yourself.

**Comment by liugan123** [comment]
@meanshe Thank you for your answer.
