### ISSUE TITLE
Is there an estimated maximum number of clients?

### ISSUE THREAD

**Issue by SexyBuggy** [chkr1011/MQTTnet#957]
### Describe your question
I would like to use the Server (broker) part to manage a large number of MQTT clients. I know this depends on a variety of things but I would like to know a estimate so I could balance in various machines.

### Which project is your question related to?
- Server

**Comment by SeppPenner** [comment]
@JanEggers You did some tests I guess. Can you share the information here, please?

**Comment by JanEggers** [comment]
@SexyBuggy just measure :) create an app that simulates your payload and than put that in a docker container and then create new instances of that container until the broker breaks / hits performance issues

**Comment by chkr1011** [comment]
@SexyBuggy I aggree to @JanEggers. This is highly complicated and there are many factors involved (number of clients, messages per second, message size, RAM of server machine, CPU of server machine). So in the end you need to verify this on your own.
