### ISSUE TITLE
Makers of industry-grade MQTT-enabled sensor devices?

### ISSUE THREAD

**Issue by KarloX2** [chkr1011/MQTTnet#96]
Hello,

this is a bit OT, sorry.

Can someone point to companies that offer boxed and ready-to-run sensor devices (specifically measuring lightness and motion)?

Thanks!
Karlo

**Comment by chkr1011** [comment]
Hi,
already with MQTT support or in general?

One project I use is this: <https://github.com/arendst/Sonoff-Tasmota>

Best regards
Christian

**Comment by KarloX2** [comment]
Thanks interesting!

Did you ever see a lightness sensor based on that hardware platform? I want to detect whether ceiling lights are switched on/off (mostly indoor).

**Comment by chkr1011** [comment]
Usually I use ESP8266 (NodeMcu dev kit) with several sensors. Or do you need some without soldering etc.?

**Comment by KarloX2** [comment]
Yes, something boxed and ready to use would be great. I' not an electronic guy :)

**Comment by chkr1011** [comment]
Sorry but I don't know much ready to use sensors.

**Comment by KarloX2** [comment]
Thanks!
