### ISSUE TITLE
Hi, There is no callback function after the message is published successfully

### ISSUE THREAD

**Issue by liaoliaoda** [chkr1011/MQTTnet#962]
### Describe the feature request
Does the new release version have callback function (include success and fail ) when message is published like paho.java?

I have tested the PublishAsync function, the msg published success when the network connected normal, but there is no exception appear when I disconnect the network and publish the msg.  so I publish the msg cotinue and the exception(connection lost) appear after ten seconds later. so during about ten seconds, our msg is missing and I do not konw the details of the missing message. any solution about this?

Thanks very much

### Which project is your feature request related to?

- Client

**Comment by SeppPenner** [comment]
Possible duplicate of https://github.com/chkr1011/MQTTnet/issues/944.

**Comment by liaoliaoda** [comment]
ok, thanks for your reply, I hava solved this issue.
