### ISSUE TITLE
Release 3.0.12

### ISSUE THREAD

**Issue by Falco20019** [chkr1011/MQTTnet#963]
### Describe your question
When is the next release for 3.0.12 planned? I would need the reason code in disconnects, already implemented in [this commit](https://github.com/chkr1011/MQTTnet/commit/df149eb0b321410b80cc34de7e62d33eb4d7ffb8) but unreleased yet.

### Which project is your question related to?
- Client
- ManagedClient
- Generic

**Comment by chkr1011** [comment]
I will release a new RC today. If nothing urgent is reported I will release the version some days after.
