### ISSUE TITLE
Could not load type

### ISSUE THREAD

**Issue by MattComb** [chkr1011/MQTTnet#965]
I have upgraded to version 3.0.11 (from 2.8.5) and when running am getting the following message:

Could not load type 'MQTTnet.Diagnostics.IMqttNetChildLogger' from assembly 'MQTTnet, Version=3.0.11.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'.":"MQTTnet.Diagnostics.IMqttNetChildLogger"}

How can I resolve this ?

This relates to the projects

- MQTTnet.Server

**Comment by chkr1011** [comment]
This class is no longer available. But in the same namespaces are the new interfaces. Mostly they are just renamed. If you share specific code I can try to explain how to migrate.
