### ISSUE TITLE
Error after upgrade to v 2.5

### ISSUE THREAD

**Issue by ascazzola** [chkr1011/MQTTnet#97]
I updated from v 2.4 to v 2.5 and in the line 

var factory = new MqttFactory()

i have the error: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.

I deleted the bin folder and clean the solution and the error persists

**Comment by JanEggers** [comment]
dup of #93 we will release 2.5.1 soon
