### ISSUE TITLE
MQTTnet poor performance when multi-threaded despite same number of messages being sent

### ISSUE THREAD

**Issue by csmorley** [chkr1011/MQTTnet#971]
I am sending around 20,000 messages per second, these can be across a number of arbitary threads (the messages are processed before sending to MQTTnet).

I have found, that the fewer the threads the better the performance, going over 16 simultanous senders causes MQTTnet to grind to a halt even with 10k messages per second.

It is not the threads that are slow, I poll the MQTTnet Managed Client buffer size every 10 seconds and see it increasing to the point where it becomes full (at the limit that I have set).

This is with the most recent code version and something I noticed a number of months ago (from today August 2020) - it was highlighted with my recent ThreadRipper system upgrade and my code creating number of threads equal to the number of Environment Processors - same code base but 8 with previous hardware with 48 on new hardware caused the "failure".

48 decode/send threads caused MQTTnet to grind to a halt, whereas 4 to 8 threads was OK and performant. I can see the speed on the NIC to the MQTT server drop from 8Mbps (with 4 to 8 sending threads) to less than 100kbps when higher thread counts are used.

Local or remote MQTT server makes no difference - as mentioned I can see the send buffer within MQTT increase and will do so until memory exhaustion unless a limit is set (either way, it will drop messages once under duress from threads and in this state).

Note, in both cases, the total number of messages being sent per second remained the same - the only variable was the number of worker threads the messages were being sent from.

Is this a bug, or something I am doing wrong? Should i create my own queue to front-end the managed client and dispatch one at a time (i don't want to reinvent the wheel, but want to ensure i am using the library correctly).

I am using Windows 10.

**Possible solution**

I have found this seems to be related to debug and start without debugs - starting without debug is magnitudes faster and can scale all the way to 48 threads (as per the environment processor count) without any issue when started without debug without any queuing whatsoever.

Strange, as the message volume is the same in both cases, only difference being the thread count as mentioned (and even with debug and 8 threads, debug can keep up without issue).

Seems there is an overhead when debugging with multiple sending threads - which may be obvious but couldn't find where this was warned.

**Comment by jimsch** [comment]
Are you doing any creation/exiting of threads or once created does the thread always exist?  All thread creation/exit events are going to get sent to the debugger.

**Comment by csmorley** [comment]
Hi Jim, no the worker threads always exist, each worker thread however does
have a loop where is calls tasks to dispatch. I will do some digging around
that code good call thank you.

The only thing that's nagging me as mentioned it seems to dispatch OK at
full speed regardless of debug or not, it is the buffer within the managed
mqtt client class that during debug increases as the writes are made when
there is a higher number of workers writing at the same time (but only in
debug).

**Comment by csmorley** [comment]
@jimsch I can confirm there are no tasks within threads:

```
foreach (var quote in data.Quotes)
   await PublishSymbol(quote, MessageType.SymbolOnly, stoppingToken);

foreach (var trade in data.Trades)
   await PublishSymbol(trade, MessageType.SymbolOnly, stoppingToken);
```

Is the only thing each worker thread (which is persistent for the app duration spinning in a consumer loop) is calling in a loop when it decodes a packet from an external system... the PublishSymbol then goes on to call:

```
var message = new MqttApplicationMessageBuilder()
			.WithTopic(topic)
			.WithPayload(data)
			.Build();

message.ContentType = contentType;
message.QualityOfServiceLevel = qos.ToMqttQos();

await this.client.PublishAsync(message);
```
As mentioned the rate of dispatch to the above `this.client.PublishAsync()` method remains constant, it is the MQTTnet buffer that is increasing to the point where it gets full (if i set a limit, otherwise it grows unbounded) once it reaches a thread count that it doesn't like when debugging (seems to be around 10 to 16 workers sending the same amount of messages just split across more workers) which I get from polling once every second:

`this.client.PendingApplicationMessagesCount`

Thanks for writing an awesome library, the performance under release and starting without debugging is mind blowing, 100k+ messages i am getting. Would like to get to the bottom of above however as will catch other devs out.

**Comment by JanEggers** [comment]
> I have found this seems to be related to debug and start without debugs - starting without debug is magnitudes faster and can scale all the way to 48 threads (as per the environment processor count) without any issue when started without debug without any queuing whatsoever.

as you discovered this is a debugger / visual studio problem. If you are looking at performance make sure to run in release mode and without debugger otherwise vs will slow things down painfully. Also you may want to disable console logging if you use it that can also slow things down extremely.

**Comment by chkr1011** [comment]
@SeppPenner Probably this is something we should add (or simply) copy to the wiki because I see more of those tickets which are related to "performance issues" but also having debugger attached, fully fledged logger enabled etc.

**Comment by SeppPenner** [comment]
I can add this to the tips and tricks and known issues section(s).

**Comment by SeppPenner** [comment]
This is now documented under https://github.com/chkr1011/MQTTnet/wiki/Tips-and-Tricks#performance-testing.
