### ISSUE TITLE
client_id.Equals(e.ClientId) == true ????

### ISSUE THREAD

**Issue by 12343954** [chkr1011/MQTTnet#980]
### Describe the bug
```
mqtt.UseApplicationMessageReceivedHandler(e =>
{
    try
    {
        string topic = e.ApplicationMessage.Topic;
        string payload = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);
        //e.ApplicationMessage.ConvertPayloadToString()
        //e.ClientId =? mqtt.client_id
        var isME = client_id.Equals(e.ClientId);// i can not understand this ,two clients id shoud not be equal here.
                                                // `isME` is always true, whe i use two client.exe to test.
                                                // why put the client_id into the payload? it's a huge waste.


            ...
```

**Comment by JanEggers** [comment]
1.Equals(1) == true ?? what are you configuring as clientids? with the provided info it is hard to tell what is wrong

**Comment by 12343954** [comment]
@JanEggers thank you for replying.
I startup two clients with different client_id.

![27-08-2020 09-57-09](https://user-images.githubusercontent.com/1804003/91374850-bb40d180-e84b-11ea-9050-78cd5d8cfa2c.png)

**Comment by JanEggers** [comment]
sorry I wasnt expecting this. but it seems this is acutually by design.

https://github.com/chkr1011/MQTTnet/blob/cf217034fa032153393e6f903762440f16b1a8ad/Source/MQTTnet/Client/MqttClient.cs#L710-L723

@chkr1011 can you explain why you added a ClientId to the eventargs that always is the local client?

**Comment by 12343954** [comment]
@JanEggers thank you for replying!
somewhere i see, chkr1011 said " client_id is designed for mqtt broker as client to connect other broker". server to server.
but i still don't understand why not bring the client_id on publishing.
https://github.com/chkr1011/MQTTnet/issues/916#issuecomment-625096767

**Comment by chkr1011** [comment]
@JanEggers The reason is that client and server are sharing the same interfaces when it comes to receiving and publishing. So I had to add something to the property (or leave it empty). Or add different interfaces but then you cannot use a generic "IApplicationMessageReceiver" etc.

**Comment by chkr1011** [comment]
I close this due to inactivity.
