### ISSUE TITLE
ManagedMqttClient is probably leaking memory through CancellationTokenSource

### ISSUE THREAD

**Issue by pluskal** [chkr1011/MQTTnet#984]
### Describe the bug
ManagedMqttClient is probably leaking memory.

According to [docs - cancellation-in-managed-threads](https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads?view=netframework-4.8) `CancellationTokenSource` used in class that implements `IDisposable` should be disposed.

E.g., [ManagedMqttClient.cs](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L40) do not disposes `cts` it holds.

### Which project is your bug related to?
ManagedClient

**Comment by chkr1011** [comment]
Hi it gets disposes in the _StopMaintainingConnection_ method. In the dispose method the client is stopped. So to me now memory leak. Do you have a memory leak?

**Comment by pluskal** [comment]
Ah, missed that. Thanks for the clarification!

No, memory leaks so far :)
