### ISSUE TITLE
TLS no certificates

### ISSUE THREAD

**Issue by 1iveowl** [chkr1011/MQTTnet#99]
.WithTls does not accept a null value for of certificate parameters. I.e. in the case where certificates are not used, but Tls is. 

Maybe [this line](https://github.com/chkr1011/MQTTnet/blob/eaf27c1e1268a9417d96fd4d8925969aaaf19fcb/MQTTnet.Core/Client/MqttClientOptionsBuilder.cs#L101) should be: `Certificates = certificates?.ToList()` instead?

Or something similar.

**Comment by chkr1011** [comment]
Thanks for sharing this issue. I fix this for version 2.5.1.
