### ISSUE TITLE
MqttClientSessionsManager should use lock

### ISSUE THREAD

**Issue by zhou881117** [chkr1011/MQTTnet#990]
log by ClientConnectedHandler ClientDisconnectedHandler ClientSubscribedTopicHandler：
Client connected 4194328.
Client connected 4194328.
Client connected 4194328.
Client disconnected 4194328.
Client disconnected 4194328.
Client Subscribed 4194328 **/devices/update/**/4194328.
info: Microsoft.Hosting.Lifetime[0]

the client can not receive subscribed topic

client is a rtos device，sometimes  subscribe  no effect when connected

**Comment by JanEggers** [comment]
can you create a test / proof of what is wrong? MqttClientSessionsManager is using concurrentdictionary so it should be good.

**Comment by zhou881117** [comment]
wait for a monent
i test 

first  the client device is reconnecting
second start the server 

at this monent, the device connected ,then subscribe the topic,most probable,subscibed not effect.

i will debug the  code.

**Comment by zhou881117** [comment]
mqttnet ver:3.0.8

bug Scene:
first：a rtos  device connecting to server  by a loop
second： start the  asp .net core 3.1 server 
result：the client can not receive subscribed topic

i solve it by a lock HashSet，code:
 public class Startup
    {
        private HashSet<string> clientIds = new HashSet<string>();

...
 public void ConfigureServices(IServiceCollection services)
...
var mqttServerOptions = new MqttServerOptionsBuilder().WithConnectionValidator(t =>
            {
                bool res = deviceManager.OnLogin(t.Username, t.Password, t.ClientId);               
                if (res)
                {
                    Console.WriteLine($"Authorized: ClientId: {t.ClientId}");
                    lock (clientIds)
                    {
                        if (clientIds.Contains(t.ClientId))
                        {
                            t.ReasonCode = MQTTnet.Protocol.MqttConnectReasonCode.ServerUnavailable; //.NotAuthorized;
                        }
                        else
                        {
                            clientIds.Add(t.ClientId);
                            t.ReasonCode = MQTTnet.Protocol.MqttConnectReasonCode.Success; //.NotAuthorized;
                        }
                    }

                }
                else
                {
                    Console.WriteLine($"NotAuthorized: userName: {t.Username} password:{t.Password}");
                    t.ReasonCode = MQTTnet.Protocol.MqttConnectReasonCode.NotAuthorized;
                }
            });
...
   public void Configure(IApplicationBuilder app, IWebHostEnvironment env,
...
 server.ClientDisconnectedHandler = new MqttServerClientDisconnectedHandlerDelegate(e =>
                {
                    Console.WriteLine("Client disconnected {0}.", e.ClientId);
                    lock (clientIds)
                    { 
                        clientIds.Remove(e.ClientId); 
                    }
                });

**Comment by zhou881117** [comment]
add the hashset,the log is:

`info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:35001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:35000
Authorized: ClientId: 3211286
Authorized: ClientId: 3211286
Client connected 3211286.
Authorized: ClientId: 3211286
Client disconnected 3211286.
Client disconnected 3211286.
Client disconnected 3211286.
Authorized: ClientId: 3211286
Client connected 3211286.
Client Subscribed 3211286 devices/update/_tcp.local./3211286.`

**Comment by JanEggers** [comment]
i still dont get what is the issue here. why is the client establishing more than one connection at a time?

**Comment by zhou881117** [comment]
> i still dont get what is the issue here. why is the client establishing more than one connection at a time?

the rtos device connect to server, failed  or initiative to disconnect by some error ,
and use the same clientId reconnect

**Comment by JanEggers** [comment]
@chkr1011  hi christian i created a minimal repro for this issue in form of a unittest.

my expectation is that 9 out of 10 connections are closed and the last one is working correctly.

```csharp
        [TestMethod]
        public async Task Manage_Session_MaxParallel()
        {
            using (var testEnvironment = new TestEnvironment(TestContext))
            {
                testEnvironment.IgnoreClientLogErrors = true;
                var serverOptions = new MqttServerOptionsBuilder();
                await testEnvironment.StartServerAsync(serverOptions);

                var options = new MqttClientOptionsBuilder()
                    .WithClientId("1")
                    ;

                var clients = await Task.WhenAll(Enumerable.Range(0, 10)
                    .Select(i => TryConnect(testEnvironment, options)));

                var connectedClients = clients.Where(c => c?.IsConnected ?? false).ToList();

                Assert.AreEqual(1, connectedClients.Count);
            }
        }

        private async Task<IMqttClient> TryConnect(TestEnvironment testEnvironment, MqttClientOptionsBuilder options)
        {
            try
            {
                return await testEnvironment.ConnectClientAsync(options);
            }
            catch (System.Exception)
            {
                return null;
            }
        }
```

there are 2 issues here:

more than one client thinks it is connected

most of the clients run into a timeout instead of disconnect exception, this leads me to belive that the server is not properly closing invalid connections.

**Comment by zhou881117** [comment]
i use the  HashSet with the lock：
HashSet < string > clientIds = new HashSet < string > ();

the rtos device reconnect by 20ms interval.
the rtos device can receive topic in a keepAliveInterval, over the  interval, can not receive topic.

> the server is not properly closing invalid connections.

**Comment by JanEggers** [comment]
@zhou881117 I already created a pr that should improve threading behavior of MqttClientSessionsManager.

there where some problems that in case of a session takeover the old code removed the new connection instead of the old one.
Also the old connection was not properly closed which could lead to timeouts in the client.

you can have a look at #1004 if you can create a testcase that is still not working please share it so we can fix it

**Comment by zhou881117** [comment]
> @chkr1011 hi christian i created a minimal repro for this issue in form of a unittest.
> 
> my expectation is that 9 out of 10 connections are closed and the last one is working correctly.
> 
> ```cs
>         [TestMethod]
>         public async Task Manage_Session_MaxParallel()
>         {
>             using (var testEnvironment = new TestEnvironment(TestContext))
>             {
>                 testEnvironment.IgnoreClientLogErrors = true;
>                 var serverOptions = new MqttServerOptionsBuilder();
>                 await testEnvironment.StartServerAsync(serverOptions);
> 
>                 var options = new MqttClientOptionsBuilder()
>                     .WithClientId("1")
>                     ;
> 
>                 var clients = await Task.WhenAll(Enumerable.Range(0, 10)
>                     .Select(i => TryConnect(testEnvironment, options)));
> 
>                 var connectedClients = clients.Where(c => c?.IsConnected ?? false).ToList();
> 
>                 Assert.AreEqual(1, connectedClients.Count);
>             }
>         }
> 
>         private async Task<IMqttClient> TryConnect(TestEnvironment testEnvironment, MqttClientOptionsBuilder options)
>         {
>             try
>             {
>                 return await testEnvironment.ConnectClientAsync(options);
>             }
>             catch (System.Exception)
>             {
>                 return null;
>             }
>         }
> ```
> 
> there are 2 issues here:
> 
> more than one client thinks it is connected
> 
> most of the clients run into a timeout instead of disconnect exception, this leads me to belive that the server is not properly closing invalid connections.

i use you test case, new master ver： a26b641 
now is ok

**Comment by zhou881117** [comment]
[TestMethod]
        public async Task Manage_Session_MaxParallel_Subscribe()
        {
            using (var testEnvironment = new TestEnvironment())
            {
                testEnvironment.IgnoreClientLogErrors = true;
                var serverOptions = new MqttServerOptionsBuilder();
                await testEnvironment.StartServerAsync(serverOptions);

                var options = new MqttClientOptionsBuilder()
                    .WithClientId("1").WithKeepAlivePeriod(TimeSpan.FromSeconds(10));

                bool hasReceive = false;
                Action onReceive = () =>
                {
                    if (!hasReceive)
                    {
                        hasReceive = true;
                    }
                };

                var clients = await Task.WhenAll(Enumerable.Range(0, 25)
                    .Select(i => TryConnect_Subscribe(testEnvironment, options, onReceive)));

                var connectedClients = clients.Where(c => c?.IsConnected ?? false).ToList();

                //Assert.AreEqual(true, connectedClients.Count > 1);

                System.Threading.Thread.Sleep(20 * 1000); //over 1.5T
                var option2 = new MqttClientOptionsBuilder()
                    .WithClientId("2").WithKeepAlivePeriod(TimeSpan.FromSeconds(10));
                var sendClient = await testEnvironment.ConnectClientAsync(option2);
                await sendClient.PublishAsync("aaa", "1");
                System.Threading.Thread.Sleep(3000);
                Assert.AreEqual(true, hasReceive);
            }
        }

        private async Task<IMqttClient> TryConnect_Subscribe(TestEnvironment testEnvironment, MqttClientOptionsBuilder options, Action onReceive)
        {

            try
            {
                var sendClient = await testEnvironment.ConnectClientAsync(options);
                sendClient.ApplicationMessageReceivedHandler = new MQTTnet.Client.Receiving.MqttApplicationMessageReceivedHandlerDelegate(e =>
           {
               onReceive();
           });
                await sendClient.SubscribeAsync("aaa");
                return sendClient;
            }
            catch (System.Exception)
            {
                return null;
            }
        }

**Comment by zhou881117** [comment]
i create a test case to test subscribe when time over 1.5 keepAlive.
ver 3.0.8 ,some times is error
now the new master is ok

`[TestMethod]
        public async Task Manage_Session_MaxParallel_Subscribe()
        {
            using (var testEnvironment = new TestEnvironment())
            {
                testEnvironment.IgnoreClientLogErrors = true;
                var serverOptions = new MqttServerOptionsBuilder();
                await testEnvironment.StartServerAsync(serverOptions);

                var options = new MqttClientOptionsBuilder()
                    .WithClientId("1").WithKeepAlivePeriod(TimeSpan.FromSeconds(10));

                bool hasReceive = false;
                Action onReceive = () =>
                {
                    if (!hasReceive)
                    {
                        hasReceive = true;
                    }
                };

                var clients = await Task.WhenAll(Enumerable.Range(0, 25)
                    .Select(i => TryConnect_Subscribe(testEnvironment, options, onReceive)));

                var connectedClients = clients.Where(c => c?.IsConnected ?? false).ToList();

                //Assert.AreEqual(true, connectedClients.Count > 1);

                System.Threading.Thread.Sleep(20 * 1000); //over 1.5T
                var option2 = new MqttClientOptionsBuilder()
                    .WithClientId("2").WithKeepAlivePeriod(TimeSpan.FromSeconds(10));
                var sendClient = await testEnvironment.ConnectClientAsync(option2);
                await sendClient.PublishAsync("aaa", "1");
                System.Threading.Thread.Sleep(3000);
                Assert.AreEqual(true, hasReceive);
            }
        }

        private async Task<IMqttClient> TryConnect_Subscribe(TestEnvironment testEnvironment, MqttClientOptionsBuilder options, Action onReceive)
        {

            try
            {
                var sendClient = await testEnvironment.ConnectClientAsync(options);
                sendClient.ApplicationMessageReceivedHandler = new MQTTnet.Client.Receiving.MqttApplicationMessageReceivedHandlerDelegate(e =>
           {
               onReceive();
           });
                await sendClient.SubscribeAsync("aaa");
                return sendClient;
            }
            catch (System.Exception)
            {
                return null;
            }
        }`

**Comment by zhou881117** [comment]
test is ok.
tks!

**Comment by chkr1011** [comment]
@zhou881117 I assume this is done. So I close this ticket.
