### ISSUE TITLE
Large number of simultaneous clients on same machine behave erratically

### ISSUE THREAD

**Issue by srinivasrb** [chkr1011/MQTTnet#991]
When using ManagedClient to connect to a broker, when I attempt to launch a number of clients in parallel threads to connect to a broker simultaneously, then connect takes a long time, and some clients error out. The same code works well with M2MQTT. 
As an observation, about 300 connections were attempted. M2MQTT completed this within a couple of seconds, while MQTTNet took about 2+ minutes or so. Some times, I see a MQTTnet.Exceptions.MqttCommunicationTimedOutException as well.

Note: I need to return to the caller after connect succeeds, so I have the following:

				TaskCompletionSource src = new TaskCompletionSource<ConnectStatus>();
				client.StartAsync(options);
				src.Task.Wait();
				var connectStatus = src.Task.Result;

I call src.SetResult in the MqttClientConnectedEvent event and in ManagedProcessFailedEvent event, to indicate whether or not connection succeeded.

Any thoughts on why I am seeing this behavior, and how I can alleviate this?

**Comment by chkr1011** [comment]
Please try the normal and not managed client. The managed client has some overhead and spawns some tasks to do its work. If the same situation applies for the normal client please let me know.

**Comment by chkr1011** [comment]
@srinivasrb I assume this issue is solved now.
