### ISSUE TITLE
ManagedMqttRpcClient

### ISSUE THREAD

**Issue by bcmccracken** [chkr1011/MQTTnet#999]
### Describe the feature request
The Managed client extension and the Rpc extension are both very useful! But I'd like to be able to use them together.

### Which project is your feature request related to?

- Client

### Describe the solution you'd like
Either allow MqttRpcClient to take a ManagedMqttClient, or add another extension (ManagedMqttRpcClient)

### Describe alternatives you've considered
I currently have the managed client at the core of an app, and in order to use the Rpc extension I'd have to spin up another client, which is possible but not efficient.

### Additional context
Perhaps this is a fairly niche request, but the auto reconnect feature of the Managed client is so nice that it'd be lovely to be able to leverage for RPC uses.

**Comment by chkr1011** [comment]
This a good idea. I will expose the internal client at the Managed Client. Then you can pass the internal client to the RPC extension. But this should be used with caution because exposing the internal client also allows to do "bad" things which will break the managed client.

**Comment by chkr1011** [comment]
This feature is available in 3.0.13+.

**Comment by bcmccracken** [comment]
Thanks for adding this! Appreciate it
